### ISSUE TITLE
problem in crating dataset

### ISSUE THREAD

**Issue by Z-Rajaei** [pyg-team/pytorch_geometric#1002]
## ❓ Questions & Help

Hello, I am a newbie in Pytorch Geometric. I want to create my own dataset to do graph classification. I just started with one single 5 node graph. but the code creates a 4 node graph (one node and one edge less)
Here is my code:

import os
import os.path as osp
import shutil

import torch
from torch_geometric.data import InMemoryDataset, download_url, extract_zip
from torch_geometric.io import read_tu_data

class MyDB(InMemoryDataset):
    

    def __init__(self, root, transform=None, pre_transform=None,pre_filter=None,
                 use_node_attr=False, use_edge_attr=False):

        super(ModelDB, self).__init__(root, transform, pre_transform, pre_filter)
        
        
        self.data, self.slices = torch.load(self.processed_paths[0])
        
        print ('data', self.data, 'slice=',self.slices)
 
       
        
        if self.data.x is not None and not use_node_attr:
            num_node_attributes = self.num_node_attributes
            self.data.x = self.data.x[:, num_node_attributes:]
        if self.data.edge_attr is not None and not use_edge_attr:
            num_edge_attributes = self.num_edge_attributes
            self.data.edge_attr = self.data.edge_attr[:, num_edge_attributes:]

    @property
    def num_node_labels(self):
        print('numnodlabel')
        if self.data.x is None:
            return 0
        for i in range(self.data.x.size(1)):
            x = self.data.x[:, i:]
            if ((x == 0) | (x == 1)).all() and (x.sum(dim=1) == 1).all():
                return self.data.x.size(1) - i
        return 0

    @property
    def num_node_attributes(self):
        print('numnodattr')
        if self.data.x is None:
            return 0
        return self.data.x.size(1) - self.num_node_labels

    @property
    def num_edge_labels(self):
        print('numeglabel')
        if self.data.edge_attr is None:
            return 0
        for i in range(self.data.edge_attr.size(1)):
            if self.data.edge_attr[:, i:].sum() == self.data.edge_attr.size(0):
                return self.data.edge_attr.size(1) - i
        return 0

    @property
    def num_edge_attributes(self):
        print('numegattr')
        if self.data.edge_attr is None:
            return 0
        return self.data.edge_attr.size(1) - self.num_edge_labels

    @property
    def raw_file_names(self):
        print('rawfilename')
        names = ['A', 'graph_indicator', 'edge_labels', 'graph_labels', 'node_attributes', 'node_labels','edge_attributes']
        return ['MM_{}.txt'.format(name) for name in names]

    @property
    def processed_file_names(self):
        print('processedfilename')
        return ['data.pt']

    @property
    def raw_dir(self):
        return osp.join(self.root, 'raw')
    

    @property
    def processed_dir(self):
        name = 'processed'
        return osp.join(self.root, name)

    def process(self):
        print('process start')
        name='MM'
        self.data, self.slices = read_tu_data(self.raw_dir, name)

       
        if self.pre_filter is not None:

            data_list = [data for data in data_list if self.pre_filter(data)]

        if self.pre_transform is not None:
            data_list = [self.pre_transform(data) for data in data_list]
            
        torch.save((self.data, self.slices), self.processed_paths[0])

    

this is the dataset created:
dataset= Data(edge_attr=[8, 1], edge_index=[2, 8], x=[5, 1], y=[0])
1
('edge_attr', tensor([[21.],
        [22.],
        [23.],
        [24.],
        [51.],
        [27.],
        [28.],
        [29.]]))
('edge_index', tensor([[0, 0, 0, 0, 0, 2, 3, 4],
        [1, 2, 3, 4, 5, 0, 0, 0]]))
('x', tensor([[50.],
        [60.],
        [70.],
        [80.],
        [90.]]))
('y', tensor([], dtype=torch.int64))

And my files are:
MM_A
1, 2
1, 3
1, 4
1, 5
1, 6
2, 1
3, 1
4, 1
5, 1
6, 1

MM_edge_attributes.txt
21
22
23
24
25
26
27
28
29
30

MM_graph_indicator:
1
1
1
1
1
1

MM_graph_labels:
1

MM_node_attributes:
50
60
70
80
90
100

There's another problem too. I want to do graph classification, so MM_graph_labels is my target. but y is []

Help me please...

**Comment by rusty1s** [comment]
There seems to be a newline symbol missing in the end of all your files :)

**Comment by zr2358** [comment]
Oh, thanks for your reply.
Yes, I added a new line in the end of all files. Now I get this error:

    if data.y.size(0) == batch.size(0):

IndexError: dimension specified as 0 but tensor has no dimensions

Is my code right?

**Comment by rusty1s** [comment]
This seems weird, and it is hard for me to say what may cause this. In the end, the `TUDataset` parses the `TU` format. If this format is not correct, it will result in some weird behavior which is hard to track down. Why don't you just initialize your data without the `TU` format by passing in the respective tensors to `data`?

**Comment by zr2358** [comment]
Do you mean passing without preparing any raw files and just with coding?
I an going to add a lot of data to files later...
If you mean something else, I don't know how! :(

**Comment by rusty1s** [comment]
I mean that you can always create your own format, you do not need to rely on the tu format to construct a dataset. Here, it might be necessary to dig into the `io/tu.py` code to see where the error occurs.

**Comment by zr2358** [comment]
I guess the problem is with my MM_graph_labels file. I removed this file and the tensor created in the right way without any error. This file is my target label for graph classification. I dont know waht is the problem and how represent this file as the target class

**Comment by zr2358** [comment]
when I add my MM_graph_labels file, the error occurs!
Should I add something else to my code?
can anybody help me?

**Comment by rusty1s** [comment]
Can you try to manually read the labels file using `torch_geometric.io` and see what it outputs?
```
read_txt_array(path, sep=',', dtype=torch.long)
```
