### ISSUE TITLE
How to use get laplacian

### ISSUE THREAD

**Issue by minyoung-mia-Kim** [pyg-team/pytorch_geometric#1003]
## ❓ Questions & Help

Hi,

I tried to use get laplacian from PyG utils, but it causes an error from torch scatter. I also gave the  num_node paramater with gt.max()+1, but the error was the same.
With running Chebnet, there is no error like this. Is there any idea to call this function rightly?

Thank in advance!

/data_my/My_coma/main2.py in train(coma, train_loader, len_dataset, optimizer, device, ground_truth)
    238         out = coma(data)
    239         l1_loss = F.l1_loss(out.cuda(), gt.x.cuda())
--> 240         sloss = smoothLoss(out.cuda(), gt.edge_index.cuda())
    241 
    242         if loss_test == 'hybrid':

/data_my/My_coma/main2.py in smoothLoss(predicted, gt)
--> 230     return torch.dist(Utils.get_laplacian(gt, num_nodes=gt.size(0)),predicted)
    231 
    232 def train(coma, train_loader, len_dataset, optimizer, device, ground_truth):

/opt/conda/envs/py36/lib/python3.6/site-packages/torch_geometric/utils/get_laplacian.py in get_laplacian(edge_index, edge_weight, normalization, dtype, num_nodes)
     42 
     43     row, col = edge_index
---> 44     deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
     45 
     46     if normalization is None:

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index' in call to _th_scatter_add_
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch_scatter/scatter.py", line 40
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)

**Comment by rusty1s** [comment]
Convert your `edge_index` to type `torch.long` first.
