### ISSUE TITLE
torch-scatter installation error

### ISSUE THREAD

**Issue by yyHaker** [pyg-team/pytorch_geometric#1009]
## Environment

* OS: Linux 3.10.0
* Python version: 3.6.7
* PyTorch version: 1.2.0
* CUDA/cuDNN version: cuda10.0
* GCC version: gcc7.3.1
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip install
* Any other relevant information:

## Additional context
I use the following method to install PyTorch Geometric, 
$ pip install --verbose --no-cache-dir torch-scatter
$ pip install --verbose --no-cache-dir torch-sparse
$ pip install --verbose --no-cache-dir torch-cluster
$ pip install --verbose --no-cache-dir torch-spline-conv (optional)
$ pip install torch-geometric
but when I run ''pip install --verbose --no-cache-dir torch-scatter'', the following problems happens, what's wrong with the problem?

![image](https://user-images.githubusercontent.com/18585628/75981574-c14e9900-5f1f-11ea-9447-d1a3333af4bd.png)
![image](https://user-images.githubusercontent.com/18585628/75981656-e8a56600-5f1f-11ea-9321-334e78184ca9.png)
![image](https://user-images.githubusercontent.com/18585628/75981703-01ae1700-5f20-11ea-9be3-0b2c46b8283a.png)

**Comment by yyHaker** [comment]
Since the error log shows the gcc version is low, but my gcc version is gcc7.3.1, is higher than 4.8.5? What's wrong?
![image](https://user-images.githubusercontent.com/18585628/75982034-acbed080-5f20-11ea-9603-508207fe25d8.png)

**Comment by rusty1s** [comment]
You need PyTorch 1.4.0.
