### ISSUE TITLE
Learning a Graph

### ISSUE THREAD

**Issue by josephdunbar** [pyg-team/pytorch_geometric#1016]
## ❓ Questions & Help

I would like to add a layer in a network that learns the adjacency matrix. The error I am getting is:

RuntimeError: Invalid index in scatterAdd at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721

Below is my relevant code and the full traceback for the error. Please advise or help on how I can get this working.

________________________________________________________________________________
class myGraph(torch.nn.Module):
    def __init__(self, in_features, out_features, batch_features):
        super(myGraph, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.batch_features = batch_features
        self.weights = torch.nn.Parameter(torch.Tensor(batch_features, in_features, out_features))
        self.reset_parameters()
        
    def reset_parameters(self):
        torch.nn.init.kaiming_uniform_(self.weights, a=math.sqrt(5))
    
    def forward(self, input):
        output = input.matmul(self.weights)
        return output

class GCNNet(torch.nn.Module):
    def __init__(self):
        super(GCNNet, self).__init__()
        self.graph = myGraph(in_features=lookback,out_features=number_of_variables,batch_features=batch_size)
        self.conv1 = GCNConv(lookback,1)
        self.sigmoid = torch.nn.Sigmoid()
        
    def forward(self, data):
        
        x = data.x
        
        adjacency_weights = self.graph(x)
        adjacency_weights = self.sigmoid(adjacency_weights)
        
        num_digits = 0
        adjacency_weights = (adjacency_weights * 10**num_digits).round() / (10**num_digits)
        
        adjacency_list = []
        for i in range(0,number_of_variables):
            for j in range(0,number_of_variables):
                if (sum(adjacency_weights[:,i,j])>=1.0*batch_size/2) and ([i,j] not in adjacency_list):
                    adjacency_list.append([i,j])
        print(len(adjacency_list))
        
        for i in range(0,number_of_variables):
            adjacency_list = [x for x in adjacency_list if x[0] != x[1]]
        print(len(adjacency_list))
        
        edge_index = torch.tensor(adjacency_list,dtype=torch.long)
        edge_index = edge_index.t().contiguous()
        print(edge_index)
        
        x = self.conv1(x, edge_index)
        
        return x

model = GCNNet()
model = DataParallel(model, device_ids=[0])#,1])
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)
#criterion = torch.nn.MSELoss()
criterion = torch.nn.L1Loss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=0.0)

num_epochs = 20
epoch_losses = []
training_losses = []
testing_losses = []

for epoch in range(0,num_epochs): 
    
    model.train()
    epoch_losses = []
    training_losses = []
    testing_losses = []
    
    # Training
    for datalist in training_loader:
        optimizer.zero_grad()
        out = model(datalist)
        out = out.flatten()
        y = torch.cat([data.y for data in datalist],dim=0).to(device)
        loss = criterion(out,y)
        loss.backward()
        optimizer.step()
        epoch_losses.append(loss.item())
    
    # Loss for Training
    with torch.no_grad():
        model.eval()
        for datalist in training_loader:
            out = model(datalist)
            out = out.flatten()
            y = torch.cat([data.y for data in datalist],dim=0).to(device)
            loss = criterion(out,y)
            training_losses.append(loss.item())
    
    # Loss for Testing
    with torch.no_grad():
        model.eval()
        for datalist in testing_loader:
            out = model(datalist)
            out = out.flatten()
            y = torch.cat([data.y for data in datalist],dim=0).to(device)
            loss = criterion(out,y)
            testing_losses.append(loss.item())
    
    epoch_loss = np.mean(epoch_losses)
    training_loss = np.mean(training_losses)
    testing_loss = np.mean(testing_losses)
    
    epoch_losses.append(epoch_loss)
    training_losses.append(training_loss)
    testing_losses.append(testing_loss)
    
    print("Epoch = "+str(epoch)+" ; "+"Epoch Loss (MSE) = "+str(round(epoch_loss,5))+" ; "+"Training Loss (MSE) = "+str(round(training_loss,5))+" ; "+"Testing Loss (MSE) = "+str(round(testing_loss,5)))

________________________________________________________________________________
6767
6704
tensor([[  0,   0,   0,  ..., 102, 102, 102],
        [  4,   6,   8,  ...,  99, 100, 101]])

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-137-b5af0ffdce33> in <module>
     14     for datalist in training_loader:
     15         optimizer.zero_grad()
---> 16         out = model(datalist)
     17         out = out.flatten()
     18         y = torch.cat([data.y for data in datalist],dim=0).to(device)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py in forward(self, data_list)
     48         if not self.device_ids or len(self.device_ids) == 1:  # Fallback
     49             data = Batch.from_data_list(data_list).to(self.src_device)
---> 50             return self.module(data)
     51 
     52         for t in chain(self.module.parameters(), self.module.buffers()):

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

<ipython-input-135-e1900e0540e9> in forward(self, data)
     32         print(edge_index)
     33 
---> 34         x = self.conv1(x, edge_index)
     35 
     36         return x

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
     96             self.cached_num_edges = edge_index.size(1)
     97             edge_index, norm = self.norm(edge_index, x.size(0), edge_weight,
---> 98                                          self.improved, x.dtype)
     99             self.cached_result = edge_index, norm
    100 

~/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in norm(edge_index, num_nodes, edge_weight, improved, dtype)
     75 
     76         row, col = edge_index
---> 77         deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)
     78         deg_inv_sqrt = deg.pow(-0.5)
     79         deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0

~/anaconda3/lib/python3.7/site-packages/torch_scatter/add.py in scatter_add(src, index, dim, out, dim_size, fill_value)
     73     """
     74     src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
---> 75     return out.scatter_add_(dim, index, src)

RuntimeError: Invalid index in scatterAdd at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:721

**Comment by rusty1s** [comment]
This basically means that your edge indices do not match with the number of nodes specified in `x.size(0)`. You should ensure that `edge_index.max() < x.size(0)`.
