### ISSUE TITLE
Question about the implementation of GraphSAGE（SAGEConv）

### ISSUE THREAD

**Issue by ytc272098215** [pyg-team/pytorch_geometric#1022]
## ❓ Questions & Help

It seems that the implementation of GraphSAGE only contains mean pooling as an aggregator, while GraphSAGE has other widely-known variants, such as LSTM-based and GCN-based aggregator. 
Therefore, how can I change the mean aggregator to others? Is there any API that can help me, or where should I modify the code?

Looking forward to your reply. Thank you!

**Comment by rusty1s** [comment]
Yes, we only have an implementation for mean aggregation. Max aggregation should be also supported when changing `aggr` to `"max"`. For LSTM aggregation, we currently do not have a fast way to implement that, but I have plans to support that in the future.

**Comment by ytc272098215** [comment]
Thank you very much for the quick response! 
I have another question: Is there a fast way to support me implement the GCN-based aggregator?

**Comment by rusty1s** [comment]
What do you mean with GCN-based aggregator?

**Comment by ytc272098215** [comment]
Well, in the paper of GraphSage, I have seen they mentioned a variant named GraphSAGE-GCN, which is an "inductive version of Kipf et al’s semi-supervised GCN [17], we term this variant GraphSAGE-GCN". I think it might be different from the original Kipf’s GCN.

**Comment by rusty1s** [comment]
Well, that is just GraphSAGE without concatenation of central node features, right?

**Comment by ytc272098215** [comment]
Ah, yes, I got it, So I just need to set the parameter "concat" as False for gcn-based and True for mean or max pooling, am I right?

**Comment by rusty1s** [comment]
That's how I understand the GraphSAGE paper :)

**Comment by ytc272098215** [comment]
You help me a lot! Thank you ~~~~ : )
