### ISSUE TITLE
mapping my string values to float

### ISSUE THREAD

**Issue by Z-Rajaei** [pyg-team/pytorch_geometric#1028]
## ❓ Questions & Help

Hello, I want to create my own dataset. I have string values for my node_attributes (e.g. John, Mary, May, ...), and I want to map them to a float value to store in my *_node_attribute.txt file as my input raw file.

I searched and tried different ideas, but no avail!!

**Comment by rusty1s** [comment]
You need to do this manually. PyG only excepts numerical values. You can, e.g., iterate over all words and assign them integers by using dictionaries, or you can make use of, e.g., Word2Vec embeddings.

**Comment by zr2358** [comment]
Yes, I want to use dictionaries but I don't know how. Can you please share me a link to know which dictionary I can use and how?
I want to know which number I should write for the word "Master", for example.

**Comment by rusty1s** [comment]
Well, if you have an array of all words, you can simply do something like the following:
```python
word2int = {}
i = 0
for word in words:
    if word not in word2int:
        word2int[word] = i
        i++
```
For getting feature vectors out of this:
```python
x = []
for word in words:
     x.append(word2int[word])
x = torch.tensor(x)
x = torch.nn.functional.one_hot(x, len(word2int.keys())
```

**Comment by zr2358** [comment]
Thank you, I coded in the following way:

words=['high','class', 'master', 'five', 'john', 'may','mary', 'linda','flat']
word2int = {}
i = 0
for word in words:
    if word not in word2int:
        word2int[word] = i
        i+=1
        
        
x = []
for word in words:
     x.append(word2int[word])
x = torch.tensor(x)
x = torch.nn.functional.one_hot(x, len(word2int.keys()))

print(x)

but the output is just a diagonal array of 1's!!

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1]])

**Comment by rusty1s** [comment]
Sure it is if words only occur once. What else should it be?

**Comment by zr2358** [comment]
I want to write the integer or float value of each attribute in the corresponding position of each row, not just 1 or 0 for its existence or not existence. 

for example I have 3attributes: name, color, size.

node 1: name: glue , color= black, with no size attribute
node 2: name: flat, no color, size= 20
node 3: name: skin, color= white, size = 10

I want to write the value of each node in each row of my file in integer or float.
for example:
0.2563, 0.2651, 0
0.5213, 0, 20.0
0.4151, 0.1656, 10.0

I don't know if it works or not.
If I'm making mistake, tell me the right solution.

**Comment by rusty1s** [comment]
Where does the values like `0.2563` should come from?

**Comment by zr2358** [comment]
I don't know. It is just an example. I want to know if we can map our string values to a value like that?
If the value of attributes are important to determine the target class, how can I define them in my attribute_nodes file?


for example the first row of ENZYMES_node_attributes.txt file of ENZYMES dataset is as the following:
11.000000, 15.887014, 37.780000, -0.510000,  1.701000, 93.900000,  4.000000,  5.000000,  2.000000,  4.000000,  4.000000,  3.000000,  3.000000,  4.000000,  4.000000,  3.000000,  6.000000,  2.000000
 
where does these numbers come from?

**Comment by rusty1s** [comment]
Well, I cannot tell you what that value should be like. It is your task to create meaningful features for a specific task (feature engineering). For your specific example, it seems to be best to encode each word as a one-hot vector (denoting its existence) - just like we did a few comments above.
