### ISSUE TITLE
Example GNN that operates on graph node and edge features

### ISSUE THREAD

**Issue by AzzamRH** [pyg-team/pytorch_geometric#1037]
## ❓ Questions & Help

Is there any implemented example where the graph neural network operates on both the features of the nodes and the features of the edges? 

Also, is it possible to develop a convolutional layer equivalent to the objective function of an optimization problem that operates on the graph?

Thank you so much

**Comment by rusty1s** [comment]
We have some examples, *e.g.*, `SplineConv` examples on MNIST and FAUST, or the QM9 example that also uses bond features of edges.
