### ISSUE TITLE
pip install torch-scatter invalid syntax

### ISSUE THREAD

**Issue by irfantakmil** [pyg-team/pytorch_geometric#1041]
## 📚 Installation
Collecting torch-scatter
  Using cached torch_scatter-2.0.2.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: //anaconda2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vz/wpgxbsr16tl99gtpfprn16lc0000gn/T/pip-install-MtojUB/torch-scatter/setup.py'"'"'; __file__='"'"'/private/var/folders/vz/wpgxbsr16tl99gtpfprn16lc0000gn/T/pip-install-MtojUB/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vz/wpgxbsr16tl99gtpfprn16lc0000gn/T/pip-install-MtojUB/torch-scatter/pip-egg-info
         cwd: /private/var/folders/vz/wpgxbsr16tl99gtpfprn16lc0000gn/T/pip-install-MtojUB/torch-scatter/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vz/wpgxbsr16tl99gtpfprn16lc0000gn/T/pip-install-MtojUB/torch-scatter/setup.py", line 47
        sources = [main, osp.join(extensions_dir, 'cpu', f'{name}_cpu.cpp')]
                                                                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
## Environment

* OS: Mac OS X Mojave 10.14.6
* Python version: 3.8.2
* PyTorch version: 1.4.0
* CUDA/cuDNN version:
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
Since we make use of the new formatted string syntax, you need to upgrade to Python > 3.5

**Comment by irfantakmil** [comment]
i already upgrade python to 3.8 but when i use the python --version it says 2.7 and when i use python3 --version it says 3.8. Then i found out that mac os comes with the default python 2.7.

**Comment by ayungavis** [comment]
> i already upgrade python to 3.8 but when i use the python --version it says 2.7 and when i use python3 --version it says 3.8. Then i found out that mac os comes with the default python 2.7.

I think you need to switch the default version of python on your mac, you can follow this instruction (https://opensource.com/article/19/5/python-3-default-mac). Or the best practice is only use one python version (3.x or 2.x), it's up to you according to your development needs
