### ISSUE TITLE
Managing common node IDs amongst various graphs

### ISSUE THREAD

**Issue by legohyl** [pyg-team/pytorch_geometric#1055]
## ❓ Questions & Help
Hi there, I need a bit of suggestion on how to manage Data object for various graphs from networkx. The setup is like this:

1. I have a bipartite graph, that is originally connected together. Suppose they are labelled from the range of IDs via [0, y], where range [0, x] form one set, P, and [x+1, y] form another set, D.
2. I am constructing 2 other graphs as well, one on set P, and one on set D.
3. In a graph set P, I am adding in a set of fake nodes, let's call them fake_P. So now set P is made up for {real_P, fake_P}, where the IDs of fake_P start from y+1 onwards. Likewise, set D has some fake nodes as well, called fake_D.
4. In totality, my new bipartite graph can be seen as connecting P', where P' is the set of {real_P, fake_P}, to D', where D' is the set of {real_D, fake_D}. I have segregated them this way as real_P has real feature nodes, while fake_P has fake (and learnable) feature nodes (e.g. embeddings).
5. Both P' and D' graphs have their node IDs the same as they are in the bipartite graph. But now that I'm looking at this problem a bit deeper, once you separate the graphs out, if I build a separate model on them, the torch tensors have no notion of ID (at least I think so?). Hence D'[0] won't understand that its ID is actually x+1.

Effectively, the bipartite graph's node list is something like this: [real_p, real_d, fake_p, fake_d].
While for P' own graph, it's node list is: [real_p, fake_p], and for D' own graph, it's node list is: [real_d, fake_d]. So, doing any graph model on just P' and D' will give us some node representations. I'd like to take these node representations to then be learnt in the bipartite graph's adjacency list.

My question then is how do we keep track of the node IDs, going from the graph D' to the bipartite graph? This is because in the bipartite graph, we have node IDs where the IDs of D don't start from 0. But in its own graph of D', its IDs start from 0 (at least according to if I use torch_geomtric.utils.from_networkx).

**Comment by rusty1s** [comment]
Interesting question. What about you save the node ids as an additional tensor to the `data` object, *e.g.*, `data.node_idx = torch.tensor([0, 1, 2, ...])`, and then use these node indices to form your `[real_p, real_d, fake_p, fake_d]` tensor?

**Comment by legohyl** [comment]
hey there, so I figured a strategy to track this. What I've done is use `nx.relabel.relabel_nodes`, and I generated a running index for it. E.g. For the d-graph, I'll have `{real_d: 0, real_d+1: 1, ... , fake_d: x, fake_d+1: x+1, ...}`. So I manually re-index the graph this way. 

When I need to recombine the feature matrix for the large bipartite graph, I can just stack the features back according to their keys, where `bipartite_graph[d_graph.keys()] = d_graph`. I'd like to confirm that all pytorch_geometric would need is that the node features are stacked correctly, and the edge_index will handle their connections.

**Comment by legohyl** [comment]
Just to follow up on this, I managed to settle tracking the keys. But I was trying to use the `from_networkx` function. Referring to my previous example, if i add `fake_p` and `fake_d`, I connect them to `real_p` and `real_d`. It seems like this causes the number of edges to explode. Hence, when I convert them to `Data` objects, the `from_networkx` function loops through the edge features and I have something like 400k edges. This becomes really slow quickly, was wondering if there's any faster way to stack the tensors from a networkx graph.

**Comment by raeidsaqur** [comment]
> hey there, so I figured a strategy to track this. What I've done is use `nx.relabel.relabel_nodes`, and I generated a running index for it. E.g. For the d-graph, I'll have `{real_d: 0, real_d+1: 1, ... , fake_d: x, fake_d+1: x+1, ...}`. So I manually re-index the graph this way.
> 
> When I need to recombine the feature matrix for the large bipartite graph, I can just stack the features back according to their keys, where `bipartite_graph[d_graph.keys()] = d_graph`. I'd like to confirm that all pytorch_geometric would need is that the node features are stacked correctly, and the edge_index will handle their connections.

@legohyl can't you just do a compose/union of the sets with `rename` and add a type prefix? Let networkx do the stacking, which should keep the ordering. For e.g., for a bi-partite graph (Gs, Gt):

```
G_union = nx.union(Gs, Gt, rename=('Gs-', 'Gt-'))  # Rename to avoid node name collisions
left_part = list(filter(lambda n: 'Gs-' in n, G_union.nodes()))
left_part, right_part = nx.bipartite.sets(G_union, left_part)
```
