### ISSUE TITLE
Power of A, for example A^2 or A^3.

### ISSUE THREAD

**Issue by JJJTF** [pyg-team/pytorch_geometric#1056]
## ❓ Questions & Help

The code is all edge_index for message passing (eg. Convolution), not using adj, if I want to use A^2 during message passing, what should I do? But edge_index cannot be calculated directly. Thank you very much!

**Comment by rusty1s** [comment]
You can pre-process your `edge_index` to contain the indices of `A^2`. If you directly want to apply that inside a message-passing layer, have a look at the `torch_sparse.spspmm` functionality.

**Comment by JJJTF** [comment]
Thank you very much for your reply. I'll have a try.
