### ISSUE TITLE
cannot import name 'SparseTensor'

### ISSUE THREAD

**Issue by Yfhu1103** [pyg-team/pytorch_geometric#1057]
## ❓ Questions & Help

Hello, I have successfully installed torch_sparse, but when I try to run /examples/cluster_gcn.py, I found "Import Error: cannot import name 'SparseTensor'",  did I used a wrong version of torch_sparse?

**Comment by rusty1s** [comment]
Yes, you have an older version installed. Try to remove *all* previous `torch-sparse` installations and try again.

**Comment by Mrslock** [comment]
Thanks for your quick reply, I'll have a try!
