### ISSUE TITLE
How can I implement A times X？

### ISSUE THREAD

**Issue by ColdenChan** [pyg-team/pytorch_geometric#1059]
where A is the adjacency matrix of the graph, and X is the node feature matrix. Thank you.

**Comment by rusty1s** [comment]
You can either (1) use `MessagePassing` for this, (2) use `torch_sparse.spmm`, or (3) convert `edge_index` to a `torch.sparse_coo_tensor` and use PyTorch sparse matrix multiplication.

**Comment by SourceCode1037** [comment]
> You can either (1) use `MessagePassing` for this, (2) use `torch_sparse.spmm`, or (3) convert `edge_index` to a `torch.sparse_coo_tensor` and use PyTorch sparse matrix multiplication.

Could you give some example code to implement A times X?

**Comment by rusty1s** [comment]
Sure:
```python
from torch_sparse import SparseTensor

A = SparseTensor.from_dense(torch.randn(100, 100))
X = torch.randn(100, 32)

out = A @ X
```
