### ISSUE TITLE
avg_pool_x  batch?

### ISSUE THREAD

**Issue by Jeevi10** [pyg-team/pytorch_geometric#1061]
## ❓ Questions & Help
 c = torch.LongTensor(range(0, h1.shape[0])).cuda()
        ba=torch.LongTensor([0])
        h1= avg_pool_x(c,h1,ba)

error
   h1= avg_pool_x(c,h1,ba)
  File "/home/jeev/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/pool/avg_pool.py", line 35, in avg_pool_x
    batch = pool_batch(perm, batch)
  File "/home/jeev/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/pool/pool.py", line 17, in pool_batch
    return batch[perm]
IndexError: index 1 is out of bounds for dimension 0 with size 1

I was trying average pooling over nodes. I have 15362 nodes. From that I have only 7674 node have labels and rest of them aren't having any labels. I want to reduce the number of node at the last layer to 7674 before classification. I have one single graph. I don't really understand the batch notion here.

Thank you in advance

**Comment by rusty1s** [comment]
That is the wrong function. If you just want to select the nodes that have labels, simply do something like this:
```
mask = which node holds a label?
x = x[mask]
```

**Comment by Jeevi10** [comment]
thank you, I have tried this solution(it works), but I want pool before I do classification(I want to compare the results). 
What if i want to pool my graph instead. I have three different graphs stacked for prediction. in last layer I have 3 x num of nodes x F(feature dimension at last layer)
I want to pool across node dimension to reduce number of nodes by average pooling, so 
I can have better representation for classification nodes?

**Comment by rusty1s** [comment]
If you want to pool your graph, you can make use of `torch_geometric.utils.subgraph`.
