### ISSUE TITLE
Shapenet features

### ISSUE THREAD

**Issue by mkumaszka** [pyg-team/pytorch_geometric#1065]
## ❓ Questions & Help

Hi,
I have a quick question about ShapeNet data - couldn't find answer anywhere.
I would like to plot examples as point cloud - to do so I need x, y, z coordinates. Are they values of data.x from imported ShapeNet dataset?

**Comment by rusty1s** [comment]
They are saved in `data.pos`.

**Comment by mkumaszka** [comment]
Thank you a lot for answer!

**Comment by Flawless1202** [comment]
> They are saved in `data.pos`, `data.x` contains the normals for each point.

Hi, @rusty1s , I find the `data.x` is provided by the raw ShapeNet Dataset, from colum 3 to 5. I'm not sure what is the `data.x` mean and how to calculate this value. Could you help me? Thx a lot!

**Comment by tchaton** [comment]
Hey @mkumaszka @Flawless1202  

Have a look at https://github.com/nicolas-chaulet/torch-points3d.

We have plenty of visualisations 👍 

Best regards,
Thomas Chaton.

**Comment by rusty1s** [comment]
The ShapeNet dataset also provides normal vectors for each point, so for any given point `data.pos[i]`, `data.x[i]` refers to its normal vector. We do not calculate that value, it's provided by the raw dataset to ease the learning task.

**Comment by Flawless1202** [comment]
> The ShapeNet dataset also provides normal vectors for each point, so for any given point `data.pos[i]`, `data.x[i]` refers to its normal vector. We do not calculate that value, it's provided by the raw dataset to ease the learning task.

Thx a lot!
