### ISSUE TITLE
Pytorch dataloader along with Geometric dataloader

### ISSUE THREAD

**Issue by gkv91** [pyg-team/pytorch_geometric#1069]
## ❓ Questions & Help

Hi, 
How can I use pytorch dataloader along with the geometric dataloader. Is there a way to use the Pytorch dataloader in geometric.? 
Also, how can I use GAT with minibatch support?.
Thanks

**Comment by rusty1s** [comment]
Yes, you can do this. Internally, we just override the `collate_fn` of the regular PyTorch DataLoader. Here, our `collate_fn` expects a list of data objects that get merged together. You can just create your own, *e.g.*, for examples holding a data object and a tensor as a tuple:
```python
def collate(list_of_examples):
    data_list = [x[0] for x in list_of_examples]
    tensors = [x[1] for x in list_of_examples]
    return Batch.from_data_list(data_list), torch.stack(tensors, dim=0)
```

**Comment by gkv91** [comment]
Thanks for your fast and kind reply. I would like to use PyG GAT in some part of my Pytorch code, and I don't want to change the data loader (because changing the data loader may affect other parts of the program). Since the current PyG GAT does not support batched inputs, I cannot use the same mini-batched data as input to it. Any thoughts in this regard?
Thanks

**Comment by rusty1s** [comment]
What do you mean it does not support mini-batches? All message passing operators support mini-batching by merging a set of graphs into a large single graph with disconnected components.

**Comment by gkv91** [comment]
Do you mean to stack the adjacency matrices?. E.g., if I have a batch of node feature tensor of dimension, 8x7x512 (Batch size x Num nodes x Feature dimension), convert it to 56x512?. Similarly, the adjacency matrices too?

**Comment by rusty1s** [comment]
Yes :)
