### ISSUE TITLE
No module named 'torch_geometric.data.GraphSAINTRandomWalkSampler'

### ISSUE THREAD

**Issue by Elizabeth1997** [pyg-team/pytorch_geometric#1081]
## ❓ Questions & Help

Hi, hope you are doing well. After I install the newest version of torch_geometric (1.4.3), no module error occurs when I tried to `import GraphSAINTRandomWalkSample from torch_geometric.data`. Anybody has the same issue?

**Comment by rusty1s** [comment]
That‘s not released yet, it is only available on master.

**Comment by Elizabeth1997** [comment]
Oh I see :) Thank you so much for replying!
