### ISSUE TITLE
PPI dataset "Connection reset by peer" error

### ISSUE THREAD

**Issue by yaoman3** [pyg-team/pytorch_geometric#1084]
## To Reproduce

When I try to use PPI class to create a PPI dataset, I got a "Connection reset by peer" error. Other datasets can be download correctly. Please find the following screenshot. Thanks.

![image](https://user-images.githubusercontent.com/10721459/78147674-706e8980-7466-11ea-80f5-75b6505f0860.png)

## Environment

* OS: Linux
* Python version: 3.7
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.1
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
I cannot reproduce this. Are you able to download the dataset manually?

**Comment by yaoman3** [comment]
I tried to curl the dataset in the command line and got the following error: "curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to s3.us-east-2.amazonaws.com:443".

**Comment by rusty1s** [comment]
There seems to be a problem with the external servers we want to download the raw files from. Not much I can do here :(
