### ISSUE TITLE
Cuda runtime error using GCNConv with node_dim set to 1

### ISSUE THREAD

**Issue by mkumaszka** [pyg-team/pytorch_geometric#1087]
Hi, 
I'm trying to run GCNConv with mini-batch manner. Found that to do so I have to set node_dim to 1 in constructor of GCNConv. Attached code below to reproduce error. Please let me know if it is the way how mini-batch approach should be handled. 
I'm wondering if it is my bug or something is not working as expected. 

## To Reproduce

edge index is calculated with:
`edge_index = radius_graph(data.pos, r=0.1, batch=data.batch)`

no batch dimension - no error
`conv = GCNConv(3, 16)`
`x = conv(data.x, edge_index) # data.x shape (B * num_nodes, num_features), x shape (B * num_nodes, num_features)`

mini-batch manner - attached error occurs
`conv = GCNConv(3, 16, node_dim=1)`
`x = data.x.view(batch_size, -1, 3)`
`x = conv(data.x, edge_index) # data.x shape (B, num_nodes, num_features), expected x shape (B, num_nodes, num_features)`

Error:

`RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/THC/generic/THCTensorScatterGather.cu:293
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/home/martyna.kumaszka/anaconda3/envs/jaw/lib/python3.7/site-packages/torch_scatter/scatter.py", line 22
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
`

Also in my notebook console following error appeard:

`/opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/THC/THCTensorScatterGather.cu:160: void THCudaTensor_scatterAddKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 1]: block: [278,0,0], thread: [179,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
`

## Environment

* OS: Ubuntu 18.04
* Python version: 3.7
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.0

Do you have any ideas how to solve this I am really stack I tried everything. I'm wondering if my first approach is a good one - if I should perform convolution without reshaping input tensor to (b, num_nodes, num_features) and then reshaping output tensor after GCNConv with x.view(B, num_nodes, num_features) will represent my data properly.

Thank you for your time and help

**Comment by rusty1s** [comment]
You do not need `node_dim` and reshaping of `data.x` in this case. This is just for calculating node embeddings on a static graph (the same for all in the mini-batch).
