### ISSUE TITLE
Issues with DataLoader

### ISSUE THREAD

**Issue by legohyl** [pyg-team/pytorch_geometric#1103]
## ❓ Questions & Help

I'm facing the following error when trying to loop through the `torch_geometric DataLoader`.
`TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

Some context, I saved each `Data` object into .pt torch files, and loaded them into a list via `torch.load()`. Then, I separate it into a train/validation set and loop through the train set. Not really sure how to debug this issue here.

**Comment by rusty1s** [comment]
Yeah, that error message is not really meaningful. It may come from a data object missing a specific key. You may want to check if this might be the case.

**Comment by legohyl** [comment]
Hmm what do you mean by keys? From the docs, it looks like all the parameters `x, edge_attr, ...` are all optional. Is there a requirement that these need to be there? Because I labelled all the tensors in the `Data` object by their own names.

**Comment by rusty1s** [comment]
If you want to batch data objects, the `DataLoader` expects that all data objects share the same keys.

**Comment by legohyl** [comment]
Hmm `keys` meaning I have to set them? Because what I did was to process my graphs, and just call `Data(tensor_a = a, tensor_b = b , ... )`. So this means I need to set keys in the Data object?

**Comment by rusty1s** [comment]
I am just referring to `tensor_a` and `tensor_b` as the keys here.

**Comment by legohyl** [comment]
That's really odd then, all my tensors in `Data` have the exact same names since they were done using a `for` loop, the tensors are just different in size (since they are different graphs).

**Comment by rusty1s** [comment]
Can you show me the descriptions of a few data objects?
```python
for data in dataset[:5]:
    print(data)
```

**Comment by legohyl** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/16208802/78756480-7526c680-79ad-11ea-969f-d9d0f1a61fb3.png)

**Comment by rusty1s** [comment]
Mh, that looks correct to me. Can you upload a few of those data object so I can inspect potential bugs further?

**Comment by legohyl** [comment]
I'm afraid as I can't as the data is sensitive. Any suggestions as how to debug it?

**Comment by rusty1s** [comment]
I expect the loader to fail [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/batch.py#L54), so you should check the inputs/outputs of this call.

**Comment by legohyl** [comment]
Looks like it's my edge indexes that have `None` instead of the integer value.

![image](https://user-images.githubusercontent.com/16208802/78759081-a86b5480-79b1-11ea-9520-8c19e25420cd.png)

**Comment by rusty1s** [comment]
Ah I see, it is not a PyG bug, it is just that PyG cannot infer how your edge indices should be incremented. I will work on a better error message :)
In your case, you should overwrite the `__inc__` method of `Data` to your specific needs, as suggested [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html).

**Comment by legohyl** [comment]
Ah I see okay. So basically my `Data` object has 3 graphs in it, any suggestion how to increment the edge indexes?

**Comment by rusty1s** [comment]
I believe based on the number of nodes in `dax` and `pax`, e.g., `dax_feat.size(0)` and `pax_feat.size(0)`.

**Comment by legohyl** [comment]
So basically this function is used to increment the edge indexes, so that we can isolate the graphs? E.g. Graph 1 has nodes [0:10], Graph 2 has nodes [0:5], to avoid confusion in the edge indexes, we increment it such that Graph 2 [11:16] ?

**Comment by rusty1s** [comment]
Yes :)

**Comment by legohyl** [comment]
Ah I see that's clear now. So I guess for `dax` and `pax` I can increment them by total size of the `dax` and `pax` graphs. Then for the `assign` graph, I'll just increment by the size of the `assign` graph.
