### ISSUE TITLE
DataParallel and NeighborSampler

### ISSUE THREAD

**Issue by raphaelsulzer** [pyg-team/pytorch_geometric#1110]
I am trying to make the NeighborSampler (sampling from multiple large grpahs) work for a model wrapped in DataParallel. As already explained [here](https://github.com/rusty1s/pytorch_geometric/issues/784#issuecomment-582348998) my current setup is the following:

`
// load some graphs
all_graphs = []
graph_loader = io.dataLoader(labels_path, device=device, with_label=True)   # my own dataLoader
graph_list = ["some_file_name"]
for graph in graph_list:
    graph_loader.load(graph)
    all_graphs.append(
        Data(x=graph_loader.features, y=graph_loader.gt, edge_index=graph_loader.edge_lists,
             edge_attr=graph_loader.edge_features, pos=None))

// get a first batch from all the graphs together
total_loader = DataLoader(all_graphs, batch_size=5, shuffle=True)
data = next(iter(total_loader))

// get batch_size cliques from graph
batch_loader = NeighborSampler(data, size=5, num_hops=5, batch_size=20, shuffle=True, add_self_loops=True,
                               drop_last=True, bipartite=False)

// init the model and wrap with DataParallel
model = gcn(...)
model = DataParallel(model, device_ids=[0, 1])
model.to("cuda")

// training
// iterate over batches
for current_batch in batch_loader(data.train_mask):
    data.current_batch = current_batch
    prediction = model(data)

// forward inside my model 
def forward(data):
    node_attr = data.x[data.current_batch.n_id][:, :, None].to(self.device).squeeze()
    edge_index = data.current_batch.edge_index.to(self.device)
    edge_attr = data.edge_attr[data.current_batch.e_id].to(self.device).squeeze()
    x = self.ecc1(x=node_attr, edge_index=edge_index, edge_attr=edge_attr)
`

**This produces an error in the line prediction = model(data)**
  File "/home/raphael/miniconda3/envs/pytorch14cuda92/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 67, in <listcomp>
    count = torch.tensor([data.num_nodes for data in data_list])
    AttributeError: 'tuple' object has no attribute 'num_nodes'

**How could I get a list of Data objects which is needed for DataParallel (like in the PyG example)
for my current setup?**

I tried to create the list of Data objects manually from every current_batch Data object. However, in
the current_batch, all the cliques are sampled together. Thus, I cannot access a single clique anymore, and I also wouldn't know how to get the num_nodes attribute for one clique (= one sample).

**Comment by rusty1s** [comment]
I do not think this is possible at the moment because the data returned by the NeighborSampler cannot be split into two disjoint sets. However, it might be possible by having as many samplers as you have GPUs, and convert each sampled data to the respective GPU.

**Comment by CapsulE07** [comment]
Can you provide an example code about it?

**Comment by Mario-Liu** [comment]
Can MPNN (enn-s2s) be implemented with DataParallel? It seems it can't, right?

> 
> 
> I do not think this is possible at the moment because the data returned by the NeighborSampler cannot be split into disjoint sets. However, it might be possible by having as many samplers as you have GPUs, and convert each sampled data to the respective GPU.

**Comment by rusty1s** [comment]
I'm fairly sure it can. What's the problem you are facing?

**Comment by Mario-Liu** [comment]
> 
> 
> I'm fairly sure it can. What's the problem you are facing?

Yes, it can. I successfully implemented it with DataParallel layer. However, I am facing another dataparallel saved model retraining problem. Please help.
When I train my model in the data parallel way, I saved the model with `"torch.save(model, 'models/parrel-gpu06.pkl')"`.
And then I reload the model with "`state_dict = torch.load('./models/parrel-gpu06.pkl')`   ` model= state_dict.module` " for training. However, I encountered a new problem in forward the NN archetecture training part: Atrribute Error, list object has no attribute x. This won't happen if you train the model without reload a former unfinished model with "`for data_list in train_loader:  optimizer.zero_grad()`" What should I do?

**Comment by rusty1s** [comment]
It looks to me like you should save `model.module` (the real model), not the `DataParallel(model)` network.

**Comment by Mario-Liu** [comment]
> 
> 
> It looks to me like you should save `model.module` (the real model), not the `DataParallel(model)` network.

I tried "torch.save(model.module, 'models/parrel-gpu06.pkl')". However, when I load the model and restart training in the dataparallel way, the error "Atrribute Error, list object has no attribute x." remain the same which is from "for data_list in train_loader: optimizer.zero_grad()".

**Comment by rusty1s** [comment]
I see. It looks like you may need to put the model into `DataParallel` once again before continuing training.
