### ISSUE TITLE
Correct dimension for SplineConv.

### ISSUE THREAD

**Issue by ziye3001** [pyg-team/pytorch_geometric#1111]
## ❓ Questions & Help

Hi, I successfully ran a ChebConv on my data and it worked very well. Now, I have some problem with the SplineConv. 
The underlying graph has 60 half edges so `edge_index.size() = [2,60]` and `pseudo.size() = [60,3]`. And the input data has `x.size() = [batch_size, vertex_size, in_channels]`.
Then, I define the layer ` SplineConv(in_channels, out_channels, dim= 3, kernel_size = 6, node_dim =1)`. However, it gives the error 

> RuntimeError: x.size(1) == weight.size(1)

I suspect that it has something to do with `node_dim =1`, which had no problem in ChebConv. So I delete it and reshape the input data to be `x.size() = [batch_size, in_channels, vertex_size]`. But it says  

> 2D tensors expected, got 3D

Could you advise me a bit how to correctly set the dimensions for data and layers. Thank you very much!

**Comment by neolei** [comment]
x size should be [vertex_size, vertex_size], ref:https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html, and create your DataLoader ref:https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html
Example:
```
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

for batch in loader:
    batch
    >>> Batch(batch=[1082], edge_index=[2, 4066], x=[1082, 21], y=[32])

    batch.num_graphs
    >>> 32
```

**Comment by rusty1s** [comment]
It seems that `SplineConv` does not support `node_dim` at the moment. I will look into it.

**Comment by rusty1s** [comment]
This is not easy to fix, since the CUDA kernels are implemented in a rather static way to only support `[num_nodes, num_features]` node matrices. I am sorry!

**Comment by ziye3001** [comment]
> x size should be [vertex_size, vertex_size], ref:https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html, and create your DataLoader ref:https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html
> Example:
> 
> ```
> from torch_geometric.datasets import TUDataset
> from torch_geometric.data import DataLoader
> 
> dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
> loader = DataLoader(dataset, batch_size=32, shuffle=True)
> 
> for batch in loader:
>     batch
>     >>> Batch(batch=[1082], edge_index=[2, 4066], x=[1082, 21], y=[32])
> 
>     batch.num_graphs
>     >>> 32
> ```
Thanks. I suppose you mean [batch_size, vertex_size]?

**Comment by ziye3001** [comment]
> This is not easy to fix, since the CUDA kernels are implemented in a rather static way to only support `[num_nodes, num_features]` node matrices. I am sorry!

I see. Then I will try to use the dynamic way of batching. Thank you!
