### ISSUE TITLE
Question about growing memory in pytorch

### ISSUE THREAD

**Issue by chendw98-1664366** [pyg-team/pytorch_geometric#1113]
## ❓ Questions & Help

Hi All,

I'm really new to pytorch and torch_geometric. I tried to train a customized network, using GNN and several MLPs, but it seems to have a problem of growing usage of memory. If I train on a small set of data point, it's not a problem. But when I want to use a larger dataset, then I get into

`RuntimeError: CUDA out of memory. Tried to allocate 454.00 MiB (GPU 0; 10.76 GiB total capacity; 7.27 GiB already allocated; 453.12 MiB free; 9.45 GiB reserved in total by PyTorch)`

Are there any suggestions on what could cause the problem? (I tried the suggestions on pytorch forum, i.e. using loss.item() instead of loss(), and use fp_16() or smaller batch_size).

Thanks!

**Comment by rusty1s** [comment]
Well, how big is your data you want to feed into your network? Your data/network might be to big to train on a single GPU without any sampling mechanism.

**Comment by chendw98-1664366** [comment]
Thanks so much for the reply!!
We have many graphs with nodes range from 10 nodes to 10000 nodes. With weighted random sampling with replacement, we get batches really large. It seems in the dataset, the highly weighted graphs are at the same time also very large. I guess this is the issue. But I don't know how to avoid this without biasing the dataset. What is the strategy to deal with this? Is there a way of doing weighted random sampling that controls the size of batches without bias the dataset?
Looking forward to your reply!
Thanks again!
