### ISSUE TITLE
`to_networkx()` not compatiable with QM9 dataset

### ISSUE THREAD

**Issue by sponde25** [pyg-team/pytorch_geometric#1135]
## To Reproduce

1.
1.
1.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
To you have a minimal example to reproduce this? The following code does not raise an error for me:
```python
G = to_networkx(data, node_attrs=['pos', 'x'], edge_attrs=['edge_attr'])
```

**Comment by sponde25** [comment]
Sorry for the late response. Running the same code throws the following error for me:
```
     78     G.add_nodes_from(range(data.num_nodes))
---> 79     values = {key: data[key].squeeze().tolist() for key in data.keys}
     80 
     81     for i, (u, v) in enumerate(data.edge_index.t().tolist()):

AttributeError: 'list' object has no attribute 'squeeze'
```
On some debugging the error is because `data.name` attribute which is a list.

**Comment by rusty1s** [comment]
I see. Fixed in master.
