### ISSUE TITLE
DataListLoader & DataParallel

### ISSUE THREAD

**Issue by legohyl** [pyg-team/pytorch_geometric#1155]
Hey, I was just going through your examples, and I noticed that in your example on using `DataParallel`, the `DataListLoader` didn't have any calls similar to a `torch.to(device)`. Does your implementation do this automatically? Meaning we can just pass in the entire batch list to the model instead?

**Comment by rusty1s** [comment]
That's correct, the data transfer is handled by `DataParallel` (in analogy to `torch.nn.DataParallel`).
