### ISSUE TITLE
Heatmap of attention weight

### ISSUE THREAD

**Issue by charosen** [pyg-team/pytorch_geometric#1160]
## ❓ Questions & Help

Hi @rusty1s, i would like to visualize attention weight in GAT, like drawing the heatmap of attention weight, but i could not figure out how to implement this with `alpha` in GAT and `edege_index` of `Batch`. So how can i draw the heatmap of attention weight?

**Comment by rusty1s** [comment]
I just added the ability to return attention weights in `GATConv`, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gat_conv.py#L78-L79). Just pass in the `return_attention_weights=True` option to the `GATConv.forward` method and you should get the node embeddings and the attention weights (NOTE: with self-loops added!).

You can use those to draw your heatmap :)

**Comment by pinkfloyd06** [comment]
Hi @charosen  and @rusty1s ,

I am also interested in drawing the attention heatmap given the number of  heads in GAT and the adjacency matrix.   l did the following: 
`x, (indices,attention_score)=self.gat(x,edge_index)`

`indices` is of shape `torch.Size([2, 147952])`
Its associated tensor is : 
```
tensor([[ 3956,  3866,  9586,  ..., 14815, 14816, 14817],
        [ 3866,  3956,  9581,  ..., 14815, 14816, 14817]], device='cuda:0')
```

Now, l transform indices to dense adjacency matrix as follow : 

`dense_adj=torch_geometric.utils.to_sscipy_sparse_matrix(indices).todense()`
of shape    `(14818, 14818)`

In my GAT, `heads=4` and 
`attention_score.shape  torch.Size([147952, 4])`

**Question :** 

attention_score[i, j] : i is the index of a pair of two nodes and  j its associated score. My question is how to convert `[147952, 4]` to` [14818, 14818, 4]` to draw the heatmaps per head or by averaging the heads ?

**Comment by rusty1s** [comment]
You can create a `scipy` matrix for each individual attention head:
```python
adjs = []
for i in range(attention_score.size(1)):
    adj = torch_geometric.utils.to_scipy_sparse_matrix(indices, attention_score[:, i])
    adjs.append(adj)
```

**Comment by pinkfloyd06** [comment]
Thanks, it helps
