### ISSUE TITLE
Batching for large graphs

### ISSUE THREAD

**Issue by MaxPflueger** [pyg-team/pytorch_geometric#1168]
Hi,
Is there an API to propagate only messages for a specified subset of the nodes similar to the push and pull APIs in DGL?
https://docs.dgl.ai/generated/dgl.DGLGraph.pull.html#dgl-dglgraph-pull

**Comment by rusty1s** [comment]
Hi,
No, there is no such API. If you only want to send messages to a specified subset of nodes, you need to filter `edge_index`, *e.g.*:
```python
node_mask = ... # Bool tensor holding all nodes that should receive a message
edge_mask = node_mask[edge_index[1]]
sub_edge_index = edge_index[:, edge_mask]
```
