### ISSUE TITLE
No full utilization of GPU with PyG models

### ISSUE THREAD

**Issue by cluel01** [pyg-team/pytorch_geometric#1169]
❓ Questions & Help

Hi,

I'm running several models of the QM9 dataset on a GPU (NVIDIA QUADRO RTX 6000 | 24GB VRAM) and I experience by far no full usage of the available GPU. In tests of different models, the GPU utilization only grows up to 30%.  In comparison, a simple benchmark model for testing GPU utilization directly occupies almost all available resources (90%). I provided you with code snippets of my tested models and two reports of pytorch bottleneck. 

The simplified code for my models:

```
params={"dim": 150,"depth": 1, "aggregation": "add", "processing_steps": 2}
model = ML_Model("GAT","regression",params,dataset.num_node_features,dataset.num_edge_features).to(device)
criterion = nn.L1Loss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
loader = DataLoader(dataset,num_workers=1,pin_memory=True,batch_size=200)

for data in loader:
    data = data.to('cuda')
    optimizer.zero_grad()
    output = model(data)
    loss = criterion(output, data.y)
    loss.backward()
    optimizer.step()
)
```

The code of the benchmark model (found here: https://discuss.pytorch.org/t/why-is-pytorchs-gpu-utilization-so-low-in-production-not-training/38366/7)
```
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

import torchvision.models as models
import torchvision.datasets as datasets
import torchvision.transforms as transforms


model = models.resnet50()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

dataset = datasets.FakeData(
    size=1000,
    transform=transforms.ToTensor())
loader = DataLoader(
    dataset,
    num_workers=1,
    pin_memory=True,
    batch_size=200
)

model.to('cuda')

for data, target in loader:
    data = data.to('cuda', non_blocking=True)
    target = target.to('cuda', non_blocking=True)
    optimizer.zero_grad()
    output = model(data)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    
print('Done')
```
[GPU_benchmark.zip](https://github.com/rusty1s/pytorch_geometric/files/4550924/GPU_benchmark.zip)
[MyModel.zip](https://github.com/rusty1s/pytorch_geometric/files/4551426/MyModel.zip)

**Comment by cluel01** [comment]
My idea was to directly move the whole dataset into the GPU as you described in #1021 with but this made it even worse regarding the performance. 
`dataset.data = dataset.data.to("cuda")`

**Comment by rusty1s** [comment]
Hi and sorry for answering late, I missed that one.
Without running your code (are there training scripts missing to reproduce?), I suspect that this is mainly due to a low amount of data passed into the model. Given that QM9 contains graphs of approximately ~10 nodes, we are talking about batched node number sizes of 2000 (which corresponds to like 3 MNIST images).
