### ISSUE TITLE
FPS not returning appropriate number of points.

### ISSUE THREAD

**Issue by divyanshj16** [pyg-team/pytorch_geometric#1190]
## ❓ Questions & Help

I have a specific number of points to sample. I calculate the ratio using that number which in this case is `npoint/N`, but fps is returning 2 more points than expected.

![image](https://user-images.githubusercontent.com/16683472/81142218-a4b8f680-8f8c-11ea-8359-24e38d39fe31.png)

```python
import torch
from torch_geometric.nn import fps
B, N, C = 2, 20000, 3
npoint = 768 
pts = torch.randn(2, 20000, 3)
batch = (torch.arange(0, B*N) // N).to(pts.device).contiguous()
pts = pts.view(-1, C).float().contiguous()
indices = fps(pts, batch, ratio=(npoint/N))
print(indices.shape, npoint * 2)
```

**Comment by rusty1s** [comment]
I think this is a result of numerical instability of floating point precision. Since we take the `ceil` of `ratio * num_points`, this may happen. A simple fix is to just slice `indices = indices[:768]` according to your needs.

**Comment by divyanshj16** [comment]
yes, that's what I did. But the strange thing is that it occurs only on these values if change 20000 to 20001, it works fine. I think it might be deeper.
