### ISSUE TITLE
Preparing data for HypergraphConv based on "morris/graphkerneldatasets"

### ISSUE THREAD

**Issue by tirtharajdash** [pyg-team/pytorch_geometric#1195]
## ❓ Questions & Help

I would like to gain some more understanding on the HypergraphConv implemented in Pytorch-Geometric. Let say we have a dataset that belongs to https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets. Further, let's say we have a set of hyperedges (each hyperedge is a set of nodes). For standard graph dataset, we have a `DatasetName_A.txt` which is the sparse adjacency matrix, there are node features in `DatasetName_node_attributes.txt` (N \times N) and etc files.

Now given this information, how do we prepare the data for HypergraphConv. According to what I understand, we need the hypergraph incidence matrix, H (N \times M), where M is the number of hyperedges. We will replace the adjacency matrix with an incidence matrix, which will mostly contain details like whether a node is a part of hyperedge. Now, what happens to the original graph and original files along with it? (Thank you for reading this. After I understand fully, I would like to prepare a readme for this and contribute to Pytorch-Geometric with an example.)

**Comment by rusty1s** [comment]
Thanks for this question. All your information is correct. Since `HypergraphConv` solely operates on the incidence matrix, the original graph data is no longer needed (but you can, of course, always keep it, e.g., via `data.hyper_edge_index` and `data.edge_index`.) Node features should be kept.
For hypergraph construction, you would want to follow the official paper here since we do not provide a single function to construct them:

<img width="406" alt="Screenshot 2020-05-08 at 07 21 19" src="https://user-images.githubusercontent.com/6945922/81373293-a9042180-90fc-11ea-9c24-7940fff79469.png">

PRs about this are always welcome :)

**Comment by tirtharajdash** [comment]
Thank you for the response. I have gone through this paper. Just want a little more clarification. In our standard morris dataset, we have the adjacency list stored in `Name_A.txt`, which contains entries of the form:

> 1,2
> 2,3
> 1,6

where, `edge_index[0]` is a node and `edge_index[1]` is also a node, each of these values between `1 -- N`. 

For the `hyperedge_index` (that is used in the `hypergraph_conv.py`), a file (say `Name_H.txt`) should contain entries like `[NodeID, HyperEdgeID]` . e.g. say in a graph of 5 nodes: {1,2,3,4,5}, a hyperedge {1,3,5} and {1,2,4} will form a file like:

> 1,1
> 1,2
> 2,2
> 3,1
> 4,2
> 5,1

Is this correct?

(Somewhat an unrelated query: For pooling, after the hypergraph_conv is done, we need to have the true adjacency matrix of the graph so that the pooling functions can use that structure to pool the network. Isn't it?)

**Comment by rusty1s** [comment]
Your understanding is correct. `use_attention` seems to be bugged, indeed. For pooling, it depends on what pooling you want to apply. You can also pool all nodes that belong to the same hyperedge.

**Comment by tirtharajdash** [comment]
Hi,
I prepared my hyperedge index file called "DS_H.txt" (DS stands for Dataset). The format is as mentioned earlier: `[nodeID, hyperedgeID]`. For my problem: I have a predefined set of hyperedges (say: `h1, h2, ..., hk`). A node of the graph can belong to any/some of these hyperedges. So, the final file looks like the following. It is a sparse incidence matrix file and contains information from all graphs; assume G1 has 4 nodes, G2 has 3 nodes; and k = 3):

> 1, 1
> 1, 3
> 2, 1
> 2, 2
> 3, 1
> 3, 2
> 4, 3
> 5, 1                      <----- G2 starts here
> 6, 1
> 7, 2
> 7, 3

I am finding it difficult to create a similar tu loader file? Can you please help? Here is tu.py and an example of the hypergraph incidence file (sparse).
[DS_H.txt](https://github.com/rusty1s/pytorch_geometric/files/4611939/DS_H.txt)
[tu.txt](https://github.com/rusty1s/pytorch_geometric/files/4611953/tu.txt) (please change the file extension to .py)

I will sincerely appreciate your help in this.

**Comment by rusty1s** [comment]
What's the problem with the current `read_tu` setup? Note that you also need `graph_indicator.txt` for proper separation of examples.

**Comment by tirtharajdash** [comment]
Yes. I am using `graph_indicator.txt` to map each node to a `graphID`. And, it is loading right also: as you can see the following results:

`Processing...
**tensor([    0,    30,    43,  ..., 80348, 80354, 80383])** <---- nodes are mapped to each graph

torch.Size([2, 307771])

torch.Size([307771])

torch.Size([307771])

tensor([ 76, 305, 520,  ..., 844, 845, 854])

tensor([[    1,     1,     1,  ..., 80382, 80382, 80382],

        [   76,   305,   520,  ...,   844,   845,   854]])

Done!
`

The goal is to create mini-batches properly. In my `tu.txt` I have tried, it doesn't seem work. I just blindly followed how `edge_index` is created.
[DS_graph_indicator.txt](https://github.com/rusty1s/pytorch_geometric/files/4622003/DS_graph_indicator.txt)

**Comment by rusty1s** [comment]
I see. You need some advanced mini-batching techniques for this, see [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html). Basically, you want to increase `edge_index[0]` by `data.num_nodes` and increase `edge_index[1]` by the number of hyperedges. The best way to achieve this is to generate new data objects out of the old ones:
```python
class HyperEdgeData(Data):
    def __inc__(self, key, value):
        if key == 'edge_index':
            return torch.tensor([[self.num_nodes], [value[1].max().item() + 1]])
        else:
            return super(HyperEdgeData, self).__inc__(key, value)
```
and use this instead of `torch_geometric.data.Data`.

**Comment by SpaceLearner** [comment]
Hi, I found that if the number of hyper edges is larger than that of hyper nodes when using HypergraphConv the program will report RuntimeError as index is out of bounds. This seems to be a bug.
Traceback of TorchScript (most recent call last):
  File "/home/yayaming/miniconda3/envs/sessRec/lib/python3.8/site-packages/torch_scatter/scatter.py", line 22, in scatter_sum
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
RuntimeError: index 540 is out of bounds for dimension 0 with size 540
