### ISSUE TITLE
How to convert MNIST dataset into PyG dataset?

### ISSUE THREAD

**Issue by adhikarirsr** [pyg-team/pytorch_geometric#1202]
I want to convert MNIST dataset into PYG dataset. The idea behind this to replicate Defferrard et al's result (https://arxiv.org/pdf/1606.09375.pdf) [Table 1. Proposed graph CNN GC32-P4-GC64-P4-FC512]. I have an Adjacency matrix which is 784 X 784. The adjacency matrix is here: https://bit.ly/2SIKPgH, which can be converted to edge list as follows as per @rusty1s suggestion: 

```
import scipy.io
adjt8 = scipy.io.loadmat('adjt8.mat')
adjt8 = adjt8['Expression1']
from scipy import sparse
adj81 = sparse.coo_matrix(adjt8)
row = torch.from_numpy(adj81.row).long()
col = torch.from_numpy(adj81.col).long()
edge_index = torch.stack([row,col],dim=0)
```

```
#Importing MNIST Data
!pip install spektral
from spektral.datasets import mnist
X_train, y_train, X_val, y_val, X_test, y_test, A = mnist.load_data()
```

Creating MNIST dataset:
```
from torch_geometric.data import InMemoryDataset

class MNISTDataset(InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super(MNISTDataset, self).__init__(root, transform, pre_transform)
        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return []

    @property
    def processed_file_names(self):
        return ['/tmp/mdata.pt']

    def download(self):
        pass

    def process(self):

        data_list= []
        for i in range(0, len(X_train)):
            data = Data(x=torch.tensor(X_train[i],dtype=torch.float).view(784,1),edge_index=edge_index1,y=torch.tensor(y_train[i]).view(1).long())
            data_list.append(data)

        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])
```

I am to trying to implement something similar to MNIST superpixel graclus example (https://bit.ly/3bdlQc6) that @rusty1s  implemented. However, for my simple MNIST there is going to be only one edge_index and no edge_attr. I also do not have pos. For normalized cut and graclus I need pos. The superpixel MNIST dataset comes with pos and edge_attr. 

How do I go about creating MNIST dataset for PyG?

**Comment by rusty1s** [comment]
You can compute `pos` via `np.meshgrid`, *e.g.*, `np.meshgrid(28, 28))`.

**Comment by arshishir** [comment]
I used `PyG`'s grid function to compute `pos`. Since I have unweighted edges with no attributes, I do not have `edge_attr`. This means I should be able to use your MNIST superpixel graclus example with simple modifications, which is what I tried to do.

Pos:
`pos1 = grid(28,28)`

Dataset:
```
from torch_geometric.data import InMemoryDataset


class MNISTDataset(InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super(MNISTDataset, self).__init__(root, transform, pre_transform)
        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return []

    @property
    def processed_file_names(self):
        return ['/tmp/mdata.pt']

    def download(self):
        pass

    def process(self):

        data_list= []
        for i in range(0, len(X_train)):
            data = Data(x=torch.tensor(X_train[i],dtype=torch.float).view(784,1),edge_index=edge_index1,y=torch.tensor(y_train[i]).view(1).long(),pos=pos1[1])
            data_list.append(data)

        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])
```
Now I just using your example :

```
def normalized_cut_2d(edge_index, pos):
    row, col = edge_index
    edge_attr = torch.norm(pos[row] - pos[col], p=2, dim=1)
    return normalized_cut(edge_index, edge_attr, num_nodes=pos.size(0))


class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SplineConv(d.num_features, 10, dim=2, kernel_size=5)
        self.conv2 = SplineConv(32, 64, dim=2, kernel_size=5)
        self.fc1 = torch.nn.Linear(64, 128)
        self.fc2 = torch.nn.Linear(128, d.num_classes)

    def forward(self, data):
        #x = F.elu(self.conv1(data.x, data.edge_index, data.batch))

        data.x = F.elu(self.conv1(data.x, data.edge_index))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        data.edge_attr = None
        data = max_pool(cluster, data, transform=transform)

        data.x = F.elu(self.conv2(data.x, data.edge_index))
        weight = normalized_cut_2d(data.edge_index, data.pos)
        cluster = graclus(data.edge_index, weight, data.x.size(0))
        x, batch = max_pool_x(cluster, data.x, data.batch)

        x = global_mean_pool(x, batch)
        x = F.elu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        return F.log_softmax(self.fc2(x), dim=1)
```

When I try to train it then I get:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-b7831ee8954a> in <module>()
     11 
     12 for epoch in range(1, 31):
---> 13     train(epoch)
     14     test_acc = test()
     15     print('Epoch: {:02d}, Test: {:.4f}'.format(epoch, test_acc))

3 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

TypeError: forward() missing 1 required positional argument: 'pseudo'
```

**Comment by rusty1s** [comment]
Super! For SplineConv, you need to pass edge features to the model. You can generate them via transforms, eg., torch_geometric.transforms.Cartesian() (just like we did in our MNIST example).

**Comment by arshishir** [comment]
Thanks! makes sense. I will try that too. 

Another silly question. Since I am new to PyTorch, I get confused a lot with how it handles batch training. I am just trying to use very simple one layer ChebConv:
```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = ChebConv(d.num_features, 10, K=25)
        self.fc1 = torch.nn.Linear(10, d.num_classes)

    def forward(self, data):
        x = F.elu(self.conv1(data.x, data.edge_index))
        return F.log_softmax(self.fc1(x), dim=1)
```

I have a Dataloader similar to one in the MNIST superpixel example. However, when I try to train my network I get this error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-134-b7831ee8954a> in <module>()
     11 
     12 for epoch in range(1, 31):
---> 13     train(epoch)
     14     test_acc = test()
     15     print('Epoch: {:02d}, Test: {:.4f}'.format(epoch, test_acc))

1 frames
<ipython-input-133-b1f5ec3df2b4> in train(epoch)
      9         data = data.to(device)
     10         optimizer.zero_grad()
---> 11         F.nll_loss(model(data), data.y).backward()
     12         optimizer.step()

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   2111     if input.size(0) != target.size(0):
   2112         raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
-> 2113                          .format(input.size(0), target.size(0)))
   2114     if dim == 2:
   2115         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

ValueError: Expected input batch_size (256) to match target batch_size (64).

```

**Comment by rusty1s** [comment]
You are missing a global pooling step.

**Comment by arshishir** [comment]
Why do I need global pooling? In this paper `https://arxiv.org/pdf/1606.09375.pdf` (code here: `https://github.com/mdeff/cnn_graph/blob/master/lib/models.py`) in `Table 3`, where they have used `GC10`, they have no pooling there.  All they have done is created a Cheblayer with 10 out channels and then used the output from that layer to do the classification. This what I want to replicate with `PyG` framework.

**Comment by arshishir** [comment]
Model parameters from Spektral:

```
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_11 (InputLayer)           [(None, 784, 1)]     0                                            
__________________________________________________________________________________________________
input_12 (InputLayer)           [(784, 784)]         0                                            
__________________________________________________________________________________________________
cheb_conv_5 (ChebConv)          (None, 784, 10)      260         input_11[0][0]                   
                                                                 input_12[0][0]                   
__________________________________________________________________________________________________
flatten_5 (Flatten)             (None, 7840)         0           cheb_conv_5[0][0]                
__________________________________________________________________________________________________
dense_7 (Dense)                 (None, 10)           78410       flatten_5[0][0]                  
__________________________________________________________________________________________________
dense_8 (Dense)                 (None, 10)           110         dense_7[0][0]                    
==================================================================================================
Total params: 78,780
Trainable params: 78,780
Non-trainable params: 0
__________________________________________________________________________________________________
```

Model parameters from PyG:

```
---------------------------------------------------------------------------
      Layer (type)             Input Shape         Param #     Tr. Param #
===========================================================================
        ChebConv-1     [784, 1], [2, 6396]             260             260
          Linear-2                 [1, 10]             110             110
===========================================================================
Total params: 370
Trainable params: 370
Non-trainable params: 0
---------------------------------------------------------------------------


========================= Hierarchical Summary =========================

Net(
  (conv1): ChebConv(), 260 params
  (fc1): Linear(in_features=10, out_features=10, bias=True), 110 params
), 370 params


========================================================================
```
PyG model:

```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = ChebConv(d.num_features, 10, K=25)
        self.fc1 = torch.nn.Linear(10, d.num_classes)

    def forward(self, data):
        x = F.elu(self.conv1(data.x, data.edge_index))
        x = global_mean_pool(x, data.batch)
        return F.log_softmax(self.fc1(x), dim=1)
```
You can see the huge number of parameters come after flattening. What am I missing here? 

After going through this paper: https://arxiv.org/pdf/1901.00596.pdf , I can see your point behind the global pool. If I am understanding correctly, then the global pool is the readout step that they mentioned in the Fig 2b, right?

**Comment by rusty1s** [comment]
Yeah, that is correct. The spektral implementation omits the readout and uses a flattening approach to shape [batch_size, num_nodes * channels] which works, too. Either way, for your final prediction you need to have the batch_size in the first dimension.

**Comment by arshishir** [comment]
Isn't it the case that in both these cases there should be an equal number of parameters? By doing pooling we reduce the amount of data that gets into the FC layer. With flattening that doesn't happen, right?

I get about 65% accuracy using PyG whereas I get 96% accuracy with spektral. This is because of the numbers of parameters and the pooling which reduces the data that get in the FC layer.

**Comment by rusty1s** [comment]
Sure, the flattening approach should work better compared to a non-hierachical global pooling variant. You can do this here too, of course. The downside of the flattening approach is that you lose translation invariance, similar to an MLP compared to a CNN.

**Comment by arshishir** [comment]
I agree with you about losing the translation invariance using flattening. With a flattening approach, all I am doing is  MLP on blurred MNIST images. Isn't it what  Defferrard et al. did here (at least when they only did GC10 without pooling) https://arxiv.org/pdf/1606.09375.pdf ? When we do GCN using flatten then we are not using CNN like architecture on a graph, right?

**Comment by jasperhyp** [comment]
> Sure, the flattening approach should work better compared to a non-hierachical global pooling variant. You can do this here too, of course. The downside of the flattening approach is that you lose translation invariance, similar to an MLP compared to a CNN.

Hi Matthias,  Thanks for creating both PyG and Spektral.  I have a question related to implementing `Flatten()` in PyTorch here...  Since I am using batches to train (`train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle = True)`), the `torch.flatten()` function would mix all batches together, and `torch.nn.Flatten()` (layer) would not actually decrease the dimension of tensor as in Spektral, where 3-D tensor `[batch_size, node_num, node_atttribute_num]` is converted to 2-D `[batch_size, node_num*node_attribute_num]`.  It might not a problem directly related to Spketral or PyG (indeed, those are built-in functions of torch and keras), but I am wondering if you can help me with this issue?  If I just go with `torch.flatten()`, the final output would only contain one result for `batch_size` of training samples...  Thanks!

**Comment by rusty1s** [comment]
I did not create Spektral ;)

Instead of `Flatten`, you can directly use `*.view(...)` to convert your tensor to the wished shape, e.g.:
```
x = x.view(batch_size, -1)
```
where `batch_size` is given by `data.num_graphs` or `int(batch.max()) + 1)`.

**Comment by jasperhyp** [comment]
> x.view(batch_size, -1)

Ahhhhh my mistake!  Thank you so much for answering my question!  Looks like I  I was using global_max_pool instead these days, but `view()` is definitely the solution!  Should not have assumed I can get hold of Torch from scratch just because I know about TF...

**Comment by jasperhyp** [comment]
> x.view(batch_size, -1)

Ahhhhh my mistake!  Thank you so much for answering my question!  Looks like I  I was using global_max_pool instead these days, but `view()` is definitely the solution!  Should not have assumed I can get hold of Torch from scratch just because I know about TF...

**Comment by Syzseisus** [comment]
Hi @adhikarirsr !
Did you succeed to convert MNIST data into PyG?
If then, could you share me whole code to make that?

**Comment by rusty1s** [comment]
Please have a look at https://gist.github.com/rusty1s/866ca8b830f22aa34923a0f8164f6e64

**Comment by Syzseisus** [comment]
@rusty1s thanks, but it doesn't work.
There was an `ImportError: 'SplineConv' requires 'torch-spline-conv'`.

I found the [site](https://github.com/rusty1s/pytorch_spline_conv) where I can download it.
Cause I'm working on Google Colab, where `torch.__version__ == 1.10.0+cu111`.
So I download `SplineConv` as:
```
!pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
```

Notebook says `Successfully installed torch-spline-conv-1.2.1` but,
The `ImportError` still occurs.

What should I do?

**Comment by rusty1s** [comment]
See https://github.com/rusty1s/pytorch_spline_conv/issues/25
