### ISSUE TITLE
How to debug transforms?

### ISSUE THREAD

**Issue by evakrowarska** [pyg-team/pytorch_geometric#1204]
## ❓ Questions & Help

Is there an intended or best practice way of debugging transforms in `PyTorch Geometric`?
For example, if I have a graph, representing a mesh: 
Is there a way to validate, if my transform is working as it is supposed to?

Debugging with huge tensors and keeping an eye on edge_indices and vertex positions, while not seeing the geometry visually at all, does not feel productive and sufficient to me. 

Is there an external tool or library that I can "plug-in" into my debugging process?
Maybe a way, where I do not have to copy the `face list` and `vertex positions`, for example, into another tool by hand. 
These may introduce their own internal indexing of the data, which may lead to confusion.

**Comment by rusty1s** [comment]
If you are working with meshes, you can convert `to_trimesh` and visualize from there, and if you are working on graphs, you can convert `to_networkx` and visualize from there, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.to_trimesh) and [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.to_networkx).

**Comment by evakrowarska** [comment]
Is there a way of using `to_trimesh` if I have only `edge_index` given inside `data`?

**Comment by rusty1s** [comment]
No, that does not exist.

**Comment by evakrowarska** [comment]
okay. But is there any possibility of displaying meshes just by using edge_index? Everything I can find uses faces, like [mayavi](https://docs.enthought.com/mayavi/mayavi/auto/mlab_helper_functions.html#mayavi.mlab.triangular_mesh).

**Comment by rusty1s** [comment]
Well, you can always visualize them with, e.g. matplotlib, where you connect points based on `edge_index`. We do not provide a wrapper for this though.
