### ISSUE TITLE
Scatter.p illegal memory access

### ISSUE THREAD

**Issue by UTpH** [pyg-team/pytorch_geometric#1209]
## ❓ Questions & Help

I have a simple GCN model that gives the following error when  I pass graph data in mini-batch mode. (2*293*1=batch_size*number of nodes*number of features).
class Net(torch.nn.Module):
    
     def __init__(self):

        super(Net, self).__init__()

        self.conv1 = GCNConv(1, 256, node_dim=1)
        self.conv2 = GCNConv(256, 1, node_dim=1)
        #self.conv3 = GCNConv(128, 1, node_dim=1)
        self.pool = gap

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = x.view(batch_size,293, -1)
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, training=self.training)
        x = x.view(batch_size,293, -1)
        x = F.relu(self.conv2(x, edge_index))
        x = x.view(293*batch_size, 1, -1)
        x = self.pool(x, batch, batch_size)
        x = F.sigmoid(x)
        return x

 
     Traceback of TorchScript (most recent call last): File 
       "/home/ph1391/.conda/envs/simclr/lib/python3.7/site-packages/torch_scatter/scatter.py", line 23, in scatter_sum

            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE

    else:
        return out.scatter_add_(dim, index, src)

     RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at 
     /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:296`

Any help would be appreciated!

**Comment by rusty1s** [comment]
This looks like it may be caused by one of the following:
1. Not all tensors lie on the same device
2. `edge_index` contains values greater than or equal to `number_of_nodes`.
Can you check that?

**Comment by rusty1s** [comment]
Note that you do not need to use `gap`, you can simply use `x.sum(dim=1)`.

**Comment by UTpH** [comment]
> This looks like it may be caused by one of the following:
> 
> 1. Not all tensors lie on the same device
> 2. `edge_index` contains values greater than or equal to `number_of_nodes`.
>    Can you check that?

I have checked for edge_index. It's a constant fully connected matrix with all indices less than 293. Inside scatter.py when I printed indices it was multiples of 293. So if I had 3 nodes, and 2 batch_size then indices would be [0,1,0,2,1,2,3,4,3,5,4,5] which I believe is correct?

**Comment by UTpH** [comment]
> Note that you do not need to use `gap`, you can simply use `x.sum(dim=1)`.

I realised that once I had designed it ✌🏽

**Comment by rusty1s** [comment]
Well, there are two ways to construct batches:
1. Using batched features on a single edge_index. 
2. Using both batched features and batched edge_indices.

I think you use Option 1 (with `node_dim=1`), so your `edge_index` should not be batched at all. Regarding your example, that means that `edge_index` should not be greater than 2.

**Comment by UTpH** [comment]
> Well, there are two ways to construct batches:
> 
> 1. Using batched features on a single edge_index.
> 2. Using both batched features and batched edge_indices.
> 
> I think you use Option 1 (with `node_dim=1`), so your `edge_index` should not be batched at all. Regarding your example, that means that `edge_index` should not be greater than 2.

I'm not sure I understand this completely. Because, I pass the same edge_index with indices < num_of_nodes, but unsure why indices in scatter.py converts it to the above format when I batch it..

**Comment by rusty1s** [comment]
Are you using the PyG `DataLoader` (which does this automatically?).

**Comment by UTpH** [comment]
Ooh, yes I am. I created an array of torch_geometric.data.Data objects, split them up into train/test/val sets and then used Dataloader on these splits. So the solution would be to not use Dataloader and just use the split array?

**Comment by rusty1s** [comment]
You can still use `DataLoader`, and simply remove `node_dim=1` and the reshape. If you desperately want to make use of `node_dim`, you should not batch `edge_index` (remove it from `data` and instead provide it as an attribute of the dataset:
```python
data = Data(x=x, y=y)
dataset.edge_index = edge_index
```

**Comment by UTpH** [comment]
Ok got it!
I don't need to use node_dim. But could you elaborate on why/where it could be a necessity?
