### ISSUE TITLE
Use different pre_transform and transform for test and train dataset

### ISSUE THREAD

**Issue by nwisniewska** [pyg-team/pytorch_geometric#1263]
I am using the ModelNet dataset. 
However, if I use different pre_transform for each, test and train, as well es transform for each, test and train, it seems like they are not applied correctly. 

For example, if I do the following: 
```

    train_dataset = ModelNet(root=pathManager.getDatasetPath(), name=pathManager.getModelNetDatasetNumber(), train=True,
                             pre_transform=T.Compose(
                                 [T.NormalizeScale(),
                                  T.FaceToEdge(remove_faces=False),
                                  ]),
                             transform=T.Compose([
                                 AddAdditionalData()),
                                 RemoveSelfLoops()
                             ]))
    test_dataset = ModelNet(root=pathManager.getDatasetPath(), name=pathManager.getModelNetDatasetNumber(), train=False,
                            pre_transform=T.Compose(
                                [T.NormalizeScale(),
                                 T.FaceToEdge(remove_faces=True),
                                 AddAdditionalData()
                                 ]),
                             transform=T.Compose([
                                 RemoveSelfLoops()]))
```

then I get the issue, that the data object misses the additional data attribute: 

`AttributeError: 'Data' object has no attribute additional_data `

I noticed, that inside the processed folder, there are just two files transform.pt and pre_transform.pt. Do the contain both distinct transformations for test and train dataset?

**Question**: So are the same transforms re-used for train and test or is there a mistake in my code?
I appreciate any kind of help :)

**Comment by rusty1s** [comment]
You can apply different transforms for different dataset splits, but you cannot apply different pre_transforms. That's a current limitation. As a workaround, you may want to store `train_dataset` and `test_dataset` in different `root` paths.
