### ISSUE TITLE
If the size of each input sample is not int, are there any methods to process?

### ISSUE THREAD

**Issue by Riofd** [pyg-team/pytorch_geometric#1273]
## ❓ Questions & Help
As mentioned in the documentation: "in_channels (int) – Size of each input sample.", if  the input feature of each node is high-dimension, such as N × M instead of int, are there any methods to solve?

**Comment by rusty1s** [comment]
Currently not. I feel like if you want to implement something special here, it's best to consider building your own `MessagePassing` layer.
