### ISSUE TITLE
Neighbour Samples variable typo

### ISSUE THREAD

**Issue by 1byxero** [pyg-team/pytorch_geometric#1274]
## 🐛 Bug

Typo in variable name size in class Neighbor sampler raises error

## To Reproduce

1. Init Neighbor Sampler class on version 1.5

## Expected behavior

Neighbor Sampler class is initiated  
## Environment
* PyTorch version: 1.5

## Additional context

Link to line of error
https://github.com/rusty1s/pytorch_geometric/blob/6c2e0674a96bce591a0b40d3d24f0a8d00e0cca3/torch_geometric/data/sampler.py#L91

**Comment by rusty1s** [comment]
What do you mean exactly? I don't see an issue here.

**Comment by 1byxero** [comment]
```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-7-453e79679898> in <module>()
      3 loader = NeighborSampler(
      4     data, size=[25, 10], num_hops=2, batch_size=1000,
----> 5     shuffle=True, add_self_loops=True
      6 )
      7 

TypeError: __init__() missing 1 required positional argument: 'sizes'
```

Above TypeError is raised

**Comment by rusty1s** [comment]
This is to be expected, the `NeighborSampler` got completely revamped with new API, new computation flow, and faster implementation due to supporting `num_workers`. It is highly recommend to upgrade your code to the new version. Feel free to ask any questions while migrating.

**Comment by donarni** [comment]
Hello. I'm currently learning PyG. Running your example on GraphSAGE (https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py) I'm getting the following error at the stage of `NeighborSampler`.

  File "L:\GraphSAGE.py", line 16, in <module>
    num_workers=12)

TypeError: __init__() got an unexpected keyword argument 'node_idx'

I'm running the latest Pytorch and PyG.

I hope you can give me a hint on how to fix the problem.

**Comment by rusty1s** [comment]
Can you check if `torch_geometric.__version__` really outputs `1.5.0`?

**Comment by donarni** [comment]
Thanks for responding. I was running on 1.5 on Pytorch but not on PyG (1.4.3). Sorry, my fault. However, when I'm now running the code I'm getting the same error as 1byxero.

`TypeError                                 Traceback (most recent call last)
<ipython-input-8-0220606deffa> in <module>
----> 1 train_loader = NeighborSampler(data.edge_index, node_idx=None, size=[25, 10], batch_size=1024, shuffle=True, num_workers=12)
      2 #subgraph_loader = NeighborSampler(data.edge_index, node_idx=None, sizes=[-1],batch_size=1024, shuffle=False,num_workers=12)

TypeError: __init__() missing 1 required positional argument: 'sizes'`

I'll try myself.

**Comment by donarni** [comment]
Likewise, Node2Vec is not working anymore after upgrading PyG. I've tried to fix it, but I'm getting this error: 
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-53-a9e27de9283a> in <module>
----> 1 train(50)

<ipython-input-49-c33b6b5b70cf> in train(epochs)
     13             optimizer.zero_grad() # reset gradient
     14 
---> 15             loss = model.loss(data.edge_index, subset.to(device))
     16 
     17             loss.backward()

L:\Anaconda\lib\site-packages\torch_geometric\nn\models\node2vec.py in loss(self, pos_rw, neg_rw)
    131 
    132         # Negative loss.
--> 133         start, rest = neg_rw[:, 0], neg_rw[:, 1:].contiguous()
    134 
    135         h_start = self.embedding(start).view(neg_rw.size(0), 1,

IndexError: too many indices for tensor of dimension 1`

Any idea how to fix it?

**Comment by rusty1s** [comment]
Yes, note that with [PyG 1.5.0](https://github.com/rusty1s/pytorch_geometric/releases) both interfaces (`NeighborSampler` and `Node2Vec`) have slightly changed. For `NeighborSampler`, `size` is now named `sizes`. For `Node2Vec`, you can look at [our example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/node2vec.py) on how to change.
