### ISSUE TITLE
mini batch while some graphs are similar in the minibatch

### ISSUE THREAD

**Issue by navid-mahmoudian** [pyg-team/pytorch_geometric#1277]
Suppose I have a mini-batch of 3 input data, two of which come from the same graph structure and the other one comes from a different graph. I want to apply convolution on this mini-batch using a similar idea as you describe on [Advanced mini-batches](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html), i.e. diagonally stacking adjacency matrices. However, to be memory efficient this concatenation shouldn't duplicate the same graph twice, i.e. rather than stacking 3 adjacency matrices where two of which are similar, I want to stack the two adjacency matrices and apply the convolution on the 3 inputs. Note that I don't want to use `torch_geometric.data.Data` and `torch_geometric.data.DataLoader` for this purpose because this process does not only occur for the input of the first layer but also it occurs in the intermediate layers before which the pooling operations are performed (the graph structure changes in intermediate layers). So, I want something general to be able to use with convolution functions.

**Comment by rusty1s** [comment]
I would still suggest to replicate your graph for each individual example. Your problem seems to be complicated to implement and very hard to parallelize. In addition, the overhead of replication is really negligible.

**Comment by navid-mahmoudian** [comment]
Ok, thank you I understand the parallelization issue. It is just that I don't know if there is an efficient way to do it for very big graphs. The example that I mentioned above was a toy example, but I am concerned about big graphs in mini-batches that some of them have similar graph structures in the mini-batch.
In case you still believe replicating the big graph is still the most efficient way (which I also belive), we can close this issue.

**Comment by rusty1s** [comment]
It's just that I don't think replicating `edge_index` is expensive. You can save 1 millions edges and still have only consumed 8MB of memory. Most memory problems are due to the size of node features.
