### ISSUE TITLE
Distribute an example over multiple GPUs

### ISSUE THREAD

**Issue by mrk4576** [pyg-team/pytorch_geometric#1302]
Is it possible to distribute a huge example through multiple GPUs at once with DataListLoader? If so, how?

As far as I understand it distributes complete examples to (multiple) GPUs and finally merges the results.

**Comment by rusty1s** [comment]
Yes, that is something which is currently not supported, although it shouldn't be too hard to implement for `NeighborSampler` or `ClusterLoader`. I will have a closer look at it. Please feel free to contribute :)

**Comment by rusty1s** [comment]
This should now be fully supported via `DistributedDataParallel`. Take a look at `examples/multi_gpu`.
