### ISSUE TITLE
Question about the edge weight of Autoencoder

### ISSUE THREAD

**Issue by ZihanChen1995** [pyg-team/pytorch_geometric#1310]
## ❓ Questions & Help

Hi! I'm trying to use the Autoencoder ([autoencoder.py](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/autoencoder.py)) for the node embeddings. And I have a question about how the model handles the edge weights. Could you please help me with this?

Like we're using the `CiteSeer` dataset with `split = full`. (`-->` represents output)
```
dataset = Planetoid("/tmp/citeseer", "CiteSeer", split = 'full', transform=T.NormalizeFeatures())
data = dataset[0]
data
--> Data(edge_index=[2, 9104], test_mask=[3327], train_mask=[3327], val_mask=[3327], x=[3327, 3703], y=[3327])


data.edge_index
-->tensor([[   0,    1,    1,  ..., 3324, 3325, 3326],
        [ 628,  158,  486,  ..., 2820, 1643,   33]])
```

May I ask how this `Autoencoder` handles the weight of each edge? For example, if we have several edge duplicates in `edge_index` (3 same edges between `node 1` and `node 15`):

```
data.edge_index
-->tensor([[   0,    1,    1,  1, ..., 3326],
        [ 628,  15,  15, 15, ..., 33]])
```
Does our model consider the edge between `node 1` and `node 15` has weight 3 instead of 1? Or we need to implement other models like GNN with attention to use the information of weights?

Thank you in advance for your help!

**Comment by rusty1s** [comment]
While the `Encoder`naturally supports handling of edges (it sums up these neighboring node features three times instead of only once), the current auto-encoder trains against a binary adjacency matrix using negative log-likelihood. If you want to reconstruct the adjacency matrix with duplicate edges, you may need to train with mean squared error against the amount of duplicated edges. Hope this helps!

**Comment by ZihanChen1995** [comment]
Hi Matthias, thank you for your reply. So can I understand it as: The model will "partially" use the weights of edge? Since the model uses: 1. Graph; 2. Node Features. It "considers" the weights when it deals with node features (As you said, 3 times). But not strictly follows the weights when it is sampling and using the graph.

Is this correct? Thank you again!

**Comment by rusty1s** [comment]
For a `GCN` or `SAGE` like aggregation, that is correct. However, GNNs may incorporate edge features in a more sophisticated way, e.g., by weighting/transforming node features differently depending on their edge weight. You may want to look at `NNConv`, `GIN-E` or `SplineConv` for that.

**Comment by ZihanChen1995** [comment]
OK, I'll check them carefully. Thank you for your help, Matthias. It's really helpful!
