### ISSUE TITLE
Help regarding understanding data input and 

### ISSUE THREAD

**Issue by AD2605** [pyg-team/pytorch_geometric#1315]
## ❓ Questions & Help
Hello all, I have just entered the field of geometrical learning so this is a very basic question. 
I have created a dataset, with x = 22x313 and each x corresponds to one class. 
What I essentially want to achieve is create a mapping between the input graph and the class C(denoted by an integer) by considering x and the edge_Attrs... 

example Data point - 
`Data(edge_attr=[462], edge_index=[2, 462], x=[22, 313], y=[])`

I simply use two convs, 
GraphConv(313, 512)
GraphConv(512,4)

I have 2 questions, 
1 - Am I preparing my data correctly,?
and 
2 - how should be classification be done, i.e. the input is x = 22x313 and y = tensor[0] and I have 4 classes so what my model ends up returning is [22x4]. How do I proceed further to classify this... 

Thanks for reading and TIA

**Comment by rusty1s** [comment]
You need to map to 22 output channels, each channel representing the class of a node. You then proceed to train against the identity matrix:
```
GraphConv(313, 512)
GraphConv(512,22)

out = model(...)
loss(out, torch.eye(22))
```

**Comment by AD2605** [comment]
Oh okay, will try it out...
Thanks a lot
