### ISSUE TITLE
GPU utilization was quite low

### ISSUE THREAD

**Issue by nanfangyinan1** [pyg-team/pytorch_geometric#1319]
Hello
Thanks for your work on this project. This is an awesome package.
I followed the instructions in the documentation to successfully install PyG, but when running the network under /benchmark/kernel, the GPU utilization was quite low.I run the code on 2080ti , and the GPU utilization is less than 10%， Increasing batch can't improve.

- Environment
OS: Ubuntu 16.04
Python version: 3.6
PyTorch version: 1.5.0
CUDA/cuDNN version: 10.1

**Comment by rusty1s** [comment]
The `benchmark/kernel` script runs a hyperparameter grid search with initially quite low number of layers and node dimensionality. Increasing those (+ batch_size) should also increase GPU utilization.

**Comment by nanfangyinan1** [comment]
Thank you for your suggestion, this really works. By the way, are there any examples of unpool for EdgePooling?

**Comment by nanfangyinan1** [comment]
Thank you for your suggestion, this really works.
But, when I use the EdgePooling layer in my network, the GPU utilization rate is also very low.

**Comment by rusty1s** [comment]
I see. `EdgePooling` is inherently sequential which limits its GPU utilization.
