### ISSUE TITLE
AUC keeps 0.5 during the Autoencoder model training

### ISSUE THREAD

**Issue by ZihanChen1995** [pyg-team/pytorch_geometric#1329]
## ❓ Questions & Help

Hi Matthias. I met a question when I'm training the [Autoencoder](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/autoencoder.py) model on my customize dataset: The AUC and AP do not change during the model training process. I remember that this problem usually happens when the feature matrix `x` is all zero. However, my feature matrix has value in it. Could you please give me some hints on it? Thank you a lot!

Here are some details of the training process. Our dataset contains two parts: 

edge list
```
edge_index = torch.tensor([receive, send], dtype=torch.long)

--> tensor([[    1,     2,     3,  ..., 37416, 37416, 37417],
        [34268, 32212,  1364,  ...,  4781, 11619,  6418]])
```
feature matrix: x (Some of them look the same, but there are differences between them. The dimension of x is [37420, 827]. The first 700 columns are float number, the remains are one-hot encoding)
```
x

--> tensor([[ 0.0299, -0.1562,  1.2514,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0299, -0.1562,  1.2514,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0299, -0.1562,  1.2514,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0299, -0.1562,  1.2514,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0299, -0.1562,  1.2514,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0299, -0.1562,  1.2514,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0')


x.type()

--> 'torch.FloatTensor'
```
Then I just use the `Data` function to build the data, split it with `train_test_split_edges`.
```
pyg_data = Data(x=fea_matrix, edge_index=edge_index)

train_data = train_test_split_edges(pyg_data)
--> Data(test_neg_edge_index=[2, 4595], test_pos_edge_index=[2, 4595], train_neg_adj_mask=[37420, 37420], train_pos_edge_index=[2, 78130], val_neg_edge_index=[2, 2297], val_pos_edge_index=[2, 2297], x=[37420, 827])
```

And finally bring them into the module.
```
class Encoder(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(Encoder, self).__init__()
        self.conv1 = pyg_nn.GCNConv(in_channels, 2 * out_channels)
        self.conv2 = pyg_nn.GCNConv(2 * out_channels, out_channels)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        return self.conv2(x, edge_index)

node_feature_dimen = pyg_data.x.shape[1]
channels = 100
dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = pyg_nn.GAE(Encoder(node_feature_dimen, channels)).to(dev)
x, train_pos_edge_index = train_data.x.to(dev), train_data.train_pos_edge_index.to(dev)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(1, 101):

    model.train()
    optimizer.zero_grad()
    
    z = model.encode(x, train_pos_edge_index)
    loss = model.recon_loss(z, train_pos_edge_index)
    loss.backward()
    optimizer.step()

    # also, show the val result of each epoch
    model.eval()
    with torch.no_grad():
        tem_z = model.encode(x, train_pos_edge_index)
        auc, ap = model.test(tem_z, train_data.test_pos_edge_index, train_data.test_neg_edge_index)
    
    if epoch % 10 == 0:
        print('Epoch: {:03d}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, auc, ap))

--> Epoch: 010, AUC: 0.5000, AP: 0.5000
Epoch: 020, AUC: 0.5000, AP: 0.5000
Epoch: 030, AUC: 0.5000, AP: 0.5000
Epoch: 040, AUC: 0.5000, AP: 0.5000
Epoch: 050, AUC: 0.5000, AP: 0.5000
Epoch: 060, AUC: 0.5000, AP: 0.5000
Epoch: 070, AUC: 0.5000, AP: 0.5000
Epoch: 080, AUC: 0.5000, AP: 0.5000
Epoch: 090, AUC: 0.5000, AP: 0.5000
Epoch: 100, AUC: 0.5000, AP: 0.5000
```

The question confuses me a lot. Could you please help me with this? Thank you a lot for your time!

**Comment by rusty1s** [comment]
Mh, it‘s hard for me to help here since it seems data-dependent so that the model cannot learn anything and makes random decisions. You can verify that by checking whether an MLP instead of a GNN has equal performance.

**Comment by ZihanChen1995** [comment]
Thank you for the reply, Matthias. Sure, I'll check different models and feature matrix format to see whether I can make any progress. Thank you again!

**Comment by tomlincr** [comment]
Appreciate this is closed/old, but sharing here as this is one of the only results for this error on Google and this may help someone else.

This issue occurred for me when I had **inadvertently included the node index in the node feature matrix**, removing the index immediately resolved the problem!
