### ISSUE TITLE
Unable to find Pytorch for CUDA 11.01

### ISSUE THREAD

**Issue by tyson98** [pyg-team/pytorch_geometric#1330]
## 📚 Installation

Error:
**python -c "import torch; print(torch.cuda.is_available())"
>>> False**

## Environment

* OS: Windows 10
* Python version: 3.7.1
* PyTorch version: 1.5.0 (CPU toolkit)
* CUDA/cuDNN version: 11.01
* GCC version: 7.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [*] I followed the installation guide.
- [*] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
You need to install a PyTorch version with CUDA Toolkit 10.1.

**Comment by tyson98** [comment]
@rusty1s I mistakenly installed Pytorch version with CUDA Toolkit 10.2, will this work? Or should I uninstall Pytorch and then install 10.1?

Also, I have a windows machine as mentioned do I still need to follow these commands provided in this [link](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html). 

I can install on Ubuntu 20.04, virtual machine as well, the only issue is CUDA has issues on running on a Virtual Machine.

**Comment by tyson98** [comment]
@rusty1s can you please update me on this?

**Comment by rusty1s** [comment]
Both Windows and Ubuntu installation should be fine if you have a PyTorch version with CUDA installed. We support CUDA 9.2, 10.1 and 10.2. You can follow the installation instructions in the document you linked. Please keep me updated on the progress you make and if there are any errors.

**Comment by tyson98** [comment]
I have Pytorch and CUDA installed. 

```
PS C:\Users\Jayesh> python -c "import torch; print(torch.__version__)"
1.5.0
PS C:\Users\Jayesh>  python -c "import torch; print(torch.version.cuda)"
10.2
```

In the place mentioned where we need to specify our CUDA version between the following options, how do we choose one? 

`where ${CUDA} and ${TORCH} should be replaced by your specific CUDA version (**cpu, cu92, cu101, cu102**) and PyTorch version (1.4.0, 1.5.0), respectively.`

**Comment by rusty1s** [comment]
Since you have CUDA 10.2 installed, you use `cu102` with PyTorch `1.5.0`.

**Comment by tyson98** [comment]
Okay, I tried with this, I am getting this message:

```
PS C:\Users\Jayesh> pip install torch-scatter==latest+${cu102} -f https://pytorch-geometric.com/whl/torch-${1.5.0}.html
Looking in links: https://pytorch-geometric.com/whl/torch-.html
ERROR: Could not find a version that satisfies the requirement torch-scatter==latest+ (from versions: 0.3.0, 1.0.2, 1.0.3, 1.0
.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.4, 2.0.5)
ERROR: No matching distribution found for torch-scatter==latest+
```

**Comment by rusty1s** [comment]
Try
```
pip install torch-scatter==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
```

**Comment by tyson98** [comment]
Yes, I am sorry. I just realized my mistake. Thank You very much.
