### ISSUE TITLE
DataLoader supports follow_batch but DataListLoader doesn't

### ISSUE THREAD

**Issue by non-void** [pyg-team/pytorch_geometric#1333]
## 🐛 Bug

I followed the instruction on Advanced Mini-Batching, I added follow_batch argument to DataLoader, and works fine

`    train_loader = DataLoader(SSDataList(args.data_path, train_indices),
                              batch_size=args.train_batch, shuffle=True,
                              num_workers=args.workers,
                              pin_memory=True,follow_batch=['x'])
`

However, when I switch my code to multi-gpu version, I found that DataListLoader do not support follow_batch argument.

`    train_loader = DataListLoader(SSDataList(args.data_path, train_indices),
                              batch_size=args.train_batch, shuffle=True,
                              num_workers=args.workers,
                              pin_memory=True,follow_batch=['x'])
`

it raises error:
`
  File "/xx/dataloader.py", line 76, in __init__
    super(DataListLoader, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'follow_batch'
`

How to use follow_batch in DataListLoader?

**Comment by rusty1s** [comment]
I see. That is indeed not indented. I have plans to work on better multi GPU support anyway :)

In the meantime, this can be fixed by manually adding `batch` objects to your data.

**Comment by non-void** [comment]
thanks for your reply, I would try it immediately.
