### ISSUE TITLE
How to build a HyperGraph by using PyG?

### ISSUE THREAD

**Issue by WhatAShot** [pyg-team/pytorch_geometric#1339]
## ❓ Questions & Help

How to build a HyperGraph by using PyG? Are there any examples?

**Comment by rusty1s** [comment]
No, sadly not :( You can follow the `HyperGraph` paper for construction, see [here](https://arxiv.org/pdf/1901.08150.pdf) (Section: Hypergraph Construction). If you are interested, please send a PR :)
