### ISSUE TITLE
No module named 'points.datasets'

### ISSUE THREAD

**Issue by shangguan9191** [pyg-team/pytorch_geometric#1340]
## ❓ Questions & Help

hey guys, when i tried to implement the pointCNN on Modelnet, this error occurs. Do you have same issues? i have installed point library, the problem still exist

**Comment by rusty1s** [comment]
You need to install the subpackage via `python setup.py install`.

**Comment by shangguan91** [comment]
> You need to install the subpackage via `python setup.py install`.
i normally use ! pip install torch-geometric to install the package. 

However, i also tried to clone it, and my pwd: /content/pytorch_geometric
after i run` !python setup.py`
it returns**usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: no commands supplied**
