### ISSUE TITLE
GINEConv edge_attributes and node_features

### ISSUE THREAD

**Issue by mesax1** [pyg-team/pytorch_geometric#1342]
## ❓ Questions & Help

Greetings,

I'm trying to use GINEConv for graph classification, but it seems to require the same number of node_features and edge_attributes in order to work correctly. 
When this number is not the same, I get the following error 
`assert x.size(-1) == edge_attr.size(-1)`
am I using it wrong or is it indeed a requirement to have the same number of node and edge features?

Thank you for your help.

**Comment by rusty1s** [comment]
`GIN-E` requires node and edge features to be of same dimensionality, since their features are added together. In general, this isn't much of a problem since you can always transform your edge features to the same dimensionality.

**Comment by mesax1** [comment]
Thank you Matthias.

May I ask how can I transform my edge features to the same dimensionality as the node ones?

For example, right now I have Graph with x=[36, 6] and edge_attr = [39, 1].

**Comment by rusty1s** [comment]
```
lin = Linear(1, 6)
edge_attr = lin(edge_attr)
```

**Comment by rtybanana** [comment]
Hi rusty1s,

Do you have any advice for transforming node features if I only have edge features. For example, if I only have a single edge feature and no node features, could I simply set node features to [1]? Or is there a better way in your opinion?

**Comment by JannarZ** [comment]
> ```
> lin = Linear(1, 6)
> edge_attr = lin(edge_attr)
> ```

Hi rusty1s,

I noticed that if I have multiple layers of the GINEConv then even if the input layer have the correct dimension, in the hidden layer they would not be the same as the node features in the hidden layer dimension changed. Do I have to implement this transformation every layer then?

**Comment by rusty1s** [comment]
Yes, this needs to be added to every layer.

**Comment by JannarZ** [comment]
> Yes, this needs to be added to every layer.

Thank you for clarify!
