### ISSUE TITLE
Using node AND edge attributes

### ISSUE THREAD

**Issue by ioannisa92** [pyg-team/pytorch_geometric#1346]
## ❓ Questions & Help
@rusty1s I would like to use both node and edge attributes for the models I am constructing. Could you please point to an example that does that? Or a layer that takes advantage of both?

Also, if possible, could you please briefly describe or point to a resource that describes how such a graph convolution (with node and edge attr) takes place? I'm interested in the mathematical basis of it.

Thank you for your time.

**Comment by rusty1s** [comment]
There are a few operators that take also edge features into account, see e.g. `GIN-E`, `NNConv` or `SplineConv`. This is usually done by also considering them in the aggregation procedure. You can have a look at [this paper](https://arxiv.org/abs/1704.01212) for a better description.

**Comment by ioannisa92** [comment]
Thank you so much. Appreciated!
