### ISSUE TITLE
Message Passing considering cliques

### ISSUE THREAD

**Issue by seziegler** [pyg-team/pytorch_geometric#1351]
## ❓ Questions & Help

Hey,

I'm trying to implement a Message Passing Model, which takes into account 3-cliques of the graph (all possible subgraphs consisting of 3 nodes that are fully connected). 

My graph consists of the edge index and edge features and my goal is to update the edge features, based on the edge features from the other two edges in the 3-clique. One edge can of course be part of many 3-cliques.

The message in this case could be a multiplication of the two other edges' features in the clique and the aggregation would be a sum of all messages from all cliques in which the initial edge is part of. 

It's similar to mean field updates like in formula 8 here: https://arxiv.org/pdf/1812.09737.pdf 

So my main problem is that in all examples I found, it is always assumed that there is one source and one target for a message. Here however, I need two targets (the two other edges from the 3-clique), do some operations on them and then send the result to the source, where all incoming messages (from all cliques) will be aggregated by sum in order to update the source.

Can this somehow be achieved in pytorch geometric? Any help or pointing to an example is much appreciated!

**Comment by rusty1s** [comment]
You need two propagation steps on two different graph connectivities for that. One `edge_index1` holds, for each edge, the indices of edges inside the same clique. The other `edge_index2` holds, for each edge, the information in which cliques this edge is part of:
```python
out = conv1.propagate(edge_index1, size=(num_edges, num_edges), x=...)
out = conv2.propagate(edge_index2, size=(num_edges, num_cliques), x=out, ...)
```

**Comment by seziegler** [comment]
Thank you for the fast reply! I'm not sure if I understand it correctly though. 

If I had a graph with the following edges:

```python
edge_index = torch.tensor([[0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4],
                           [1, 2, 0, 2, 0, 1, 3, 4, 2, 4, 2, 3],
                           ], dtype=torch.long)
```

consisting of 5 nodes, 12 edges and two 3-cliques consisting of nodes 0,1,2 and 2,3,4.

Could you please say how `edge_index1` and `edge_index2` would look like in this example?

**Comment by rusty1s** [comment]
Maybe I misunderstood the question at first. If you solely want to update edge features based on the edge features that are part of the same clique, your `clique_edge_index` would look like this:
```
0 0 0 0 0 1 1 1 1 1 ... 10 10 10 10 10 11 11 11 11 11
1 2 3 4 5 0 2 3 4 5 ...  6  7  8  9 11  6  7  8  9 10
```
So for each edge (indices `0-11`), it holds the information which edges belong to the same clique.

**Comment by seziegler** [comment]
Yes it is my goal to update the edge features based on the edge features that are part of the same clique. But I have an intermediate step which requires multiplying the two other edges in the clique , before sending the message to the edge I want to update. (There are always two other edges since I only look at cliques of size 3)

So in the example graph I mentioned before, if I wanted to update the first edge (0,1), I'd need to check in which cliques it is part of which here is the clique consisting of the undirected edges (0,1), (0,2) and (1,2).
I then need to multiply the edge features from edge (0,2) and (1,2). This result is then one message for edge (0,1). If it was part of other cliques as well I'd to the same for the other cliques and then aggregate the messages as usual.  So it is one message per clique and not one message per edge.

The `clique_edge_index` wouldn't work as it wouldn't be possible to do the intermediate multiplication step with it, right?

**Comment by rusty1s** [comment]
`clique_edge_index` should also work for that since it only holds nodes of the same degree, namele 2 (or 4 if you utilize undirected edges). You can then aggregate based on a simple reshape.
```python
row, col = clique_edge_index
edge_attr[col].view(-1, 2, edge_attr.size(-1).mul(dim=2)
```
