### ISSUE TITLE
Which method should I use to apply to 2D lidar data ?

### ISSUE THREAD

**Issue by karanbirchahal-bc** [pyg-team/pytorch_geometric#1360]
## ❓ Questions & Help

 I have to solve a segmentation problem on 2D lidar points (I get ranges and angles). What kind of network would best be suited for my problem ? Overall, I want to create a good feature representation of my lidar range scan. Any help would be very appreciated !

**Comment by rusty1s** [comment]
I think you can look into `PointConv`, `SplineConv` or `GMMConv`, which can all operate on point clouds.
