### ISSUE TITLE
Finding MNISTSuperpixel's superpixel mask.

### ISSUE THREAD

**Issue by TwiggyDaniels** [pyg-team/pytorch_geometric#1375]
## ❓ Questions & Help
Is there any way to get the mask mapping each pixel in MNIST to its superpixel in MNISTSuperpixel?

Unfortunately, I can't just create my own superpixels in my use case. If I can't locate the original, an approximation would also work. I figure I can try and approximately undo a center of mass like a sort of 3D Voronoi diagram including pixel intensity as part of the distance?

I'm sort of stumbling around in the dark, if there's an easier way to find the masks, please do share!

**Comment by rusty1s** [comment]
The `MNISTSuperpixel` dataset is borrowed from the [MoNet paper](https://arxiv.org/abs/1611.08402), so I do not have access to any additional information. I am sorry! You can contact its authors to provide additional data, or modify the [`ToSLIC`](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.ToSLIC) transform to your own needs.
