### ISSUE TITLE
one_hot import error

### ISSUE THREAD

**Issue by LvShengZe903** [pyg-team/pytorch_geometric#1379]
## ❓ Questions & Help

Hello, when i run this code 
`from torch_geometric.utils import degree, one_hot`
and an error was found as below

>  ImportError: cannot import name 'one_hot'

the enviroment i used is 
torch 1.4.0
python 3.6
cuda 10.0
torch-geometric 1.5.0

i read the doc and did not found this module one_hot ,but i saw this code in other`s project and run correctly.
thank you for your early reply.

**Comment by rusty1s** [comment]
Yeah, that got removed long time ago since PyTorch now provides this functionality via `torch.nn.functional.one_hot`. Should be a drop-in replacement.

**Comment by LvShengZe903** [comment]
I am really appreciate for your reply. Thank you very much.

**Comment by LvShengZe903** [comment]
> Yeah, that got removed long time ago since PyTorch now provides this functionality via `torch.nn.functional.one_hot`. Should be a drop-in replacement.


I am really appreciate for your reply. Thank you very much.
