### ISSUE TITLE
Does pyG support distributed storage and training?

### ISSUE THREAD

**Issue by AI-Friend** [pyg-team/pytorch_geometric#1382]
## ❓ Questions & Help
Hi, 
I want to use multiple GPUs or machines to read and train models. 
Does pyG support distributed storage and training?

**Comment by rusty1s** [comment]
Hi,
currently no. I am sorry. We just provide a `DataParallel` wrapper that is similar to the one in PyTorch, but not a `DistributedDataParallel` analogy. I will work on it once I have some free time.

**Comment by rusty1s** [comment]
`DistributedDataParallel` is now fully supported. Take a look at `examples/multi_gpu`.
