### ISSUE TITLE
Update node features with connected edges in GAT

### ISSUE THREAD

**Issue by roholazandie** [pyg-team/pytorch_geometric#1385]
## ❓ Questions & Help
I came across this paper https://arxiv.org/abs/1906.01195 that tries to extend the basic GAT model and use edge features to update the node embedding. How can this be done in MessagePassing implementation. I tried to write:

```
    def message(self, x_i, x_j, edge_index_i, size_i, return_attention_weights):
        # Compute attention coefficients.
        x_i = x_i.view(-1, self.heads, self.out_channels)
        x_j = x_j.view(-1, self.heads, self.out_channels)
        r_i = r_i.view(-1, self.heads, self.out_channels)

        alpha = (x_i * self.att_i).sum(-1) + (x_j * self.att_j).sum(-1) + (r_i * self.att_r).sum(-1)
```
And pass the r as relation in propagate function like:
```
        out = self.propagate(edge_index, x=x, r=r, return_attention_weights=return_attention_weights)

```
But I get size errors. I think propagate treats r as another node embedding matrix and that causes the problem. Is there any better way to implement this?
(Also here I assume there is only one relation between x_i and x_j nodes which is fine for my dataset but I also wanted to know if pytorch-geomentric supports more than one edge per each node pairs?)

**Comment by rusty1s** [comment]
For edge features, you do not need to add suffixes like `_i` or `_j`. You can simply use the original feature name, and the shape mismatch should disappear. [Here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/cg_conv.py#L77-L82) is a simple example.
