### ISSUE TITLE
No matching distribution found for torch-scatter==latest+cu102

### ISSUE THREAD

**Issue by AD2605** [pyg-team/pytorch_geometric#1387]
## 📚 Installation

Not able to install the binaries in centOS 8.

## Environment

* OS: CentOS 8
* Python version: 3.6
* PyTorch version: 1.5.0
* CUDA/cuDNN version: 10.2/ 7.6.5
* GCC version: 8.3.1
* How did you try to install PyTorch Geometric and its extensions (wheel, source): Binaries
* Any other relevant information:

## Checklist

- [Yes ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ Yes] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ Yes] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ No] I do have multiple CUDA versions on my machine.

## Additional context

 The error message is as follows  - Could not find a version that satisfies the requirement torch-scatter==latest+cu102 (from versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.4, 2.0.4+cpu, 2.0.4+cu101, 2.0.4+cu102, 2.0.4+cu92, 2.0.5, 2.0.5+cpu, 2.0.5+cu101, 2.0.5+cu102, 2.0.5+cu92)
No matching distribution found for torch-scatter==latest+cu102

**Comment by rusty1s** [comment]
Ok, that‘s interesting. Does installing version 2.0.5+cu102 work?

**Comment by AD2605** [comment]
Nope, I still get the same error...

**Comment by rusty1s** [comment]
Does it work to install from this link directly?
```
pip install https://pytorch-geometric.com/whl/torch-1.5.0/torch_scatter-latest%2Bcu102-cp36-cp36m-win_amd64.whl
```

**Comment by AD2605** [comment]
Yep, this works, although I ran the linux_x86 and with pip I got the message saying  file does not exist.

**Comment by rusty1s** [comment]
Yeah, that was a mistake. I wanted to link the linux wheel, sorry! So that‘s working now?

**Comment by AD2605** [comment]
Just realized the pip3 version shipped in centOS 8 in version 9.. upgraded it to 20 and installed the wheels after downloading them. 
I suppose installing  the binaries would work fine too
