### ISSUE TITLE
DB15K does not download correctly

### ISSUE THREAD

**Issue by nd7141** [pyg-team/pytorch_geometric#1389]
## 🐛 Bug

When one tries to download and process DB15K data set for fr_en pairing, it fails. 

## To Reproduce

```
import torch_geometric as pg
pg.datasets.DBP15K(root='./', pair='fr_en')
```

![image](https://user-images.githubusercontent.com/4607709/86228441-ab2fad00-bb8e-11ea-89b4-2d2fa8bb9825.png)

I guess the issue can be in `process` method which does not decode the file correctly. 

Is it possible to fix?

**Comment by rusty1s** [comment]
I can not reproduce this with Python 3.7. This might be a Python version/OS issue. It looks like you have problems reading `sub.glove.300d`. Can you inspect the file and see whether it got downloaded correctly?
