### ISSUE TITLE
NeighborSampler for k-hop sampling

### ISSUE THREAD

**Issue by roholazandie** [pyg-team/pytorch_geometric#1391]
## ❓ Questions & Help
I have a hard time understanding `NeighborSampler` even with small examples. It doesn't make sense in most cases. 

```
l = np.array([[0, 1], [1, 4], [1, 5], [1, 6], [0, 2], [2, 7], [0, 3], [3, 8], [3, 9], [3, 10], [3, 11]]).transpose()
r = np.array([l[1, :], l[0, :]])
edge_index = torch.from_numpy(r)

train_loader = NeighborSampler(edge_index,
                               sizes=[2, 2], batch_size=1)

for batch_size, n_id, adjs in train_loader:
    print("###")
    for edge_ind, e_id, size in adjs:
        print(e_id)

```
gives me:
```
tensor([ 4,  0, 10,  8,  3,  1])
tensor([6, 0])
```
It looks like it jumps over edges?

How can I use it for k-hop sampling?

**Comment by roholazandie** [comment]
I also tried TwoHop() with edge_attr, but it gives me error for not symmetric graphs, even the example you have in test is a symmetric one. Is there any way around this?

**Comment by rusty1s** [comment]
The NeighborSampler example looks correct to me. It samples two edges in the last layer for node 0: to nodes 1 and 3. in the first layer, it samples 6 edges for nodes 0, 1 and 3: to nodes 1, 4, 6, 2, 9, 11.

Regarding your second issue: You pass in two edges, but 3 edge features. So that‘s an expected crash and isn‘t related to symmetric adjacencies.

**Comment by roholazandie** [comment]
> The NeighborSampler example looks correct to me. It samples two edges in the last layer for node 0: to nodes 1 and 3. in the first layer, it samples 6 edges for nodes 0, 1 and 3: to nodes 1, 4, 6, 2, 9, 11.
> 
> Regarding your second issue: You pass in two edges, but 3 edge features. So that‘s an expected crash and isn‘t related to symmetric adjacencies.

Thanks for your response. Is there any simple way to get the edge_id for edges between hops? for example if I have:
```
edge_index = torch.tensor([
    [0, 1],
    [1, 2]
])
```
and TwoHop gives me 0-2. Is there any way to get the edges that create this without changing the internal code?

**Comment by rusty1s** [comment]
I am not really sure what you mean. TwoHop just performs a sparse-sparse matrix multiplication.

**Comment by raphaelsulzer** [comment]
> The NeighborSampler example looks correct to me. It samples two edges in the last layer for node 0: to nodes 1 and 3. in the first layer, it samples 6 edges for nodes 0, 1 and 3: to nodes 1, 4, 6, 2, 9, 11.
> 
> Regarding your second issue: You pass in two edges, but 3 edge features. So that‘s an expected crash and isn‘t related to symmetric adjacencies.

why are edge 0 (node 1 to 0) and edge 4 (node 2 to 0) sampled in the first layer? all the rest makes sense to me, but not these two edges.

source nodes 4 and 6 send to target 1, source nodes 11 and 9 send to target 3 in the first layer, and in the second layer source nodes 3 and 1 send to target 0. why these other two edges?

**Comment by rusty1s** [comment]
Edge 0 and Edge 4 are sampled for node 0 in layer 1. The NeighborSampler will recursively sample neighbors/edges for all nodes encountered in all previous layers, *e.g.*, for applying skip-connections.
