### ISSUE TITLE
Using DataParallel with Batchnorm

### ISSUE THREAD

**Issue by mrk4576** [pyg-team/pytorch_geometric#1408]
I have applied the DataParallel module of PyTorch Geometric, 
as described [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/data_parallel.py).

Now, if I use more than 1 GPU, 
then my last batch norm layer fails with the following issue: 

`ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])
`

Is there a way to use multi GPU in PyTorch Geometric together with batch norm?

Help is quite urgent. Thanks

**Comment by rusty1s** [comment]
Applying `BatchNorm` to a matrix of batch size 1 produces this error since it cannot compute the batch statistics. You may want to prevent batches of size `1`.

**Comment by mrk4576** [comment]
Thanks for your reply. 
Yes, you are completely right! 

The thing is, that I have used a batch_size of `20` on `2 ` GPUs, receiving that error message. 
Does the multi-GPU implementation somehow distribute the examples, such that a large graph may end up alone on a GPU, to make it fit?
Or is that probably rather a mistake in my code?

**Comment by rusty1s** [comment]
Yeah, that might indeed happen. We split examples based on their number of nodes.

**Comment by mrk4576** [comment]
OK, so the only way to solve that issue is to deactivate `Batchnorm`?

**Comment by rusty1s** [comment]
How about using [`SyncBatchNorm`](https://pytorch.org/docs/master/generated/torch.nn.SyncBatchNorm.html#torch.nn.SyncBatchNorm). As an alternative, you can fix `BatchNorm` to use current `mean` and `std` values for normalization in case `batch_size=1`.

**Comment by mrk4576** [comment]
Thanks for the advise !

Does `SyncBatchNorm` work with `DataParallel`, especially the `PyTorch Geometric` implementation, as well?
I mean, I use multiple GPUs within a single training within a single process?

The reason, why I ask, are the following lines of the documentation, that you have linked:

> Currently SyncBatchNorm only supports DistributedDataParallel (DDP) with single GPU per process. Use torch.nn.SyncBatchNorm.convert_sync_batchnorm() to convert BatchNorm*D layer to SyncBatchNorm before wrapping Network with DDP.

**Comment by rusty1s** [comment]
Ok, sorry! Did not know that it was only available for distributed data parallel. I think the other way should work though, but you shouldn‘t call it based on len(data_list), but instead inside your model based on data.num_graphs.

**Comment by mrk4576** [comment]
The second approach run through, by setting `self.eval()`, if` data.num_graphs` equals to `1.`
Just one question:
Does this bias my training somehow?
I mean, if each gpu calculates its stats independently, and sometimes one example does not get considered at all, 
does this achieve the same training performance?

**Comment by rusty1s** [comment]
Generally, I would say it doesn‘t affect training performance much since the batching process is still random. It‘s just that batch norm gets computed based on a smaller number of samples.
