### ISSUE TITLE
Why does the Batch object store flat tensors by default?

### ISSUE THREAD

**Issue by richardrl** [pyg-team/pytorch_geometric#1450]
By default, the Batch object flattens the batch dimension and uses the .batch property to retain the batch indices.

However, the batch indices are not retained for the Data.y attribute, which means we have to manually reshape it in certain loss functions.

In general, it seems like a better idea to store batched tensors, with the batch dimension intact, instead of flattening.

**Comment by mariolinovIC** [comment]
In general, graphs are designed to work that way. When you want to create a batch with N graphs, those N graphs are represented as a unique graph (but isolated from each other).

In general, that approach is more convenient than what you propose. However, if for some reason you want to access the different graphs in a batch you can do:

for idx in range(data.batch[-1]):
     data.y[data.batch==idx] = ...

Hope it helps.

**Comment by richardrl** [comment]
@mariolinovIC The code you posted won't work, and even if something like that does work, a for loop is a very slow solution.

Right now, I think I will try to build a class around the Batch class that retains the shape information. @rusty1s What do you think about this?

**Comment by rusty1s** [comment]
I think @mariolinovIC solution works fine, except that you may want to replace `range(data.batch[-1])` by `range(int(data.batch[-1]) + 1)`.

Nonetheless, there are different ways to obtain example-specific information from the `Batch` object. First of all, there is a method called `to_data_list`, which converts a `Batch` object back to a list of `Data` objects.

If you are only interested in splitting a specific tensor, you can also do the following:
```python
from torch_scatter import scatter
num_nodes_per_graph = scatter(torch.ones(data.batch.size(0), dtype=torch.long), batch, reduce='add')
ys = data.y.split(num_nodes_per_graph.tolist())
```

**Comment by richardrl** [comment]
@rusty1s For loops are very slow. 

List is not good because it's slow..

If we have variable sized graphs, usually what we do is pad the graphs up to a maximum size, not use lists.

**Comment by rusty1s** [comment]
Ok, I somehow thought you wanted to operate on a list of splitted ground-truth tensors. If you simply want to reshape your data to `[batch_size, max_num_nodes, ...]`, you can make use of the `to_dense_batch` method:
```python
from torch_geometric.utils import to_dense_batch
y, mask = to_dense_batch(data.y, data.batch)
```

**Comment by richardrl** [comment]
> Ok, I somehow thought you wanted to operate on a list of splitted ground-truth tensors. If you simply want to reshape your data to `[batch_size, max_num_nodes, ...]`, you can make use of the `to_dense_batch` method:
> 
> ```python
> from torch_geometric.utils import to_dense_batch
> y, mask = to_dense_batch(data.y, data.batch)
> ```

Hi @rusty1s ,
This function seems to be assuming all the attributes are the same size as data.pos, which is not true in most cases.

> batch.pos.shape
torch.Size([10240, 3])

> batch.relative_quat_world.shape
torch.Size([40])

> to_dense_batch(batch.relative_quat_world, batch.batch)
RuntimeError: The expanded size of the tensor (40) must match the existing size (10240) at non-singleton dimension 0.  Target sizes: [40].  Tensor sizes: [10240]


The original shape of batch.pos is [10, 1024, 3] and the original size of batch.relative_quat_world is [10, 4].

**Comment by rusty1s** [comment]
You can still do that, but you need a specific batch vector for relative_quad_world. You can get it by making use of `DataLoader(dataset, follow_batch=['relative_quad_world'])` and use `data.relative_quad_world_batch` instead.

**Comment by richardrl** [comment]
@rusty1s I tried this on edge_indices, it doesn't work

```
to_dense_batch(data.edge_index, data.edge_index_batch)

** RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/richard/improbable/venvs/minimum_bandu_venv/lib/python3.6/site-packages/torch_scatter/scatter.py", line 31, in scatter_add
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    return scatter_sum(src, index, dim, out, dim_size)
           ~~~~~~~~~~~ <--- HERE
  File "/home/richard/improbable/venvs/minimum_bandu_venv/lib/python3.6/site-packages/torch_scatter/scatter.py", line 12, in scatter_sum
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    index = broadcast(index, src, dim)
            ~~~~~~~~~ <--- HERE
    if out is None:
        size = src.size()
  File "/home/richard/improbable/venvs/minimum_bandu_venv/lib/python3.6/site-packages/torch_scatter/utils.py", line 13, in broadcast
    for _ in range(src.dim(), other.dim()):
        src = src.unsqueeze(-1)
    src = src.expand_as(other)
          ~~~~~~~~~~~~~ <--- HERE
    return src
RuntimeError: The expanded size of the tensor (2) must match the existing size (2048) at non-singleton dimension 0.  Target sizes: [2].  Tensor sizes: [2048]

```

```
(Pdb) data.edge_index.shape
torch.Size([2, 2048])
(Pdb) data.edge_index_batch.shape
torch.Size([2048])

```

**Comment by rusty1s** [comment]
For `edge_index`, you can make use of `torch_geometric.utils.to_dense_adj`.
