### ISSUE TITLE
RuntimeError with torch.utils.bottleneck

### ISSUE THREAD

**Issue by mariolinovIC** [pyg-team/pytorch_geometric#1451]
Hi, 

I am trying to profile a script that I am using for training. The script works perfectly but when I profile it with torch.utils.bottleneck I get the following error the third time the script is run by the profiler:

`    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 23007, 23012, 23013, 23015) exited unexpectedly
`

Any idea?

Cheers, 

Mario

**Comment by rusty1s** [comment]
This seems to be more PyTorch than PyG related, see *e.g.*, [here](https://github.com/pytorch/pytorch/issues/5301). Not much I can do here :(
