### ISSUE TITLE
Chebconv & GCNConv

### ISSUE THREAD

**Issue by SYSUHPK** [pyg-team/pytorch_geometric#1456]
## ❓ Questions & Help
Hello, I test GCNConv corresponds to one round of neighborhood aggregation (k=1) and Chebconv (k=1)，I think output should be the same(or not so different), but the result is not.  The difference is not small, why?

Source code:
![image](https://user-images.githubusercontent.com/47689665/88299133-992bcf00-cd34-11ea-87e6-04803b5bccb0.png)

import torch
from torch_geometric.datasets import Planetoid
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, ChebConv
import numpy as np
from torch_geometric.data import Data

class Net(torch.nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        **self.conv1 = GCNConv(1,1)
        self.conv1 = ChebConv(1,1,1)**
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        return x 

torch.manual_seed(1) 

edge_index = torch.tensor([[0, 1, 1, 1, 2, 3],
                           [1, 0, 2, 3, 1, 1]], dtype=torch.long)
x = torch.tensor([[1.], [2.], [3.], [4.]], dtype=torch.float)
data = Data(x=x, edge_index=edge_index)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
data = data.to(device)

model.train()
out = model(data)
print(out)
![image](https://user-images.githubusercontent.com/47689665/88299335-d2643f00-cd34-11ea-9208-ca06563d9325.png)

**Comment by rusty1s** [comment]
The aggregation of `GCNConv` and `ChebConv` is different, even for `k=1`, *e.g.*, `ChebConv` transform central node features diffrently from neighboring node features, while `GCNConv` does not. In general, `GCNConv` is a more simplified version of `ChebConv`.
