### ISSUE TITLE
ImportError with GENConv, DeepGCNLayer, RandomNodeSampler

### ISSUE THREAD

**Issue by rangan2510** [pyg-team/pytorch_geometric#1458]
I am trying to replicate examples/ogbn_proteins_deepgcn.py in Kaggle Kernels. 

In the first cell, I am simply installing the PyG and OGB using the following:
`! pip install ogb`
`!pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html`
`!pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html`
`!pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html`
`!pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html`
`!pip install torch-geometric`

In the second, cell, I am importing torch and PyG
`import torch`
`from torch.nn import Parameter`
`import torch.nn.functional as F`
`print(torch.version.cuda)`
`import torch_geometric.transforms as T`
`from torch_geometric.nn import GCNConv,SAGEConv`
`from torch_geometric.nn import GENConv, DeepGCNLayer`
`from torch_geometric.data import RandomNodeSampler`
`from ogb.nodeproppred import PygNodePropPredDataset, Evaluator`

Here, I am getting an import error
`---------------------------------------------------------------------------`
`ImportError                               Traceback (most recent call last)`
`<ipython-input-4-cf5d9093cdf6> in <module>`
`      8 import torch_geometric.transforms as T`
`      9 from torch_geometric.nn import GCNConv,SAGEConv`
`---> 10 from torch_geometric.nn import GENConv, DeepGCNLayer`
`     11 from torch_geometric.data import RandomNodeSampler`
`     12 `
` `
`ImportError: cannot import name 'GENConv' from 'torch_geometric.nn' (/opt/conda/lib/python3.7/site-packages/torch_geometric/nn/__init__.py)`

The code executes when I do not import GENConv or DeepGCNLayer or RandomNodeSampler

**Comment by haofanwang** [comment]
I also met with this import error.

**Comment by rusty1s** [comment]
Hi everyone, please note that `GENConv` and DeepGCN are currently only included in the master branch and not yet fully released. You will need to install PyG from source to play around with it.
