### ISSUE TITLE
Graph R-CNN: Propagation rule depending on both edge and node features

### ISSUE THREAD

**Issue by zc-alexfan** [pyg-team/pytorch_geometric#147]
## ❓ Questions & Help

Hi, 

I am trying to implement a scene graph generation model called [Graph R-CNN](https://arxiv.org/pdf/1808.00191.pdf). It is a variation of GCN. *I am wondering what would be the easiest way to implement?*

Given a scene graph with nodes (bounding boxes of objects) and edges (connections between bounding boxes) where each predicate (connecting two nodes) is an edge. There are node and edge features. 

There are separate propagation rule for nodes and edges: 
- For node propagation, each node aggregates its neighbouring edge features and all other node features (skip-connect). 
- For edge propagation, each edge aggregates itself and its neighbouring nodes (bounding boxes). Again, both node and edge features. 

**My confusion:** the aggregation rule for the node or edge depends on **both the node feature and the edge feature**. 

**What would be the best way to implement in Py-Geometric? (or is it possible?) Because the formulation in the tutorial seems to assume only aggregate node features from node features.**

**Comment by rusty1s** [comment]
Hi,
this should be straightforward to implement in PyG. I suggest using the `MessagePassing` base class for node-propagation, and using a custom op for edge propagation. This should boil down to something like this:
```python
class SceneGraphConv(MessagePassing):
    def forward(self, x, edge_index, edge_attr):
        # Aggregate neighbouring edge features
        out_x = self.propagate(edge_index, edge_attr)

        # Aggregate neighboring nodes for each edge.
        row, col = edge_index        
        out_edge_attr = edge_attr + transform(x[row]) + transform(x[col])
        return out_x, out_edge_attr

    def message(self, edge_index, edge_attr):
        # Aggregate edge features ala GAT.
```
I would be very happy if you could PR this operator once finished :)

**Comment by zc-alexfan** [comment]
Thanks for the fast reply! I am definitely trying to implement the Graph RCNN. 

Just to confirm my understanding of your tips: 

1. `edge_index` is a list of indices in COO format indicating which edges a particular node is connecting to (non-squared adjacency matrix); `edge_attr` is the features of each edge. 
2. The `forward` pass starts by doing the node propagation to obtain `x_out`; then the two `transform` functions are just two linear mapping matrix to change channel width and add back to the edge features to obtain the new edge features `out_edge_attr`. 

I am a bit confused by the `message` function comments. Could you elaborate a bit more?

**Comment by rusty1s** [comment]
This is mostly pseudo-code, sorry! But everything you say is right. `message()` defines the messages of message passing started by `self.propagate` (the documentation provides a tutorial about this).
