### ISSUE TITLE
Filters/Kernels of SplineConv

### ISSUE THREAD

**Issue by adhikarirsr** [pyg-team/pytorch_geometric#1475]
Here's a `SplineConv` network:

```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SplineConv(1, 64, dim=2, kernel_size=5)
        self.conv2 = SplineConv(64, 64, dim=2, kernel_size=5)
        self.conv3 = SplineConv(64, 64, dim=2, kernel_size=5)
        self.conv4 = SplineConv(64, 1, dim=2, kernel_size=5)

    def forward(self, data):
        data.x = F.elu(self.conv1(data.x, data.edge_index, data.edge_attr))
        data.x = F.elu(self.conv2(data.x, data.edge_index, data.edge_attr))
        data.x = F.elu(self.conv3(data.x, data.edge_index, data.edge_attr))
        data.x = self.conv4(data.x, data.edge_index, data.edge_attr)

        return data.x
```
I am just training it on MNIST grid graph data. After an epoch of training, I just want to see what kind of filter it has learned. This is what I did:

```
wl1 = modelscn.to('cpu').conv1.weight
wl1t = wl1.detach().numpy()
tl = []
tl1= []

for i in range(0,64):
    tl = []
    for j in range(0,25):
        tl.append(wl1t[j][0][i])
    tl1.append(tl)
tl1np=np.array(tl1)
```
I plotted using:

```
#filters from layer 1
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,10))
fig.subplots_adjust(hspace=0.4, wspace=0.01)
ix =1

for i in range(0, len(tl1np)):
    ax = fig.add_subplot(8,8,ix)
    plt.imshow(tl1np[i].reshape(5,5))
    ix = ix + 1
plt.tight_layout()
plt.show()
```
This is what I got: https://imgur.com/a/Q4CewRb
It looks anisotropic (which I expected), however, I am not sure if I am plotting the correct filters here because in figure 6 of this paper(https://arxiv.org/pdf/1711.08920.pdf) it looks smooth and I am not sure how to understand the directionality of the filter. Since it's 5X5 filter, is it just looking at 25 edges that is connected to the node? How does it learn the direction of the nodes?

**Comment by rusty1s** [comment]
Your code looks fine to me. However, you only plot the discrete weights, while the `SplineConv` uses this weights to compute B-Spline basis functions. In the most simple case (degree=1), this corresponds to an *interpolation* between the different weights.
