### ISSUE TITLE
PyTorch and system CUDA versions don't match, but PyTorch still works

### ISSUE THREAD

**Issue by shobrook** [pyg-team/pytorch_geometric#1476]
## ❓ Questions & Help

Hi,

I'm running Ubuntu 20.04 and recently installed CUDA, PyTorch, and PyTorch Geometric. However, my PyTorch and system CUDA versions don't match:
```bash
$ python -c "import torch; print(torch.version.cuda)"
>>> 10.2

$ nvcc --version
>>> 11.0
```
As a result, when I import `torch_geometric` I get the following exception:
```
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory
```
The thing is, I can still use CUDA to train non-GNN models in PyTorch with no problems:
```bash
$ python -c "import torch; print(torch.cuda.is_available())"
>>> True
```
How is this possible? And is there any way to get PyTorch Geometric working without downgrading to CUDA v10.2?

Thanks for the help, and for making a great library!

**Comment by rusty1s** [comment]
That's a tricky question. It looks like `cudatoolkit` does not provide the `cusparse` library, which requires PyG to find a matching `torch.version.cuda` and CUDA installation. I'm not sure if you can get around this problem by simply copying `libcusparse.so.10` to your CUDA library.

**Comment by rusty1s** [comment]
To follow up, it seems like `torch-sparse` looks for `libcusparse.so.10` in `/usr/local/cuda`, and not in the `conda cudatoolkit` repository. This may be fixable by adding the `cudatoolkit` path to `LD_LIBRARY_PATH`.
