### ISSUE TITLE
memory management during mini-batching 

### ISSUE THREAD

**Issue by abasak24** [pyg-team/pytorch_geometric#1495]
## ❓ Questions & Help

Hi,
I have a question on the GPU device memory management during mini-batching. I am actually following the GraphSAINT example where training happens in subgraphs produced by GraphSAINTRandomWalkSampler. 

In the **train()** function, the following loop goes on.

**for data in loader:
        data = data.to(device)**

When the second subgraph is loaded to GPU device memory, can I ask what happens to the first subgraph? Does it continue to remain in the GPU device memory? Or is there some additional memory management going on under the hood? If so, could you please point me to some resources/documentation where I can learn about it? 

Thanks!

**Comment by rusty1s** [comment]
The good thing of PyTorch is that you do not need to care about memory management at all (it makes use of the Python garbage collector). The first data tensor will be automatically removed from the device once it is no longer of use.
