### ISSUE TITLE
problem about using nn.Conv1d to replace linear？

### ISSUE THREAD

**Issue by MichaleWong** [pyg-team/pytorch_geometric#1502]
I want to replace linear with conv1d, but encounter error:
_Excepted 3-dimensional input for 3-dimensional weight [x,x,x], but got 2-dimensional input of size [x,x] instead_

how to convert pyg feature[num_points, num_channels] into the input of nn.conv1d

**Comment by rusty1s** [comment]
You need to create input shapes of size `[batch_size, in_channels, num_nodes]` to apply `conv1d`:
```python
from torch_geometric.utils import to_dense_batch

x, mask = to_dense_batch(data.x, data.batch)  # [batch_size, num_nodes, in_channels]
x = x.transpose(1, 2)  # [batch_size, in_channels, num_nodes]
conv1d(x, ...)
```
