### ISSUE TITLE
About voxel grid pooling

### ISSUE THREAD

**Issue by Wang-Tianyu** [pyg-team/pytorch_geometric#1510]
Hi,
I am trying to implement a layer that puts a voxel grid over a space where my point clouds are saved, computes the center position of points of each voxel and finally aggregates points in each voxel into the center position via GNN.
Thus, I need to be able to generate assign indexes just like radius operation.
One of my early attempts involves called radius operation  the voxel_grid operation.

`def voxel_mean_pool_(pos, batch, start, end, size):

    voxel_cluster = voxel_grid(pos, batch, size =size, start = min_pos, end = max_pos)
    voxel_cluster, perm = consecutive_cluster(voxel_cluster)
    batch_sample = batch[perm]

    # pos_sample is listed in voxel cluster index increaing order
    pos_sample = scatter_mean(pos, voxel_cluster, dim = 0)
    voxel_cluster_sample = torch.arange(pos_sample.size(0), dtype=torch.long, device=pos.device)

    # need large enough radius to cover entire voxel
    out_index, in_index = radius(x = pos, y = pos_sample, r = size * 10, batch_x = voxel_cluster, batch_y = voxel_cluster_sample, max_num_neighbors=64)

    return (out_index, in_index), pos_sample, batch_sample, voxel_cluster, voxel_cluster_sample
`
However, when I print out the maximum distance from voxel members to their center points, I get values much larger than the voxel size and definitely larger than the diagonal distance of voxels.
I am not sure whether this is a bug or not. Code below.

`      pos_d = torch.norm(pos_sample[out_index] - pos[in_index], p = None, dim = 1) # >> distance larger than 0.25/16
`

After more consideration, I managed to get ride of the radius operation and below is what I get.
Do you think this is the right way to carry out this operation?

`def voxel_mean_pool(pos, batch, start, end, size):

    voxel_cluster = voxel_grid(pos, batch, size = size, start = min_pos, end = max_pos)
    voxel_cluster, perm = consecutive_cluster(voxel_cluster)
    batch_sample = batch[perm]

    # pos_sample is listed in voxel cluster index increaing order
    pos_sample = scatter_mean(pos, voxel_cluster, dim = 0)
    voxel_cluster_sample = torch.arange(pos_sample.size(0), dtype=torch.long, device=pos.device)

    out_index = voxel_cluster
    in_index = torch.arange(pos.size(0), dtype=torch.long, device=pos.device)

    return (out_index, in_index), pos_sample, batch_sample, voxel_cluster, voxel_cluster_sample
`

Cheers

**Comment by rusty1s** [comment]
That's absolutely correct. The assign index is given by `(torch.arange(num_nodes), cluster)`, and you can use it to pool your node positions and node features.
