### ISSUE TITLE
Implementing SplineCNN and possible model on modelnet40 for classification problem

### ISSUE THREAD

**Issue by shangguan9191** [pyg-team/pytorch_geometric#1513]
Dear Matt,

I want to implement SplineCNN on modelnet10, what kind of modification do i need to do？ shall i just change a forward pass?

and do you happend to know this repo: https://github.com/nicolas-chaulet/torch-points3d as well, they have only implementation for segmentation. is there anyway to just load their model. e.g. Kpconv, then use your setting to achieve the implementation? like this example : https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_classification.py

**Comment by rusty1s** [comment]
You can replace the `PointConv` call with a `SplineConv` call, but there are some crucial differences:
1. For `SplineConv`, there needs to exist initial node features, e.g., via `torch_geometric.transform.Constant`
2. Spatial relations should be passed as edge features `edge_attr` and need to lay in the interval `[0, 1]`

TorchPoints3D is built upon PyG, and also provides different aggregation schemes, *e.g., partial dense. AFAIK, you can directly load their model into PyTorch and use it in conjunction with the PyG datasets.

**Comment by shangguan91** [comment]
Thank you for the explaination for SplineConv. i have futher question of implementing more models for my own dataset:
let us take the RsConv for example[https://github.com/nicolas-chaulet/torch-points3d/torch_points3d/applications/rsconv.py](url) 
I have already reshaped my data into Data(pos=[1024, 3], x=[1024, 3], y=[1]) and imported model. However, i do not know how to write forward base on model:
![image](https://user-images.githubusercontent.com/64595972/89805748-65bfb180-db36-11ea-9159-8cb76efb8b58.png).
how should i start, it looks way more complex than normal example i have seen in pyg repo.

**Comment by shangguan91** [comment]
thank you! and i have noticed that you have 5 models for Point Cloud classification. if i wanna write a paper for althgorithm camparison, could be MPNN be baseline for this task?

**Comment by rusty1s** [comment]
Yes, I think this is a reasonable baseline. You can also compare against PointNet and PointNet++.
