### ISSUE TITLE
In GATConv operator, what will be edge_index for arbitrary shapes graphs ? suitable pooling operation with GATConv

### ISSUE THREAD

**Issue by ssbahade** [pyg-team/pytorch_geometric#1520]
## ❓ Questions & Help

Hi, 
I am using the GATConv operator for graph classification problem. As input to the operator I should pass (X, edge_index).  What would be the edge index for the arbitrary size graphs.
**Example:** I have image of original size (1024,1024,3), and cropping many subgraphs from original size graph. cropped subgraphs size X have different size and shape i.e (1, 7, 3), (1, 16, 3), (1, 144,3)....etc. 
1) What would be the edge_index for each subgraph?. 
2) Is that each arbitrary subgraph I consider as a new fresh graph and starting their edge_index from node zero. i.e (1,16,3) for this feature I have cropped the graph having nodes number (4000,4001........etc) 16 node. shall I consider fresh graph and assign node 0 to node 4000 or same node keeping same subgraph node 4000 and find edge_index based on that.  
3) please suggest suitable pooling operator with GATConv to work with this graph classification.

**Comment by rusty1s** [comment]
1. That depends on the task at hand. If your nodes correspond to some kind of clustering of the input data, you may want to connect nodes that are spatially near, *e.g.*, via `torch_geometric.transforms.radius`
2. Each subgraph is a fresh graph and should start from index 0.
3. That's hard to tell. In most cases, global pooling works fine. As an alternative, you can look at Top-k pooling.
