### ISSUE TITLE
TypeError: knn_graph() takes from 2 to 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by RoyHirsch** [pyg-team/pytorch_geometric#1521]
## ❓ Questions & Help
Hi,
I'm new to pytorch_geometric, while trying to call knn_graph() I encountered the following error:
TypeError: knn_graph() takes from 2 to 6 positional arguments but 7 were given

It is raises from the initialization of the torch-cluster knn_graph function.
I'm using Ubuntu 18.04, pytorch 1.4 and cuda: 10.0.

Maybe there is some inconsistency with the pytorch_geometric installation for my env and the torch-cluster package version?

**Comment by rusty1s** [comment]
You may want to upgrade `torch-cluster`.

**Comment by ranahanocka** [comment]
I have the same issue on my machine. I'm using Ubuntu 18.04, pytorch 1.4 and cuda: 10.1 , and using torch-cluster-1.5.4.

Does knn_graph support pytorch 1.4?

**Comment by rusty1s** [comment]
Yes, it does. It's just that the API of `knn_graph` slightly changed since we added a `num_workers` argument. If you do not want to upgrade, I suggest that you remove those arguments from all `knn_graph` calls in PyTorch Geometric.

**Comment by ranahanocka** [comment]
cool. I upgraded to Pytorch 1.6 and now it is working. Thanks :)

**Comment by suyouooooo** [comment]
> Yes, it does. It's just that the API of `knn_graph` slightly changed since we added a `num_workers` argument. If you do not want to upgrade, I suggest that you remove those arguments from all `knn_graph` calls in PyTorch Geometric.

I have the same issue on my machine too. I have Ubuntu 18.04.5 LTS, pytorch 1.4 and cuda 10.0. However,  I found no version of Pytorch 1.6 for cuda 10.0. In this case, what should I do except remove those arguments from all knn_graph calls in PyTorch Geometric?

**Comment by rusty1s** [comment]
It is generally not possible for us to provide backward compatibility to older PyTorch versions, so upgrading PyTorch is the way to go here. As far as I know, your local CUDA does not need to match with the one provided by PyTorch (conda will install its own `cudatoolkit`), but you need to point to this CUDA library in `$LD_LIBRARY_PATH` (mine is located in `~/miniconda3/lib`).
