### ISSUE TITLE
Difference between EdgeConv and DynamicEdgeConv

### ISSUE THREAD

**Issue by chowkamlee81** [pyg-team/pytorch_geometric#1523]
## ❓ Questions & Help

Not able to understand Difference between EdgeConv and DynamicEdgeConv. Kindly give some details has a confusion on this

**Comment by rusty1s** [comment]
The `EdgeConv` applies the Edge Convolution operator on a predefined graph-structure (`forward(self, x, edge_index)`), while the latter creates graph-structure on-the-fly, based on the nearest neighbors in the feature space.
