### ISSUE TITLE
Is max_pool Chanel wise?

### ISSUE THREAD

**Issue by mrk4576** [pyg-team/pytorch_geometric#1546]
## ❓ Questions & Help

The function `global_max_pool` is channel-wise, as mentioned in the [docs](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/glob/glob.html#global_max_pool). 

Are the functions `max_pool` and `max_pool_x` channel-wise, as well, or do they consider the whole features across all dimensions and compare across all dimensions at the same time? Reading the [docs](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/pool/max_pool.html#max_pool) I am not sure if they do or not.

Thanks for your help.

**Comment by rusty1s** [comment]
Both `max_pool` and `max_pool_x` apply max pooling channel-wise, similar to the `global_max_pool` method.
