### ISSUE TITLE
Does the Flickr/Yelp dataset support for inductive learning?

### ISSUE THREAD

**Issue by mengliu1998** [pyg-team/pytorch_geometric#1547]
## ❓ Questions & Help

Hi Matthias,

From the original [GraphSAINT](https://arxiv.org/pdf/1907.04931.pdf) paper, the Flickr dataset is utilized for inductive learning, where neither attributes nor connections of the test nodes are present during training. 

I am investigating this dataset In Pytorch Geometric, and I found it seems to support transduction learning only because we do not have an adj_train here. The same problem exist for Yelp and (Reddit?). Is my understanding correct? And do you have any recommendations for evaluating methods on these datasets under an inductive setting?

Thank you in advance.

**Comment by rusty1s** [comment]
For inductive learning, you need to manually convert your data object into an inductive one. That's actually quite easy:
```python
edge_index = torch_geometric.utils.subgraph(data.train_mask, edge_index, relabel_nodes=True)
x = data.x[data.train_mask]
y = data.y[data.train_mask]
```

**Comment by mengliu1998** [comment]
This is great. Thank you, Matthias!
