### ISSUE TITLE
One hot encoding for TUDataset

### ISSUE THREAD

**Issue by ferdisvea** [pyg-team/pytorch_geometric#1552]
## ❓ Questions & Help

Hey,
I was wondering if there is any easy way around converting node features to one-hot encoding when using the TUDataset class?

I am working with spreading graphs from twitter. Each graph represent a Tweet and the retweets of the tweet, where each node has a timestamp as a feature. The timestamp is the time difference between the node and the original tweet/source.

I tried to convert the timestamps to something smaller (minutes/hours) in order for me to not run out of memory when converting to one-hot encoding, but I loose a lot of information that way...

**Comment by rusty1s** [comment]
There is currently no way to allow that for the `TUDataset`. It seems like you are saving your graphs following the `TUDataset` format, is this correct? IMO, a better and much more flexible way to handle that would be to write your own processing code.
