### ISSUE TITLE
run SAGPool code on dataset COLLAB

### ISSUE THREAD

**Issue by zeyuanyin** [pyg-team/pytorch_geometric#1557]
## To Reproduce

1.get dataset COLLAB by using `dataset = TUDataset(path, name="COLLAB")`
2.use  `Top-K Pooling` Framework and `pytorch_geometric.nn.SAGPooling`
3.run the code
4.bug is as follows.
```
Traceback (most recent call last):
  File "C:/Users/YZY1037/Desktop/new/SAG.py", line 136, in <module>
    model = SAGPool(dataset=dataset, num_layers=3, hidden=args.nhid).to(device)
  File "C:/Users/YZY1037/Desktop/new/SAG.py", line 50, in __init__
    self.conv1 = GraphConv(dataset.num_features, hidden, aggr='mean')
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch_geometric\nn\conv\graph_conv.py", line 37, in __init__
    self.lin = torch.nn.Linear(in_channels, out_channels, bias=bias)
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\modules\linear.py", line 77, in __init__
    self.reset_parameters()
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\modules\linear.py", line 80, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\init.py", line 324, in kaiming_uniform_
    std = gain / math.sqrt(fan)
ZeroDivisionError: float division by zero
```

## Expected behavior
The program can run correctly when dataset is DD or PROTEINS. When I change the dataset to COLLAB, the bug appears.

## Environment

* OS:windows 10
* Python version:3.6.10
* PyTorch version:1.5.1
* CUDA/cuDNN version:10.2
* GCC version:
* Any other relevant information:

## Additional context
I want to know why and how to solve it. Thanks.
And I'd like to know whether TUDataset can download and process all datasets in [http://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/](url) by only changing `name` in  `dataset = TUDataset(path, name="COLLAB")`.

**Comment by rusty1s** [comment]
This is to be expected since `COLLAB` does not come with any node features. You need to create them synthetically, *e.g.*, by making use of `torch_geometric.transforms.OneHotDegree`.

2. That's correct. You can process all datasets by just changing the name.

**Comment by pixar0407** [comment]
Have related question for author of this issue.

So, the final code would be like,
`max_degree = 0
for data in dataset:
    deg = torch_geometric.utils.degree(data.edge_index[1], num_nodes=data.num_nodes)
    max_degree = max(max_degree, max(deg).item())

p = torch_geometric.transforms.OneHotDegree(int(max_degree))
dataset.transform = OneHotDegree(int(max_degree))`


is it true?
I am also trying to make use of COLLAB for my GCN.
Thank you.

**Comment by SourceCode1037** [comment]
```
max_degree = 0
for data in dataset:
    deg = torch_geometric.utils.degree(data.edge_index[1], num_nodes=data.num_nodes)
    max_degree = max(max_degree, max(deg).item())

dataset.transform = torch_geometric.transforms.OneHotDegree(int(max_degree))
```

**Comment by pixar0407** [comment]
Thank you 👍

**Comment by pixar0407** [comment]
I have question!

Do you use COLLAB dataset as graph classification problem?
Because the initial dataset has no vertex label, only has one layer for one graph among 5000 graphs(e.g. dataset[0]=> Data(edge_index=[2,2352], y=[1])), it looks graph classification problem.

**Comment by rusty1s** [comment]
Yes, COLLAB is a graph classification dataset, so for each graph you have exactly one label to predict.

**Comment by czzzn** [comment]
Thanks for the solution. I'm wondering if it is possible to calculate the max_degree and assign the node features as a pre_transform?
