### ISSUE TITLE
how to add pos in qm9_nn_conv?

### ISSUE THREAD

**Issue by chenhust1995** [pyg-team/pytorch_geometric#1564]
hi,how to add pos in qm9_nn_conv?thanks

**Comment by rusty1s** [comment]
Do you want to add it to the node features? The `qm9_nn_conv` example already uses `pos` to compute the distances between atoms as edge features. If you want to additionally add it to the node features, you can do something like:
```python
x = torch.cat([data.x, data.pos], dim=-1)
```

**Comment by chenhust1995** [comment]
thanks，i will use your advice
