### ISSUE TITLE
run DiffPool code on dataset IMDB-BINARY、IMDB-MULTI、MUTAG

### ISSUE THREAD

**Issue by zeyuanyin** [pyg-team/pytorch_geometric#1578]
## To Reproduce

1.I change dataset to IMDB-BINARY in` /examples/proteins_diff_pool.py `

```
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data',
                'IMDB-BINARY_dense')
dataset = TUDataset(path, name='IMDB-BINARY', transform=T.ToDense(max_nodes),
                    pre_filter=MyFilter())
```
2.run the code, there is a bug:
```
Traceback (most recent call last):
  File "C:/Users/YZY1037/Desktop/new/di.py", line 147, in <module>
    train_loss = train(epoch)
  File "C:/Users/YZY1037/Desktop/new/di.py", line 125, in train
    output, _, _ = model(data.x, data.adj, data.mask)
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/YZY1037/Desktop/new/di.py", line 95, in forward
    s = self.gnn1_pool(x, adj, mask)
  File "D:\Users\YZY1037\Anaconda3\envs\gcn\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/YZY1037/Desktop/new/di.py", line 62, in forward
    batch_size, num_nodes, in_channels = x.size()
AttributeError: 'NoneType' object has no attribute 'size'
```

## Expected behavior
It's ok when dataset is PROTEINS. 
When I run DiffPool code on dataset IMDB-BINARY、IMDB-MULTI、MUTAG, the bug appears.

## Environment

* OS:windows10
* Python version:3.6.10
* PyTorch version:1.5.1
* CUDA/cuDNN version:10.2
* GCC version:
* Any other relevant information:

## Additional context
I want to know and how to solve it. Thanks.

**Comment by rusty1s** [comment]
This error occurs since those datasets do not come with any node features. A common work-around is to use the node degree as input features, as can be seen [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/datasets.py#L26-L38).

**Comment by SourceCode1037** [comment]
I add these code to my.  There is an error.

```
Traceback (most recent call last):
  File "C:/Users/YZY1037/Desktop/new/di.py", line 44, in <module>
    degs += [degree(data.edge_index[0], dtype=torch.long)]
TypeError: 'NoneType' object is not subscriptable
```

When I debug it, I find `data.edge_index={NoneType}None`. But `data.edge_index = {Tensor:2} tensor(...)` in COLLAB which does not come with any node features.

How to solve it？

**Comment by rusty1s** [comment]
I see. For `DiffPool`, we convert the `edge_index` representation into a dense one via `transforms.ToDense()`. You may want to apply this transform after computing the maximum node degree, as shown [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/datasets.py#L58-L59).
