### ISSUE TITLE
About Amazon Dataset

### ISSUE THREAD

**Issue by cjissmart** [pyg-team/pytorch_geometric#1581]
## ❓ Questions & Help

In the paper, pitfalls of graph neural network evaluation, the num_nodes of Amazon Computers/Photo is 13381/7487. However, the num_nodes of the two datasets is 13752/7650 when I use the function, Amazon of pytorch_geometric, to load the datasets. Why aren't these the same?

**Comment by rusty1s** [comment]
I'm not exactly sure what is causing this. We are loading the data directly from the `gnn-benchmark` repo.
