### ISSUE TITLE
Why the pointnet2 in benchmark is way faster than example?

### ISSUE THREAD

**Issue by shangguan9191** [pyg-team/pytorch_geometric#1598]
Dear Matt,

I am evaluating the time performance of algorithm. 
ps: Could you tell me also from your experience, how much faster or slower is pointnet2 than pointnet per epoch for modelnet10?

**Comment by rusty1s** [comment]
In practice, `PointNet2` is **a lot** slower than `PointNet`, since it involves computing knn-graphs repeatedly and perform neighboring point aggregation. I do not have timings for you though since this also depends on the number of layers and hidden dimensionalities.

**Comment by shangguan9191** [comment]
Sorry for not specify the question correctly, I mean you have two implementation for pointnet2, one is in example and the other is in benchmark for classification problem, why is that in benchmark fast 3 time faster than in in example

**Comment by shangguan9191** [comment]
![image](https://user-images.githubusercontent.com/64595972/92325027-91f02480-f047-11ea-98d0-b7924af3af26.png)
As, you can say i use 5 k folder to perform both for pointnet2 in example and pointnet2 in benchmark in your repo. The algorithm in benchmark perform 7times faster

**Comment by rusty1s** [comment]
The MLPs used in `examples/pointnet2_classification.py` are much deeper than the ones used in the benchmark repo, which might well explain the time differences. In general, you do not need such deep MLPs for ModelNet10, but the PointNet++ example tries to closely replicate the architecture from the PointNet++ paper.
