### ISSUE TITLE
We currently only have an implementation of the `mean` aggregator of GraphSAGE, which replaces lines 4 and 5 of the pseudocode with Eq. (2).

### ISSUE THREAD

**Issue by hamid-kiavarz** [pyg-team/pytorch_geometric#1600]
Hi, Can you help me to have a better understanding of Concatenation in this step? 
Does it mean we use the Mean of feature value of neighbors and node itself or we combine neighbor agg_oout with self node feature values?

**Comment by rusty1s** [comment]
We concatenate the mean of neighboring node features with the self node feature values.

**Comment by hamid-kiavarz** [comment]
Thanks. Does it mean to combine two vectors? So what would be the input of the first layer of NN?

**Comment by rusty1s** [comment]
I'm not sure I understand. The input to the first layer are always the node features `x` and the edge connectivity `edge_index`. Inside `SAGEConv`, it then performs `x @ weight_1 + mean_j x[j] @ weight_2`, which is identical to computing `cat([ x, mean_j x[j] ]) @ weight` (but a bit faster).
