### ISSUE TITLE
On the fly dataset generation

### ISSUE THREAD

**Issue by richardrl** [pyg-team/pytorch_geometric#1611]
In the docs, it says:

https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html?highlight=on%20the%20fly#frequently-asked-questions

```
from torch_geometric.data import Data, DataLoader
data_list = [Data(...), ..., Data(...)]
loader = DataLoader(data_list, batch_size=32)

```

that the above is the recommended way to create on the fly datasets.

But, that is not exactly correct, right? Because for me, on the fly means, that we generate every batch on the fly. 

The example code assumes you generate all the data at once. 

I am interested in quite a different use case; for me, I want to sample a fresh batch every time I do backprop. E.g., my neural network will likely never see the exact batch twice. This means I should generate batches on the fly, instead of generating all the data one time like in the example code snippet and loading a DataLoader.

What's the appropriate way to do this, while still using the BatchClass? I guess I could generate data as lists on the fly and use from_data_list to create batch objects... If that doesn't have much overhead that would probably be the right way

**Comment by rusty1s** [comment]
Your solution should work fine. If you really want to create batches on the fly, you can override the `collate` function of `torch.utils.data.DataLoader`, *e.g.*:
```python
from torch.utils.data import DataLoader

def collate(batch):
    # Create and return your batch object.

loader = DataLoader(range(num_examples), batch_size=1, collate_fn=collate)
```

**Comment by richardrl** [comment]
> Your solution should work fine. If you really want to create batches on the fly, you can override the `collate` function of `torch.utils.data.DataLoader`, _e.g._:
> 
> ```python
> from torch.utils.data import DataLoader
> 
> def collate(batch):
>     # Create and return your batch object.
> 
> loader = DataLoader(range(num_examples), batch_size=1, collate_fn=collate)
> ```

Hi, this is not possible right now because DataLoader class has the collate_fn hardcoded, instead of passed in as a default kwarg.

**Comment by rusty1s** [comment]
You need to use the `DataLoader` directly from PyTorch:
```
from torch.utils.data import DataLoader
```
