### ISSUE TITLE
Applying function to each batch

### ISSUE THREAD

**Issue by legohyl** [pyg-team/pytorch_geometric#1617]
## ❓ Questions & Help

Hi Matthias, I'm wondering if there's a way to apply functions (or algorithms) to each batch in an efficient manner? In my case, I wish to apply an algorithm that takes in representations from a GNN. So e.g. for 1 graph, we do the following:

```
wts = self.weight_transform(torch.cat((out[data.sorted_edges[:, 0], :], out[data.sorted_edges[:, 1], :]), dim=1))
wts = wts.view(n_nodes, n_nodes)
b_a, b_b = self.iter_simp_min_sum_batch_scatter(wts.unsqueeze(0), wts.t().unsqueeze(0), fixed_weights, 2)
```

where `out` is basically the outputs of a GNN in the torch_geometric format. Basically, `weight_transform` is just some NN that takes pairs of nodes and outputs a value i.e. edge value. I re-arrange these values and apply an algorithm `iter_simp_min_sum_batch_scatter` on it, where the function expects some `n x n` matrix to be input. The thing is, each graph can vary in size here. It's easy to do the batching if I adhere to the `torch_geometric` format but only for the GNN part. I'm having some troubles figuring out how to get the algorithm part working.

Thanks for any tips!

**Comment by rusty1s** [comment]
If you want to reshape your edge data to a dense format, you can have a look at the `torch_geometric.utils.to_dense_adj` function, which converts your edge representation into shape `[batch_size, num_nodes, num_nodes, num_edge_features]`. You can then apply your algorithm `iter_simp_min_sum_batch_scatter` in a batch-wise fashion. Hope this helps!
