### ISSUE TITLE
Creating large dataset for static graph

### ISSUE THREAD

**Issue by Sara-Za** [pyg-team/pytorch_geometric#1620]
Hello,
Thanks for this awesome library.
I have a question about how to create my own large dataset for the static graph. In my case, I have a single graph with many sets of features (i.e., the graph is fixed, but the node features and labels are changing). Currently, I'm adding "node_dim = 1" to my GCNconv layers to take care of a static graph with dynamic features, as you suggested in issue #857, and it works well for the small datasets. However, as I want to use larger datasets (add more sets of features to the same graph), I encounter memory problems. May you please tell me how I can create a large dataset on disk for this problem? 
let's say that instead of the following data object that I'm using now:

Data(edge_attr=[77612, 1], edge_index=[2, 77612], edge_weight=[77612], test_mask=[320, 37849], train_mask=[320, 37849], x=[320, 37849, 57], y=[320, 37849])

I want to create the following data object:
Data(edge_attr=[77612, 1], edge_index=[2, 77612], edge_weight=[77612], test_mask=[32000, 37849], train_mask=[32000, 37849], x=[32000, 37849, 57], y=[32000, 37849])

**Comment by rusty1s** [comment]
Yeah, that might be a bit too much to handle for the GPU memory :)

In this case, a simple way to fix that would be to make use of mini-batches, *e.g.*:
```python
edge_index = data.edge_index.cuda()
loader = torch.utils.DataLoader(range(num_examples), batch_size=..., shuffle=True)

for idx in loader:
    x = data.x[idx].cuda()
    y= data.y[idx].cuda()
    # Call your model on the mini-batch
```

**Comment by Sara-Za** [comment]
Thanks for your quick response. I'll try your suggestion when I get to the point of training my model with the large data. But, before that, I have a question about how to make this large data objects on disk. This might be a very basic question as I'm new to Pytorch. It seems to me that the method for building large datasets you explained here [https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html] is for the cases when we have many graphs and, respectively, many data objects. How can I apply it to my case where I want to create a single massive data object.

**Comment by rusty1s** [comment]
you can just save your `data` using `torch.save`, or using the `InMemoryDataset`. Of course, your giant graph needs to be able to fit into your memory :)

**Comment by Sara-Za** [comment]
Yeah, my main problem is that the graph can't be fit into the memory I have:(
Thanks for helping anyhow:)

**Comment by srikanthmalla** [comment]
@rusty1s , InMemoryDataset performs the best. I want to keep using it but encountered same issue out of memory because of big dataset. 

Is there a way to do n chunks of memory, iterate across them and use InMemory on each chunk (to avoid this issue)? Does such functionality available in your dataloader? Any example to do this efficiently would be really helpful. Please let me know.

Best Regards,
Srikanth

**Comment by rusty1s** [comment]
Sadly no, since PyTorch cannot load chunks from tensors via `torch.load` (as least as far as I know), but there may exist some utility package to allow this.
