### ISSUE TITLE
Point Cloud Classification using PointNet++

### ISSUE THREAD

**Issue by amalin95** [pyg-team/pytorch_geometric#1626]
## ❓ Questions & Help

Hi, I'm a postgraduate student who new in programming. I have involve in a project on 'Point Cloud Classification using PointNet++'. The data used is in LAS file. Can somebody help me with this issue. I need to know how to get started with the project. I really appreciate if somebody can help me from the scratch. Please give me any guidelines/references/ sample/ tutorial that I can follow. I looking forward for your help.
Thanks in advance.

**Comment by tchaton** [comment]
https://github.com/nicolas-chaulet/torch-points3d

**Comment by amalin95** [comment]
> 
> 
> https://github.com/nicolas-chaulet/torch-points3d

Thank you for the help!!
