### ISSUE TITLE
Efficient way to extract node embedding

### ISSUE THREAD

**Issue by arglog** [pyg-team/pytorch_geometric#1629]
## ❓ Questions & Help

Suppose I run `GCNConv` on a batch of data, which has two graphs, one with 2 nodes, and the other with 3 nodes. The output of `GCNConv` is a `(5, #dim)` tensor. What I want in the next step is to reshape this tensor to a (zero-padded) tensor of node embeddings with the shape `(#graphs, #nodes, #dim)`. In this example, it would be `(2, 3, #dim)`, where the third node embedding of the first graph is zero-padded.

Of course I can manually iterate the `batch` tensor to assign each embedding to each graph, but I'm wondering if there is a more efficient way to do this (preferably on using PyTorch/PyG API on GPU)?

Thanks!

**Comment by rusty1s** [comment]
You can use `torch_geometric.utils.to_dense_batch` to achieve that :)

**Comment by smorad** [comment]
Does `to_dense_batch` stop the gradients during the backward pass?

**Comment by rusty1s** [comment]
No, gradients will flow through `to_dense_batch` just as one would expect :)

**Comment by arglog** [comment]
Thanks! This answered my question.
