### ISSUE TITLE
Why the time consumption of torch_geometric.data.DataLoader is expensive?

### ISSUE THREAD

**Issue by jwwu666** [pyg-team/pytorch_geometric#1662]
## ❓ Questions & Help

When I use torch_geometric.data.DataLoader to get mini-batch of dataset ENZYMES and the batch size is 128, the time consumption of 'for data in train_loader' is expensive which is more than half of the training time. 

dataset = TUDataset(path, name='ENZYMES', use_node_attr = True)
....
train_loader = Dataloader(train_dataset, batch_size=128)
for data in train_loader:
    .......

**Comment by rusty1s** [comment]
Iterating over training batches takes about 0.04 sec on my machine:
```python
import time
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader

dataset = TUDataset('data/TU', name='ENZYMES', use_node_attr=True)

train_loader = DataLoader(dataset, batch_size=128)

t = time.perf_counter()
for data in train_loader:
    pass
print(time.perf_counter() - t)
```
How long does it take for you?
