### ISSUE TITLE
Utilizing Edge Weights for Message Filtering

### ISSUE THREAD

**Issue by bsaghafi** [pyg-team/pytorch_geometric#1668]
I am wondering whether an implementation exists for utilizing edge weights in message passing of GNN. I want the messages from neighboring nodes to be multiplied by (normalized) edge weights when passing through the edges.

**Comment by reshinthadithyan** [comment]
You can check [NNConv](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/nn_conv.html). These are edge conditioned Message Filters.
