### ISSUE TITLE
RGCN node features

### ISSUE THREAD

**Issue by juanshu30** [pyg-team/pytorch_geometric#1669]
## ❓ Questions & Help

Hi, 

I read the code in example rgcn.py and I didn't see the model incorporating the node features. Is that because the data doesn't have node features? If I want to use the RGCN on the other graph data, how can I incorporate the features into the model. Thanks!

**Comment by rusty1s** [comment]
Yes, that is true, the data RGCN is operating on does not come with any node features. However, you can still use RGCN with node features by simply passing them to its forward call, *e.g.* `conv(x, edge_index, edge_type)`.

**Comment by rusty1s** [comment]
You need to replace
```python
self.conv1 = FastRGCNConv(data.num_nodes, 16, data.num_relations, num_bases=30)
```
with
```python
self.conv1 = FastRGCNConv(num_features, 16, data.num_relations, num_bases=30)
```
Here, the first argument denotes the input dimensionality of your node features, which needs to be adjusted in case features are present.
