### ISSUE TITLE
radius function not working from torch_geometric

### ISSUE THREAD

**Issue by ishitamed19** [pyg-team/pytorch_geometric#1672]
## 📚 Installation

I am using the following example as it is: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/pointnet2_classification.py

However, when I run it on my system, it throws an error saying: `TypeError: radius() takes from 3 to 6 positional arguments but 7 were given`

But then, as a lucky guess, I just changed `from torch_geometric.nn import radius` to `from torch_geometric.nn import radius ` and that seemed to work. Is there any reason, especially due to some conflicts during installation, that might have caused this issue?

## Environment

* OS: Ubuntu 16.04.11
* Python version: 3.7.3 
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.0
* GCC version: 5.4.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheel
* Any other relevant information: I did set all the requisite paths to my Cuda installation

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Yes, the input arguments of `torch_cluster.radius` slightly changed. Fixable by upgrading `torch-cluster` or by downgrading PyG to version 1.5.0. IMO, it is best to always use PyG with the latest PyTorch version, so please feel free to upgrade if that is possible :)

**Comment by rusty1s** [comment]
Also related: https://github.com/rusty1s/pytorch_geometric/issues/1673#issuecomment-699556584
