### ISSUE TITLE
Question on minibatching a torch_geometric.data.Data object. 

### ISSUE THREAD

**Issue by reshinthadithyan** [pyg-team/pytorch_geometric#1686]
## ❓ Questions & Help

Lets say there is a **torch_geometric.data.Data** object which is a huge graph with a lot of disconnected sub graphs. What is the best way to batch the Data object into such n disconnected graphs. Is that what **torch_geometric.data.dataloader** is doing?

**Comment by rusty1s** [comment]
You can create a list of data objects out of your single data object and pass them to the DataLoader.
