### ISSUE TITLE
About minibatch of graph and edge

### ISSUE THREAD

**Issue by starxchina** [pyg-team/pytorch_geometric#1689]
## ❓ Questions & Help

Hello, is there any way when I put a batch size of graph and edge(a batch size of different edges) into model in order to make each graph do different message passing?

**Comment by rusty1s** [comment]
Is there a specific use-case where this might be needed? I think one way to implement this is by "un-batching" the batch object via `to_data_list()`, and perform different message passing ops by iterating over the data list. However, that may result in increased runtimes.

**Comment by starxchina** [comment]
Thank you for your reply.
For example, I have two graphs A and B, and ecah graph has four nodes: 1,2,3,4. 
Graph A, the edges are 1->4, 2->3.
Graph B, the edges are 1->3, 2->4.
Now, I want to put them in a batch to forward. Besides separating batch in forward function, is there any way can I compute them together?

**Comment by rusty1s** [comment]
Well, in case they use the shall use the same GNN model, you can batch them together using `torch_geometric.data.DataLoader`. You can read more about it [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html).

**Comment by starxchina** [comment]
Ok, thank you. Let me read it carefully first
