### ISSUE TITLE
Format for the acknowledgement for using your repo

### ISSUE THREAD

**Issue by shangguan9191** [pyg-team/pytorch_geometric#1693]
Dear author,

I reimplement SplineCNN, Pointnet++ in your repo for my master thesis. How should I include your work in acknowledgement?

**Comment by rusty1s** [comment]
I hope that PyG helped you in writing your master thesis :) Please feel free to just cite its respective paper:
```
@inproceedings{Fey/Lenssen/2019,
  title={Fast Graph Representation Learning with {PyTorch Geometric}},
  author={Fey, Matthias and Lenssen, Jan E.},
  booktitle={ICLR Workshop on Representation Learning on Graphs and Manifolds},
  year={2019},
}
```
