### ISSUE TITLE
A question about Cora datasets

### ISSUE THREAD

**Issue by tanjia123456** [pyg-team/pytorch_geometric#1696]
Hello, I noticed that the GCN/GAT data sets are all processed by others. For my own data set, how should I make a data format similar to ind.cora.x?
I have now got the corresponding adjacency matrix, feature matrix and label matrix

**Comment by rusty1s** [comment]
That depends. The easiest way is to just load your data as numpy/torch tensors and pass them to the `Data` object, *e.g.*:
```python
adj = torch.from_numpy(adj)
data = Data()
data.edge_index = adj.nonzero().t()
data.x = torch.from_numpy(x)
data.y = torch.from_numpy(y)
```

**Comment by tanjia123456** [comment]
Sorry, I still can't understand it for a while, is there any tutorial or link?

**Comment by rusty1s** [comment]
Sadly no, but you may can take a look at all the dataset implementations. In general, the format in which we you want to save and load your data is completely up to you. In my opinion, the easiest way to save that data is by calling `torch.save`.

**Comment by tanjia123456** [comment]
Ok thank you, I will study again！
