### ISSUE TITLE
unsupported GNU version! gcc versions later than 5 are not supported!

### ISSUE THREAD

**Issue by hagianga21** [pyg-team/pytorch_geometric#170]
## Environment

* OS: Linux 18.04
* Python version: 3.6
* PyTorch version: 1.0.1
* CUDA/cuDNN version: 10.0.130 / 7.3.1
* GCC version: 7.3.0
* How you tried to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
Hi,
what is the error message of the installation?

**Comment by Xiaoshunxin** [comment]
Hi, I mett the same problem when I setup up the pytorch-sparse from source code. The error was showing follow:
`
running install
running bdist_egg
running egg_info
writing torch_sparse.egg-info/PKG-INFO
writing dependency_links to torch_sparse.egg-info/dependency_links.txt
writing requirements to torch_sparse.egg-info/requires.txt
writing top-level names to torch_sparse.egg-info/top_level.txt
reading manifest file 'torch_sparse.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_sparse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torch_sparse.spspmm_cuda' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include/TH -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-8.0/include -I/home/amax/anaconda2/envs/xsx_pyg/include/python3.6m -c cuda/spspmm.cpp -o build/temp.linux-x86_64-3.6/cuda/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
/usr/local/cuda-8.0/bin/nvcc -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include/TH -I/home/amax/anaconda2/envs/xsx_pyg/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-8.0/include -I/home/amax/anaconda2/envs/xsx_pyg/include/python3.6m -c cuda/spspmm_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/spspmm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/cuda-8.0/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda-8.0/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
error: command '/usr/local/cuda-8.0/bin/nvcc' failed with exit status 1
`

But, the version of the gcc is bigger than 5. I type the command:
`
(xsx_pyg) amax@amax:~/xsx/software/pytorch_sparse-master$ gcc --version
gcc (crosstool-NG 1.23.0.449-a04d0) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

I don't know where the problem come from.

Thank you for the help!

**Comment by hagianga21** [comment]
Thank you so much for your rep, this is the error message. I tried couple of ways but cannot fix.

Collecting torch-scatter
  Using cached https://files.pythonhosted.org/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz
Building wheels for collected packages: torch-scatter
  Running setup.py bdist_wheel for torch-scatter ... error
  Complete output from command /home/gtruong/anaconda3/envs/geometric/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zontn27e/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-wgxn8soz --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
  creating build/lib.linux-x86_64-3.6/test
  copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
  copying test/utils.py -> build/lib.linux-x86_64-3.6/test
  creating build/lib.linux-x86_64-3.6/torch_scatter/utils
  copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
  copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
  copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
  running build_ext
  building 'torch_scatter.scatter_cpu' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/cpu
  gcc -pthread -B /home/gtruong/anaconda3/envs/geometric/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/TH -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/THC -I/home/gtruong/anaconda3/envs/geometric/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -B /home/gtruong/anaconda3/envs/geometric/compiler_compat -L/home/gtruong/anaconda3/envs/geometric/lib -Wl,-rpath=/home/gtruong/anaconda3/envs/geometric/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu/scatter.o -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
  building 'torch_scatter.scatter_cuda' extension
  creating build/temp.linux-x86_64-3.6/cuda
  gcc -pthread -B /home/gtruong/anaconda3/envs/geometric/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/TH -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/gtruong/anaconda3/envs/geometric/include/python3.6m -c cuda/scatter.cpp -o build/temp.linux-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /usr/local/cuda/bin/nvcc -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/TH -I/home/gtruong/anaconda3/envs/geometric/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/gtruong/anaconda3/envs/geometric/include/python3.6m -c cuda/scatter_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
  In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                   from <command-line>:0:
  /usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
   #error -- unsupported GNU version! gcc versions later than 5 are not supported!
    ^~~~~
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by rusty1s** [comment]
Maybe [this](https://github.com/fireice-uk/xmr-stak/issues/1990) fixed the issue.

**Comment by hagianga21** [comment]
I cannot fix this file (/usr/local/cuda/include/host_config.h) because first it would affect somebody code and I also don't have admin account to fix this file. They discussed about modifying cmake file, how could I do that when installing torch-scatter?

**Comment by rusty1s** [comment]
Wouldn't it be easier to just downgrade gcc?

**Comment by hagianga21** [comment]
Hmm... As I run it on Lambda Quad where a lot of users run their code on so I don't have an admin account to downgrade it. Also, in the future, it maybe makes some conflicts with somebody else code.

**Comment by rusty1s** [comment]
As far as I know, you can install gcc user-only via anaconda.
