### ISSUE TITLE
Memory leak during GCN training

### ISSUE THREAD

**Issue by niklasamslgruber** [pyg-team/pytorch_geometric#1702]
## ❓ Questions & Help

I'm currently training a 2-layer GCN model. I noticed that the memory needed for creating the model in each epoch is increasing heavily (already in the first epoch). During my trainings the memory consumption went up to more than 40 GB. Running the model in Google Colab even leads to a `tcmalloc: large alloc` error. The memory issue happens on both GPU and CPU training. The dataset used for it has about 7000 lines of text (R8 Reuters dataset). I marked the exact line where the memory increases heavily in the code snippet below. Is there any way to optimize the memory usage to be able to actually run the model?

 ```
def train(train_data, val_data, saver):
    train_data.init_node_feats(FLAGS.device)
    val_data.init_node_feats(FLAGS.device)
    model = create_model(train_data)
    model = model.to(FLAGS.device)
    pytorch_total_params = sum(p.numel() for p in model.parameters())
    print("Number params: ", pytorch_total_params)
    moving_avg = MovingAverage(FLAGS.validation_window_size, FLAGS.validation_metric != 'loss')
    pyg_graph = train_data.get_pyg_graph(FLAGS.device)
    optimizer = torch.optim.Adam(model.parameters(), lr=FLAGS.lr, )

    epoch_losses = []
    losses = []
    for epoch in range(FLAGS.num_epochs):
        t = time.time()
        model.train()
        model.zero_grad()
		# Memory starts to increase here until it crashes
        loss, preds_train = model(pyg_graph, train_data)
        loss.backward()
        optimizer.step()

        loss = loss.item()
        with torch.no_grad():
            val_loss, preds_val = model(pyg_graph, val_data)
            val_loss = val_loss.item()
            eval_res_val = eval(preds_val, val_data, False)
            epoch_losses.append(val_loss)
            losses.append(loss)
        
    best_model = saver.load_trained_model(train_data)
    return best_model, model

```

**Comment by rusty1s** [comment]
That shouldn‘t be the case, obviously. My guess is that PyTorch cannot release the computation graph after each epoch. Do you store some internal state somewhere inside your forward computation?

**Comment by niklasamslgruber** [comment]
I debugged the memory usage and I think I found the parts which are causing the high memory. However, I don't know why this happens.

The memory increases by 20 GB when the return statement of the `forward()` method of the `GCNConv(MessagePassing) `class is called
```
  def forward(self, x, edge_index, edge_weight=None):
        """"""
        if x.is_sparse:
            x = torch.sparse.mm(x, self.weight)
        else:
            x = torch.matmul(x, self.weight)

        if not self.cached or self.cached_result is None:
            edge_index, norm = GCNConv.norm(edge_index, x.size(0), edge_weight,
                                            self.improved, x.dtype)
            self.cached_result = edge_index, norm

        edge_index, norm = self.cached_result


        # Until here the memory usage is about 1GB, after the next line it's 20GB


        return self.propagate(edge_index, x=x, norm=norm)
```

Then the message(...) method is called, the return state here causes the memory usage to **increase by additional 20GB**
```
   def message(self, x_j, norm):
        # Memory increases here from 20GB to 40GB
        return norm.view(-1, 1) * x_j
```

Afterwards the memory usage is 40GB in the very first epoch. So apparently the memory doesn't add up while the number of epochs increases but one single epoch causes the high memory usage. Any idea @rusty1s ?

**Comment by rusty1s** [comment]
How big is your graph actually?

**Comment by niklasamslgruber** [comment]
About 15.000 nodes with weighted edges between them

**Comment by rusty1s** [comment]
Can you try using `SparseTensor` instead of `edge_index`, as suggested [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html).
```python
import torch_geometric.transforms as T

data = T.ToSparseTensor()(data)
out = gcn_conv(data.x, data.adj_t)
```

**Comment by anuradhawick** [comment]
@rusty1s your last reply is quite helpful as I have the same issue.

However, I am embedding a graph (DNA sequencing reads graph) of size; |nodes| = 157708 and |edges| = 41661144 and the sparse matrix has density=0.17%. I expect graphs to get much bigger and a sparse matrix could be the only way to go.

Unfortunately the model.recon_loss(z, adj_t) fails with `SparseTensor has no len()` error. So I still have to use the edge list here. Could you suggest a workaround?

TIA

**Comment by rusty1s** [comment]
Yes, you still need to use the edge list for `model.recon_loss`, but this does not result in a higher memory-footprint as you are required to compute edge representations anyway:
```python
z = model.encode(x, adj_t)
col, row, _ = adj_t.coo()
loss = model.recon_loss(z, torch.stack([row, col], dim=0)
```
You can reduce the memory footprint by only reconstructing a subset of positive edges though, for example via:
```python
z = model.encode(x, adj_t)
col, row, _ = adj_t.coo()
perm = torch.randperm(col.size(0))[:1000]  # Only reconstruct 1000 random samples
loss = model.recon_loss(z, torch.stack([row[perm], col[perm]], dim=0)
```

**Comment by anuradhawick** [comment]
Thanks heaps for the suggestion! Cheers!
