### ISSUE TITLE
Message passing with more than two nodes

### ISSUE THREAD

**Issue by vxfung** [pyg-team/pytorch_geometric#1710]
Hi, I'm still a beginner with gnn's. I've been looking to implement a layer where three nodes are considered, i.e. a concatenation of x_i, x_j, x_k (or x_l, x_m, ...etc if needed) is done. Is there a straightforward way to do this with the existing message passing class? If not, what would be the recommended way to do this?

**Comment by rusty1s** [comment]
Are you referring to hypergraphs? This is currently not really covered by the `MessagePassing` interface, so you may need to write logic for that by yourself.
