### ISSUE TITLE
How to get value pass through using knn?

### ISSUE THREAD

**Issue by xinanhuang** [pyg-team/pytorch_geometric#1723]
## ❓ Questions & Help
Just recently picked up this library and was having trouble figuring out how to pass the back-propagation values through the [knn function](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/pool.html#knn). Since knn function returns index only I assume I need to set other things in order for the back-propagation of the network to work as intended (currently its broken). If anyone could point me the right direction that would be awesome. Thanks!

**Comment by rusty1s** [comment]
That's correct. `knn` computation has now backward computation since its output is discrete. I'm not sure what you are trying do to, but this should not be the reason for any errors you are receiving during back-propagation.
