### ISSUE TITLE
Could I create 2 different batches in data

### ISSUE THREAD

**Issue by hagianga21** [pyg-team/pytorch_geometric#1727]
## ❓ Questions & Help
Hi, could I create 2 different batches in data? For example, one batch for x and another batch for posx, I mean x and posx are in different shape. Or I have to create 2 separate data set?
Thanks for your help.

**Comment by rusty1s** [comment]
You can pass the `follow_batch` argument to the `DataLoader, *e.g.*:
```python
loader = DataLoader(dataset, batch_size, follow_batch=['posx']
```
