### ISSUE TITLE
split dataset for cross-validation 

### ISSUE THREAD

**Issue by zeyuanyin** [pyg-team/pytorch_geometric#1752]
## ❓ Questions & Help
I want to split the dataset for 10-fold cross validation, I use `sklearn.model_selection.StratifiedKFold` to split the dataset, and it returns the index list. But ` IndexError: Only integers, slices (`:`), list, tuples, and long or bool tensors are valid indices (got int32).` TUdataset can't be splited by index list. Can you give some suggestions?

**Comment by rusty1s** [comment]
As the error message suggest, you need to convert the indices to PyTorch long tensors first, *e.g.*:
```python
index = torch.from_numpy(index).to(torch.long)
sub_dataset = dataset[index]
```
