### ISSUE TITLE
radius operation

### ISSUE THREAD

**Issue by Wang-Tianyu** [pyg-team/pytorch_geometric#1754]
Hi, I have a couple of questions regarding the radius operation.
If the number of nodes within the radius is larger than max_num_neighbors, will the returned nodes be deterministic?
If it is not deterministic, is there a way to return the closest max_num_neighbors nodes?
If I do not want to set max_num_neighbors, is it safe to set it to a really large number like the maximum value of int32?

Thanks.

**Comment by rusty1s** [comment]
1. They will be deterministic for CPU but not for GPU
2. This would require substantial re-write of the GPU kernels
3. This is not a good idea when running on GPU since it creates a `[num_nodes, max_num_neighbors]` tensor on the fly.
