### ISSUE TITLE
Confusion about how Pytorch Geometric works

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#1761]
## ❓ Questions & Help

I am confused about the operation of Pytorch Geometric. For example, this was taken from the guide online to define the GCNConv example: 

```
import torch
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import add_self_loops, degree

class GCNConv(MessagePassing):
    def __init__(self, in_channels, out_channels):
        super(GCNConv, self).__init__(aggr='add')  # "Add" aggregation (Step 5).
        self.lin = torch.nn.Linear(in_channels, out_channels)

    def forward(self, x, edge_index):
        # x has shape [N, in_channels]
        # edge_index has shape [2, E]

        # Step 1: Add self-loops to the adjacency matrix.
        edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))

        # Step 2: Linearly transform node feature matrix.
        x = self.lin(x)

        # Step 3: Compute normalization.
        row, col = edge_index
        deg = degree(col, x.size(0), dtype=x.dtype)
        deg_inv_sqrt = deg.pow(-0.5)
        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        # Step 4-5: Start propagating messages.
        return self.propagate(edge_index, x=x, norm=norm)

    def message(self, x_j, norm):
        # x_j has shape [E, out_channels]

        # Step 4: Normalize node features.
        return norm.view(-1, 1) * x_j
```

I don't understand how `message` works: 
1. If I load data into `x` in `forward`, it will concatenate all the batch graphs, correct? So N refers to the total number of nodes in the entire batch, and E refers to the total number of edges in the entire batch?
2. Why is the shape of `x_j` [E, out_channels]? To my understanding, `x_j` is node specific (ie. a neighbor `j` of `i`), so why are we including all the edges in all the graphs here?

**Comment by rusty1s** [comment]
1. That's correct.
2. We process all neighbors of all nodes in parallel. Therefore, the first dimension of `x_j` can be seen as the batch dimension.

**Comment by vymao** [comment]
If I test this on Cora, I see the following: 

```
Data(edge_index=[2, 10556], test_mask=[2708], train_mask=[2708], val_mask=[2708], x=[2708, 1433], y=[2708])
```

However, looking at the dimensions of the `forward` and `propagate` inputs, I see this: 
```
x: 
torch.Size([2708, 1433])
edge_index: 
torch.Size([2, 10556])
x: 
torch.Size([2708, 16])
x_j: 
torch.Size([13264, 16])
norm: 
torch.Size([13264])
```
Why is the size of `x_j` now 13264?

**Comment by rusty1s** [comment]
The `GCNConv` adds self-loops to the graph: `10556 + 2708 = 13264`

**Comment by vymao** [comment]
I see, thanks. I was also confused about Pytorch Geometric's negative_sampling method: what exactly are negative edges? I had some understanding through node2vec but I'm unsure how it applies here.

**Comment by rusty1s** [comment]
Negative edges refer to all zero-entries in the adjacency matrix, which correspond to the pairs of nodes that shouldn't be connected.

**Comment by vymao** [comment]
Thanks. On a separate note, when we define out our Dataset class and `process` method, do we have to manually send anything to the gpu using `to()` for this to be processed there?

**Comment by rusty1s** [comment]
You are free to do this on your own. For example, we also do this for the `WillowObjectClass` dataset, which involves getting features out of a VGG16 (see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/willow_object_class.py#L141-L142)).
