### ISSUE TITLE
Is there a code example for graph classification？

### ISSUE THREAD

**Issue by ysgncss** [pyg-team/pytorch_geometric#1769]

**Comment by rusty1s** [comment]
There are several examples, *e.g.*:
* https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py
* https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mnist_graclus.py
* https://github.com/rusty1s/pytorch_geometric/blob/master/examples/multi_gpu/distributed_batching.py

There is also a newly introduced Colab notebook regarding graph classification, see https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html.
