### ISSUE TITLE
Neighbor sampling in SAGE layer

### ISSUE THREAD

**Issue by juliosol** [pyg-team/pytorch_geometric#1771]
I am working on a graph neural network for link prediction using the SAGE layer. I am basing my architecture on the examples I have seen on [this ogb link prediction example](https://github.com/snap-stanford/ogb/blob/master/examples/linkproppred/ppa/gnn.py), [the  reddit example in torch geometric](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py) and [the ogb example in torch geometric](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/ogbn_products_sage.py).

My main misunderstanding is why in the reddit and torch geometric ogb example are we using the NeighborSampler class (which I understand the original paper puts strong emphasis on the generation of neighbor samples as part of the algorithm) and why in the ogb link prediction example there is no use of the NeighborSampler class? Would it be correct to say that in the ogb link prediction example we are basically propagating the node feature vectors through all the neighbors instead of just through a selected number of neighbors? 

Thanks for clarifying this for me and for your help! If you know of any source that covers this and I missed, I would greatly appreciate it!

**Comment by rusty1s** [comment]
That's correct. If your graph does fit into memory, there is generally no need to apply any sampling (since it complicates the implementation). Note that OGB also provides a link prediction example based on sampling, see [here](https://github.com/snap-stanford/ogb/blob/master/examples/linkproppred/citation/sampler.py).

**Comment by juliosol** [comment]
Thanks your answer makes sense to me! I missed that example, I will check it out.
