### ISSUE TITLE
About GCN applys in Mnist_SP

### ISSUE THREAD

**Issue by zeranyan** [pyg-team/pytorch_geometric#1776]
## ❓ Questions & Help

Hi , i havea  question about using GCN in Mnist_SP dataset. When i use batch_size=64 in DataLoader, the GCN  layers  are  
 **self.conv1 = GCNConv(1, 32, cached=True)
 self.conv2 = GCNConv(32, 64, cached=True)**
After conv2, i got matrix **torch.Size([5184, 10])** , where 5184=64*81. Now how can  i  readout the matrix to vectors for classification in the batch.

**Comment by rusty1s** [comment]
When using `DataLoader`, you should remove the `cached=True` option for `GCNConv`. For global readout, you can make use of our [global pooling functions](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#module-torch_geometric.nn.glob). You can find a basic example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/gcn.py).

**Comment by zeranyan** [comment]
> When using `DataLoader`, you should remove the `cached=True` option for `GCNConv`. For global readout, you can make use of our [global pooling functions](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#module-torch_geometric.nn.glob). You can find a basic example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/gcn.py).

OK, thanks, the GCN is working. 
These has an another problem about the dataset. Because i want to generate the Mnist_sp dataset with different numbers of superpixel, i use the from torch_geometric.transforms.ToSLIC and RadiusGraph to immplement this work. However i get the following regular graph:

![image](https://user-images.githubusercontent.com/45200605/97964438-be2fe380-1df3-11eb-843f-9961db04a2f1.png)

which likes a rectangle.
The dataset coming from torch_geometric.datasets.MNISTSuperpixels is irregular... like this:
![image](https://user-images.githubusercontent.com/45200605/97964676-1ff04d80-1df4-11eb-8d3e-589762b0e3a9.png)

Does such data affect model training? Can my dataset be processed into such irregular graphs?

**Comment by rusty1s** [comment]
As far as I know, SLIC is known for providing rather "grid-like" superpixels. I think it is worth it to play around with its arguments quite a bit, see [here](https://scikit-image.org/docs/dev/api/skimage.segmentation.html?highlight=slic#skimage.segmentation.slic), especially `enforce_connectivity`.

**Comment by zeranyan** [comment]
> As far as I know, SLIC is known for providing rather "grid-like" superpixels. I think it is worth it to play around with its arguments quite a bit, see [here](https://scikit-image.org/docs/dev/api/skimage.segmentation.html?highlight=slic#skimage.segmentation.slic), especially `enforce_connectivity`.

Sure, i'll research about its args. Thanks for your answers, it really helps me a lot. 
In addition, whether the graph is regular or irrgular. SplineConv performed great on them, but the GCN performed baddly... I define the 2 layers GCNconv with hidden=64 before 2 layers of Linear, but the acc in Mnist is less than 60%...

**Comment by rusty1s** [comment]
This is to be expected for GCN since it cannot learn any meaningful features. You can boost its performance by adding node positions to its features:
```python
data.x = torch.cat([data.x, data.pos], dim=-1)
```
You lose translation invariance though.

**Comment by ZulunZhu** [comment]
So how do we try a different number of superpixels except for 75 nodes?

**Comment by rusty1s** [comment]
You can do this manually by loading an image dataset and using the `ToSLIC` of PyTorch Geometric.
