### ISSUE TITLE
About MoNet GMMConv.py

### ISSUE THREAD

**Issue by cjissmart** [pyg-team/pytorch_geometric#1778]
## ❓ Questions & Help

I noticed the forward function of GMMConv has two parameters and two parameters with default values.
![image](https://user-images.githubusercontent.com/37531166/97694411-6d8a5480-1a9a-11eb-992c-3e8a43609af8.png)
For the edge_attr, it seemly can be set as None. However, if I do so, it raises an error when I do a node classification task for Cora:
![image](https://user-images.githubusercontent.com/37531166/97694922-294b8400-1a9b-11eb-9725-cf4c88921412.png)

![image](https://user-images.githubusercontent.com/37531166/97694778-fc976c80-1a9a-11eb-9e09-4a07f1e65a7c.png)

I find the error caused by the line:
![image](https://user-images.githubusercontent.com/37531166/97695184-8f380b80-1a9b-11eb-8f9d-7622ee14cd68.png)

For the edge_attr, it seemly can't be set as None.
I'm confused that the Cora dataset doesn't edge_attr. How I set the value of edge_attr for the node classification tasks?

**Comment by rusty1s** [comment]
Yeah, it is marked as optional because in case you are using `SparseTensor`, we expect edge attributes to be included there, e.g.:
```python
adj = SparseTensor(row=edge_index[0], col=edge_index[1], value=edge_attr)
```
MoNet needs edge attributes/pseudo coordinates, and in case they are not given, the paper suggests to generate them by yourself, e.g. via node degrees (check Sec. 5.2 in the [paper](https://arxiv.org/pdf/1611.08402.pdf)).

**Comment by cjissmart** [comment]
Thanks for your reply! whether do I need to construct a two-tuples list ![image](https://user-images.githubusercontent.com/37531166/97703434-8994f280-1aa8-11eb-87c0-321de0970733.png) according to the edge index? Then, the edge attributes are a tensor with shape [num_edges, 2].

**Comment by rusty1s** [comment]
Yes, exactly.

**Comment by cjissmart** [comment]
Thanks very much! ! !
