### ISSUE TITLE
About running PYG on 30 series GPU

### ISSUE THREAD

**Issue by LZhangMorilab** [pyg-team/pytorch_geometric#1789]
## ❓ Questions & Help

The GA102 chips is not supported by cuda verision lower than 11.0, but the latest PYG only support pytorch 1.6.0 and cuda 10.2. Is there any way to run PYG on RTX3090 GPU? Thank you.

**Comment by rusty1s** [comment]
I'm currently in the process of providing wheels for CUDA 11.0 (should be ready by tomorrow). In the meantime, you can install the external packages from source via:
```
pip install torch-scatter ...
```

**Comment by LZhangMorilab** [comment]
okay, thank you. Good luck
