### ISSUE TITLE
How to use muti-GPU to train with DataListLoader and my own dataset?

### ISSUE THREAD

**Issue by yanty123** [pyg-team/pytorch_geometric#1790]
## ❓ Questions & Help

Here I have a big graph built by myself. so I have to sub it into sub-graphs and train it on muti-GPUs.
First of all, I sample it with ‘RandomNodeSampler’ and try to use 
`loader=DataListLoader(data_,batch_size=2,sampler=data_sub)`
to train the model on muti-GPU. 
However it says 
`ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=<torch_geometric.data.sampler.RandomNodeSampler object at 0x7fa8dc493048>`
It seems that I can use the sampler together with the DatalistLoader.
So how can I use both the sampler and DatalistLoader?

Thank you!

`data_=Data(torch.tensor(dataset.x,dtype=torch.float),adj)
data_sub=RandomNodeSampler(data_,16)
loader=DataListLoader(data_,batch_size=2,sampler=data_sub)
model = DataParallel(model)
`

**Comment by rusty1s** [comment]
I suggest that you are looking into distributed training instead of using `DataParallel`. We provide an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py).

**Comment by yanty123** [comment]
> I suggest that you are looking into distributed training instead of using `DataParallel`. We provide an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling.py).

ok thank you ! I will try it later, it is that I don't want to learn how to do it with distributed training but to do it with `DataListLoader` .
However, its fine to solve the problem. If there are some easy ways to do it with `DataListLoader` and `DataParalled`, please tell me! Thank you.

**Comment by rusty1s** [comment]
There isn't actually, that's why i suggested to use distributed training. It's implementation is also quite straightforward since you can define a sampler for each machine.

**Comment by yanty123** [comment]
> There isn't actually, that's why i suggested to use distributed training. It's implementation is also quite straightforward since you can define a sampler for each machine.

Okay, thank you!  I also want to ask if there are some problems that if I try to apply my own dataset.Is it ok if I replace `dataset` with my own `[Data]`？

**Comment by rusty1s** [comment]
That should work just fine.

**Comment by yanty123** [comment]
> That should work just fine.

ok, thank u!

**Comment by yanty123** [comment]
> That should work just fine.

Sir, I come back with a  problem when using distibuted training. It broken after I sampled the data and tried to feed into model.
Here is the main codes and the Error information:
`data_=Data(torch.tensor(data.x,dtype=torch.float),adj)
    dataset=[data_]`
`train_loader = NeighborSampler(dataset[0].edge_index, node_idx=None,
                                   sizes=[10], batch_size=512, shuffle=True,
                                   num_workers=0)
    if rank==0:
        subgraph_loader = NeighborSampler(dataset[0].edge_index, node_idx=None, sizes=[-1],
                                      batch_size=512, shuffle=False,
                                      num_workers=12)`
`    for epoch in range(200):
        model.train()
        for batch_size,n_id,adjs in train_loader:
        # sub.cuda()
            if epoch % 1 == 0:`

**Comment by rusty1s** [comment]
Please upgrade your `torch-sparse` version if that's possible.
