### ISSUE TITLE
Segmentation network for PointCNN

### ISSUE THREAD

**Issue by edshkim98** [pyg-team/pytorch_geometric#1793]
## ❓ Questions & Help

Hi, I am currently using pytorch_geometric library to build a segmentation network for PointCNN.
In PointCNN network, the author uses farthest point sampling technique which samples the furthest point, hence reduces the number of the points.
However, as author says in the paper, there should be deconvolution or upsampling where the number of points are increased.
For example, pointnet++ uses interpolation but not with PointCNN.
Do you know how to perform deconvolution for PointCNN with pytorch_geometric?

Thank you and I look forward to hearing from you soon.

**Comment by edshkim98** [comment]
Or is the PointCNN's deconvolution just pure concatenation with the previous convolution layer and x-conv?

**Comment by rusty1s** [comment]
You can find an example for PointCNN on the segmentation task here: https://github.com/rusty1s/pytorch_geometric/issues/1470
I hope that gets you going!

Best,
Matthias
