### ISSUE TITLE
How to incorporate auxiliary input information in geometric models

### ISSUE THREAD

**Issue by asadabbas09** [pyg-team/pytorch_geometric#1818]
## ❓ Questions & Help

Thanks for awesome work.

I'm trying to use [SpiralNet++](https://github.com/sw-gong/spiralnet_plus)/SplineConv/GMMConv for CFD analysis (something like this [paper](https://arxiv.org/abs/1810.08217) but for 3D) and getting good results.

I would like to know what's the best way to incorporate auxiliary input information (other than input coordinates and spiral sequences/edges) in the network.

For example, I would like to introduce input freestream velocity (x,y, z-direction) and angle of attack (scaler value) to the network.

Many Thanks.

**Comment by rusty1s** [comment]
Can't you just use these features as input features to your network?

**Comment by asadabbas09** [comment]
One way is to concatenate extra information with input coordinates. 

But I'm confused that what if I have only one single scaler value (e.g. angle of attack = 30) as auxiliary input information, then I would concatenate 30 with all input coordinates (x,y,z, 30) making input coordinates 4 dimensional?

**Comment by rusty1s** [comment]
Yeah, that‘s what I meant.
