### ISSUE TITLE
Does GCNConv (and other modules) support batch graph input?

### ISSUE THREAD

**Issue by kevin3567** [pyg-team/pytorch_geometric#1825]
## ❓ Questions & Help

I am wondering if the GCNConv (and other modules in pytorch_geometric) support taking batch inputs? Specifically, my inputs are of the following dimensions:

**x** = (batch_size, num_of_nodes, node_features)
**edge_index** = (batch_size, 2, num_of_edges)
Note that some padding have been applied to **x** and **edge_index** to ensure that all samples within a batch have the same dimension.

I understand that there is a advanced mini-batching method which, if I understand correctly, diagonally stacks all adjacency matrices into a giant matrix. However, the project I am working on takes in multi-modal inputs, consisting of both text and graph fields (processed concurrently). Applying mini-batching technique would require significant changes in the codebase. Thus it is preferable to preserve the (batch, *, *) dimensionality.

Any help or suggestions is appreciated.

**Comment by rusty1s** [comment]
There is currently no such way. Currently, you can only apply a node feature tensor of shape `[batch_size, num_nodes, num_features]` to the same `edge_index` tensor of shape `[2, num_edges]`.

I'm not sure why you can not simply reshape your node features to shape `[batch_size * num_nodes, ...]` and use the PyG mini-batching approach. Since this is just a reshape, this does not seem to require significant changes.

**Comment by kevin3567** [comment]
Hi, 

Upon further inspection, it seems I could just reshape the **x** and **edge_index** separately. Specifically, the **x** vector could be reshaped to stack the nodes of each graph. The **edge_index** required some more work for diagonal stacking, as I had to keep track of a cumulative sum of total number of nodes already processed.

Just a follow up question, is there a specific function that already exists for performing the diagonal stacking operation automatically when given a tensor of dimension (batch_size, 2, num_of_edges)?

Thanks for you help.

**Comment by rusty1s** [comment]
You could do something like this (untested):
```python
offset = torch.arange(0, batch_size * num_nodes, num_nodes).view(-1, 1, 1)
edge_index = edge_index + offset
edge_index = edge_index.permute(1, 0, 2).view(2, -1)
```
