### ISSUE TITLE
Dataset creation I/O or process limited?

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#1844]
## ❓ Questions & Help
I'm trying to create an out-of-memory dataset using Data objects described below: 
```
    if use_orig_A: o_data = Data(node_features, edge_index, z=z, node_id=node_ids, num_nodes=num_nodes)
    else: o_data = None

    L_node_features, L_edges,  L_num_nodes, w, z1, z2, L_node_ids = construct_line_graph(node_ids, adj, z, node_features)
    edge_weight = torch.ones(len(L_edges))
    #print(L_edges)
    data = Data(L_node_features, L_edges.t(), edge_weight=edge_weight, y=y, w=torch.LongTensor(w), z1=torch.LongTensor(z1), 
        z2=torch.LongTensor(z2), node_id=L_node_ids, num_nodes=len(L_node_ids), o_data=o_data)
```
As you can see, one of the attributes of the Data object is another Data object (`o_data`). This is because I want to learn over two different types of graphs simultaneously. 

However, I found that the runtime for dataset creation (ie. creating the Dataset and saving the individual Data objects) is extremely slow, much slower than if I just set `o_data` to `None`. My plan was to parallelize the operation (ie. parallelize creating individual Data objects), but I'm not sure if this is I/O or process limited (in order to proceed with multithreading or multiprocessing). I would have thought that it was I/O limiting because each Data object (now almost twice as large) needs to be saved, but I checked the CPU usage and it seems near 100%. 

Does adding the Data object in `o_data` slow down the processing (as opposed to writing) significantly? What would you recommend?

**Comment by rusty1s** [comment]
I wouldn't expect that loading/processing two data objects slows down the processing by an unexpected margin. Not exactly sure what's causing this, sorry!

However, I don't think adding a `data` object into an existing one is very practical. For example, batching of such a data object will likely fail. IMO, a better way to approach this might be to return a tuple:
```python
def __getitem__(self, idx)
   data1, data2 = torch.load(...)
   return data1, data2
```
