### ISSUE TITLE
Directed graph message passing?

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#1845]
## ❓ Questions & Help

Just to clarify, for directed networks, message passing only occurs for outgoing edges, correct? Since those are the neighbors of a given node?

**Comment by rusty1s** [comment]
That's correct. Messages are send from source to target nodes.

**Comment by vymao** [comment]
So then when aggregating messages for any given node, PyTorch Geometric only considers incoming nodes?

**Comment by rusty1s** [comment]
It only passes messages to incoming nodes. In general, all layers are compatible with directed graphs, but some are only defined for undirected ones, *e.g.*, `GCNConv`.

**Comment by vymao** [comment]
I'm a bit confused; if messages are passed from source to target, isn't that outgoing?

**Comment by rusty1s** [comment]
Let me clarify: Messages are passed along outgoing edges (so basically to incoming nodes).

**Comment by kangzhang0709** [comment]
> Let me clarify: Messages are passed along outgoing edges (and are aggregated by incoming nodes).

![image](https://user-images.githubusercontent.com/32809802/124389668-bc1f7b00-dd1a-11eb-9e31-4cb2d6efb807.png)

if A is the target node,the node A embedding = aggr(X,Y)?  or A embedding = aggr(B,C) when use graph_sage_unsup model

**Comment by rusty1s** [comment]
A will receive messages from X and Y, so A = aggr(X, Y).

**Comment by kangzhang0709** [comment]
> A will receive messages from X and Y, so A = aggr(X, Y).

so，how to define the edge_index ?
edge_index = torch.tensor([[X,A],[Y,A],...]) or edge_index = torch.tensor([[A,X],[A,Y],...])
which on is correct?

**Comment by rusty1s** [comment]
It should be defined as:
```python
edge_index = torch.tensor([
    [X, Y, A, A, B, B, C],
    [A, A, B, C, D, E, F],
])
```
or
```python
edge_index = torch.tensor([
    [X, A],
    [Y, A],
    [A, B],
    [A, C],
    [B, D],
    [B, E],
    [C, F],
]).t()
```

**Comment by kangzhang0709** [comment]
> It should be defined as:
> 
> ```python
> edge_index = torch.tensor([
>     [X, Y, A, A, B, B, C],
>     [A, A, B, C, D, E, F],
> ])
> ```
> 
> or
> 
> ```python
> edge_index = torch.tensor([
>     [X, A],
>     [Y, A],
>     [A, B],
>     [A, C],
>     [B, D],
>     [B, E],
>     [C, F],
> ]).t()
> ```

Very Clearly !! Thanks for you reply!!!

**Comment by GaopanHuang** [comment]
> Let me clarify: Messages are passed along outgoing edges (and are aggregated by incoming nodes).

hi, rusty1s, if messages only passed along outgoing edges, then what for params "target_to_source" as follows:
![image](https://user-images.githubusercontent.com/5493168/125446000-2b3f4c20-e705-41b4-8787-fbc8670ed778.png)

**Comment by rusty1s** [comment]
You can reverse this message passing flow by setting `flow="target_to_source"`.

**Comment by GaopanHuang** [comment]
So when the directed graph is defined as:
`edge_index = torch.tensor([
    [X, Y, A, A, B, B, C],
    [A, A, B, C, D, E, F],
])`
By setting `flow=source_to_target`, A will receive messages from X and Y, A = aggr(X, Y), while `flow=target_to_source`, A will receive messages from B and C, then A = aggr(B, C)
Is that right?

**Comment by rusty1s** [comment]
That is correct.

**Comment by GaopanHuang** [comment]
> That is correct.

Thanks a lot!
