### ISSUE TITLE
Convolution in digraphs

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#1847]
## 🚀 Feature

[This](https://arxiv.org/pdf/2004.13970.pdf) is a paper that describes the convolutional operator applied to directed graphs, and [this ](https://proceedings.neurips.cc/paper/2020/file/cffb6e2288a630c2a787a64ccc67097c-Paper.pdf) is a better implementation. The results seem good for directed graphs. Would be great if these could be implemented; it seems the latter has already been done, but it would be great to make it official. 

Do any layers here handle address spectral-based convolution in digraphs?

**Comment by rusty1s** [comment]
This looks super interesting. I added it to the PyG [roadmap](https://github.com/rusty1s/pytorch_geometric/issues/1465). If you are interested, feel free to contribute :)

**Comment by reshinthadithyan** [comment]
Hello @rusty1s . I have a rough implementation intact with few changes from [DiGCN Github](https://github.com/flyingtango/DiGCN) . Message Passing Class is fine, Where should the pre-processing wrt the Receptive Fields sit within PyG?_(Should it be in torch_geometric.data like SAINTSampler?)_ I can share some rough construction wrt my understanding, please elaborate.

**Comment by rusty1s** [comment]
I think it's fine to add them as additional functions to the same file, just like we do in [`GCNConv`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/gcn_conv.py#L30).
