### ISSUE TITLE
What is the corresponding version of prerequisites for cu10.0? 

### ISSUE THREAD

**Issue by zhengx18** [pyg-team/pytorch_geometric#1848]
## 📚 Installation

I noticed that there are cpu, cu92, cu101, cu102, or cu110 for torch-geometric Installation. However, my cuda is 10.0 version, and I tried cu101, and it failed. I am wondering if there is the version  for cu10.0, thankyou for your kind help if there is any reply on my question.
## Environment

* OS: linux
* Python version:  3.6
* PyTorch version: 1.7
* CUDA/cuDNN version: 10.0
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
* Any other relevant information:

## Checklist

- [ ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

![image](https://user-images.githubusercontent.com/48192689/99892823-05ebb180-2cb4-11eb-8789-7d80a8e0906b.png)
![image](https://user-images.githubusercontent.com/48192689/99892825-156afa80-2cb4-11eb-9d87-32c7b729d176.png)

**Comment by rusty1s** [comment]
We follow PyTorch here and provide pre-built versions that match with the one PyTorch is providing (for example, PyTorch dropped cu100 installation in PyTorch 1.6.0). I suggest to install the CUDA version that matches the one of PyTorch:
```python
import torch
print(torch.version.cuda)
```
Note that you may need to add the miniconda3 `cudatoolkit` to `$LD_LIBRARY_PATH`. Mine is located in `~/.miniconda3/lib`.

**Comment by zhengx18** [comment]
> We follow PyTorch here and provide pre-built versions that match with the one PyTorch is providing (for example, PyTorch dropped cu100 installation in PyTorch 1.6.0). I suggest to install the CUDA version that matches the one of PyTorch:
> 
> ```python
> import torch
> print(torch.version.cuda)
> ```
> 
> Note that you may need to add the miniconda3 `cudatoolkit` to `$LD_LIBRARY_PATH`. Mine is located in `~/.miniconda3/lib`.

Thankyou for your reply, I will try to change my cuda version to match pytorch.
