### ISSUE TITLE
Docker Image with torch_geometric 1.7 cu110

### ISSUE THREAD

**Issue by mapa17** [pyg-team/pytorch_geometric#1868]
## ❓ Questions & Help
I did not find any torch_geometric base image for a dockerized project, and so I created my own in case anyone is interested:

Docker image based on **pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime** that contains torch_geometric 1.7 with cu110

```
docker pull mapa17/torch_geometric
```

**Comment by rusty1s** [comment]
Thank you :)

**Comment by zhangj1an** [comment]
thank you so much @mapa17 !!

**Comment by PreckLi** [comment]
great!

**Comment by sina-Kim** [comment]
thank you!

**Comment by Dave11233** [comment]
> ## ❓ Questions & Help
> I did not find any torch_geometric base image for a dockerized project, and so I created my own in case anyone is interested:
> 
> Docker image based on **pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime** that contains torch_geometric 1.7 with cu110
> 
> ```
> docker pull mapa17/torch_geometric
> ```

Hi, I docker pull the image and run it in a container, but there is no support of cuda with torch.cuda.is_available(), and the output is false; and found no NVIDIA Driver;
