### ISSUE TITLE
How to convert a pooled graph to networkx data?

### ISSUE THREAD

**Issue by jiaruHithub** [pyg-team/pytorch_geometric#1873]
## ❓ Questions & Help

I have a question about func ```to_networkx(G)```.
When A graph through pooling layers will use the code:
```x, edge_index, batch = data.x, data.edge_index, data.batch```
pooled graph will obtain the two matrix ```x1 and edge_index1```
how to use ```x1 and edge_index1``` convert to networkx data and draw a graph?
Thank you!

**Comment by rusty1s** [comment]
How about:
```python
from torch_geometric.data import Data
from torch_geometric.utils import to_networkx

G = to_networkx(Data(x=x, edge_index=edge_index), node_attrs=['x'])
```
