### ISSUE TITLE
Directed cluster-GCN

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#1885]
## ❓ Questions & Help

Hi, 

It seems to me that Cluster-GCN should theoretically only work on undirected graphs. Is there an implementation (or of any other efficient message passing layer) for digraphs?

**Comment by rusty1s** [comment]
It should work for directed graphs, also METIS can only operate on undirected graphs (it will automatically convert your directed graph to an undirected one to compute the partioning). In general, all GNN layers in PyG can operate on directed graphs, and we have some plans to incorporate dedicated GNN operators for directed graphs in the future.
