### ISSUE TITLE
Dataset Loader Error - REDDIT-MULTI-5k

### ISSUE THREAD

**Issue by ghost** [pyg-team/pytorch_geometric#1887]
hi,
when I tried to load Reddit-5K in google colab, I'm getting the following error. Is there any solution?

/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/tu_dataset.py in __init__(self, root, name, transform, pre_transform, pre_filter, use_node_attr, use_edge_attr, cleaned)
     63         self.cleaned = cleaned
     64         super(TUDataset, self).__init__(root, transform, pre_transform,
---> 65                                         pre_filter)
     66         self.data, self.slices = torch.load(self.processed_paths[0])
     67         if self.data.x is not None and not use_node_attr:

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     52                  pre_filter=None):
     53         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 54                                               pre_filter)
     55         self.data, self.slices = None, None
     56         self.__data_list__ = None

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     87 
     88         if 'download' in self.__class__.__dict__.keys():
---> 89             self._download()
     90 
     91         if 'process' in self.__class__.__dict__.keys():

/usr/local/lib/python3.6/dist-packages/torch_geometric/data/dataset.py in _download(self)
    139 
    140         makedirs(self.raw_dir)
--> 141         self.download()
    142 
    143     def _process(self):

/usr/local/lib/python3.6/dist-packages/torch_geometric/datasets/tu_dataset.py in download(self)
    129         os.unlink(path)
    130         shutil.rmtree(self.raw_dir)
--> 131         os.rename(osp.join(folder, self.name), self.raw_dir)
    132 
    133     def process(self):

FileNotFoundError: [Errno 2] No such file or directory: '/data/REDDIT-MULTI-5k/REDDIT-MULTI-5k' -> '/data/REDDIT-MULTI-5k/raw'

I'm using the following version:
torch-cluster           1.5.8
torch-geometric     1.6.3
torch-scatter           2.0.5
torch-sparse           0.6.8
torch-spline-conv   1.2.0

[package.txt](https://github.com/rusty1s/pytorch_geometric/files/5635713/package.txt)

**Comment by rusty1s** [comment]
Can you try passing in `REDDIT-MULTI-5K` instead of `REDDIT-MULTI-5k`? Dataset names are case-sensitive. The latter works for me.

**Comment by m-Tajari** [comment]
It works for me too. thanks.
