### ISSUE TITLE
Swap `i` and `j` indices in edge_index and then how to get edge_attr for the same graph ?

### ISSUE THREAD

**Issue by aGIToz** [pyg-team/pytorch_geometric#1913]
Hello all,

Given the graph:

```
edge_index = torch.tensor([[1,2,0,2,0,1],
                           [0,0,1,1,2,2]])
edge_attr = torch.tensor([5,4,3,2,1,0]) # feature values
```

**How to get this tensor `a`?**
```
a = torch.tensor([3,1,5,0,4,2])
```
The above tensor is the `edge_attr` which corresponds to the exactly same graph as above, but for swapped `i` and `j` indices in the `edge_index`, that is:
```
edge_index = torch.tensor([[0,0,1,1,2,2],
                           [1,2,0,2,0,1]])
```

**Comment by rusty1s** [comment]
This is basically a `transpose`, which can be achieved by sorting `edge_index`:
```python
import torch

edge_index = torch.tensor([[1, 2, 0, 2, 0, 1], [0, 0, 1, 1, 2, 2]])
edge_attr = torch.tensor([5, 4, 3, 2, 1, 0])  # feature values

num_nodes = 3
perm = (edge_index[0] * num_nodes + edge_index[1]).argsort()
print(edge_index[:, perm])
print(edge_attr[perm])
```

**Comment by aGIToz** [comment]
Thanks buddy !

Actually the problem I am dealing with is somewhat  more involved.

Consider this graph:

```python
# OBserve edge from 0 to 1, but NO edge from 1 to 0
edge_index = torch.tensor([[1, 2, 3, 2, 0, 1, 1], [0, 0, 1, 1, 2, 2, 3]]) 
edge_attr = torch.tensor([5, 4, 3, 2, 1, 0.5, 0.25])  # non zero feature values
```
*Observer that this graph is not symmetric unlike the previous graph and also the non zero feature values*

Now given the above graph, **how to get this tensor `n_edge_attr`?**

```python
n_edge_attr = torch.tensor([0, 1, 0.25, 0.5, 4, 2, 3])
```

The above tensor is the edge_attr for the following edge_index, which is obtained by swapping the `i` and `j` (`edge_index[1]` and `edge_index[0]`).
```python
edge_index = torch.tensor([[0, 0, 1, 1, 2, 2, 3], [1, 2, 3, 2, 0, 1, 1]]) 
```
Since originally there was no edge from `1 to 0` hence it assigned the value `0` i.e  `n_edge_attr[0] is  0`

**Comment by aGIToz** [comment]
Apparently the only way I am able to do this is as follows:

```python
edge_index = torch.tensor([[1, 2, 3, 2, 0, 1, 1], [0, 0, 1, 1, 2, 2, 3]]) 
edge_attr = torch.tensor([5, 4, 3, 2, 1, 0.5, 0.25])  # non zero feature values
graph = Data(edge_index = torch.tensor(edge_index, dtype=torch.long), edge_attr=edge_attr)

from torch_geometric.transforms import ToDense
todense = ToDense(4)
dense_graph = todense(graph)
```

Here I get the desired `n_edge_attr`:
```python
n_edge_attr = dense_graph.adj[edge_index[1], edge_index[0]]
#  tensor([0.0000, 1.0000, 0.2500, 0.5000, 4.0000, 2.0000, 3.0000]
```

*I am wondering if this is possible without explicitly converting my graph to dense adj graph as it is not memory efficient for large graph?*

**Comment by rusty1s** [comment]
I see what you are trying to do, but something like this is currently not supported (and probably never will since it contradicts the design philosophy of sparse tensors). I guess converting your graph to a dense one is the only way to achieve that.
