### ISSUE TITLE
output: nodes vs edges

### ISSUE THREAD

**Issue by iceland20** [pyg-team/pytorch_geometric#1929]
Most of the available intro examples focus on targeting nodes (e.g., classifying them). But how do I specify edges, in particular edge attributes, as graph NNs' output? Simply following the examples, losses are being computed for [num_nodes x dim_output], with dim_output specified in the forward function (e.g., just 1).

Thank you very much.

**Comment by rusty1s** [comment]
The general strategy for edge prediction/link prediction is to apply a GNN to compute node embeddings, and to then infer edge representations based on source and destination node embeddings:
```python
x = conv(x, edge_index)
src, dst = edge_index
out = MLP(torch.cat([x[src], x[dst]], dim=-1))
```

**Comment by iceland20** [comment]
Thanks very much @rusty1s!

Trying to implement your suggestion... I have a follow-up question, does this piece seem correct to you? I'm getting funny results, so trying to figure out whether it's the data or the code (and which part of it) is responsible.

```
num_n1 = 10
num_n2 = 10
num_out_features = 1

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        nn_NE = torch.nn.Sequential(torch.nn.Linear(data.num_edge_features, data.num_node_features*num_n1))
        self.conv = NNConv(data.num_node_features, num_n1, nn_NE, aggr='mean')
        
        self.nnEFP = torch.nn.Sequential(torch.nn.Linear(2 * num_n1, num_n2), torch.nn.ReLU(), torch.nn.Linear(num_n2, num_n2))
        
        self.W = torch.nn.Parameter(torch.randn(num_out_features, num_n2))
        self.b = torch.nn.Parameter(torch.randn(num_out_features))

    def forward(self, data):
        edge_attr, edge_index, x = data.edge_attr, data.edge_index, data.x

        x = self.conv(x, edge_index, edge_attr)
        
        src, dst = edge_index
        x = self.nnEFP(torch.cat([x[src], x[dst]], dim=-1))

        return torch.nn.functional.linear(x, self.W, self.b)
```

(Also, I'm generally interested in predicting edge features (for now, just a single feature) rather than existence of a link, but I guess it does not make a difference for your suggested approach.)

**Comment by rusty1s** [comment]
That looks correct to me.

**Comment by iceland20** [comment]
Great, appreciate your help!
