### ISSUE TITLE
Attention layer

### ISSUE THREAD

**Issue by GTaherzadeh** [pyg-team/pytorch_geometric#1930]
## ❓ Questions & Help

Hi there, 

I just wonder if there is an example for adding an attention layer to our network? And if not can you help me to add an attention layer to this example? https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py

Thanks

**Comment by rusty1s** [comment]
Are you referring to attention-based GNN layers or global readout layers? The former can just be implemented by adding an additional `GATConv` layer to your network. For the latter, you can find an example [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/global_attention.py).

**Comment by GTaherzadeh** [comment]
Thanks Matthias. How can I assign edge attributes when using the attention layer (GATConv)? Is there any example for that?

**Comment by rusty1s** [comment]
Currently not, and the `GATConv` layer needs to be modified in order to include edge attributes. The `TransformerConv` can handle edge features though.

**Comment by GTaherzadeh** [comment]
Is there any example of using TransformerConv in the github? I am not sure how to intergrate it to my network!

**Comment by rusty1s** [comment]
There is no real example of using `TransformerConv` besides in the recently added [Temporal Graph Network example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/tgn.py#L45). Its application is really similar to `GATConv` though:
```python
conv = TransformerConv(in_channels, out_channels, heads=2, edge_dim=edge_dim)
conv(x, edge_index, edge_attr)
```
