### ISSUE TITLE
GNNExplainer for a graph classification problem

### ISSUE THREAD

**Issue by Fatima-Haouari** [pyg-team/pytorch_geometric#1933]
## ❓ Questions & Help
Hi, 
I am using GCNConv for graph classification and I want to add the GNNExplainer to explain the predictions of my model. I found an example in the repository for GNNExplainer but what I understood is that it is for a node classification problem and that a node index should be provided. Could you please advice on how can I use it for my problem.

**Comment by rusty1s** [comment]
We currently only provide `GNNExplainer` functionality for node prediction tasks, but [this issue](https://github.com/rusty1s/pytorch_geometric/issues/1730) might be of interest to you.

**Comment by levulinh** [comment]
Hi @rusty1s, I am still curious why you have to inject the edge_mask in the message passing function? The original paper states that the new sub-graph is generated by the dot product 
![image](https://user-images.githubusercontent.com/15706978/102992864-71e56200-455f-11eb-8600-842fb9d3c90f.png)
What is the problem of generating a completely new subgraph and then run model on the newly created graph?
Thank you.

**Comment by rusty1s** [comment]
I'm not sure I understand. The above formula says that the adjacency matrix is given by the (soft) masked out adjacency matrix `A * sigma(M)`, so we need a way to perform inference in our GNN with masking capabilities. That is why we use the `edge_mask` in the message passing layers.
