### ISSUE TITLE
add_self_loops in ChebConv

### ISSUE THREAD

**Issue by Water-Silver** [pyg-team/pytorch_geometric#1941]
Hi! Sorry if there's a duplicate, looked over some issues but couldn't find one.
I have a questions on the implementation of ChebConv.

![image](https://user-images.githubusercontent.com/36324014/102757639-f942a200-43b4-11eb-943b-c208e1309132.png)
I figured that add_self_loops() is called twice in __norm__ function, once in get_laplacian and the other right before returning.
I get that calling add_self_loop() in the last stage is for filling in degree values with -1 which makes 
![image](https://user-images.githubusercontent.com/36324014/102758206-bd5c0c80-43b5-11eb-8405-d2bea905c443.png)
this term true.

But since add_self_loops() only concatenates self loop weights and indices,
shouldn't remove_self_loop() work better for avoiding unnecessary computation?
Having self loops with 1 weights and self loops with -1 weights in the same matrix seems confusing for me.
Please correct me if I'm understanding it wrong.

BTW I really appreciate your work. Thanks.

**Comment by Water-Silver** [comment]
Oops my bad. Didn't realize that scaling the weights in between may alter the self loop weights.
I guess having add_self_loops with fill_value -1 is necessary in cases wehre lambda_max is not 2.

**Comment by MHThomsen** [comment]
> Oops my bad. Didn't realize that scaling the weights in between may alter the self loop weights. I guess having add_self_loops with fill_value -1 is necessary in cases where lambda_max is not 2.

@Water-Silver Hi - Just stumbled upon this as well. Can you elaborate a bit on what you realized so it makes sense now? Would be a great help, thanks
