### ISSUE TITLE
from torch_geometric.nn import import GNNExplainer

### ISSUE THREAD

**Issue by gamzeakyol** [pyg-team/pytorch_geometric#1945]
## ❓ Questions & Help

Hi, 

I cannot import GNNExplainer in torch-geometric version 1.4.1 (Error is: ImportError: cannot import name 'GNNExplainer' from 'torch_geometric.nn'). Where can I import it?
Thanks,

Best,

**Comment by rusty1s** [comment]
You will need to upgrade to at least [PyG 1.5.0](https://github.com/rusty1s/pytorch_geometric/releases/tag/1.5.0).

**Comment by gamzeakyol** [comment]
Okay, thank you for your quick response.
