### ISSUE TITLE
How to create a customize Dataset by pytorch Geometric

### ISSUE THREAD

**Issue by HarlanZhou** [pyg-team/pytorch_geometric#1951]
## ❓ Questions & Help

I still understand how to  create a customize Dataset by pytorch geometric when I has read the document of CREATING YOUR OWN DATASETS.

How get my dataset just assigned the root?

**Comment by rusty1s** [comment]
Can you clarify your question? `root` denotes the root directory of the dataset (where raw and processed files are stored on disk).
