### ISSUE TITLE
TransformerConv output size is not out_channels

### ISSUE THREAD

**Issue by ZacharyKaplan** [pyg-team/pytorch_geometric#1953]
## 🐛 Bug

It seems that the ```torch_geometric.nn.TransformerConv``` layer will give an output which is of size ```out_channels * heads``` by default rather than just ```out_channels```. Though this only happens when ```concat=True```, it's a bit awkward to chain multiple transformer layers, as the sizes increase over iterations. Is this the correct behavior? Should there possibly be another linear component in ```torch_geometric.nn.TransformerConv``` to map back to ```out_channels```?

## To Reproduce
```
import torch
from torch_geometric.nn import TransformerConv

in_channels = 10
out_channels = 10
num_heads = 3

input_tensor = torch.rand((10,in_channels))
edge_index = torch.tensor([[1,2,3,4],[4,3,2,1]]).long()

tc = TransformerConv(
    in_channels=in_channels,
    out_channels=out_channels,
    heads=num_heads,
    concat=True,
    beta=0.5,
)
output = tc(input_tensor, edge_index)
assert output.shape[1] == out_channels

# >>> Assertion fails, output.shape[1] == (out_channels * num_heads)
```

## Environment

* OS: Centos 7
* Python version: 3.7.9
* PyTorch version: 1.6.0
* CUDA/cuDNN version: 10.1
* PyTorch Geometric: 1.6.3

**Comment by rusty1s** [comment]
That's not a bug but intended :) `out_channels` denotes the number of output channels per head (similar to how `GATConv` works). I feel like this makes more sense, especially with `concat=False`. You can simply set the number of input channels in the next layer via `num_heads * output_channels`.

**Comment by ZacharyKaplan** [comment]
> That's not a bug but intended :) `out_channels` denotes the number of output channels per head (similar to how `GATConv` works). I feel like this makes more sense, especially with `concat=False`. You can simply set the number of input channels in the next layer via `num_heads * output_channels`.

Understood! Thank you for maintaining such a fantastic library!
