### ISSUE TITLE
Questions related to LINUX of GEDDataset

### ISSUE THREAD

**Issue by reshinthadithyan** [pyg-team/pytorch_geometric#1975]
## ❓ Questions & Help

Hello @rusty1s. I have a question related to `GEDDatset("LINUX")`.   
- Given are a set of Graphs and when a pair is invoked, we can get the GED for the given pair. Are we expected to sample the pairs from the 800 graphs given?
- Do we have an implementation referred in the [SimGNN](https://arxiv.org/pdf/1808.05689v4.pdf) paper? If not, I can work onto it.

**Comment by rusty1s** [comment]
You can find a `SimGNN` PyG implementation [here](https://github.com/gospodima/Extended-SimGNN), although I would very much appreciate to include a simple example of SimGNN in this repo. Feel free to add it. You can create pairs between graphs by making use of two loaders:
```python
for data1, data2 in zip(loader1, loader2):
   ...
```
