### ISSUE TITLE
failed to install under windows 10 with GPU

### ISSUE THREAD

**Issue by elfayoumi** [pyg-team/pytorch_geometric#1977]
## 📚 Installation

when building the package from source, it fails: 
C:/workspace/anaconda3/lib/site-packages/torch/include\torch/csrc/jit/ir/ir.h(1347): error: member "torch::jit::ProfileOptionalOp::Kind" may not be initialized

C:/workspace/anaconda3/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(106): warning: modifier is ignored on an enum specifier

C:/workspace/anaconda3/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(138): warning: modifier is ignored on an enum specifier

C:/workspace/anaconda3/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/modules/transformerlayer.h(73): warning: extra ";" ignored

C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/include\xutility(4109): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "_OutIt std::_Move_unchecked1(_InIt, _InIt, _OutIt, std::false_type) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
(4125): here
            instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/include\vector(1353): here
            instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, at::Tensor>::Item, _Alloc=std::allocator<torch::OrderedDict<std::string, at::Tensor>::Item>]"
C:/workspace/anaconda3/lib/site-packages/torch/include\torch/csrc/api/include/torch/ordered_dict.h(419): here
            instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=at::Tensor]"
C:/workspace/anaconda3/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/modules/container/parameterdict.h(51): here

2 errors detected in the compilation of "C:/Users/ielfa/AppData/Local/Temp/tmpxft_00002440_00000000-7_fps_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

## Environment

* OS: Windows 10
* Python version: 3.8.3
* PyTorch version: 1.7.1
* CUDA/cuDNN version: 10.1
* GCC version: 7.4.0 and visual studio 2019
* How did you try to install PyTorch Geometric and its extensions (wheel, source): source
* Any other relevant information:

## Checklist

- [x ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ x] I do have multiple CUDA versions on my machine.

**Comment by johnny12150** [comment]
Why don't install it from `source`?

**Comment by elfayoumi** [comment]
Hi Jonny12150
This is an installation form source, I can install as documented but source compilation fails.
I did :
python setup.py install
and this was the error.

**Comment by rusty1s** [comment]
In general, manual installation on Windows is a mess, and requires modification to the PyTorch sources, see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/script/torch.sh).

**Comment by edw-01** [comment]
Is there a fix to this error?

I am having the same trouble on Windows 10 with PyTorch 1.8.0 and 1.7.1, along with CUDA version of 10.1. I also am using a fresh conda virtual environment

**Comment by rusty1s** [comment]
I see. I guess you have a system-wide CUDA 11.2 installation, which is used to load the extension. In order to change that, you need to link your system to the CUDA installation provided by PyTorch, i.e. the `cudatoolkit` that gets additionally installed when installing PyTorch via conda.

Mine is located in `{miniconda_path}/lib` and should contain files such as `libtorchsparse.so`. You can link to this specfic `cudatoolkit` via:
```
export LD_LIBRARY_PATH={miniconda_path}/lib:$LD_LIBRARY_PATH
```

**Comment by rusty1s** [comment]
Did you apply the changes from my previous answer?

**Comment by edw-01** [comment]
Not able to see your other reply in this thread but was able to see in my email 
 
I don't believe I have a system-wide CUDA 11.2 installation, because when I do "nvcc --version" it shows:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

And I am not sure what is the best way to do the "export" command on windows. Maybe I should just leverage Linux VM to do the installation :(

**Comment by rusty1s** [comment]
My previous reply was meant to answer a question in a different thread, sorry for the confusion :)

As mentioned previously, you need to make some modifications to PyTorch in order to build from source in Windows, see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/script/torch.sh). This is also mentioned in other threads, see [here](https://github.com/NVIDIAGameWorks/kaolin/issues/135).

You can also follow our build procedure on Windows (which works on Travis-CI), see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/.travis.yml#L109-L118).

**Comment by edw-01** [comment]
I used WSL tool to run torch.sh as suggested, but am still facing the following errors:

    __2 errors detected in the compilation of "C:/Users/edw/AppData/Local/Temp/tmpxft_00001a50_00000000-7_scatter_cuda.cpp1.ii".
    scatter_cuda.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\edw\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\edw\\AppData\\Local\\Temp\\pip-install-e3dit_an\\torch-scatter\\setup.py'"'"'; __file__='"'"'C:\\Users\\edw\\AppData\\Local\\Temp\\pip-install-e3dit_an\\torch-scatter\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\edw\AppData\Local\Temp\pip-record-xrb0mrcn\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.__

Should I modify to PyTorch using some other methods?

**Comment by rusty1s** [comment]
Can you show the actual error that occurred during installation?

**Comment by edw-01** [comment]
[error_logs.log](https://github.com/rusty1s/pytorch_geometric/files/6223860/error_logs.log)

I have attached the whole log here (sorry it's quite long), thank you so much!

**Comment by rusty1s** [comment]
The error is
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/include\xutility(4671): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
```
which comes from MSVC directly. I'm not sure which versions of MVSC can be used to compile PyTorch extension Code, but `MVCS/2017/14.16.27023` works just fine in our build scripts.
