### ISSUE TITLE
Farthest Point Sampling

### ISSUE THREAD

**Issue by edshkim98** [pyg-team/pytorch_geometric#1983]
## ❓ Questions & Help

Hi, I am trying to use fps function to train my Point cloud network.
The problem is that my data for point cloud is fed into the network as (batch_size, channels, num_points) but when I use the fps function to sample my data, it works on the batch size, so the shape stays the same even after the sampling.
Is there anyway to use fps function to sample num_points?
Could reshaping the data shape to (num_points, channels, batch_size) and then change it back to the original shape after sampling to continue the training be valid approach?

Thank you!

**Comment by rusty1s** [comment]
I suggest to permute your input data to align with the representation `fps` expects:
```python
pos = ... [batch_size, channels, num_points]
pos = pos.permute(0, 2, 1).view(batch_size * num_points, channels]
batch = torch.arange(batch_size).view(-1, 1).repeat(1, num_points).view(-1)
index = fps(pos, batch=batch, ratio=0.5)
```
