### ISSUE TITLE
1.6.1 -> 1.6.2 breaks replacing values from InMemoryDataSet

### ISSUE THREAD

**Issue by gunthergl** [pyg-team/pytorch_geometric#1984]
## 🐛 Bug

Replacing `Data` values from `InMemoryDataSet`s does not work with `get()` anymore. See the code to reproduce, the code resulted in the expected output using `pytorch_geometric 1.6.1`.
It might also be that this usage is not intended at all, then sorry for the bug - If you could please hint me how to do that properly would be great. 

## To Reproduce
<details><summary> Class definition, hardcoded 3 "pointclouds" with only the response y (as the pos, edge_index, etc. are unaffected) </summary>  

```
# Class mostly copied from https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html
import torch
from torch_geometric.data import InMemoryDataset
from torch_geometric.data.data import Data


class MyOwnDataset(InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super(MyOwnDataset, self).__init__(root, transform, pre_transform)
        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return ['some_file_1']

    @property
    def processed_file_names(self):
        return ['data.pt']

    def download(self):
        # Download to `self.raw_dir`.
        pass

    def process(self):
        # Read data into huge `Data` list.
        data_list = [
            Data(y=torch.tensor([0])),
            Data(y=torch.tensor([0])),
            Data(y=torch.tensor([0]))
        ]

        if self.pre_filter is not None:
            data_list = [data for data in data_list if self.pre_filter(data)]

        if self.pre_transform is not None:
            data_list = [self.pre_transform(data) for data in data_list]

        data, slices = self.collate(data_list)
        torch.save((data, slices), self.processed_paths[0])
```

</details>

The following lines are running as expected, comments are the actual outputs with `pytorch_geometric 1.6.3` (or 1.6.2, output is the same)

```
# Instantiate the dataset
a = MyOwnDataset(root='.')

print(a.data)            # Data(y=[3])
print(a.data.y)          # tensor([0, 0, 0])
print([x.y for x in a])  # [tensor([0]), tensor([0]), tensor([0])] 
print(a.get(1).y)        # tensor([0])


print()
a.data.y = torch.tensor([2,2,2])  # ***

print(a.data)            # Data(y=[3])
print(a.data.y)          # tensor([2, 2, 2])
```

**Actual problem**: I just updated `a.data.y` successfully in *** but if I get the values one by one, the values have not been overwritten.  
```
print([x.y for x in a])  # [tensor([0]), tensor([0]), tensor([0])]
print(a.get(1).y)        # tensor([0])
```

I looked into the code and found that `.get()` relies on `__data_list__` starting from `1.6.2`, but I do not know how I should fix that. Overwriting `__data_list__` could be a possibility but feels quite bad. 

## Additional context

I am working on pointcloud classification. Out of my workflow it makes sense to replace the response variable `y` for all pointclouds but leave the other attributes. Think of loading the actual point cloud once but having multiple [distinct, unrelated] response variables to predict such that I do not want to train them all at once. I do not even need to make those changes persistent (e.g. save/overwrite `data.pt`).

**Comment by rusty1s** [comment]
Thanks for reporting. It might not qualify as bug directly, since accessing `dataset.data` is not recommended. It might be better to convert each `data` object separately, e.g., by using `transform` or `pre_transform` parameters. I will think about a way to fix that though!
