### ISSUE TITLE
Cluster data class

### ISSUE THREAD

**Issue by gopikr92** [pyg-team/pytorch_geometric#1987]
## ❓ Questions & Help

Does the subgraphs returned by ClusterData has got between between cluster links or do we get 'x' number of disconnected subgraphs?

**Comment by rusty1s** [comment]
Indexing `ClusterData` only returns intra-cluster links. In case you are also interested in inter-cluster links between different partitions, you want to look at `ClusterLoader`.

**Comment by gopikr92** [comment]
I want to make  each cluster as a minibatch without considering the inter-cluster links. So if I use DataLoader on the output returned by the ClusterData will that work?

**Comment by rusty1s** [comment]
Yes, that will work :)

**Comment by gopikr92** [comment]
Thank you

**Comment by gopikr92** [comment]
Will ClusterData return clusters comprising of only training nodes similar to   the inductive setting mentioned in the paper?

**Comment by rusty1s** [comment]
No, it will contain clusters of all the nodes in the graph.

**Comment by gopikr92** [comment]
So in that case  in the ClusterGCN example reddit.py during the training message passing and update phase it sees all the  train,test and val nodes. So is that fully inductive?. I mean in the ClusterGCN github repo I've seen during them seperating out the train nodes and doing the training using the features of train nodes only. So just confused

**Comment by rusty1s** [comment]
If you want to train it in an inductive fashion, you indeed need to separate graphs first, e.g., via `torch_geometric.utils.subgraph`.

**Comment by gopikr92** [comment]
Hello,
For the data returned by ClusterData I noticed  a val_tensor inside the adj field. What does that val_tensor mean?

**Comment by rusty1s** [comment]
Can you give a brief example to what you are referring? I'm actually not sure what you mean. There shouldn't be any additional attributes besides the one original passed to `Data`.
