### ISSUE TITLE
Cannot connect to pyg whl using pip.

### ISSUE THREAD

**Issue by Whisht** [pyg-team/pytorch_geometric#1995]
## Environment

* OS: Ubuntu 18.04.5 LTS
* Python version: 3.8.5
* PyTorch version: 1.7.1
* CUDA/cuDNN version: CUDA11.0/cuDNN8.0.5
* GCC version:7.5.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
 Using `pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
* Any other relevant information:
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f98abc6e160>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/torch-1.7.0+cu110.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f98abc6e370>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/torch-1.7.0+cu110.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f98abc6e520>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/torch-1.7.0+cu110.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f98abc6e6d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/torch-1.7.0+cu110.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f98abc6e880>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/torch-1.7.0+cu110.html
ERROR: Could not find a version that satisfies the requirement torch-scatter
ERROR: No matching distribution found for torch-scatter
```
## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.
No, I have only CUDA 110.

## Additional context
` pip install https://pytorch-geometric.com/whl/torch-1.7.0+cu110/torch_scatter-2.0.5-cp38-cp38-linux_x86_64.whl` is not working with the connection error too.

**Comment by rusty1s** [comment]
Can you manually download https://pytorch-geometric.com/whl/torch-1.7.0+cu110/torch_scatter-2.0.5-cp38-cp38-linux_x86_64.whl? Where are you located?

**Comment by Whisht** [comment]
I am in Beijing, China now. I can download the `whl` through 4g. But with the network of my company, it failes as connection error. Seems the gateway should be to blame.
