### ISSUE TITLE
Do you know any graph paper whose nodes are feature map, instead of vectors?

### ISSUE THREAD

**Issue by zc-alexfan** [pyg-team/pytorch_geometric#2009]
## ❓ Questions & Help

Looking at the literature, it seems that most graph neural network formulate the nodes as vectors. Are there any paper that you encountered formulate the nodes as feature maps? 

Thanks.

**Comment by rusty1s** [comment]
It is indeed more common to refer to them as node feature vectors, while feature maps is more common for CNNs. Note that a single feature map refers to a single feature across all nodes, while the features of a single node is a feature vector.

**Comment by zc-alexfan** [comment]
Sorry, I was wondering if you have encountered any paper that formulate each node as a feature map? I was asking this as you have more experience in GNN. :)

**Comment by rusty1s** [comment]
No particular in mind, but I have definitely read it :)

**Comment by Frank-LIU-520** [comment]
> 
> 
> Sorry, I was wondering if you have encountered any paper that formulate each node as a feature map? I was asking this as you have more experience in GNN. :)

In fact, the node feature of 1*N size could be regarded as feature map of 1*N size. Perhaps , you need transformation to map those M*N feautre maps to 1*N feature.
