### ISSUE TITLE
Parallelized training with progress bar?

### ISSUE THREAD

**Issue by vymao** [pyg-team/pytorch_geometric#2016]
## ❓ Questions & Help

Does PyTorch Geometric have (or do you know of) any feature that allows one to parallelize training (and possibly DataSet generation/processing) while allowing one to view progress through a progress bar? I'm not sure `tqdm` would work here.

**Comment by rusty1s** [comment]
Why don't you think that `tqdm` not works in this case?

You can take a look at our [PyTorch Lightning examples](https://github.com/rusty1s/pytorch_geometric/tree/master/examples/pytorch_lightning) which automatically provides progress bars.

For dataset generation/processing, you can use `multiprocessing.Pool` (see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/utils/geodesic.py#L75)) and update `tqdm manually in each iteration.
