### ISSUE TITLE
Examples of ARGA or ARGVA

### ISSUE THREAD

**Issue by Xiaoshunxin** [pyg-team/pytorch_geometric#203]
## ❓ Questions & Help

Can you give me an example that redo the experiments about using the ARGA or ARVGA models on citation datasets appear in the paper "Adversarially Regularized Graph Autoencoder for Graph Embedding"
Thank you very much!

**Comment by rusty1s** [comment]
I definitively plan to do this.

**Comment by Xiaoshunxin** [comment]
Thank you again.
And, why the performance is very lower than the source paper when I run the VGAE model on the citeseer dataset? The performance of the pubmed dataset is similary to the source paper. When it run on the cora dataset, the ap metric is between on 80-90. This is very serious.

**Comment by rusty1s** [comment]
Hi and thank you for your interest,
IMO, we achieve best results when omitting KL regularization and simply use standard autoencoders. The results of VGAE *can* be different (this is REALLY split dependent) to the original paper, because we use a slightly different `kl_loss`, which we did not additionally normalize by the number of nodes (see https://github.com/tkipf/gae/issues/20).

**Comment by Xiaoshunxin** [comment]
Hi, I’m doing about node classification, now. I had rerun the G2G model, which the code is provided by the author, on the node classification task.
I also want to run the task using the VAGE or ARVGE model which provided by your team. I don't know whether this is feasible. If so, can you give me an example?
thank you very much!

**Comment by Xiaoshunxin** [comment]
Hi, I hava used the GAE to do the node classification task by using the embedding come form the GAE as the input of a linear model. Now, I also want to this task with ARGA model. I wonder if it is convenient for you to give me the correct example to produce embedding for each node by using the ARGA model, similary to the GAE example you have gived?
Thank for your help!

**Comment by qiuhaolu** [comment]
also need the examples for ARGA and ARGVA
