### ISSUE TITLE
link prediction using node/edge features

### ISSUE THREAD

**Issue by iceland20** [pyg-team/pytorch_geometric#2038]
Hi,

I have a couple of related questions about PyG's usage, and I would appreciate an answer...

I'm now trying to predict graph links using both node features (with their embedding `n`) and edge features (with their embedding `e`) . That is, strength of the edge between two nodes depends on source and destination nodes' features and on some known features of this same edge:
```
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.CONV = GCNConv(data.num_node_features, num_d1)
        self.MLPe = torch.nn.Sequential(torch.nn.Linear(data.num_edge_features, num_d1), torch.nn.ReLU(), torch.nn.Linear(num_d1, num_d1))

        self.MLP = torch.nn.Sequential(torch.nn.Linear(2*num_d1 + num_d2, num_d3), torch.nn.ReLU(), torch.nn.Linear(num_d3, num_d3))
        self.W = torch.nn.Parameter(torch.randn(num_dout, num_d3))
        self.B = torch.nn.Parameter(torch.randn(num_dout))

    def forward(self, data):
        edge_attr, edge_index, x = data.edge_attr, data.edge_index, data.x
        n = self.CONV(x, edge_index)
        e = self.MLPe(edge_attr)

        src, dst = edge_index
        s = self.MLP(torch.cat([n[src], n[dst], e], dim=-1))
        return torch.nn.functional.linear(s, self.W, self.B)
```
However, I am not sure if I'm treating `e` correctly here in terms of dimensionality. Am I supposed to index it like I index `n` (eg, `n[src]`)?

Also, a more general question that is the source of my confusion above: within the `forward()` method in this example, do I treat `x` and `edge_attr` as vectors of size `data.num_node_features` and `data.edge_node_features`, or as matrices of size `data.num_nodes * data.num_node_features` and `data.num_edges * data.edge_node_features`? And what sizes are `n[src]` and `n[dst]` then?

Thank you for the help!

**Comment by rusty1s** [comment]
Your general network architecture looks fine to me. `e[i]` corresponds to the edge given by `src[i]` and `dst[i]`, so:
```python
torch.cat([n[src], n[dst], e], dim=-1)
```
groups the source, destination and edge features into a single vector per edge.

Since everything computed in `forward` is done in parallel, `x` corresponds the the node features of all nodes (`[num_nodes, num_node_features]`). The same holds true for `e` (`[num_eges, num_edge_features]`). Therefore, `n[src]` is of size `[num_edges, num_node_features]`: Every node feature is gathered into the respective source nodes.

**Comment by iceland20** [comment]
Thanks a lot for a quick reply! I think I understood you, but just to be safe...

Isn't `e` here of size `[num_edges, num_d1]`, but not `[num_eges, num_edge_features]` (because that would be the dimensionality of `edge_attr` itself), right? Similarly for `n` in your reply, `num_edge_features`should be `num_d1`.

Also, `src` is size `[num_edges, 1]`, `n` is size `[num_nodes, num_d1]`, and `n[src]` is `[num_edges, num_d1]` but not `[1, num_d1]` (as I thought earlier) or `[num_nodes, num_d1]`? So effectively `n[src]` just allocates each source node's `num_d1` "embedding attributes" among appropriate edges?

**Comment by rusty1s** [comment]
1. Yes, since `MLPe` maps to `d1` outputs for each edge, sorry for the confusion :)

2. Yes, `n[src]` will push node embeddings to the appropriate edges.

**Comment by iceland20** [comment]
Thank you very much for the confirmation!

The second point is now clear, though it is at first counter intuitive (at least to me) that `n[src]` inherits its dimension 0 from `src` rather than `n`.
