### ISSUE TITLE
GAT for Graph Classification Task

### ISSUE THREAD

**Issue by dongxiangjue** [pyg-team/pytorch_geometric#2043]
## ❓ Questions & Help

I noticed that the GAT example was used for the node classification task. I was wondering how I can implement it for the graph classification task. Thank you very much!

**Comment by rusty1s** [comment]
For graph classification, you additionally need some global pooling after computing node embeddings. See [here](https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/gcn.py#L7-L36) for an example on how to use GCN in a graph classification scenario. For GAT, you can simply swap out the GNN operator.
