### ISSUE TITLE
RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements

### ISSUE THREAD

**Issue by suyouooooo** [pyg-team/pytorch_geometric#2067]
## ❓ Questions & Help

I use function dense_to_sparse in torch_geometric/utils/sparse.py, when I set my batch size to 20, everything is fine. However, when I set my batch size to 30 or 40, I got an error:
` 
 File "/home/syh/lib/python3.6/site-packages/torch_geometric/utils/sparse.py", line 18, in dense_to_sparse
    index = tensor.nonzero().t().contiguous()
RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements,   file a support request
`

My packages' version are as follows:
`
torch                 1.7.1+cu110
torch-cluster         1.5.8
torch-geometric       1.6.3
torch-scatter         2.0.5
torch-sparse          0.6.8
torch-spline-conv     1.2.0
`

And the function dense_to_sparse is 

> def dense_to_sparse(tensor):
    r"""Converts a dense adjacency matrix to a sparse adjacency matrix defined
    by edge indices and edge attributes.

    Args:
        tensor (Tensor): The dense adjacency matrix.
     :rtype: (:class:`LongTensor`, :class:`Tensor`)
    """
    assert tensor.dim() == 2
    index = tensor.nonzero().t().contiguous()
    value = tensor[index[0], index[1]]
    return index, value

I don't know how to fix the problem, can you help me?
Thanks.

**Comment by rusty1s** [comment]
How big is your adjacency matrix? Looks like the maximum index is larger than `INT_MAX`.

**Comment by suyouooooo** [comment]
> How big is your adjacency matrix? Looks like the maximum index is larger than `INT_MAX`.

My adjacency matrix is very big, its size is [2, 266900], can I adjust `INT_MAX` myself?

**Comment by rusty1s** [comment]
I guess that‘s not a problem with the number of edges, but rather with`edge_index.max()`. Please ensure that values inside `edge_index` are in the range `[0, num_nodes - 1]`.
