### ISSUE TITLE
Giving mesh as graph label

### ISSUE THREAD

**Issue by jsaisagar** [pyg-team/pytorch_geometric#2072]
Hi all,

Is it possible to give mesh as graph label instead of [num_nodes, labels]. 
I have a task where input is mesh with number of vertices X is and output is mesh with vertices X. I want to minimise chamfer distance with a ground truth mesh with number of vertices Y.

Thanks for any help,

**Comment by rusty1s** [comment]
In case you are dealing with graph labels, you can set `data.y` to a single value/vector (dropping the num_nodes dimension).
