### ISSUE TITLE
question about NNCONV

### ISSUE THREAD

**Issue by chenhust1995** [pyg-team/pytorch_geometric#2085]
hi there,It seems like the NNCONV(QM9_NN_CONV) doesn't use the attribure "edge_index" but only use "edge_attr" and "x" in message function,but why do it need the information of "edge_index", how can  I use edge_index as a attribute in it?

**Comment by MatthewMasters** [comment]
NNConv does use `edge_index` on the forward pass: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/qm9_nn_conv.py#L87

**Comment by rusty1s** [comment]
You can access `edge_index` in `message` by just adding it to the argument list:
```python
def message(self, edge_index, edge_attr, x_j):
    pass
```
In general, there is no need to access `edge_index` to generate messages though, that's why you do not see it accessed much (we generate messages independently for every edge).
