### ISSUE TITLE
about the using way of ‘ SAGpooling’ 

### ISSUE THREAD

**Issue by WangYibucea** [pyg-team/pytorch_geometric#2139]
I encountered the following error report when I was using this model.

![image](https://user-images.githubusercontent.com/65903769/108559405-4223c200-7336-11eb-8ec3-d979d67e3b93.png)
![image](https://user-images.githubusercontent.com/65903769/108559535-65e70800-7336-11eb-8aa1-a00e9eecbc6e.png)
![image](https://user-images.githubusercontent.com/65903769/108559556-6b445280-7336-11eb-8e6c-34e2fb7cec77.png)
![image](https://user-images.githubusercontent.com/65903769/108559452-52d43800-7336-11eb-96c5-0ac0be11ee06.png)

**Comment by rusty1s** [comment]
`edge_index` needs to be a `torch.LongTensor` of shape `[2, num_edges]` instead of a scipy sparse matrix.

**Comment by WangYibucea** [comment]
Thanks for your help.
But I encounter one problem again, such next.
I have completed the graph pooling layer with your help.
Then I put it to pass some  graph convolution layers , but I can't unsample the new graph to the original graph.
So,  how to unsample the new graph in order that we can make it back to the original graph?

**Comment by rusty1s** [comment]
You can upsample your node features by making use of the returned `perm` vector, e.g., by filling the blanks with zero vectors:
```python
x_downsampled, edge_index_downsampled, _, _, perm, _ = self.pool(...)

x = torch.zeros(num_orig_nodes, x_downsampled.size(-1))
x[perm] = x_downsampled
```

**Comment by WangYibucea** [comment]
Thank you very much！
The another question is that.
What is this `perm` vector supposed to be, I don't quite understand.

**Comment by rusty1s** [comment]
The `perm` vector is a index tensor, which contains the node indices of the nodes that are kept after pooling.

**Comment by WangYibucea** [comment]
Thank you very much ！！！！！！！Great help！！！！！
