### ISSUE TITLE
link_pred.py bug when training on multiple graphs 

### ISSUE THREAD

**Issue by inferense** [pyg-team/pytorch_geometric#2175]
Hi @rusty1s,

In `link_pred.py` I'm getting this error `IndexError: index 10 is out of bounds for dimension 0 with size 10` on this [line](https://github.com/rusty1s/pytorch_geometric/blob/ed8df7bf5ea3963be8cf25914ad3b28a39e1712d/examples/link_pred.py#L34) `logits = (z[edge_index[0]] * z[edge_index[1]]).sum(dim=-1)` in the `decoder`.

My dataset is not a single graph, rather hundreds of small graphs going through the model one by one.

This is especially difficult to figure out as it happens after few iterations, here's a print of the z and edge index before the bug. (the models gets stuck on the 3rd graph)

```
 edg index torch.Size([2, 28])
z shape torch.Size([10, 2])
 edg index torch.Size([2, 2])
z shape torch.Size([10, 2])
 edg index torch.Size([2, 4])
z shape torch.Size([10, 2])
```

Any idea why this might be happening?

**Comment by rusty1s** [comment]
I guess there might be an error in your data, where `edge_index.max() >= z.size(0)`. Can you check for that?

**Comment by inferense** [comment]
you're right, I get true on the last tensors which break it, though it's strange as it breaks in the `test()` decoder not in right away in the `train()` decoder.

I've tried to check for shapes they seem okay, any ideas why it brakes?

**Comment by rusty1s** [comment]
Did you check that all your data objects are encoded correctly? It might well be that you have a single test data object that is broken which might introduce this error.

**Comment by inferense** [comment]
looks good to me,

this is my pre-encoded data object 
`Batch(batch=[22], relation=[36], test_neg_edge_index=[2, 6], test_pos_edge_index=[2, 6], train_neg_adj_mask=[22, 22], train_pos_edge_index=[2, 30], val_neg_edge_index=[2, 5], val_pos_edge_index=[2, 5], x=[22, 16])`

and encoded tensor
```
 tensor([[-0.1608,  0.1482],
        [-0.4557, -0.1002],
        [-0.4557, -0.1002],
        [-0.3798,  0.2446],
        [-0.3713,  0.1165],
        [-0.2379, -0.0432],
        [-0.1300,  0.1606],
        [-0.1035, -0.0876],
        [-0.1076,  0.0796],
        [-0.0331,  0.0238],
        [-0.0122,  0.0303],
        [ 0.1625, -0.1230],
        [ 0.5303, -0.2167],
        [-0.0429, -0.1503],
        [ 0.0688, -0.1550],
        [ 0.3249, -0.1345],
        [ 0.9367, -0.2735],
        [ 0.9052, -0.2497],
        [ 0.6747, -0.2559],
        [-0.2442, -0.3383],
        [ 0.6747, -0.2559],
        [ 1.5855, -0.5819]], grad_fn=<AddBackward0>)

```

one observation is that sometimes the batch and num_nodes don't match but still goes through. Is there anything specific I should be looking at here?

**Comment by rusty1s** [comment]
I think you should confirm that, for each `data` object,
* `data.num_nodes == data.x.size(0)`
* and `data.{train,test,val}_{pos,neg}.edge_index.max() < data.num_nodes`
