### ISSUE TITLE
Removing --no-index in pip install results in ignoring the provided html page

### ISSUE THREAD

**Issue by sigeisler** [pyg-team/pytorch_geometric#2183]
## 🐛 Bug

In a recent [commit](https://github.com/rusty1s/pytorch_geometric/commit/d889c1c8a1c818817fbbb847cc2b7fbebec3bbb0), the `--no-index` option in the pip install commands was removed. With my pip 21.* installation this results in ignoring the provided URL:

```
pip -v install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html
Using pip 21.0.1 from /nfs/staff-ssd/geisler/anaconda3/envs/pytorch1_4/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-1a9f39jl
Created temporary directory: /tmp/pip-req-tracker-rdx2seky
Initialized build tracking at /tmp/pip-req-tracker-rdx2seky
Created build tracker: /tmp/pip-req-tracker-rdx2seky
Entered build tracker: /tmp/pip-req-tracker-rdx2seky
Created temporary directory: /tmp/pip-install-11dvkm61
Looking in links: https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html
2 location(s) to search for versions of torch-scatter:
* https://pypi.org/simple/torch-scatter/
* https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html
Skipping link: unsupported archive format: .html: https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html (from -f)
...
```

## To Reproduce

1. `pip -v install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html` does not work (2.0.5 is installed which is not compatible with pytorch 1.4.0)
1. `pip -v install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html` on the other hand works

## Environment

* OS: Linux
* Python version: 3.8
* PyTorch version: 1.4
* CUDA/cuDNN version: 10.1
* GCC version: 7.3

**Comment by rusty1s** [comment]
In theory, the `--no-index` option shouldn't be needed in order to install the pre-built wheels. I removed it since it fails to install any dependencies outside of the extensions (such as `scipy` which is a dependency of `torch-sparse`).

I'm very curious why this does not work for you though. Is this a newly introduced "feature" in `pip >= 21`?

**Comment by sigeisler** [comment]
I get the same result

`Skipping link: unsupported archive format: .html: https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html (from -f)` 

with `pip 20.0.2`

**Comment by sigeisler** [comment]
For the same reason, this pipeline failed: https://github.com/sigeisler/reliable_gnn_via_robust_aggregation/runs/1999090796?check_suite_focus=true

The URL get's ignored and then an incompatible version of `torch-scatter` is loaded from the public repository
