### ISSUE TITLE
Layer to group cluster of nodes under single label

### ISSUE THREAD

**Issue by Joel-De** [pyg-team/pytorch_geometric#2188]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Is there a way to group nodes within a graph under a single label? For example, let's say there is a graph structure where each node is an animal of either a cat, dog or hamster, the nodes are in clusters within their own type (Ie, groups of animals on a field, where the field is the graph) and the node features include attributes of the animal but not what kind it is. The nodes are connected with each other based on position (KNN or Radius). Is there a way to extract where a pack of dogs is given this graph? My current approach is to classify each node(animal) as its type and then cluster the model's classification output afterward using a separate algorithm. This approach somewhat works, but I feel a lot of relevant information pertaining to the structure of the dog pack is left out of the model (For example sake let's say that smaller dogs tend to group around the largest dog, and puppies are always beside their mother), as its only concern is to figure out what makes a dog or not, whereas I am concerned with finding the group. Is there some way to have a node mask as an output where the model is predicting several nodes to be under the same entity, rather than just under the same label. Given the graph described, how can I get which nodes make up a pack of dogs rather than which nodes are dogs?

Thanks

**Comment by rusty1s** [comment]
I don't think there is any way to group nodes directly in an end-to-end DL pipeline. AFAIK, this is always done after the neural pipeline has finished. Nonetheless, there might be better options to cluster nodes in the embedding space, e.g., a triplet loss formulation, where you want the embeddings of the same label to be close to each other and embeddings of different classes distinct from each other.
