### ISSUE TITLE
Build dataset/dataloader for multi-parted graph

### ISSUE THREAD

**Issue by paulagd** [pyg-team/pytorch_geometric#2196]
## ❓ Questions & Help

Hi, I am working with context-aware datasets for recommendation and I would like to use your library for mini-batching the graph. However, I don't know how to match the mini-batching of my samples (triplets from training data) with GCN mini-batch.

For now, I have a dataset with samples batches of data in the shape of (u, i, c, j, L) -- where u = user / i = positive item / c=context / j = negative item / L = label. I have build a torch.utils.data.Dataset which I named **PairData** and returns data like:

         [(536, 1157, 2804, 1711, 1.0),
         (453, 1194, 2881, 1864, 1.0),
         (864, 1871, 3036, 2487, 1.0),
         (387, 1450, 2771, 1006, 1.0),
         (341, 1077, 3727, 2123, 1.0),
         (737, 1350, 2631, 2005, 1.0),
         (436, 1230, 2910, 2268, 1.0),
         (806, 1146, 3017, 1989, 1.0),
         (140, 1814, 2952, 1941, 1.0),
         (683, 1307, 2639, 1525, 1.0),
         (234, 943, 2759, 2168, 1.0),
         (644, 1033, 3277, 2312, 1.0),
         (452, 1128, 3276, 1927, 1.0),
         (936, 1239, 2643, 970, 1.0),
         (748, 1029, 4064, 1260, 1.0),
         (88, 1678, 3340, 1273, 1.0)]

*CODE:*

    class PairData(data.Dataset):
    def __init__(self, data, sampler=None, adj_mx=None, context=False, is_training=True):
        """
        Dataset formatter adapted pair-wise algorithms
        Parameters
        ----------
        neg_set : List,
        is_training : bool,
        """
        super(PairData, self).__init__()
        self.features_fill = []
        self.context = context
        self.adj_mx = adj_mx  # Sparse coo mx
        self.is_training = is_training
        self.set = data
        self.sampler = sampler

        self._neg_sampling()

    def __len__(self):
        return len(self.features_fill)

    def _neg_sampling(self):
        if self.is_training:
            neg_set, _ = self.sampler.transform(self.set, is_training=self.is_training, context=self.context, pair_pos=self.adj_mx)
            self.neg_set = neg_set
        else:
            assert self.sampler is None and self.adj_mx is None
            self.neg_set = self.set

        for u, i, c, r, js in self.neg_set:
            if isinstance(c, list):
                u, i, r = int(u), int(i), np.float32(1)
            else:
                u, i, c, r = int(u), int(i), int(c), np.float32(1)
            if self.is_training:
                for j in js:
                    self.features_fill.append([u, i, c, j, r])
            else:
                self.features_fill.append([u, i, c, i, r])

    def __getitem__(self, idx):

        features = self.features_fill
        user = features[idx][0]
        item_i = features[idx][1]
        context = features[idx][2]
        item_j = features[idx][3]
        label = features[idx][4]
        return user, item_i, context, item_j, label

The Dataset class performs negative sampling inside, thus filling up the 4th column ("j" items) with those items which stands as zero entries in the adjacency matrix. As a model, I use GCN to get embeddings of the nodes. However, I do not know how to perform mini-batch . I don't know if it's possible to perform convolutions just on those nodes that the dataloader is randomly sampling.

My dataLoader looks like:

    train_dataset = PairData(train_set, sampler=sampler, adj_mx=adj_mx, is_training=True)

    def custom_collate(batch):
        return list(zip(*batch))

    train_loader = data.DataLoader(
        train_dataset,
        batch_size=int(args.batch_size),
        shuffle=True,
        num_workers=args.num_workers,
        collate_fn=custom_collate
    )

For now, my model is like:

    class GCE(torch.nn.Module):
    def __init__(self, field_dims, embed_dim, features, train_mat_edges):

        super(GCE, self).__init__()

        self.A = train_mat_edges (edge_index object from PyG)
        self.features = features  # so far, Identity matrix
        self.GCN_module = GCNConv(field_dims, embed_dim, cached=True)

    def forward(self, x):
        """
        :param x: Long tensor of size ``(batch_size, num_fields)``
        """
        return self.GCN_module(self.features, self.A)[x]

And then i just define `self.embeddings = GCE(max_dim, factors, X, A)` and perform matrix factorization in the fordward pass:

    class PairMF(nn.Module):

    def __init__(self, user_num, max_dim, factors=32, X=None, A=None, dropout=0):
        """
        self.embeddings = GCE(max_dim, factors, X, A, dropout=dropout)

    def forward(self, u, i, j, c):
        embeddings_uic = self.embeddings(torch.stack((u, i, c), dim=1))
        embeddings_ujc= self.embeddings(torch.stack((u, j, c), dim=1))
        
        pred_i = embeddings_uic.prod(dim=1).sum(dim=1)
        pred_j = embeddings_ujc.prod(dim=1).sum(dim=1)
        return pred_i, pred_j

    def predict(self, u, i, c):
        pred_i, _ = self.forward(u, i, i, c)

        return pred_i.cpu()

> Finally, I perfrom the BPR loss...
I would like to know if there is a way of doing mini-batch with GCN, for example with ClusterData and ClusterLoader, so that I can align my data sampling with GCN sampling, as for now I am fitting the entire graph on memory and, of course, it does not work with bigger data.

========================================================================================
============================================================================================

I have looked at all your documentation but I do not know how to deal with my data (is MovieLens dataset, for example) in a useful manner. Maybe the most similar thing could be to build a dataset of similar shape with PUBMED, as you show in [this notebook](https://colab.research.google.com/drive/1XAjcjRHrSR_ypCk_feIWFbcBKyT4Lirs?usp=sharing#scrollTo=KDy46FIQ6OWN). Thus, I have built the following dataset but I don't know how to follow in: 

-  leave-one-out strategy split
- how to mark the **n**  different types of nodes (in this example n=3 for users, items, context)
- how to match GCN sampling with triplets
 I'm very confused actually about how to address the problem of building correct dataset... If you could give me some insights about how should I do it it would be nice! This is what I have built:

            class GraphDataset(InMemoryDataset):
            def __init__(self, root, users=None, items=None, transform=None, pre_transform=None):
                super(GraphDataset, self).__init__(root, transform, pre_transform)
                self.data, self.slices = torch.load(self.processed_paths[0])
                self.num_items = self.data.num_users.item()
                self.num_users = self.data.num_items.item()
                self.num_context = 0
        
            @property
            def raw_file_names(self):
                return [f'u.data']
        
            @property
            def processed_file_names(self):
                return ['post_processed.pt']
        
            def download(self):
                # Download to `self.raw_dir`.
                #'curl -O http://files.grouplens.org/datasets/movielens/ml-1m.zip
                #unzip ml-1m.zip'
                pass
        
            def len(self):
                return len(self.processed_file_names)
        
            def process(self):
                df = pd.read_csv(os.path.join(self.root, self.raw_file_names[0]), sep='\t', header=None,
                                 names=['user', 'item', 'rating', 'timestamp'], engine='python')
        
                df['rating'] = 1.0
                df['user'] = pd.Categorical(df['user']).codes
                df['item'] = pd.Categorical(df['item']).codes
        
                user_num = df['user'].nunique()
                item_num = df['item'].nunique()
                df['item'] = df['item'] + user_num
                num_nodes = df['item'].max()
        
                target_nodes = df['item'].values
                source_nodes = df['user'].values
                edge_index = torch.LongTensor([source_nodes, target_nodes])
        
                x = torch.LongTensor(np.identity(num_nodes + 1))
                y = torch.FloatTensor(df['rating'].values)
        
                data = Data(x=x, edge_index=edge_index, y=y)
                data.num_users = user_num
                data.num_items = item_num
                data, slices = self.collate([data])
                torch.save((data, slices), self.processed_paths[0])

In order to load it I do:

        pyg_dataset = GraphDataset(root=f'data/{args.dataset}')
        data = pyg_dataset[0]

My dataset and data look like:
        GraphDataset(1)
        Data(edge_index=[2, 100000], num_items=1682, num_users=943, x=[2625, 2625], y=[100000])

Then I use ClusterLoader to split the data, and this is where I get stucked:

        cluster_data = ClusterData(data, num_parts=128)  # 1. Create subgraphs.
        train_loader = ClusterLoader(cluster_data, batch_size=32, shuffle=True)  # 2. Stochastic partioning scheme.
        model = PairMF(pyg_dataset, embedding_dim=args.factors, GCE_flag=args.gce, gpuid=args.gpu, dropout=args.dropout)
        # Define loss and optimizer [...]
        model.train()
    
        for sub_data in train_loader:  # Iterate over each mini-batch.
            sub_data = sub_data.to(device)
            out = model(sub_data)  # Perform a single forward pass.

**MODEL**

          class GCN(torch.nn.Module):
              def __init__(self, hidden_channels, dataset):
                  super(GCN, self).__init__()
                  self.conv1 = SGConv(dataset.num_node_features, hidden_channels)
          
              def forward(self, x, edge_index):
                  x = self.conv1(x, edge_index)
                  return x
          
        class PairMF(nn.Module):
            def __init__(self, dataset, embedding_dim=16, GCE_flag=False, gpuid='0', dropout=0):
                super(PairMF, self).__init__()
        
                self.gcn = GCN(embedding_dim, dataset)
        
            def forward(self, sub_data):
            # def forward(self, u, i, j, c):
                # pred_i = self._out(u, i, c)
                # pred_j = self._out(u, j, c)
                # return pred_i, pred_j
                return self._out(sub_data)
                    
            def _out(self, sub_data):
                embeddings = self.gcn(sub_data.x.float(), sub_data.edge_index)
        
                return []

  

I do not understand how to mixt both concepts...I guess I need to mixt all of this with something like [bi-partite graphs](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html?highlight=bipartite#bipartite-graphs) but I don't know how to do it...

 Thank you very much in advance for your time and for building such a useful library !!

**Comment by rusty1s** [comment]
As far as I understand, you want to perform mini-batching on the data returned by `PairData`, and therefore only want to consider relevant nodes in `GCNConv`.

The easiest way to achieve this is combining `DataLoader` and `NeighborSampler` behaviour. For example, given a returned mini-batch [u, i, j], you can get all relevant node ids via `n_id = torch.unique(torch.cat([u, i, j])`, and input those to sample their neighbors:
```python
sampler = NeighborSampler(edge_index, sizes=[10, 5])

for data in pair_data_loader:
    ...
    n_id = torch.unique(torch.cat([u, i, j])
    _, n_id2, adjs = sampler.sample(n_id)
    embedding = gnn(x[n_id2, adjs)
    ...
```
You can find an example of utilizing `NeighborSampler` [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py).

**Comment by paulagd** [comment]
Hi,

Thanks for your time!

Actually, what I want is on one side, to perform the convolution based on u -i- c (user interacted with an item on a given context), which are 3 different types of nodes connected. On the other side I'll perform the convolution on u -j -c (where represents that a user did NOT interact with "j" item on that context). But to perform the second one is the same as the first one being like:

            def forward(self, u, i, j, c):                
                pred_i = self._out(u, i, c)
                pred_j = self._out(u, j, c)

                return pred_i, pred_j


However, I have defined the sampler as `sampler = NeighborSampler(edge_index, sizes=[10, 5])`, and I have looked at your example as well, but I do not understand what does the sampler return.

        n_id = torch.unique(torch.cat([u, i, c]))

> len(n_id)  == 101, which is taken all the different unique nodes that are important in this mini-batch convolution

        In [28]: len(n_id2)
        Out[28]: 2031
        
        In [29]: len(adjs)
        Out[29]: 2

I do not get either what are the different edge_index representing:

        In [30]: adjs[0].edge_index
        Out[30]:
        tensor([[ 737,  738,  597,  ..., 2029, 1593, 2030],
                [   0,    0,    0,  ...,  736,  736,  736]])
        
        In [31]: adjs[1].edge_index
        Out[31]:
        tensor([[101, 102, 103,  ...,  10,  35, 736],
                [  0,   0,   0,  ..., 100, 100, 100]])

Thank you again for your time!

**Comment by paulagd** [comment]
For more information, normally I would do this:

**MODEL:**
        class GCE(torch.nn.Module):
            def __init__(self, field_dims, embed_dim, features, train_mat_edges, dropout=0, args=None, gce_loader=None):
        
                super(GCE, self).__init__()
        
                self.A = train_mat_edges
                self.features = features  # so far, Identity matrix
              self.GCN_module = GCNConv(field_dims, embed_dim, cached=True)
        
            def forward(self, x):
                """
                :param x: Long tensor of size ``(batch_size, num_fields)``
                """
                return self.GCN_module(self.features, self.A)[x]


**PairMF model:**
      
         [...]
         self.embeddings = GCE(max_dim, factors, X, A, dropout=dropout, args=args)\

        def _out(self, u, i, c):                
            self.embeddings(torch.stack((u, i, c), dim=1)).   # shape [bs, 3, embedding_size])


I would like to obtain the same "self.embeddings" but just feeding to the GCN the (u,i,c) from the mini-batch. Thanks!

**Comment by rusty1s** [comment]
The `NeighborSampler` returns node indices which represent all nodes involved in the current computation graph, and a list of edge indices which represent the computation graph (forming a tree-like structure), where, finally, you obtain the node embeddings for the initial `n_id` passed to the sampler.

In my example, I unified positive and negative examples into a single `n_id` vector, but you can also distinguish those by calling `sampler.sample()` twice and perform two model calls, e.g.:
```python
n_id, adjs = sampler.sample(i)
pos_embedding = gnn(x[n_id], adjs)

n_id, adjs = sampler.sample(j)
neg_embedding = gnn(x[n_id], adjs)
```
Let me know if that helps you :)

**Comment by paulagd** [comment]
Hi,

Thank you a lot for your time. Though, I'm afraid I am still a bit confuse...

So, going back to the example where I have **u**, **i** and **c** variables which refers to user, item and context nodes respectively. If my batch_size is 99, in testing I have:

`In [8]: u
Out[8]:
tensor([820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820, 820,
        820], device='cuda:0')

In [9]: i
Out[9]:
tensor([1280, 2561, 2562, 1029, 1019, 2058, 1550, 1807, 2319, 2067, 2324, 1304,
        2331, 1052, 1565, 1308, 2591, 1567, 1314, 1573, 1574, 1066, 2090, 1324,
        1329, 2610, 2356, 1589, 1085, 1600, 1856, 1603, 1099, 1101, 1873, 1362,
        1107, 1624, 1113, 1114, 2396, 1888, 1633, 1121, 1641, 1643, 1645, 1392,
        1906, 2164, 1910, 1403, 1405, 1920, 1921, 1410, 1160, 2187, 2448, 1173,
        2456, 2459, 1183, 1184, 1187, 2467, 1192, 1450, 1963, 2481, 2226, 2232,
        1722, 2240, 1472, 1984, 1220, 2500, 1483, 1228, 1741,  977, 2260, 2005,
        1750, 2522, 2523, 1244, 1505, 2535, 1516, 1773, 1007, 1777, 2289, 1522,
        1013, 1016, 1275], device='cuda:0')

In [12]: c
Out[12]:
tensor([2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694, 2694,
        2694, 2694, 2694], device='cuda:0')`

First, as you said I get the unique nodes por positive examples (**i** variable):

`In [13]: unique_uic = torch.unique(torch.cat([u, i, c]))
    ...:

In [14]: unique_uic
Out[14]:
tensor([ 820,  977, 1007, 1013, 1016, 1019, 1029, 1052, 1066, 1085, 1099, 1101,
        1107, 1113, 1114, 1121, 1160, 1173, 1183, 1184, 1187, 1192, 1220, 1228,
        1244, 1275, 1280, 1304, 1308, 1314, 1324, 1329, 1362, 1392, 1403, 1405,
        1410, 1450, 1472, 1483, 1505, 1516, 1522, 1550, 1565, 1567, 1573, 1574,
        1589, 1600, 1603, 1624, 1633, 1641, 1643, 1645, 1722, 1741, 1750, 1773,
        1777, 1807, 1856, 1873, 1888, 1906, 1910, 1920, 1921, 1963, 1984, 2005,
        2058, 2067, 2090, 2164, 2187, 2226, 2232, 2240, 2260, 2289, 2319, 2324,
        2331, 2356, 2396, 2448, 2456, 2459, 2467, 2481, 2500, 2522, 2523, 2535,
        2561, 2562, 2591, 2610, 2694], device='cuda:0')`

Then, I define the NeighbourSampler and I get the n_id and the adjs: `_, n_id, adjs = self.sampler.sample(unique_uic.cpu())` and I get:

`In [15]: n_id
Out[15]: tensor([ 820,  977, 1007,  ..., 3065,   19, 2873])`

In [16]: adjs
Out[16]:
[Adj(edge_index=tensor([[   0,    2,    2,  ..., 2046, 2047, 2048],
         [ 105,  296,  352,  ...,  741,  744,  746]]), e_id=tensor([  5078, 340087, 149833,  ...,
167333, 167976, 319386]), size=(2049, 747)),
 Adj(edge_index=tensor([[100, 101, 102,  ..., 744, 745, 746],
         [ 37,   0,   0,  ..., 100, 100, 100]]), e_id=tensor([245579,   5199,   5064, 309849,   42
72,   5118,   5079,   5160,   5051, ..., 59842, 319712]), size=(747, 101))]

But here is where I get stucked. I understand what that n_id represents node indices which are all nodes involved in the current computation graph and for which I will get the corresponding embeddings as GCN result but I do not get how should I enter **adjs** variable in GCN layer... as it is a list of two `Adj()` instances.

The only way I have found to make the model work is by entering:

`
X = self.features.to_dense()[n_id]
A =  adjs[0].edge_index
self.GCN(X, A)
`

But however, I do not understand either If I should enter adjs[0] or adjs[1], neither what does adjs host.

Thank you so much again for your time!

PS: I'll be faster answering now, was handling other stuff this month, sorry for that!

**Comment by rusty1s** [comment]
`adjs` is a list that holds the edge connectivity information *per* layer. You will need to use different adjacency matrices in each layer, similar to [this example](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/reddit.py#L32-L45).

**Comment by paulagd** [comment]
Thank you very much!

I just have one last question:

When I pass to the model the unique idx so that it computes the corresponding embeddings, following the example, I pass the variable (whose  len(unique_uic) == 101) :

    `In [32]: unique_uic  
    Out[32]:
    tensor([ 820,  946,  959, 1009, 1010, 1013, 1044, 1109, 1147, 1149, 1152, 1182,
            1184, 1208, 1222, 1267, 1308, 1334, 1409, 1417, 1421, 1431, 1455, 1457,
            1462, 1470, 1475, 1565, 1578, 1586, 1628, 1632, 1675, 1686, 1690, 1698,
            1723, 1733, 1737, 1745, 1775, 1802, 1817, 1835, 1854, 1860, 1864, 1868,
            1879, 1892, 1894, 1896, 1915, 1918, 1930, 1947, 1951, 1968, 1978, 1984,
            2037, 2042, 2045, 2070, 2075, 2086, 2106, 2125, 2186, 2199, 2205, 2290,
            2302, 2303, 2332, 2338, 2347, 2363, 2368, 2381, 2382, 2417, 2440, 2441,
            2449, 2464, 2466, 2471, 2500, 2512, 2519, 2548, 2549, 2557, 2568, 2578,
            2580, 2582, 2617, 2618, 2694])
    `

However, when I apply the sampler like `_, n_id, adjs = self.sampler.sample(unique_uic.cpu())`, the *n_id* variable has the lenght of 2000. I understand that the first 101 are the ones that i want and the others are other nodes involved in the convolution, right? If that's okay, then it would be okay to end up getting the embeddings like:

    `embeddings_uic = self.embeddings(n_id, adjs)[:len(unique_uic)]`

However, then I end up with 101 embeddings which I need to keep in the original stacked form in order to feed them to Factorization Machines model to perform pairwise operation. It requires the following stacked form:

    `Out[34]:
    tensor([[ 820, 2568, 2694],
            [ 820, 1802, 2694],
            [ 820, 2578, 2694],
            [ 820, 2580, 2694],
            [ 820, 1044, 2694],
            [ 820, 2070, 2694],
            [ 820, 2582, 2694],
            [ 820, 1817, 2694],
            [ 820, 2075, 2694],  
                      .........      
            [820, 2042, 2694],
            [ 820, 2045, 2694],
            [ 820, 2302, 2694],
            [ 820, 2303, 2694]]) 
    `

It should have the shape [99, 3] as it refers to the 99 interactions (in this example) of user-item-context. However, when i get the embeddings i just get those 101 corresponding to the unique id's. Is there a way to keep the mapping of the node number that we inputed and the resulting embedding?

Thank you very much!

**Comment by rusty1s** [comment]
The `self.embeddings` module should already return a tensor of shape `[101, ...]`. I'm not yet sure I understand, but for the mapping, `unique_uic` already contains the mapping from global to local indices.

**Comment by paulagd** [comment]
Hi,

Thanks, I'll just do a mapping to get the embeddings stacked again in the original shape of U-I-C. 

I'll leave you here the paper of [our work](https://arxiv.org/pdf/2103.03587.pdf) in case you want to take a look. I can also share my code in case you find it interesting.

**Comment by paulagd** [comment]
Hi,

I realized that edge_index is not giving me what I really want. As I explained, I have three different type of nodes and, for example, they are not connected among the same type nodes. So, Following with the example i have users from 0 to 943, then items from 944 to 2626 and the rest of nodes as context. So, If i do what we said:

`In [3]: n_id
Out[3]: tensor([ 820,  954,  955,  ..., 2392, 2741,   24])

In [4]:         edge_index, _, size = adjs[0]  # first layer A

In [5]: edge_index
Out[5]:
tensor([[   1,    1,    1,  ..., 2055, 2056, 2057],
        [ 122,  361,  486,  ...,  734,  734,  735]])`

I actually don't think its okey because in the edge_index variable there are connections among same type of nodes (1-122, 1-361, etc). Would it be possible to do like a n-partite graph with mini-batch?

I'll leave you here the paper of [our work](https://arxiv.org/pdf/2103.03587.pdf) in case you want to take a look. I can also share my code in case you find it interesting.

Thanks

**Comment by rusty1s** [comment]
Note that the `NeighborSampler` will perform a relabeling of nodes, so that subgraphs have consecutive indices from `0` to `N-1`. You can get the original graph indices via
```python
global_sub_edge_index = n_id[edge_index]
```

**Comment by paulagd** [comment]
Okey, thanks!

Now, sometimes I get the following error. Do you know what am I missing?

    ` Traceback (most recent call last):                                                           [18/1833]
  File "main.py", line 468, in <module>
    main()
  File "main.py", line 447, in main
    desc=total_info)
  File "/home/paulagomez/GCE/model/pair/train.py", line 39, in train
    tune=tune, populary_dict=None)
  File "/home/paulagomez/GCE/utils/splitter.py", line 46, in perform_evaluation
    prediction = model.predict(user_u, item_i, context)
  File "/home/paulagomez/GCE/model/pair/FMRecommender.py", line 117, in predict
    pred_i, _ = self.forward(u, i, i, c, inference=True)
  File "/home/paulagomez/GCE/model/pair/FMRecommender.py", line 59, in forward
    pred_i = self._out(u, i, c)
  File "/home/paulagomez/GCE/model/pair/FMRecommender.py", line 86, in _out
    embeddings_ui = self.embeddings(n_id, adjs)[:len(unique_uic)]
  File "/home/paulagomez/.virtualenvs/research/lib/python3.6/site-packages/torch/nn/modules/module.py"
, line 722, in _call_impl
    result = self.forward(*input, **kwargs)  
File "/home/paulagomez/GCE/model/GCE/gce.py", line 91, in forward                    [0/1833]
        return self.GCN_module(self.features[ids], edge_index)
      File "/home/paulagomez/.virtualenvs/research/lib/python3.6/site-packages/torch/nn/modules/module.py"
    , line 722, in _call_impl
        result = self.forward(*input, **kwargs)
      File "/home/paulagomez/.virtualenvs/research/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn
    _conv.py", line 169, in forward
        size=None)
      File "/home/paulagomez/.virtualenvs/research/lib/python3.6/site-packages/torch_geometric/nn/conv/mes
    sage_passing.py", line 233, in propagate
        kwargs)
      File "/home/paulagomez/.virtualenvs/research/lib/python3.6/site-packages/torch_geometric/nn/conv/mes
    sage_passing.py", line 158, in __collect__
        j if arg[-2:] == '_j' else i)
      File "/home/paulagomez/.virtualenvs/research/lib/python3.6/site-packages/torch_geometric/nn/conv/mes
    sage_passing.py", line 127, in __lift__
        return src.index_select(self.node_dim, index)
    IndexError: index out of range in self`

thank you again!

**Comment by rusty1s** [comment]
You still need to input the `edge_index` into the GNN returned by `NeighborSampler`. The aforementioned assignment is just a way to get the original graph structure back.
