### ISSUE TITLE
Do you have an example of link prediction task (SuperGAT)?

### ISSUE THREAD

**Issue by GabbySuwichaya** [pyg-team/pytorch_geometric#2220]
## ❓ Questions & Help

Hi, thank you for releasing the library. 

I am interested in using GNN for link prediction tasks, but I am very new to GNN. 
Initially, I have tried the original repo. of SuperGAT, but my CUDA version is newer...So, I cannot use their codes

But I am not sure if [your example of SuperGAT](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/super_gat.py) can perform this task?  

If not, can you teach me how to turn the example into a link prediction problem? 
(Or do you have any example of the link prediction task that I can follow)?

**Comment by rusty1s** [comment]
Our `SuperGAT` example performs node classification. Note that each individual `SuperGAT` layer will train against a link prediction objective, which results you can obtain by accessing `conv.att_x` and `conv.att_y`.
