### ISSUE TITLE
A problem for GNNExplainer

### ISSUE THREAD

**Issue by ZRF98** [pyg-team/pytorch_geometric#2227]
Hello, thank you for your fantastic work! But I’m a little confused about GNNExplainer, can  GNNExplainer in PyG explain a graph classification model? I see the example of GNNExplainer is based on Cora dataset, and it seems I must choose a node_idx to work.

**Comment by joaquincabezas** [comment]
Hello, I think this thread might be of your interest: https://github.com/rusty1s/pytorch_geometric/issues/1730
