### ISSUE TITLE
Problems about GCNConv and definition of edges

### ISSUE THREAD

**Issue by AlbertoWang** [pyg-team/pytorch_geometric#2278]
## ❓ Questions & Help

Thank u for your excellent work of gcn! But I have some problems during using pytorch_geometric:

1. How to finish a GCNConv operation on a batched data? I follow the codes in `/test`:
```python
x = torch.tensor([[[0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [5.0, 5.0, 5.0], [1.0, 1.0, 1.0]],
                  [[5.0, 5.0, 5.0], [0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 1.0, 1.0]]])
edges = torch.tensor([[[0, 0, 1, 1, 3, 3],
                       [1, 3, 0, 3, 0, 1]],
                      [[1, 1, 2, 2, 3, 3],
                       [2, 3, 1, 3, 1, 2]]])
conv = GCNConv(3, 3)
print(conv(x[0], edges[0]))
```
where x is a batched data that represents a batched 3D point data consisted of two point clouds. First problem is, if edges in each point cloud are not the same, how can I do batched GCNConv operation?

2. As we all know, in deep learning it is better to learn features with a batch size. Is there a good way to determine edges in different point cloud? Because if we learn features in different point cloud, the edges that link different points are not same in different point clouds that partitioned in one batch, thus there will be a problem: in one batch, the number of edges of two point cloud is different, how to define the tensor (because the two edge sets are unable to align)?

I am not sure if you can understand my problems above, I am not a native English speaker😂...
Appreciate it again for your help!

**Comment by rusty1s** [comment]
We provide mini-batch support in two forms:
1. Batch-wise features, same graph structure: This is what you have currently implemented (in some form), e.g., `conv(x, edge_index)`, where `x` is a tensor of shape `[batch_size, num_nodes, num_features]`, and `edge_index` is a tensor of shape `[2, num_edges]`.
2. Batching of different graphs via `torch_geometric.utils.DataLoader`, and you can learn more about it [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches) and [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html). This is exactly what you need :)
