### ISSUE TITLE
add_self_loops() or add_remaining_self_loops()?

### ISSUE THREAD

**Issue by ldv1** [pyg-team/pytorch_geometric#2288]
Hi,

In many convolution layers, we can set the option `add_self_loops`. By default, it is almost always `true` and so `utils.add_self_loops()` is used for that purpose. Isn't it an issue if the dataset already has self-loops or some of them? Shouldn't we always prefer `utils.add_remaining_self_loops()` to be on the safe side?

**Comment by rusty1s** [comment]
I guess this depends. For example, for `GCNConv`, the modified adjacency matrix is defined as `A + I`, so it might be natural to just think of it as adding additional self-loops. On the other side, it might be more natural to solely add remaining self-loops. The main reason why I did go for this approach is that `add_remaining_self_loops` is computational more expensive than calling `add_self_loops`, and most graphs do not have a notation of self-connections anyway.

**Comment by icedpanda** [comment]
Hi @rusty1s, should I set `add_self_loop` to `False` using modules like `GATConv` if I have already added `self-loops` in the dataset?

**Comment by rusty1s** [comment]
Yes, in that case `add_self_loops=True` would result in unnecessary computation.

**Comment by icedpanda** [comment]
> Yes, in that case `add_self_loops=True` would result in unnecessary computation.

Thanks!
