### ISSUE TITLE
Searching for neighbours (sender and receiver nodes) given the edge_index

### ISSUE THREAD

**Issue by mariolinovIC** [pyg-team/pytorch_geometric#2294]
Hi,

I need to find the neighbouring nodes for each node in a graph. My code is like this:
```
for i in range(data.num_nodes):
    senders      = data.edge_index[0, data.edge_index[1]==i]
    receivers    = data.edge_index[1, data.edge_index[0]==i]
neighbours = torch.cat([senders, receivers])
```

This loop is too slow. and and the operation `==` along the whole data.edge_index is too expensive for large graphs. Do you know if there is a more efficient way to do it?

Cheers, 

Mario

**Comment by rusty1s** [comment]
You can make use of our `SparseTensor` class to achieve that:
```python
adj = SparseTensor(row=edge_index[1], col=edge_index[0])
rowptr, col, value = adj.csr()
rowcount = rowptr[1:] - rowptr[:-1]
receivers = col.split(rowcount.tolist())
```

**Comment by mariolinovIC** [comment]
Thank you very much Matthias. I also found info on SparseTensor here: [https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html?highlight=SparseTensor](url)
