### ISSUE TITLE
Unable to have "face" or "index" in property name

### ISSUE THREAD

**Issue by richardrl** [pyg-team/pytorch_geometric#2408]
If my sample has a field called "mesh_face_normals", line 105 of batch.py:

                inc = data.__inc__(key, item)

will return "None" for inc.

This is because "__inc__" looks like this:

    def __inc__(self, key, value):
        r"""Returns the incremental count to cumulatively increase the value
        of the next attribute of :obj:`key` when creating batches.

        .. note::

            This method is for internal use only, and should only be overridden
            if the batch concatenation process is corrupted for a specific data
            attribute.
        """
        # Only `*index*` and `*face*` attributes should be cumulatively summed
        # up when creating batches.
        return self.num_nodes if bool(re.search('(index|face)', key)) else 0

Why ?

**Comment by rusty1s** [comment]
We use `data.face` and `data.edge_index` for storing face and edge connectivities, which indices needs to be increased in mini-batch mode. I suggest to simply rename your attribute or override `Data`:
```python
class MyData(Data):
    def __inc__(self, key, value):
        return self.num_nodes if 'index' in key else 0

    def __cat_dim__(self, key, value):
        return -1 if 'index' in key else 0
```
