### ISSUE TITLE
Can edge_index format data derivable？

### ISSUE THREAD

**Issue by caoyxuan** [pyg-team/pytorch_geometric#2427]
From now on, we recommend using our discussion forum (https://github.com/rusty1s/pytorch_geometric/discussions) for general questions.

## ❓ Questions & Help

Thanks for your sharing and you have helped us a lot!
I have a question that when I trying to sample subgraphs with NeighborSampler, the subgraph is represented as the data structure "adjs", and it has edge_index to store the structure information. 
My problem is that does "**adjs**" derivable? If not, does **edge_index** derivable? I have tried to modify the **required_grad** attribute but the error said the dtype of edge_index is **int** instead of **float**. However, when I tried to change its type from int to float, an error occurs saying that **can not set attributes**. Does it mean I can't change its type manually?
I will appreciate it if you can give me some advice! Thanks!

**Comment by rusty1s** [comment]
Index tensors are not differentiable, as they are not continuous. If you want to differentiate trough graph structures, you have to do that via additional edge features such as `edge_weight`.
