### ISSUE TITLE
set the number of threads for pyg

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [pyg-team/pytorch_geometric#2532]
## 🐛 Bug

 Unable to set the number of threads for pyg

## To Reproduce

When I run
```OMP_NUM_THREADS=3 MKL_NUM_THREADS=3 NUMEXPR_NUM_THREADS=3 python -c 'import torch_geometric; print(torch_geometric.__version__)'``` 
I expect to use only three threads but using htop to monitor the process, it uses 6 threads.  It seems that it will always use 2x number of threads when I set the number of thread to be x. 

I found this when I was trying to set the number of threads for my model to be 1 (so that I can run multiple models for hyperparameters tunning on cpu). I found whenever I execute the ```from torch_geometric.data.data import Data```, the number of threads increase from 1 to 11. 

## Environment

* OS: ubuntu 18.04
* Python version: 3.7.10
* PyTorch version:1.7.1
* CUDA/cuDNN version: 11.0
* GCC version:  7.5.0
* Any other relevant information:

**Comment by Chen-Cai-OSU** [comment]
To add a bit more context, I used
```
n = 1
import os
import torch
print(torch.get_num_threads())
torch.set_num_threads(n)
os.environ['MKL_NUM_THREADS'] = str(n)
os.environ['OMP_NUM_THREADS'] = str(n)
os.environ['OPENBLAS_NUM_THREADS'] = str(n)
os.environ['MKL_NUM_THREADS'] = str(n)
os.environ['VECLIB_MAXIMUM_THREADS'] = str(n)
os.environ['NUMEXPR_NUM_THREADS'] = str(n)
```
and 
```OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 python script.py ``` to set the thread number. I found if I exit before the line ```from torch_geometric.data.data import Data```, the number of thread (monitored using htop) used is 1, but if I add ```from torch_geometric.data.data import Data```, the thread number increase to 11.

**Comment by rusty1s** [comment]
Mh, I cannot really reproduce this. All commands will yield the desired number of threads. Any idea what might cause this on your side?

**Comment by eedalong** [comment]
I dont think this is a bug related to PyG, PyG is based on pytorch and didnt use multithread in its pytorch extensions, so if you set OMP_NUM_THREAD to 1, it should only use 1 thread
