### ISSUE TITLE
pointnet2_classification.py in the examples does not work

### ISSUE THREAD

**Issue by soccken** [pyg-team/pytorch_geometric#2554]
pointnet2_classification.py in the examples does not work. When executed, processing is still displayed on the terminal. Over time, 「terminate called after throwing an instance of'std :: runtime_error'
what (): could not allocate bytes object!」 is displayed. The operating environment is Jetsonnano (jetpack 4.5.1)
python3.6.7.There is 6GB of swap

**Comment by rusty1s** [comment]
Does that mean that `ModelNet()` can not be processed for you? Do you mind doing some further debugging of [this procedure](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/datasets/modelnet.py#L90-L109)?

**Comment by soccken** [comment]
Yes, Modelnet() can not be processed. The download of modelnet has been completed by [from torch_geometric.datasets import ModelNet] in the program, but it does not work after that.
How should I solve it?

**Comment by rusty1s** [comment]
It would be great if you can install PyG from source (clone the repo and run `python setup.py develop`). You can then directly check which statement produces the error (one can use `print` statements for simplicity).

**Comment by soccken** [comment]
The environment for pytorch-geometric has been built. Does that mean I should run setup.py?

**Comment by rusty1s** [comment]
Not sure what you mean, but you can also follow the detailed steps in (`CONTRIBUTING.md`)[https://github.com/rusty1s/pytorch_geometric/blob/master/CONTRIBUTING.md]
