### ISSUE TITLE
(macOS) importing failed: torch_sparse/_convert_cpu.so Symbol not found.

### ISSUE THREAD

**Issue by stonesthatwhisper** [pyg-team/pytorch_geometric#2908]
## 🐛 Bug

Importing Data failed with the message:

`... /lib/python3.9/site-packages/torch_sparse/_convert_cpu.so, 6): Symbol not found: __ZN2at8internal13_parallel_runExxxRKNSt3__18functionIFvxxmEEE`

I installed it in a newly created environment with `conda install pytorch-geometric -c rusty1s -c conda-forge` 

## To Reproduce

> from torch_geometric.data import Data

## Expected behavior

Importing should succeed.

## Environment

* OS: MacOS 11.1
* Python version: 3.9
* PyTorch version: 1.8 or 1.9
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:
*
> conda list | grep rusty1s

pytorch                   1.8.0           cpu_py39h4f2e8f6_1    conda-forge
pytorch-cluster           1.5.9           py39_torch_1.8.0_cpu    rusty1s
pytorch-geometric         1.7.2           py39_torch_1.8.0_cpu    rusty1s
pytorch-scatter           2.0.7           py39_torch_1.8.0_cpu    rusty1s
pytorch-sparse            0.6.10          py39_torch_1.8.0_cpu    rusty1s
pytorch-spline-conv       1.2.1           py39_torch_1.8.0_cpu    rusty1s

or

pytorch                   1.9.0           cpu_py39hbc4979b_0    conda-forge
pytorch-cluster           1.5.9           py39_torch_1.9.0_cpu    rusty1s
pytorch-geometric         1.7.2           py39_torch_1.9.0_cpu    rusty1s
pytorch-scatter           2.0.7           py39_torch_1.9.0_cpu    rusty1s
pytorch-sparse            0.6.10          py39_torch_1.9.0_cpu    rusty1s
pytorch-spline-conv       1.2.1           py39_torch_1.9.0_cpu    rusty1s

**Comment by rusty1s** [comment]
Thanks for letting me know. I tried to reproduce on macOS 11.2 and everything works just fine. Can you try to install via `pip` to see if this error is present there as well?

**Comment by mfansler** [comment]
This is a channel mixing issue. The documentation is telling users to install with:

```bash
conda install pytorch-geometric -c rusty1s -c conda-forge
```

whereas [the `conda-build` command](https://github.com/rusty1s/pytorch_geometric/blob/master/conda/pytorch-geometric/build_conda.sh#L33) uses:

```bash
-c defaults -c pytorch -c conda-forge -c rusty1s
```

This results is the packages building against the PyTorch channel version, but trying to run against the Conda Forge one.

### Recommendation

Documentation should updated to 

```bash
conda install -c defaults -c pytorch -c conda-forge -c rusty1s pytorch-geometric
```

Even better, users should be encouraged to create new environment rather than installing into existing ones.
