### ISSUE TITLE
Collate function

### ISSUE THREAD

**Issue by paulamartingonzalez** [pyg-team/pytorch_geometric#2962]
## ❓ Questions & Help

Hi! Is there a way to create a collate function that batches different Data objects? I am using in particular the MNIST dataset and it gives me errors as it expects a tensor but finds a data object. Thanks in advance!

**Comment by rusty1s** [comment]
If you want to modify the `collate_fn`, you can directly use the `torch.utils.data.DataLoader` and override the `collate_fn`. This is exactly what we are doing for [`torch_geometric.data.DataLoader`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/dataloader.py#L67-L70).

**Comment by paulamartingonzalez** [comment]
Hi @rusty1s Thanks for your help! I am trying to use the collate_fn used in the torch geometric data loader but it doesn't work in the setting I am trying to use. 

I am trying to use pytorchgeometric together with pycox (you can find [here](https://github.com/paulamartingonzalez/GNNs-cox/blob/main/time_to_event_prediction_using_GNNs.ipynb) my notebook and here the [issue where the people from pycox tell me what the outputs from collate should be](https://github.com/havakv/pycox/issues/92).

I am trying to use:


`from collections.abc import Mapping, Sequence
from torch_geometric.data import Data, Batch
from torch.utils.data.dataloader import default_collate

class Collater(object):
    def __init__(self, follow_batch, exclude_keys):
        self.follow_batch = follow_batch
        self.exclude_keys = exclude_keys

    def collate(self, batch):
        elem = batch[0]
        if isinstance(elem, Data):
            print('1')
            return Batch.from_data_list(batch, self.follow_batch,
                                        self.exclude_keys)
        elif isinstance(elem, torch.Tensor):
            return default_collate(batch)
        elif isinstance(elem, float):
            return torch.tensor(batch, dtype=torch.float)
        elif isinstance(elem, int):
            return torch.tensor(batch)
        elif isinstance(elem, str):
            return batch
        elif isinstance(elem, Mapping):
            return {key: self.collate([d[key] for d in batch]) for key in elem}
        elif isinstance(elem, tuple) and hasattr(elem, '_fields'):
            return type(elem)(*(self.collate(s) for s in zip(*batch)))
        elif isinstance(elem, Sequence) and not isinstance(elem, str):
            return [self.collate(s) for s in zip(*batch)]

        raise TypeError('DataLoader found invalid type: {}'.format(type(elem)))

    def __call__(self, batch):
        return self.collate(batch)

collate_fn=Collater(follow_batch = [],exclude_keys = [])

dl_train = DataLoader(dataset_train, batch_size, shuffle=True, collate_fn=collate_fn)
dl_test = DataLoader(dataset_test, batch_size, shuffle=False, collate_fn=collate_fn)
`

but it is not working when doing:

```
net = GCN(hidden_channels=10)
batch = next(iter(dl_train))
x, y = batch
net(*x)
```

error being `TypeError: unsupported operand type(s) for @: 'tuple' and 'Parameter'`
