### ISSUE TITLE
why do we need this line? metapath2vec.

### ISSUE THREAD

**Issue by qoffee** [pyg-team/pytorch_geometric#2964]
https://github.com/rusty1s/pytorch_geometric/blob/58eb6b433b4100544a20c05b5db4b8168a25d6c9/torch_geometric/nn/models/metapath2vec.py#L68

Hello, i'm trying to use PyG in HeteroGraph.
First i'm trying to run it using metapath2vec. 
And my code crashed on this line. So my question is:why do we need this line? Example:
```
edge_list_dict = {
('domain_A', 'link_A_A', 'domain_A'): tensor.Size(2, number_of_edges_A_A_through_link_A_A),
('domain_B', 'link_B_B', 'domain_B'): tensor.Size(2, number_of_edges_B_B_through_link_B_B),
('domain_B', 'link_B_A', 'domain_A'): tensor.Size(2, number_of_edges_B_A_through_link_B_A),
('domain_A', 'link_A_B', 'domain_B'): tensor.Size(2, number_of_edges_B_B_through_link_A_B)
}
metapath = [
('domain_A', 'link_A_A', 'domain_A'), ('domain_B', 'link_B_B', 'domain_B'), ('domain_B', 'link_B_A', 'domain_A'), ('domain_A', 'link_A_B', 'domain_B')
]
metapath[0][0] -> domain_A
metapath[-1][-1] -> domain_B
```

**Comment by rusty1s** [comment]
This is mentioned in the [metapath2vec paper](https://ericdongyx.github.io/papers/KDD17-dong-chawla-swami-metapath2vec.pdf) (before Eq. (4)): "meta-paths are commonly used in a symmetric way, that is, its first node type V_1 is the same with the last one V_L, facilitating its recursive guidance for random walkers". However, I agree that the `assert` statement is not really necessary.
