### ISSUE TITLE
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by soumbane** [pyg-team/pytorch_geometric#2971]
Hi,

I get the following error while installing the PyTorch Geometric and torch-scatter:
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1
ERROR: Failed building wheel for torch-scatter
My Pytorch version is 1.8.2 and cuda version is 10.1. I tried downgrading pytorch ver and gcc version but still does not work. Also tried adding $ export CUDA_HOME=/usr/local/cuda
But nothing works. 

Please help @rusty1s or anyone familiar with this error.

**Comment by rusty1s** [comment]
How did you try to install `torch-scatter`? Can you show me the log of installation?

**Comment by soumbane** [comment]
I did the following:
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://pytorch-geometric.com/whl/torch-1.8.2+cu101.html
Also I downgraded from gcc/g++ 8.x to 7.x. Do you think downgrading to gcc/g++ 6.x will work? I can try that.

**Comment by rusty1s** [comment]
There does not exist a PyTorch version 1.8.2. Can you try to install via:
```
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
```

**Comment by soumbane** [comment]
Actually the current pytorch version was 1.8.2 as given in its installation.
That's why I tried that. 
I think the problem is solved. I downgraded pytorch to 1.7.1+cu101 and also downgraded gcc/g++ to 6.5 instead of 7.5.
I think the gcc version was the main problem. Now torch-scatter could be installed. Installing/building wheel for torch-sparse now.

Thank you for your help.

**Comment by soumbane** [comment]
But while importing torch geometric the following happens:

import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_sparse/__init__.py", line 36, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_scatter/__init__.py", line 14, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/gq3136/.local/bin/.virtualenvs/dl4cv/lib/python3.6/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_

**Comment by rusty1s** [comment]
This error usually indicates a versioning conflict between used PyTorch/CUDA version and the versions which were used to compile `torch-scatter`. Are you using PyTorch 1.8.* to load the binaries for PyTorch 1.7.*? Did you install from source or from wheel?

**Comment by soumbane** [comment]
I installed from wheel. Also I am using pytorch 1.7.1 with cuda 10.1

**Comment by rusty1s** [comment]
When installing from wheels, compiling via `gcc` is not required. You should check for versioning conflicts (e.g. having multiple PyTorch versions). It would be also great if you can share the installation log:
```
pip uninstall torch-scatter
pip uninstall torch-scatter
pip install --verbose -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```

**Comment by soumbane** [comment]
Thank you @rusty1s for all the help and support. The installation finally worked with torch 1.8.0+cu101 and the command:
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
Thanks again for the support.
