### ISSUE TITLE
How to combine data batch with GCN?

### ISSUE THREAD

**Issue by TianhangWang** [pyg-team/pytorch_geometric#3008]
## 🐛 Bug

Hi!, Thanks for your amazing framework. But recently, I am to using GCN to extract spatial-feature from node features in a batch way, but it got the error like this:
```
ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape 
`[2, num_messages]` or `torch_sparse.SparseTensor` for argument edge_index`.
```

## The code I am using
The edge_index and edge_weight is defined as below:
```
graph_edges = torch.tensor(graph_edges, dtype=torch.long, device="cuda:0").t().contiguous()
graph_edges_b = torch.stack([graph_edges for x in range(location_t.shape[0])], dim=0)
print("graph_weight", graph_weight.shape)      # [16, 171]
print("graph_edges_b", graph_edges_b.shape) # [16, 2, 171]
print("feature_t", feature_t.shape)                     # [16, 19, 512] 
```
then 
```
enc_feature = self.g_conv1(feature_t, graph_edges_b, graph_weight)
```
it feeds back the error as below:
```
ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index`.
```
For more details:

The batch_size is 16, and all the graph is `fully-connected`, but the weights is `different` for each graph.

**Comment by rusty1s** [comment]
`MessagePassing` indeed only supports as `edge_index` a shape of `[2, num_edges]`. In order to allow batch-wise training, you need to make use of the diagonal stacked procedure as described [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches). The `DataLoader` does support that automatically when using `torch_geometric.data.Data` objects.

**Comment by TianhangWang** [comment]
Thanks for your reply! The graph is dynamically changed through the training, the `edge_weight` is computed by network, so perheps the DataLoader might not help this situation.  Do you mean I need to use like this?
```
out_batch = []
for i in range(graph_edges_b.size(0)):
    hidden_enc_feature = F.relu(self.g_conv1(feature_t[i], graph_edges_b[i], graph_weight[i]))
    enc_feature = F.relu(self.g_conv2(hidden_enc_feature, graph_edges_b[i], graph_weight[i]))
    out_batch.append(F.relu(enc_feature))

out_batch = torch.stack(out_batch)
```

**Comment by rusty1s** [comment]
You can concatenate features as follows to avoid the for-loop:
```python
feature = torch.cat(feature_t, dim=0)
graph_weight = torch.cat(graph_weight, dim=0)
cumsum = 0
edge_indices = []
for edge_index, x in zip(graph_edges_b, feature_t):
    edge_indices.append(edge_index + cumsum)
    cumsum += x.size(0)
graph_edges = torch.cat(edge_indices, dim=-1)

hidden_enc_feature = F.relu(self.g_conv1(feature, graph_edges, graph_weight)
enc_feature = F.relu(self.g_conv2(hidden_enc_feature, graph_edges, graph_weight)
out_batch = enc_feature.view(batch_size, num_nodes, -1)
```

**Comment by TianhangWang** [comment]
Sorry to bother you again, Could you tell me why use the following codes:
```
feature = torch.cat(feature_t, dim=0)
graph_weight = torch.cat(graph_weight, dim=0)
```
Perheps, I do not explain the problem clearly. The shape of `feature_t` is `[batch, 19, 1024]`, and the shape of `graph_weight` is `[batch, num_edges]`. So, when I used `torch.cat`, it throwed out `TypeError'

**Comment by rusty1s** [comment]
Oh, I thought it is a list of tensors. As such, reshaping to `[batch * 10, 1024]` and `[batch * num_edges]` is sufficient.

**Comment by TianhangWang** [comment]
Excuse me, Could you tell me if I have many graphs to do GCN operation, but actually the graphs share same fully-connection(meaning have same graph_index, but different graph_weight)
```
print(feature.shape)  # [1600, 19, 2048]
print(graph_index.shape)  # [2, 171] just one graph structure
print(graph_weight.shape) #[1600, 171]
```
When I do the following operation, got error.
```
gcn_feature = self.g_conv1(feature, graph_index, graph_weight)
```
I got the error `IndexError: The shape of the mask [171] at index 0 does not match the shape of the indexed tensor [1600, 171] at index 0`

Do I really need to stack the `graph_index` to meet  the shape of `[1600, 2, 171]`?
```
graph_index = torch.stack([graph_index for i in range(1600)]
```
But I got error too, `RuntimeError: Sizes of tensors must match except in dimension 0. Got 2 and 1600 (The offending index is 0)`

**Comment by TianhangWang** [comment]
![image](https://user-images.githubusercontent.com/42128414/133088569-7deec01e-c30b-40ad-92e1-086dd7a1f42e.png)

Actually, the graphs' graph_index are same, just as image shows.

**Comment by rusty1s** [comment]
In case you want to operate on static graphs with varying edge weights, you cannot use the static graph computation scheme that you are currently using. Instead, create a list of `data` objects and load them via `DataLoader`:
```python
data_list = []  # Each element in `data_list` describes a data object with x=[19,2048], edge_index=[2, 171] and edge_weight=[171]

loader = DataLoader(data_list, batch_size=128, shuffle=True)
```

**Comment by TianhangWang** [comment]
I see! Thanks a lot! Hope you have a good day!
