### ISSUE TITLE
(Almost) same hidden variables for all nodes

### ISSUE THREAD

**Issue by mehdi1902** [pyg-team/pytorch_geometric#305]
## ❓ Questions & Help

Hi. I'm using a simple message passing network while the graph is complete. I will get the same feature vector for all nodes after the propagation part, is it because of the complete graph or something else?

```
class GCNConv(MessagePassing):
    def __init__(self, in_channels, out_channels):
        super(GCNConv, self).__init__(aggr='mean')  # "Add" aggregation.
        self.message_func = Seq(Linear(2*in_channels, out_channels),
                                ReLU(),
                                Linear(out_channels, out_channels),
                                ReLU())

        self.lin = Linear(in_channels, out_channels)

    def forward(self, x, edge_index):
        edge_index = add_self_loops(edge_index, num_nodes=x.size(0))
        x = self.lin(x)
        return self.propagate(edge_index, x=x)
    def message(self, x_i, x_j):
        m = self.message_func(torch.cat([x_i, x_j], dim=1))
        return m

    def update(self, aggr_out, x):
        return aggr_out
```
 Following is the x matrix after the propagation part. 

![image](https://user-images.githubusercontent.com/6816535/57762031-62593280-7707-11e9-9804-6f6cb52466bb.png)

**Comment by rusty1s** [comment]
Is this without training? How does your graph and initial node features look like?

**Comment by mehdi1902** [comment]
Actually, I had some problem in training, then I decided to simplify the problem to debug. Currently, I'm using a totally random _x_ and the graph is a complete graph which means:

```
edge_index = [i for i in product(range(N), repeat=2)]
edge_index = torch.tensor(edge_index, dtype=torch.long)
edge_index = torch.transpose(edge_index, 1, 0)
```

P.S. Even when I had the training process, it wasn't changing! Although I considered the parameters in the optimizer!

**Comment by rusty1s** [comment]
Given a complete with self-loops and mean aggregation, all node features should be the same after aggregation.

**Comment by mehdi1902** [comment]
Right. Then what can one do to prevent it? I want to have a complete graph. Should I change the message function wrt to the edge features? Or maybe message passing is not the right choice in this case? Thanks for your answer btw.

**Comment by mehdi1902** [comment]
Also, I had another problem. Assume node 1. Regardless of the input (x) the output of the GNN is (almost) the same! I had the intuition for the previous problem but for this one, I don't know honestly.

**Comment by rusty1s** [comment]
IMO, for conplete graphs, edge information should be crucial. I do not understand your second concern.
