### ISSUE TITLE
Hierarchical graph datasets?  Graph of graphs.

### ISSUE THREAD

**Issue by ags-wsu** [pyg-team/pytorch_geometric#309]
Thanks for your hard work on Geometric! 
I'm interested in how we could implement a model where the data is a graph of graphs. 

Perhaps something like Fig 3. in this paper:
https://arxiv.org/abs/1904.05003

I currently have an InMemoryDataset, `subG`, of, say, 100 graphs that have the same number of features, but differing number of nodes.  I consider each of these "sub-graphs" to be a node in the "master graph", `G`.  I imagine that `G` could also be Data object.   

I would like to do some operations to each graph in `subG`, pool, and use this output as the feature for that corresponding node in `G`.  

Can I initialize `G` at the beginning of training and then update its `x` and `edge_index` at each step?  Perhaps I'm missing something simple?

**Comment by rusty1s** [comment]
As far as I understand, you need to create an assignment vector in `Data` which maps each node to its respective subgraph. Then you can perform message passing in each subgraph in parallel, and global pool each subgraph afterwards.
