### ISSUE TITLE
edge_attr = None in GMMConv network

### ISSUE THREAD

**Issue by monk1337** [pyg-team/pytorch_geometric#3095]
## 🐛 Bug

In the doc of GMMConv, it says `edge_attr` is optional but while setting  `edge_attr = None`, getting error 

```
/usr/local/lib/python3.7/dist-packages/torch_geometric/nn/conv/gmm_conv.py in message(self, x_j, edge_attr)
    132         EPS = 1e-15
    133         F, M = self.rel_in_channels, self.out_channels
--> 134         (E, D), K = edge_attr.size(), self.kernel_size
    135 
    136         if not self.separate_gaussians:

AttributeError: 'NoneType' object has no attribute 'size'
```

```
import pytest
import torch
from torch_sparse import SparseTensor
from torch_geometric.nn import GMMConv



x1 = torch.randn(4, 8)
x2 = torch.randn(2, 16)
edge_index = torch.tensor([[0, 1, 2, 3], [0, 0, 1, 1]])
row, col = edge_index
value = torch.rand(row.size(0), 3)
adj = SparseTensor(row=row, col=col, value=value, sparse_sizes=(4, 4))

conv = GMMConv(8, 32, dim=3, kernel_size=25)
conv(x1, edge_index, edge_attr = None)
```

https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GMMConv.forward

I can open a PR if required, please verify if it's a bug or Am I doing any mistake to test the model?

**Comment by rusty1s** [comment]
Thanks for reporting. `edge_attr` is only optional in case you are using the `SparseTensor` class for message propagation (in which case edge features are part of the `SparseTensor`). Other-wise, if using the standard PyG `edge_index` representation, `edge_attr` needs to be defined.

**Comment by monk1337** [comment]
Should we add this info in doc file?

**Comment by rusty1s** [comment]
Done. I added this information to the end of the "Memory-Efficient Aggregation" tutorial.
