### ISSUE TITLE
About HeteroData,  the edge index in converted homo-data is local idx or global idx?

### ISSUE THREAD

**Issue by Yonggie** [pyg-team/pytorch_geometric#3120]
Before asking any, I'd like to say thank you so much for this open source project torch geometric! This helps me so much!! Thank every one in the team!

sorry for mistaken opening the issue.
I've solved my problem.

**Comment by rusty1s** [comment]
`to_homogeneous` converts local ids in `edge_index` between pairs of node types to global ones. Does that answer your question?

**Comment by Yonggie** [comment]
wow I didn't expect you would reply this fast! Thanks for your answer.
