### ISSUE TITLE
Easy: a few questions about DBLP dataset, what does the data mean?

### ISSUE THREAD

**Issue by Yonggie** [pyg-team/pytorch_geometric#3130]
Hi, I'm so glad that in torch geometric 1.9.0, there comes the `HeteroData` that helps deal with hetorogeneous graph data.
And I'm making my own dataset. 

I followed the example code to check DBLP dataset:
```python
path = osp.join(osp.dirname(osp.realpath(__file__)), 'data/DBLP')

dataset = DBLP(path)

data = dataset[0]

author2paper=data.edge_index_dict[('author','to','paper')]
```
I got this data in `author2paper` when debuging:
```python
tensor([[    0,     0,     1,  ...,  4054,  4055,  4056],
        [ 2364,  6457,  2365,  ..., 13891, 13891, 13892]])
```
Question 1:
If I'm not wrong, this means `author0` links `paper2364`(taking first pair for example), and etc.

Question 2:
![image](https://user-images.githubusercontent.com/31330044/133217957-809f802e-d002-465f-a814-d755e7d0bdf5.png)
Here I extracted `paper2author` and `auther2paper`, however I found first paper node with `id0` and  first author node also with `id0`.
Hence, every id in single `edge index` are locally( within bipartite graph of these two type of nodes) assigned, is that correct?

Thanks in advance.

**Comment by rusty1s** [comment]
1. Yes, that is correct.
2. Yes, each `edge_index` representation between two node types is locally. The reverse direction `author2paper` is actually the "transposed" representation of `paper2author`. If you sort `author2paper` column-wise, both tensors should be identical:
```python
perm = author2paper[1].argsort()
print(author2paper[:, perm])
```

**Comment by kunjan-github** [comment]
Very helpful for understanding the tensor... as I am working with XAI project
