### ISSUE TITLE
Pickling error

### ISSUE THREAD

**Issue by RishabhPandit-00** [pyg-team/pytorch_geometric#3145]
## 🐛 Bug
_pickle.PicklingError: Can't pickle <class 'torch_geometric.data.batch.Batch'>: it's not the same object as torch_geometric.data.batch.Batch
  
This type of error is coming during training the model. I am able to figure it out. I request you to look in to it.

## To Reproduce

1.If your run your dgcnn_classification.py , this error is coimg.
1.I think during train_loader if I write for loop like this:
for data in train_loade:
    print(data)
it will produce same error. SO you need to check in train_loader.
1.

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Please see https://github.com/pyg-team/pytorch_geometric/issues/3143. I‘m releasing a bugfix release soon.

**Comment by rusty1s** [comment]
I just released `torch-geometric==2.0.1` that fixes this issue :)

**Comment by RishabhPandit-00** [comment]
Thanks You very much rusty1s sir....
