### ISSUE TITLE
Heterogeneous Graph Attention Networks (HAN)

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#3162]
https://arxiv.org/abs/1903.07293

**Comment by sara-02** [comment]
Hey, @rusty1s I would like to help with this, but I am new to the pyg ecosystem.

**Comment by rusty1s** [comment]
Sure, highly appreciated :) How shall we proceed with this?

**Comment by rishubhkhurana** [comment]
Hey, @rusty1s I would like to help out here if no one has yet started.

**Comment by rusty1s** [comment]
Sure, thanks a lot! Please keep me updated :)

**Comment by rusty1s** [comment]
I see. This look great. So I assume the interface would be similar to:
```python
class TwoHopMetaPath(
    metapaths=[(('movie', 'acted', 'person'), ('person, 'acted_in', 'movie')),
                         (('movie', 'directed_by', 'person'), ('person', 'directed', 'movie'))])
```
Is that correct?

**Comment by wsad1** [comment]
Thanks. I was thinking of something like this.
```
transform = TwoHopMetaPath(node_metapath={'movie':'target'})
# will contain node type movie and 2 edges types between movie nodes with common target.
data = transform(data)

transform = TwoHopMetaPath(node_metapath={'movie':'target', 'person':'both'})
# will contain node type movie and person and 4 edges types.
# 2 between movie nodes with common target and 2 between person nodes with common target or source.
data = transform(data)
```
This way the user just needs to mention the node types they want in the final graph and the metapath types for those nodes.

**Comment by rishubhkhurana** [comment]
Hi Jinu,

It's actually much easier than this. We don't really need to compute two
hop neighbors. Rather we need different adjacency graph for each meta path
which is already available through HeteroData module. I have already
implemented this HANConv but due to being on vacation haven't been able to
commit.

Regards,
Rishu h

**Comment by rishubhkhurana** [comment]
I have developed the HANConv and necessary test file. Just requested merge with branch name han_network

**Comment by faizan1234567** [comment]
@rusty1s does HANConv work with the Cora dataset, how to define meta paths for it?

**Comment by rusty1s** [comment]
In order to define metapaths, you need a heterogenous graph with multiple edge types or node types. Cora is a homogeneous graph so `HANConv` is not applicable.
