### ISSUE TITLE
Removing nodes from a graph

### ISSUE THREAD

**Issue by ekosman** [pyg-team/pytorch_geometric#3176]
## 🚀 Feature
Given a graph and a list of indices of nodes `ll`, remove all nodes in `ll`.

## Motivation

I want to augment a graph by removing nodes from an input graph.

## Additional context

I'm aware of the existence of the function `remove_isolated_nodes` although it doesn't perform exactly what I want. I want to remove specific nodes. Simply modifying the `x` attribute in the `Data` object doesn't work because I have to manipulate `edge_index` too.

**Comment by rusty1s** [comment]
You can use `utils.subgraph` for this:
```python
data.edge_index, data.edge_attr = subgraph(idx, data.edge_index, data.edge_attr, relabel_nodes=True)
data.x = x[idx]
```

**Comment by ekosman** [comment]
This is great @rusty1s !

Do you know if `idx` must be sorted in this case? The assignment `data.x = x[idx]` looks suspicious.

**Comment by rusty1s** [comment]
No it does not need to be sorted
