### ISSUE TITLE
HeteroConv no aggregation

### ISSUE THREAD

**Issue by Vid201** [pyg-team/pytorch_geometric#3178]
## 🚀 Feature

HeteroConv no aggregation - return stacked embeddings of different edge types (only torch.stack).

## Motivation
Sometimes embeddings over different edge types are further processed (e.g., with attention mechanism) before summation - HeteroConv should return only stacked embeddings for further processing.

**Comment by rusty1s** [comment]
Thanks for the suggestion. This is now supported in master.
