### ISSUE TITLE
Problem with installing torch-scatter

### ISSUE THREAD

**Issue by nhutnamhcmus** [pyg-team/pytorch_geometric#3180]
I want to install pytorch-geometric on my virtual machine wich using ubuntu 16.04, cuda 9.2, cudnn 7.6.4 
![image](https://user-images.githubusercontent.com/52648432/133989079-4e3b7d42-42e5-477a-9d60-49a5c46a72e1.png)

but I get this error when I trying to execute:
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.7.1+cu92.html

in this document page: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
![image](https://user-images.githubusercontent.com/52648432/133988843-24be972e-e6a0-4021-af68-831f7349d300.png)
Can someone help me know how to fix this? Thanks you very much :D

**Comment by rusty1s** [comment]
For downloading older versions of the wheel (i.e. for PyTorch < 1.8.0), you need to specify the exact version number. In this case:
```
pip install torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.1+cu92.html
```
You can find all supported versions [here](https://data.pyg.org/whl/torch-1.7.1+cu92.html).

**Comment by nhutnamhcmus** [comment]
Thanks for your guide. I will close this issue now
