### ISSUE TITLE
[🚀 Feature] `FakeData` dataset as in `torchvision`

### ISSUE THREAD

**Issue by levulinh** [pyg-team/pytorch_geometric#3195]
## 🚀 Feature

A fake dataset class will be useful to test the output of model or some time metrics. Like in [torchvision](https://pytorch.org/vision/stable/_modules/torchvision/datasets/fakedata.html). Although it's straightforward to implement one, but it will be convenience to have the feature embedded into the library.

**Comment by rusty1s** [comment]
You are absolutely right, this is a great idea! Are you interested in contributing such feature? For generating graph structure, we can directly make use of some random graph generators, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/random.py).

**Comment by levulinh** [comment]
I would love to. Please assign that to me.

**Comment by rusty1s** [comment]
Done. Please feel free to make a first draft.

**Comment by rusty1s** [comment]
I needed something like that by myself, and so I made a first draft that is now available in master, see https://github.com/pyg-team/pytorch_geometric/pull/3741. Please let me know what you think :)
