### ISSUE TITLE
Add new topic to repo (Hacktoberfest)

### ISSUE THREAD

**Issue by riccardobucco** [pyg-team/pytorch_geometric#3220]
Hey @rusty1s, it might be a good idea to add the hacktoberfest topic to your repo.
Hacktoberfest (https://hacktoberfest.digitalocean.com) is an event during the entire month of October. During this period you need to find an open-source project on GitHub or GitLab with the hacktoberfest topic and work on a PR. If 4 of your PRs in any participating project are merged or approved by the maintainers by the end of the event (31 October), you will successfully complete the challenge.
This even is basically a way for developers to give back to the open-source community.

I personally would love to work on your project, so I'm simply asking if you can add that topic to your repo. Thanks!!

**Comment by rusty1s** [comment]
Thanks for letting me know. I'm not sure if adding `hacktoberfest` as a topic is a requirement, but I did so nonetheless. Let me know if there is anything else to do on my side :)

**Comment by riccardobucco** [comment]
@rusty1s Thanks for your quick response. I think you can find more info here: https://hacktoberfest.digitalocean.com/resources/maintainers

Anyway, I don't think you need to do anything else. You may want to "Apply the 'Hacktoberfest' label to issues in your GitHub or GitLab project that are ready for contributors to work on". And if you want a t-shirt you have to register and do a couple of more things (everything id described in the above page) haha

**Comment by rusty1s** [comment]
Super. Thanks a lot for the clarification. I also added the `hacktoberfest` label.
