### ISSUE TITLE
Error in NeighborSampler and NeighborLoader with PyTorch Lightning on multi-GPU

### ISSUE THREAD

**Issue by Vid201** [pyg-team/pytorch_geometric#3234]
## 🐛 Bug

`TypeError: __init__() got multiple values for argument 'dataset'
`
## To Reproduce

1. Example: https://github.com/pyg-team/pytorch_geometric/blob/master/examples/pytorch_lightning/graph_sage.py
1. Use trainer with ddp and 2 GPUs (comment and uncomment Trainer in example).
2. NeighborSampler and NeighborLoader are not working (same error). 

## Expected behavior

Training on multi-GPU.

**Comment by rusty1s** [comment]
Thanks for letting me know. I think that a new release of PyTorch Lightning introduced this issue. I fixed it in master, see here: https://github.com/pyg-team/pytorch_geometric/commit/c52028dc4661a0e2612462f852eab7de27745e09

You can update to latest PyG via:
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
