### ISSUE TITLE
`pickle.PicklingError: Can't pickle <class 'torch_geometric.data.batch.Batch'>: it's not the same object as torch_geometric.data.batch.Batch`  error when calling Queue.get() in torch.multiprocessing 

### ISSUE THREAD

**Issue by RasmusOrsoe** [pyg-team/pytorch_geometric#3241]
## 🐛 Bug

`pickle.PicklingError: Can't pickle <class 'torch_geometric.data.batch.Batch'>: it's not the same object as torch_geometric.data.batch.Batch` error when batches are used in `torch.multiprocessing.manager().Queue()`

## To Reproduce

```
from torch_geometric.loader import DataLoader
import torch
from torch.multiprocessing import Manager
from torch_geometric.data import Data 

manager = Manager()
q = manager.Queue()


graph = Data(x = torch.tensor([1],dtype = torch.int))

data_list_train = [graph,graph,graph,graph]

batch_size = 2
loader = DataLoader(data_list_train,batch_size = batch_size,drop_last=True)
loader_it = iter(loader)
for k in range(0,len(loader)):
    q.put(next(loader_it))

batch = q.get()
```

last line yields `pickle.PicklingError: Can't pickle <class 'torch_geometric.data.batch.Batch'>: it's not the same object as torch_geometric.data.batch.Batch` 

Used to work with
torch==1.7.1+cu110
torch-geometric==1.6.3
Python 3.8.5
CentOS Linux 7
gcc (GCC) 6.1.0

## Environment
torch-geometric 2.0.1
torch 1.9.1+cu111
Python 3.8.5
CentOS Linux 7
gcc (GCC) 6.1.0

## Additional context

I know this message was mentioned in 2.0.1 (https://github.com/pyg-team/pytorch_geometric/issues/3143) but it still exists in this context.  This error is quite debilitating for my work :-(

**Comment by rusty1s** [comment]
Thanks for reporting. I pushed a fix to master.
