### ISSUE TITLE
GCNConv change in the new version

### ISSUE THREAD

**Issue by sunshineatnoon** [pyg-team/pytorch_geometric#3244]
## ❓ Questions & Help

Hi, I have an old model trained with torch-geometric 1.7.2. Today after upgrading to the newest version, I found the class members of the `GCNConv` changed. Specifically, the `GCNConv` in the old version has a member called `weight`, while in the new version it becomes `lin.weight`. I tried to simply copy the weight of my old model into `lin.weight`, but it doesn't produce meaningful output as the old model does. Could you please given me some hints about how to transfer old model weights into the new PyG version? Thanks!

**Comment by wsad1** [comment]
let us know if this #3171 discussion helps.

**Comment by rusty1s** [comment]
You need to also transpose the matrix:
```python
state_dict["conv1.lin.weight"] = state_dict["conv1.weight"].t()
```
