### ISSUE TITLE
A question about applying transforms

### ISSUE THREAD

**Issue by shirinmous** [pyg-team/pytorch_geometric#3258]

**Comment by rusty1s** [comment]
What's your question? :)

**Comment by shirinmous** [comment]
Sorry.
I want to know whether we can apply transforms like feature normalization on our own data.
For the datasets like cora we apply transforms  loading method.
Is there any way to apply transforms after loading data?

**Comment by rusty1s** [comment]
Sure, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.BaseTransform).

**Comment by shirinmous** [comment]
Thanks
