### ISSUE TITLE
Bugs in ToUndirected()

### ISSUE THREAD

**Issue by lmkmkrcc** [pyg-team/pytorch_geometric#3265]
## 🐛 Bug

ToUndirected transforms a Data variable into an ill-structured form if the variable has only two edges, or if its edges and nodes are equal in number.

## To Reproduce

For the first case:

1. make a Data variable with 2 edges  ( d = Data( x = [0,1,2], edge_index = [[0,1], [1,2]] )
2. transform the variable with ToUndirected()  ( tu = ToUndirected() ; tu(d) )
3. the variable becomes ill-structured  ( d : Data( x = [0,1,2], edge_index = [[0,1],[0,1],[1,2],[1,2]] )

For the second case:

1. make a directed cycle with node feature  ( d = Data( x = [1,3,5,7,9], edge_index = [[0,1,2,3,4], [1,2,3,4,0]] )
2. transform the variable with ToUndirected()  ( tu = ToUndirected() ; tu(d) )
3. the variable becomes ill-structured  ( d : Data( x = [1,9,1,3,3,5,5,7,9,7], edge_index = [[0,0,1,1,2,2,3,3,4,4],[1,4,0,2,1,3,2,4,0,3]] )

## Expected behavior

d should become Data( x = [0,1,2], edge_index = [[0,1,1,2], [1,0,2,1]] and Data( x = [1,3,5,7,9], edge_index = [[0,0,1,1,2,2,3,3,4,4],[1,4,0,2,1,3,2,4,0,3]])

## Environment

* OS: Ubuntu 20.04.2 LTS
* Python version: 3.9.7
* PyTorch version: 1.9.1
* CUDA/cuDNN version: 10.2
* GCC version: 9.3.0
* Any other relevant information:

## Additional context

This bug was caused by the code in line 59 of to_undirected.py.
The code tried to gather edge attributes from edge_store but it failed because the number of rows in a store can be equal to the number of edges even the store is not an edge attribute.

**Comment by rusty1s** [comment]
Thanks for spotting. I fixed it in master, see https://github.com/pyg-team/pytorch_geometric/commit/ca23b315fbb769ec173e56fbb1ddfdea6e37ea28.
