### ISSUE TITLE
torch.cat() error when networkx graph has node and edge attributes with same name

### ISSUE THREAD

**Issue by will-maclean** [pyg-team/pytorch_geometric#3276]
## 🐛 Bug

Not sure if I've missed something obvious or if this is a bug. I have a networkx graph that has node and edge attributes. I'd like to convert it to a pyg.Data graph, however I get a .cat() error when I try to do the conversion.

I believe this is because the attributes for both the nodes and edges are stored in the same dictionary data during the conversion, so when nodes and edges have an attribute on the same name they are both added to the element in the dictionary.

## To Reproduce

```
import networkx as nx
import torch_geometric as pyg

G = nx.Graph()

G.add_nodes_from([
    (0, {"age": 1, "legs": 2}),
    (1, {"age": 6, "legs": 2}),
    (2, {"age": 5, "legs": 2}),
])

G.add_edges_from([(0, 1, {"age": 2}), (1, 2, {"age": 7})])

pyg_g = pyg.utils.from_networkx(G, group_node_attrs=['age', 'legs'], group_edge_attrs=['age'])
```

This gives the following error:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    pyg_g = pyg.utils.from_networkx(G, group_node_attrs=['age', 'legs'], group_edge_attrs=['age'])
  File "python3.9/site-packages/torch_geometric/utils/convert.py", line 177, in from_networkx
    data.x = torch.cat(xs, dim=-1)
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 7 and 3 in dimension 0 (The offending index is 1)
```

## Expected behavior

A correctly converted pyg.Data graph, with no errors thrown.

## Environment

* OS: macOS (M1)
* Python version: 3.9.5
* PyTorch version: 1.9.1
* CUDA/cuDNN version: CPU
* GCC version: 4.2.1
* Any other relevant information:

**Comment by rusty1s** [comment]
Yeah, this is currently a "bug" induced by shared names. I fixed it in master, see #3283.
