### ISSUE TITLE
Attribute Error when pass new parameter into __init__

### ISSUE THREAD

**Issue by xyqbest** [pyg-team/pytorch_geometric#3277]
## 🐛 Bug

When I use [this template](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html) to create my own dataset, there is an attribute error `Attribute Error: object xxx has no attribute 'xxx' `

## Reproduce the bug：

```

import os.path as osp

import torch
from torch_geometric.data import Dataset


class MyOwnDataset(Dataset):
    def __init__(self, root, transform=None, pre_transform=None, test_par=0):
        super().__init__(root, transform, pre_transform)
        self.test_par = test_par

    @property
    def raw_file_names(self):
        return ['some_file_1']

    @property
    def processed_file_names(self):
        return ['data_1.pt']

    def download(self):
        pass

    def process(self):
        if self.test_par == 0:
            print("No problem")
        torch.save(torch.FloatTensor(10), osp.join(self.processed_dir, 'data_1.pt'))

if __name__ == '__main__':
    dataset = MyOwnDataset("./data")
```
## Solution
The reason is `super().__init__(root, transform, pre_transform)` implement the `self.process()`. Meanwhile, `self.test_par` is not initialized. 

If I change the order of `__init__` as follows, then it works.
```
    def __init__(self, root, transform=None, pre_transform=None, test_par=0):
        self.test_par = test_par
        super().__init__(root, transform, pre_transform)
        
```

I am not sure whether this is a bug, or some parts of the documentation have explained.

**Comment by rusty1s** [comment]
Yes, this is "intended". As `process` will be called as part of `super().__init__()`, you have to declare all variables before calling it. Can you point me to the part in the documentation where this is wrongly documented?

**Comment by xyqbest** [comment]
> Can you point me to the part in the documentation where this is wrongly documented?

It is not wrongly documented. I just follow the example of [creating-in-memory-datasets](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html#creating-in-memory-datasets). And I wrongly think the new parameter should be after `super().__init__(root, transform, pre_transform)`, just like `self.data, self.slices `
```
class MyOwnDataset(InMemoryDataset):
    def __init__(self, root, transform=None, pre_transform=None):
        super().__init__(root, transform, pre_transform)
        self.data, self.slices = torch.load(self.processed_paths[0])
...
```
