### ISSUE TITLE
Inherit Data class loose the ability to use data.num_nodes

### ISSUE THREAD

**Issue by LingxiaoShawn** [pyg-team/pytorch_geometric#3295]
## 🐛 Bug
data = Data()
data.num_nodes originally return the number of nodes in the graph automatically. 
Create a CustomData(Data) class that inherit Data 
custom_data = CustomData() 
custom_data.num_nodes should still work. (at least in previous version of pyg it works)

For PyG 2.0
custom_data.num_nodes always return None.

**Comment by rusty1s** [comment]
Can you give some further instructions on how to replicate this? For example, the following works for me without any issues:
```python
import torch
from torch_geometric.data import Data


class MyData(Data):
    pass


data = MyData(x=torch.randn(10, 5))
print(data.num_nodes)

data = MyData(num_nodes=10)
print(data.num_nodes)

data = MyData()
data.num_nodes = 10
print(data.num_nodes)
```

**Comment by LingxiaoShawn** [comment]
I found that this is my fault. 
`def __inc__(self, key, value, *args, **kwargs) `should be used instead of old `def __inc__(self, key, value) `
