### ISSUE TITLE
yacs version is not 0.1.8

### ISSUE THREAD

**Issue by LingxiaoShawn** [pyg-team/pytorch_geometric#3303]
Hey @rusty1s it seems PyG2.0 installs yacs=0.1.6,
which is not good enough as the yacs.config does not allow hyperparameter=None. 
If you can update the yacs to newest version 0.1.8 that would be great.

**Comment by JiaxuanYou** [comment]
Hi @LingxiaoShawn, thanks for your question. 
I have been using yacs=0.1.6 for GraphGym development without issue. Indeed yacs=0.1.8 looks better, but it's not a requirement.
