### ISSUE TITLE
torch_geometric OS_Error

### ISSUE THREAD

**Issue by fffahim** [pyg-team/pytorch_geometric#3310]
![image](https://user-images.githubusercontent.com/45016119/136415110-e37eb8f1-f671-479d-8af5-c306a957c953.png)
How to solve this? Can anyone help?

**Comment by manzar96** [comment]
I have a similar problem that I can not figure out how to solve.
![image](https://user-images.githubusercontent.com/38495091/139673400-0911c49c-7a67-406e-8387-5ab0fc716435.png)

I am using pytorch==1.9.0+cu111
and I installed pytorch-geom according to the following command as referred at the docs:
``
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
``
The Cuda version of the GPU is 1.4, however, I could not find the corresponding version for pytorch-geom.
What should I do?

**Comment by rusty1s** [comment]
Your system looks for CUDA 10.2, so I expect that installing from `https://data.pyg.org/whl/torch-1.9.0+cu102.html` should fix this error.

**Comment by manzar96** [comment]
![image](https://user-images.githubusercontent.com/38495091/139828291-a697719e-e655-4b86-8198-c9141f0ff5ce.png)
I am using an RTX 3090 CUDA version 11.4. How is that possible?

**Comment by rusty1s** [comment]
What does `torch.version.cuda` return for you?

**Comment by manzar96** [comment]
> What does `torch.version.cuda` return for you?

11.1

**Comment by rusty1s** [comment]
I see, thanks for confirming. I think you might have duplicated versions of `torch-cluster` installed (one for CUDA 10.2 and one for CUDA 11.1), other-wise it should never look for CUDA 10.2 in the first-place. Can you confirm that there do not exist multiple versions of `torch-cluster` by repeatedly running:
```
pip uninstall torch-cluster
```
and re-install `torch-cluster+cu111` once again?

**Comment by manzar96** [comment]
Yes, that was the problem. Thanks a lot!
