### ISSUE TITLE
Wrong aggregation function in nn.to_hetero.ToHeteroTransformer

### ISSUE THREAD

**Issue by Flunzmas** [pyg-team/pytorch_geometric#3314]
## 🐛 Bug ?

```
    aggrs = {
        'sum': torch.add,
        'mean': torch.add,
        'max': torch.max,
        'min': torch.min,
        'mul': torch.mul,
    }
```
The aggregation functions dict entry `"mean"` [(link)](https://github.com/pyg-team/pytorch_geometric/blob/682ab6c77a487d6dc48ba3f41d16e1ab411b5f67/torch_geometric/nn/to_hetero_transformer.py#L116) seems to wrongfully hold `torch.add` instead of something like `torch.mean`.

## Expected behavior

One of the following:
- `torch.add` -> `torch.mean`, or
- A short comment/explanation on why this is correct.

**Comment by rusty1s** [comment]
This is indeed intended, as we divide by the number of elements in a later step, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/to_hetero_transformer.py#L205-L211). I added a comment to describe this procedure.
