### ISSUE TITLE
Graph level neural networks

### ISSUE THREAD

**Issue by vlatorre847** [pyg-team/pytorch_geometric#3316]
Dear All,

The machine learning task I want to perform consists in a dataset that has as input a collection of graphs for which:
- every graph has a different number of nodes and edges;
- the nodes and edges have the same attributes,

and as an output a real number.
By reading the documentation, it looks like to me that the models and layers implemented in pytorch geometric should work on graph level as well.

However it is not clear to me how to go from a node level task to a graph level task.

By searching around the web, I found the following solution:

first I perform the prediction with the model:

`pred = model(batch.x, batch.edge_index)`

and then I apply a global_mean_pool:

`pred = pyg_nn.global_mean_pool(pred, batch.batch)`

but this is done outside of the forward function of the network, in the for cycle of the batches.

Is this right? does it exist a more elegant and standard method to do such a thing?

**Comment by rusty1s** [comment]
Your intuition is correct. However, graph-based pooling is usually done inside a GNN model, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/mutag_gin.py#L47-L57).

**Comment by vlatorre847** [comment]
So let's say that I want to use the model GAT from the library, I can create the class myGAT in the following way:

```
class myGAT(GAT):
    def __init__(self, in_channels, hidden_channels, num_layers, out_channels):
        super(myGAT, self).__init__(in_channels, hidden_channels, num_layers, out_channels)


    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x=GAT.forward(self, x, edge_index)
        x=pyg_nn.global_mean_pool(x, batch)
        return x
```
and that should be the right way to do it right?

**Comment by vlatorre847** [comment]
I think you were in an hurry and made a mistake in the code written in the
issue:
`self.classifier = GraphLevelClassifier(hidden_channels, in_channels):`
should be more like:
`self.classifier = GraphLevelClassifier(hidden_channels, out_channels)`

Regards,

V. L.

Il giorno lun 11 ott 2021 alle ore 12:31 Matthias Fey <
***@***.***> ha scritto:

**Comment by rusty1s** [comment]
Thanks for spotting. I edited my previous comment.
