### ISSUE TITLE
How to use Spline-CNN as Generator?

### ISSUE THREAD

**Issue by Felijasha** [pyg-team/pytorch_geometric#332]
## ❓ Questions & Help
Hi :)
I'm trying the last to weeks to get a GAN work with Spline-CNNs.
The Discriminator works pretty well, but I don't get a Generator work :/
Do you have any idea for the structure of the Generator and the forward function? I looked at several papers and Github-repos, but I still don't get it.
My actual problem is that I can't imagine how the input noise should look like. I can't use just a noise vector like in other models. Maybe I just stand in the tub :D 

Best wishes :)

**Comment by rusty1s** [comment]
This depends on whether you want to generate point clouds or meshes. For point clouds, graph convolutions like SplineCNN should be promising (see [here](https://openreview.net/forum?id=SJeXSo09FQ)). This approach can be easily implemented in PyG. For meshes, the task is much harder and is usually tackled by mesh deformation. Another interesting approach is the [AtlasNet](http://imagine.enpc.fr/~groueixt/atlasnet/). However, given that the mesh structure is unknown during generation, this task can not easily be performed with something like SplineCNN.

**Comment by Felijasha** [comment]
I will have a look at it thank you for your very fast answer.
Actually I try to implement a Generator and a Discriminator for MNISTSuperpixel.
