### ISSUE TITLE
Empty mutable defaults in `torch_geometric.loader.DataLoader`

### ISSUE THREAD

**Issue by nec4** [pyg-team/pytorch_geometric#3410]
## 🐛 Bug

Empty mutable defaults in `torch_geometric.loader.DataLoader`

## To Reproduce

visit https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/loader/dataloader.html#DataLoader

## Expected behavior

Arguments initialized as empty lists should be initialized as `None`.

## Environment

Any

## Additional context

Hello! Really enjoying the tools so far. Is there a specific reason why some of the arguments of the `torch_geometric.loader.DataLoader` constructor are set as empty lists? Would it be safer to set them as `None` by default and then initialize them as empty lists inside the method? Is this a concern?

**Comment by rusty1s** [comment]
No particular reason. The `Batch.from_data_list()` call can well handle `follow_batch` inputs of type `None`. I changed it default values to `None` in master. Thanks!
