### ISSUE TITLE
RuntimeError for knn on cuda when skipping last batch number

### ISSUE THREAD

**Issue by rkansal47** [pyg-team/pytorch_geometric#3441]
## 🐛 Bug

The following RuntimeError occurs when performing a knn between two sets of bipartite graphs on cuda.
I think I have narrowed it down to only occurring when either set of graphs has no nodes in the last batch.

```
Traceback (most recent call last):
  File "/home/jovyan/weaver/knn_test.py", line 9, in <module>
    eidx = knn(sv_points, pf_points, 1, sv_batch, pf_batch)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch_cluster/knn.py", line 75, in knn
        torch.cumsum(deg, 0, out=ptr_y[1:])

    return torch.ops.torch_cluster.knn(x, y, ptr_x, ptr_y, k, cosine,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                       num_workers)
RuntimeError: ptr_x.value().numel() == ptr_y.value().numel()INTERNAL ASSERT FAILED at "csrc/cuda/knn_cuda.cu":106, please report a bug to PyTorch. Input mismatch
```

## To Reproduce

Example code:

```
import torch
from torch_cluster import knn, knn_graph

pf_points = torch.rand(3, 2).cuda()
sv_points = torch.rand(2, 2).cuda()
pf_batch = torch.tensor([0, 1, 1]).cuda()

sv_batch = torch.tensor([1, 1]).cuda()  # this is ok
eidx = knn(sv_points, pf_points, 1, sv_batch, pf_batch)

sv_batch = torch.tensor([0, 0]).cuda()  # will give an error
eidx = knn(sv_points, pf_points, 1, sv_batch, pf_batch)
```

## Expected behavior

Shouldn't give an error.

## Environment

* OS: Ubuntu 20.04.2
* Python version: 3.9.5
* PyTorch version: 1.9.0
* CUDA/cuDNN version: 11.2
* GCC version: -
* Any other relevant information: -

## Additional context

Similar to #3437, this specifically comes up for me when working with heterogeneous graphs with e.g. node types A and B, where occasionally some graphs may not have any nodes of type B, in which case the batch tensor for type B nodes will skip that graph number.

**Comment by rusty1s** [comment]
I'm really sorry for the late reply. This is now fixed in `torch-cluster`, see https://github.com/rusty1s/pytorch_cluster/commit/61ef00a6ba978603f866652c10005150409f2423.
