### ISSUE TITLE
torch.long and torch.int64

### ISSUE THREAD

**Issue by liongkj** [pyg-team/pytorch_geometric#3443]
## 🐛 Bug

torch.long and torch.int64 should be equivalent according to the pytorch documentation, however, the following error message shows.

`` ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index`.

## Expected behavior
I am not sure if I am creating the tensor wrongly or the dtype check did not include torch.int64.

I had tried changing the dtype by using .to(torch.long) but the dtypes stays at torch.int64

## Environment

* OS: wsl ubuntu
* Python version: 3.9
* PyTorch version: 1.9
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Can you show me the shape of the `edge_index` you are passing into `propagate`?

**Comment by liongkj** [comment]
Sorry for the late reply, is this sufficient?
![image](https://user-images.githubusercontent.com/20205301/140854631-951809c6-4b1c-48dd-a7d0-c522b6030c59.png)

**Comment by rusty1s** [comment]
This seems to be perfectly fine as input to `propagate`. Which layer are you calling? Or do you define your own? Please feel free to send me a code snippet to reproduce this issue.

**Comment by liongkj** [comment]
Sorry, apparently I mistyped edge_idx as edge_index and I passed a None variable into the function.

**Comment by MoSuunny** [comment]
hi,
I get same error I check everything and it should work perfectly but It doesn't.
`Traceback (most recent call last):
  File "Predict/make_prediction.py", line 123, in <module>
    main()
  File "Predict/make_prediction.py", line 47, in main
    drug_vector = torch.mean(model(data).cpu().detach().numpy(),axis=0) #obtain the drug embedding
  File "/homes/msanian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/msanian/DrugOrchestra-master/Predict/GNN_model.py", line 281, in forward
    h = self.gnns[layer](h_list[layer], edge_index, edge_attr)
  File "/homes/msanian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/msanian/DrugOrchestra-master/Predict/GNN_model.py", line 53, in forward
    return self.propagate(self.aggr, edge_index, x=x, edge_attr=edge_embeddings)
  File "/homes/msanian/.local/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 270, in propagate
    size = self.__check_input__(edge_index, size)
  File "/homes/msanian/.local/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 155, in __check_input__
    raise ValueError(
ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index`.`

**Comment by rusty1s** [comment]
What's the output of `edge_index.dtype` and `edge_index.shape`?

**Comment by Old-Shatterhand** [comment]
Hi @MoSuunny,

I had that same problem but with `GeometricMultisetTransformers`. I solved the problem by looking into the documentation and specifying every argument I gave to the GMT call explicitly, so
`self.pool(x=x, index=batch, edge_index=edge_index)` worked whereas
`self.pool(x, batch, edge_index)` does not work. In the second sample `edge_index` is taken as `ptr`, I think.

I hope this helps you.

**Comment by wpav** [comment]
Hi @rusty1s 
I am getting this issue when trying to run some code in the anaconda prompt.  How would I see those outputs?  
Thank you!

**Comment by rusty1s** [comment]
Which code are you running? You should be able to simply print these before inputting them into the GNN.

**Comment by codeastra2** [comment]
Hi @rusty1s , thanks for the framework! I was trying to learn in  a situation when there are no edges and and there are only nodes, so either I pass a empty tensor or  pass None for edge index, when I do that I run into the above error, but according to the [documentation](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html) here, it states that these attributes are not required, could you please help me out here?

**Comment by rusty1s** [comment]
All GNN layers need a valid `edge_index` to propagate information. You can define an empty `edge_index` matrix via
```python
edge_index = torch.empty(2, 0, dtype=torch.long)
```
Note that this matrix is still two-dimensional despite having zero elements, i.e it has shape `[2, 0]`.
