### ISSUE TITLE
Assertion Error: can only test a child process after 2.0.2 update

### ISSUE THREAD

**Issue by Michael-C-Strobel** [pyg-team/pytorch_geometric#3473]
## 🐛 Bug

 After updating pytorch-geometric from 2.0.1 to 2.0.2 I get the following error message repeatedly. The issue does not occur with num_workers=0.

**Stack Trace:**
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x2ac2fb8fddc0>
Traceback (most recent call last):
  File "/home-4/strobelm@umd.edu/pytorch_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home-4/strobelm@umd.edu/pytorch_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/home-4/strobelm@umd.edu/pytorch_env/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

## Environment

* OS: CentOS Linux release 7.6.1810
* Python version: 3.9.7
* PyTorch version: 1.9.1
* CUDA/cuDNN version: 10.2
* GCC version: 7.5.0

**Comment by rusty1s** [comment]
Which script/loader produces this error? Any additional info is much appreciated.

**Comment by Michael-C-Strobel** [comment]
I was able to recreate the issue with the following script. It seems that the issue is in NeighborLoader. When I set num_workers=0 for NeighborLoader the issue goes away.

```
from os import path as osp
import torch
from torch_geometric.loader import DataLoader, NeighborLoader, DataListLoader, ClusterData, ClusterLoader, dataloader
from torch_geometric.utils import dropout_adj, from_scipy_sparse_matrix
from torch_geometric.datasets import PPI
import torch_geometric
import torch

print(torch_geometric.__version__)
print(torch.__version__)

path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'PPI')
dataset = PPI(path, split='train')

loader = DataLoader(dataset)

for batch in loader:
    train_sampler = NeighborLoader(batch, num_neighbors=[-1,-1, -1], batch_size=1000, directed=True, num_workers=8) 
    for sample in train_sampler:
        print(sample)
```

**Comment by rusty1s** [comment]
This might happen due to [this line](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/loader/neighbor_loader.py#L133). Can you check what happens if you remove it?

**Comment by Michael-C-Strobel** [comment]
I commented the line out and unfortunately it's still happening. Is there any other info that I could provide that could help?

**Comment by rusty1s** [comment]
Ah, I think the main issue is the automatic `persistent_workers=True` call one line below, as you are throwing away your loader after processing one graph. I removed it in master.

**Comment by Michael-C-Strobel** [comment]
This fix seems to be working, thank you so much!
