### ISSUE TITLE
when I run pointnet2_classification in the example, something wrong happened!

### ISSUE THREAD

**Issue by ZhouAo-ZA** [pyg-team/pytorch_geometric#3475]
I run the pointnet2 classification in the example on the modelnet10 data set, but found that an error was reported, as below:

`    File "E:/code/pytorch_geometric-master/examples/pointnet2_classification.py", line 24, in forward
    x = self.conv((x, x[idx]), (pos, pos[idx]), edge_index)
TypeError: 'NoneType' object is not subscriptable
`

I found through debugging that there is no x in the data：

`DataBatch(pos=[32768, 3], y=[32], batch=[32768], ptr=[33])`

How can i fix it？

**Comment by rusty1s** [comment]
Thanks for letting me know. This is now fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/cca3c0cb1fec2e60e56465ec5efb18fe5d09797d
