### ISSUE TITLE
How to install torch_geometric with torch 1.4.0?

### ISSUE THREAD

**Issue by monk1337** [pyg-team/pytorch_geometric#3480]
## 📚 Installation

I am trying to install torch geometric with torch 1.4.0 and having different issues:

## Environment

* OS: Ubuntu 18.04.6 LTS
* Python version: Python 3.6.9
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.1
* GCC version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): 
* `pip3 install torch-scatter -f https://data.pyg.org/whl/torch-1.4.0+cu101.html`

Getting the following error :

```
    csrc/segment_coo.cpp: In static member function ‘static torch::autograd::variable_list SegmentMeanCOO::backward(torch::autograd::AutogradContext*, torch::autograd::variable_list)’:
    csrc/segment_coo.cpp:104:13: error: ‘class at::Tensor’ has no member named ‘true_divide_’
         grad_in.true_divide_(count);
                 ^~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/admin/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nye8v3oe/torch-scatter_42fd1ce5fcb14bec80024915646d0733/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nye8v3oe/torch-scatter_42fd1ce5fcb14bec80024915646d0733/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i_2gj1_5/install-record.txt --single-version-externally-managed --compile --install-headers 

```

**Comment by rusty1s** [comment]
For older PyTorch versions, you need to specify a version for `torch-scatter`, see [here](https://data.pyg.org/whl/torch-1.4.0%2Bcu101.html):
```
pip install torch-scatter==2.0.4 -f https://data.pyg.org/whl/torch-1.4.0+cu101.html
```

**Comment by OnurSelim** [comment]
Thank you a lot!

> For older PyTorch versions, you need to specify a version for `torch-scatter`, see [here](https://data.pyg.org/whl/torch-1.4.0%2Bcu101.html):
> 
> ```
> pip install torch-scatter==2.0.4 -f https://data.pyg.org/whl/torch-1.4.0+cu101.html
> ```
