### ISSUE TITLE
Custom Dataset Integration - OMDB

### ISSUE THREAD

**Issue by MiracAydin1** [pyg-team/pytorch_geometric#3483]
Dear all,

Thank you for your effort to create Pytorch-Geometric.

I am working with big molecules using OMDB dataset in Schnetpack. It is quite similar to QM9. The dataset includes xyz file for coordinates and csv file for bandgaps. You can see the dataset below:

[https://omdb.mathub.io/dataset](url)

QM9 is not that useful for models that work on big molecules because average size of a molecule in QM9 is aroung 9-11 atoms. I tried to create custom dataset from OMDB but it is a little bit complicated. I could not succeed it. 

Do you have any plan to implement new dataset like OMDB in the future? You have SchNetPack and DimeNet implementation and they are extremely useful for quantum users. It would be great to work with OMDB using Pytorch-Geometric.

I appreciate your help.
Mirac

**Comment by rusty1s** [comment]
Yes, that's definitely something we are interested in. Let me know if you wanna help us with this :)

**Comment by rusty1s** [comment]
I created a PR (https://github.com/pyg-team/pytorch_geometric/pull/3506) to integrate the `OMDB` dataset. Please let me know your thoughts and if the provided information (`pos`, atomic type, bandgap) is sufficient for your use-case.

**Comment by MiracAydin1** [comment]
Hi @rusty1s,

Thank you so much for your help. You the real MVP :)

I will test this datasets and inform you according to the result. So far, your integration (atomic type, bandgap) seems fair enough.

Best regards.
