### ISSUE TITLE
OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor5zero_Ev

### ISSUE THREAD

**Issue by mmtan** [pyg-team/pytorch_geometric#3486]
I executed the following command in Colab 
```

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

import torch
import torch_geometric.transforms as T
```

and encountered the following error: 

`OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor5zero_Ev`

There wasn't such error when I ran it last week.

**Comment by rusty1s** [comment]
See here: https://github.com/pyg-team/pytorch_geometric/issues/3484
