### ISSUE TITLE
WikipediaNetwork Download Error

### ISSUE THREAD

**Issue by csbobby** [pyg-team/pytorch_geometric#3491]
## 🐛 Bug

Reported Http Error when downloading the 'chameleon' dataset of WikipediaNetwork:
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
       
## To Reproduce

from torch_geometric.datasets import WikipediaNetwork
dataset_name = 'chameleon'
dataset = WikipediaNetwork('aaa', dataset_name)
    

## Expected behavior

Download dataset

**Comment by rusty1s** [comment]
Should be fixed in master. The original data sources have been removed in the [`geom-gcn`](https://github.com/graphdml-uiuc-jlu/geom-gcn) repo.
