### ISSUE TITLE
OSError: python3.8/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by JhuoW** [pyg-team/pytorch_geometric#3496]
When I upgrade Pytorch from 1.9 to 1.10 and Pytorch_geometric from 1.71. to 2.0.2, and I have also upgraded torch_sparse, torch-scatter, and torch-sparse， but when I run ```import torch_geometric```, the following error occurs: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.8/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/anaconda3/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/anaconda3/lib/python3.8/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "anaconda3/lib/python3.8/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/anaconda3/lib/python3.8/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/anaconda3/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /anaconda3/lib/python3.8/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

When I use Pytorch 1.9 with Pytorch_geometric 1.71，there is no such error.

My cuda version is CUDA Version 10.2.89
My Pytorch Cuda Version is 10.2

**Comment by rusty1s** [comment]
Can you ensure that there exists no older libraries? What happens if you run
```
pip uninstall torch-scatter torch-sparse
```
repeatedly and try to install again?

**Comment by JhuoW** [comment]
@rusty1s  Thanks, it has been solved. However, I do not know what it means when I run the former code ```data = dataset[0]```:
```
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.
```
How can I modify the code to adapt to the new version of PYG, could you give me an example？

**Comment by Sunjin-K** [comment]
Hi JhuoW, can you tell me how you resolved this issue?

**Comment by Sunjin-K** [comment]
Nevermind, I found this:
https://github.com/pyg-team/pytorch_geometric/issues/999

**Comment by harry-fuyu** [comment]
I encountered the same issue with torch==1.11.0 and pyg==2.1.0, both installed via conda. (but I'm using mambaforge)
I solved this by `conda uninstall pyg` first, then just `pip install torch_geometric`.
Might worth a try... although mixing pip with conda is generally not recommended.
