### ISSUE TITLE
question about GCN implementation formula

### ISSUE THREAD

**Issue by hogsmeade89** [pyg-team/pytorch_geometric#3507]
## ❓ Questions & Help

Hello, the "Creating Message Passing Networks" document metions
The GCN layer is mathematically defined as
```math
\mathbf{x}_i^{(k)} = \sum_{j \in \mathcal{N}(i) \cup \{ i \}} \frac{1}{\sqrt{\deg(i)} \cdot \sqrt{\deg(j)}} \cdot \left( \mathbf{\Theta} \cdot \mathbf{x}_j^{(k-1)} \right)
```

But I am wondering, to keep the same \theta as in matrix formulation, should the theta comes after the x and be something like this?

```math
\mathbf{x}_i^{(k)} = \sum_{j \in \mathcal{N}(i) \cup \{ i \}} \frac{1}{\sqrt{\deg(i)} \cdot \sqrt{\deg(j)}} \cdot \left( \mathbf{x}_j^{(k-1)}  \cdot \mathbf{\Theta} \right)
```

**Comment by rusty1s** [comment]
Yeah, in practice one would either need to transpose `x` or `Theta` to achieve similar output. I added the transpose to `Theta` in the `GCNConv` doc.

**Comment by hogsmeade89** [comment]
Thanks for your reply. Could you also add the transpose to `Theta` here? https://pytorch-geometric.readthedocs.io/en/latest/notes/create_gnn.html#the-messagepassing-base-class

**Comment by rusty1s** [comment]
Done.
