### ISSUE TITLE
Outdated example in the docs

### ISSUE THREAD

**Issue by remondn-swk** [pyg-team/pytorch_geometric#3512]
## 🐛 Bug

In the docs :

https://github.com/pyg-team/pytorch_geometric/blob/master/docs/source/notes/introduction.rst#L99

This is outdated, and should be instead :

```
data.num_node_features
```

**Comment by rusty1s** [comment]
Can you clarify what you mean? Line 99 already contains `data.num_node_features`.

**Comment by remondn-swk** [comment]
My bad, I must have see an older version of the docs
