### ISSUE TITLE
Return undefined attribute of torch_geometric.data.Data

### ISSUE THREAD

**Issue by JhuoW** [pyg-team/pytorch_geometric#3513]
In the prior version of PyG (1.7.1), when I call a undefined attribute of torch_geometric.data.Data, it will return ```None```. For example, given a  torch_geometric.data.Data ```Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708])```, and I use ```data.edge_weight``` and ```None``` will be returned.  However, in PyG 2.0.2, it raise the following error:
```
AttributeError: 'GlobalStorage' object has no attribute 'edge_weight'
```
In my project, there are several undefined attributes needed to return ```None``` like v1.7.1, rather than raising an error. How to fix it?

**Comment by rusty1s** [comment]
I added the `edge_weight` property back in, see https://github.com/pyg-team/pytorch_geometric/commit/11f881bf0133ea63f92174b6d496c1d30f1e25ff, but overall PyG 2.0 is a little bit more stricter on how it handles `None` values to prevent some common mistakes (e.g., adding edge weights to a `conv` operator although it is undefined) and to be more in-line with how Python dictionaries work. If you want to restore the old behavior, it's best to access attributes via `data.get('edge_weight', None)`

**Comment by JhuoW** [comment]
Thanks for your reply.
