### ISSUE TITLE
Subgraph Data instance generation for inductive learning setting

### ISSUE THREAD

**Issue by maximocrv** [pyg-team/pytorch_geometric#3515]
## 🚀 Feature
Given a graph (in a Data instance), you would be able to provide to a set of train/val/test indices for the nodes and output a new Data instance whose node feature matrix is determined by the indices, and whose edge index consists of reindexed edges (so they correspond to the new node feature matrix) contained only within the nodes indicated by the provided indices. 

## Motivation
This would be useful and frequently used in the inductive learning setting (would help with more compact code), and could be implemented with help of the `torch_geometric.utils.subgraph` function.

**Comment by rusty1s** [comment]
This is now integrated in master, see #3521:
```python
data = data.subgraph(torch.tensor([0, 1, 2, 3]))
```
