### ISSUE TITLE
question about `ogbn_products_sage` implementation (NeighborSampler)

### ISSUE THREAD

**Issue by Lintianqianjin** [pyg-team/pytorch_geometric#3518]
## ❓ Questions & Help
In line 167 in the implementation ( https://github.com/pyg-team/pytorch_geometric/blob/master/examples/ogbn_products_sage.py ), I am confused about why the `NeighborSampler` for inference only set `sizes` to `[-1]`, which means the sampler only considers 1-hop neighbors I guess. Should not it be consistent with the training stage?

**Comment by rusty1s** [comment]
During inference, we make use of layer-wise computation of node embeddings. That is, we use `NeighborSampler` to sample the full 1-hop neighborhood of each node in the mini-batch, and compute the node embeddings of each node in layer `i` before moving to layer `i + 1`. This saves a lot of GPU memory, as we do not have to sample the full `k`-hop neighborhood for a mini-batch, e.g., `[-1, -1, -1]` which might be intractable on same datasets with high node degree.

**Comment by Lintianqianjin** [comment]
> During inference, we make use of layer-wise computation of node embeddings. That is, we use `NeighborSampler` to sample the full 1-hop neighborhood of each node in the mini-batch, and compute the node embeddings of each node in layer `i` before moving to layer `i + 1`. This saves a lot of GPU memory, as we do not have to sample the full `k`-hop neighborhood for a mini-batch, e.g., `[-1, -1, -1]`, which might be intractable on same datasets with high node degree.

I understand, thanks a lot!
