### ISSUE TITLE
MLP weight initialization in SchNet filter generating networks

### ISSUE THREAD

**Issue by nec4** [pyg-team/pytorch_geometric#3523]
## 🐛 Bug

This is a very small thing, but in `InteractionBlock.reset_parameters()`, the first few calls to `torch.nn.init.xavier_uniform_` read:

```
torch.nn.init.xavier_uniform_(self.mlp[0].weight)
self.mlp[0].bias.data.fill_(0)
torch.nn.init.xavier_uniform_(self.mlp[2].weight)
self.mlp[0].bias.data.fill_(0)
``` 
to reset the filter generating network weights/biases. Should the fourth line be instead:

```
self.mlp[2].bias.data.fill_(0)
```
if the intent is to also fill the the biases of the second `torch.nn.Linear` layer with zeros?

## To Reproduce

visit https://github.com/pyg-team/pytorch_geometric/blob/4dc1a4cbc1477a2f713be2f15b155bfe4401023e/torch_geometric/nn/models/schnet.py#L294

## Expected behavior

```
torch.nn.init.xavier_uniform_(self.mlp[0].weight)
self.mlp[0].bias.data.fill_(0)
torch.nn.init.xavier_uniform_(self.mlp[2].weight)
self.mlp[2].bias.data.fill_(0)
``` 
If the intent is to fill the biases of the second `torch.nn.Linear` layer with zeros.

## Environment

Any.

## Additional context

Thanks for continuing to support/guide development on these amazing tools!

**Comment by rusty1s** [comment]
Thanks for spotting. This is now fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/817a6b766ab8c08760cd45a623d60ada9b6b73d4.
