### ISSUE TITLE
installed successfully, but could not be imported

### ISSUE THREAD

**Issue by peggy-minyao** [pyg-team/pytorch_geometric#3526]
## 📚 Installation

 1 import torch_geometric as pyg

~/anaconda3/lib/python3.7/site-packages/torch_geometric/__init__.py in <module>
      5 from .debug import is_debug_enabled, debug, set_debug
      6 
----> 7 import torch_geometric.data
      8 import torch_geometric.loader
      9 import torch_geometric.transforms

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py in <module>
----> 1 from .data import Data
      2 from .hetero_data import HeteroData
      3 from .temporal import TemporalData
      4 from .batch import Batch
      5 from .dataset import Dataset

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py in <module>
      1 from typing import (Optional, Dict, Any, Union, List, Iterable, Tuple,
      2                     NamedTuple, Callable)
----> 3 from torch_geometric.typing import OptTensor, NodeType, EdgeType
      4 from torch_geometric.deprecation import deprecated
      5 

~/anaconda3/lib/python3.7/site-packages/torch_geometric/typing.py in <module>
      1 from typing import Tuple, Optional, Union, List
      2 
----> 3 from torch import Tensor
      4 from torch_sparse import SparseTensor
      5 

ImportError: cannot import name 'Tensor' from 'torch' (unknown location)
-->

## Environment

* OS:
* Python version:2.7
* PyTorch version:1.9
* CUDA/cuDNN version:cpu
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source):pip
* Any other relevant information:

## Checklist

- [ yes] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [yes ] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
Does `import torch` and `from torch import Tensor` work for you when not importing PyG?

**Comment by peggy-minyao** [comment]
> Do `import torch` and `from torch import Tensor` work for you when not importing PyG?
thankyou! I reinstall torch again and try reinstall torch_sparse etc. like you answer in other issue, the problem was solved.
