### ISSUE TITLE
Static graph with varying node features: node_dim parameter works in many cases e.g. with GCNConv but not with GATConv.

### ISSUE THREAD

**Issue by daniel-unyi-42** [pyg-team/pytorch_geometric#3529]
Hi,

I have a static graph with varying node features, the tensor shape is [batch_size x num_nodes x num_features].
I used the node_dim parameter in many cases e.g. with GCNConv, and it worked properly.
However, I cannot use this parameter with GATConv:

[super().__init__(node_dim=0, **kwargs)](https://github.com/pyg-team/pytorch_geometric/blob/817a6b766ab8c08760cd45a623d60ada9b6b73d4/torch_geometric/nn/conv/gat_conv.py#L102)

I saw in the code that it's intentional, but I don't know why it's not supported. Is there a way to overcome this issue?

Thank you very much,
Daniel

**Comment by rusty1s** [comment]
Currently the only way to overcome that is to utilize default mini-batching in PyG (using the same graph) when using `GATConv`. Static graph support in `GATConv` is tricky, as the weights of the graph are not really static, but learned inside of `GATConv` instead.

**Comment by daniel-unyi-42** [comment]
I see. Thank you for the quick help!
