### ISSUE TITLE
Recovering global node ids from NeighborLoader

### ISSUE THREAD

**Issue by JasonMoho** [pyg-team/pytorch_geometric#3535]
The NeighborLoader maps the node ids of the sampled neighbors to the unique node ids in the set of neighbors, is there a way to recover the global node ids as with the [NeighborSampler](https://github.com/pyg-team/pytorch_geometric/issues/1904#issuecomment-740784062)? I couldn't find any class members which contain the map (which looks to be performed in [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/neighbor_sample_cpu.cpp#L15) somewhere). 

This example highlights the issue. 
```
from torch_geometric.datasets import RelLinkPredDataset
from torch_geometric.loader import NeighborLoader

path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'RLPD')
dataset = RelLinkPredDataset(path, 'FB15k-237')
data = dataset[0]

neighbor_loader = NeighborLoader(data, [-1], batch_size=1) # get all neighbors of node id 0 

output_data = next(iter(neighbor_loader))
print(output_data.edge_index) # print sampled neighbors (There are 10 in total)

src_sort = torch.argsort(data.edge_index[0]) 
print(data.edge_index[:, src_sort][:, :10]) # print neighbors of 0 by sorting the edge list
```

This outputs:
```
# received from NeighborLoader
tensor([[0, 0, 1, 1, 2, 3, 4, 4, 5, 6],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
        
# want this
tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 9448,  6786,     0,  6786,     0,  2548,  1042,  4994, 11757,  1042]])
```

How can I perform the mapping to get the proper global node ids? 

Also, I may be reading this wrong, but it seems like the source and destination of the output edge_index are flipped. As node 0 is in output_data[1, :] rather than output_data[0, :].

**Comment by JasonMoho** [comment]
For a workaround I am just going to call `torch.ops.torch_sparse.neighbor_sample` directly.

As the first return value `node` has the mapping it looks like: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/loader/neighbor_loader.py#L193

**Comment by rusty1s** [comment]
See https://github.com/pyg-team/pytorch_geometric/discussions/3528
