### ISSUE TITLE
TransformerConv Layer Incompatible with torch.jit.script

### ISSUE THREAD

**Issue by RobMcH** [pyg-team/pytorch_geometric#3537]
## 🐛 Bug

The TransformerConv layer is incompatible with torch.jit.script as `self._alpha` is not initialised in the constructor, which causes `torch.jit.script` to crash with the error message `Tried to access nonexistent attribute`.

## To Reproduce

1. Create model with TransformerConv layers, add `.jittable()` call when initialising layers to make them jittable.
1. Wrap model in `torch.jit.script` call to jit the model.
1. Feed any inputs into the model, observe crash.

## Expected behavior
No crash.

## Environment

* OS: Ubuntu 20.04
* Python version: 3.8
* PyTorch version: 1.8
* CUDA/cuDNN version: None
* GCC version: Used prebuilt binaries.
* Any other relevant information: PyTorch Geometric 2.0.1/2.0.2

## Additional context

The fix is trivial, simply initialise `self._alpha = None` in the constructor of the layer.

**Comment by RobMcH** [comment]
Corresponding [https://github.com/pyg-team/pytorch_geometric/pull/3538](fix and pull request).

**Comment by rusty1s** [comment]
Fixed by https://github.com/pyg-team/pytorch_geometric/pull/3538.
