### ISSUE TITLE
OMDB Dataset Import Error

### ISSUE THREAD

**Issue by MiracAydin1** [pyg-team/pytorch_geometric#3541]
Hi @rusty1s,

Thank you again for integration of OMDB dataset.

I checked features of both QM9 and OMDB. Result is like below:

OMDB edge features 0
OMDB features 0
OMDB node features 0
OMDB classes 9955
################
QM9 edge features 4
QM9 features 11
QM9 node features 11
QM9 classes 19

QM9 has some classes including homo, lumo, bandgap, energy and so on. But OMDB has only one class which is bandgap. I think there is a problem here but I could not figure it out how to solve this.

For test purposes, I tried to run the "QM9 pretrained schnet model" [https://github.com/pyg-team/pytorch_geometric/blob/master/examples/qm9_pretrained_schnet.py](url)

I ran the code snipped below:

```python
for target in range(12):
    model, datasets = SchNet.from_qm9_pretrained(path, dataset, target)
    train_dataset, val_dataset, test_dataset = datasets
```

And it gave the following error:

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/torch_geometric/data/storage.py in __getattr__(self, key)
     49         except KeyError:
     50             raise AttributeError(
---> 51                 f"'{self.__class__.__name__}' object has no attribute '{key}'")
     52 
     53     def __setattr__(self, key: str, value: Any):

AttributeError: 'GlobalStorage' object has no attribute 'idx'

I am not sure but this error may occur because of the line 172 in schnetpack model integration: https://github.com/pyg-team/pytorch_geometric/blob/70eb7883ab65f419c8022775c08777927efc4cb8/torch_geometric/nn/models/schnet.py#L172

Do you have any suggestion to solve the issue?
Thank you for your help.

**Comment by rusty1s** [comment]
Note that you still need to pass the `QM9` dataset to `from_qm9_pretrained`. This is currently required (for splitting purposes of `QM9`), although I see a point in making this argument optional. Given a trained model, you can then apply it to the `OMDB` dataset.

**Comment by MiracAydin1** [comment]
Hi @rusty1s ,

Thanks for suggestion.

I tried to give QM9 dataset as you mentioned and edited the code snippet below:

`device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

path = osp.join(osp.dirname(osp.realpath('/content/gdrive/MyDrive/Colab Notebooks/Pytorch-Geometric')), '..', 'data', 'OMDB')
path2 = osp.join(osp.dirname(osp.realpath('/content/gdrive/MyDrive/Colab Notebooks/Pytorch-Geometric')), '..', 'data', 'QM9')

dataset1 = OMDB(path)
dataset2 = QM9(path2)

for target in range(12):
    model, datasets = SchNet.from_qm9_pretrained(path, dataset2, target)
   
    # there are 12500 datapoints in OMDB

    train_dataset = dataset1[:10000]
    val_dataset = dataset1[10000:11000]
    test_dataset = dataset1[11000:]
    
    model = model.to(device)
    test_loader = DataLoader(test_dataset, batch_size=16)

    #train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    #val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False) 

    maes = []
    for data in test_loader:
        data = data.to(device)
        with torch.no_grad():
            pred = model(data.z, data.pos, data.batch)
        mae = (pred.view(-1) - data.y[:, target]).abs()
        maes.append(mae)

    mae = torch.cat(maes, dim=0)

    # Report meV instead of eV.
    # mae = 1000 * mae if target in [2, 3, 4, 6, 7, 8, 9, 10] else mae

    print(f'Target: {target:02d}, MAE: {mae.mean():.5f} ± {mae.std():.5f}')`



In the line "mae = torch.cat(maes, dim=0", it gives the following error:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-52-7baa6210bb53> in <module>()
     32         maes.append(mae)
     33 
---> 34     mae = torch.cat(maes, dim=0)
     35 
     36     # Report meV instead of eV.

NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.

**Comment by rusty1s** [comment]
The `OMDB` dataset has a `train` argument, and so by default, it also contains 10000 examples.
```python
dataset1 = OMDB(path, train=False)
test_loader = DataLoader(test_dataset, ...)

mae = (pred.view(-1) - data.y).abs()
```
fixes the script for me.

**Comment by MiracAydin1** [comment]
Hi @rusty1s,

Thank you so much for your help. I am able to obtain test MAE now.
