### ISSUE TITLE
No module named 'torch_geometric.typing'

### ISSUE THREAD

**Issue by yaominghong** [pyg-team/pytorch_geometric#3542]
## Environment

* OS: windows 10
* Python version:3.6.3
* PyTorch version:1.2.0
* CUDA/cuDNN version:9.2
* GCC version:g++ (MinGW.org GCC-6.3.0-1) 6.3.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source):
* Any other relevant information:

## Checklist

- [v] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [v] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [v] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [v] I do have multiple CUDA versions on my machine.

## Additional context
i check the above things ,but always occur No module named 'torch_geometric.typing'

**Comment by rusty1s** [comment]
Which `torch_geometric` version (`torch_geometric.__version__`) are you using? The `typing` module was added in version 1.7.1.

**Comment by yaominghong** [comment]
My Version is 2.0.1. Thanks
