### ISSUE TITLE
return_attention_weights returned different number of edges

### ISSUE THREAD

**Issue by peggy-minyao** [pyg-team/pytorch_geometric#3550]
## ❓ Questions & Help

when i set return_attention_weights= True, i want get the weight of every edge of graph,however, i find the number of edge of return value is different from my input value even when i remove selfloop, i don't konw why?
my code:
x,w = self.conv1(x, edge_index,return_attention_weights= True)
edges = w[0]
weight = w[1]
edge, edge_weight = remove_self_loops(edges, weight)
print(edge_index.shape) --> torch.Size([2, 16282])
print(w[0].shape)  --> torch.Size([2, 34369])
print(edge.shape) --> torch.Size([2, 23564])

**Comment by rusty1s** [comment]
That's because `GATConv` will add self-loops as part of its computation (it also computes self-attention on the node itself). You can either remove self-loops of `edges` and `weights`, or istantiate `GATConv` via `add_self_loops=False`.

**Comment by peggy-minyao** [comment]
> That's because `GATConv` will add self-loops as part of its computation (it also computes self-attention on the node itself). You can either remove self-loops of `edges` and `weights`, or instantiate `GATConv` via `add_self_loops=False`.

i have removed self-loops of edges and weights, they are still differents.

**Comment by rusty1s** [comment]
Do you have an example to reproduce? The following works for me:
```python
from torch_geometric.datasets import Planetoid
from torch_geometric.nn import GATConv
from torch_geometric.utils import remove_self_loops

dataset = Planetoid('/tmp/Planetoid', name='Cora')
data = dataset[0]

conv = GATConv(dataset.num_features, 16)

out, w = conv(data.x, data.edge_index, return_attention_weights=True)

edges = w[0]
weight = w[1]
edge, edge_weight = remove_self_loops(edges, weight)

print(data.edge_index.shape)
print(edge.shape)
print(edge_weight.shape)
```

```
torch.Size([2, 10556])
torch.Size([2, 10556])
torch.Size([10556, 1])
```

**Comment by peggy-minyao** [comment]
thank you !!! I find the small data works for me. Maybe there are other problem in my code.
