### ISSUE TITLE
BaseTransform not available in torch_geometric.transforms

### ISSUE THREAD

**Issue by errhernandez** [pyg-team/pytorch_geometric#3564]
## ❓ Questions & Help

Hello! I am trying to device a transform class to manipulate my data; my understanding from the docs is that one should inherit BaseTransform and define __call__() to implement one's particular transform, but when I try to import torch_geometric.transforms.BaseTransform this appears not to exist (at least in my installation), though other content of transforms (such as compose) do exist. Did I misunderstand something?

Thanks!

**Comment by rusty1s** [comment]
Inheriting from `BaseTransform` is not absolutely necessary, but you can import it via `from torch_geometric.transforms.base_transform import BaseTransform`.

**Comment by rusty1s** [comment]
Which version of PyG are you using? This was introduced in `2.0.0.`. If the import fails, I suggest to simply inherit from `object` for your own transform.

**Comment by errhernandez** [comment]
Thanks; that explains. I have 1.7.0. I will upgrade, but I will also inherit from object and surely that will solve the problem. Thank you so much.
