### ISSUE TITLE
Adding input and output shapes to docs

### ISSUE THREAD

**Issue by Gaurangkarwande** [pyg-team/pytorch_geometric#3573]
Can you add to the documentation the input shape to a layer and the corresponding output shape after forward() has been executed. This is similar to the Pytorch documentation.

For e.g. - the documentation for 2D Convolution layer, nn.torch.Conv2d( ), states that:
input  = (N, Cin, H, W)
output = (N, Cout, Hout, Wout)

## Motivation

I am fairly new to GNNs and pytorch-geometric. I think it will be a lot easier and smooth for newbies/noobies like me to get a sense of the dimensional transformation within layer.

## Additional context

nn.torch.Conv2d( ) - 

![image](https://user-images.githubusercontent.com/49279636/143517046-8ae3e10c-71e5-4bde-abdb-c2de265be92f.png)

**Comment by rusty1s** [comment]
This is a great point, but it will involve a lot of work. Let me know if you want to help me with that. 

In general, The input of a `GNN` layer will be `[num_nodes, in_channels]` and will output a tensor of shape `[num_nodes, out_channels]`.

**Comment by Gaurangkarwande** [comment]
Yeah, I sure can contribute. I am new to GNNs but I can try adding on the documentation for the models I know of are have used.

**Comment by rusty1s** [comment]
Super. Let's start with a single layer, e.g., `GraphConv` and go from there. Let me know if you need any more guidance.

**Comment by saiden89** [comment]
Do you think  `edge_index` and optional tensors like `edge_weight` should also be acknowledged as inputs?

**Comment by rusty1s** [comment]
Yeah, that would be something like:
* `edge_index: (2, num_edges)`
* `edge_weight: (num_edges)`

**Comment by saiden89** [comment]
Here is a proposal for `GraphConv`:

![image](https://user-images.githubusercontent.com/45285915/145580021-ddf1eb44-2962-4825-979f-974c10db5660.png)

I've tried to follow as closely as possible the conventions already established in PyTorch, as well as mathematical notations present in the literature. Along these guidelines, the `x` and `edge_index` are proxied by the calligraphic typeface V and E respectively, while enclosure with vertical bars (|) refers to the number of elements.
It would also be possible to ditch the mathematical notation altogether in favor of more agnostic solutions, but considering that this framework is specifically aimed towards GNN, I believe that some mathematic rigor can be justified.
Of course, I would love to hear the community's opinion 😄.

**Comment by rusty1s** [comment]
I think this is great :) Please feel free to contribute!
