### ISSUE TITLE
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by archerwushuai** [pyg-team/pytorch_geometric#3574]
## Environment

* OS:Red Hat Enterprise Linux Server release 7.4
* Python version:Python 3.7.9
* PyTorch version:1.7.1
* CUDA/cuDNN version:10.1
* GCC version:GCC 7.3.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): pip install torch-scatter -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
pip install torch-geometric
* Any other relevant information:

## Checklist

- [yes ] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [ yes] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [yes ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ no] I do have multiple CUDA versions on my machine.

## Additional context

i try to import torch_geometric,the error is :OSError: libc10_cuda.so: cannot open shared object file: No such file or directory.
detail:
Traceback (most recent call last):
  File "test_and_visulise.py", line 8, in <module>
    from models.gat_gcn import GAT_GCN
  File "/home/qmy/cyp/models/gat_gcn.py", line 5, in <module>
    from torch_geometric.nn import GCNConv, GATConv, GINConv, global_add_pool
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/qmy/anaconda3/envs/deeplearning/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

i can't find the libc10_cuda.so in my usr/local/lib/ , but i can find libcudart.so and libcudart.so.10.1.

**Comment by archerwushuai** [comment]
I downloaded it again with conda, and then it can be imported normally, although I don’t know why.

**Comment by sauhaardac** [comment]
For those who run into this error again, I solved it by starting in a fresh environment and first installing pyg using:
```
conda install -q -y pyg -c pyg
```
then, installing a cuda enabled version of pytorch
```
conda install -q -y pytorch cudatoolkit=11.3 -c pytorch
```

This first installs a CPU enabled version of torch in the first line and then replaces it with a GPU enabled version of torch. For whatever reason this was the only way I could resolve the error.

**Comment by rish-16** [comment]
> For those who run into this error again, I solved it by starting in a fresh environment and first installing pyg using:
> 
> ```
> conda install -q -y pyg -c pyg
> ```
> 
> then, installing a cuda enabled version of pytorch
> 
> ```
> conda install -q -y pytorch cudatoolkit=11.3 -c pytorch
> ```
> 
> This first installs a CPU enabled version of torch in the first line and then replaces it with a GPU enabled version of torch. For whatever reason this was the only way I could resolve the error.

This worked for me!!! Thank you :D

**Comment by sauhaardac** [comment]
Weirdly my solution above stopped working again for me. I found success with the following:
```
conda install pytorch==1.11.0 cudatoolkit=11.3 -c pytorch
```
then
```
conda install pyg -c pyg
```

**Comment by HelloWorldLTY** [comment]
Hi, both of the methods cannot work for me. Are there any offical solutions? Thanks.

**Comment by rusty1s** [comment]
We give detailed installation instructions in the README. Did you try pip-based installation already?

**Comment by HelloWorldLTY** [comment]
Hi, I used a cluster, so if I directly use pip based method, I may not successfully install some packages like so file.

**Comment by busraoguzoglu** [comment]
Hello, I'm having the same problem. Mentioned solutions unfortunately did not work for me. Can someone please share any official solution? (If there is any)

**Comment by HelloWorldLTY** [comment]
Hi all, I find the solution. The first step is to install pytorch 1.11.0 via pip, and the second step is to install pyg via conda. It works for me

**Comment by Powerdiao** [comment]
> For those who run into this error again, I solved it by starting in a fresh environment and first installing pyg using:
> 
> ```
> conda install -q -y pyg -c pyg
> ```
> 
> then, installing a cuda enabled version of pytorch
> 
> ```
> conda install -q -y pytorch cudatoolkit=11.3 -c pytorch
> ```
> 
> This first installs a CPU enabled version of torch in the first line and then replaces it with a GPU enabled version of torch. For whatever reason this was the only way I could resolve the error.

thank you very much.it works!
