### ISSUE TITLE
OSError when import torch_geometric

### ISSUE THREAD

**Issue by matthew-valentine** [pyg-team/pytorch_geometric#3575]
## 📚 Installation

I am trying to set up a Conda environment with the exact same versions of all the packages as in a paper (hence using an older version of PyTorch). Installation seemingly went perfectly, installing everything from within the Conda environment using pip, while specifying the correct wheel to use with -f as instructed in the installation guide. When I run list with pip it finds all of the required packages. However when I try to import torch_geometric I get the following error, as I have seen in many other issues:

```
OSError: /home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_
```

I have tried uninstalling and reinstalling, and making a fresh Conda environment and reinstalling everything there. As far as I can tell there is only one version of everything, no older libraries to cause confusion for python when trying to load them in. One maybe related problem is when I try to load in atom3d.datasets I get the warning message "torch geometric not found, GNN examples will not work until it is.". So maybe python is unable to locate torch_geometric for some reason?

## Environment

* OS: Linux
* Python version: 3.8
* PyTorch version: 1.5.0
* CUDA/cuDNN version: 10.1
* GCC version:
* How did you try to install PyTorch Geometric and its extensions (wheel, source): wheels
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

## Additional context

Full traceback:

```
Traceback (most recent call last):
  File "/home/matthew/.conda/envs/ares/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/matthew/.conda/envs/ares/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matthew/tools/ares_release/ares/train.py", line 11, in <module>
    import torch_geometric
  File "/home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/matthew/.conda/envs/ares/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/matthew/.conda/envs/ares/lib/python3.8/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_```

**Comment by rusty1s** [comment]
Can you tell me the versions you used for installing the extension packages?

**Comment by matthew-valentine** [comment]
I used the wheel https://pytorch-geometric.com/whl/torch-1.5.0+cu101.html for installation and got the following versions of the packages:

```
pytorch-lightning       1.3.8
torch                   1.5.0+cu101
torch-cluster           1.5.9
torch-geometric         2.0.2
torch-scatter           2.0.9
torch-sparse            0.6.12
torch-spline-conv       1.2.1
torchmetrics            0.6.0
torchvision             0.6.0+cu101
atom3d                  0.2.4
python-dotenv           0.19.2
wandb                   0.12.7
```

**Comment by rusty1s** [comment]
Thank you. Do you have a local CUDA installation that is different from CUDA 10.1? What's the output of `nvcc --version`?

**Comment by matthew-valentine** [comment]
The output of nvcc --version is command not found! I just tried installing everything on a new environment with "+cpu" instead of "+cu101", but I get the same error as before when trying to import torch_geometric.

**Comment by rusty1s** [comment]
Ok, got it. So this does not seem related to a version conflict with CUDA. How did you install PyTorch? We are only supporting the official binaries from PyTorch, and not, e.g., self-hosted versions in `conda-forge`.

**Comment by matthew-valentine** [comment]
I installed everything using pip:

```
TORCH="1.5.0"
TORCH_VISION="0.6.0" # Version compatible with torch 1.5.0
CUDA="+cu101"
python3.8 -m pip install torch==${TORCH}${CUDA} torchvision==${TORCH_VISION}${CUDA} -f https://download.pytorch.org/whl/torch_stable.html
```

When I run the sample PyTorch code to verify installation it seems to work fine.

**Comment by matthew-valentine** [comment]
So I was playing around with this and actually got the error to go away by installing an older version of torch-sparse (0.6.7)!

**Comment by Samarth-T-Setty** [comment]
Hi @matthew-valentine, Sorry to hijack/reopen this thread. Thank you for writing your solution here. It worked for me this way too. However, I have not been able to run the ARES training command. Were you able to run the tool successfully? If so would you mind, writing to me here - samarth.setty [at] ranchobiosciences.com

We are really interested in running the tool and unfortunately have issues running the train command!
