### ISSUE TITLE
num_classes is implemented in InMemoryDataset but not in Dataset

### ISSUE THREAD

**Issue by padmalcom** [pyg-team/pytorch_geometric#3578]
Hi, I created my own dataset using torch_geometric.data.dataset.

```
class FakeNewsDataset(Dataset):
	def __init__(self, root, filename, test=False, transform=None, pre_transform=None):
		self.test = test
		self.filename = filename
		super(FakeNewsDataset, self).__init__(root, transform, pre_transform)
```

I can set nodes and edges successfully in the process function, but when I want to create my model, I'm told that my model does not implement num_classes. Which is correct when I look at the code. Since this property is required for nearly all examples I find, I assume this is a bug?

**Comment by rusty1s** [comment]
`num_classes` is only provided by `InMemoryDataset` (it currently checks the number of classes by taking the maximum value of `y` for every example in the dataset).

**Comment by padmalcom** [comment]
Thank you, so I guess for a large dataset I have to provide it myself? I know how many classes I have.

**Comment by rusty1s** [comment]
Yes, you will need to implement it by yourself in this case :)

**Comment by padmalcom** [comment]
Thanks! :)
