### ISSUE TITLE
Wrong link in tutorial

### ISSUE THREAD

**Issue by hfarhidzadeh** [pyg-team/pytorch_geometric#3587]
Hi,

Reference :  https://github.com/pyg-team/pytorch_geometric/blame/master/docs/source/notes/colabs.rst#L25

The link for both notebooks are the same, point to link prediction. Second notebook should refers to label prediction. Please check the urls.

Thanks

**Comment by rusty1s** [comment]
Thanks for letting me know. This should now be fixed :)
