### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by hossam-zaki** [pyg-team/pytorch_geometric#3593]
## 📚 Installation

I have followed the instructions on the pytorch geometric website, and am repeatedly getting this error. The issues opened about this haven't been helpful either. I simply copy and paste the installation commands and get the error. Here's what I do

```
pip3 install torch torchvision torchaudio

```
and
```
pip3 install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.10.0+cu102.html
```
and when I import torch-spline-conv, I get the following
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_spline_conv/__init__.py", line 15, in <module>
    torch.ops.load_library(spec.origin)
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/gpfs/runtime/opt/python/3.7.4/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_spline_conv/_basis_cuda.so)
```

## Environment

* OS: Linux
* Python version: 3.7
* PyTorch version: 1.10.0
* CUDA/cuDNN version: 10.2
* GCC version: 10.2
* How did you try to install PyTorch Geometric and its extensions (wheel, source): Via the wheel and guide on the website
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I do have multiple CUDA versions on my machine.

**Comment by rusty1s** [comment]
All wheels require GLIBC=2.27 by now. You need to either upgrade GLIBC or install the extensions from source (might take some time):
```
pip install torch-scatter
```

**Comment by hossam-zaki** [comment]
I'll try this. But wouldn't this download the CPU version?

**Comment by hossam-zaki** [comment]
I followed these directions, and get the following:

```
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_sparse/__init__.py", line 16, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
```
Any advice with this?

**Comment by rusty1s** [comment]
This likely indicates that something went wrong while building the extension. Can you uninstall the package, re-install it and send the installation log?

**Comment by shahriar-faghani** [comment]
> ## 📚 Installation
> I have followed the instructions on the pytorch geometric website, and am repeatedly getting this error. The issues opened about this haven't been helpful either. I simply copy and paste the installation commands and get the error. Here's what I do
> 
> ```
> pip3 install torch torchvision torchaudio
> ```
> 
> and
> 
> ```
> pip3 install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.10.0+cu102.html
> ```
> 
> and when I import torch-spline-conv, I get the following
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_spline_conv/__init__.py", line 15, in <module>
>     torch.ops.load_library(spec.origin)
>   File "/gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch/_ops.py", line 110, in load_library
>     ctypes.CDLL(path)
>   File "/gpfs/runtime/opt/python/3.7.4/lib/python3.7/ctypes/__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /gpfs/home/hzaki1/celltypefromgrn/env/lib/python3.7/site-packages/torch_spline_conv/_basis_cuda.so)
> ```
> 
> ## Environment
> * OS: Linux
> * Python version: 3.7
> * PyTorch version: 1.10.0
> * CUDA/cuDNN version: 10.2
> * GCC version: 10.2
> * How did you try to install PyTorch Geometric and its extensions (wheel, source): Via the wheel and guide on the website
> * Any other relevant information:
> 
> ## Checklist
> * [x]  I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
> * [x]  I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
> * [x]  I set up CUDA correctly and can compile CUDA code via `nvcc`.
> * [ ]  I do have multiple CUDA versions on my machine.
> 
> ## Additional context

Same error here!

**Comment by hossam-zaki** [comment]
I was able to resolve the error by 
1. Changing my cuda version to 10.2
2. Lowering my GCC Version
3. making sure that I was installing the packages from the source (not from the .whl files given in the installation page) with the GPU available

**Comment by melancholicwang** [comment]
have same error.
lower to torch_geometric=2.0.2 fix.

**Comment by Michael-C-Strobel** [comment]
I'm also currently running into the same issue. It only seems to happen when I have PyTorch 1.10.x installed. I was able to temporarily avoid it by switching to PyTorch 1.9.0 and using the Anaconda instillation in the quick start.

**Comment by rusty1s** [comment]
Yeah, PyTorch 1.9 might fix thix. I'm still not sure how to fix this on our ends (although manual installation is always an option), since we use `ubuntu-1804` to build the wheels (which comes with `GLIBC_2.27`). Any help or pointers highly appreciated :)

**Comment by edgarsmdn** [comment]
I faced the same error, and indeed installing [`PyTorch 1.9.0`](https://pytorch.org/get-started/previous-versions/) and then installing PyG with `conda` did the trick.

**Comment by jacanchaplais** [comment]
Same issue here when installing with conda. Here's my `environment.yml` contents. :)

```yaml
name: gnn
channels:
  - conda-forge
dependencies:
  - python=3.9.10
  - pip=22.0.3
  - setuptools=59.5.0
  - click
  - cudatoolkit=11.3.1
  - cupy
  - rapidsai::cudf
  - pytorch::pytorch=1.10.2
  - torchmetrics  # modular ML metrics for PyTorch
  - pytorch-lightning  # parallelisation
  - pyg::pyg=2.0.3  # pytorch geometric
  - tensorboard  # visualising metrics
  - numpy=1.20
  - pandas<1.4.0
  - omegaconf
  - tqdm
  - "hdf5=1.*=mpi_openmpi*"
  - "h5py=3.*=mpi_openmpi*"
  - ipython=7.28.0
  - jupyter
  - pythia8
  - attrs
  - networkit
  - plotly
  - matplotlib
```

**Comment by chocolocked** [comment]
> I faced the same error, and indeed installing [`PyTorch 1.9.0`](https://pytorch.org/get-started/previous-versions/) and then installing PyG with `conda` did the trick.

thank you so much it worked for me!

**Comment by Zhen-Tan-dmml** [comment]
> Try
> 
> ```
> conda install pyg -c pyg -c conda-forge
> ```
> 
> for PyTorch 1.9 :)

Thank you for your instant reply! It works.

**Comment by 666-sudo** [comment]
I had similar errors. Thanks for the above suggestions. I fixed the problems by: 

```
conda uninstall pytorch
conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=10.2 -c Pytorch
conda install pyg -c pyg -c conda-forge
```

**Comment by 666-sudo** [comment]
version `GLIBC_2.27' not found  ->> it was also resolved by 
`pip uninstall torch-spline-conv`

For A100 cards that lowering install versions was not compatible.

**Comment by KingsleyHsu** [comment]
I am having trouble（GLIBC_2.27' not found） installing the latest version 1.21.1：

conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
pip install torch-geometric
pip install torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.12.1+cu102.html

and I try the 1.19 and still encountered（  ERROR: Failed building wheel for torch-cluster and  torch-sparse）:

conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=10.2 -c pytorch

pip install torch-scatter -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
pip install torch-geometric

pip install torch-cluster -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.9.0+cu102.html

More importantly, ogb ==1.3.4 reminds that the geometric version is too low

**Comment by rusty1s** [comment]
The `GLIB_2.27` not found issue happens due to `torch-spline-conv`. Just uninstalling the dependency should fix this issue.

**Comment by KingsleyHsu** [comment]
Thanks, solved the issue by uninstalling the torch-spline-conv.

**Comment by sololzc** [comment]
> version `GLIBC_2.27' not found ->> it was also resolved by `pip uninstall torch-spline-conv`
> 
> For A100 cards that lowering install versions was not compatible.

It works!!

**Comment by ustcsky** [comment]
> 谢谢，通过卸载torch-spline-conv解决了这个问题。

解决，谢谢

**Comment by jasperhyp** [comment]
Actually, what does `torch-spline-conv` do if it can usually be uninstalled?

**Comment by rusty1s** [comment]
`torch-spline-conv` holds the CUDA implementation of our `SplineConv` operator. If you are not making use of it, it is save to remove the dependency.

**Comment by Raymundo-cj** [comment]
> > 谢谢，通过卸载torch-spline-conv解决了这个问题。
> 
> 解决，谢谢

thanks，I have solved the problem in your way, but want to know the reason why ```uninstall torch-spline-conv``` can solve this problem?

**Comment by jiayaonan** [comment]
When I was using roseTTAFold2NA, I encountered an error OSError:/lib64/libm. so. 6: version ` GLIBC_2.27 'not found. I understood it to be updating libm. so. 6, but this is a library that all underlying files require, such as mv, cp, etc., and the system crashed
OS：centos7
但是在centos8的时候就没有问题

**Comment by jiayaonan** [comment]
When I was using roseTTAFold2NA, I encountered an error OSError:/lib64/libm. so. 6: version ` GLIBC_2.27 'not found. I understood it to be updating libm. so. 6, but this is a library that all underlying files require, such as mv, cp, etc., and the system crashed
OS：centos7


But there was no problem with Centos8
