### ISSUE TITLE
Examples in Jupyter

### ISSUE THREAD

**Issue by gourav-sg** [pyg-team/pytorch_geometric#3600]
## 📚 Documentation of examples

Examples as mentioned here: https://github.com/pyg-team/pytorch_geometric/tree/master/examples

All the examples in python code without any documentation or pydoc, this makes it extremely painful to read and understand. Should the purpose of examples not be to explain and elucidate? For most users the entry point to the libraries are the examples, and using Jupyter notebooks or properly in-code documentation makes up for an easy adoption.

**Comment by rusty1s** [comment]
I'm sorry to hear. I always had plans to clean up the examples to make them more user-friendly, but hadn't have time to do this yet.

If you are completely new to GNNs, it's probably best to start with our [Colabs](https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html) :)

**Comment by gourav-sg** [comment]
Hi @rusty1s ,
thanks I am using the details in Colab, and closing this. Thank you so very much.
