### ISSUE TITLE
RuntimeError while using GDC

### ISSUE THREAD

**Issue by Misterion777** [pyg-team/pytorch_geometric#3618]
Hi, i'm experiencing this error while using GDC with parameters from [example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/gcn.py#L21-L25):

```
 File "/Users/ilyalasy/opt/anaconda3/envs/tg/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 199, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/Users/ilyalasy/opt/anaconda3/envs/tg/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Users/ilyalasy/opt/anaconda3/envs/tg/lib/python3.8/site-packages/torch_geometric/transforms/gdc.py", line 107, in __call__
    edge_index, edge_weight = self.sparsify_dense(
  File "/Users/ilyalasy/opt/anaconda3/envs/tg/lib/python3.8/site-packages/torch_geometric/transforms/gdc.py", line 372, in sparsify_dense
    edge_index = torch.stack([top_idx.flatten(), row_idx], dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [2704] at entry 0 and [6656] at entry 1
```
I am passing GDC callable as a [transform](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/dataset.py#L28-L31) parameter to custom dataset, probably each data object should have some specific properties for such parameters to work?

### Environment

* PyG version: `2.0.2`
* PyTorch version:`1.10.0`
* OS:`MacOS`
* Python version:`3.8.11`
* CUDA/cuDNN version: `cpu`
* How you installed PyTorch and PyG:`pip`

**Comment by rusty1s** [comment]
Do you have a small example to reproduce?

**Comment by Misterion777** [comment]
```
import torch
import torch_geometric.transforms as T

transform = T.GDC(self_loop_weight=1, normalization_in='sym',
                normalization_out='col',
                diffusion_kwargs=dict(method='ppr', alpha=0.05),
                sparsification_kwargs=dict(method='topk', k=128,
                                           dim=0), exact=True)

path = 'data_1.pt'

data = torch.load(path)
print(data)
transformed = transform(data)
print(data)
```
You can try [this](https://drive.google.com/file/d/1oU6cHm7wGn8omqAQWce82vsgBLVbGfQg/view?usp=sharing) data object.
I have multiple data objects that cause this bug, and one common thing is that they have first dimension shape significantly smaller than the feature dimension, e.g:
```
Data(x=[52, 300], edge_index=[2, 102], y=[52, 2])
Data(x=[64, 300], edge_index=[2, 126], y=[64, 2])
Data(x=[61, 300], edge_index=[2, 120], y=[61, 2])
```
Although, this example works fine: `Data(x=[263, 300], edge_index=[2, 524], y=[263, 2])`

**Comment by rusty1s** [comment]
Thank you. This is really helpful. I fixed the issue in master, see https://github.com/pyg-team/pytorch_geometric/commit/7fc1767ece2edd614575dcbff1eb8f79f1035742.

The issue was that `k` was larger than the number of nodes. A simple `k = min(k, num_nodes)` fixes this issue :)
