### ISSUE TITLE
Bug in neighbor_loader if data.num_nodes == data.num_edges

### ISSUE THREAD

**Issue by WuliangHuang** [pyg-team/pytorch_geometric#3626]
## 🐛 Bug

In `torch.loader.neighbor_loader`, when collecting a batch, if `batch.num_nodes == batch.num_edges`, the behavior will be unwanted.

### To Reproduce

Following is a small case:
```python
import torch
from torch_geometric.loader import NeighborLoader
from torch_geometric.data import Data

edge_index = torch.LongTensor(
    [[0, 1, 2, 3, 4], [1, 2, 3, 4, 0]])  # this will create a circular graph.
data = Data(
    edge_index=edge_index,
    node_id=torch.arange(5),
    num_nodes=5,
)

data_loader = NeighborLoader(data, num_neighbors=[1, 1],
                             input_nodes=torch.LongTensor([0, 3]),
                             # sample for node 0 and 2
                             batch_size=2, shuffle=True)

for batch in data_loader:
    print(f'{batch=}')
    print(f'{batch.edge_index=}')
    print(f'{batch.node_id=}')
    print(f'{batch.num_nodes=}')
```
The output of this case is:
```python
batch=Data(edge_index=[2, 4], node_id=[4], num_nodes=5, batch_size=2)
batch.edge_index=tensor([[2, 3, 1, 4],
        [0, 1, 2, 3]])
batch.node_id=tensor([1, 4, 2, 3])
batch.num_nodes=5
```

### Expected behavior

There should be 5 nodes, however, there are only four nodes.

### Environment

* PyG version (`torch_geometric.__version__`):2.0.2
* PyTorch version: (`torch.__version__`):1.10.0+cu113
* OS (*e.g.*, Linux): Ubuntu 20.04.3 LTS
* Python version (*e.g.*, `3.9`): 3.8.10
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): following the install instruction

### Additional context

This type of problems will only happen when batch.num_nodes equals batch.num_edges. In `torch_geometric.loader.utils.py` , it first checks tensor whose first dimension matches batch.num_nodes or batch.num_edges, and then collects them into a new batch. All the tensor will follow `filter_node_store_` if `num_nodes == num_edges`.
https://github.com/pyg-team/pytorch_geometric/blob/e8915ad1cb5831c33c77f0fa69ee8a2267074647/torch_geometric/loader/utils.py#L102-L111

https://github.com/pyg-team/pytorch_geometric/blob/e8915ad1cb5831c33c77f0fa69ee8a2267074647/torch_geometric/loader/utils.py#L71-L72

https://github.com/pyg-team/pytorch_geometric/blob/e8915ad1cb5831c33c77f0fa69ee8a2267074647/torch_geometric/loader/utils.py#L96-L97

### My suggestions
I think we can add a warning if `batch.num_nodes == batch.num_edges`, and add a more explicit way for user to define if a variable is relelated to nodes feature or edge feature.

Such as in torch_geometric.loader.utils.py L59-L70:
```python
# def filter_node_store_(store: NodeStorage, index: Tensor) -> NodeStorage:
def filter_node_store_(store: NodeStorage, index: Tensor, keys:List[str]) -> NodeStorage:  # add
    # Filters a node storage object to only hold the nodes in `index`:
    num_nodes = store.num_nodes

    for key, value in store.items():
        if key == 'num_nodes':
            store.num_nodes = index.numel()
        
        if keys is not None and key in keys: # add
            store[key] = value[index] # add
        elif isinstance(value, Tensor) and value.size(0) == num_nodes:
            store[key] = value[index]

    return store
```

**Comment by rusty1s** [comment]
Thanks for letting me know. I fixed this in master by making use of `data.is_edge_attr(key)`.
