### ISSUE TITLE
K-fold cross validation for GCNs in PyTorch Geometric

### ISSUE THREAD

**Issue by bianchiniriccardo95** [pyg-team/pytorch_geometric#3663]
Hello!
First of all, thanks for this amazing tool.
I have a question:
I want to perform node classification on my network composed of 2410 nodes. Since now, I split my nodes using the function AddTrainValTestMask function in order to validate the machine, but my idea is to perform a K-fold cross validation of the network, to gain better confidence about the goodness of the GCN.
How can I do this? How can I split my nodes in the different masks multiple times? Is there a specific function?
Thanks in advance.

**Comment by rusty1s** [comment]
https://github.com/pyg-team/pytorch_geometric/discussions/3662#discussioncomment-1786963
