### ISSUE TITLE
torch_geometric.loader.DataLoader Iteration Issue

### ISSUE THREAD

**Issue by annatn998** [pyg-team/pytorch_geometric#3679]
## 🐛 Bug

Hi, I'm trying to loop through a DataLoader object. However, I keep getting a torch.cat() issue when I loop through just this specific list. 

listOfData containts all torch_geometric.data.data.Data objects. 

The following code is how I created the DataLoader object. 

```python
np.random.seed(seed)
np.random.shuffle(listOfData)
train_loader = DataLoader(listOfData[:int((length*0.80))], batch_size=batch_size_train)
test_loader = DataLoader(listOfData[int((length*0.80)):], batch_size=batch_size_test)
```

### To Reproduce

Then when I try to loop through the DataLoader. 

```
for i in train_loader: 
     print(i) 
```

It prints out a few graphs and then comes up with this error: 

```
Batch(x=[462, 300], edge_index=[2, 223], y=[13], batch=[462], ptr=[14])
Batch(x=[501, 300], edge_index=[2, 247], y=[13], batch=[501], ptr=[14])
Batch(x=[764, 300], edge_index=[2, 370], y=[13], batch=[764], ptr=[14])
Batch(x=[490, 300], edge_index=[2, 236], y=[13], batch=[490], ptr=[14])
Batch(x=[353, 300], edge_index=[2, 169], y=[13], batch=[353], ptr=[14])
Batch(x=[452, 300], edge_index=[2, 215], y=[13], batch=[452], ptr=[14])
Batch(x=[375, 300], edge_index=[2, 161], y=[13], batch=[375], ptr=[14])
Batch(x=[622, 300], edge_index=[2, 336], y=[13], batch=[622], ptr=[14])
Batch(x=[355, 300], edge_index=[2, 177], y=[13], batch=[355], ptr=[14])
Batch(x=[506, 300], edge_index=[2, 132], y=[13], batch=[506], ptr=[14])
Batch(x=[486, 300], edge_index=[2, 176], y=[13], batch=[486], ptr=[14])
Batch(x=[534, 300], edge_index=[2, 266], y=[13], batch=[534], ptr=[14])
Batch(x=[540, 300], edge_index=[2, 252], y=[13], batch=[540], ptr=[14])
Batch(x=[560, 300], edge_index=[2, 247], y=[13], batch=[560], ptr=[14])
Batch(x=[600, 300], edge_index=[2, 269], y=[13], batch=[600], ptr=[14])
Batch(x=[486, 300], edge_index=[2, 220], y=[13], batch=[486], ptr=[14])
Batch(x=[228, 300], edge_index=[2, 88], y=[13], batch=[228], ptr=[14])
Batch(x=[473, 300], edge_index=[2, 191], y=[13], batch=[473], ptr=[14])
Batch(x=[322, 300], edge_index=[2, 142], y=[13], batch=[322], ptr=[14])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_4277/2753664710.py in <module>
----> 1 for i in layer2_test:
      2     print(i)

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

/opt/conda/lib/python3.7/site-packages/torch_geometric/loader/dataloader.py in __call__(self, batch)
     37 
     38     def __call__(self, batch):
---> 39         return self.collate(batch)
     40 
     41 

/opt/conda/lib/python3.7/site-packages/torch_geometric/loader/dataloader.py in collate(self, batch)
     18         if isinstance(elem, Data) or isinstance(elem, HeteroData):
     19             return Batch.from_data_list(batch, self.follow_batch,
---> 20                                         self.exclude_keys)
     21         elif isinstance(elem, torch.Tensor):
     22             return default_collate(batch)

/opt/conda/lib/python3.7/site-packages/torch_geometric/data/batch.py in from_data_list(cls, data_list, follow_batch, exclude_keys)
     67             add_batch=True,
     68             follow_batch=follow_batch,
---> 69             exclude_keys=exclude_keys,
     70         )
     71 

/opt/conda/lib/python3.7/site-packages/torch_geometric/data/collate.py in collate(cls, data_list, increment, add_batch, follow_batch, exclude_keys)
     75             # Collate attributes into a unified representation:
     76             value, slices, incs = _collate(attr, values, data_list, stores,
---> 77                                            increment)
     78 
     79             out_store[attr] = value

/opt/conda/lib/python3.7/site-packages/torch_geometric/data/collate.py in _collate(key, values, data_list, stores, increment)
    146             incs = None
    147 
--> 148         value = torch.cat(values, dim=cat_dim or 0)
    149         return value, slices, incs
    150 

RuntimeError: torch.cat(): Tensors must have same number of dimensions: got 1 and 2
```

I'm very stuck, if someone could please help me. 

### Environment

* PyTorch version: (`torch.__version__`): 1.9.1+cu111
* OS (*e.g.*, Linux): Jupyter Notebook 
* Python version (*e.g.*, `3.9`): 3.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by rusty1s** [comment]
It looks like one of your attributes in one of your `data` objects is only one-dimensional, while the attribute of other `data` objects are two-dimensional. Can you confirm?

**Comment by annatn998** [comment]
Hi! @rusty1s Thank you for responding! I'm unsure of how to check this as I have over 30,000 objects. I did try and print out the shape to see if there were any noticeable differences but they all seem to be consistent. Is there a way I can check this / identify the index of the object so I can remove it?

**Comment by annatn998** [comment]
>

**Comment by annatn998** [comment]
> Hi! @rusty1s Thank you for responding! I'm unsure of how to check this as I have over 30,000 objects. I did try and print out the shape to see if there were any noticeable differences but they all seem to be consistent. Is there a way I can check this / identify the index of the object so I can remove it?

**Comment by rusty1s** [comment]
How about:
```python
for i in range(0, len(dataset), 20):
    try:
        Batch.from_data_list(dataset[i:i+20])
    except Error:
        for data in dataset[i:i+20]:
            print(data)
```

**Comment by anna-pulsetech** [comment]
> How about:
> 
> ```python
> for i in range(0, len(dataset), 20):
>     try:
>         Batch.from_data_list(dataset[i:i+20])
>     except Error:
>         for data in dataset[i:i+20]:
>             print(data)
> ```

Yes this works great! Turns out there are a few graphs in the many that have no nodes which gave the graph a dimension of 1 instead of 2. I've removed those from the list and now incrementing works fine! Thanks so much!

**Comment by anna-pulsetech** [comment]
I've also tried this which works as well: 

I```
mport numpy as np 
for num,i in enumerate(layer2_emotions): 
    shape = i.edge_index.size(0)
    x_shape = len(i.x.size())
    if x_shape != 2: 
        print(i)
```

**Comment by annatn998** [comment]
> How about:
> 
> ```python
> for i in range(0, len(dataset), 20):
>     try:
>         Batch.from_data_list(dataset[i:i+20])
>     except Error:
>         for data in dataset[i:i+20]:
>             print(data)
> ```

Yes! This works great! It helps to determine that I had some graphs in the many that were created without nodes giving the graphs a dimension of 1. I've removed the graphs from the list entirely and the iteration works great now. Thanks :)


I also tried this which works as well: 
```

import numpy as np 
for n,i in enumerate(list): 
    shape = i.edge_index_size(0)
    x_shape = len(i.x.size())
    if x_shape != 2: 
        print(i)

```

**Comment by annatn998** [comment]
> How about:
> 
> ```python
> for i in range(0, len(dataset), 20):
>     try:
>         Batch.from_data_list(dataset[i:i+20])
>     except Error:
>         for data in dataset[i:i+20]:
>             print(data)
> ```

Yes! This works great! It helps to determine that I had some graphs in the many that were created without nodes giving the graphs a dimension of 1. I've removed the graphs from the list entirely and the iteration works great now. Thanks :)

I also tried this which works as well:


import numpy as np 
for n,i in enumerate(list): 
    shape = i.edge_index_size(0)
    x_shape = len(i.x.size())
    if x_shape != 2: 
        print(i)
