### ISSUE TITLE
A potential bug in FastRGCNConv

### ISSUE THREAD

**Issue by Jokeren** [pyg-team/pytorch_geometric#3689]
## 🐛 Bug

FastRGCNConv's output is different from RGCNConv when input is `None` (i.e., `x`=`None`).

### To Reproduce

```Python
    edge_index = torch.tensor([
        [0, 1, 1, 2, 2, 3, 0, 1, 1, 2, 2, 3],
        [0, 0, 1, 2, 1, 1, 0, 0, 1, 0, 1, 3],
    ])
    edge_type = torch.tensor([0, 1, 1, 0, 7, 6, 4, 3, 3, 2, 2, 3])

    torch.manual_seed(12345)
    rgcn_conv = RGCNConv(4, 32, 8, num_bases=4, aggr=mode)
    rgcn_conv_out = rgcn_conv(
        x=None, edge_index=edge_index, edge_type=edge_type)

    torch.manual_seed(12345)
    fast_rgcn_conv = FastRGCNConv(4, 32, 8, num_bases=4, aggr=mode)
    fast_rgcn_conv_out = fast_rgcn_conv(
        x=None, edge_index=edge_index, edge_type=edge_type)

    assert(torch.allclose(fast_rgcn_conv_out, rgcn_conv_out) is True)
```

### Expected behavior

According to PyG's documentation, the `message` method has the `index` argument identical to `edge_index_i`. 

The following execution assumes `x_l = torch.arange(self.in_channels_l, device=self.weight.device)`. 

In FastRGCNConv's message, we pass `index` (i.e., `edge_index_i`) as an argument and broadcast on `weight` to collect node features.

In RGCNConv's, we first select a specific type of `weight` in `forward`. Then, in `message` returns `x_j` which **are features on `edge_index_j` instead of `edge_index_i`.** 

To fix this problem, I suppose we can change the `index` argument of  FastRGCNConv's message to `edge_index_j`. 

I don't see such a case is covered in https://github.com/pyg-team/pytorch_geometric/blob/master/test/nn/conv/test_rgcn_conv.py. So perhaps an additional test case is needed. 

@rusty1s Please let me know if I could help.

### Environment

* PyG version (`5b4ccafa1409aa4711c0f11713ad53cc79806383`):
* PyTorch version: (`1.10`):
* OS (*e.g.*, Linux):
* Python version (*e.g.*, `3.8.5`):
* CUDA/cuDNN version: 11.4
* How you installed PyTorch and PyG (`source`):

**Comment by rusty1s** [comment]
I think you are absolutely correct. This is a bug. Let me know if you want to fix it on your own, otherwise I can try to fix it on my own.. An additional test is very much appreciated.

**Comment by Jokeren** [comment]
Hi @rusty1s , a quick PR is created here: https://github.com/pyg-team/pytorch_geometric/pull/3690.
