### ISSUE TITLE
If it is a regression problem rather than a classification problem？

### ISSUE THREAD

**Issue by xyb151158** [pyg-team/pytorch_geometric#3694]
If it is a regression problem, each graph corresponds to a predicted value. Is there a corresponding convolution layer, or what is the solution?
Thank you！

**Comment by rusty1s** [comment]
The GNN layer stay the same (similar to how an MLP or CNN feature extractor stays the same), but the head of the model changes, that is, you output a single scalar value and use a `MSELoss` training objective.

**Comment by xyb151158** [comment]
> The GNN layers stay the same (similar to how an MLP or CNN feature extractor stays the same), but the head of the model changes, that is, you output a single scalar value and use a `MSELoss` training objective.

Thank you very much. But I don't quite understand what layer can be added to make the output become a scalar value. Can you be more detailed? For example, two layers of GCN are added in front. What layer should be added in the back? thank you!

**Comment by rusty1s** [comment]
You can either set the last GNN layer to have a `out_channels` dimension of `1`, e.g., `GCNConv(hidden_channels, 1)`, or use a final linear layer/MLP that maps to a scalar, e.g., `Linear(hidden_channels, 1)`

**Comment by xyb151158** [comment]
> You can either set the last GNN layer to have a `out_channels` dimension of `1`, e.g., `GCNConv(hidden_channels, 1)`, or use a final linear layer/MLP that maps to a scalar, e.g., `Linear(hidden_channels, 1)`

I have roughly understood it. Thank you very much. In addition, I also want to know whether the input data should be standardized or normalized?

**Comment by xyb151158** [comment]
> That's super hard to tell. I suggest to simply check for validation performance with and without normalization to see which one works better.

OK, thank you very much for your reply!
