### ISSUE TITLE
Bug of UPFD dataset

### ISSUE THREAD

**Issue by CurryTang** [pyg-team/pytorch_geometric#3700]
## 🐛 Bug

There's a bug when I try to use pyg's dataloader on UPFD dataset. When I try to extract batches from test dataset of UPFD, I find that some edge index will be extracted incorrectly(shape of these edge indexes become [4,x], the correct ones should be [2,x])
![image](https://user-images.githubusercontent.com/15672123/146110915-4016a585-b2a9-4ff4-a86b-cb4527e20db6.png)
![image](https://user-images.githubusercontent.com/15672123/146110836-ce4386da-5c43-4608-9174-06df6e76c624.png)

### To Reproduce

``` python3
import argparse
import os.path as osp

import torch
from torch.nn import Linear
import torch.nn.functional as F
from upfd import UPFD
from torch_geometric.loader import DataLoader
from torch_geometric.transforms import ToUndirected
from torch_geometric.nn import GCNConv, SAGEConv, GATConv, global_max_pool
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'UPFD')
train_dataset = UPFD(path, args.dataset, args.feature, 'train', ToUndirected())
val_dataset = UPFD(path, args.dataset, args.feature, 'val', ToUndirected())
test_dataset = UPFD(path, args.dataset, args.feature, 'test', ToUndirected())

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=128, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False)
```

### Expected behavior
This bug can be produced by running the examples/upfd.py file.

![image](https://user-images.githubusercontent.com/15672123/146110836-ce4386da-5c43-4608-9174-06df6e76c624.png)
All edge index tensors should have shape [2,x] 

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.1
* PyTorch version: (`torch.__version__`): 1.8.2
* OS (*e.g.*, Linux): Linux
* Python version (*e.g.*, `3.9`): 3.8
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): 

### Additional context

![image](https://user-images.githubusercontent.com/15672123/146111172-32d2b7ae-fa63-44e6-bf02-22717e27301f.png)
`datalist` object in upfd.py has correct shape(all [2,x])

**Comment by rusty1s** [comment]
Thanks for reporting. I can reproduce the issue with PyG 2.0.1, but it is already resolved in PyG 2.0.2. Please consider upgrading your version :)
