### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device in Google Colab

### ISSUE THREAD

**Issue by lmy86263** [pyg-team/pytorch_geometric#3709]
### To Reproduce

Example `link_pred.py` runs with errors in Google Colab.

> Traceback (most recent call last):
>   File "tutorials/link_pred.py", line 82, in <module>
>     train_data, val_data, test_data = dataset[0]
>   File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/dataset.py", line 199, in __getitem__
>     data = data if self.transform is None else self.transform(data)
>   File "/usr/local/lib/python3.7/dist-packages/torch_geometric/transforms/compose.py", line 21, in __call__
>     data = transform(data)
>   File "/content/drive/MyDrive/Colab Notebooks/QueryExpand/Graph/gnn/tutorials/improved_random_link_split.py", line 212, in __call__
>     out=val_store,
>   File "/content/drive/MyDrive/Colab Notebooks/QueryExpand/Graph/gnn/tutorials/improved_random_link_split.py", line 286, in _create_label
>     edge_index = torch.cat([edge_index, neg_edge_index], dim=-1)
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper___cat)

But it can run perfectly in local machine in CPU.

### Expected behavior

It can run in Google Colab with GPU acceleration.

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.10
* OS (*e.g.*, Linux): Google Colab Ubuntu 18.04
* Python version (*e.g.*, `3.9`): 3.7
* CUDA/cuDNN version: cu111
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Yes, there was an error in `negative_sampling` on GPU, which is already fixed in master. Installing via
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
should resolve this issue. Please re-open if it does not fix it on your end.

**Comment by lmy86263** [comment]
Thx for this quick reply, it resolves the issue.
