### ISSUE TITLE
ImportError: cannot import name 'HANConv' from 'torch_geometric.nn'

### ISSUE THREAD

**Issue by Gori-LV** [pyg-team/pytorch_geometric#3716]
## 🐛 Bug

Hi, I am trying to run the [example code for HAN](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/han_imdb.py), I tried other imports, including another heterogeneous conv, all worked fine, but failed when import HANConv.

```python
>>> import torch_geometric
>>> import torch_geometric.nn
>>> from torch_geometric.nn import HGTConv
>>> from torch_geometric.nn import HANConv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'HANConv' from 'torch_geometric.nn' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch_geometric/nn/__init__.py)
```

### Environment
* PyG version: 2.0.2
* PyTorch version: 1.8.0
* OS: MacOS
* Python version: 3.8
* How you installed PyTorch and PyG: pip3
* Any other relevant information:
&nbsp; torch-cluster                     1.5.9
&nbsp; torch-scatter                     2.0.9
&nbsp; torch-sparse                      0.6.12
&nbsp; torch-spline-conv                 1.2.1

Thanks a lot for your help :)

**Comment by wsad1** [comment]
HanConv isn't present in the latest release 2.0.2. Installing the latest code  via `pip install git+https://github.com/pyg-team/pytorch_geometric.git` should resolve this.

**Comment by Gori-LV** [comment]
Solved! thanks ;D
