### ISSUE TITLE
mlp.py missing in installation 

### ISSUE THREAD

**Issue by alexliniger** [pyg-team/pytorch_geometric#3718]
## 🐛 Bug

Installing PyG with both conda and pip resulted in the mlp.py file missing in "site-packages/torch_geometric/nn/models"
Adding the file mlp.py from the github to the folder and adding it to the __init__.py solved the issue

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.10.0
* OS (*e.g.*, Linux): Ubuntu 20.04
* Python version (*e.g.*, `3.9`): 3.9
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
The `MLP` model just got recently added, and it is not available in `2.0.2`. I will probably craft a new minor release in the next week.
