### ISSUE TITLE
It takes a long time for installing torch-scatter/torch-sparse in Google Colab

### ISSUE THREAD

**Issue by lmy86263** [pyg-team/pytorch_geometric#3750]
## 😵 Installation

I find that it will take a long time for installing torch-scatter/torch-sparse in Google Colab about 20/30 minutes. So, I need to reinstall them for another 30 minutes when I start a new task.

But I don't know why. The possible reason for that I guess is that it will take a long time for compiling these packages. Am I right?

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.10
* OS (*e.g.*, Linux): Google Colab Ubuntu 18.04
* Python version (*e.g.*, `3.9`): 3.7
* CUDA/cuDNN version:  cu111
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
How do you try to install those packages? It should just take a few seconds when installing from wheels, see [here](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing) on how to do so.

**Comment by lmy86263** [comment]
Thx, I find why it is.
I just use this:

```
CUDA = torch.version.cuda

pip install torch-cluster -f https://data.pyg.org/whl/torch-1.9.0+${CUDA}.html
pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.9.0+${CUDA}.html
```
I don' t realize the CUDA represent 11.1 not cu111. It needs a manual tranformation.

**Comment by rusty1s** [comment]
Super :)
