### ISSUE TITLE
neg_edge_label_index should be passed in autoencoder example

### ISSUE THREAD

**Issue by zhenlan0426** [pyg-team/pytorch_geometric#3761]
I think we should pass in neg_edge_label_index here instead of leaving it to negative_sampling. The reason is that we are doing train/test split. This means the complement of pos_edge_label_index are not necessarily negative edge. They could be positive edge but left out for test split. 
https://github.com/pyg-team/pytorch_geometric/blob/e6aa4c94f3a6b89302e71664a7be03dc7e955e3c/examples/autoencoder.py#L90

**Comment by zhenlan0426** [comment]
Just to be more explicit, I think negative_sampling should be done within train_data.neg_edge_label_index. i.e. should not include any edge from test.

**Comment by rusty1s** [comment]
I think this is correct. I tried to answer it here: https://github.com/pyg-team/pytorch_geometric/issues/2475

**Comment by zhenlan0426** [comment]
Thank you for the clarification. I will close it. "it is to be expected that such a noise in the learning signal is averaged out during optimization." I don't think it will be averaged out though as test edge could be used as negative sample but never as positive sample (since we explicitly pass in train_data.pos_edge_label_index)
