### ISSUE TITLE
indexSelectLargeIndex error in edge_index

### ISSUE THREAD

**Issue by sajastu** [pyg-team/pytorch_geometric#3762]
## 🐛 Bug

`indexSelectLargeIndex` error is raised even when indices are correctly formatted. 

### To Reproduce

I'm using the GCN example which is put on the Readme of the repo. My `x` is a tensor of shape `[1491, 768]`, edge_index is in shape of `[2, num_edges]` (num_edge = 2316), and edge_weight is a tensor of shape `[2316]`. I pass the `edge_weight`  tensor as I'm constructing the `edge_index` from the adjacency matrix. The graph is a directed one i.e., `(i, j)` being connected doesn't guarantee `(j, i)` being connected.  Here is the full script:

```
class GraphEncoder():
...

self.conv1 = GCNConv(768, 1024, cached=True )
self.conv2 = GCNConv(1024, 768, cached=True )

...

edge_index = (adj_t > 0).nonzero().t()
row, col = edge_index
edge_weight = adj_t[row, col]

# ensure tensors are in the proper type...
edge_weight = edge_weight.type(torch.FloatTensor)
clss_graph = clss_graph.type(torch.LongTensor)

# ensure tensors are in cuda
edge_index = edge_index.cuda()
edge_weight = edge_weight.cuda()

x = x.squeeze(0) # [node_size, feat]

x = self.conv1(x, edge_index).relu()
x = self.conv2(x, edge_index)
```

I checked to make sure if `edge_index.max()` falls within the `x.size(0)` (i.e., it should be less than `x.size(0)`) and it turns out to be holding this condition: 

```
$ edge_index.max()
tensor(1459, device='cuda:0')

$ x.size(0)
1461

```

I'm trying to figure out what the possible problem is here, but have been unfortunate to find the reason. But I'm getting this error: 

> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [65,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [67,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [68,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [69,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [70,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [71,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [72,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [73,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [74,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [75,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [76,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [77,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [78,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [79,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [80,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [82,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [83,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [84,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [85,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [86,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [88,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [89,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [90,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [91,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [92,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /pytorch/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [191,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> Traceback (most recent call last):
>   File "train.py", line 183, in <module>
>     train_ext(args, device_id, intro_cls=args.intro_cls)
>   File "/home/sajad/packages/sum/GraphTransSum/src/train_extractive.py", line 331, in train_ext
>     train_single_ext(args, device_id)
>   File "/home/sajad/packages/sum/GraphTransSum/src/train_extractive.py", line 387, in train_single_ext
>     trainer.train(train_iter_fct, args.train_steps, valid_iter_fct=val_iter_fct, wandb=run_wandb)
>   File "/home/sajad/packages/sum/GraphTransSum/src/models/trainer_ext.py", line 189, in train
>     self._gradient_accumulation(
>   File "/home/sajad/packages/sum/GraphTransSum/src/models/trainer_ext.py", line 634, in _gradient_accumulation
>     sent_scores, mask = self.model(src, clss, mask, mask_cls, segs, id, graph)
>   File "/home/sajad/anaconda3/envs/graphsum/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/sajad/packages/sum/GraphTransSum/src/models/graphSum_builder.py", line 180, in forward
>     sent_scores = self.graph_encoder(top_vec, clss, mask_cls, mask_src, src, id, graph=graph)
>   File "/home/sajad/anaconda3/envs/graphsum/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/sajad/packages/sum/GraphTransSum/src/models/encoder.py", line 360, in forward
>     x = self.conv1(x, edge_index).relu()
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

If that helps following is the content of my edge_index (for the sake of simplicity, I'm showing 400 elements):

```
tensor([[   1,    2,    3,    4,    5,    6,    6,    6,    6,    6,    6,    6,
            6,    6,    6,    6,    6,    6,    7,    8,    9,   10,   11,   11,
           11,   11,   11,   11,   11,   11,   11,   11,   12,   13,   13,   13,
           13,   13,   13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
           13,   13,   14,   14,   14,   14,   14,   14,   14,   14,   14,   15,
           16,   17,   18,   19,   19,   19,   19,   19,   19,   19,   20,   21,
           22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
           34,   35,   36,   38,   39,   39,   39,   39,   39,   39,   39,   39,
           39,   40,   40,   41,   41,   41,   41,   41,   41,   42,   43,   44,
           44,   44,   44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
           44,   44,   44,   44,   45,   46,   47,   48,   49,   50,   51,   52,
           52,   52,   52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
           52,   52,   53,   54,   54,   54,   54,   54,   54,   54,   54,   54,
           54,   54,   55,   56,   57,   58,   58,   58,   58,   58,   58,   58,
           58,   59,   59,   60,   61,   62,   62,   62,   62,   62,   62,   62,
           62,   62,   62,   62,   62,   62,   62,   62,   62,   62,   63,   64,
           65,   65,   65,   65,   65,   65,   65,   65,  ..., 1275, 1275, 1276,
         1276, 1276, 1276, 1277, 1278, 1279, 1280, 1281, 1281, 1281, 1281, 1282,
         1283, 1284, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293,
         1294, 1295, 1296, 1297, 1298, 1299, 1299, 1300, 1301, 1302, 1303, 1304,
         1305, 1306, 1307, 1308, 1310, 1311, 1312, 1312, 1312, 1313, 1314, 1315,
         1316, 1317, 1317, 1317, 1317, 1317, 1318, 1319, 1321, 1322, 1322, 1323,
         1324, 1325, 1326, 1327, 1328, 1329, 1330, 1332, 1333, 1334, 1335, 1336,
         1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1344, 1345, 1346, 1347,
         1348, 1349, 1350, 1351, 1352, 1353, 1355, 1356, 1357, 1358, 1359, 1360,
         1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372,
         1373, 1374, 1375, 1376, 1376, 1376, 1377, 1378, 1379, 1380, 1381, 1382,
         1383, 1384, 1385, 1386, 1387, 1388, 1389, 1389, 1389, 1390, 1392, 1393,
         1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1404, 1405, 1406,
         1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418,
         1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430,
         1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442,
         1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454,
         1455, 1456, 1457, 1458, 1459],
        [   0,    0,    0,    0,    0,    0,   73,  272,  339,  370,  406,  546,
          594,  611,  675,  717,  762,  769,    0,    0,    0,    0,    0,   77,
          302,  412,  421,  442,  450,  465,  554, 1316,    0,    0,   65,  107,
          134,  167,  173,  184,  216,  234,  242,  258,  274,  356,  419,  447,
          524,  558,    0,   58,  185,  235,  416,  453,  798, 1051, 1417,    0,
            0,    0,    0,    0,   41,  128,  199,  210,  240,  249,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,   37,   37,   93,  269,  298,  326,  363,  607,  644,
          736,   37,  637,   37,  128,  199,  210,  240,  249,   37,   37,   37,
          311,  437,  443,  614,  792,  815,  861,  909,  914, 1189, 1268, 1317,
         1376, 1389, 1412, 1437,   37,   37,   37,   37,   37,   37,   37,   37,
          221,  277,  512,  639,  819,  866,  887,  901,  996, 1276, 1281, 1312,
         1344, 1373,   37,   37,  109,  332,  372,  598,  617,  720, 1262, 1284,
         1299, 1411,   37,   37,   37,   37,  185,  235,  416,  453,  798, 1051,
         1417,   37,  414,   37,   37,   37,  311,  437,  443,  614,  792,  815,
          861,  909,  914, 1189, 1268, 1317, 1376, 1389, 1412, 1437,   37,   37,
           37,  107,  134,  167,  173,  184,  216,  234,  ..., 1270, 1311, 1270,
         1312, 1344, 1373, 1270, 1270, 1270, 1270, 1270, 1312, 1344, 1373, 1270,
         1270, 1270, 1411, 1270, 1270, 1270, 1270, 1270, 1270, 1270, 1270, 1270,
         1270, 1270, 1270, 1270, 1270, 1270, 1411, 1270, 1270, 1270, 1270, 1270,
         1270, 1270, 1270, 1270, 1309, 1309, 1309, 1344, 1373, 1309, 1309, 1309,
         1309, 1309, 1376, 1389, 1412, 1437, 1309, 1309, 1320, 1320, 1348, 1320,
         1320, 1320, 1320, 1320, 1320, 1320, 1320, 1331, 1331, 1331, 1331, 1331,
         1331, 1331, 1331, 1331, 1331, 1331, 1331, 1331, 1373, 1331, 1331, 1331,
         1331, 1331, 1331, 1331, 1331, 1331, 1354, 1354, 1354, 1354, 1354, 1354,
         1354, 1354, 1354, 1354, 1354, 1354, 1354, 1354, 1354, 1354, 1354, 1354,
         1354, 1354, 1354, 1354, 1412, 1437, 1354, 1354, 1354, 1354, 1354, 1354,
         1354, 1354, 1354, 1354, 1354, 1354, 1354, 1412, 1437, 1354, 1391, 1391,
         1391, 1391, 1391, 1391, 1391, 1391, 1391, 1391, 1391, 1403, 1403, 1403,
         1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403,
         1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403,
         1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403,
         1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403, 1403,
         1403, 1403, 1403, 1403, 1403]], device='cuda:0')
```

### Environment

* PyG version (`torch_geometric.__version__`):  2.0.3
* PyTorch version: (`torch.__version__`): 1.9.0
* OS (*e.g.*, Linux): Ubuntu
* Python version (*e.g.*, `3.9`): 3.8
* CUDA/cuDNN version: 11
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): installed PyG from installation guideline, so yes I have installed all packages denoted in there.

**Comment by rusty1s** [comment]
This is probably induced by the `cached=True` option of `GCNConv`. This option should only be set to true if you are operating on a single graph that does not change:
```python
self.conv1 = GCNConv(768, 1024)
self.conv2 = GCNConv(1024, 768)
```
Let me know if this fixes your issues :)

**Comment by sajastu** [comment]
@rusty1s Thank you so much! It works perfectly fine now! :)
