### ISSUE TITLE
Errors in the section "Using the Heterogenous Convolution Wrapper"

### ISSUE THREAD

**Issue by anonymousrepoxxx** [pyg-team/pytorch_geometric#3771]
Errors in the section "Using the Heterogenous Convolution Wrapper" of the part "Heterogenous Graph Learning"
(1) There are no commas in the item initialization of conv.
(2) In practice, the parameter (-1,-1) in SAGEConv((-1, -1) may cause a runtime error when performing SAGEConv.
The runtime error is as follows:

> return torch._C._nn.linear(input, weight, bias)
> RuntimeError: tensors must be 2-D

This crash is directly caused by the weight initialization in torch_geometric.nn.dense.linear.Linear:

>         if in_channels > 0:
>             self.weight = Parameter(torch.Tensor(out_channels, in_channels))
>         else:
>             self.weight = torch.nn.parameter.UninitializedParameter()
>             self._hook = self.register_forward_pre_hook(
>                 self.initialize_parameters)

When in_channles==-1, the weight will be [].

I think it's a bug that needs to be fixed.

The versions of my PyTorch and PyG are 1.8.1 and 2.0.1, with Python 3.9 and Ubuntu 16 as  the backend environment.

> from torch_geometric.nn import HeteroConv, GCNConv, SAGEConv, GATConv, Linear
> 
> class HeteroGNN(torch.nn.Module):
>     def __init__(self, hidden_channels, out_channels, num_layers):
>         super().__init__()
> 
>         self.convs = torch.nn.ModuleList()
>         for _ in range(num_layers):
>             conv = HeteroConv({
>                 ('paper', 'cites', 'paper'): GCNConv(-1, hidden_channels)    #there's no comma
>                 ('author', 'writes', 'paper'): GATConv((-1, -1), hidden_channels) #there's no comma
>                 ('author', 'affiliated_with', 'institution'): SAGEConv((-1, -1), hidden_channels) #there's no comma
>             }, aggr='sum') 
>             self.convs.append(conv)
> 
>         self.lin = Linear(hidden_channels, out_channels)
> 
>     def forward(self, x_dict, edge_index_dict):
>         for conv in self.convs:
>             x_dict = conv(x_dict, edge_index_dict)
>             x_dict = {key: x.relu() for key, x in x_dict.items()}
>         return self.lin(x_dict['author'])
> 
> model = HeteroGNN(hidden_channels=64, out_channels=dataset.num_classes,
>                   num_layers=2)

**Comment by rusty1s** [comment]
Thanks for reporting. I fixed the typo in the documentation.

Regarding your other issue: I am not able to reproduce this issue and I don't see a mistake in the weight initialization. In case `in_channels == -1`, `self.weight` will be given as an `UninitializedParameter()` which is exactly what we want it to be: Its concrete weights should be inferred from the first set of inputs.
