### ISSUE TITLE
Problem in Data.is_directed()

### ISSUE THREAD

**Issue by JeffreyHuSC** [pyg-team/pytorch_geometric#3785]
## 🐛 Bug

import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[4, 1, 1, 2],
                           [1, 4, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)
#When I changed the label ID 4, to 5, the code runs normally.

data = Data(x=x, edge_index=edge_index)

print(data.is_directed())

Causes error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/var/folders/85/03cpw2k96qd8vx7hkznsjmkm0000gs/T/ipykernel_98002/4216900986.py in <module>
      4 print(data.has_isolated_nodes())
      5 print(data.has_self_loops())
----> 6 print(data.is_directed())

~/.local/lib/python3.9/site-packages/torch_geometric/data/data.py in is_directed(self)
    185     def is_directed(self) -> bool:
    186         r"""Returns :obj:`True` if graph edges are directed."""
--> 187         return not self.is_undirected()
    188 
    189     def clone(self):

~/.local/lib/python3.9/site-packages/torch_geometric/data/data.py in is_undirected(self)
    181     def is_undirected(self) -> bool:
    182         r"""Returns :obj:`True` if graph edges are undirected."""
--> 183         return all([store.is_undirected() for store in self.edge_stores])
    184 
    185     def is_directed(self) -> bool:

~/.local/lib/python3.9/site-packages/torch_geometric/data/data.py in <listcomp>(.0)
    181     def is_undirected(self) -> bool:
    182         r"""Returns :obj:`True` if graph edges are undirected."""
--> 183         return all([store.is_undirected() for store in self.edge_stores])
    184 
    185     def is_directed(self) -> bool:

~/.local/lib/python3.9/site-packages/torch_geometric/data/storage.py in is_undirected(self)
    421         edge_index = self.edge_index
    422         edge_attr = self.edge_attr if 'edge_attr' in self else None
--> 423         return is_undirected(edge_index, edge_attr, num_nodes=self.size(0))
    424 
    425     def is_directed(self) -> bool:

~/.local/lib/python3.9/site-packages/torch_geometric/utils/undirected.py in is_undirected(edge_index, edge_attr, num_nodes)
     42     print(f"******",edge_index1)
     43     print(f"******",edge_index2)
---> 44     return (bool(torch.all(edge_index1[0] == edge_index2[1]))
     45             and bool(torch.all(edge_index1[1] == edge_index2[0])) and all([
     46                 torch.all(e == e_T) for e, e_T in zip(edge_attr1, edge_attr2)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

Possible Reason: The problem could possibly be caused by the coalesce function.

    edge_index1, edge_attr1 = coalesce(edge_index, edge_attr,
                                       num_nodes=num_nodes, sort_by_row=True)
    edge_index2, edge_attr2 = coalesce(edge_index1, edge_attr1, num_nodes=num_nodes, sort_by_row=False)
 
### Environment

* PyG version (`torch_geometric.__version__`):
* PyTorch version: (`torch.__version__`):
* OS (*e.g.*, Linux):
* Python version (*e.g.*, `3.9`):
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
I think the issue stems from the fact that your data is wrongly encoded, e.g., `edge_index.max()` needs to be lower than `x.size(0)` (the number of nodes).

**Comment by JeffreyHuSC** [comment]
> I think the issue stems from the fact that your data is wrongly encoded, e.g., `edge_index.max()` needs to be lower than `x.size(0)` (the number of nodes).

this is NOT true. when I change the node id from 4 to 5, it works correctly.

**Comment by rusty1s** [comment]
Yes, the error does not happen for all node ids, but it still stems from the fact that `edge_index.max() >= x.size(0)`. The `coalesce` call will remove some entries in `edge_index` since it mistakenly believes that there exist duplicated edges due to the conversion to one-dimensional indices via `num_nodes *  edge_index[0] + edge_index[1]`. I nonetheless pushed a fix to remove this error, see https://github.com/pyg-team/pytorch_geometric/pull/3789.
