### ISSUE TITLE
Accessing layers and their weights/parameters inside Sequential

### ISSUE THREAD

**Issue by SimonCrouzet** [pyg-team/pytorch_geometric#3788]
Hello,

First, thanks a lot for your work on this framework, it's a very powerful tool!

I had a concern about your customized nn.Sequential. It does not allowed to access to the layers inside it:
```
m = Sequential(
  (0): BatchNorm(200)
  (1): GCNConv(200, 10)
  (2): ELU(alpha=1.0, inplace=True)
  (3): <function global_mean_pool at 0x0000026F7CA36AF0>
  (4): BatchNorm(10)
  (5): Dropout(p=0.2, inplace=False)
  (6): Linear(in_features=10, out_features=2, bias=True)
)
m[1]     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Sequential_dbe74c' object is not subscriptable
```
It would be useful to be able to access them, for example to check the weights and parameters of the layers.

For example, the initial nn.Sequential allows it, and propose to name our layer like that:
```
# Using Sequential with OrderedDict. This is functionally the same as the above code
model = nn.Sequential(OrderedDict([
          ('conv1', nn.Conv2d(1,20,5)),
          ('relu1', nn.ReLU()),
          ('conv2', nn.Conv2d(20,64,5)),
          ('relu2', nn.ReLU())
        ]))
```
(from https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html)

Would it be possible to add a similar feature, to get a direct access to our layers?

Thanks for your attention,

**Comment by rusty1s** [comment]
This is a great idea. I pushed a fix in https://github.com/pyg-team/pytorch_geometric/pull/3790.

**Comment by SimonCrouzet** [comment]
Great, thanks a lot!

**Comment by rusty1s** [comment]
Added support for `OrderedDict` as well, see https://github.com/pyg-team/pytorch_geometric/pull/4075.

**Comment by LostOxygen** [comment]
Just being curious: how would i exactly access the weights of, let's say, a GCNConv layer? In the original nn.Sequential manner i could simply iterate over all layers of a model and access the weights with `layer.weight`. But this does not seem to work here, or did i get something wrong with the functionality?

**Comment by rusty1s** [comment]
Can you show an example of what you mean? I assume
```python
for i in range(len(sequential_model)):
    layer = sequential_model[i]
```
works as expected.

**Comment by LostOxygen** [comment]
Yes, but if you try to access the weights with:
```python
for i in range(len(sequential_model)):
    layer_weight = sequential_model[i].weight
```
you'll get an `AttributeError` for `'GCNConv' object has no attribute 'weight'`. Is there any other option to access the weights of the layers?

**Comment by rusty1s** [comment]
Every layer is different, some layers may utilize multiple linear layers, some may use MLPs, etc. It is best to look up the code on a GNN layer in order to see how to access its parameters.
