### ISSUE TITLE
Request a cheat sheet for datasets

### ISSUE THREAD

**Issue by Jokeren** [pyg-team/pytorch_geometric#3791]
## 🚀 Feature

A clear table (or list) that shows the attributes of each dataset. 

### Motivation

The [GNN cheat sheet](https://pytorch-geometric.readthedocs.io/en/latest/notes/cheatsheet.html) provides a good example to fast compare properties among different GNNs.

Right now, [torch_geometric.datasets](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html) includes a brief description for each dataset but without a detailed comparison between them. It is not clear to users how large a dataset is and what properties a dataset has. 

### Pitch

I come up with attributes as follows, please feel free to add more:

- number of nodes
- number of edges
- number of graphs
- number of node/entity types (>1 if heterogenous)
- number of edge/relation types (>1 if heterogenous)
- size of the dataset

### Additional context

@rusty1s

**Comment by rusty1s** [comment]
I added the basic concept of a dataset cheatsheet into master. See [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/data_cheatsheet.html) for the cheatsheet. The next step is to fill this table with content. Please consider helping us with this task :)
