### ISSUE TITLE
Error: KeyError: 'graph_encoder.layers.0.encoder.lin_src.weight' 

### ISSUE THREAD

**Issue by dxlong2000** [pyg-team/pytorch_geometric#3793]
Dear authors, 
Thank you for your great work on Torch geometric. When I tried to run the below command, I got this error. Hopefully I would received some advices from you.

## 🐛 Bug

I got the bug ```KeyError: 'graph_encoder.layers.0.encoder.lin_src.weight'``` when trying to load ```checkpoint_utils.load_model_ensemble``` from ```fairseq```.
### To Reproduce

```
from fairseq import options, tasks, checkpoint_utils, progress_bar, utils
parser = options.get_generation_parser()
args = options.parse_args_and_arch(parser)
task = tasks.setup_task(args)
models, _ = checkpoint_utils.load_model_ensemble(["models/generation_models/tplgen_template_generation/model.pt"], task=task)
```
where the models folder it is from ```https://drive.google.com/drive/folders/1EpfamTiOosKvy_s9Bm_tW1NdtAzKpkY7``` and I alreadly used the model so I think it works fine.

### Expected behavior
```
models, _ = checkpoint_utils.load_model_ensemble([args.path], task=task)
  File "/content/gdrive/.shortcut-targets-by-id/1euwk1Zyt7Sa5sxm4_AVBZ9m4ECrtcIo7/A*/open-ended_question_ontology/fairseq/fairseq/checkpoint_utils.py", line 368, in load_model_ensemble
    state,
  File "/content/gdrive/.shortcut-targets-by-id/1euwk1Zyt7Sa5sxm4_AVBZ9m4ECrtcIo7/A*/open-ended_question_ontology/fairseq/fairseq/checkpoint_utils.py", line 471, in load_model_ensemble_and_task
    state["model"], strict=strict, model_cfg=cfg.model
  File "/content/gdrive/.shortcut-targets-by-id/1euwk1Zyt7Sa5sxm4_AVBZ9m4ECrtcIo7/A*/open-ended_question_ontology/fairseq/fairseq/models/fairseq_model.py", line 128, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1468, in load_state_dict
    load(self)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1466, in load
    load(child, prefix + name + '.')
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1466, in load
    load(child, prefix + name + '.')
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1466, in load
    load(child, prefix + name + '.')
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1463, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1372, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/nn/dense/linear.py", line 131, in _lazy_load_hook
    weight = state_dict[prefix + 'weight']
KeyError: 'graph_encoder.layers.0.encoder.lin_src.weight'
```

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.3
* PyTorch version: (`torch.__version__`): 1.10.0
* OS (*e.g.*, Linux): Colab, Yes
* Python version (*e.g.*, `3.9`): 3.7.12
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): I install by pip from the instruction here: https://pytorch.org/
* Any other relevant information (*e.g.*, version of `torch-scatter`): I install torch_geometric:
```
!pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
!pip install torch-geometric 
```

**Comment by rusty1s** [comment]
Looks to be a versioning conflict between the model implementation from PyG 2.0.3 and earlier. Which version of PyG was used to generate `model.pt` in the first place? Can you share some information about the implementation of `graph_encoder`?

**Comment by dxlong2000** [comment]
> Looks to be a versioning conflict between the model implementation from PyG 2.0.3 and earlier. Which version of PyG was used to generate `model.pt` in the first place? Can you share some information about the implementation of `graph_encoder`?

Hi, thanks for your reply.

The version that is used to generate ```model.pt``` was ```PyTorch-Geometric 1.7.2``` and ```fairseq``` is at commit ```0db28cd```. I alreadly downloaded it and it still raises error.

May I ask how could I download ```PyTorch-Geometric 1.7.2```??? It seems that it doesn't have installation for previous version.

Couple of other bugs I want to report: 
- I tried multiple times but I couldn't install ```!pip install torch-scatter -f https://data.pyg.org/whl/torch-1.7.0+cu102.html```

Please help me to solve those issues.

Thanks!
BR,

**Comment by rusty1s** [comment]
You can install PyG 1.7.2 via `pip install torch-geometric==1.7.2`. Similarly, for the external packages, it might be necessary to specify a version number since PyTorch 1.7.0 is no longer maintained. You can find the latest version numbers by looking at https://data.pyg.org/whl/torch-1.7.0+cu102.html, e.g.:
```
pip install torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.0+cu102.html
```

**Comment by dxlong2000** [comment]
> You can install PyG 1.7.2 via `pip install torch-geometric==1.7.2`. Similarly, for the external packages, it might be necessary to specify a version number since PyTorch 1.7.0 is no longer maintained. You can find the latest version numbers by looking at https://data.pyg.org/whl/torch-1.7.0+cu102.html, e.g.:
> 
> ```
> pip install torch-scatter==2.0.7 -f https://data.pyg.org/whl/torch-1.7.0+cu102.html
> ```
Thank you very much, it works now!!!

It can be installed by ```pip install torch-geometric==1.7.2```, I suggest that it should be documented. Since previously I searched and I got this link: https://github.com/pyg-team/pytorch_geometric/issues/720 so I thought no way for me to try to specify the version. 
The way you specify the version for other packages also very nice, I understand the index for each link now.
Thanks!
