### ISSUE TITLE
TOSCA dataset index based 1

### ISSUE THREAD

**Issue by JRowbottomGit** [pyg-team/pytorch_geometric#3805]
## 🐛 Bug

TOSCA high-resolution (http://tosca.cs.technion.ac.il/book/resources_data.html) is a mesh dataset of " 1-based list of triangular faces", originally processed in matlab. Needs to be rebased to 0.

### To Reproduce

from torch_geometric.datasets import TOSCA
dataset = TOSCA("../data/tosca")

drop a line break in here
https://github.com/pyg-team/pytorch_geometric/blob/df182adb85988fb99bf89ea1776e0e16898497d2/torch_geometric/datasets/tosca.py#L90

try:
(face).min()
(face).max()
(face - 1).min()
(face - 1).max()

### Expected behavior

Needs to be 0-based

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.3
* PyTorch version: (`torch.__version__`): 1.10.1
* OS (*e.g.*, Linux): WSL
* Python version (*e.g.*, `3.9`): 3.8
* CUDA/cuDNN version: cpu
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/8c282a05ff7dadef5f954279443710077dec91c2.
