### ISSUE TITLE
Transform of Data loader

### ISSUE THREAD

**Issue by yunhak0** [pyg-team/pytorch_geometric#3806]
## 🐛 Bug

I found 3 bugs related to `torch_geometric.datasets` and `torch_geometric.transforms`.

1. Discrepancy in attributes of `Data` object.

When I apply a transform (e.g. `T.ToSparseTensor()`, `T.NormalizeFeatures()`, `dataset.data` doesn't apply the transform but the transform is only applied in `dataset[0]`
![image](https://user-images.githubusercontent.com/40286691/148160869-aa8557fc-864b-49fe-a0e2-69264cc06efc.png)

2. Change the value of `dataset.data.x`, after compiling dataset[0] when we use `T.NormalizeFeatures()`.

Although `dataset.data` is not applied the transform, after compiling dataset[0], the value is changed same as dataset[0].
However, `dataset.data` doesn't have `adj_t` after compiling dataset[0].adj_t when the transform is `T.ToSparseTensor()`.
![image](https://user-images.githubusercontent.com/40286691/148160116-fdce74b3-b4ab-4470-ae9a-a3583bd90968.png)

3. WikiCS `T.NormalizeFeatures()` seems not work correctly.

The features of WikiCS is not normalized correctly, if applied `T.NormalizeFeatures()`.
![image](https://user-images.githubusercontent.com/40286691/148160348-887581e7-a407-4410-80ec-d1de8bebbc32.png)

### To Reproduce

Please refer to the above screenshot.

### Expected behavior

1. Alignment of all attributes in the same data object (`dataset.data` and `dataset[0]`).
2. The value shouldn't be changed. It should be correct from the first time.
3. `T.NormalizeFeatures()` should work correctly.

### Environment

* PyG version (`torch_geometric.__version__`): 2.0.2
* PyTorch version: (`torch.__version__`): 1.10.0
* OS (*e.g.*, Linux): Linux
* Python version (*e.g.*, `3.9`): 3.8
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

### Additional context

Thank you so much for your effort and passion in this area!

**Comment by rusty1s** [comment]
Thanks for reporting.

1. This is actually intended. If you want to modify the underlying storage, you need to use `pre_transform`.
2. Fixed in master. The bug was that `NormalizeFeatures` transformed the node features in-place.
3. Fixed in master. The bug was that `NormalizeFeatures` did not correctly account for negative values in the data.

**Comment by yunhak0** [comment]
Thank you so much for your prompt feedback!

**Comment by AlexLiuyz** [comment]
![95774dcd5f79b8ae5a1278d1f5ae47d](https://github.com/pyg-team/pytorch_geometric/assets/117089712/50489f28-9538-4964-bc8f-f192d79dde41)
May I ask why does this occurs, seems I cannot download the dataset correctly
