### ISSUE TITLE
nn.Embedding input seems incorrect in pna example

### ISSUE THREAD

**Issue by hash-ir** [pyg-team/pytorch_geometric#3810]
Hi, I am running the Principal Neighborhood Aggregation [example](https://github.com/pyg-team/pytorch_geometric/blob/d3739283fa9d7d50fb433509fec45333760989fe/examples/pna.py). The input to the embedding layer should be an indices tensor, right? Whereas in the example, I found the node features tensor `x` to be the input: 

https://github.com/pyg-team/pytorch_geometric/blob/d3739283fa9d7d50fb433509fec45333760989fe/examples/pna.py#L53

At the moment, I am not using the `edge_attr` tensor but a similar question would arise in that case as well.

**Comment by rusty1s** [comment]
Yes, the `ZINC` dataset holds atom indices inside `x`, so we first need to embed them via `torch.nn.Embedding`. You do not have to do that in case `x` already holds continuous node features.

**Comment by hash-ir** [comment]
I see. That makes sense
