### ISSUE TITLE
Additional comments on Loading Graph from CSV and Creating custom dataset

### ISSUE THREAD

**Issue by mprithiv** [pyg-team/pytorch_geometric#3864]
### 📚 Describe the documentation issue

Hi,

I am trying to create an unsupervised graph embedding using heterogenous graph. I am using my own dataset that I have in a CSV format. I tried to use "Load Graph from CSV" but then when trying to create a GNN model as per the example, I am stuck with not having train_mask. Does this mean, I need to create a dataset first and then load the csv files? What is the difference between loading graph from CSV and Creating a custom dataset?

Thanks

**Comment by rusty1s** [comment]
Closing this in favor of https://github.com/pyg-team/pytorch_geometric/discussions/3866.
