### ISSUE TITLE
Improving documentation for Set2Set layer

### ISSUE THREAD

**Issue by arunppsg** [pyg-team/pytorch_geometric#3870]
### 📚 Describe the documentation issue

I am new to `pytorch_geometric` ecosystem and I was exploring it. At the first glance to the `Set2Set` layer in the [docs](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.glob.Set2Set), it is not clear what the inputs `x` and `batch` are to the forward pass.

If I am not wrong, `x` represents the node features of the graph and `batch` represents a mapping between the node features to their graph identifiers.

### Suggest a potential alternative/fix

I was wondering whether it will be good to include it to the docs or maybe also add typing.
Potential fix in `nn.glob.set2set.py`:
```
def forward(self, x: torch.Tensor, batch: torch.Tensor):
        r"""
        Args:
             x: The input node features.
             batch: A one dimension tensor representing a mapping between nodes and their graphs
        """
```

**Comment by wsad1** [comment]
@arunppsg I think its a good idea to add type hints. Please feel free to contribute this.

**Comment by rusty1s** [comment]
There is also some recent effort to bring shape information to all GNN operators, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/gin_conv.py#L41-L48). We can likely also do this for any other PyG operator.

**Comment by arunppsg** [comment]
Putting up shape information will be super useful. I will put up a small PR regarding the suggestions later this week. Thanks!

**Comment by arunppsg** [comment]
@wsad1 @rusty1s I wish to contribute to documentation, so that I could learn more about this project. Is there any place you suggest to start with? Like any models which require improvements to documentation, etc?

**Comment by rusty1s** [comment]
Thanks for the updates @arunppsg! Looks pretty clean :) If you are interested, we can continue with this road for alternative operators in `torch_geometric.nn`. Alternatively, we are in the process of providing a ["Dataset Cheatsheet"](https://pytorch-geometric.readthedocs.io/en/latest/notes/data_cheatsheet.html) that also need some community help :)

**Comment by arunppsg** [comment]
Perhaps, shall I continue with the work on `torch_geometric.nn`? Suggestions on good places to start will be helpful. Thanks a lot!

**Comment by rusty1s** [comment]
How about we continue adding "Shapes" support for [Global Pooling Layers](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#global-pooling-layers)?

**Comment by arunppsg** [comment]
Sure, I will put up PRs for the same shortly.
