### ISSUE TITLE
to_networkx to_undirected option inconsistent with documentation

### ISSUE THREAD

**Issue by RemyLau** [pyg-team/pytorch_geometric#3873]
### 🐛 Describe the bug

According to the documentation for [``to_networkx``](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.to_networkx), the ``to_undirected`` option preserves the upper triangle of the adjacency matrix and turn it into an undirected graph, something like the following

![eqn](https://quicklatex.com/cache3/06/ql_77affd715d97f56e1b528dfa14eb9606_l3.png)

But actually, the implementation does the opposite, which preserves the lower triangle and ignores the upper triangle.
The easiest fix would be to rewrite line#95 to ``if to_undirected and v < u``.

https://github.com/pyg-team/pytorch_geometric/blob/ffb70bcf6147b8d5c5a00650e1d1f514771d8898/torch_geometric/utils/convert.py#L93-L104

Despite this fix, the ``to_undirected`` option is a bit misleading in then sense that it is tempting to think it does what [``networkx.DiGraph.to_undirected``](https://networkx.org/documentation/stable/reference/classes/generated/networkx.DiGraph.to_undirected.html#networkx-digraph-to-undirected) does, i.e. if (u, v) in E, then add (v, u) in E if not already existed. My current work-around is the following:
```python
G = torch_geometric.utils.to_networkx(data, to_undirected=False, remove_self_loops=True).to_undirected()
```
Would it make sense to follow the ``to_undirected`` as networkx instead of only keeping track of either out (or in) edges?

### Environment

* PyG version: 2.0.2
* PyTorch version: 1.10
* OS: CentOS Linux
* Python version: 3.9.7
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for the issue. I might be wrong, but IMO `v > u` (which `u` being the row/source and `v` being the col/destination node maintain the upper triangle. That is, all column indices are greater than all corresponding row indices.

I agree that `to_undirected` naming is a bit confusing. It should probably be renamed to `undirected`. As PyG does not discriminate between undirected and directed graphs, this option is useful to tell `networkx` whether it should return a `nx.DiGraph` or a `nx.Graph`.

**Comment by RemyLau** [comment]
Hi @rusty1s, thanks for the quick response! I agree that ``v > u`` corresponds to the upper triangle, that is correct. But Line#96 implies that if it is in the upper triangle, you discard that edge, which is the opposite of what it meant to do, i.e. _preserving_ the upper triangle. Let me know I'm misunderstanding this.

**Comment by PabloAMC** [comment]
So the idea is to change
https://github.com/pyg-team/pytorch_geometric/blob/ffb70bcf6147b8d5c5a00650e1d1f514771d8898/torch_geometric/utils/convert.py#L95-L96
to 
```
        if to_undirected and u > v:
            continue
```
and that should be it, no? That'd skip the steps where `u>v`, eg the steps where the row > column, so the lower-left triangle.

**Comment by RemyLau** [comment]
Hi @rusty1s, I've made a [PR](https://github.com/pyg-team/pytorch_geometric/issues/3873) to fix this minor issue, now it should produce the results as suggested by the documentation.

However, I think it might still be helpful to have an option undirected conversion that converts all edges to undirected edges, instead of just the upper triangle. I'll propose doing so by having ``to_undirected`` take str type input in addition to the boolean type. Specifically, we can set ``to_undirected`` to
* ``"upper"`` (equivalent to ``True``): only preserve the upper triangle, same as the behavior of ``to_undirected=True`` in the current (#3901) implementation.
* ``"lower"``: only preserve the lower triangle.
* ``"all"``: preserve and convert all directed edges to undirected ones.
* ``False``: no undirected conversion.

Let me know if you think this is worth implementing.

**Comment by rusty1s** [comment]
Thank you @RemyLau. I think your suggestion sounds reasonable and I'm happy to add if it is of need for your use-case. For `"all"`, we would still need to merge edge features of duplicated edges, right?

**Comment by rusty1s** [comment]
Mh, after some thoughts I don't think we should over-complicate things here and try to merge separate functionalities into a single one. For the `"all"` option, the user can always let the function return a `DiGraph` and do the conversion `to_undirected` manually. As such, I'm in favor of just adding the option whether the user wants to preserve the lower or upper triangle in case `to_undirected=True`, and out-source `"all"` functionality to `networkx`.

**Comment by RemyLau** [comment]
@rusty1s yes, that sounds reasonable to me!

**Comment by RemyLau** [comment]
Hi @rusty1s, I've proposed a solution for the "upper" and "lower" options (#3948) in case you haven't had time to implement this change.

> Mh, after some thoughts I don't think we should over-complicate things here and try to merge separate functionalities into a single one. For the `"all"` option, the user can always let the function return a `DiGraph` and do the conversion `to_undirected` manually. As such, I'm in favor of just adding the option whether the user wants to preserve the lower or upper triangle in case `to_undirected=True`, and out-source `"all"` functionality to `networkx`.

**Comment by rusty1s** [comment]
Thank you! I just merged your PR.
