### ISSUE TITLE
to_netwrokx attr

### ISSUE THREAD

**Issue by MohsenFazaeli** [pyg-team/pytorch_geometric#3881]
### 🐛 Describe the bug

Hi,
I am new to package. I wrote following code and attributes are empty in networkx export. I it bug or I had some mistake in code.

```
import os.path as osp

import torch
from torch_geometric.datasets import Planetoid
from torch_geometric.utils import to_networkx
import networkx as nx

def main():
    dataset = 'Cora'
    path = osp.join('data', 'Planetoid')
    datasets = Planetoid(path, dataset)
    data = datasets[0]

    nxg = to_networkx(data, node_attrs=['x','y'], to_undirected=True, remove_self_loops=True)
    nx.write_edgelist(nxg, "data2/"+dataset+"/edges.txt", data=True)


if __name__ == "__main__":
    main()
```

### Environment

* PyG version: 1.6.3
* PyTorch version:1.7.1
* OS:windwos 10
* Python version:3.7
* pip

**Comment by rusty1s** [comment]
What's the issue? Is it that the `data` is empty for the given edge list? This is the case since `x` and `y` are node attributes, while you are currently only saving edge indices and features.

**Comment by PabloAMC** [comment]
@MohsenFazaeli also notice that by `y` the dataset refers to the target node prediction?

**Comment by MohsenFazaeli** [comment]
TY for answers.
I thought it also saves nodes features in some way.
