### ISSUE TITLE
Adding Pix3d dataset to torch.geometric.dataset

### ISSUE THREAD

**Issue by addy1997** [pyg-team/pytorch_geometric#3883]
### 🚀 The feature, motivation and pitch

**Pix3D** is a widely used dataset in *3D modeling* and *Geometric processing*. Since, **pytoch_geometric** is a library with a variety of functions to perform `3D shape analysis`, `Point Cloud Processing`, and `Material Reconstruction`, it will be really helpful to include this dataset in the list. This will considerably increase the usage of this library.

**Comment by rusty1s** [comment]
I'm happy to include this one. Let me know if you have interest in contributing this dataset :)

**Comment by addy1997** [comment]
@rusty1s, Yes, I will be happy to contribute. Is there a specific template/structure the code follows?

**Comment by rusty1s** [comment]
There is not, I'm sorry. It's probably best to look at related datasets, e.g., [ShapeNet](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/datasets/shapenet.py) or [S3DIS](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/datasets/s3dis.py).
