### ISSUE TITLE
DBP15K download url seems to be broken

### ISSUE THREAD

**Issue by AndAgio** [pyg-team/pytorch_geometric#3980]
### 🐛 Describe the bug

The google drive file ID linked with the DBP15K dataset seems to point to a broken URL. Indeed, running a simple 
```dataset = torch_geometric.datasets.DBP15K(os.getcwd(), 'en_fr')``` returns a ```zipfile.BadZipFile: File is not a zip file```.
This is due to the fact that the code downloads an empty zip file, which can't be unzipped. Digging a bit more it seems that the google drive URL used for the dataset download is not valid anymore. Is there a workaround?

### Environment

* PyG version: 2.0.1
* PyTorch version: 1.9.0
* OS: MacOS 12.0.1
* Python version: 3.8.12
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by rusty1s** [comment]
Mh, you are right. What a bummer. It looks like the files are not longer available under this repo: https://github.com/syxu828/Crosslingula-KG-Matching. I created an issue here: https://github.com/syxu828/Crosslingula-KG-Matching/issues/18

**Comment by nxznm** [comment]
Hi @AndAgio  @rusty1s 
Recently, I obtained a copy of the DBP15K.zip from [this issue](https://github.com/syxu828/Crosslingula-KG-Matching/issues/9), and I put this copy in my google drive. Here is the url: https://drive.google.com/open?id=1ggYlYf2_kTyi7oF9g07oTNn3VDhjl7so.
I also test this dataset with `examples/dbp15k.py` in the [repo](https://github.com/rusty1s/deep-graph-matching-consensus/tree/master/examples), and it works well.

**Comment by rusty1s** [comment]
This is awesome! Can you send a PR with the applied changes?

**Comment by nxznm** [comment]
Yes, I'm glad to do it :)
