### ISSUE TITLE
Eigenvalues in ChebConv

### ISSUE THREAD

**Issue by daniel-unyi-42** [pyg-team/pytorch_geometric#3996]
### 🚀 The feature, motivation and pitch

In the forward function of ChebConv, there's this error message:

```
if self.normalization != 'sym' and lambda_max is None:
            raise ValueError('You need to pass `lambda_max` to `forward() in`'
                             'case the normalization is non-symmetric.')
```

Based on the Gershgorin circle theorem, 2.0 is the upper bound of eigenvalues for **both** normalizations ('sym' and 'rw').
Furthermore, 2.0 * edge_weight.max() is the upper bound of eigenvalues for the non-normalized Laplacian.

I'd suggest to remove this error message for 'rw' normalization and consider to remove it for non-normalization.
It makes the usage of ChebConv way easier, especially for the regular user.

**Comment by rusty1s** [comment]
Sounds good. Let me know if you want to contribute this feature.

**Comment by daniel-unyi-42** [comment]
I'd be glad to contribute.
