### ISSUE TITLE
GlobalStorage unable to infer num_nodes for graph

### ISSUE THREAD

**Issue by xoroyoko** [pyg-team/pytorch_geometric#4002]
### 🐛 Bug

Hi, first of all, thank you for this amazing package. I am trying to create a graph that has both `edge_index` and `x` stored as `SparseTensor()`. I believe it is possible and it makes sense. If not, please let me know right away. So I am running this code:
```python
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
import torch
from torch_sparse import SparseTensor


class MyData(Data): # class that would allow me to use sparse X
    def __cat_dim__(self, key, value, *args, **kwargs):
        if key == 'x':
            return 0
        else:
            return super().__cat_dim__(key, value, *args, **kwargs)


edge_index = torch.tensor([
   [0, 1, 1, 2],
   [1, 0, 2, 1],
])
x = torch.tensor([
    [0, 1, 0, 3],
    [4, 5, 0, 7],
    [0, 9, 0, 0]
])
num_nodes = x.size(0)

data = MyData(
    x=SparseTensor.from_dense(x),
    adj_t=SparseTensor(row=edge_index[0], col=edge_index[1], value=None, sparse_sizes=(num_nodes, num_nodes)).t()
)

data_list = [data, data]
loader = DataLoader(data_list, batch_size=2)
batch = next(iter(loader))

print(batch)
```
And straight away I get a pretty long stack trace ending up with:
`AttributeError: 'GlobalStorage' object has no attribute 'num_nodes'`
I have tried setting up the `num_nodes` attribute manually on the `data` object, but that fails too. I believe this is a bug in the GlobalStorage. Please, could you have a look and let me know? Thanks!

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10.0+cu113
* OS: Linux Ubuntu 20.04
* Python version: 3.8
* CUDA/cuDNN version: 11.3.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): --

**Comment by rusty1s** [comment]
Thanks for reporting! This is already fixed in master. You can check by installing PyG via
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
