### ISSUE TITLE
Unexpected `GATConv` behavior

### ISSUE THREAD

**Issue by augustwester** [pyg-team/pytorch_geometric#4020]
### 🐛 Describe the bug

I am experiencing what to me looks like unexpected behavior using `GATConv`. To demonstrate, consider the following extremely simple model.

```
class GAT(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = GATConv(1, 1, bias=False)

    def forward(self, data):
        x, att = self.conv(data.x, data.edge_index, return_attention_weights=True)
        return x, att

model = GAT()

x = torch.tensor([[1], [2]], dtype=torch.float)
edge_index = torch.tensor([[1], [0]], dtype=torch.long)
data = Data(x=x, edge_index=edge_index)

out, att = model(data)
print(out)
print(att)
```

We give as input a graph containing two nodes, A and B, with a directed edge from B to A. The initial value of A is 1 and the initial value of B is 2. We get the following output:

```
tensor([[-2.2648],
        [-3.0969]], grad_fn=<ViewBackward0>)
(tensor([[1, 0, 1],
        [0, 0, 1]]), tensor([[0.4626],
        [0.5374],
        [1.0000]], grad_fn=<DivBackward0>))
```

Since `GATConv` adds self-loops to the graph, we get three attention weights. One of those weights is `1.0000` and must therefore belong to the self-loop of node A, since A only has one neighbor (itself). This also means that W=`-2.2648` since A's initial value was 1 and `bias=False`. For reference, this is the relevant equation from the original paper:

<img width="808" alt="Screen Shot 2022-02-07 at 18 18 03" src="https://user-images.githubusercontent.com/747600/152838606-0ffbae99-2aeb-4ca8-90e1-2e89838a3d2f.png">

Given that W is also used to update the representation of node B, it seems to me that either

`0.4626*W*A + 0.5374*W*B = 0.4626*(-2.2648)*1 + 0.5374*(-2.2648)*2`
or
`0.5374*W*A + 0.4626*W*B = 0.5374*(-2.2648)*1 + 0.4626*(-2.2648)*2`

must be the updated representation for B, depending on which weight belongs to which edge.

However, the first expression equals `-3.4819` and the second equals `-3.3125`. How does this square with the updated representation for B of `-3.0969`?

Am I misunderstanding something or is this a bug in the implementation?

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10.2
* OS: macOS 12.1 (Monterey)
* Python version: 3.9.1
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by rusty1s** [comment]
Since you have a directed edge from B to A, the attention coefficient of 1 belongs to the self-loop of B. This can also be directly read by from the output:
```
(tensor([[1, 0, 1],
        [0, 0, 1]]),
tensor([[0.4626],
        [0.5374],
        [1.0000]], grad_fn=<DivBackward0>))
```
with being `(1, 1)` and `(1.0)` being the last entries.

As such, `W = 0.5 * -3.0969 = -1.54845` and `A = 0.4626 * -1.54845 * 2 + 0.5374 * -1.54845 * 1 = -2.26476297` (which looks correct to me).

**Comment by augustwester** [comment]
Ah, I see. I guess that means B is considered a neighbor of A but A is not considered a neighbor of B? This is counterintuitive to me because of the direction of the edge. However, it makes sense when you think about information flowing from source to target.

Thanks for helping out (and sorry for the false alarm) 🙂

**Comment by rusty1s** [comment]
If you prefer it the other way round, you can set `flow="target_to_source"` inside a `MessagePassing` module.
