### ISSUE TITLE
env/lib/python3.9/site-packages/torch_sparse/_convert_cpu.so, 0x0006): Symbol not found

### ISSUE THREAD

**Issue by DonghanHe** [pyg-team/pytorch_geometric#4044]
### 😵 Describe the installation problem

just barely getting started with 

``` 
from ogb.graphproppred import PygGraphPropPredDataset
from torch_geometric.data import DataLoader

# Download and process data at './dataset/ogbg_molhiv/'
# dataset = PygGraphPropPredDataset(name = "ogbn-arxiv", root = 'dataset/')
dataset = PygGraphPropPredDataset(name = 'ogbn-arxiv')
```

OSError: dlopen(/Users/donghanhe/env/lib/python3.9/site-packages/torch_sparse/_convert_cpu.so, 0x0006): Symbol not found: __ZN2at5emptyEN3c108ArrayRefIxEENS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE

### Environment

* PyG version:
* PyTorch version: 1.10.0
* OS: MAC
* Python version: 3.9
* CUDA/cuDNN version: cpu
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. This error is well-known to us and you can search in the existing issues to find some possible solutions.

In general, this error indicates that there is a mismatch between the PyTorch version `torch-sparse` were compiled with, and the PyTorch version you are actually using. How did you install PyTorch and `torch-sparse` in the first place?

**Comment by DonghanHe** [comment]
hey rusty1s, thanks for replying. after re-installing torch-sparse and related packages, it's working now! thanks again :)

**Comment by furmanlukasz** [comment]
I have similar error, but with M1 apple silicon while importing `from torch_geometric.nn import GCNConv`: 
```
OSError: dlopen(/Users/luki/opt/anaconda3/envs/cookie3LAB/lib/python3.8/site-packages/torch_cluster/_grid_cpu.so, 0x0006): Symbol not found: (__ZN2at4_ops15sum_dim_IntList4callERKNS_6TensorEN3c108ArrayRefIxEEbNS5_8optionalINS5_10ScalarTypeEEE)
  Referenced from: '/Users/luki/opt/anaconda3/envs/cookie3LAB/lib/python3.8/site-packages/torch_cluster/_grid_cpu.so'
  Expected in: '/Users/luki/opt/anaconda3/envs/cookie3LAB/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib'
```
tried both with last nightly pytorch (mps support) and with regular one, on new envs(anaconda) with python versions 3.8. & 3.9.  PyG installed for 3.8 with `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cpu.html` for 3.9 with anaconda `conda install pyg -c pyg`. Each time the same error..

**Comment by rusty1s** [comment]
For M1, it is currently best to install from source by running `pip install --verbose torch-scatter`, etc. This works for me. At best, try to do that in a fresh environment.

**Comment by furmanlukasz** [comment]
> For M1, it is currently best to install from source by running `pip install --verbose torch-scatter`, etc. This works for me. At best, try to do that in a fresh environment.

Did you manage it to work with pytorch msp support (eg. last nightly build)? I was able to install with this library configuration but is only cpu:

```
python 3.9.12
torch                              1.11.0                  
torch-cluster                 1.6.0                   
torch-geometric            2.1.0.post1             
torch-scatter                 2.0.9                    
torch-sparse                  0.6.15                 
torch-spline-conv         1.2.1                    
torchaudio                      0.11.0                  
torchvision                      0.12.0                  
```

**Comment by rusty1s** [comment]
Yes, there is no support for mps yet.

**Comment by rusty1s** [comment]
I only know about this one: https://medium.com/@jgbrasier/installing-pytorch-geometric-on-mac-m1-with-accelerated-gpu-support-2e7118535c50
