### ISSUE TITLE
Allow direct contruction of `Batch`

### ISSUE THREAD

**Issue by mova** [pyg-team/pytorch_geometric#4071]
### 🚀 The feature, motivation and pitch

I'm working on GANs  for graphs that generates multiple graphs at once.
The output of the generator is a feature matrix and a vector in the form of `Batch.batch`. I would like to pass it on to the discriminator directly as a `Batch`, without splitting the matrix first, creating `Data` objects and then calling `from_data_list`.
After the construction `.__getitem__` and `.num_graphs` should be available.

Cheers!

**Comment by rusty1s** [comment]
You should be able to do this via `Batch(x=x, batch=batch)`. Let me know if this helps you.

**Comment by mova** [comment]
```
batch = Batch(x=x, batch=batch)
batch[0]
```
Leads to 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[/home/mscham/fgsim/venv1.10.1]()+cu111[/lib/python3.8/site-packages/torch_geometric/data/batch.py]()", line 148, in __getitem__
    return self.get_example(idx)
  File "[/home/mscham/fgsim/venv1.10.1]()+cu111[/lib/python3.8/site-packages/torch_geometric/data/batch.py]()", line 92, in get_example
    raise RuntimeError(
RuntimeError: Cannot reconstruct 'Data' object from 'Batch' because 'Batch' was not created via 'Batch.from_data_list()'
```
I need a `__getitem__`, because at times, I need to pull single graphs from the batch.

**Comment by rusty1s** [comment]
Ah, sorry I missed this. To allow for this feature, `_num_graphs`, `_slice_dict` and `_inc_dict` need to be available, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/batch.py#L77-L79). If you only have a node feature `x`, then setting `_num_graphs` to `int(batch.max()) + 1` and setting `_slice_dict` to `{'x': torch.cat([torch.zeros(1, dtype=torch.long), batch.cumsum(dim=0)], dim=0) }` is probably sufficient.

**Comment by mova** [comment]
Apparently this there is still an _inc_dict missing:
```Traceback (most recent call last):
  File "[.../torch_geometric/data/storage.py]()", line 48, in __getattr__
    return self[key]
  File "[.../torch_geometric/data/storage.py]()", line 68, in __getitem__
    return self._mapping[key]
KeyError: '_inc_dict'
```

**Comment by mova** [comment]
Okay, I looked at how batches are constructed if I split them up and recombine them with `from_data_list` and came up with the following code for `_inc_dict`:
```
        _inc_dict = defaultdict(dict)
        _inc_dict["x"] = torch.zeros(
            batch._num_graphs, dtype=torch.long, device=device
        )
        batch._inc_dict = _inc_dict
```
but the slice dict looks quite different, then the one generated with the code:
```
slice_dict["x"] #from the collate function in torch_geometric.data.collate
>tensor([    0,   639,  1206,  1776,  2281,  2977,  3508,  3956,  4621,  5089,
         5694,  6267,  6895,  7582,  8175,  8693,  9198,  9755, 10331, 10916,
        11501, 12061, 12689, 13150, 13619, 14247, 14880, 15552, 16063, 16635,
        17270, 17967, 18415, 19053, 19521, 20143, 20611, 21168, 21736, 22408,
        23035, 23464, 23992, 24541, 25067, 25540, 26044, 26663, 27187, 27682,
        28362])
```
vs 
```
_slice_dict["x"].shape
> torch.Size([28363])

**Comment by rusty1s** [comment]
Oh yeah, sorry. I was too fast :)

```python
out = torch_scatter.scatter_add(torch.ones(batch, dtype=torch.long), batch, dim=0)
out = out.cumsum(dim=0)
_slice_dict['x'] = torch.cat([torch.zeros(1, dtype=torch.long), out], dim=0
```
should hopefully do the trick.

**Comment by rusty1s** [comment]
I see. For the current approach, `events` need to be sorted. Thus,
```python
events = torch.randint(0, n_graphs, (n_graphs * 10, )).sort()[0]
```
fixes your issues.

**Comment by mova** [comment]
Hey,
thanks for your help. 
I came up with the following code that works for now.
```
def batch_construct_direct(pcs: torch.Tensor, batch_idxs: torch.Tensor) -> Batch:
    device = pcs.device
    batch = Batch(x=pcs, batch=batch_idxs)
    batch._num_graphs = int(batch.batch.max() + 1)

    _slice_dict = defaultdict(dict)
    out = torch_scatter.scatter_add(
        torch.ones(len(batch.x), dtype=torch.long, device=device), batch_idxs, dim=0
    )
    out = out.cumsum(dim=0)
    _slice_dict["x"] = torch.cat(
        [torch.zeros(1, dtype=torch.long, device=device), out], dim=0
    )

    batch._slice_dict = _slice_dict

    _inc_dict = defaultdict(dict)
    _inc_dict["x"] = torch.zeros(batch._num_graphs, dtype=torch.long, device=device)
    batch._inc_dict = _inc_dict
    return batch
    ```
Do you think it would be worth a having a constructor of the `Batch` class could take care of this?  If not feel free to close this.

**Comment by rusty1s** [comment]
Glad that it's working.

I think it is not really possible to allow this in a generic case, as we usually cannot do any assumptions on `_slice_dict` and `_inc_dict`. How they look like is really task-dependent.
