### ISSUE TITLE
Default installation causes CUDA error in Google Colab

### ISSUE THREAD

**Issue by MQSchleich** [pyg-team/pytorch_geometric#4095]
### 😵 Describe the installation problem

When trying to install the library with 
```
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric
```
I receive the following error in Google Colab

```
/usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor5zero_Ev
```
I experienced the error before with PyTorch 1.10 on a local cluster. I was searching the issues but could not find someone with the same problem, yet. The error is known in the site package https://github.com/rusty1s/pytorch_sparse/issues/180

### Environment

* PyG version: NameError: name 'torch_geometric' is not defined
* PyTorch version: 11.1
* OS: Ubuntu
* Python version: 3.7
* CUDA/cuDNN version: 1.10
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): PyG is not recognized properly as a package and CUDA bindings seem to be broken.

**Comment by rusty1s** [comment]
Can you try following the installation we utilize in our Google Colabs? See [here](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing).

**Comment by MQSchleich** [comment]
It works, thank you. Do you know why the error occurs?

**Comment by rusty1s** [comment]
I haven't yet tried to reproduce the error but it looks like Colab only installs the CPU version of `torch-sparse` while it has a GPU available. Ensuring that you install from binaries rather than via manual installation fixes this.
