### ISSUE TITLE
Batching graphs with additional attributes passed via kwargs

### ISSUE THREAD

**Issue by arunppsg** [pyg-team/pytorch_geometric#4099]
### 🐛 Describe the bug

Steps to reproduce:
```
x = torch.randn(5, 10)
edge_attr = torch.randn(5, 3)
edge_index = torch.tensor([[0, 1, 2, 3, 4], [1, 2, 3, 4, 0]]).long()
z = torch.randn(4)

g1 = Data(x, edge_index, edge_features, z=global_features)
g2 = Data(x, edge_index, edge_features, z=global_features)

b = Batch()
b = b.from_data_list([g1, g2])

print (b.z.shape)
```
Expected: `[2, 4]`, got `[8]`.

I think some check should be added when graphs with kwargs are passed to `Batch` method to assert their shape. Something like:
```
if z.dim() == 1:
  z = z.unsqueeze(0)
```

**Comment by rusty1s** [comment]
By default, we concatenate in the first dimension. If you want to batch along a new dimension, you should consider reshaping your global features to shape `[1, 4]` or follow [this tutorial](https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html#batching-along-new-dimensions).

**Comment by arunppsg** [comment]
Sorry, I missed looking into it. It's clear now. Thanks!
