### ISSUE TITLE
How to deal with high-dimensional features of nodes?

### ISSUE THREAD

**Issue by finquick** [pyg-team/pytorch_geometric#4108]
### 🚀 The feature, motivation and pitch

I just started using PYG, how to deal with the high dimensional feature of nodes？
For example, if the node feature dimension is 7\*96 and the input data shape is 【Batch, num_nodes, signal_channel, time_slice】, how do I feed the data into the GAT model? 【Num_nodes, signal_channel*time_slice】?
In DGL I can feed the feature as the shape【Batch, num_nodes, signal_channel, time_slice】, how can I do this in PYG?
Thanks！

**Comment by rusty1s** [comment]
Please see my answer in https://github.com/pyg-team/pytorch_geometric/discussions/4107.
