### ISSUE TITLE
Docs in Creating “Larger” Datasets part

### ISSUE THREAD

**Issue by Nokimann** [pyg-team/pytorch_geometric#4131]
### 📚 Describe the documentation issue

I followed the [Creating “Larger” Datasets](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html#creating-larger-datasets).

I wrote my dataset class. But, when I reuse my own class, the class tries re-processing again from scratch.

### Suggest a potential alternative/fix

I guess one line like `self.data, self.slices = torch.load(self.processed_paths[0])` in the right above Docs for `InMemoryDataset` should be added.

**Comment by rusty1s** [comment]
In general, datasets are only re-processed in case not all files in `processed_file_names` cannot be found inside `{root}/processed`. Does that might explain your issues?

**Comment by Nokimann** [comment]
Remember this is my fault.
