### ISSUE TITLE
`has_isolated_nodes()` and `contains_isolated_nodes()` return different result for same edge_index graph

### ISSUE THREAD

**Issue by BodyCSoulN** [pyg-team/pytorch_geometric#4138]
### 🐛 Describe the bug

`has_isolated_nodes()` and `contains_isolated_nodes()` return different result for same edge_index graph

```python
from torch_geometric.data import Data
import torch_geometric.utils as utils
import torch

g = Data(x=torch.randn(4, 3), edge_index = torch.tensor([[0, 0, 1], [1, 2, 3]]))
print(g.has_isolated_nodes())
print(utils.contains_isolated_nodes(g.edge_index))
```

```bash
True
False
```

### Environment

* PyG version: 2.0.3
* PyTorch version:1.10.0
* OS:Linux
* Python version:3.7.11
* CUDA/cuDNN version:11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. There was indeed some inconsistency between both methods (`data.has_isolated_nodes()` checked if every node has at least one in-coming edge, while `utils.contains_isolated_nodes()` did not differentiate between in-coming and out-going edges). This is now fixed.

**Comment by BodyCSoulN** [comment]
> Thanks for reporting. There was indeed some inconsistency between both methods (`data.has_isolated_nodes()` checked if every node has at least one in-coming edge, while `utils.contains_isolated_nodes()` did not differentiate between in-coming and out-going edges). This is now fixed.

So, which one is the correct answer?
I think that a isolated node have neither in-coming edges nor out-going edges.

**Comment by rusty1s** [comment]
Yes, that's how it is implemented now in master (replicating the old behavior of `utils.contains_isolated_nodes`).
