### ISSUE TITLE
maybe an error in the doc of “Heterogeneous Graph Learning”

### ISSUE THREAD

**Issue by finquick** [pyg-team/pytorch_geometric#4149]
### 📚 Describe the documentation issue

Compared to the picture, the relationship of the edges seems to be wrong.
```python
data['author', 'has_topic', 'institution'].edge_index = ... # [2, num_edges_topic]
```

### Suggest a potential alternative/fix

data['paper', 'has_topic', 'field_of_study'].edge_index = ... # [2, num_edges_topic]

**Comment by rusty1s** [comment]
Thanks for spotting. This is now fixed in master.

**Comment by finquick** [comment]
> Thanks for spotting. This is now fixed in master.
More need to thank you for your efforts, and the help to me with the graph neural network！
Thanks！
