### ISSUE TITLE
GNNs with Missing Node Features 🚀

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#4176]
### 🚀 The feature, motivation and pitch

**Paper:** [On the Unreasonable Effectiveness of Feature propagation in Learning on Graphs with Missing Node Features](https://arxiv.org/abs/2111.12128)
**Code:** [zip](https://openreview.net/attachment?id=tx4qfdJSFvG&name=supplementary_material)

The paper presents simple, fast and scalable approach for handling missing features in graph machine learning applications.
It might be very interesting to add the approach of feature propagation and an example of it to PyG.

 @wsad1 Let me know if you have interest in looking into this.

**Comment by wsad1** [comment]
Sure @rusty1s, I'll check this out and come up with a short plan.

**Comment by wsad1** [comment]
Some thoughts

- Add `FeaturePropagation` to `torch_geometric.nn.models`.
- 
![image](https://user-images.githubusercontent.com/13963626/157891878-47d3f437-3508-49c0-b43f-4d514cca487e.png)
Instead of resetting know features every iteration, we could remove incoming edges to nodes with features from nodes without features, before starting the propagation. This would be more efficient than resetting.

**Comment by rusty1s** [comment]
Since this model has no parameters, I'm not sure we want to put it into `model`. How about providing it as a `transform`? What that work as well? Also note that the code just got released: https://github.com/twitter-research/feature-propagation

**Comment by rusty1s** [comment]
Thanks for chiming in @emalgorithm.

I think resetting features is easier to implement. It should also be more efficient if we utilize `SparseTensor` matrix-multiplication rather than scatter/gather (but this is just a guess). The edge removal proposal also doesn't work if features of a node are only partially missing, right?

**Comment by emalgorithm** [comment]
Yes actually, that's true, the edge removal would work only when a node either has all features or none, but not in the general case of some features missing.  Standard diffusion and then resetting is definitely the cleanest solution then.

**Comment by wsad1** [comment]
Yes it does fit into `transform` better.

For the general case where node features are partially missing the user would input a `mask` of shape num_nodes*num_features, which we would use while resetting the features, right? But at the same time we might need to let the user pass a `mask` of shape num_nodes when a node has all features or none.

**Comment by EdisonLeeeee** [comment]
Is anyone working on this? If not I can take it.

**Comment by rusty1s** [comment]
This would be awesome :)

**Comment by Praniyendeev** [comment]
I was looking at the source code, doesnt seem like it is implemented for HeteroData right?

**Comment by rusty1s** [comment]
I don't think this feature is applicable to GNNs since it relies on aggregating nearby features of the same node type. This would only be possible if you have an edge type specified that points to itself (same source and destination node type).
