### ISSUE TITLE
AttributeError: 'GlobalStorage' object has no attribute 'adj_t'

### ISSUE THREAD

**Issue by shravankumar147** [pyg-team/pytorch_geometric#4192]
### 🐛 Describe the bug

An error occurred while executing  [gcn2_cora](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/gcn2_cora.py).

It's occurring while performing => 
 `data.adj_t = gcn_norm(data.adj_t)  # Pre-process GCN normalization. `

Whole error from the screen: 
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/torch_geometric/data/storage.py](https://localhost:8080/#) in __getattr__(self, key)
     46         try:
---> 47             return self[key]
     48         except KeyError:

3 frames
[/usr/local/lib/python3.7/dist-packages/torch_geometric/data/storage.py](https://localhost:8080/#) in __getitem__(self, key)
     66     def __getitem__(self, key: str) -> Any:
---> 67         return self._mapping[key]
     68 

KeyError: 'adj_t'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
[<ipython-input-6-107ffeaeccd1>](https://localhost:8080/#) in <module>()
      7 # dataset = Planetoid(path, dataset, transform=transform)
      8 data = dataset[0]
----> 9 data.adj_t = gcn_norm(data.adj_t)  # Pre-process GCN normalization.

[/usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py](https://localhost:8080/#) in __getattr__(self, key)
    360                 "dataset, remove the 'processed/' directory in the dataset's "
    361                 "root folder and try again.")
--> 362         return getattr(self._store, key)
    363 
    364     def __setattr__(self, key: str, value: Any):

[/usr/local/lib/python3.7/dist-packages/torch_geometric/data/storage.py](https://localhost:8080/#) in __getattr__(self, key)
     48         except KeyError:
     49             raise AttributeError(
---> 50                 f"'{self.__class__.__name__}' object has no attribute '{key}'")
     51 
     52     def __setattr__(self, key: str, value: Any):

AttributeError: 'GlobalStorage' object has no attribute 'adj_t'
```

### Environment

* PyG version:2.0.4
* PyTorch version:1.10.0+cu111
* OS:Linux
* Python version:3.7.12
* CUDA/cuDNN version:11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): on colab
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

**Comment by rusty1s** [comment]
Thanks for reporting. I cannot really reproduce this on my machine. What's the output of `print(data)` prior to the `gcn_norm` call for you? Can you try to delete any processed files of `Planetoid` first and try downloading/processing them again?

**Comment by shravankumar147** [comment]
Hi Matt, 

 I have started a new session and retested the code, this time it worked without any issues. 

Below attaching my notebook for reference. 
[gcn2_cora example notebook](https://gist.github.com/shravankumar147/acdcd9799b008b96630afcba187bca46)

Thanks for the suggestions.

Best
Shravan

**Comment by JennySeidenschwarz** [comment]
Hey everyone :)

I also have this from time to time and then if I re-run my code it works. I'm not sure what it is but it seems like it appears for several people and very irregularly so it's hard to reproduce.

Best,
Jenny
