### ISSUE TITLE
Missing ``class_resolver`` dependency

### ISSUE THREAD

**Issue by RemyLau** [pyg-team/pytorch_geometric#4195]
### 😵 Describe the installation problem

Recently I'm receiving the following error caused by loading a GNN layer object from PyG due to a missing dependency on ``class_resolver``.

```txt
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/torch_geometric/nn/models/basic_gnn.py", line 60, in __init__
    from class_resolver.contrib.torch import activation_resolver
ModuleNotFoundError: No module named 'class_resolver'
```

The issue is resolved by simply installing this (``pip install class_resolver``). I also notice that this requirement is included in the "full" install requirements and will be installed automatically if I do ``pip install torch-geometric [full]``. However, I'm using the latest PyG on github in my github actions ``pip install git+https://github.com/pyg-team/pytorch_geometric.git``. I'm wondering would it be possible to pass the ``[full]`` option to ``pip`` in this case? I tried ``pip install git+https://github.com/pyg-team/pytorch_geometric.git [full]`` and it did not work:

```txt
ERROR: Invalid requirement: '[full]'
```

### Environment

* PyG version: latest (``pip install git+https://github.com/pyg-team/pytorch_geometric``)
* PyTorch version: 1.9.0
* OS: ubuntu-latest
* Python version: 3.8
* CUDA/cuDNN version: CPU
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This should work:
```python
pip install git+https://github.com/pyg-team/pytorch_geometric.git#egg=torch-geometric[full]
```
Alternatively, you can just install `class-resolver` after installing PyG:
```
pip install "git+https://github.com/pyg-team/pytorch_geometric.git
pip install class-resolver

**Comment by RemyLau** [comment]
Thanks a lot, @rusty1s! I'll go with the first option since I might encounter some other missing dependencies as I'm adding more tests to the project.

**Comment by chenzhekl** [comment]
I encountered a similar problem. However, I installed `torch_geometric` through `conda`. I found that `class-resolver` is not available as a `conda` package, which means it is necessary to fallback to `pip install class-resolver`. But mixing pip and conda packages is not considered a good practice. Do you have any suggestions? @rusty1s

**Comment by rusty1s** [comment]
Currently, `class_resolver` is used inside `MLP` and basic `GNN` models for resolving activation functions from PyTorch. We could consider integrating this functionality directly inside PyG to avoid the extra dependency. Otherwise, falling back to `pip install class-resolver` is the only workaround I am aware of.

Pinging @cthoyt here as well.

**Comment by cthoyt** [comment]
`class-resolver` currently doesn't have any dependencies (i.e., it only uses stuff that's built in to modern versions of Python), so it wouldn't introduce a huge footprint to include as a required dependency. I plan to keep it as lightweight as possible (except for when introducing more parts to the `class_resolver.contrib` module, which contain optional dependencies).

I'm pretty skeptical of Conda in that it's almost always better as a package maintainer to make code that is easily installable through pip (e.g., with pre-compiled wheels, where appropriate). That being said, if someone wants to take the time to educate me in how to deploy to Conda, I will consider doing so for `class-resolver` (and include it in the tox configuration in https://github.com/cthoyt/cookiecutter-snekpack that all of my packages use)
