### ISSUE TITLE
to_networkx causes a bug

### ISSUE THREAD

**Issue by meloncolie** [pyg-team/pytorch_geometric#4229]
### 🐛 Describe the bug

Code:
```python
import torch
from torch_geometric.data import Data
from torch_geometric.utils import to_networkx

to_networkx(Data(torch.Tensor([0, 0, 0]).long(), torch.Tensor([[1],[2]]).long(), edge_type=torch.Tensor([0]).long()), edge_attrs=['edge_type'], to_undirected=False)
```

Segmentation Fault:
```
'int' object is not subscriptable
```

Analysis:
https://github.com/pyg-team/pytorch_geometric/blob/c40e28a6b19a69ee61271857aa4396d5dc5a0f3e/torch_geometric/utils/convert.py#L90

the `.squeeze().tolist()` function converts a torch.Tensor to a python list except that it converts a torch.Tensor with single size  (in whatever dimention) to a single int value. In the latter case, the segmentation fault occurs onces the output int value is indexed.
https://github.com/pyg-team/pytorch_geometric/blob/c40e28a6b19a69ee61271857aa4396d5dc5a0f3e/torch_geometric/utils/convert.py#L113
The results of the above function is demonstrated as below:
```python
In [2]: torch.Tensor([1]).squeeze().tolist()
Out[2]: 1.0

In [3]: torch.Tensor([[1]]).squeeze().tolist()
Out[3]: 1.0

In [4]: torch.Tensor([[1]]).squeeze()
Out[4]: tensor(1.)

In [5]: torch.Tensor([[1],[1]]).squeeze().tolist()
Out[5]: [1.0, 1.0]

In [6]: torch.Tensor([[1,1]]).squeeze().tolist()
Out[6]: [1.0, 1.0]
```

Temporally, I avoid this segmentation fault by changing edge_type to a numpy array.

### Environment

* PyG version: until the latest version 2.0.3
* PyTorch version: 1.7.1
* OS: MacOS\CentOS
* Python version: 3.8.12\3.6.8
* CUDA/cuDNN version: CPU
* How you installed PyTorch and PyG (`conda`, `pip`, source): PyTorch with conda, PyG with pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-cluster         1.5.9
torch-scatter         2.0.7
torch-sparse          0.6.12
torch-spline-conv     1.2.1

**Comment by rusty1s** [comment]
Thanks for reporting. This should now be fixed in master, see https://github.com/pyg-team/pytorch_geometric/commit/fa05a615f473fdd1cf9d730d34a19b6f1233c459.
