### ISSUE TITLE
Transforme_conv has a bug about query key and value.

### ISSUE THREAD

**Issue by sixu0** [pyg-team/pytorch_geometric#4232]
### 🐛 Describe the bug

There is a bug about **query**, **key** and **value** in Transforme_conv. According to the formula, `alpha` is calculated by `query_i `and `key_j`, which means **key** should be sorted by index and `query` should be repeated `n-1` times of node `i`. In addition, `value_j` also should be sorted by index.

However, when I print it in the `message module` like this：
```
    def message(self, query_i: Tensor, key_j: Tensor, value_j: Tensor,
                edge_attr: OptTensor, index: Tensor, ptr: OptTensor,
                size_i: Optional[int]) -> Tensor:

        if self.lin_edge is not None:
            assert edge_attr is not None
            edge_attr = self.lin_edge(edge_attr).view(-1, self.heads,
                                                      self.out_channels)
            key_j += edge_attr
        for i in range(len(query_i)):
            temp_file = 'query_' + str(i) + ':'
            print(temp_file,query_i[i,:,0])
        alpha = (query_i * key_j).sum(dim=-1) / math.sqrt(self.out_channels)
        alpha = softmax(alpha, index, ptr, size_i)
        self._alpha = alpha
        alpha = F.dropout(alpha, p=self.dropout, training=self.training)
```
It shows the opposite of what I understand. The result is shown below:

```
query_i:
query_0: tensor([0.0022], device='cuda:0', grad_fn=<SelectBackward0>)
query_1: tensor([0.0629], device='cuda:0', grad_fn=<SelectBackward0>)
query_2: tensor([-0.1268], device='cuda:0', grad_fn=<SelectBackward0>)
query_3: tensor([0.0629], device='cuda:0', grad_fn=<SelectBackward0>)
query_4: tensor([-0.1268], device='cuda:0', grad_fn=<SelectBackward0>)
query_5: tensor([0.0022], device='cuda:0', grad_fn=<SelectBackward0>)

key_j:
key_0: tensor([-0.1309], device='cuda:0', grad_fn=<SelectBackward0>)
key_1: tensor([-0.1309], device='cuda:0', grad_fn=<SelectBackward0>)
key_2: tensor([-0.1215], device='cuda:0', grad_fn=<SelectBackward0>)
key_3: tensor([-0.1215], device='cuda:0', grad_fn=<SelectBackward0>)
key_4: tensor([-0.0779], device='cuda:0', grad_fn=<SelectBackward0>)
key_5: tensor([-0.0779], device='cuda:0', grad_fn=<SelectBackward0>)

value_j:
value_0: tensor([-0.0897], device='cuda:0', grad_fn=<SelectBackward0>)
value_1: tensor([-0.0897], device='cuda:0', grad_fn=<SelectBackward0>)
value_2: tensor([0.0788], device='cuda:0', grad_fn=<SelectBackward0>)
value_3: tensor([0.0788], device='cuda:0', grad_fn=<SelectBackward0>)
value_4: tensor([0.2025], device='cuda:0', grad_fn=<SelectBackward0>)
value_5: tensor([0.2025], device='cuda:0', grad_fn=<SelectBackward0>)
```

So is this a misunderstanding or is it really a bug？

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10.0
* OS: Ubuntu 20.04
* Python version: 3.9.0

**Comment by rusty1s** [comment]
Can you also show the output of `index` (`print(index)`)? The interpretation of `query_i` and `key_j` values depend on it.

**Comment by sixu0** [comment]
The output of index is like this:
`tensor([ 1,  2, 0, 2, 0, 1], device='cuda:0') `

Beside, my edge_index is a [2,n] shape matrix and sorted by node 0 *_j  and node 1 *_j...., like this:
`tensor([[ 0,  0, 1, 1, 2, 2],[1, 2, 0, 2, 0, 1]], device='cuda:0')`

**Comment by rusty1s** [comment]
Thanks. I think there might be a misunderstanding. `_i` denotes the central node index (the node to which we aggregate), and `_j` denote the neighbors. As such, it's actually the reverse: `query` is sorted by index.

**Comment by sixu0** [comment]
Thanks for you reply. I also have a question. if under this rule, you mean that the `value_i` also denotes the node index. However, I think the `alpha` should multiple the neighbors before the aggregate and then add their own node parts (multiple with `W1`) after the aggregate.

**Comment by rusty1s** [comment]
The addition of central node features happens after message passing is done, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/transformer_conv.py#L187-L194). `value_i` (the values of central node features) is not needed, we only need `query_i` to calculate `alpha`. Let me know if that helps!

**Comment by sixu0** [comment]
Oh, I'm sorry that you misunderstood my question due to my inappropriate description. According to this [formula,](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.TransformerConv) the `alpha` should multiple the neighbors' node features (`value_i`) before the aggregate in [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/transformer_conv.py#L220-L225). However, according to our discussion above, I think the `value_i` denotes the central node features. I think there might be a misunderstanding or a bug. Could you help me to understand it? Thanks!

**Comment by rusty1s** [comment]
Ah, I get your point. The documentation does not specify the key, query and value relation, so it might be best to think of it as:
```
value_j = W_2 @ x_j
query_i = W_3 @ x_i
key_j = W_4 @ x_j
```
As you can see, there is no need to compute `value_i`.

**Comment by sixu0** [comment]
Yep.  However, according to the output above, I think in this version code:  

`value_j` is calculated by `W_2 @ x_i` rather than `W_2 @ x_j`

**Comment by sixu0** [comment]
In the other words, in this version code, the relation of key, query, and value is in a trouble like this
`
value_j = W_2 @ x_i
query_i = W_3 @ x_j
key_j = W_4 @ x_i
`

**Comment by rusty1s** [comment]
I'm not sure I understand. `value` is computed via `W_2 @ x`, and is then accessed via `value_j` in `message` (the features of neighbors).

**Comment by sixu0** [comment]
I will explain my problem in as much detail as possible. For example, we set a graph that has 7 nodes and 49 edges (each node connects with other nodes) as the input into the transform_conv and the index of nodes is 1,2,3,4,5,6 and 7.

In propagate function, the shape of `x_i` and `x_j` would be [42 * features]. Thus, the index of `x_i` (denotes the central node index) would be like this:
```
1 1 1 1 1 1
2 2 2 2 2 2 
3 3 3 3 3 3
4 4 4 4 4 4
5 5 5 5 5 5
6 6 6 6 6 6
7 7 7 7 7 7 
```
while the index of `x_j` (denote the neighbors) would be like this:
```
2 3 4 5 6 7
1 3 4 5 6 7 
1 2 4 5 6 7 
1 2 3 5 6 7
1 2 3 4 6 7
1 2 3 4 5 7
1 2 3 4 5 6
```
Then, the `key`, `query` and `value` are calculated by: 
```
value_j = W_2 @ x_j
query_i = W_3 @ x_i
key_j = W_4 @ x_j
```

To improve efficiency and save memory, the `key`, `query` and `value` are calculated before input to the propagate function and the shape of them [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/transformer_conv.py#L171-L173) is [7 * features]. During input to the message passing (here), `key_j`, `query_i` and `value_j` are copied by `key`, `query` and `value`, respectively. Therefore, the index of `key_j` and `value_j` is the same as that in `x_j` like this:
```
2 3 4 5 6 7
1 3 4 5 6 7 
1 2 4 5 6 7 
1 2 3 5 6 7
1 2 3 4 6 7
1 2 3 4 5 7
1 2 3 4 5 6
```
while the index of `query_i` is the same as that in `x_i` like this:
```
1 1 1 1 1 1
2 2 2 2 2 2 
3 3 3 3 3 3
4 4 4 4 4 4
5 5 5 5 5 5
6 6 6 6 6 6
7 7 7 7 7 7 
```
Then, we can use `key_j` and `query_i` to calculate the `alpha` and then multiply `alpha` by `value_j` to get the output of the message passing function. Finally, because the shape of `value_j` is [42 * features], we aggregate it by this rule:
```
2 3 4 5 6 7 --> node1
1 3 4 5 6 7 --> node2
1 2 4 5 6 7 --> node3
1 2 3 5 6 7 --> node4
1 2 3 4 6 7 --> node5
1 2 3 4 5 7 --> node6
1 2 3 4 5 6 --> node7
```
The description above is my understanding of Transformer_conv. I think that might be correct. 

However, according to my test, the bug might occur [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/transformer_conv.py#L176-L177). The input and repeat process cause some error of `value_i`. If you print the `value_j` here, you can find the index of it is not the same as `x_j`. The index of it is the same as the `x_i` like this
```
1 1 1 1 1 1
2 2 2 2 2 2 
3 3 3 3 3 3
4 4 4 4 4 4
5 5 5 5 5 5
6 6 6 6 6 6
7 7 7 7 7 7 
```
I think we cannot use this kind of `value_j` to aggregate the correct result. I think this description would help you to understand my question and test it [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/transformer_conv.py#L220). Thanks for your patient reply!

**Comment by sixu0** [comment]
Oh! I found it matches your description. I totally understand it now. Thanks for your patient reply again!
