### ISSUE TITLE
Conda install PyG with cuda 11.3 will download a cu115 version pytorch-scatter

### ISSUE THREAD

**Issue by yaox12** [pyg-team/pytorch_geometric#4256]
### 😵 Describe the installation problem

When I use conda to install pyg with pytorch 1.10 and cuda 11.3, it downloads the cu115 version pytorch-scatter.
The installing command I use:
```bash
conda install pytorch=1.10 cudatoolkit=11.3 pyg -c pytorch -c pyg -c conda-forge
```
![image](https://user-images.githubusercontent.com/3831900/158101120-28e5fb47-06e4-4a2b-9071-82a2962695d2.png)

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.10.2
* OS: Ubuntu 20.04
* Python version: 3.8
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. I think I found the error and re-build `pytorch-scatter` for conda. Can you check once again? :)

**Comment by yaox12** [comment]
Seems fixed. Thanks.
