### ISSUE TITLE
Modelling different part of the graph with different weights

### ISSUE THREAD

**Issue by zc-alexfan** [pyg-team/pytorch_geometric#428]
## ❓ Questions & Help

Hi, 

I am trying to implement a `GCNConv` model that learns different `GCNConv` weights at different parts of the graph. For example, consider each `Data` is a graph that looks like: 

![](https://laurentlessard.com/bookproofs/wp-content/uploads/2018/10/archipelago1.png). 

I would like to perform `GCNConv` operations on the **three** sub-graphs: `{A, B, C, D}`, `{D, F}`, `{D, E, G, H, I}` where each subgraph use independent `GCNConv` weights. Note: the node `D` is shared among subgraphs. 

My current strategy is to create three `GCNConv` layers and keep three separate `edge_index`. However, the three `GCNConv` operations have to run sequentially (thus, slow), and keeping track of three `edge_index` doesn't seem to be elegant. 

What would be the best way to approaching this?

**Comment by rusty1s** [comment]
Hi, You could create an additional tensor `edge_type` holding indices that mark the weights to use for aggregation. You can either create a new GCNConv which makes use of this additional argument and applies the linear layer in the message function, or simply use the RGCN which should already do this.
