### ISSUE TITLE
extend line length to 120

### ISSUE THREAD

**Issue by Borda** [pyg-team/pytorch_geometric#4288]
### 🛠 Proposed Refactor

I would update the YAPF an Isort formating to use 120 line length which is nowadays standard... the default 80 is too restrictive and eve GH web UI is fine with 120 chars per line :+1: 

### Suggest a potential alternative/fix

If you are fine with it I am happy to send this config change and then let pre-commit to execute the update :rabbit: 

```
[yapf]
COLUMN_LIMIT=120

[isort]
...
line_length = 120

[flake8]
...
max-line-length = 120
```

Also, happy to send a PR if you agree with it... :rabbit:

**Comment by rusty1s** [comment]
Actually, I prefer the 80 line length limit and am in favor of keeping it:
* It leaves space for putting two versions side by side for comparison (even on a laptop)
* It limits the complexity of a single line by enforcing that we are not composing too many functions in a single line
* I absolutely hate vertical scrolling or breaking lines

**Comment by Borda** [comment]
btw, a bit off-topic, how about Isort formatting when long imports are on separate lines?
https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html
My preference is for option 3 :rabbit:

**Comment by rusty1s** [comment]
I personally like both option 0 and 3. If you feel so strongly about it, feel free to send a PR to see how it looks like in practice :)
