### ISSUE TITLE
move lints to pre-commit

### ISSUE THREAD

**Issue by Borda** [pyg-team/pytorch_geometric#4289]
### 🛠 Proposed Refactor

I would suggest moving most of the extra linting from https://github.com/pyg-team/pytorch_geometric/blob/master/.github/workflows/linting.yml
to recommit as you already use the bot and set the check as mandatory :rabbit: 

### Suggest a potential alternative/fix

check that can be safely moved to pre-commit:
- [flake8](https://flake8.pycqa.org/en/latest/user/using-hooks.html)
- [yamllint](https://yamllint.readthedocs.io/en/stable/integration.html)
- sort - it is already there
- [pylint](https://pylint.pycqa.org/en/latest/user_guide/pre-commit-integration.html)
- [pyroma](https://github.com/regebro/pyroma#version-control-integration)

Also, happy to send a PR if you agree with it... :rabbit:

**Comment by rusty1s** [comment]
Thanks for this issue. Do you mean that we also add the linter to `pre-commit` in addition to our auto-formatter? I would be happy to accept such a PR :)

**Comment by Borda** [comment]
Yes, I would move there all except `mypy` and this is a bit time-consuming some it is fine to keep it aside.... :rabbit:

**Comment by rusty1s** [comment]
It would be great to skip both `mypy` and `pylint` for now since neither of them are enforced right now.
