### ISSUE TITLE
Incorrect Conversion To Networkx Graph with the flag to_undirected=True

### ISSUE THREAD

**Issue by meloncolie** [pyg-team/pytorch_geometric#4294]
### 🐛 Describe the bug

The function to_networkx drops edge (i, j) if i < j when the flag to_undirected is True

```python
>>> x = torch.zeros([4]).long()
>>> edge_index = torch.Tensor([[0, 0, 2, 2, 2], [1, 3, 0, 1, 3]]).long()
>>> data = Data(x, edge_index)
>>> G = to_networkx(data, to_undirected=True)
>>> G.edges
EdgeView([(0, 2), (1, 2)])
```

This problem might be caused by this paragraph:
https://github.com/pyg-team/pytorch_geometric/blob/57c88c0c7b86fb38715b72f5914bb208c7aa11e7/torch_geometric/utils/convert.py#L101

This problem is difficult to be detected, however, it may cause the incorrect building of subgraphs and more catastrophic results. A Data with asymmetric edge_index is supposed to be automatically converted to symmetric (call to_undirected in to_networkx) or simply raise an error.

### Environment

PyG version: until the latest version 2.0.3
PyTorch version: 1.7.1
OS: MacOS\CentOS
Python version: 3.8.12\3.6.8
CUDA/cuDNN version: CPU
How you installed PyTorch and PyG (conda, pip, source): PyTorch with conda, PyG with pip
Any other relevant information (e.g., version of torch-scatter):
torch-cluster 1.5.9
torch-scatter 2.0.7
torch-sparse 0.6.12
torch-spline-conv 1.2.1

**Comment by rusty1s** [comment]
Can you upgrade to PyG 2.0.4? This should have been already fixed (see https://github.com/pyg-team/pytorch_geometric/issues/3873). The output for me is:
```
[(0, 1), (0, 3), (2, 3)]
```

**Comment by meloncolie** [comment]
> Can you upgrade to PyG 2.0.4? This should have been already fixed (see #3873). The output for me is:
> 
> ```
> [(0, 1), (0, 3), (2, 3)]
> ```

The output is supposed to be
```python
[(0, 1), (0, 2), (0, 3), (1, 2), (2, 3)]
```

**Comment by rusty1s** [comment]
Oh, sorry for being too fast on this one. You are right that it is hard to detect and it may involve a `to_undirected` call on the PyG `data` object first. To fix this, one can always apply the `to_undirected` call by yourself beforehand. Let me know if you have any interest in fixing this directly in PyG :)

**Comment by meloncolie** [comment]
> Oh, sorry for being too fast on this one. You are right that it is hard to detect and it may involve a `to_undirected` call on the PyG `data` object first. To fix this, one can always apply the `to_undirected` call on its own beforehand. Nonetheless, I feel we should fix this since it also makes the interface nicer. Let me know if you have any interest in fixing this directly in PyG :)

Yes, As a KG researcher, It's my honor to contribute to this Programm ^_^

**Comment by rusty1s** [comment]
Super. Let me know how it goes :)
