### ISSUE TITLE
RECT no related configuration！ Please help me！！

### ISSUE THREAD

**Issue by Jinn02-25** [pyg-team/pytorch_geometric#4303]
### 🐛 Describe the bug

Hello author, when I ran RECT training, I got the following prompts that I don't know how to solve. I would like to ask what is your environment configuration！！Thankyou!!!

‘’‘
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.13.0 -- An enhanced Interactive Python.

Populating the interactive namespace from numpy and matplotlib

runfile('C:/Users/DELL/Desktop/My exp2/Cora/Cora_RECT/Cora_rect.py', wdir='C:/Users/DELL/Desktop/My exp2/Cora/Cora_RECT')
Traceback (most recent call last):

  File "C:\Users\DELL\Desktop\My exp2\Cora\Cora_RECT\Cora_rect.py", line 17, in <module>
    from torch_geometric.nn import RECT_L

ImportError: cannot import name 'RECT_L' from 'torch_geometric.nn' (C:\Users\DELL\Anaconda3\envs\pytorch\lib\site-packages\torch_geometric\nn\__init__.py)
’‘’

### Environment

* PyG version:1.4.3
* PyTorch version:1.5.0
* OS:win10
* Python version:3.7.4
* CUDA/cuDNN version:10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
*torch                     1.5.0                     <pip>
torch-cluster             1.5.5                     <pip>
torch-geometric           1.4.3                     <pip>
torch-scatter             2.0.5                     <pip>
torch-sparse              0.6.6                     <pip>
torch-sparse              0.6.4                     <pip>
torch-spline-conv         1.2.0                     <pip>
torchvision               0.6.0                     <pip>

**Comment by rusty1s** [comment]
The `RECT` model was added to PyG in version `torch-geometric==2.0.0`, see [here](https://github.com/pyg-team/pytorch_geometric/releases/tag/2.0.0).

**Comment by Jinn02-25** [comment]
Ok thanks！！！
