### ISSUE TITLE
SparseTensor Sampling problems

### ISSUE THREAD

**Issue by nt1tov** [pyg-team/pytorch_geometric#4319]
### 🐛 Describe the bug

As I mentioned in [PyG discussion](https://github.com/pyg-team/pytorch_geometric/discussions/4317)

when I run this code snippet:
```
import copy
import os.path as osp

import torch
import torch.nn.functional as F
from tqdm import tqdm

from torch_geometric.datasets import Reddit
from torch_geometric.loader import NeighborLoader

import torch_geometric.transforms as T

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'Reddit')
dataset = Reddit(path, transform=T.ToSparseTensor())


# Already send node features/labels to GPU for faster access during sampling:
data = dataset[0].to(device, 'x', 'y')

kwargs = {'batch_size': 1024, 'num_workers': 6, 'persistent_workers': True}
train_loader = NeighborLoader(data, input_nodes=data.train_mask,
                              num_neighbors=[5, 2], shuffle=True, **kwargs)

batch = next(iter(train_loader))
rptr, col, v = batch.adj_t.csr()
print(batch.x.shape)
print(rptr.size(0))

```

I got those output:
```
torch.Size([14307, 602])
232966
```

Hence, if I want to run `method` from `torch_sparse` library I will get dimensions mismatch -- my sampled features have **14307** but `rowptr` tensor size is **232906** with a lot of zeros which should be pruned. 

As a result, if you want to run GraphSAGE model with large samples you will be faced with this issue(on backward pass too), and not be able to train your network.

### Environment

* PyG version:  2.0.3
* PyTorch version: 1.10.2+cu113
* OS:  Ubuntu 16.4
* Python version: 3.6
* CUDA/cuDNN version: 11.6     
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
    torch-scatter                 2.0.9
    torch-sparse                  0.6.12

**Comment by rusty1s** [comment]
Thank you! I just fixed it in https://github.com/pyg-team/pytorch_geometric/pull/4320.
