### ISSUE TITLE
Expose the `cosine` and `num_workers` parameters in `transforms.KNNGraph`

### ISSUE THREAD

**Issue by chenzhekl** [pyg-team/pytorch_geometric#4339]
### 🚀 The feature, motivation and pitch

Expose the `cosine` and `num_workers` parameters in `transforms.KNNGraph`.

### Alternatives

Implement my custom `transforms.KNNGraph` transformation.

**Comment by rusty1s** [comment]
Indeed :) Fixed in https://github.com/pyg-team/pytorch_geometric/pull/4344.
