### ISSUE TITLE
Graphgym config dump location

### ISSUE THREAD

**Issue by RemyLau** [pyg-team/pytorch_geometric#4359]
### 🐛 Describe the bug

The changes made in #4338 seems to introduce an unwanted behavior of storing config file in the root directory.

I have a config file ``example_config.yaml``, and the output directory is set to ``out_dir: result``.

Previously, the output generated looked something like:
```txt
result
`-- example_config
    |-- 0
    |   |-- train
    |   |-- val
    |   |-- test
    |   `-- logging.log
    |-- 1
    |   |-- train
    |   |-- val
    |   |-- test
    |   `-- logging.log
    `-- config.yaml
```

After the changes made in #4338, the output directory looks something like:
```txt
result
|-- config.yaml
`-- example_config
    |-- 0
    |   |-- train
    |   |-- val
    |   |-- test
    |   `-- logging.log
    `-- 1
        |-- train
        |-- val
        |-- test
        `-- logging.log
```

### Question
Was it intentional to pull the ``config.yaml`` out of ``example_config`` and place it under ``result/``? If so, I'm a little bit confused by this setup. Is the use case then have for example another ``example_config2`` output the results to ``result/`` and then share the same ``config.yaml`` (which does not quite make sense)?

### Environment

* PyG version: Latest
* PyTorch version: 1.11.0
* OS: CentOS
* Python version: 3.9.7
* CUDA/cuDNN version: 10.2.89
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by RemyLau** [comment]
@JiaxuanYou thank you for your timely response! I think I have found the issue: I have my own version of the ``main.py`` script, but for some reason, I messed up the order in which functions are called. Instead of calling ``set_out_dir`` before ``dump_cfg``, I did the opposite, causing the issue here. Sorry for causing any confusion here, and I appreciate your help! I think I'm all set for this specific issue, so closing it now.

Having said that, if the order in which the setup functions are called is crucial, would it be a good idea to add some sort of checks or warnings to the user that they are not calling the functions in the right order?

**Comment by JiaxuanYou** [comment]
Sounds good! And yes, this is a good suggestion. I think in the future we will pack things into a `Trainer` object, so that you won't need to worry about maintaining your own `main.py`. I'll let you know when we are able to make progress there.
