### ISSUE TITLE
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

### ISSUE THREAD

**Issue by SyounenZ** [pyg-team/pytorch_geometric#4378]
### 🐛 Describe the bug

code:
from torch_geometric.datasets import KarateClub
dataset = KarateClub()

bug:
Traceback (most recent call last):
  File "F:\study\python\test\test4pyg.py", line 2, in <module>
    dataset = KarateClub()
  File "F:\anaconda\envs\ai\lib\site-packages\torch_geometric\datasets\karate.py", line 50, in __init__
    adj = nx.to_scipy_sparse_array(G).tocoo()
  File "F:\anaconda\envs\ai\lib\site-packages\networkx\convert_matrix.py", line 921, in to_scipy_sparse_array
    A = sp.sparse.coo_array((d, (r, c)), shape=(nlen, nlen), dtype=dtype)
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

### Environment

* PyG version:2.0.4
* PyTorch versn:1.10.1
* OS:windows10
* Python version:3.9.7
* CUDA/cuDNN version:CU113
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):
* pytorch-scatter:2.0.9
* pytorch-sparse:0.6.13
* pytorch-spline-conv:1.2.1
* pytorch-cluster:1.6.0

**Comment by rusty1s** [comment]
Looks like this is a version conflict between `networkx` and `scipy`. Can you upgrade both to see if this resolves your issues?

**Comment by SyounenZ** [comment]
it does work! Thanks!

**Comment by Godofnothing** [comment]
`coo_array` appears only in script version `1.8.0`

**Comment by judamace** [comment]
I downgraded to scipy version 1.8 and downgraded networkx but I am still getting module 'scipy.sparse' has no attribute 'coo_array'. Could you please confirm the version of networkx that you downgraded to? Thank you!

**Comment by judamace** [comment]
> it does work! Thanks!

I downgraded to scipy version 1.8 and downgraded networkx but I am still getting module 'scipy.sparse' has no attribute 'coo_array'. Could you please confirm the version of networkx that you downgraded to? Thank you!

**Comment by lfcc1** [comment]
I'm having the same problem, already upgraded both versions but still getting the same error..
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

**Comment by SyounenZ** [comment]
i'm a greenhand to use pyg, so i can't solve this problem.


maybe you can try update all related module, and this is my version

pytorch-scatter:2.0.9

pytorch-sparse:0.6.13

pytorch-spline-conv:1.2.1

pytorch-cluster:1.6.0

Python version:3.9.7

PyTorch versn:1.10.1

PyG version:2.0.4

scipy:1.8.0

networkx:2.7.1






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyg-team/pytorch_geometric"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月23日(星期六) 晚上11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyg-team/pytorch_geometric] AttributeError: module 'scipy.sparse' has no attribute 'coo_array' (Issue #4378)





 
I'm having the same problem, already upgraded both versions but still getting the same error..
 AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

**Comment by rusty1s** [comment]
I am not really sure why this happen to you, but it should be fixed in PyG master. Can you try to do:
```
pip uninstall torch-geometric
pip install pyg-nightly
```

**Comment by SyounenZ** [comment]
I'm sorry, I'm afraid I'll have the same problem as you.
I install pyg via anaconda, it's really simple.
I think you can try to install pyg via anaconda..




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyg-team/pytorch_geometric"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyg-team/pytorch_geometric] AttributeError: module 'scipy.sparse' has no attribute 'coo_array' (Issue #4378)





 
I am not really sure why this happen to you, but it should be fixed in PyG master. Can you try to do:
 pip uninstall torch-geometric pip install pyg-nightly

**Comment by absent1353** [comment]
same error，AttributeError: module 'scipy.sparse' has no attribute 'coo_array'，scipy1.8.0，networkx 2.8

**Comment by rusty1s** [comment]
You can either upgrade PyG to use `pyg-nightly` (see above), or try to downgrade `networkx` to 2.7.

**Comment by david-AH** [comment]
Same error.  Using pyg-nightly and networkx 2.7.1

**Comment by lfcc1** [comment]
I upgraded networkx and scipy, restarted vscode (powershell) and now it works.

**Comment by decanbay** [comment]
Upgrading the networkx caused the same problem.
These ones solved the problem for me
scipy==1.8.0
networkx==2.6

**Comment by ayanatherate** [comment]
> Upgrading the networkx caused the same problem. These ones solved the problem for me scipy==1.8.0 networkx==2.6

Thanks! This works totally!

**Comment by rradhai** [comment]
networkx 2.8.6
scipy 1.7.3
the same error 'AttributeError: module 'scipy.sparse' has no attribute 'coo_array'
please help!!

**Comment by kakkapriyesh** [comment]
For me conda couldnt update to correct version but this works:

`pip install --upgrade scipy networkx `

**Comment by Giuva-Sergi** [comment]
Hi everyone, I tried to upgrade scipy and networkx to the latest version inside of my virtual environment, but it still doesn't work. Does somebody know why?

**Comment by SyounenZ** [comment]
my networkx version is 2.7.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyg-team/pytorch_geometric"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 凌晨3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyg-team/pytorch_geometric] AttributeError: module 'scipy.sparse' has no attribute 'coo_array' (Issue #4378)





  
it does work! Thanks!
  
I downgraded to scipy version 1.8 and downgraded networkx but I am still getting module 'scipy.sparse' has no attribute 'coo_array'. Could you please confirm the version of networkx that you downgraded to? Thank you!

**Comment by VijayJia** [comment]
> Upgrading the networkx caused the same problem. These ones solved the problem for me scipy==1.8.0 networkx==2.6

Thanks for your share!!!

**Comment by anindya-dey** [comment]
I was using Google Colab when I encountered this problem. After going through all the suggestions, I executed the following to resolve the issue:

```
!pip install --upgrade scipy networkx
```

**Comment by dharrypotter** [comment]
> I was calculating the `network.pagerank` of a graph on Google Colab when I encountered this problem. After going through all the suggestions, I executed the following to resolve the issue:
> 
> ```
> !pip install --upgrade scipy networkx
> ```

I tried this but still shows the same error. Can anyone suggest something that works? (My networkX version = 3.0 , scipy = 1.10)

**Comment by decanbay** [comment]
> > I was calculating the `network.pagerank` of a graph on Google Colab when I encountered this problem. After going through all the suggestions, I executed the following to resolve the issue:
> > ```
> > !pip install --upgrade scipy networkx
> > ```
> 
> I tried this but still shows the same error. Can anyone suggest something that works? (My networkX version = 3.0 , scipy = 1.10)

try scipy==1.8.0 and networkx==2.6

**Comment by ToufikBenmessabih** [comment]
> > I was calculating the `network.pagerank` of a graph on Google Colab when I encountered this problem. After going through all the suggestions, I executed the following to resolve the issue:
> > ```
> > !pip install --upgrade scipy networkx
> > ```
> 
> I tried this but still shows the same error. Can anyone suggest something that works? (My networkX version = 3.0 , scipy = 1.10)

same issue, i tried scipy==1.8.0 and networkx==2.6 and still same problem.

**Comment by decanbay** [comment]
> 



> > > I was calculating the `network.pagerank` of a graph on Google Colab when I encountered this problem. After going through all the suggestions, I executed the following to resolve the issue:
> > > ```
> > > !pip install --upgrade scipy networkx
> > > ```
> > 
> > 
> > I tried this but still shows the same error. Can anyone suggest something that works? (My networkX version = 3.0 , scipy = 1.10)
> 
> same issue, i tried scipy==1.8.0 and networkx==2.6 and still same problem.

scipy==1.8.1 and networkx==3.0 is also working in my case, could you confirm that you really have the correct versions? 'conda list scipy' and 'conda list networkx' should give you version numbers

**Comment by ServoCryptid** [comment]
Tried scipy==1.8.1 and networkx==3.0, I'm still getting the same error

**Comment by ServoCryptid** [comment]
> > 
> 
> > > > I was calculating the `network.pagerank` of a graph on Google Colab when I encountered this problem. After going through all the suggestions, I executed the following to resolve the issue:
> > > > ```
> > > > !pip install --upgrade scipy networkx
> > > > ```
> > > 
> > > 
> > > I tried this but still shows the same error. Can anyone suggest something that works? (My networkX version = 3.0 , scipy = 1.10)
> > 
> > 
> > same issue, i tried scipy==1.8.0 and networkx==2.6 and still same problem.
> 
> scipy==1.8.1 and networkx==3.0 is also working in my case, could you confirm that you really have the correct versions? 'conda list scipy' and 'conda list networkx' should give you version numbers

Tried with scipy==1.8.1 and networkx==3.0, I'm still getting the same error

**Comment by elalex22** [comment]
i have done that too and i have the same error
