### ISSUE TITLE
In `negative_sampling`, assert captures an exception condition

### ISSUE THREAD

**Issue by fierval** [pyg-team/pytorch_geometric#4382]
### 🐛 Describe the bug

Not the highest priority, but...

`negative_sampling` function has an assert (negative_sampling.py line 52: `assert idx.numel() < population, ("No negative edges to sample")`

This assert should be removed and replaced with either an exception or an empty `edge_index` returned. Otherwise `negative_sampling` cannot really be used without being wrapped into  `try/except` for `AssertionError`.

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10
* OS: Windows / Linux
* Python version: 3.9
* CUDA/cuDNN version: 3.13
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. This is fixed in #4383.
