### ISSUE TITLE
libc++abi: terminating with uncaught exception of type std::length_error: vector

### ISSUE THREAD

**Issue by yezhuoyang** [pyg-team/pytorch_geometric#4419]
### 😵 Describe the installation problem

Hi guys! I've installed "torch_geometric" on my MAC OS, but when I import it in python code, a c++ error occurs as following:

> libc++abi: terminating with uncaught exception of type std::length_error: vector
fish: Job 1, 'python3' terminated by signal SIGABRT (Abort)

I've installed all related package by pip install. And the error seems to be caused by the dynamic C++ library torch_geometric linked to but I cannot figure out why. 

### Environment

* PyG version:pyg-nightly-2.0.5.dev20220405.tar.gz
* PyTorch version:1.11.0
* OS:MAC
* Python version:3.9.7
* CUDA/cuDNN version: No cuda
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): 2.0.9

**Comment by rusty1s** [comment]
I've never encountered this issue. Does it only apply to the nightly release of PyG, or for `torch-geometric==2.0.4` as well? Can you share some information about how you tried to install PyG? Does the same issue happen in case you install it in a fresh miniconda environment?

**Comment by arunppsg** [comment]
Is it the arm64 mac? sometimes it returns weird errors.

**Comment by yezhuoyang** [comment]
> Is it the arm64 mac? sometimes it returns weird errors.
Thanks for reply! 
My mac uses a 6-core Intel Core I7 processor.
<img width="586" alt="Screen Shot 2022-04-07 at 2 28 10 PM" src="https://user-images.githubusercontent.com/34168020/162134858-fcd20b0c-d0d4-446b-aca1-92e2bee2d366.png">

**Comment by yezhuoyang** [comment]
> I've never encountered this issue. Does it only apply to the nightly release of PyG or to `torch-geometric==2.0.4` as well? Can you share some information about how you tried to install PyG? Does the same issue happen in case you install it in a fresh miniconda environment?

I use the command `pip install torch-geometric` first(On my system directly). And the error happens whenever I try to import torch_geometric

<img width="1029" alt="Screen Shot 2022-04-07 at 2 41 27 PM" src="https://user-images.githubusercontent.com/34168020/162136249-58110c48-b9f0-46b4-8a99-52750b41b740.png">


Then, I uninstall the package by `pip uninstall torch-geometric`. 

I run the command according to the following page ,  where I choose Pytorch 1.11.*, Mac, Pip, Cpu  
https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

`pip3 install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html`

However, the error still remains.

**Comment by rusty1s** [comment]
Can you show me the output of `which python3`? Do you use the system-wide Python? It might be a good idea to install miniconda and try again. Let me know!

**Comment by yezhuoyang** [comment]
> Can you show me the output of `which python3`? Do you use the system-wide Python? It might be a good idea to install miniconda and try again. Let me know!

Install miniconda is a great suggestion and solve my problem.
I create a conda virtual environment myvenv, activate myenv, and then use conda install command
`conda install pyg -c pyg`.
Then the import works fine!

However, when I deactivate conda, the problem is still there.
As you can see in the fowllowing:
<img width="1181" alt="Screen Shot 2022-04-07 at 5 00 35 PM" src="https://user-images.githubusercontent.com/34168020/162162474-a7b90359-e817-4083-ba40-ff9f4faa5ee5.png">

**Comment by mysakbm** [comment]
I have the very same problem with importing torch vision.
I'm on the most updated MacBook M1, Monterey, latest update, fresh instalation. Python 3.9.12.

**Comment by rusty1s** [comment]
@yezhuoyang I think it is good practice to work in personal environments. Glad that it is resolved!

@mysakbm What's the problem with `torchvision`? It might be best to ask for help directly in `pytorch/vision` repo.

**Comment by jtduran** [comment]
I have an M1 mac  running only miniconda (for the arm natively compiled stuff )  where everything works fine and I have an i9 mac running regular conda  where I get the same error, tried adding miniconda and switching to that got same error, guessing I need to nuke the whole conda install which I don't want to do.  I will go with the M1 I guess. 
libc++abi: terminating with uncaught exception of type std::length_error: vector

**Comment by mnbucher** [comment]
can confirm that using venv (or conda) resolved the issue for me as well.

**Comment by 21S003018** [comment]
I have exactly the same problem! I solved it by uninstall all the depencies: torch-sparse\scatter\cluster\spline-conv. And re-install with `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html`.

**Comment by ruandocini** [comment]
Just had the same problem, it worked here.

**Comment by ruandocini** [comment]
I used the solutions presented here but It did not work.
If this happens to anyone, I used this to fix my problem -> #https://github.com/rusty1s/pytorch_scatter/issues/241

**Comment by zzyzeyuan** [comment]
> I have exactly the same problem! I solved it by uninstall all the depencies: torch-sparse\scatter\cluster\spline-conv. And re-install with `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html`.

It does work!  very helpful!

**Comment by limitless-insanity** [comment]
**I know it's strange but I got this while not doing anything with python whatsoever. this is the c++ program:**

`#include <iostream>
#include <algorithm>
#include <vector>
#include <limits.h>
using namespace std;

vector<int> MinimumCoins(int n)
{
    int arr[] = {10, 20, 30};
    int k = sizeof(arr) / sizeof(arr[0]);
    vector<int> coinValues(arr, arr + k);
    int numCoins = coinValues.size();
    vector<int> result;

    vector<int> dp(n + 1, INT_MAX);
    dp[0] = 0;

    vector<int> lastCoin(n + 1, -1);
    for (int i; i <= n; i++)
    {
        for (int j = 0; j <= numCoins; j++)
        {
            if (coinValues[j] <= i && dp[i - coinValues[j]] + 1 < dp[i])
            {
                dp[i] = dp[i - coinValues[j]] + 1;
                lastCoin[i] = j;
            }
        }
    }
    if (dp[n] == INT_MAX)
        return result;

    int current = n;
    while (current > 0)
    {
        int coinIndex = lastCoin[current];
        result.push_back(coinValues[coinIndex]);
        current -= coinValues[coinIndex];
    }
    sort(result.begin(), result.end(), greater<int>());
    for (int i = 0; i < result.size(); i++)
    {
        cout << result[i] << " ";
    }
    return result;
}

int main()
{
    int n = -13;

    vector<int> result = MinimumCoins(n);
    if (result.empty())
    {
        cout << "-1";
    }
    else
    {
        sort(result.begin(), result.end(), greater<int>());
        for (int i = 0; i < result.size(); i++)
        {
            cout << result[i] << " ";
        }
    }
    return 0;
}

`
its a basic program of Dsa...

and now this is the error:
`libc++abi: terminating due to uncaught exception of type std::length_error: vector
/bin/sh: line 1: 22734 Abort trap: 6 `

I am using c++11 to compile in Mac m1.
can anybody help??
