### ISSUE TITLE
Heterogenious graph learning example is not reproducable

### ISSUE THREAD

**Issue by blokhinnv** [pyg-team/pytorch_geometric#4421]
### 🐛 Describe the bug

I'm trying to reproduce the example from [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html#automatically-converting-gnn-models). I far as I can see it's almost the same code as in [your examples folder](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/to_hetero_mag.py).

Here is the code:
```python
import argparse
import os.path as osp

import torch
import torch.nn.functional as F
from torch.nn import ReLU
from tqdm import tqdm

import torch_geometric.transforms as T
from torch_geometric.datasets import OGB_MAG
from torch_geometric.loader import HGTLoader, NeighborLoader
from torch_geometric.nn import Linear, SAGEConv, Sequential, to_hetero



device = torch.device('cpu')


transform = T.ToUndirected(merge=True)
dataset = OGB_MAG('./tmp', transform=transform)

# Already send node features/labels to GPU for faster access during sampling:
data = dataset[0].to(device, 'x', 'y')

train_input_nodes = ('paper', data['paper'].train_mask)
val_input_nodes = ('paper', data['paper'].val_mask)
kwargs = {'batch_size': 1024, 'num_workers': 6, 'persistent_workers': True}


train_loader = NeighborLoader(data, num_neighbors=[10] * 2, shuffle=True,
                                  input_nodes=train_input_nodes, **kwargs)
val_loader = NeighborLoader(data, num_neighbors=[10] * 2,
                            input_nodes=val_input_nodes, **kwargs)

model = Sequential('x, edge_index', [
    (SAGEConv((-1, -1), 64), 'x, edge_index -> x'),
    ReLU(inplace=True),
    (SAGEConv((-1, -1), 64), 'x, edge_index -> x'),
    ReLU(inplace=True),
    (Linear(-1, dataset.num_classes), 'x -> x'),
])
model = to_hetero(model, data.metadata(), aggr='sum').to(device)
```
I made some modifications, but I believe that is not the problem:
1. set device as cpu only
2. removed `preprocess='metapath2vec'` argument from `OGB_MAG`
3. using only `NeighborLoader` as I dont know the difference between it and `HGTLoader` yet.

At first, I tried to do this to initialize the dimentions:
```python
@torch.no_grad()
def init_params():
    # Initialize lazy parameters via forwarding a single batch to the model:
    batch = next(iter(train_loader))
    batch = batch.to(device, 'edge_index')
    model(batch.x_dict, batch.edge_index_dict)


init_params()  # Initialize parameters.
``` 

But it took 5 mins without any result which seems kinda strange to me. Then I modified the function this way:

```python
@torch.no_grad()
def init_params():
    # Initialize lazy parameters via forwarding a single batch to the model:
    model(data.x_dict, data.edge_index_dict)


init_params()  # Initialize parameters.
```
and now I see this error:

 ```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
e:\python\gcn\pytorch-geometric\04_heterognn.ipynb Cell 11' in <cell line: 7>()
      1 @torch.no_grad()
      2 def init_params():
      3     # Initialize lazy parameters via forwarding a single batch to the model:
      4     model(data.x_dict, data.edge_index_dict)
----> 7 init_params()

File E:\anaconda3\envs\gcn\lib\site-packages\torch\autograd\grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

e:\python\gcn\pytorch-geometric\04_heterognn.ipynb Cell 11' in init_params()
      1 @torch.no_grad()
      2 def init_params():
      3     # Initialize lazy parameters via forwarding a single batch to the model:
----> 4     model(data.x_dict, data.edge_index_dict)

File E:\anaconda3\envs\gcn\lib\site-packages\torch\fx\graph_module.py:630, in GraphModule.recompile.<locals>.wrapped_call(self, *args, **kwargs)
    627 if "eval_with_key" in topmost_framesummary.filename:
    628     print(generate_error_message(topmost_framesummary),
    629           file=sys.stderr)
--> 630 raise e.with_traceback(None)

AttributeError: 'NoneType' object has no attribute 'dim'
```

I believe the problem is the same as in [this issue](https://github.com/pyg-team/pytorch_geometric/issues/4404) but I tried to inspect the `forward` method and haven't found any suspicious lines.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: Windows 10
* Python version: 3.10.4
* CUDA/cuDNN version: I use CPU only
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda

**Comment by rusty1s** [comment]
Interesting. `init_params` fails for me instantaneously. I'm not sure why it takes 5 mins for you to compute.

Note that the error is to be expected since you are missing node features for author, institution and field_of_study nodes (which will get added by the `preprocess=metapath2vec` call). You can also initialize them randomly:
```python
# Already send node features/labels to GPU for faster access during sampling:
data = dataset[0].to(device, 'x', 'y')

for node_type in ['author', 'institution', 'field_of_study']:
    data[node_type].x = torch.randn(data[node_type].num_nodes, 64)
```
in which case your example code runs through for me. Let me know if this helps!

**Comment by blokhinnv** [comment]
Oh, I see... There are these lines which add some extra attributes if `preprocess is not None`... 
Maybe it's just me, but the error seems a little bit uninformative. I can't see full traceback, probably because of decorators and the way the `forward` method is created, therefore, I made the wrong conclusions. 

I'm closing the issue, thank you for your help!

**Comment by rusty1s** [comment]
Yeah, the error is a little bit uninformative due to the model conversion of `torch.fx`. Not much we can do about it :(
