### ISSUE TITLE
DimeNet Implementation Error

### ISSUE THREAD

**Issue by LanceKnight** [pyg-team/pytorch_geometric#4425]
### 🐛 Describe the bug

`        self.rbf = BesselBasisLayer(num_radial, cutoff, envelope_exponent)`

> Traceback (most recent call last):
>   File "training_contrastive_dimenetpp.py", line 79, in <module>
>     model = DimeNetPlusPlus(
>   File "/home/liuy69/projects/unified_framework/examples/ChIRo/model/gnn_3D/dimenet_pp.py", line 245, in __init__
>     self.rbf = BesselBasisLayer(num_radial, cutoff, envelope_exponent)
>   File "/home/liuy69/environments/venv/kgnn-env/lib/python3.8/site-packages/torch_geometric/nn/models/dimenet.py", line 59, in __init__
>     self.reset_parameters()
>   File "/home/liuy69/environments/venv/kgnn-env/lib/python3.8/site-packages/torch_geometric/nn/models/dimenet.py", line 62, in reset_parameters
>     torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
> RuntimeError: a leaf Variable that requires grad is being used in an in-place operation

### Environment

* PyG version: 2.0.5
* PyTorch version: 1.11.0
* OS: CentOS7
* Python version: 3.8
* CUDA/cuDNN version: 11.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by arunppsg** [comment]
Just fixed this in #4424 . Use the latest version of torch-geometric (`pip install --pre torch_geometric`) will fix it.

**Comment by rusty1s** [comment]
Indeed, although you probably mean `pip install pyg-nightly` :)

**Comment by LanceKnight** [comment]
Thank you! @rusty1s and @arunppsg . I will check it.
