### ISSUE TITLE
AttributeError: 'GlobalStorage' object has no attribute 'neg_edge_label_index'

### ISSUE THREAD

**Issue by puranjayr96** [pyg-team/pytorch_geometric#4465]
### 🐛 Describe the bug

When trying to train an autoencoder using GAE

I get the above error for the following line:
```python
z = model.encode(data.x.double(), data.edge_index)
loss = model.recon_loss(z, data.pos_edge_label_index, data.neg_edge_label_index)
```
I checked and my data has neg_edge_label_index 
I've used RandomLinkSplit to get the positive and negative edges
```python
tfs = T.RandomLinkSplit(num_val=0.0, num_test=0.2,
                      split_labels=True,neg_sampling_ratio=2.0)
```

this is my error output
```
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    loss = train(data)
  File "train.py", line 166, in train
    loss = model.recon_loss(z, data.pos_edge_label_index, data.neg_edge_label_index)
  File "{path}/lib/python3.10/site-packages/torch_geometric/data/data.py", line 362, in __getattr__
    return getattr(self._store, key)
  File "{anaconda_path}/anaconda3/envs/autoencoder/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 52, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'neg_edge_label_index'

```

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0+cu102
* OS: CentOS
* Python version: 3.10
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Did you resolve this issue on your own? Feel free to post your solution so that others can benefit from it as well.
