### ISSUE TITLE
GCNConv does not use additive bias

### ISSUE THREAD

**Issue by lubo92** [pyg-team/pytorch_geometric#4501]
### 🐛 Describe the bug

When using GCNConv, I found that the Linear Layer never uses a bias, regardless of whether the bias parameter is set to True or False when calling GCNConv.
In my opinion, the reason for this is that in the constructor of GCNConv initialize the Linear Layer the parameter bias is always set to False and not the value of the parameter from the call to GCNConv is used.

```py
from torch_geometric.nn import GCNConv
from torch.nn.parameter import Parameter

gcn1 = GCNConv(
            in_channels=4, 
            out_channels=16, 
            bias=True,
        )

assert isinstance(gcn1._modules["lin"].bias, Parameter)  # bias in Linear layer is None
```

### Environment

* PyG version: ```2.0.4```
* PyTorch version: ```1.11.0+cpu```
* OS: ```Ubuntu 20.04.4 LTS```
* Python version: ```3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0]```
* CUDA/cuDNN version: I'm using the CPU
* How you installed PyTorch and PyG (`conda`, `pip`, source):  ```conda```
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by lubo92** [comment]
P.S.: A very, very big thank you to the whole Pytorch Geometric community for this really great project! It really helps me a lot!

**Comment by rusty1s** [comment]
We apply the bis separately outside the Linear layer, see https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/gcn_conv.py#L197.

**Comment by lubo92** [comment]
Aah, I see, so of course it makes sense.
Thank you for your quick response and your helpful support! And please excuse me for mistakenly creating a bug report. ;)

**Comment by rusty1s** [comment]
No worries :) Glad that it is resolved.
