### ISSUE TITLE
IMDB dataset contains DBLP data

### ISSUE THREAD

**Issue by vedantbhatia** [pyg-team/pytorch_geometric#4515]
### 🐛 Describe the bug

The IMDB dataset in torch_geometric.datasets seems to contain the same data as DBLP. Tested on two machines, not sure what I'm doing wrong.

Reproduce through:
```
import torch_geometric as tg
dataset = tg.datasets.IMDB()
print(dataset.data)
```
Screenshot attached.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/22726676/164525594-ddfedde0-1652-4a19-a1f5-d657389592e1.png">

### Environment

* PyG version: 2.0.5
* PyTorch version: 1.10.0
* OS: Ubuntu
* Python version: 3.8 and 3.7
* CUDA/cuDNN version: 11.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Was the same `root_dir` used?

**Comment by vedantbhatia** [comment]
> Was the same `root_dir` being used?

Yes, it wasn't being cleaned as expected.
