### ISSUE TITLE
Importing torch-geometry resulting crash on colab

### ISSUE THREAD

**Issue by Kousaka-Honoka** [pyg-team/pytorch_geometric#4542]
### 🐛 Describe the bug

As title.
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q torch-geometric

from torch_geometric.data import Data
Crash

**Comment by rusty1s** [comment]
Please see https://github.com/pyg-team/pytorch_geometric/issues/4539#event-6496454715.
