### ISSUE TITLE
degree() discussion

### ISSUE THREAD

**Issue by yutaizhou** [pyg-team/pytorch_geometric#455]
## ❓ Questions & Help

I would like to discuss the way `pyg.utils.degree()` works. In my head, an ideal `degree()` function would take in an `edge_index` and output the degree of each node. In- and out-degree could be an option as well. 

The current `degree()` function takes just one row of an `edge_index` and computes the degree of each node encountered in that row. This means the degree of nodes that happens to be in the other row of `edge_index` will not be computed. 

Example:
```
e = torch.tensor([[0,0,0], [1,2,3]])
# [[0, 0, 0],
   [1, 2, 3]]
pyg.utils.degree(e[0]) # [3]
pyg.utils.degree(e[1]) # [0,1,1,1]
```
I supposed the degree of every node can be computed by `pyg.utils.degree(e.flatten())`, but I am not sure about edge cases of such usage.

Why is the output intended to be this way?

**Comment by rusty1s** [comment]
I agree with you that the naming is a bit off. A more reasonable name would simply be `bincount`. A `degree` function as described by you would be similar to:
```python
def new_degree(edge_index, num_nodes, out=True):
    return degree(edge_index[0 if out else 1], num_nodes)
```
Note that `degree(e.flatten())` is not the right approach to compute the node degree because you compute both in- **and** out-degree.
