### ISSUE TITLE
LightningDataset works with Plugins but not Strategies

### ISSUE THREAD

**Issue by tagirshin** [pyg-team/pytorch_geometric#4560]
### 🐛 Describe the bug

While working with PyG LightningDataset and PyTorch lightning Trainer, for example, with this minimal code:
```
import torch
import pytorch_lightning as pl
from torch_geometric.data import LightningDataset

datamodule = LightningDataset(train_dataset, val_dataset, batch_size=1000, pin_memory=True)
model = ...
trainer = pl.Trainer(accelerator="gpu", devices=[0], strategy="ddp_spawn", max_epochs=100,  gradient_clip_val=1.0, precision=16, detect_anomaly=False) 
trainer.fit(model, datamodule)
```

I get following error:
``` 
NotImplementedError: 'LightningDataset' currently only supports 'SingleDevicePlugin' and 'DDPSpawnPlugin' training type plugins of 'pytorch_lightning' (got 'DDPSpawnStrategy')
```

When I'm changing on `DDPSpawnPlugin`, everything works fine:

```
from pytorch_lightning.plugins import DDPSpawnPlugin 

trainer = pl.Trainer(accelerator="gpu", devices=[0], strategy=DDPSpawnPlugin(), max_epochs=100,  gradient_clip_val=1.0, precision=16, detect_anomaly=False)
```

However, in the PyG [docs](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.LightningDataset) it written, that it works with `pytorch_lightning.strategies.DDPSpawnStrategy` but not Plugin. Also, plugins are deprecated in future versions of PyTorch lightning.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: Ubuntu 20.4
* Python version: 3.9.7
* CUDA/cuDNN version: 11.3.1/2.8.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* PyTorch lightning: 1.6.2

**Comment by rusty1s** [comment]
This is already fixed in master. Instructions for installation can be found [here](https://github.com/pyg-team/pytorch_geometric#nightly-and-master).
