### ISSUE TITLE
`download` and `process` methods are not called when `Dataset` is subclassed indirectly

### ISSUE THREAD

**Issue by raimis** [pyg-team/pytorch_geometric#4567]
### 🐛 Describe the bug

Create a dummy dataset `DS`  by directly subclassing `Dataset`, i.e. `DS` --> `Dataset`:
```python
from torch_geometric.data import Dataset

class DS(Dataset):

    @property
    def raw_file_names(self):
        return 'dummy'

    def download(self):
        print(f'Calling {self.__class__.__name__}.download')
``` 
When creating an instance of `DS`, the method `download` is called as expected:
```python
ds = DS('.')
Calling DS.download
```

Create a dummy dataset `DS2` by indirectly subclassing `Dataset`, i.e.  `DS2` --> `DS1` --> `Dataset`:
```python
class DS1(Dataset):

    def download(self):
        print(f'Calling {self.__class__.__name__}.download')

class DS2(DS1):

    @property
    def raw_file_names(self):
        return 'dummy'
```
When creating an instance of `DS2`, the method `download` **is not called**, as expected:
```python
ds2 = DS2('.')
# No output
```
However, the method can be called directly:
```python
ds2.download()
Calling DS2.download
``` 

Additionally, the same issue exists with `process` method.

### Environment

* PyG version: `master` (https://github.com/pyg-team/pytorch_geometric/commit/484b7922ec68d146280acba409fc7170549e2775)
* PyTorch version: 1.10.0
* OS: CentOS 7.9
* Python version: 3.9.10
* CUDA/cuDNN version: 11.2.2/8.2.1.32
* How you installed PyTorch and PyG (`conda`, `pip`, source): `conda` and `source`
* Any other relevant information (*e.g.*, version of `torch-scatter`): N/A

**Comment by raimis** [comment]
I suspect, the problem is here:
https://github.com/pyg-team/pytorch_geometric/blob/484b7922ec68d146280acba409fc7170549e2775/torch_geometric/data/dataset.py#L83-L87

**Comment by Padarn** [comment]
I suggest we replace this with 
```
if hasattr(hasattr, 'download'): 
     self._download() 
```
Thoughts?

**Comment by rusty1s** [comment]
Thanks for reporting, although this is somewhat intended. In general, we only want to call `download()` in case it is overridden by the base class. Note that
```python
if hasattr(self, 'download'):
```
does not work as it is always true. One solution to fix would be to check if `download` is never implemented for any child class. @Padarn @raimis Let me know if you have interested in looking into this.

One simple fix to unblock is to simply override `download()` again:
```python
def download(self):
    super().download()
```

**Comment by Padarn** [comment]
Oh good point @rusty1s.

Happy to look into this
>  is never implemented for any child class
Just to be clear, the final behavior we want here is that as long as some class implements `download` (other than `Dataset`) then we'd want to call it?

**Comment by Padarn** [comment]
I'll investigate a bit first. I'm sure this something that StackOverflow has answered at some point :-)

**Comment by Padarn** [comment]
One option is to use 
```
if self.download.__qualname__.split(".")[0] != 'Dataset':
    self._download()
```
But it does seem a tiny bit fragile.

**Comment by raimis** [comment]
@Padarn @rusty1s thank you for the quick fix!
