### ISSUE TITLE
About message of GCN

### ISSUE THREAD

**Issue by chengsen** [pyg-team/pytorch_geometric#459]
## ❓ Questions & Help
I pass the edge_indx [2, 9075063] to the GCN, and I found the return of `def message` is [9075063, 1] * [9075063, 200], and it is `CUDA out of memory`. 

the features of input are one-hot vector. so the x is the weight matrix [14049, 200]

Is there a better way to solve it? May my edge is too much?

**Comment by rusty1s** [comment]
Your graph seems to be too big to be processed at once. There are more memory efficient ways to process your graph, *e.g.*, converting to a PyTorch sparse tensor and simply using `torch.matmul(adj, torch.matmul(x, weight))`. I might make an additional argument of `GCNConv` to allow this. Alternatively, you can sample nodes to compute embeddings for using our `NeighborSampler` API (only in current master).

**Comment by chengsen** [comment]
because the input of node feature is one-hot vector, so the node features equal to the weight. The original code is `torch.spmm(adj, weight)` or `torch.mm(adj, weight)`, it is worked.  adj is sparse tensor of graph. 

I tried to use PyG to further improve efficiency, but the result was unexpected. Am I using it correctly?

**Comment by rusty1s** [comment]
`GCNConv` supports `SparseTensor` as node feature input, so closing this now :)
