### ISSUE TITLE
`HeteroConv` does not support `add_self_loop` models

### ISSUE THREAD

**Issue by Padarn** [pyg-team/pytorch_geometric#4646]
### 🐛 Describe the bug

Brought up by @rusty1s in the discussion [here](https://github.com/pyg-team/pytorch_geometric/discussions/4637), it was noted that when using a `HetreoConv` model with relationship models that use `add_self_loops` the message passing will be incorrect. For example:
```
HeteroConv({('A', 'to', 'B'): GATConv((-1, -1), hidden_channels, heads=4, dropout=0.2)})
```
This is caused by the fact that the self loops would then refer links between source and destination nodes of different types.

The suggestion here is to add a check inside `HeteroConv` that would warn raise an exception to avoid users unknowingly doing this.

**Comment by rusty1s** [comment]
Can we do the same for `to_hetero()`?
