### ISSUE TITLE
bug in GCN2Conv

### ISSUE THREAD

**Issue by suxnju** [pyg-team/pytorch_geometric#4662]
### 🐛 Describe the bug

The `message` function is implemented as:
```python
def message(self, x_j: Tensor, edge_weight: Tensor) -> Tensor:
    return edge_weight.view(-1, 1) * x_j
```

**But**, if the `edge_weight` is None, it will raise an error.

### Fix

Refer to the `GCNConv`, it is easy to fix
```python
def message(self, x_j: Tensor, edge_weight: Tensor) -> Tensor:
    return x_j if edge_weight is None else edge_weight.view(-1, 1) * x_j
```

**Comment by rusty1s** [comment]
Thanks. This is fixed in https://github.com/pyg-team/pytorch_geometric/pull/4670.
