### ISSUE TITLE
[Conda Release] ModuleNotFoundError: No module named 'torch_geometric.logging'

### ISSUE THREAD

**Issue by cs-sun** [pyg-team/pytorch_geometric#4681]
### 🐛 Describe the bug

`torch_geometric.logging` is missing in `pyg 2.0.4 py39_torch_1.11.0_cu113   pyg`

Issue still exists after `conda remove` & `conda clean --all` & `conda install pyg -c pyg`.

Error occurs when trying `from torch_geometric.logging import init_wandb, log`.

```
File "/home/xxx/miniconda3/envs/torch/lib/python3.9/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 9, in <module>
    from torch_geometric.logging import init_wandb, log
ModuleNotFoundError: No module named 'torch_geometric.logging'
```
<img width="583" alt="Screenshot 2022-05-19 at 19 35 28" src="https://user-images.githubusercontent.com/15100503/169284220-2f7bd817-5ec4-4cb0-af1c-fe2f1d8c68dd.png">

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0 (py3.9_cuda11.3_cudnn8.2.0_0)
* OS: Ubuntu 20.04.4 LTS x86_64 (Kernel: 5.13.0-35-generic)
* Python version:3.9.12
* CUDA/cuDNN version: CUDA 11.6 cudnn 8.2.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): N/A

**Comment by Sanzo00** [comment]
I have the same error, when run examples/gcn.py

```bash
python gcn.py
```


```bash
Traceback (most recent call last):
  File "gcn.py", line 9, in <module>
    from torch_geometric.logging import init_wandb, log
ModuleNotFoundError: No module named 'torch_geometric.logging'
```

## Environment
torch:                     1.11.0             
torch-geometric:           2.0.4  
torch-scatter:             2.0.9         
torch-sparse:              0.6.13             
OS: macOS 12.3.1
python: 3.8.13

**Comment by rusty1s** [comment]
Yes, we just recently added support for "Weights & Biases" logging. For now, it is best to execute the 2.0.4 example:
https://github.com/pyg-team/pytorch_geometric/blob/2.0.4/examples/gcn.py
