### ISSUE TITLE
Issue with pip installing torch-scatter (ERROR: Command errored out with exit status 1: ....)

### ISSUE THREAD

**Issue by mohammadmahdikarimi** [pyg-team/pytorch_geometric#4706]
### 😵 Describe the installation problem

I am trying to run [this colab](https://colab.research.google.com/drive/16tqEHKOLUgYvXKx1V3blfYGpQb1_09MG?usp=sharing) on my Jupiter notebook and I keep getting weird errors:

I am getting the following error while installing. Please any clue how to fix it? The script runs fine on the Colab but not on my machine!

- !pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --no-binary :all:

Looking in links: https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
Collecting torch-scatter
  Using cached torch_scatter-2.0.9.tar.gz (21 kB)
Skipping wheel build for torch-scatter, due to binaries being disabled for it.
Installing collected packages: torch-scatter
    Running setup.py install for torch-scatter ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h201hh5f/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h201hh5f/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n_b8_xqb/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/torch-scatter
         cwd: /tmp/pip-install-h201hh5f/torch-scatter/
    Complete output (132 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.6/torch_scatter
    creating build/lib.linux-x86_64-3.6/torch_scatter/composite
    copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
    copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
    copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
    copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
    running build_ext
    building 'torch_scatter._version_cpu' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/csrc
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/opt/conda/include/python3.6m -c csrc/version.cpp -o build/temp.linux-x86_64-3.6/csrc/version.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_version_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/KernelFunction.h:5:0,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/dispatch/DispatchTable.h:9,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/dispatch/OperatorEntry.h:3,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:3,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/TensorMethods.h:10,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:12,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                     from csrc/version.cpp:2:
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h: In instantiation of ‘typename c10::guts::infer_function_traits<Functor>::type::return_type c10::detail::call_functor_with_args_from_stack_(Functor*, c10::Stack*, std::index_sequence<INDEX ...>) [with Functor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >; bool AllowDeprecatedTypes = true; long unsigned int ...ivalue_arg_indices = {}; typename c10::guts::infer_function_traits<Functor>::type::return_type = long int; c10::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >; std::index_sequence<INDEX ...> = std::integer_sequence<long unsigned int>]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h:218:77:   required from ‘typename c10::guts::infer_function_traits<Functor>::type::return_type c10::detail::call_functor_with_args_from_stack(Functor*, c10::Stack*) [with Functor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >; bool AllowDeprecatedTypes = true; typename c10::guts::infer_function_traits<Functor>::type::return_type = long int; c10::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h:250:91:   required from ‘static void c10::detail::make_boxed_from_unboxed_functor<KernelFunctor, AllowDeprecatedTypes, typename std::enable_if<(! std::is_same<void, typename c10::guts::infer_function_traits<Functor>::type::return_type>::value), void>::type>::call(c10::OperatorKernel*, const c10::OperatorHandle&, c10::Stack*) [with KernelFunctor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >; bool AllowDeprecatedTypes = true; c10::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:100:9:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedFunctor(std::unique_ptr<c10::OperatorKernel>) [with bool AllowLegacyTypes = true; KernelFunctor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:165:110:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedRuntimeFunction(FuncType*) [with bool AllowLegacyTypes = true; FuncType = long int()]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/op_registration/op_registration.h:527:72:   required from ‘std::enable_if_t<(c10::guts::is_function_type<T>::value && (! std::is_same<FuncType, void(const c10::OperatorHandle&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)>::value)), c10::RegisterOperators&&> c10::RegisterOperators::op(const string&, FuncType*, c10::RegisterOperators::Options&&) && [with FuncType = long int(); std::enable_if_t<(c10::guts::is_function_type<T>::value && (! std::is_same<FuncType, void(const c10::OperatorHandle&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)>::value)), c10::RegisterOperators&&> = c10::RegisterOperators&&; std::string = std::basic_string<char>]’
    csrc/version.cpp:25:79:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h:207:22: warning: variable ‘num_ivalue_args’ set but not used [-Wunused-but-set-variable]
         constexpr size_t num_ivalue_args = sizeof...(ivalue_arg_indices);
                          ^~~~~~~~~~~~~~~
    g++ -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/csrc/version.o -L/opt/conda/lib/python3.6/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.6/torch_scatter/_version_cpu.so -s
    building 'torch_scatter._version_cuda' extension
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Icsrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c csrc/version.cpp -o build/temp.linux-x86_64-3.6/csrc/version.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_version_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/KernelFunction.h:5:0,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/dispatch/DispatchTable.h:9,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/dispatch/OperatorEntry.h:3,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:3,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/TensorMethods.h:10,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:12,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /opt/conda/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                     from csrc/version.cpp:2:
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h: In instantiation of ‘typename c10::guts::infer_function_traits<Functor>::type::return_type c10::detail::call_functor_with_args_from_stack_(Functor*, c10::Stack*, std::index_sequence<INDEX ...>) [with Functor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >; bool AllowDeprecatedTypes = true; long unsigned int ...ivalue_arg_indices = {}; typename c10::guts::infer_function_traits<Functor>::type::return_type = long int; c10::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >; std::index_sequence<INDEX ...> = std::integer_sequence<long unsigned int>]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h:218:77:   required from ‘typename c10::guts::infer_function_traits<Functor>::type::return_type c10::detail::call_functor_with_args_from_stack(Functor*, c10::Stack*) [with Functor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >; bool AllowDeprecatedTypes = true; typename c10::guts::infer_function_traits<Functor>::type::return_type = long int; c10::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h:250:91:   required from ‘static void c10::detail::make_boxed_from_unboxed_functor<KernelFunctor, AllowDeprecatedTypes, typename std::enable_if<(! std::is_same<void, typename c10::guts::infer_function_traits<Functor>::type::return_type>::value), void>::type>::call(c10::OperatorKernel*, const c10::OperatorHandle&, c10::Stack*) [with KernelFunctor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >; bool AllowDeprecatedTypes = true; c10::Stack = std::vector<c10::IValue, std::allocator<c10::IValue> >]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:100:9:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedFunctor(std::unique_ptr<c10::OperatorKernel>) [with bool AllowLegacyTypes = true; KernelFunctor = c10::detail::WrapRuntimeKernelFunctor_<long int (*)(), long int, c10::guts::typelist::typelist<> >]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/KernelFunction_impl.h:165:110:   required from ‘static c10::KernelFunction c10::KernelFunction::makeFromUnboxedRuntimeFunction(FuncType*) [with bool AllowLegacyTypes = true; FuncType = long int()]’
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/op_registration/op_registration.h:527:72:   required from ‘std::enable_if_t<(c10::guts::is_function_type<T>::value && (! std::is_same<FuncType, void(const c10::OperatorHandle&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)>::value)), c10::RegisterOperators&&> c10::RegisterOperators::op(const string&, FuncType*, c10::RegisterOperators::Options&&) && [with FuncType = long int(); std::enable_if_t<(c10::guts::is_function_type<T>::value && (! std::is_same<FuncType, void(const c10::OperatorHandle&, std::vector<c10::IValue, std::allocator<c10::IValue> >*)>::value)), c10::RegisterOperators&&> = c10::RegisterOperators&&; std::string = std::basic_string<char>]’
    csrc/version.cpp:25:79:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/boxing/kernel_functor.h:207:22: warning: variable ‘num_ivalue_args’ set but not used [-Wunused-but-set-variable]
         constexpr size_t num_ivalue_args = sizeof...(ivalue_arg_indices);
                          ^~~~~~~~~~~~~~~
    g++ -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/csrc/version.o -L/opt/conda/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.6/torch_scatter/_version_cuda.so -s
    building 'torch_scatter._segment_csr_cpu' extension
    creating build/temp.linux-x86_64-3.6/csrc/cpu
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/opt/conda/include/python3.6m -c csrc/segment_csr.cpp -o build/temp.linux-x86_64-3.6/csrc/segment_csr.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_segment_csr_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/opt/conda/include/python3.6m -c csrc/cpu/segment_csr_cpu.cpp -o build/temp.linux-x86_64-3.6/csrc/cpu/segment_csr_cpu.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_segment_csr_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/csrc/segment_csr.o build/temp.linux-x86_64-3.6/csrc/cpu/segment_csr_cpu.o -L/opt/conda/lib/python3.6/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.6/torch_scatter/_segment_csr_cpu.so -s
    building 'torch_scatter._segment_csr_cuda' extension
    creating build/temp.linux-x86_64-3.6/csrc/cuda
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Icsrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c csrc/segment_csr.cpp -o build/temp.linux-x86_64-3.6/csrc/segment_csr.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_segment_csr_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Icsrc -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c csrc/cpu/segment_csr_cpu.cpp -o build/temp.linux-x86_64-3.6/csrc/cpu/segment_csr_cpu.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_segment_csr_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h201hh5f/torch-scatter/setup.py", line 102, in <module>
        packages=find_packages(),
      File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/conda/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/opt/conda/lib/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 353, in unix_wrap_single_compile
        cflags = unix_cuda_flags(cflags)
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 336, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1316, in _get_cuda_arch_flags
        raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
    ValueError: Unknown CUDA arch (8.0+PTX) or GPU not supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h201hh5f/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h201hh5f/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n_b8_xqb/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/torch-scatter Check the logs for full command output.

### Environment

* PyG version: I get error
* PyTorch version: downgraded to 1.5.0
* OS: linux (JupyterNB)
* Python version: 3.6.10
* CUDA/cuDNN version: CUDA Version: 11.4 
* How you installed PyTorch and PyG (`conda`, `pip`, source):
!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --no-binary :all:

* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
You need to specify the latest version of `torch-scatter` listed in https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html:
```
You need to specify the latest version of torch-scatter listed in: https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```

**Comment by mohammadmahdikarimi** [comment]
Thank you @rusty1s , 

I encountered many more errors that I had to look for their solution online. I needed to perform the following initialization to set up my environment before I was able to run the script on my machine. I am quite new to graph in python, I was wondering if there is a better way to do this instead of try and error and fixing each error one by one? Anyone? Any Idea, Please?



> conda install pytorch torchvision cudatoolkit=10.1 -c pytorch -y
> pip uninstall torch -y 
> pip uninstall torch -y 
> pip install tqdm --upgrade --use-feature=2020-resolver
> pip install torch==1.7.0 torchvision==0.8.1 -f https://download.pytorch.org/whl/cu101/torch_stable.html --use-feature=2020-resolver 
> pip install pillow  --use-feature=2020-resolver 
> pip install networkx==2.1 --use-feature=2020-resolver 
> pip install matplotlib==2.2.3 --use-feature=2020-resolver 
> pip install torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --use-feature=2020-resolver 
> pip install  torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html --use-feature=2020-resolver 
> pip install  torch-geometric --use-feature=2020-resolver
