### ISSUE TITLE
Not compatible with python 3.10

### ISSUE THREAD

**Issue by Xin-yang-Liu** [pyg-team/pytorch_geometric#4709]
### 😵 Describe the installation problem

I tried to install ```PyG``` via conda:
```
conda install pyg -c pyg
```
but I got the following error from conda:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyg -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

Your python: python=3.10
```
Could you please add support for python 3.10? Thanks!

### Environment

* PyG version: N/A
* PyTorch version: 1.11.0
* OS: Ubuntu 20.04.4 LTS, Linux kernel 5.13
* Python version: 3.10.4
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda

**Comment by Xin-yang-Liu** [comment]
I put the complete conda output here, in case you need it. 
```
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                         

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyg -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - pyg -> cudatoolkit=11.3 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - python=3.10 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

**Comment by rusty1s** [comment]
I think you are correct. It looks like the Python 3.10 Linux packages are missing, see https://anaconda.org/pyg/pyg/files?page=1. We can fix this in the next version. For now, you need to downgrade to Python 3.9 or install via `pip`, sorry :(

**Comment by rusty1s** [comment]
Looks like this issue is indeed desired to prevent some issues, see https://github.com/pyg-team/pytorch_geometric/blob/master/.github/workflows/building_pyg_conda.yml#L31-L33. I think this should be definitely be fixed in the next release since we made `torch-spline-conv` an optional dependency (which causes these issues).
