### ISSUE TITLE
unbatching a `DataBatch`

### ISSUE THREAD

**Issue by Padarn** [pyg-team/pytorch_geometric#4717]
### Discussed in https://github.com/pyg-team/pytorch_geometric/discussions/4714

<div type='discussions-op-text'>

<sup>Originally posted by **BraveDistribution** May 25, 2022</sup>
Hello,

I am working with meshes and I have a DataBatch, with batch size of 4. I am interested in splitting the DataBatch into 4 objects (let's say the inverse of CollateFunction) in the data loader. 

Is there any native support? thanks.</div>

**Comment by rusty1s** [comment]
Isn't this already supported via `batch[i]` or `batch.to_data_list()`?

**Comment by rusty1s** [comment]
Closing this for now until there is further feedback.

**Comment by chenzhekl** [comment]
Hi @rusty1s, I have a simple workaround assuming that the batch index is continuous, sorted, and starts with 0.

```python
def unbatch_edge_index(edge_index, batch):
    boundary = torch.cumsum(degree(batch), dim=0)
    inc = torch.cat([boundary.new_tensor([0]), boundary[:-1]], dim=0)

    edge_assignments = torch.bucketize(edge_index, boundary, right=True)

    out = [
        edge_index[edge_assignments == batch_idx].view(2, -1) - inc[batch_idx]
        for batch_idx in range(batch.max().item() + 1)
    ]

    return out
```

Do you think we can include it inside `utils` alongside `unbatch`?

**Comment by rusty1s** [comment]
Yes, definitely! :)
