### ISSUE TITLE
utils.subgraph

### ISSUE THREAD

**Issue by Misterion777** [pyg-team/pytorch_geometric#4724]
### 🐛 Describe the bug

`utils.subgraph` returns empty results.

I think issue is in wrong logic operator [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/subgraph.py#L58). Operation should be OR (`|`), not AND.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: MacOS
* Python version: 3.8
* CUDA/cuDNN version: -
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
I think the `AND` is correct here. We only want to maintain edges for which both source and destination nodes are in the node set of the induced subgraph.

**Comment by Misterion777** [comment]
It turns out, I was looking for k_hop_subgraph, rather then just subgraph.
Sorry for bothering.
