### ISSUE TITLE
Separate master and latest release docs

### ISSUE THREAD

**Issue by ZakSingh** [pyg-team/pytorch_geometric#4760]
### 📚 Describe the documentation issue

It appears that the pyg docs' "latest" version includes doc changes from subsequent commits to master. This can be confusing when trying to use a feature which is in the docs but not available in the currently published latest version of pyg (Just happened to me with the "v2" arg on GAT).

This wouldn't be a problem if you could view the latest published version's docs, but right now there's no way to see the 'real' 2.0.4 docs:

![image](https://user-images.githubusercontent.com/18584287/171799254-027f6103-689d-4ff3-871f-47f192d0e7a6.png)

### Suggest a potential alternative/fix

I think the more natural behavior would be to default to the latest release docs, and have the current master 'latest' version be available in the dropdown separately.

**Comment by rusty1s** [comment]
I just pushed version `2.0.4` as well, forgot about it :(
I actually like having `latest` as default since it better displays what we are working on, although I agree that it can be confusing at times.

**Comment by ZakSingh** [comment]
Ah ok, makes sense. Thanks for the great library!
