### ISSUE TITLE
Change the download location of the AmazonProducts dataset

### ISSUE THREAD

**Issue by ThyrixYang** [pyg-team/pytorch_geometric#4787]
### 🛠 Proposed Refactor

datasets.AmazonProducts(root="./root")
will download raw data into ./root/raw
which is not consist with other datasets in PyG (and torchvision) that
save to ./root/dataset_name/raw.

### Suggest a potential alternative/fix

Save downloaded data to ./root/AmazonProducts/raw and processed data to ./root/AmazonProducts/processed.

I'm glad to open a PR if this is approved.

**Comment by rusty1s** [comment]
Thanks for this issue. I think in case we want to change that, we would need to change it for every dataset in PyG. In regular, `root` refers to the directory containing the data, not its parent directory. We only leverage `root/{dataset_name}/raw` for datasets that bundle multiple datasets together. WDYT?

**Comment by ThyrixYang** [comment]
Hi @rusty1s , I agree with you, thanks.
