### ISSUE TITLE
cannot import name 'GraphGymDataModule' from 'torch_geometric.graphgym.loader'

### ISSUE THREAD

**Issue by NotTodayNotMe** [pyg-team/pytorch_geometric#4829]
### 🐛 Describe the bug

When trying to run the basic graphgym example with "bash run_single.sh ", I get the following error:
`Traceback (most recent call last):
  File "/home/siqing/pytorch_geometric/graphgym/main.py", line 16, in <module>
    from torch_geometric.graphgym.loader import GraphGymDataModule
ImportError: cannot import name 'GraphGymDataModule' from 'torch_geometric.graphgym.loader' (/home/siqing/anaconda3/lib/python3.9/site-packages/torch_geometric/graphgym/loader.py)
Traceback (most recent call last):
  File "/home/siqing/pytorch_geometric/graphgym/main.py", line 16, in <module>
    from torch_geometric.graphgym.loader import GraphGymDataModule
ImportError: cannot import name 'GraphGymDataModule' from 'torch_geometric.graphgym.loader' (/home/siqing/anaconda3/lib/python3.9/site-packages/torch_geometric/graphgym/loader.py)
Traceback (most recent call last):
  File "/home/siqing/pytorch_geometric/graphgym/main.py", line 16, in <module>
    from torch_geometric.graphgym.loader import GraphGymDataModule
ImportError: cannot import name 'GraphGymDataModule' from 'torch_geometric.graphgym.loader' (/home/siqing/anaconda3/lib/python3.9/site-packages/torch_geometric/graphgym/loader.py)`
Before I get there, I followed the methods in this issue :[https://github.com/pyg-team/pytorch_geometric/issues/4367](url) to fix the bug 'ImportError: cannot import name 'set_out_dir' from 'torch_geometric.graphgym.config'. However, here comes a new one.

### Environment

* PyG version:2.0.5
* PyTorch version:1.11.0
* OS: Ubuntu20.04
* Python version: 3.9
* CUDA/cuDNN version:11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip install git+https://github.com/pyg-team/pytorch_geometric.git

**Comment by rusty1s** [comment]
Please install [PyG from master](https://github.com/pyg-team/pytorch_geometric#nightly-and-master) or checkout the `2.0.4` tag:
```
cd /home/siqing/pytorch_geometric/
git checkout 2.0.4
```
We recently did some changes to GraphGym in recent commits.

**Comment by NotTodayNotMe** [comment]
I have already installed PyG from master before I encounter this error.

**Comment by rusty1s** [comment]
Thanks for confirming. There was indeed a bug which is now fixed, see https://github.com/pyg-team/pytorch_geometric/pull/4843. Thank you!
