### ISSUE TITLE
Using both `pre_transform` and `pre_filter` with `torch_geometric.dataset.TUDataset` gives unexpected behaviour. 

### ISSUE THREAD

**Issue by henrykenlay** [pyg-team/pytorch_geometric#4836]
### 🐛 Describe the bug

I'm trying to load a TUDataset using `pre_transform` and `pre_filter`. The `pre_filter` discards small graphs. The `pre_transform` for my use case is `Compose([ToUndirected(), RemoveIsolatedNodes(), AssignID()])` where `AssignID` is a transform I wrote that assigns a unique id to each graph. For a minimal example below we can just add a constant node feature (which does not affect the graph topology). Here is the example:

```python
import torch_geometric
from torch_geometric.transforms import Constant
from torch_geometric.utils import from_networkx
import networkx as nx
import os
import shutil

# make sure the data is not cached
if os.path.exists('data_temp/'):
   shutil.rmtree('data_temp/')

# define pre_filter and check it does what we expect
pre_filter = lambda graph: graph.num_nodes >= 6
print(pre_filter(from_networkx(nx.barabasi_albert_graph(5, 2))))
print(pre_filter(from_networkx(nx.barabasi_albert_graph(6, 2))))
print(pre_filter(from_networkx(nx.barabasi_albert_graph(7, 2))))

# load dataset with a pre_filter and a transform
# print the size of the smallest graph, number of graphs and total number of nodes
dataset = torch_geometric.datasets.TUDataset('data_temp/with_pre_transform', 'AIDS', pre_filter = pre_filter, pre_transform=Constant())
print('With transform', min([x.num_nodes for x in dataset]), len(dataset), dataset.data.num_nodes)

# load dataset with a pre_filter only
# print the size of the smallest graph, number of graphs and total number of nodes
dataset = torch_geometric.datasets.TUDataset('data_temp/without_pre_transform', 'AIDS', pre_filter = pre_filter)
print('Without transform', min([x.num_nodes for x in dataset]), len(dataset), dataset.data.num_nodes)
```

The output of this code block is 

```
False
True
True
Downloading https://www.chrsmrrs.com/graphkerneldatasets/AIDS.zip
Extracting data_temp/with_pre_transform/AIDS/AIDS.zip
Processing...
Done!
With transform 2 1980 30990
Downloading https://www.chrsmrrs.com/graphkerneldatasets/AIDS.zip
Extracting data_temp/without_pre_transform/AIDS/AIDS.zip
Processing...
Done!
Without transform 6 1980 31307
```

The first three lines show the `pre_filter` working as expected. The data is downloading in both cases so this is not an issue with caching. When we use a transform the smallest graph is `2` nodes, so the `pre_filter` is not working as expected. Without the transform, the smallest graph is `6` nodes which is what we expect. It is also weird to me that both datasets have the same number of graphs and that the one that seems to be working has more total nodes. 

I am not sure if I'm making a mistake here, or is this a bug? I looked at `transform` in the `TUDataset` class and cannot find anything obvious that might be causing this unexpected behaviour. 

### Environment

* PyG version: `2.0.4`
* PyTorch version: `1.11.0`
* OS: `Ubuntu 16.04.7 LTS`
* Python version: `3.9.12`
* CUDA/cuDNN version: `11.3`  
* How you installed PyTorch and PyG (`conda`, `pip`, source): `conda install pyg -c pyg`
* Any other relevant information (*e.g.*, version of `torch-scatter`): I also do `pip uninstall torch-spline-conv` according to this [issue](https://github.com/pyg-team/pytorch_geometric/issues/3477#issuecomment-1059538897=).

I also reproduced this issue on a Mac with OS version `12.4` using `cpu` version of torch (all other information is the same).

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in https://github.com/pyg-team/pytorch_geometric/pull/4842.
