### ISSUE TITLE
Possible typo in MinCut pooling

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#4878]
### 📚 Describe the documentation issue

Docs: "The MinCUt pooling operator from the" (https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.dense.dense_mincut_pool). Is "MinCUt" on purpose?

### Suggest a potential alternative/fix

Change to "MinCut" or "MinCUT". The first version is more proper in this context in my opinion, as minCUT is an algorithmic problem, while MinCut is a graph algorithm from paper linked in docs.

**Comment by rusty1s** [comment]
Thanks! Fixed in #4895
