### ISSUE TITLE
`segment_matmul` integration from `pyg-lib`

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#4887]
### 🚀 The feature, motivation and pitch

- `pyg-lib` issue: https://github.com/pyg-team/pyg-lib/issues/49
- `pyg-lib` PR: https://github.com/pyg-team/pyg-lib/pull/51

Need to integrate this into the backend of PyG's heterogeneous GNNs.

**Comment by puririshi98** [comment]
Candidates for first round of integration:
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/rgcn_conv.html#RGCNConv
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/rgat_conv.html#RGATConv
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/dense/linear.html#HeteroLinear

Candidates for second round(nvfuser+pyg-lib):
[torch_geometric.nn.conv.HeteroConv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html?highlight=heteroconv#torch_geometric.nn.conv.HeteroConv)

**Comment by rusty1s** [comment]
Important to note, this will require adding backward support of `segment_matmul` in `pyg-lib`.

**Comment by puririshi98** [comment]
https://github.com/pyg-team/pytorch_geometric/pull/5052

**Comment by puririshi98** [comment]
speeding it up:
https://github.com/pyg-team/pyg-lib/pull/73

**Comment by puririshi98** [comment]
heterolinear cutlass support: https://github.com/pyg-team/pytorch_geometric/pull/5330
