### ISSUE TITLE
Unable to implement mini-batch training using heterogeneous dataset

### ISSUE THREAD

**Issue by luisfredgs** [pyg-team/pytorch_geometric#4899]
### 🐛 Describe the bug

Hello, 
I'm trying to adapt the MovieLens example to work with mini-batch training. However, I'm facing an issue when calling the decoder. I'll share my notebook on Google Colab. Thank you in advance for your help or any directions.

My Google Colab notebook to reproduce the error:
https://drive.google.com/file/d/1p_C5bqs3XRFiLDjeGCvcx5JC6SV3_ioP/view?usp=sharing

The complete error message:
```
IndexError                                Traceback (most recent call last)

[<ipython-input-160-69326f3fb109>](https://localhost:8080/#) in <module>()
     37     out = model(batch.x_dict, 
     38                  batch.edge_index_dict,
---> 39                  batch['user', 'movie'].edge_label_index)
     40 
     41     out = out['user'][:batch_size]

3 frames

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

[<ipython-input-150-fa150fdb5f4a>](https://localhost:8080/#) in forward(self, x_dict, edge_index_dict, edge_label_index)
     45     def forward(self, x_dict, edge_index_dict, edge_label_index):
     46         z_dict = self.encoder(x_dict, edge_index_dict)
---> 47         return self.decoder(z_dict, edge_label_index)
     48 
     49 

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

[<ipython-input-150-fa150fdb5f4a>](https://localhost:8080/#) in forward(self, z_dict, edge_label_index)
     28         z = torch.cat([
     29                        z_dict['user'][row],
---> 30                        z_dict['movie'][col]
     31                        ], dim=-1)
     32 

IndexError: index 587 is out of bounds for dimension 0 with size 4
```

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0+cu113
* OS: Ubuntu 18.04.5 LTS
* Python version: 3.7
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
You need to use `LinkNeighborLoader` for this, which takes care of correctly batching links. Let me know how it goes!

**Comment by luisfredgs** [comment]
I tried importing the `LinkNeighborLoader`. Now, I've got the error:

`ImportError: cannot import name 'LinkNeighborLoader' from 'torch_geometric.loader' (/home/luisfredgs/venvs/main/lib/python3.8/site-packages/torch_geometric/loader/__init__.py)`

I guess my PyG version is the most recent stable (2.0.4). Perhaps, I should install PyG from master.

**Comment by luisfredgs** [comment]
I tried importing the `LinkNeighborLoader`. My PyG version is 2.0.4. Now, I've got the error:
```ImportError: cannot import name 'LinkNeighborLoader' from 'torch_geometric.loader' (/home/luisfredgs/venvs/main/lib/python3.8/site-packages/torch_geometric/loader/__init__.py)```

Anyway, I installed PyG from the master branch. It's working now.

Thank you so much!!!

**Comment by rusty1s** [comment]
Indeed. Will try to release a new version soon :)

**Comment by alaasouabni** [comment]
Hi, im facing the same issue, can someone please guide me on how to solve this? i've been stuck here for days
