### ISSUE TITLE
KNN selects fewer number of neighbours when executed on cuda

### ISSUE THREAD

**Issue by Ignasijus** [pyg-team/pytorch_geometric#4906]
### 🐛 Describe the bug

Hi,
I noticed that sometimes knn_graph selects a different number of neighbors when executed on cuda compared to cpu. I add a code to reproduce (positions of the points are here: [pos.zip](https://github.com/pyg-team/pytorch_geometric/files/9027825/pos.zip)).
In this example I have 32 points (they are not repeating) and try to generate a knn graph with k = 8. 

```python
import torch
from torch_geometric.nn import knn_graph

pos = torch.load('pos.pt')

edge_index_cpu = knn_graph(pos.cpu(), k=8)
edge_index_cuda = knn_graph(pos.cuda(), k=8)
```
```python
print(edge_index_cpu.shape)
torch.Size([2, 256])

print(edge_index_cuda.shape)
torch.Size([2, 250])
```
Each point should have 8 edges, so the expected number of edges is 32 * 8 = 256. So the cpu result is correct, while the cuda result misses 6 edges. 
In particular, somewhy on cuda the node 14 has only six neighbors and the node 20 has only four neighbors.
```python
print(edge_index_cuda[:, edge_index_cuda[1] == 14])
tensor([[13, 20, 31, 24,  4, 17],
        [14, 14, 14, 14, 14, 14]], device='cuda:0')

print(edge_index_cuda[:, edge_index_cuda[1] == 20])
tensor([[14, 31, 13, 24],
        [20, 20, 20, 20]], device='cuda:0')
```
Maybe I'm missing something? I would appreciate any comments on this. 

### Environment

* PyG version: 2.0.4
* torch-cluster version: 1.6.0
* PyTorch version: 1.11.0
* OS: Windows
* Python version: 3.9.12
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda

**Comment by rusty1s** [comment]
Thanks for reporting. Will look into this in the next week.

**Comment by rusty1s** [comment]
I fixed this in in `torch-cluster` see https://github.com/rusty1s/pytorch_cluster/commit/113e8a6abbe3c2856b1656f111bb4716770ddfdc.

The bug was that we set an initial threshold for the maximum distance between two nodes that was too low. For an easy fix on your end, `pos = pos / 100.` does the trick as well. Sorry for the inconveniences!
