### ISSUE TITLE
UserWarning error from transform tutorial using ShapeNet

### ISSUE THREAD

**Issue by Jaceyjc** [pyg-team/pytorch_geometric#4916]
### 🐛 Describe the bug

Hi, I am going through the transform section on the tutorial page, and I have not been able to resolve the following error:

```import torch_geometric.transforms as T
from torch_geometric.datasets import ShapeNet

dataset_T = ShapeNet(root='/tmp/ShapeNet', categories=['Airplane'],
                   pre_transform=T.KNNGraph(k=6))

>>> /home/user/.conda/envs/pytorch/lib/python3.9/site-packages/torch_geometric/data/dataset.py:150: UserWarning: The `pre_transform` argument differs from the one used in the pre-processed version of this dataset. If you want to make use of another pre-processing technique, make sure to sure to delete '/tmp/ShapeNet/processed' first
  warnings.warn(
```

A component from the resulting transformed dataset shows:
```
dataset_T[0] 
>>> Data(x=[2518, 3], y=[2518], pos=[2518, 3], category=[1])
```
which is incorrect.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: Linux
* Python version: 3.9
* CUDA/cuDNN version: -
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
The `pre_transform` is only applied when processing the dataset for the first time. Try to remove the processed data in `/tmp/ShapeNet/processed` first and run again.

**Comment by Jaceyjc** [comment]
Thank you for the quick reply - resolved!
