### ISSUE TITLE
How do I ClusterData the whole Dataset of graphs?

### ISSUE THREAD

**Issue by davodogster** [pyg-team/pytorch_geometric#4923]
### 🐛 Describe the bug

Hello, I am facing this error when I try to convert one graph in the dataset to ClusterData.
Also, I want to convert a whole PyG Dataset to a ClusterData set. Is it possible?
Similarly can I convert an InMemory Dataset to a ClusterDataset?

![image](https://user-images.githubusercontent.com/46079516/177465360-6dbba37b-49de-4e5e-b0c9-6e186304d1df.png)

Thanks, Sam

### Environment

Env:
Python: 3.9.7
Torch: 1.10.0
Ubuntu: 20.04
CUDA: 11.3.1
PyG: 2.0.3

**Comment by rusty1s** [comment]
Thanks for reporting. This should be fixed with #4932.
