### ISSUE TITLE
DataLoader returns dictionary instead of GraphDataBatch

### ISSUE THREAD

**Issue by Hamidreza3252** [pyg-team/pytorch_geometric#4928]
### 🐛 Describe the bug

I am training a model using pytorch geometric on Ubuntu 20.04. The data loader (of the type **torch_geometric.loader.dataloader.DataLoader**) returns a dictionary instead of **torch_geometric.data.batch.GraphDataBatch**,. The same code with the same conda environment works fine on Ubuntu 16.04. Just wondering if anything is wrong with pytorch geometric and anyone else has encountered this error. 

I believe you can test it using a simple code, since my code is huge, I am not able to provide it here.. 

### Environment

* torch-geometric  2.0.5  
* torch-scatter  2.0.9  
* torch-sparse   0.6.13  
* PyTorch version::  1.10.1          py3.8_cuda11.3_cudnn8.2.0_0
* OS: Ubuntu 20.04
* Python version: 3.8.13  
* CUDA/cuDNN version:  11.3  
* How you installed PyTorch and PyG (`conda`, `pip`, source):  
    - pytorch 
    from here:  https://pytorch.org/get-started/previous-versions/ 
    `conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge`  
    - PyG: cloned the source from github and ran the following command n my conda environment: 
    `python setup.py install`  

* Any other relevant information (*e.g.*, version of `torch-scatter`):  mentioned above

**Comment by rusty1s** [comment]
Do you have an example to reproduce? In general, the `DataLoader` should only return a dictionary in case your dataset returns a dictionary to begin with. Might this be the case? Are elements of your data of type `dict` or of type `Data`?

**Comment by Hamidreza3252** [comment]
I could resolve the issue by using one of your earlier commits, not the latest one. 

```
commit d451d6d20287b03cbe5036e5c53ee5f633f3c429
Author: Matthias Fey <matthias.fey@tu-dortmund.de>
Date:   Wed Mar 30 12:36:22 2022 +0200

    PyTorch Lightning 1.6 support (#4377)
    * PL 1.6 support
    * update
    * typo
    * update
    * typo
    * typo
```

There is a lot of lines of codes if I want to share. But what I can add helping you reproduce it at your and is the structure of the class inherited from DataLoader.. 

```
from torch_geometric.data import Data, InMemoryDataset

class GraphData(Data):
    def __inc__(self, key, value, *args):
        if (key == "edge_index"):
            return self.x.size(0)
        else:
            return 0

class InMemoryTest(InMemoryDataset):
    ....
    def get(self, idx):
       ....  some calculations 
        data = GraphData(x, y, ...)  # with some other keywords 
        print("data  {}".format(data))
        return data

```
**output:** 
data  GraphData(x=[276, 10], edge_index=[2, 4697], y=[60], cluster=[276], identifier=[24, 2], plus some other keys when I instantiated GraphData above. 

The problem happens in the training loop, when the data loader call this get method. For example: 

```
        for data in data_loader:
            num_graphs = data.num_graphs
            data = data.to(self.device)
```

Using the earlier commit, these lines work just fine as the type of the data is GraphData, however, using the latest commit, these lines fail as the type of the data is dictionary. Is it by the new design or a bug? Returning a dictionary is bizarre anyway...

**Comment by rusty1s** [comment]
Thank you! I think this issue is related to https://github.com/pyg-team/pytorch_geometric/issues/4848 (I am leaving only one of them open now). We will work on a fix ASAP!
