### ISSUE TITLE
batch length seems incorrect

### ISSUE THREAD

**Issue by cinntamani** [pyg-team/pytorch_geometric#4930]
### 🐛 Describe the bug

When a batch of graphs is formed, len(batch) does not seem to return the intuitive number of graphs:
```
import torch_geometric.data
d = torch_geometric.data.Data(x=torch.tensor([[1.], [2.]]), edge_index=torch.LongTensor([[0], [1]]))
batch = torch_geometric.data.batch.Batch.from_data_list([d] * 10)
print(len(batch))
4
print(batch.num_graphs)
10
```
It seems it would be better to define Batch.\__len\__() to return Batch.num_graphs.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: macOS 12.3.1
* Python version: 3.10
* CUDA/cuDNN version: NA
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. This is now fixed in https://github.com/pyg-team/pytorch_geometric/pull/4931. Previously, `len(batch)` returned the number of attributes (which is indeed not very intuitive).
