### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_geometric.nn.resolver'

### ISSUE THREAD

**Issue by FedeOtto** [pyg-team/pytorch_geometric#4949]
### 🐛 Describe the bug

Studying the `DimeNet` implementation I get the following error when I try to import

    from torch_geometric.nn.resolver import activation_resolver

    ModuleNotFoundError: No module named 'torch_geometric.nn.resolver'

Actually I cannot find such module in the docs, is that deprecated?

### Environment

* PyG version: `2.0.4`
* PyTorch version: `1.11.0`
* OS: Windows 10
* Python version:  `3.8.12`
* CUDA/cuDNN version: /
* How you installed PyTorch and PyG (`conda`, `pip`, source): `conda`
* Any other relevant information (*e.g.*, version of `torch-scatter`): /

**Comment by Padarn** [comment]
`activation_resolver` was added in https://github.com/pyg-team/pytorch_geometric/pull/4749, its not in the release version of pytorch_geometricc yet, you'd have to install from master.
