### ISSUE TITLE
Unintuitive --normalize_features option in benchmark scripts

### ISSUE THREAD

**Issue by gau-nernst** [pyg-team/pytorch_geometric#4966]
### 🐛 Describe the bug

In the reference benchmark script for GAT [here](https://github.com/pyg-team/pytorch_geometric/blob/master/benchmark/citation/gat.py), the `--normalize-features` option is probably not behaving what it is intended to do. As noted by the official Python argparse [documentation](https://docs.python.org/3/library/argparse.html#type)

> The [bool()](https://docs.python.org/3/library/functions.html#bool) function is not recommended as a type converter. All it does is convert empty strings to False and non-empty strings to True. This is usually not what is desired.

In other words,

```bash
python gat.py --dataset=Cora --normalize_features=False  # this will silently evaluate to normalize_features=True
python gat.py --dataset=Cora --normalize_features=0  # same problem as above, since "0" is a string
python gat.py --dataset=Cora --normalize_features="" # the only way to turn off feature normalization correctly
```

One alternative would be

```python
parser.add_argument('--no-normalize_features', action="store_true")
...

dataset = get_planetoid_dataset(args.dataset, not args.no_normalize_features)
```

It is not a huge bug, but I think it would improve usability for the users, as well as providing better reference scripts.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: macOS (ARM)
* Python version: 3.10
* CUDA/cuDNN version: NA
* How you installed PyTorch and PyG (`conda`, `pip`, source): PyTorch through conda, PyG through pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): NA

**Comment by rusty1s** [comment]
Oh shit, I was too fast. Thanks for checking!
