### ISSUE TITLE
Broken Link to MoleculeNet website

### ISSUE THREAD

**Issue by pgmikhael** [pyg-team/pytorch_geometric#4984]
### 📚 Describe the documentation issue

MoleculeNet website link in the docstring [https://moleculenet.ai/datasets-1] routes to wrong websites (possibly due to the .ai anguilla domain). https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/datasets/molecule_net.py#L12 

### Suggest a potential alternative/fix

https://moleculenet.org/datasets-1 should work instead

**Comment by rusty1s** [comment]
Thanks for reporting. Fixed in master.
