### ISSUE TITLE
Captum explainability interface doesn't work anymore

### ISSUE THREAD

**Issue by jan0b** [pyg-team/pytorch_geometric#4989]
## Bug Description
One can reproduce the error by using the PyG's own example code for the Captum interface (https://github.com/pyg-team/pytorch_geometric/blob/24a185e7268f70ee549c7a424b9426b9a18b5706/examples/captum_explainability.py). The "testing.py" script is exactly the script from the example from the link. A few weeks back the interface worked perfectly, but now there is an error thrown by the edge index's.

### **Calculating edge greadients** aka _mask_type='edge'_

Traceback (most recent call last):
* File "<>/pyg_tests/testing.py", line 56, in <module>
  * ig_attr_edge = ig.attribute(edge_mask.unsqueeze(0), target=target,
* File "<>/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 278, in attribute
  * grads = _batched_operator(
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/batching.py", line 156, in _batched_operator
  * all_outputs = [
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/batching.py", line 157, in <listcomp>
  * operator(
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/gradient.py", line 96, in compute_gradients
  * outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/common.py", line 500, in _run_forward
  * output = forward_func(
* File "<>/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  * return forward_call(*input, **kwargs)
* File "<>/lib/python3.8/site-packages/torch_geometric/nn/models/explainer.py", line 65, in forward
  * set_masks(self.model, mask.squeeze(0), args[1],
* File "<>/lib/python3.8/site-packages/torch_geometric/nn/models/explainer.py", line 17, in set_masks
  * loop_mask = edge_index[0] != edge_index[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

### **Calculating node gradients** aka _mask_type='node'_

Traceback (most recent call last):
* File "<>/pyg_tests/testing.py", line 76, in <module>
  * ig_attr_node = ig.attribute(data.x.unsqueeze(0), target=target,
*  File "<>/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 278, in attribute
   * grads = _batched_operator(
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/batching.py", line 156, in _batched_operator
  * all_outputs = [
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/batching.py", line 157, in <listcomp>
  * operator(
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/gradient.py", line 96, in compute_gradients
  * outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
* File "<>/lib/python3.8/site-packages/captum/attr/_utils/common.py", line 500, in _run_forward
  * output = forward_func(
* File "<>/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  * return forward_call(*input, **kwargs)
* File "<>/lib/python3.8/site-packages/torch_geometric/nn/models/explainer.py", line 76, in forward
  * x = self.model(mask.squeeze(0), *args)
* File "<>/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  * return forward_call(*input, **kwargs)
* File "<>/pyg_tests/testing.py", line 25, in forward
  * x = F.relu(self.conv1(x, edge_index))
* File "<>/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
  * return forward_call(*input, **kwargs)
* File "<>/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 172, in forward
  * edge_index, edge_weight = gcn_norm(  # yapf: disable
* File "/<>/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 58, in gcn_norm
  * edge_index, tmp_edge_weight = add_remaining_self_loops(
* File "<>/lib/python3.8/site-packages/torch_geometric/utils/loop.py", line 198, in add_remaining_self_loops
  * mask = edge_index[0] != edge_index[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

### **Calculating node and edge gradients** aka _mask_type='node_and_edge'_
Same error message as when only calculating the edge gradients.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: Linux 4.18.0
* Python version: 3.8.13
* CUDA/cuDNN version: cuda11.3_cudnn8.2.0_0
* How you installed PyTorch and PyG (`conda`, `pip`, source): both with conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): captum 0.2.0 via pip

**Comment by rusty1s** [comment]
Mh, I cannot reproduce this :(

Can you try to re-process your data/delete the dataset folder, and [upgrade to latest master](https://github.com/pyg-team/pytorch_geometric#installation)?

**Comment by jan0b** [comment]
Updating the Captum version to 0.5. solved the issue. Thank you for your help.
