### ISSUE TITLE
Wrong Import (UniMP Example)?

### ISSUE THREAD

**Issue by imethanlee** [pyg-team/pytorch_geometric#4992]
### 🐛 Describe the bug

It seems the `'MaskLabel'` module is not defined in `torch_geometric.nn`.
https://github.com/pyg-team/pytorch_geometric/blob/50f22b18be387a81da06465694d944fae13e30ec/examples/unimp_arxiv.py#L8

Could you please check it out?

### Environment

* PyG version:2.04
* PyTorch version:1.10.2
* OS:LINUX
* Python version:3.8
* CUDA/cuDNN version:11.2
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):None

**Comment by rusty1s** [comment]
We just recently added this in, see [here](https://github.com/pyg-team/pytorch_geometric#nightly-and-master) on how to update to master.
