### ISSUE TITLE
Support for multiple aggregations in `SAGEConv`

### ISSUE THREAD

**Issue by lightaime** [pyg-team/pytorch_geometric#5009]

**Comment by lightaime** [comment]
The `SAGEConv` should support multiple aggregations already by using `combine`(https://github.com/pyg-team/pytorch_geometric/pull/5000) by setting the correct `in_channels`. Do we still need a specific fix for this? @rusty1s

**Comment by rusty1s** [comment]
I always thought it might be cool to add support for this without the user needing to specify a different number of input channels (so that `SAGEConv` is tunable across a variety of different aggregations). WDYT?

**Comment by lightaime** [comment]
Sure, that sounds good! Will open a PR later to use `combine` to support this.
