### ISSUE TITLE
Mac MPS device support

### ISSUE THREAD

**Issue by kirisaki1312** [pyg-team/pytorch_geometric#5012]
### 🚀 The feature, motivation and pitch

I‘m an apple M1 mac user. Recently, pytorch has added MPS device support since 1.12.* version. Can pytorch_geometric also follow up the support for MPS devices as soon as possible? This will help me a lot. So much gratitude to all contributors!

**Comment by rusty1s** [comment]
Please see https://github.com/pyg-team/pytorch_geometric/issues/4776. Closing this  issue here, happy to continue discussion in the other issue.
