### ISSUE TITLE
Noisy warning raised by the collate function

### ISSUE THREAD

**Issue by chenzhekl** [pyg-team/pytorch_geometric#5024]
### 🐛 Describe the bug

After upgrading to PyTorch 1.12, I got the following warnings while collating data:

```
/opt/conda/lib/python3.8/site-packages/torch_geometric/data/collate.py:150: UserWarning: A
n output with one or more elements was resized since it had shape [58791], which does not 
match the required output shape [19597, 3]. This behavior is deprecated, and in a future P
yTorch release outputs will not be resized unless they have zero elements. You can explici
tly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Tr
iggered internally at  ../aten/src/ATen/native/Resize.cpp:17.)                            
  value = torch.cat(values, dim=cat_dim or 0, out=out)
```

I guess the cause is the same as this one https://github.com/pytorch/pytorch/issues/71063 for PyTorch. Their fix is directly applicable to PyG.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.12.0
* OS: Ubuntu
* Python version: 3.8.10
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by chenzhekl** [comment]
Thank you for your prompt reply! I can confirm that it has been fixed in nightly. But now I am facing a similar problem as https://github.com/pyg-team/pytorch_geometric/issues/4848, and I am not using PyTorch Lightning. Anyway, I will close this issue.

**Comment by rusty1s** [comment]
Yeah, still working on a fix. Do you have a simple example to reproduce without PL dependency?

**Comment by chenzhekl** [comment]
Probably. Let me see if it is possible to distill the code to a small example.

**Comment by sebk26** [comment]
* PyG version: 2.0.4
* PyTorch version: 1.12.0
* OS: CentOS Linux
* Python version: 3.9.6
* CUDA/cuDNN version: 11.3.1
* How you installed PyTorch and PyG: pip

This produces the same warning as @chenzhekl described:
```python
import torch
import numpy as np
import time
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader



    
class MyIterDataset(torch.utils.data.IterableDataset):
    def __init__(self,training=False,stride=1,seed=42):
        super(MyIterDataset).__init__()

        self.start    = 0
        self.end      = 1000
        self.training    = training
        self.stride      = stride
        self.window      = 600 - stride
        
        #reproducibility
        self.seed = seed
        self.rng = np.random.default_rng(seed)
        
    def __len__(self):
        return (self.end-self.start)*self.window

    
    def __iter__(self):
        f_ids = np.arange(self.start,self.end)
        if self.training: self.rng.shuffle(f_ids)

        for idx in f_ids:
            n_edges = self.rng.integers(5000,12000)
            n_nodes = self.rng.integers(1500,2500)
            edge_index = torch.randint(low=1,high=n_nodes,size=(2,n_edges))
            edge_attr = torch.rand(n_edges,4) * self.rng.integers(1,20)
            
            inds = np.arange(self.window) 
            if self.training: self.rng.shuffle(inds)
            for k in range(self.window-1):
                pos         = torch.rand(n_nodes,3) * self.rng.integers(1,5)
                
                input1 = torch.rand(n_nodes,2) * self.rng.integers(1,8)
                input2 = torch.rand(n_nodes,4) * self.rng.integers(3,12)
                X = torch.cat([input1,input2],dim=1)

                out1 = torch.rand(n_nodes,3) * self.rng.integers(1,4)
                
                yield Data(pos=pos,edge_index=edge_index,edge_attr=edge_attr,x = X, 
                           y=X)


if __name__ == '__main__':
    train_dat = MyIterDataset(training=True)
    sl = 0.01
    loader = DataLoader(train_dat,batch_size=2,prefetch_factor=2,num_workers=2)
    for i,b in enumerate(loader):
        #print('{} {}'.format(b[0].edge_index,b[1].edge_index))
        print(f'{i=}')
        time.sleep(sl)
        if i>10:
            break
    exit(0)
```

**Comment by sebk26** [comment]
> Thank you for your prompt reply! I can confirm that it has been fixed in nightly. But now I am facing a similar problem as #4848, and I am not using PyTorch Lightning. Anyway, I will close this issue.

Maybe open the issue again until it's fixed?

**Comment by chenzhekl** [comment]
> > Thank you for your prompt reply! I can confirm that it has been fixed in nightly. But now I am facing a similar problem as #4848, and I am not using PyTorch Lightning. Anyway, I will close this issue.
> 
> 
> 
> @chenzhekl: Maybe open the issue again until it's fixed?

I prefer to keep the issue closed, as it has been fixed in the master branch. :)

**Comment by sebk26** [comment]
Oh, yes, i can confirm, it's also fixed for me. 
@chenzhekl Sorry for bothering!

**Comment by Amadeus-System** [comment]
Hi. I am experiencing same error in google colab pro plus environment.

**Comment by jangkj09** [comment]
How are you supposed to fix this problem if you are not building from source?

**Comment by chenzhekl** [comment]
@jangkj09 There is a [nightly package](https://pypi.org/project/pyg-nightly/) on PyPI. But you may still need a working compiler to install it.

```
pip install pyg-nightly
```

**Comment by jangkj09** [comment]
Thanks!
