### ISSUE TITLE
 RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

### ISSUE THREAD

**Issue by waqar12868** [pyg-team/pytorch_geometric#5028]
### 🐛 Describe the bug

 I ran the clique pooling based graph neural network model, which is working correctly on the CPU, but when I tried to run it on GPU, I got an error.  Here is the model:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001, weight_decay=0.001) # lr=0.01, weight_decay=5e-4
data = dataset[0].to(device)
def train(epoch):
  model.train()

  loss_all = 0
  for data in train_loader:
    data = data.to(device)
    optimizer.zero_grad()
    output = model(data)
    loss = F.nll_loss(output, data.y.to(device))
    loss.backward()
    loss_all += data.num_graphs * loss.item()
    optimizer.step()
  return loss_all / len(train_dataset)

def test(loader):
  model.eval()

  correct = 0
  for data in loader:
    data = data#.to(device)
    pred = model(data).max(dim=1)[1]
    correct += pred.eq(data.y).sum().item()
  return correct / len(loader.dataset)

for epoch in range(1, 100):
  loss = train(epoch)
  train_acc = test(train_loader)
  test_acc = test(test_loader)
  print('Epoch: {:03d}, Loss: {:.5f}, Train Acc: {:.5f}, Test Acc: {:.5f}'.
        format(epoch, loss, train_acc, test_acc))
 

The traceback log is here:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-15-952e9c7a1d38>](https://localhost:8080/#) in <module>()
     31 
     32 for epoch in range(1, 100):
---> 33   loss = train(epoch)
     34   train_acc = test(train_loader)
     35   test_acc = test(test_loader)

5 frames
[<ipython-input-3-5bdba30d2477>](https://localhost:8080/#) in <listcomp>(.0)
    253             0,
    254             torch.tensor(clique, dtype=torch.long)
--> 255         )) for clique in considered_cliques
    256       ]
    257     )

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

Please can you guide me about this error?
Thank you.

**Comment by rusty1s** [comment]
To which example do you refer to? Isn‘t that because the `data.to(device)` call is commented out?

**Comment by waqar12868** [comment]
I am using the graph convolution model with clique pooling. I removed the comments from data.to(device) but again I got an error. Here is the complete model with training:

from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, global_mean_pool
from CliquePoolingLayer import *

#https://github.com/rusty1s/pytorch_geometric/blob/cff934ec28fb70d05d434c74111047078667ace8/examples/proteins_topk_pool.py#L25
dataset = TUDataset(root='/home/waqar.ali/GDL_Project-main/clique_pooling', name='PROTEINS')
dataset = dataset.shuffle()

n = len(dataset) // 10
b_size = 2
test_dataset = dataset[:n]
train_dataset = dataset[n:]
test_loader = DataLoader(test_dataset, batch_size=b_size)
train_loader = DataLoader(train_dataset, batch_size=b_size)


class Net(torch.nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = GCNConv(dataset.num_node_features, 16)
    self.conv2 = GCNConv(16, 32)
    self.pool  = CliquePooling('avg')
    self.conv3 = GCNConv(32, dataset.num_classes, add_self_loops=False)

  def forward(self, data):
    ## 1. Obtain node embeddings:
    x, edge_index, batch = data.x, data.edge_index, data.batch

    # First GCN
    x = self.conv1(x, edge_index)
    x = F.relu(x)
    x = F.dropout(x, training=self.training)
    # Second GCN
    x = self.conv2(x, edge_index)
    x = F.relu(x)
    x = F.dropout(x, training=self.training)
    x, d_edge_index, _, d_batch, _ = self.pool(x, edge_index, None, batch)
    x = F.relu(x)
    x = F.dropout(x, training=self.training)
    # Third GCN
    x = self.conv3(x, d_edge_index)

    ## 2. Readout layer:
    x = global_mean_pool(x, d_batch)

    x = F.log_softmax(x, dim=-1)

    return x


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001, weight_decay=0.001) # lr=0.01, weight_decay=5e-4

def train(epoch):
  model.train()

  loss_all = 0
  for data in train_loader:
    data = data.to(device)
    optimizer.zero_grad()
    output = model(data)
    loss = F.nll_loss(output, data.y).to(torch.device('cuda'))
    loss.backward()
    loss_all += data.num_graphs * loss.item()
    optimizer.step()
  return loss_all / len(train_dataset)


def test(loader):
  model.eval()

  correct = 0
  for data in loader:
    data = data.to(device)
    pred = model(data).max(dim=1)[1]
    correct += pred.eq(data.y).sum().item()
  return correct / len(loader.dataset)


for epoch in range(1, 500):
  loss = train(epoch)
  train_acc = test(train_loader)
  test_acc = test(test_loader)
  print('Epoch: {:03d}, Loss: {:.5f}, Train Acc: {:.5f}, Test Acc: {:.5f}'.
        format(epoch, loss, train_acc, test_acc))


backtrace log:

Traceback (most recent call last):
  File "CliquePooling.py", line 86, in <module>
    loss = train(epoch)
  File "CliquePooling.py", line 66, in train
    output = model(data)
  File "/home/waqar.ali/.conda/envs/kplex-pool1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "CliquePooling.py", line 39, in forward
    x, d_edge_index, _, d_batch, _ = self.pool(x, edge_index, None, batch)
  File "/home/waqar.ali/.conda/envs/kplex-pool1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/waqar.ali/GDL_Project-main/clique_pooling/CliquePoolingLayer.py", line 258, in forward
    )) for clique in considered_cliques
  File "/home/waqar.ali/GDL_Project-main/clique_pooling/CliquePoolingLayer.py", line 258, in <listcomp>
    )) for clique in considered_cliques
RuntimeError: Input, output and indices must be on the current device

**Comment by rusty1s** [comment]
IMO, this looks to be a mistake in your clique pooling layer (maybe it expects hard-coded devices)? You should check the devices of tensors right before the error and adjust accordingly.

**Comment by waqar12868** [comment]
Exactly, the problem was in the clique pooling layer, and I resolved it. Thank you for your reply.
