### ISSUE TITLE
Something questions about torch_geometric.data.HeteroData

### ISSUE THREAD

**Issue by downeykking** [pyg-team/pytorch_geometric#5040]
### 🐛 Describe the bug

```
from torch_geometric.loader import NeighborLoader
train_loader = NeighborLoader(graph, input_nodes=(labeled_class, train_idx),
                                  num_neighbors=[10] * args.n_layers,
                                  shuffle=True, batch_size=args.batch_size)
device = torch.device('cuda:' + args.device_id if torch.cuda.is_available() else 'cpu')
batch = next(iter(train_loader))
for key in batch.x_dict.keys():
    batch.x_dict[key] = batch.x_dict[key].to(device)
```
I have a HeteroData `graph`  and i sample it by `NeighborLoader`.
Then i want to put the batch.x_dict[key] (`x`) to cuda, but finally it is still in cpu.
i solve the problem by these codes:
`x_dict = {node_type: batch[node_type].x.to(device) for node_type in batch.to_dict().keys() if node_type in node_types}
        edge_index_dict = {edge_type: batch[edge_type].edge_index.to(
            device) for edge_type in batch.to_dict().keys() if edge_type in edge_types}`

I wonder why original code couldn't put the `x` to cuda? Thanks in advance!

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.1.10
* OS: linux
* Python version: 3.9
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
torch-cluster         1.6.0
torch-geometric       2.0.4
torch-scatter         2.0.9
torch-sparse          0.6.13
torch-spline-conv     1.2.1

**Comment by Padarn** [comment]
> I wonder why original code couldn't put the x to cuda?

Sorry I don't fully understand what you mean by this. Do you mean that you are unable to move it to CUDA afterwards, or that the result of the sampling is in CPU?

We do move the sampling graph to CPU: https://github.com/pyg-team/pytorch_geometric/blob/6ed5caff57cc088f4216694bbcf496c65fbadea8/torch_geometric/loader/neighbor_loader.py#L70

But I don't know if we expect the features to be on GPU.

**Comment by rusty1s** [comment]
The `batch.x_dict` is a temporary object and will be re-created everytime you request it. You cannot do any assignment to it. The recommended way to put your batch to the GPU is
```python
batch = batch.to(device)
```

**Comment by downeykking** [comment]
> 

thanks for your response! I just want to put the features `x` to the GPU because the batch of graph has other big but useless data which is unnecessary to be calculated in GPU.

**Comment by downeykking** [comment]
> > I wonder why original code couldn't put the x to cuda?
> 
> Sorry I don't fully understand what you mean by this. Do you mean that you are unable to move it to CUDA afterwards, or that the result of the sampling is in CPU?
> 
> We do move the sampling graph to CPU:
> 
> https://github.com/pyg-team/pytorch_geometric/blob/6ed5caff57cc088f4216694bbcf496c65fbadea8/torch_geometric/loader/neighbor_loader.py#L70
> 
> But I don't know if we expect the features to be on GPU.

thanks for your response! I just want to put the features x to the GPU because the batch of graph has other big but useless data which is unnecessary to be calculated in GPU.

**Comment by downeykking** [comment]
> 

thanks for your response! I just want to put the features x to the GPU because the batch of graph has other big but useless data which is unnecessary to be calculated in GPU. What do you suggest to solve this problem? Thanks in advance! :)

**Comment by downeykking** [comment]
> The `batch.x_dict` is a temporary object and will be re-created everytime you request it. You cannot do any assignment to it. The recommended way to put your batch to the GPU is
> 
> ```python
> batch = batch.to(device)
> ```

thanks for your response! I just want to put the features x to the GPU because the batch of graph has other big but useless data which is unnecessary to be calculated in GPU. What do you suggest to solve this problem? Thanks in advance! :)

**Comment by rusty1s** [comment]
```python
batch = batch.to(device‚ ‘x‘)
