### ISSUE TITLE
Release not done after pushes on master

### ISSUE THREAD

**Issue by Aleksandar1932** [pyg-team/pytorch_geometric#5048]
### 😵 Describe the installation problem

I have noticed that new commits have been pushed on master, i.e. PRs are merged, thus the docs is re-built automatically including those new changes.

However a new release hasn't been done, and on pypi and the private registry by PYG it is still the version `2.0.4` from Mar 12 2022. This causes inconsistencies and new features are not present in the package while they are present in the docs.

One such example is: `https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/__init__.py`, `LightningLinkData` which is introduced in this [commit](https://github.com/pyg-team/pytorch_geometric/commit/6c3c235a653da2f11231eec70a6d010d345f87c7) is available in the [docs](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.LightningLinkData), however is not present in the latest [release](https://github.com/pyg-team/pytorch_geometric/archive/refs/tags/2.0.4.zip).

This causes inconsistencies between the docs and the codebase which can be frustrating and time consuming. In a way that there is difference between `latest` and the actual latest version.

### Environment

* PyG version: `2.0.4`
* PyTorch version: `1.12.0`
* OS: macOS Monterey
* Python version: `3.9.11`
* CUDA/cuDNN version: `n/a` using cpu
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip`
* Any other relevant information (*e.g.*, version of `torch-scatter`): not relevant

**Comment by Aleksandar1932** [comment]
Even a version bump is done to `2.0.5`.

**Comment by rusty1s** [comment]
Yes, we are actively working towards a new release which should be available in 2-3 weeks.

**Comment by rusty1s** [comment]
Please also note that you can simply select the 2.0.4 version in the documentation.
