### ISSUE TITLE
Cannot Import LinkNeighborLoader from  torch_geometric.loader

### ISSUE THREAD

**Issue by nishant42491** [pyg-team/pytorch_geometric#5050]
### 🐛 Describe the bug

I get the message ImportError: cannot import name 'LinkNeighborLoader' from 'torch_geometric.loader' (/usr/local/lib/python3.7/dist-packages/torch_geometric/loader/__init__.py) whilst importing the LinkNeighbourLoader Class.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/79035403/180852810-c5ec1c11-0ae7-4108-a63f-b9f66a3b019e.png">

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.12.0+cu113
* OS: linux
* Python version: 3.7
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch_scatter-2.0.9-cp37-cp37m-linux_x86_64.whl
* torch_sparse-0.6.14-cp37-cp37m-linux_x86_64.whl

**Comment by rusty1s** [comment]
We just recently added the `LinkNeighborLoader` to PyG. We are crafting a new release soon. Until then, you need to install from master or nightly (as described in the README).
