### ISSUE TITLE
Median Aggregation Support

### ISSUE THREAD

**Issue by storyandwine** [pyg-team/pytorch_geometric#5054]
### 🚀 The feature, motivation and pitch

I'm working on a noise graph, some papers show that the interference of noise can be largely reduced using median aggregation.

Papers:
Robustness of Graph Neural Networks at Scale [NIPS'21]
Understanding Structural Vulnerability in Graph Convolutional Networks [IJCAI'21]

### Alternatives

Using torch.argsort like https://github.com/EdisonLeeeee/MedianGCN in the large-scale graph is time costing.
The CUDA-accelerated version of median aggregation is implemented here,https://github.com/sigeisler/robustness_of_gnns_at_scale. However, it requires a specific software version and seems to have some inexplicable errors, which makes debugging difficult for many people who do not know CUDA programming.
If Pyg could support this kind of aggregation, it would be a great joy for the community! Thanks in advance.

**Comment by rusty1s** [comment]
Yeah, I always thought this is super challenging to implement in an efficient way. Thanks for the pointers! We can try to look into it but it currently has lower priority.

**Comment by flandolfi** [comment]
Maybe I'm wrong, but I don't think we can break the $\log(n)$ depth complexity of parallel (arg)sort (that is basically the time complexity in a parallel setting). The (sequential) time complexity of the [selection algorithm](https://en.wikipedia.org/wiki/Selection_algorithm) for computing the median is $O(n)$, and even doing an approximation using median of medians we would obtain a log-depth complexity. So, I think we could use sorting with no hesitation (btw, I don't think the slow part in the [official `MedianGCN` implementation](https://github.com/EdisonLeeeee/MedianGCN) is really the argsort, but rather the fact that they compute a masking and a median [for every different node degree](https://github.com/EdisonLeeeee/MedianGCN/blob/b1f3db62bf378935624f3f23cc31e3ce83f8908d/median_pyg.py#L94), which could become very time expensive).

I tried implementing the `MedianAggregation` using indeed stable sorting, which is available in the newest versions of PyTorch. Here is the code:
```python
from typing import Optional

import torch
from torch import Tensor

from torch_geometric.nn.aggr.base import Aggregation


class MedianAggregation(Aggregation):
    def forward(self, x: Tensor, index: Optional[Tensor] = None,
                ptr: Optional[Tensor] = None, dim_size: Optional[int] = None,
                dim: int = -2) -> Tensor:
        self.assert_index_present(index)  # we could also expand `ptr` to an index
        
        if dim_size is None:
            dim_size = index.max() + 1
        
        # compute the two median indices (they coincide if the number of elements is odd)
        count = torch.bincount(index, minlength=dim_size)
        cumsum = torch.cumsum(count, dim=0)
        l_idx = cumsum - count.div(2, rounding_mode='trunc') - 1
        r_idx = cumsum - (count + 1).div(2, rounding_mode='trunc')

        # shape used for expansions 
        # (1, ..., 1, -1, 1, ..., 1)
        shape = [1] * x.dim()
        shape[dim] = -1

        # two sorts: the first one on the value, the second (stable) on the indices
        x, x_perm = torch.sort(x, dim=dim)
        index = index.view(*shape).expand_as(x)
        index = index.take_along_dim(x_perm, dim=dim)
        index, index_perm = torch.sort(index, dim=dim, stable=True)
        x = x.take_along_dim(index_perm, dim=dim)

        # median as an average of the two central elements
        l_med = x.index_select(dim, l_idx)
        r_med = x.index_select(dim, r_idx)

        # if the number of elements is 0, return 'nan'
        out_mask = (count > 0).view(*shape)
        
        return torch.where(out_mask, 0.5*l_med + 0.5*r_med, float('nan'))
```
I did not made a proper testing, only some examples on the terminal:
```python
In [10]: x = torch.randint(10, size=(10, 5))
    ...: idx, _  = torch.randint(4, size=(10,)).sort()
    ...: aggr = MedianAggregation()
    ...: x, idx, aggr(x, idx, dim=0)
Out[10]: 
(tensor([[4, 6, 6, 3, 5],
         [3, 8, 1, 8, 3],
         [0, 4, 1, 6, 8],
         [0, 1, 9, 2, 1],
         [7, 3, 4, 9, 5],
         [4, 2, 1, 0, 9],
         [3, 6, 4, 3, 4],
         [7, 3, 7, 2, 9],
         [4, 9, 8, 7, 4],
         [5, 9, 3, 4, 4]]),
 tensor([0, 0, 0, 1, 1, 2, 2, 2, 3, 3]),
 tensor([[3.0000, 6.0000, 1.0000, 6.0000, 5.0000],
         [3.5000, 2.0000, 6.5000, 5.5000, 3.0000],
         [4.0000, 3.0000, 4.0000, 2.0000, 9.0000],
         [4.5000, 9.0000, 5.5000, 5.5000, 4.0000]]))
```

**Comment by rusty1s** [comment]
I think this is pretty cool! I haven't verified the correctness yet, but happy to do that if you are interested in contributing this implementation. Let me know!

**Comment by flandolfi** [comment]
Sure, I'll willingly self-assign. But I have a question: should I make a PR in PyG or in torch-scatter (as a "composite", maybe)? In the second case I'll have to wait to be public in pip/conda before putting an aggregation in PyG. Let me know!

**Comment by rusty1s** [comment]
Let's go with the first option and integrate it directly into PyG :)

**Comment by flandolfi** [comment]
Perfect, I'll do a PR as soon as possible!
