### ISSUE TITLE
Some questions on Linear layers of Conv layers

### ISSUE THREAD

**Issue by downeykking** [pyg-team/pytorch_geometric#5119]
### 🐛 Describe the bug

In SAGEConv, we have {x_i}^' = W1x1 + mean(x_j) like https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.SAGEConv
and in the source code, we have
```python
self.lin_l = Linear(aggr_out_channels, out_channels, bias=bias)
        if self.root_weight:
            self.lin_r = Linear(in_channels[1], out_channels, bias=False)
...
if isinstance(x, Tensor):
            x: OptPairTensor = (x, x)

        if self.project and hasattr(self, 'lin'):
            x = (self.lin(x[0]).relu(), x[1])

        # propagate_type: (x: OptPairTensor)
        out = self.propagate(edge_index, x=x, size=size)
        out = self.lin_l(out)

        x_r = x[1]
        if self.root_weight and x_r is not None:
            out += self.lin_r(x_r)
```
Why we don't use `self.lin_r(x_r[col])` to transfome the x_i 's node features just look like the formula above? Some nodes in x may not attend the message to target nodes but we still give it a linear transformation?
And in GATConv, we add a linear transformation to all nodes too:
```python
if isinstance(x, Tensor):
            assert x.dim() == 2, "Static graphs not supported in 'GATConv'"
            x_src = x_dst = self.lin_src(x).view(-1, H, C)
```
The same question confused me for why we transform all nodes other than specific nodes like x[col] or x[row]?

### Environment

* PyG version: 2.0.4
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
The transformation on node-level features is generally more efficient since the number of edges is usually way greater than the number of edges. As such, we usually prefer to do `lin(x)[col]` whenever applicable.

**Comment by downeykking** [comment]
> 

Got it, thanks!

**Comment by downeykking** [comment]
> The transformation on node-level features is generally more efficient since the number of edges is usually way greater than the number of edges. As such, we usually prefer to do `lin(x)[col]` whenever applicable.

Got it, thanks!
