### ISSUE TITLE
RuntimeError when using DataLoader with multiprocessing and CUDA

### ISSUE THREAD

**Issue by hannes-brt** [pyg-team/pytorch_geometric#5139]
### 🐛 Describe the bug

I get the following error when I attempt to use a `DataLoader` with multiprocessing and CUDA simulataneously:

```
E         File "/home/ubuntu/.conda/envs/abab_bind_gvp/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 146, in _collate
E           out = elem.new(storage)
E       RuntimeError: Attempted to set the storage of a tensor on device "cuda:0" to a storage on different device "cpu".  This is no longer allowed; the devices must match.
```

Apparently, the collate function attempts to set the storage of a tensor that is on the GPU to CPU.

I believe this should be reproducible using any `Dataset` that returns tensors on the GPU memory and setting `num_workers > 0` on the `DataLoader`. 

### Environment

* PyG version: 2.04
* PyTorch version: 1.12.0
* OS: Ubuntu 22.04
* Python version: 3.10.5
* CUDA/cuDNN version: 11.6
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Yes, using `num_workers>0` with CUDA tensors is not supported by CUDA - we can probably throw a better error here.

**Comment by yuanqm55** [comment]
I encounter the same problem

**Comment by rusty1s** [comment]
Do you have a reproducible example?
