### ISSUE TITLE
GINEConv assumes nn is subscriptable

### ISSUE THREAD

**Issue by oiao** [pyg-team/pytorch_geometric#5143]
### 🐛 Describe the bug

There is an issue with the GINEConv class when providing the `edge_dim` parameter.
Line https://github.com/pyg-team/pytorch_geometric/blob/e805f0ca606ad67564d1c2de9e4a893243ca5d78/torch_geometric/nn/conv/gin_conv.py#L144
assumes that the passed `nn` is subscriptable, which is not the case when it is directly derived from `nn.Module`:

``` python
from torch import nn
from torch_geometric import nn as gnn

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = nn.Linear(1, 2)
    def forward(self, x):
        return self.lin(x)

gnn.GINEConv(Net(), edge_dim=3)
```
```
File torch_geometric/nn/conv/gin_conv.py:144, in GINEConv.__init__(self, nn, eps, train_eps, edge_dim, **kwargs)
    [142]     self.register_buffer('eps', torch.Tensor([eps]))
    [143] if edge_dim is not None:
--> [144]     if hasattr(self.nn[0], 'in_features'):
    [145]         in_channels = self.nn[0].in_features
    [146]     else:

TypeError: 'Net' object is not subscriptable
```

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.12
* OS: Ubuntu
* Python version: 3.8
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by rusty1s** [comment]
Thanks for reporting. Will look into it.

**Comment by Padarn** [comment]
I had some spare time, so raised a PR to address this.
