### ISSUE TITLE
Help! Cannot install the latest version of Scipy.

### ISSUE THREAD

**Issue by KazY0601** [pyg-team/pytorch_geometric#5157]
### 🐛 Describe the bug

code:
import math
G = create_graph(jaccards, vocab_group, topk=30)
k = 2.0/math.sqrt(len(G.nodes()))
plot_network(group, G, k=k, iterations=65)

bug:
File ~\Anaconda3\lib\site-packages\networkx\convert_matrix.py:921, in to_scipy_sparse_array(G, nodelist, dtype, weight, format)
    919         r += diag_index
    920         c += diag_index
--> 921     A = sp.sparse.coo_array((d, (r, c)), shape=(nlen, nlen), dtype=dtype)
    922 try:
    923     return A.asformat(format)

AttributeError: module 'scipy.sparse' has no attribute 'coo_array'
----------------------------------------
I read this article (https://github.com/pyg-team/pytorch_geometric/issues/4378) and tried everything below to update Scipy to the latest version, but it is not updated from 1.7.3.
conda update scipy
conda update networkx
pip install --upgrade pip
conda update --all

### Environment

* PyG version:
* PyTorch version:1.12.1
* OS: windows10 pro
* Python version:3.9.12
* CUDA/cuDNN version:N/A
* How you installed PyTorch and PyG (`conda`, `pip`, source): maybe conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
What about
```
pip install --upgrade scipy

**Comment by KazY0601** [comment]
It's done! Thank you so much!
