### ISSUE TITLE
If RGATConv uses f-scaled mod, there will be bugs of different tensors on different devices

### ISSUE THREAD

**Issue by goldenNormal** [pyg-team/pytorch_geometric#5163]
### 🐛 Describe the bug

When using RGATConv, set mod = 'f-scaled', tensor in different devices error will appear .

`RGATConv(in_channels, out_channels, 14, num_bases=8,mod='f-scaled',concat =False,heads=8)` 

`RGATConv(in_channels, out_channels, 14, num_bases=8,concat =False,heads=8,)`,

error:

>   File "/home/mist/tianchi/RevRgcn.py", line 365, in forward
    return self.conv(x, edge_index,edge_type)
  File "/mistgpu/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mistgpu/site-packages/torch_geometric/nn/conv/rgat_conv.py", line 341, in forward
    out = self.propagate(edge_index=edge_index, edge_type=edge_type, x=x,
  File "/mistgpu/site-packages/torch_geometric/nn/conv/message_passing.py", line 374, in propagate
    out = self.message(**msg_kwargs)
  File "/mistgpu/site-packages/torch_geometric/nn/conv/rgat_conv.py", line 473, in message
    degree = scatter_add(ones, index,
  File "/mistgpu/site-packages/torch_scatter/scatter.py", line 29, in scatter_add
    return scatter_sum(src, index, dim, out, dim_size)
  File "/mistgpu/site-packages/torch_scatter/scatter.py", line 21, in scatter_sum
    return out.scatter_add_(dim, index, src)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_scatter_add_)

### Environment

* PyG version:`2.0.4`
* PyTorch version:`1.12.1`
* OS:`ubuntu 18.04.6 LTS`
* Python version:`3.9.12`
* CUDA/cuDNN version:`cu116`
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html`
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. Will take a look!

**Comment by rusty1s** [comment]
Thanks for reporting. Fixed in #5187.
