### ISSUE TITLE
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 2

### ISSUE THREAD

**Issue by WindWalker69** [pyg-team/pytorch_geometric#5182]
### 😵 Describe the installation problem

I tried to install PyG in my project venv with the following command:
`pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html`. 
Every time I try I receive this 
`error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 2`.
I already try to update my wheel, setuptools and other packages, even my CUDA version (I actually have 11.7) but nothing goes. Somebody can help me?

This is my whole output (I stoped to torch-scatter because the output is the same even for the other packages):
[log.txt](https://github.com/pyg-team/pytorch_geometric/files/9300556/log.txt)

### Environment

* PyG version: 1.12.0 + cu116
* PyTorch version: Stable (1.12.1)
* OS: Windows 11
* Python version: 3.7
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
What happens if you run
```
pip install --verbose --no-index torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
```

**Comment by WindWalker69** [comment]
@rusty1s 

this is the output i get with the command you suggest:

(venv) C:\Users\mR_95\PycharmProjects\GNN_GraphClassification>pip install --verbose --no-index torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
Using pip 22.2.2 from C:\Users\mR_95\PycharmProjects\GNN_GraphClassification\venv\lib\site-packages\pip (python 3.7)
Looking in links: https://data.pyg.org/whl/torch-1.12.0+cu116.html
ERROR: Could not find a version that satisfies the requirement torch-scatter (from versions: none)
ERROR: No matching distribution found for torch-scatter

**Comment by rusty1s** [comment]
Ah, can you try to upgrade to Python 3.8? We had some trouble building the wheel on Python 3.7 and Windows, so we dropped support for now.

**Comment by WindWalker69** [comment]
@rusty1s
I updated my Python version to 3.8 as you suggested and now, finally, I've succefully installed the packages. Thank you very much!
