### ISSUE TITLE
pip install  pytorch_geometric a bug

### ISSUE THREAD

**Issue by shubihu** [pyg-team/pytorch_geometric#5195]
### 🐛 Describe the bug

use pip install pytorch_geometric or pip install pytorch_geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
there is a bug in line 227 and line 228 in pytorch_geometric.nn.conv.message_passing (torch_geometric/nn/conv/message_passing.py). 

source code in line 285 and line 286 in torch_geometric/nn/conv/message_passing.py ( function def __collect__(self, args, edge_index, size, kwargs)) in github as flow:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/36021958/184575670-6c188f92-ebfc-46a5-8b42-6ac87b0ec5be.png">

but with pip install the package , line 227 and line 228 in torch_geometric/nn/conv/message_passing.py ( function def __collect__(self, args, edge_index, size, kwargs)) as flow:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/36021958/184575380-fc9ee05d-0f82-4492-927b-260b666eac3a.png">

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.12.0
* OS: linux
* Python version: 3.10, 3.9
* CUDA/cuDNN version: 11.6, 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Can you clarify what you mean? There were some recent changes in master that fixed this already - it got fixed here: https://github.com/pyg-team/pytorch_geometric/pull/4418

**Comment by shubihu** [comment]
I mean the script I downloaded from the internet with pip install pytorch_geometric or pip install pytorch_geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html  is wrong and I checked the source code in the pypi, it's also wrong.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/36021958/184601555-80fa9f8b-f162-4bdb-a75e-207707b303e0.png">
Whether the latest is not updated to pypi ?

**Comment by rusty1s** [comment]
Yes, this will be fixed in the upcoming release - we will release it on Wednesday.

**Comment by shubihu** [comment]
Thanks! Great!
