### ISSUE TITLE
No longer able to install pytorch geometric on Colab

### ISSUE THREAD

**Issue by JosephGatto** [pyg-team/pytorch_geometric#5197]
### 😵 Describe the installation problem

I have for quite some time been using the following to run PyG on Colab 

```
import torch

def format_pytorch_version(version):
  return version.split('+')[0]

TORCH_version = torch.__version__
TORCH = format_pytorch_version(TORCH_version)

def format_cuda_version(version):
  return 'cu' + version.replace('.', '')

CUDA_version = torch.version.cuda
CUDA = format_cuda_version(CUDA_version)

!pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-geometric 
```

However just today, I have found this now infinitely hangs. Has something changed regarding Colab install instructions recently? 

Thanks! 

### Environment

Env: Google Colab w/ Cuda

**Comment by rusty1s** [comment]
I assume Colab has upgraded to PyTorch 1.12.1. Can you manually reset `TORCH` to 1.12.0? In the meantime, I will also publish wheels for PyTorch 1.12.1.

**Comment by rusty1s** [comment]
I think I just fixed that on our end. Let me know if it is not working for you!
