### ISSUE TITLE
very slow PyG Installation issue in googlecolab pro+

### ISSUE THREAD

**Issue by Amadeus-System** [pyg-team/pytorch_geometric#5203]
### 😵 Describe the installation problem

Hi. I was using PyTorch Geometric very well til now.
Recently I found very weird issue. When I have tried to install PyG, installation speed is so slow, I need to wait at least 30 minutes.
I found that the installation speed is about "190 kb/s" in googlecolab.

``` python
%%time 
# Install required packages.
import os
import torch
os.environ['TORCH'] = torch.__version__  # 1.12.0+cu113
print(torch.__version__)
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-geometric==2.0.4
# !pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
!pip install -q pymatgen==2020.11.11
!pip install -U kaleido
```

![image](https://user-images.githubusercontent.com/76824867/184806484-b7f38b7a-c835-4e99-99d7-ebab26de4151.PNG)

And I tried installation with PyG example jupyter notebook (https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html). and this file also have a very slow installation problem.

![image2](https://user-images.githubusercontent.com/76824867/184806788-08572426-bd56-47c0-b47a-020fb1e82781.PNG)

I think there's something wrong in the PyG distribution process or googlecolab server.
Can you check about this?
Thank you for your useful library.

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.12.1+cu113
* OS: linux
* Python version: 3.9
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
I think I just fixed that. Let me know if it is not working for you!

**Comment by Amadeus-System** [comment]
> I think I just fixed that. Let me know if it is not working for you!

Now It's working very well. Thank you for your fast response!!
