### ISSUE TITLE
`RandomLinkSplit` in HeteroData

### ISSUE THREAD

**Issue by Tigerrr07** [pyg-team/pytorch_geometric#5206]
# Problem background
When applying `RandomLinkSplit` in an undirected HeteroData `data`, in figure1 (I already store reverse edges in original `edge_index`, see figure 2 as an example), I find  in splitted data, such as `train_data`, `val_data` or `test_data`, the `edge_index` of one `edge_type` is not undirected , I test it using `is_undirected()` method.
![image](https://user-images.githubusercontent.com/86994637/184830074-edfb2210-7e02-4d1d-9ae7-6ec860bfe47e.png)
![image](https://user-images.githubusercontent.com/86994637/184831326-939fcf8b-c4dd-45b9-8cb5-9ac4b6dc379d.png)

# Code
``` python
node_types, edge_types = data.node_types, data.edge_types
# split data
train_data, val_data, test_data = T.RandomLinkSplit(
        num_val=0.1,
        num_test=0.1,
        is_undirected=True,
        add_negative_train_samples=False,
        disjoint_train_ratio=0,
        edge_types=edge_types,
        rev_edge_types=edge_types
    )(data)

# test if undirected
from torch_geometric.utils import is_undirected

edge_type = ('drug', 'anaemia','drug')
print(len(data[edge_type].edge_index[0]), is_undirected(data[edge_type].edge_index)) # 54012, True
print(len(train_data[edge_type].edge_index[0]), is_undirected(train_data[edge_type].edge_index)) # 43210, False
print(len(val_data[edge_type].edge_index[0]), is_undirected(val_data[edge_type].edge_index))   # 43210, False
print(len(test_data[edge_type].edge_index[0]), is_undirected(test_data[edge_type].edge_index))  # 48611, False
```
# Problem
* The number of edges in `test_data` is odd, but this should be an **even** number related to bidirectional edges in undirected graphs.
* `edge_index` in `train_data, val_data, test_data` should be undirected.

In homogeneous graphs, there are no such problems. But I don't know why this happen in my constructed heterogeneous graph.

_Originally posted by @Tigerrr07 in https://github.com/pyg-team/pytorch_geometric/issues/5190#issuecomment-1216310281_

**Comment by rusty1s** [comment]
Do you have a small example to reproduce? I cannot reproduce it on my end yet with some synthetic data.

Note that `edge_types` and `rev_edge_types` should only be identical in case `HeteroData` has a single node type.

**Comment by Tigerrr07** [comment]
> Do you have a small example to reproduce? I cannot reproduce it on my end yet with some synthetic data.
> 
> Note that `edge_types` and `rev_edge_types` should only be identical in case `HeteroData` has a single node type.

I downloaded the source code, here's an example followed from the last function in `/test/transforms/test_random_link_split.py`.
``` python
import torch
from torch_geometric.transforms import RandomLinkSplit
from torch_geometric.data import HeteroData
from torch_geometric.utils import is_undirected, to_undirected

def get_edge_index(num_src_nodes, num_dst_nodes, num_edges):
    row = torch.randint(num_src_nodes, (num_edges, ), dtype=torch.long)
    col = torch.randint(num_dst_nodes, (num_edges, ), dtype=torch.long)
    return torch.stack([row, col], dim=0)

data = HeteroData()
data['p'].x = torch.arange(100)
data['p', 'p'].edge_index = get_edge_index(100, 100, 500)
data['p', 'p'].edge_index = to_undirected(data['p', 'p'].edge_index)


transform = RandomLinkSplit(is_undirected=True, edge_types=('p', 'p'),
                            rev_edge_types=('p', 'p'))
train_data, val_data, test_data = transform(data)
assert train_data['p', 'p'].is_undirected()  # AssertionError
```
The edge is assumed undirected, and `rev_edge_types` is specified. But I got an `AssertionError` in the last line.

**Comment by rusty1s** [comment]
I added the test to our test suite, see https://github.com/pyg-team/pytorch_geometric/pull/5221. Note that there were both changes to `RandomLinkSplit` and `HeteroData.is_undirected` in current master, which likely resolved this already. I will be releasing PyG 2.1 today, so hopefully this fixes the error on your end already.
