### ISSUE TITLE
Typo in VarAggregation

### ISSUE THREAD

**Issue by Nokimann** [pyg-team/pytorch_geometric#5226]
### 📚 Describe the documentation issue

[VarAggregation](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.aggr.VarAggregation) seems to have typo in the quation.

    r"""An aggregation operator that takes the feature-wise variance across a
    set of elements

    .. math::
        \mathrm{var}(\mathcal{X}) = \mathrm{mean}(\{ \mathbf{x}_i^2 : x \in
        \mathcal{X} \}) - \mathrm{mean}(\mathcal{X}). ##################### <-- this line
    """

### Suggest a potential alternative/fix

    r"""An aggregation operator that takes the feature-wise variance across a
    set of elements

    .. math::
        \mathrm{var}(\mathcal{X}) = \mathrm{mean}(\{ \mathbf{x}_i^2 : x \in
        \mathcal{X} \}) - \mathrm{mean}(\mathcal{X})^2.
    """

**Comment by Padarn** [comment]
Good catch. Do you want to raise a PR?

**Comment by Padarn** [comment]
Had a spare minute so fixed it up https://github.com/pyg-team/pytorch_geometric/issues/5226

Thanks @Nokimann.
