### ISSUE TITLE
Activation function as a parameter in PNAConv

### ISSUE THREAD

**Issue by pgniewko** [pyg-team/pytorch_geometric#5234]
### 🚀 The feature, motivation and pitch

Allow custom activation functions in `pre_layers` and `post_layers` of the PNAConv class. At the moment, I have my own custom implementation of this class, and I found that other activations work better for my problem. 

### Alternatives

My local implementation takes an extra argument and leverages getattr.

### Additional context

![Screen Shot 2022-08-18 at 9 59 13 AM](https://user-images.githubusercontent.com/31355874/185452812-04104e5a-a358-4111-b519-a9849a366f51.png)

**Comment by rusty1s** [comment]
I am happy to accept a PR on this one if you want to contribute. Let me know :)

**Comment by pgniewko** [comment]
I have the code ready. How do I send a PR?

**Comment by pgniewko** [comment]
PR has been submitted
