### ISSUE TITLE
Installation of new version 2.1.0 via Anaconda

### ISSUE THREAD

**Issue by anjaseidel** [pyg-team/pytorch_geometric#5238]
### 🚀 The feature, motivation and pitch

Hi, could you please provide the newest version 2.1.0 as an Anaconda package? Many thanks!

**Comment by rusty1s** [comment]
Yes, this will follow in the next week. Sorry for the delay!

**Comment by anjaseidel** [comment]
Thanks a lot!

**Comment by abhshkdz** [comment]
Hey @rusty1s, any updates on this?

**Comment by rusty1s** [comment]
Sadly no, I have some trouble to update `torch-sparse` packages on conda which is the cause of this delay. Sorry for any inconveniences!

**Comment by giacomoorsi** [comment]
Any update?

**Comment by anjaseidel** [comment]
@rusty1s Thank you for the implementation! Duplicate of #5679
