### ISSUE TITLE
Jinja templates are missing from install

### ISSUE THREAD

**Issue by jdchn** [pyg-team/pytorch_geometric#5249]
### 😵 Describe the installation problem

The Jinja templates appear to be missing:

```
File "/opt/conda/lib/python3.8/site-packages/torch_geometric/nn/sequential.py", line 101, in Sequential
     with open(osp.join(root, 'sequential.jinja'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.8/site-packages/torch_geometric/nn/sequential.jinja'
```

```
$ ls /opt/conda/lib/python3.8/site-packages/torch_geometric/nn
__init__.py   data_parallel.py  glob.py   norm/        sequential.py
__pycache__/  dense/            inits.py  pool/        to_hetero_transformer.py
aggr/         functional/       meta.py   reshape.py   to_hetero_with_bases_transformer.py
conv/         fx.py             models/   resolver.py  unpool/

```

See also #1459.

Note that `include_package_data=True` was removed from `setup.py` by 834be97d27acc1011698dc1419ab551869e22e50.

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.10 and 1.12
* OS: Ubuntu 20.04
* Python version: 3.8.12
* CUDA/cuDNN version: 11.4.2
* How you installed PyTorch and PyG (`conda`, `pip`, source):  `source` and `pip`
* Any other relevant information (*e.g.*, version of `torch-scatter`): [NGC PyTorch 21.10](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-10.html#rel_21-10)

**Comment by rusty1s** [comment]
My bad, really sorry :( This is now fixed as I released `torch-geometric==2.1.0.post1`.
