### ISSUE TITLE
`dblp` dataset download link is broken

### ISSUE THREAD

**Issue by Padarn** [pyg-team/pytorch_geometric#5251]
### 🐛 Describe the bug

The `dblp` dataset is currently broken as the dropbox [link](https://www.dropbox.com/s/yh4grpeks87ugr2/DBLP_processed.zip?dl=1) is no longer live. This was showing up in failing CI tests for all PRs.

Possible fixes:
- Find another source of the same data (or upload the same if we have it anywhere).
- Recreate the data from the dataset which is available [here](https://dblp.org/faq/How+can+I+download+the+whole+dblp+dataset.html).

Note that we have added a skipped test [here](https://github.com/pyg-team/pytorch_geometric/pull/5250/files#r950671979) which should be re-enabled once this dataset is fixed.

Note there is a temporary fix: https://github.com/pyg-team/pytorch_geometric/pull/5250

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12
* OS: CI

**Comment by rusty1s** [comment]
It is back online :)
