### ISSUE TITLE
A way to override processed_dir when creasting InMemoryDataset or Datasets

### ISSUE THREAD

**Issue by snknitin** [pyg-team/pytorch_geometric#5266]
### 🚀 The feature, motivation and pitch

The raw files for a particular dataset might be common for multiple graph data and different classes can be called on the same root location, to have a single store of data files without needing constant downloads or risk overwriting or reloading the old processed directory.

If we can pass an additional name tag for the processed_dir like `processed_{dataset_0}` that can store the data.pt files then , we can use configs to run the same code in parallel and generate different graph data objects as per need.  

This will avoid manual runs, code changes, renaming folders and ensure we load the right dataset for the models through configs or args

### Alternatives

If there is a hack to rename it as an override, that could work. Like modifying the `self.processed_dir` since we know the root anyway.  That way multiple subset graphs or dataset runs of the same code will look for the correct path and not reload the old data by mistake

**Comment by rusty1s** [comment]
You can override `processed_dir` in your own dataset as follows:
```python
@property
def processed_dir(self) -> str:
    if foo:
        return osp.join(self.root, 'processed_foo')
    return osp.join(self.root)
```
Alternatively, you can specify different `processed_file_names` depending on the config you are using. This will share the `processed_dir`, but will generate multiple processed files. Let me know if this helps you!

**Comment by snknitin** [comment]
I see. Thanks for your response ! I was working with a similar hack, but post folder creation and during re-run access,outside teh class. 

So `return osp.join(self.root)` automatically makes it `....\root\processed\` or should we return `return osp.join(self.root,'processed')` instead in the property method?
