### ISSUE TITLE
dgcnn_segmentation:AttributeError: 'Batch' object has no attribute 'category'

### ISSUE THREAD

**Issue by liangzhenm** [pyg-team/pytorch_geometric#528]
## ❓ Questions & Help

when i run dgcnn_segmentation with batch=4 (my GPU memory only 3G), it raise:
"     categories.append(data.category.to(torch.device('cpu')))
AttributeError: 'Batch' object has no attribute 'category"
why??

**Comment by rusty1s** [comment]
Yes, the `ShapeNet` dataset changed in master. You need to install PyG from source, and everything should work as expected. I will craft a new minor release soon.
