### ISSUE TITLE
Links to incorrect wheels on torch-1.12.1+cpu page.

### ISSUE THREAD

**Issue by oheikk** [pyg-team/pytorch_geometric#5282]
### 😵 Describe the installation problem

I'm having trouble installing torch-sparse for CPU, and I believe it has to do with the links in https://pytorch-geometric.com/whl/torch-1.12.1%2Bcpu.html

All the links to wheels on that particular page point to the previous version /whl/torch-**1.12.0**%2Bcpu.html/wheel.whl. Perhaps this is intentional though and I have a problem elsewhere?

Please correct me if I'm wrong, and I'll post an issue with the steps I took to install and my environment info instead. :)

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This is intentional. The wheels should work both for PyTorch 1.12.0 and 1.12.1. What's the error you are seeing?

**Comment by oheikk** [comment]
Sorry for the misunderstanding. I'm getting `OSError: /home/oskari/.local/lib/python3.10/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs` when trying `from torch_sparse import SparseTensor`.

**Comment by oheikk** [comment]
I just realised I've made a mistake setting up my environment. I corrected it and PyG works fine.
