### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by good-demo** [pyg-team/pytorch_geometric#5285]
### 🐛 Describe the bug

File "/home/data1/yxd/envs/gns/lib/python3.7/site-packages/torch_geometric/loader/dynamic_batch_sampler.py", line 9, in <module>
    class DynamicBatchSampler(torch.utils.data.sampler.Sampler[List[int]]):
TypeError: 'type' object is not subscriptable

### Environment

torch                 1.4.0+cu100
torch-cluster         1.5.2
torch-geometric       2.1.0
torch-scatter         2.0.4
torch-sparse          0.5.1
torch-spline-conv     1.2.0

**Comment by rusty1s** [comment]
Mh, weird. It works for me. Anyway, I removed it in master, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/loader/dynamic_batch_sampler.py#L9). Thanks for reporting!

**Comment by HuichuanLiu** [comment]
Also met it in pip versions2.1.0.post1 (default) and 2.1.0 with python  3.7.7.
I worked around by downgrading to 2.0.4.
Would be nice if pip default package could be switched, as it is triggered even with the simplest 'import torch_geometric' cmd.

**Comment by rusty1s** [comment]
You can still use 2.1.0 and manually adjust the line of code to fix this. This will be fixed in the next release. Sorry for any inconveniences!
