### ISSUE TITLE
 module 'torch_geometric' has no attribute 'experimental_mode'

### ISSUE THREAD

**Issue by vanly89** [pyg-team/pytorch_geometric#5300]
### 🐛 Describe the bug

Hi, experts, 
Thanks for your dedication to the great project torch_geometric. When I tried to  using the experimental function of torch_geometric, I got the an error : " AttributeError: module 'torch_geometric' has no attribute 'experimental_mode' ".
The relevant codes as follows:
import torch_geometric
with torch_geometric.experimental_mode():

I'm not sure if it's a problem with the way I use it, or with the software。Could you so nice to give some guidiance？

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12.1
* OS: ubuntu 18.04
* Python version: 3.8
* CUDA/cuDNN version:  11.3 / 8.2.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
pip install command ： pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu113.html

**Comment by rusty1s** [comment]
We just added this to master. You need to install PyG as described [here](https://github.com/pyg-team/pytorch_geometric#nightly-and-master).
