### ISSUE TITLE
AttributeError when getting a variable from `Data` with the value of `None`

### ISSUE THREAD

**Issue by EdisonLeeeee** [pyg-team/pytorch_geometric#5310]
### 🐛 Describe the bug

For some reason, I need to specify a variable in `Data` and I initialized it with `None`. But I got an `AttributeError` when trying to get the value of this variable:
```python
from torch_geometric.data import Data
data = Data()
data.a_variable = None
data.a_variable
# AttributeError: 'GlobalStorage' object has no attribute 'a_variable'
```

### Environment

* PyG version: master
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
We currently treat objects set to `None` as "deleted" from the store. While I agree that this does not align with how Python handles dictionaries, it might be hard to change at this point. If you are unsure whether an attribute exist, I suggest to simply access it via `data.get('a_variable')`. Does that work for you?

**Comment by EdisonLeeeee** [comment]
Thanks for your response. It works for me. Will close this issue :)
