### ISSUE TITLE
edgeconv edge features 

### ISSUE THREAD

**Issue by germayneng** [pyg-team/pytorch_geometric#5313]
### 🚀 The feature, motivation and pitch

Based on the original paper https://arxiv.org/pdf/1801.07829.pdf, x_i and x_j are defined by edge features. However, based on the documentation of torch geometric: https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.EdgeConv, the input features are the node features. Is there something i missed or does it takes in edge features as well if included? Or do i simply include the edge weights in the adjacency matrix? https://github.com/pyg-team/pytorch_geometric/blob/master/examples/egc.py#L65

**Comment by rusty1s** [comment]
Can you clarify? Equation (7) only takes the source and destination node features into account. If you want to integrate edge features, you can easily do this as follows:
```python
import torch
from torch import Tensor
from torch.nn import Sequential, Linear, ReLU
from torch_geometric.nn import MessagePassing

class EdgeConv(MessagePassing):
    def __init__(self, in_channels, edge_dim, out_channels):
        super().__init__(aggr="max")  # "Max" aggregation.
        self.mlp = Sequential(
            Linear(2 * in_channels + edge_dim, out_channels),
            ReLU(),
            Linear(out_channels, out_channels),
        )

    def forward(self, x: Tensor, edge_index: Tensor, edge_attr: Tensor) -> Tensor:
        return self.propagate(edge_index, x=x, edge_attr=edge_attr)

    def message(self, x_j: Tensor, x_i: Tensor, edge_attr: Tensor) -> Tensor:
        edge_features = torch.cat([x_i, x_j - x_i, edge_attr], dim=-1)
        return self.mlp(edge_features)
```

**Comment by germayneng** [comment]
Thanks for the fast reply. Yes you are right as the edge_features are defined as non-linear learnable parameters. 
The snippet provided is very helpful as i did intend to concat additional edge attr / edge weights.
