### ISSUE TITLE
Installation from source: csrc/cpu/utils.h:40:3: error

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [pyg-team/pytorch_geometric#5322]
### 😵 Describe the installation problem

**cmd : **pip install torch-sparse**
error info:**
Collecting torch-sparse
  Using cached torch_sparse-0.6.15.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in ./miniconda3/envs/pytorch/lib/python3.8/site-packages (from torch-sparse) (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in ./miniconda3/envs/pytorch/lib/python3.8/site-packages (from scipy->torch-sparse) (1.21.5)
Building wheels for collected packages: torch-sparse
  Building wheel for torch-sparse (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/reduce.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/eye.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/metis.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/utils.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/sample.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/__init__.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/padding.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/cat.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/permute.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/spadd.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/transpose.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/narrow.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/saint.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/index_select.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/add.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/matmul.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/select.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/mul.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/bandwidth.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/convert.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/rw.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/spmm.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/diag.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/storage.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/tensor.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/masked_select.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      running egg_info
      writing torch_sparse.egg-info/PKG-INFO
      writing dependency_links to torch_sparse.egg-info/dependency_links.txt
      writing requirements to torch_sparse.egg-info/requires.txt
      writing top-level names to torch_sparse.egg-info/top_level.txt
      reading manifest file 'torch_sparse.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*' found under directory 'test'
      adding license file 'LICENSE'
      writing manifest file 'torch_sparse.egg-info/SOURCES.txt'
      running build_ext
      building 'torch_sparse._sample_cpu' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/csrc
      creating build/temp.linux-x86_64-cpython-38/csrc/cpu
      gcc -pthread -B /Storage/wwd/miniconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_PYTHON -Icsrc -Ithird_party/parallel-hashmap -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/Storage/wwd/miniconda3/envs/pytorch/include/python3.8 -c csrc/cpu/sample_cpu.cpp -o build/temp.linux-x86_64-cpython-38/csrc/cpu/sample_cpu.o -O2 -Wno-sign-compare -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=_sample_cpu -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from csrc/cpu/sample_cpu.cpp:3:
      csrc/cpu/utils.h: In function ‘int64_t uniform_randint(int64_t, int64_t)’:
      `csrc/cpu/utils.h:40:3: error: ‘CHECK_LT’ was not declared in this scope; did you mean ‘CHECK’?`
         40 |   CHECK_LT(low, high);
            |   ^~~~~~~~
            |   CHECK
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-sparse
  Running setup.py clean for torch-sparse
Failed to build torch-sparse
Installing collected packages: torch-sparse
  Running setup.py install for torch-sparse ... error
  error: subprocess-exited-with-error

  × Running setup.py install for torch-sparse did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      running install
      /Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/reduce.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/eye.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/metis.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/utils.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/sample.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/__init__.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/padding.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/cat.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/permute.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/spadd.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/transpose.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/narrow.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/saint.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/index_select.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/add.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/matmul.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/select.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/mul.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/bandwidth.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/convert.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/rw.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/spmm.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/diag.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/storage.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/tensor.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      copying torch_sparse/masked_select.py -> build/lib.linux-x86_64-cpython-38/torch_sparse
      running egg_info
      writing torch_sparse.egg-info/PKG-INFO
      writing dependency_links to torch_sparse.egg-info/dependency_links.txt
      writing requirements to torch_sparse.egg-info/requires.txt
      writing top-level names to torch_sparse.egg-info/top_level.txt
      reading manifest file 'torch_sparse.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*' found under directory 'test'
      adding license file 'LICENSE'
      writing manifest file 'torch_sparse.egg-info/SOURCES.txt'
      running build_ext
      building 'torch_sparse._sample_cpu' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/csrc
      creating build/temp.linux-x86_64-cpython-38/csrc/cpu
      gcc -pthread -B /Storage/wwd/miniconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_PYTHON -Icsrc -Ithird_party/parallel-hashmap -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/Storage/wwd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/Storage/wwd/miniconda3/envs/pytorch/include/python3.8 -c csrc/cpu/sample_cpu.cpp -o build/temp.linux-x86_64-cpython-38/csrc/cpu/sample_cpu.o -O2 -Wno-sign-compare -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=_sample_cpu -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from csrc/cpu/sample_cpu.cpp:3:
      csrc/cpu/utils.h: In function ‘int64_t uniform_randint(int64_t, int64_t)’:
      `csrc/cpu/utils.h:40:3: error: ‘CHECK_LT’ was not declared in this scope; did you mean ‘CHECK’?`
         40 |   CHECK_LT(low, high);
            |   ^~~~~~~~
            |   CHECK
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> torch-sparse

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

### Environment

* PyG version: none
* PyTorch version: 1.13
* OS: ubuntu 20.04
* Python version: 3.8
* CUDA/cuDNN version: 11.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): source
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by seanliu96** [comment]
I faced the same problem in M1 Mac.

**Comment by seanliu96** [comment]
Resolved by [Pull #272](https://github.com/rusty1s/pytorch_sparse/pull/272)

**Comment by rusty1s** [comment]
Thank you!

**Comment by 0106WeiWeiDeng** [comment]
Thank you for such quick reply, "many thanks"!
