### ISSUE TITLE
How to reformulate link classification as node classification problem

### ISSUE THREAD

**Issue by PPGGG** [pyg-team/pytorch_geometric#5326]
How to reformulate link classification as node classification problem ?

**Comment by rusty1s** [comment]
You can treat link classification as node classification by converting your graph to a line graph, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.LineGraph).

**Comment by PPGGG** [comment]
@rusty1s Love you Fey !
