### ISSUE TITLE
Bug - HeteroData Model building issue in message_passing.py "IndexError: index out of range in self"

### ISSUE THREAD

**Issue by sriakhil25** [pyg-team/pytorch_geometric#5327]
### 🐛 Describe the bug

Hi Pyg Team,

My HeteroData Object appears as below:
HeteroData(
  patient={ x=[480, 3] },
  condition={
    x=[10128, 1],
    y=[10128],
    train_mask=[10128],
    test_mask=[10128],
    val_mask=[10128]
  },
  (patient, has, condition)={ edge_index=[2, 10128] }
)

`torch.save(data, 'HetroData.pt')`
pt file of this HeteroData can be downloaded from below URL:
https://github.com/sriakhil25/GraphNN_Research/blob/main/HetroData.pt

Model looks like below
HGT(
  (lin_dict): ModuleDict(
    (patient): Linear(-1, 64, bias=True)
    (condition): Linear(-1, 64, bias=True)
  )
  (convs): ModuleList(
    (0): HGTConv(-1, 64, heads=2)
  )
  (lin): Linear(64, 4, bias=True)
)

I am building a simple node classification task on 'condition' using HGT or HeteroGNN by referring the example code DBLP dataset.

while running the following code :
with torch.no_grad():  # Initialize lazy modules.
    out = model(data.x_dict, data.edge_index_dict)

I am getting index error in  message_passing.py "IndexError: index out of range in self". Complete error is as follows:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7996\418962991.py in <module>
      1 with torch.no_grad():  # Initialize lazy modules.
----> 2     out = model(data.x_dict, data.edge_index_dict)

~\.conda\envs\gnn\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

~\AppData\Local\Temp\ipykernel_7996\1550241237.py in forward(self, x_dict, edge_index_dict)
     22 
     23         for conv in self.convs:
---> 24             x_dict = conv(x_dict, edge_index_dict)
     25 
     26         return self.lin(x_dict['condition'])

~\.conda\envs\gnn\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

~\.conda\envs\gnn\lib\site-packages\torch_geometric\nn\conv\hgt_conv.py in forward(self, x_dict, edge_index_dict)
    158             # propagate_type: (k: Tensor, q: Tensor, v: Tensor, rel: Tensor)
    159             out = self.propagate(edge_index, k=k, q=q_dict[dst_type], v=v,
--> 160                                  rel=self.p_rel[edge_type], size=None)
    161             out_dict[dst_type].append(out)
    162 

~\.conda\envs\gnn\lib\site-packages\torch_geometric\nn\conv\message_passing.py in propagate(self, edge_index, size, **kwargs)
    308 
    309                 coll_dict = self.__collect__(self.__user_args__, edge_index,
--> 310                                              size, kwargs)
    311 
    312                 msg_kwargs = self.inspector.distribute('message', coll_dict)

~\.conda\envs\gnn\lib\site-packages\torch_geometric\nn\conv\message_passing.py in __collect__(self, args, edge_index, size, kwargs)
    200                 if isinstance(data, Tensor):
    201                     self.__set_size__(size, dim, data)
--> 202                     data = self.__lift__(data, edge_index, dim)
    203 
    204                 out[arg] = data

~\.conda\envs\gnn\lib\site-packages\torch_geometric\nn\conv\message_passing.py in __lift__(self, src, edge_index, dim)
    170         if isinstance(edge_index, Tensor):
    171             index = edge_index[dim]
--> 172             return src.index_select(self.node_dim, index)
    173         elif isinstance(edge_index, SparseTensor):
    174             if dim == 1:

IndexError: index out of range in self

### Environment

* PyG version:  2.0.4
* PyTorch version: 1.11.0
* OS: Windows10 
* Python version: 3.7.9
* CUDA/cuDNN version: CPU
* How you installed PyTorch and PyG (`conda`, `pip`, source): Conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch_scatter 2.0.9

**Comment by EdisonLeeeee** [comment]
I've downloaded your `HetroData.pt` and I found there must have some errors when building your heterogeneous graph. The `edge_index` between `patient` and `condition` is out of range:
```python
>>> data['patient', 'condition'].edge_index.max(1).values
tensor([10128,   495])
```
but `patient` and `condition` only have 480 and 10128 nodes, respectively.

**Comment by sriakhil25** [comment]
> I've downloaded your `HetroData.pt` and I found there must be some errors when building your heterogeneous graph. The maximum values in `edge_index` between `patient` and `condition` are:
> 
> ```python
> >>> data['patient', 'condition'].edge_index.max(1).values
> tensor([10128,   495])
> ```
> 
> However, `patient` and `condition` only have 480 and 10128 nodes, respectively. So it would lead to an out-of-range error.

Thanks for quick reply - due to nature of data, I removed patient values at index "76, 103, 119, 185, 192, 203, 274, 278, 286, 297, 314, 323, 363, 386,425,460"

so we are left with only 480 nodes but node values are same so max node value can be 495

`len(set(data[('patient', 'has', 'condition')].edge_index[1].numpy()))
`
Output - 480

`max(set(data[('patient', 'has', 'condition')].edge_index[1].numpy()))`
Output - 495 

Hope it clarifies.

**Comment by EdisonLeeeee** [comment]
I would suggest you rearrange your node ids and make sure `edge_index` lies in the proper range. BTW, the order of your `edge_index` might be reversed since `edge_index[0]` should be `patient` but it seems to be `condition`.

**Comment by EdisonLeeeee** [comment]
I think you have you've got something wrong in building your graph, particularly the direction of `edge_index`. In your HeteroData, the direction of `[('patient', 'has', 'medication'), ('patient', 'has', 'careplan'), ('patient', 'has', 'condition')]` are opposite, you'd better flip them before forward:
```python
edge_types = [('patient', 'has', 'medication'), 
              ('patient', 'has', 'careplan'), 
              ('patient', 'has', 'condition')]   
for edge_type in edge_types:
    data[edge_type].edge_index = data[edge_type].edge_index.flip(0)
```
That's the main reason for the IndexError.

In addition, you need to convert your HeteroData to an undirected one, so as to make sure all types of nodes have occurred during propagation.

**Comment by EdisonLeeeee** [comment]
Please note that the name `careplan` you defined in node types and edge types is inconsistent: `careplan` and `careplans`

**Comment by sriakhil25** [comment]
> so we are left with only 480 nodes but node values are same so max node value can be 495
> 
> `len(set(data[('patient', 'has', 'condition')].edge_index[1].numpy())) ` Output - 480
> 
> `max(set(data[('patient', 'has', 'condition')].edge_index[1].numpy()))` Output - 495
> 
> Hope it clarifies.

Thanks for your review and help. Flipping of the edges worked and issue resolved. However I used different approach. I changed source and destination tensors in beginning itself while tensorizing the edges.
Also note that the point that edge 'patient_has_condition' has only 480 nodes while total patient nodes are 495 didn't required any fix. which makes sense also as there may be patient nodes which have no association with any of the conditions nodes.


My HeteroData appears as below:

HeteroData(
  patient={ x=[496, 3] },
  medication={ x=[20069, 5] },
  symptom={ x=[63462, 3] },
  ethnicity={ x=[2, 1] },
  careplans={ x=[3949, 1] },
  condition={
    x=[10128, 1],
    y=[10128],
    train_mask=[10128],
    test_mask=[10128],
    val_mask=[10128]
  },
  gender={ x=[2, 1] },
  race={ x=[5, 1] },
  attribute={ x=[20, 1] },
  observation={ x=[406834, 4] },
  (patient, has, medication)={ edge_index=[2, 20069] },
  (patient, has, symptom)={ edge_index=[2, 12613] },
  (patient, has, careplans)={ edge_index=[2, 3949] },
  (patient, has, condition)={ edge_index=[2, 10127] },
  (observation, for, patient)={ edge_index=[2, 406833] },
  (patient, has, attribute)={ edge_index=[2, 9920] },
  (patient, has, race)={ edge_index=[2, 496] }
)

**Comment by sriakhil25** [comment]
closed as comment added above
