### ISSUE TITLE
sample_points bug

### ISSUE THREAD

**Issue by voidmomo** [pyg-team/pytorch_geometric#534]
## 🐛 Bug

Line 33 on pytorch_geometric/torch_geometric/transforms/sample_points.py :
after sampling should be 
`data.face = face `

**Comment by rusty1s** [comment]
Why? We do not want to modify the initial mesh, just sample points from it.

**Comment by voidspiral** [comment]
I think it can be made an optional
In some case， sample points from mesh if we want to build a local graph on mesh.But actually it has much edges   too difficult to compute it

**Comment by rusty1s** [comment]
Can you elaborate? I do not understand the use-cases.
