### ISSUE TITLE
Weighted Neighbor Sampling

### ISSUE THREAD

**Issue by rafaelvanbelle** [pyg-team/pytorch_geometric#5345]
### 🚀 The feature, motivation and pitch

I recently used SAGEConv combined with the Neighborloader on a large graph. The graph contained many nodes with a high degree (degree >> number of neighbors to sample). Instead of randomly sampling neighbors, I tried to implement a variant of the random sampler to take into account edge weights. Taking into consideration the edge weights while sampling allows me to select 'relevant' neighbors before passing them to SAGEConv. 
In my case it led to improvements to the node classification performance.

I wonder if it would make sense to add weighted neighbor sampling as a new feature for the NeighborLoader/NeighborSampler in Pytorch Geometric?
Maybe this is already implemented or it might not make sense from a theoretical perspective.

**Comment by rusty1s** [comment]
Yes, we have plans to integrate this as part of PyG 2.2. Please stay tuned :)

**Comment by siddhartha047** [comment]
Can you point me to the function?

**Comment by rusty1s** [comment]
False promise, sadly :( Still WIP.

**Comment by lynn-1998** [comment]
> False promise, sadly :( Still WIP.

Hi, is this function now implemented？

**Comment by siddhartha047** [comment]
@rusty1s I have implemented several weighted neighbor sampling codes modifying the existing torch-sparse library functions and then creating a shared library. I implemented both neighborhood sampling and weighted random walk. I can share the codes if you want.

**Comment by lynn-1998** [comment]
> @rusty1s I have implemented several weighted neighbor sampling codes modifying the existing torch-sparse library functions and then creating a shared library. I implemented both neighborhood sampling and weighted random walk. I can share the codes if you want.


Hello, @siddhartha047. Your contributions could be of great value to me. Would it be possible for you to share the codes?

**Comment by rusty1s** [comment]
Yes, weighted sampling was added in `torch-geometric==2.4.0`.
