### ISSUE TITLE
How can I install for pytorch 1.8.2 ?

### ISSUE THREAD

**Issue by wickcode** [pyg-team/pytorch_geometric#5346]
### 😵 Describe the installation problem

Hi,

I would like to use the package for pytorch 1.8.2 as that is LTS version, 1.12.1 seems to be unstable.
I could not find a binary for  1.8.2  and 11.1 cuda.

I can build from source but having many systems starts breaking things. Is there a binary for this which can be used?

Thank you 

### Environment

* PyG version: Latest 
* PyTorch version: 1.8.2
* OS: Linux
* Python version: 3.7
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
You can use the binaries for 1.8.0+cu111, see https://data.pyg.org/whl/torch-1.8.0+cu111.html. This should work fine for PyTorch 1.8.2 as well. Please note that you need to specify the most recent supported version of these packages when installing for older PyTorch versions.

**Comment by wickcode** [comment]
Thank you.
