### ISSUE TITLE
Bug on line 132 in the 'tudataset.py' file

### ISSUE THREAD

**Issue by StevanStanovic** [pyg-team/pytorch_geometric#5360]
### 🐛 Describe the bug

Hello,

There is a bug on line 132 in the 'tudataset.py' file for the 2.1.0 version of Pytorch Geometric.
The message error is:
ValueError: not enough values to unpack (expected 3, got 2)

I fixed it by removing the 'self.sizes' part and replacing the 'num node_labels', 'num_node attributes', 'num_edge_labels' and 'num_edge attributes' methods with those from version 2.0.4.

I have attached a screenshot (PNG image) of my solution. I hope this will be useful.

Stevan Stanovic

 
![screenshot](https://user-images.githubusercontent.com/61746436/188644398-5690a4a6-a9db-48d2-bb51-cd75d3e74288.png)

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12.1
* OS: Linux
* Python version: 3.9.12
* CUDA/cuDNN version: 11.6
* How you installed PyTorch and PyG (`conda`, `pip`, source): 
  conda create -n test python=3.9.12
  conda activate test
  pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
  pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch                         1.12.1+cu116
torch-cluster             1.6.0
torch-geometric        2.1.0.post1
torch-scatter             2.0.9
torch-sparse             0.6.15
torch-spline-conv     1.2.1
torchaudio               0.12.1+cu116
torchvision              0.13.1+cu116

**Comment by rusty1s** [comment]
Mh, if `len(out) != 3` then it should raise a `RuntimeError` in L127. Can you verify why this error is not thrown for you? Furthermore, try to remove any old processed data from PyG 2.0.4 and try again. I am pretty sure `TUDataset` works just fine with PyG 2.1.0 (at least it works flawlessly for me).

**Comment by StevanStanovic** [comment]
The 'If' condition is not correct. I think the 'if' condition below is the solution for the 2.1.0 version. 

if not(isinstance(out, tuple) and len(out) == 3)

If the two conditions are True, the RumtimeError appears, and, inversely, if one of the two conditions is False.

Thank you for the quick response.

**Comment by rusty1s** [comment]
Oh, you are right. Is has to be `if not(isinstance(out, tuple) or len(out) == 3)`.
