### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by Diego0511** [pyg-team/pytorch_geometric#5383]
### 📚 Describe the documentation issue

Hi,

I have a suggestion for the documentation. Why not just providing a simple example for all the APIs just like Pytorch official documentation. I am pretty sure this would be more convenient for users to know how exactly those APIs work. Thank you
 

### Suggest a potential alternative/fix

Need a simple example so that users can know how to use those APIs

**Comment by rusty1s** [comment]
Do you mean for `torch_geometric.utils` or for every module provided in PyG? A lot of these modules built upon similar principles so I assume this would result in a lot of duplicated code examples. Anyway, I am always happy to improve documentation, but would need to rely on help to integrate this.

**Comment by Diego0511** [comment]
Thank you for your reply.
Yep. I think torch_geometric.utils might be the first priority, cause it's a very common used module in PyG. For the rest modules, I guess a simple example can also be provided if the usage is not that straightforward?

**Comment by rusty1s** [comment]
Sounds great. Shall we split the work and collect all functions for which we want to provide an example?

**Comment by Diego0511** [comment]
Yep. Looks like a good idea!

**Comment by EdisonLeeeee** [comment]
Would you mind if I take this task? I plan to add PyTorch-style code examples to `torch_geometric.utils` functions.

**Comment by rusty1s** [comment]
@EdisonLeeeee would be great to get help in. I will be collecting all functions we want to add an example for in this issue here, but this shouldn‘t stop you from going ahead :)

**Comment by rusty1s** [comment]
@EdisonLeeeee did an amazing job and just integrated it :)
