### ISSUE TITLE
ASAPooling :  torch.jit.script export failed

### ISSUE THREAD

**Issue by huang229** [pyg-team/pytorch_geometric#5385]
### 🐛 Describe the bug

ASAPooling :  torch.jit.script export failed.  I hope to get help. Thank you.

#code

cconv2=ASAPooling(128, ratio=0.25, dropout=0.0)
conv2 = torch.jit.script(conv2)

#error
Module 'LEConv' has no attribute 'inspector' (This attribute exists on the Python module, but we failed to convert Python type: 'torch_geometric.nn.conv.utils.inspector.Inspector' to a TorchScript type. Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type Inspector.. Its type was inferred; try adding a type annotation for the attribute.):
  File "D:\huangchaolin\teeth_classfication_train\torch_geometric\nn\conv\message_passing.py", line 470
    
        self._explain = explain
        self.inspector.inspect(self.explain_message, pop_first=True)
        ~~~~~~~~~~~~~~ <--- HERE
        self.__user_args__ = self.inspector.keys(methods).difference(
            self.special_args)

python-BaseException



### Environment

* PyG version:2.04
* PyTorch version:1.11.0
* OS: windows
* Python version:3.7.0
* CUDA/cuDNN version:  cuda=11.3.1   cudnn not have
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
* pytorch-scatter==2.0.9
* pytorch-sparse==0.6.13
* pytorch-cluster==1.6.0

**Comment by rusty1s** [comment]
Thanks for confirming. I pushed a fix here: https://github.com/pyg-team/pytorch_geometric/pull/5395
```python
torch.jit.script(pool.jittable())
```
should work now.
