### ISSUE TITLE
Learning Separate Transformation Matrix for Different Nodes

### ISSUE THREAD

**Issue by zc-alexfan** [pyg-team/pytorch_geometric#539]
## ❓ Questions & Help

I am working on an application in which all examples have the **same graph structure**. 

Most graph network (such as `GCNConv`) use a shared transformation matrix for all nodes. However, one could leverage the fixed graph structure of each example by either: 
1. Learn different transformation matrix for each node. 
OR
2. Learn some kind of attention (aka probability mask) over neighbours of a node for aggregation (such as attentional GCN in Graph RCNN).
OR
3. An approximation of 1. 

I am wondering what do you recommend to leverage the relationships between nodes in a dataset which always has the same graph?

**Comment by rusty1s** [comment]
This sounds good to me. I see that you [have found a paper](https://github.com/rusty1s/pytorch_geometric/issues/541) which already does your proposed approach 2. An alternative could be to learn additional parameters for each node and append those to its input features (which is closely related to 1, but comes with much less parameters).
