### ISSUE TITLE
FileNotFoundError: Could not find module 'E:\python38\Lib\site-packages\torch_sparse\_convert_cpu.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by RENEK-bool** [pyg-team/pytorch_geometric#5394]
### 😵 Describe the installation problem

python 3.8.10
torch 1.12.1+cpu

I followed the pip command below to complete the installation.

pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
pip install torch-geometric
pip install torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
pip install torch-spline-conv -f https://data.pyg.org/whl/torch-1.12.1+cpu.html

After the installation is complete, I run the following Python command
import torch_geometric

 and get an error as shown in the title

Could you please help me solve this problem?

### Environment

* PyG version:
* PyTorch version: 
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): 
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Can you post the installation log of running
```
pip install --verbose --no-cache-dir torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
pip install --verbose --no-cache-dir torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
```
You might want to uninstall previous versions first.

**Comment by RENEK-bool** [comment]
I upgraded the Python version to 3.9.13 and the installation was complete without any errors when importing Python packages.
