### ISSUE TITLE
Having trouble installing torch-scatter (Win10)

### ISSUE THREAD

**Issue by kunwuz** [pyg-team/pytorch_geometric#540]
## Environment

* OS: Win10
* Python version: 3.6.8
* PyTorch version: 1.10
* CUDA/cuDNN version: 9
* GCC version: 8.1.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v9.0\bin\nvcc -c cuda/scatter_kernel.cu -o build\temp.win-amd64-3.6\Release\cuda/scatter_kernel.obj -Xcompiler /wd4819 -Xcompiler /MD -If:\anaconda3\envs\tf-gpu\lib\site-packages\torch\include -If:\anaconda3\envs\tf-gpu\lib\site-packages\torch\include\torch\csrc\api\include -If:\anaconda3\envs\tf-gpu\lib\site-packages\torch\include\TH -If:\anaconda3\envs\tf-gpu\lib\site-packages\torch\include\THC "-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v9.0\include" -If:\anaconda3\envs\tf-gpu\include -If:\anaconda3\envs\tf-gpu\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0
    **error: command 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\\v9.0\\bin\\nvcc' failed: No such file or directory

ERROR: Command "'f:\anaconda3\envs\tf-gpu\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-_kfpmpw3\\torch-scatter\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-sdcwvgeh\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\LENOVO\AppData\Local\Temp\pip-install-_kfpmpw3\torch-scatter\**

**But when I check the version of nvcc:

(tf-gpu) C:\Users\LENOVO>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176**

## Checklist

- [Y] I followed the installation guide.
- [Y] I cannot find my error message in the FAQ.
- [Y] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment]
The installation looks for `nvcc` in `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v9.0\bin\` and cannot find it there. Where is your CUDA installation located? It may help to add the `CUDA_HOME` environment variable to your path.

**Comment by kunwuz** [comment]
Thanks, it works for the first error.
But here comes the next and it doesn't seem like to be related with environment path.

   nvcc error   : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
    error: command 'F:\\CUDA9\\bin\\nvcc.exe' failed with exit status 5
    ----------------------------------------
ERROR: Command "'f:\anaconda3\envs\tf-gpu\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-nqp4502s\\torch-scatter\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-ht6r9ufc\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\LENOVO\AppData\Local\Temp\pip-install-nqp4502s\torch-scatter\

**Comment by rusty1s** [comment]
Uff, I never encountered an exit status of 5 in `nvcc`. It seems that CUDA 9 and Visual Studio do not play nicely together, see, *e.g.*, [here](https://github.com/vlfeat/matconvnet/issues/1201).
