### ISSUE TITLE
Confusing notation/source for AttentionalAggregation

### ISSUE THREAD

**Issue by RafiBrent** [pyg-team/pytorch_geometric#5400]
### 📚 Describe the documentation issue

I may be misunderstanding the documentation/code, and if so please correct me. However, I believe there are a few issues with the documentation for AttentionalAggregation. The first confusing aspect is the use of the Hadamard product symbol between the softmaxed output of h_gate (shape [-1, 1]) and the output of h_theta (shape [-1, out_channels]). As I understand it, the mathematical convention is that this symbol is only used between arrays of the same size, so if what is actually happening is that each row of the output of h_theta is scalar-multiplied by the corresponding entry of h_gate, I believe there is a clearer way to express this. Secondly, and more importantly, I believe that this module is performing a fundamentally different aggregation function from that in the paper that is cited in the documentation. Despite the superficial similarity of the formulas involved, Equation 3 in the “Gated Graph Sequence Neural Networks” paper involves applying a neural network to a feature vector pertaining to a single node, outputting a vector (rather than a scalar) and then softmaxing across this modified feature vector. Thus, instead of a single softmaxed vector of size num_nodes, the neural network from the paper actually generates num_nodes different softmaxed vectors, each of which are independently element-wise multiplied by the corresponding output of the second neural network. Fundamentally, it seems that the operation in the paper is applying attentional weights to the channels of each (post-neural-network) feature vector, while the operation in PyG is applying attentional weights to the set of nodes as a whole (since all channels of a given node are multiplied by the same scalar output of h_gate). Please let me know if this interpretation is correct, and if so it would be helpful if the citation were modified in some way to avoid the confusion. Thanks so much for your help.

**Comment by rusty1s** [comment]
Really sorry for the late reply. Interestingly, we use the implementation from https://arxiv.org/pdf/1904.12787.pdf (Eq. 3) which cites the initial work of Li et al., 2015. I will change the reference in the documentation.

**Comment by rusty1s** [comment]
https://github.com/pyg-team/pytorch_geometric/pull/5448

**Comment by rusty1s** [comment]
Also added support for feature-level gating, see https://github.com/pyg-team/pytorch_geometric/pull/5449.

**Comment by RafiBrent** [comment]
Sorry to reopen this issue, but I wanted to check the exact function of the node-level gating implementation. Based on the equation in the docs, it looks like the output of h_gate on each set of node features is softmaxed individually, but if h_gate reduces each set of node features to a scalar then this would simply return 1, reverting the whole process to an unweighted sum of the outputs of h_theta. On the other hand, true node-level gating would require softmaxing the entire collection of outputs of h_gate (a vector of length N_i) and then using the elements of this vector to weight the corresponding output vectors of h_theta before summing them all together. Please let me know if I'm missing something here, but I believe that either the documentation or the code need to be modified for true node-level attentional aggregation.
