### ISSUE TITLE
ShaDowKHopSampler creates incorrect data.batch when using Batch graph

### ISSUE THREAD

**Issue by cvanea** [pyg-team/pytorch_geometric#5409]
### 🐛 Describe the bug

Hello! Firstly, thank you for this fantastic library.

I am trying to run various scalable GNNs on custom data but I am having an issue with shaDow.

On this line in the shaDow model definition (as per the example):
`x = torch.cat([x[root_n_id], global_mean_pool(x, batch)], dim=-1)`
This error is thrown:
`RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1024 but got size 1 for tensor number 1 in the list.`
Where 1024 is the batch size.

I've found this is only a problem when the graph dataset is composed into a disjointed `Batch` graph.

To reproduce the problem, run the code from `examples/shadow.py` but change the data object into a `Batch` object:

```
from torch_geometric.data import Batch
dataset = Flickr(path)
datas = [dataset[0]]
data = Batch.from_data_list(datas)
```

Thank you for any help!

### Environment

* PyG version: 2.1.0.post1
* PyTorch version: 1.11.0+cu113
* OS: Ubuntu 20.04.2 (WSL) and macOS 11.1
* Python version: 3.7.2
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
Hi @cvanea 

I can indeed reproduce this error and I solved it by deleting the attribute `batch` in `data`:
```python

from torch_geometric.data import Batch
dataset = Flickr(path)
datas = [dataset[0]]
data = Batch.from_data_list(datas)
del data.batch # here
```
I understand that this solution might not be perfect. Will investigate it further and report back.

**Comment by EdisonLeeeee** [comment]
To be fixed in [this PR](https://github.com/pyg-team/pytorch_geometric/pull/5410).

**Comment by cvanea** [comment]
Thanks! This has fixed it on my data as well. 

One additional note, in the `shadow.py` example it may be worth changing `data.num_graphs` as the count of nodes in each batch to `out.size()[0]`. With more than 1 graph in `Batch` this key is overridden as well. That should probably also be added to the excluded keys in the PR change.

**Comment by EdisonLeeeee** [comment]
Thanks for your suggestion! I think `num_graphs` would not be overridden as it is not an attribute but a property() method. Also, the key `num_graphs` was already excluded when iterating `self.data`.  WDYT?

**Comment by cvanea** [comment]
Apologies, I explained that badly.

Before passing in a `Batch` object to the shadow dataloader, `data.num_graphs` would return 1024 (the batch size) in the example file:

https://github.com/pyg-team/pytorch_geometric/blob/0da9e1903c3b8ffd41b9a51b9e481dd1ba616a7f/examples/shadow.py#L61

After passing in a `Batch` object, it now returns the number of graphs used to construct the `Batch` object. In my case that was 2, which led to some funny accuracies (630% accuracy!)

I guess this isn't an issue unless someone tries to use the example file code with their own `Batch` input graph.

**Comment by EdisonLeeeee** [comment]
Thank you for making it clear. I get your point now. Previously, `data.num_graphs` is calculated by `batch.max() + 1`, which would lead to a wrong result if `batch` was overridden in the sampler (e.g., passing a `Barch` object).

Now I think `data.num_graphs` would return a correct result even passing a `Batch` object after the fix in PR. I've tested the `example/shadow.py` example with your case, and it works fine -- `data.num_graphs` always equals `out.size(0)`.

**Comment by cvanea** [comment]
Thanks very much! I'm closing the Issue then :)
