### ISSUE TITLE
Possible typos in the docstring of `GENConv`

### ISSUE THREAD

**Issue by yuanx749** [pyg-team/pytorch_geometric#5412]
### 📚 Describe the documentation issue

I am trying to use `GENConv` on bipartite graphs. According to the [docstring](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GENConv), the `in_channels` can be `int` or `tuple`. And it also says input node features $((|{V_s}|, F_{in}), (|{V_t}|, F_{t})$ if bipartite.

However, if a tuple is passed, e.g. `GENConv(in_channels=(-1, -1), out_channels=4)`, I get `TypeError: '>' not supported between instances of 'tuple' and 'int'`.

Does `GENConv` only support bipartite graph with the same feature dimensionality for source and destination nodes?

### Suggest a potential alternative/fix

in_channels (int or tuple) -> in_channels (int)
$((|{V_s}|, F_{in}), (|{V_t}|, F_{t})$ -> $((|{V_s}|, F_{in}), (|{V_t}|, F_{in})$

I can submit a PR to fix the docstring, if there are indeed typos.

**Comment by rusty1s** [comment]
Thank you! I fixed this in master, see https://github.com/pyg-team/pytorch_geometric/pull/5450.

**Comment by lightaime** [comment]
Hi @yuanx749, thanks for the issue. Now you can use `GENConv` for bipartite graphs. See https://github.com/pyg-team/pytorch_geometric/pull/5627 for the fix.
