### ISSUE TITLE
torch.sparse

### ISSUE THREAD

**Issue by DivyaWadehra** [pyg-team/pytorch_geometric#542]
from torch_sparse import coalesce
ImportError: No module named 'torch_sparse'

**Comment by rusty1s** [comment]
It seems that `torch_sparse` is not installed. How did you try to install it? Try to run
```
pip install --verbose --no-cache-dir torch-sparse
```
and see if there are any errors during installation.

**Comment by MichalisLazarou** [comment]
I also use the exact command and I still get an error No module named 'torch_sparse'

**Comment by qiulesun** [comment]
I met the same error and I have successfully run pip install --verbose --no-cache-dir torch-sparse. 
What should I do next ?

**Comment by rusty1s** [comment]
This seems strange. As long as `torch-sparse` is listed in `pip list`, it should find the module. There can be only an installation error which prevents that or you may have different python installations, and you install it in to a different python location. In addition, you can alway try to install from source and see if this fixes the issue.

**Comment by qiulesun** [comment]
When I run pip install --verbose --no-cache-dir torch-sparse, the error occurs.

root@hh-ubuntu:/home/hh# pip install --verbose --no-cache-dir torch-sparse
Created temporary directory: /tmp/pip-ephem-wheel-cache-1lc3vaps
Created temporary directory: /tmp/pip-req-tracker-sxiwp27z
Created requirements tracker '/tmp/pip-req-tracker-sxiwp27z'
Created temporary directory: /tmp/pip-install-v9mjfxtu
Collecting torch-sparse
  1 location(s) to search for versions of torch-sparse:
  * https://pypi.org/simple/torch-sparse/
  Getting page https://pypi.org/simple/torch-sparse/
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/torch-sparse/ HTTP/1.1" 200 835
  Analyzing links from page https://pypi.org/simple/torch-sparse/
    Found link https://files.pythonhosted.org/packages/21/a6/af5865f7bc2dc45ea789ebb35bdf5d84c05e140d7d2ec7e5823d24db176f/torch_sparse-0.1.0.tar.gz#sha256=d774c4b05a96bf09e3c3becd2f48c65ed66b03195a2cfc4992ef57c9a8c6b399 (from https://pypi.org/simple/torch-sparse/), version: 0.1.0
    Found link https://files.pythonhosted.org/packages/02/4f/89bcb156022a3960c4db852915c64ea78b4e993e0f8d7a83e60e6819fc11/torch_sparse-0.2.0.tar.gz#sha256=578fdc3522b06c948d43fbc360d0dcde8a89d9a2496ac468592bf3493baedd33 (from https://pypi.org/simple/torch-sparse/), version: 0.2.0
    Found link https://files.pythonhosted.org/packages/8f/41/98db80cc9d9345c76445393661ce4dd3e08fc46fb17028e7706612063e4d/torch_sparse-0.2.1.tar.gz#sha256=01346234f0e76103304f8aa1099f22c0904d2fff8b36c5ec0230335149f526bc (from https://pypi.org/simple/torch-sparse/), version: 0.2.1
    Found link https://files.pythonhosted.org/packages/73/5b/5b7b6c66148afaa5e2ed8a3e18e109361957d28e67032d92cb282d173f32/torch_sparse-0.2.2.tar.gz#sha256=11e87c0214a4491168f15726ddda6c771b5f34be728f3edbb4add203e46d924d (from https://pypi.org/simple/torch-sparse/), version: 0.2.2
    Found link https://files.pythonhosted.org/packages/43/2a/bb2ead5b33c6932937c6c74199ebecd72bd4b3ab224842a50366e5b2af4a/torch_sparse-0.2.3.tar.gz#sha256=47b3f85b0c243d0c98798db722b0f066830f6b8ff9d298a6e2aed0662598e356 (from https://pypi.org/simple/torch-sparse/), version: 0.2.3
    Found link https://files.pythonhosted.org/packages/73/72/e374662f6f47d9ac0e082a6d5c18d14e15c52863e89c6bc6957a0d2ed026/torch_sparse-0.2.4.tar.gz#sha256=5cae8b40a5d11b8917e0f4b95034b5842b052f42a089ce59f8c02f2cff00ca55 (from https://pypi.org/simple/torch-sparse/), version: 0.2.4
    Found link https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz#sha256=bf217539b4f714a1d6fac4d39ace3ad8033871717f44f8f365a2746056b9d805 (from https://pypi.org/simple/torch-sparse/), version: 0.4.0
  Using version 0.4.0 (newest of versions: 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.4.0)
  Created temporary directory: /tmp/pip-unpack-o9_p7qzz
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz HTTP/1.1" 200 10444
  Downloading https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz#sha256=bf217539b4f714a1d6fac4d39ace3ad8033871717f44f8f365a2746056b9d805 (from https://pypi.org/simple/torch-sparse/)
  Added torch-sparse from https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz#sha256=bf217539b4f714a1d6fac4d39ace3ad8033871717f44f8f365a2746056b9d805 to build tracker '/tmp/pip-req-tracker-sxiwp27z'
  Running setup.py (path:/tmp/pip-install-v9mjfxtu/torch-sparse/setup.py) egg_info for package torch-sparse
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/torch_sparse.egg-info
    writing pip-egg-info/torch_sparse.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/torch_sparse.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/torch_sparse.egg-info/requires.txt
    writing top-level names to pip-egg-info/torch_sparse.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/torch_sparse.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/torch_sparse.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/torch_sparse.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-v9mjfxtu/torch-sparse has version 0.4.0, which satisfies requirement torch-sparse from https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz#sha256=bf217539b4f714a1d6fac4d39ace3ad8033871717f44f8f365a2746056b9d805
  Removed torch-sparse from https://files.pythonhosted.org/packages/b0/0a/2ff678e0d04e524dd2cf990a6202ced8c0ffe3fe6b08e02f25cc9fd27da0/torch_sparse-0.4.0.tar.gz#sha256=bf217539b4f714a1d6fac4d39ace3ad8033871717f44f8f365a2746056b9d805 from build tracker '/tmp/pip-req-tracker-sxiwp27z'
Requirement already satisfied: scipy in /usr/anaconda3/lib/python3.6/site-packages (from torch-sparse) (1.1.0)
Installing collected packages: torch-sparse
  Created temporary directory: /tmp/pip-record-u1t4qisr
  Running setup.py install for torch-sparse ...     Running command /usr/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v9mjfxtu/torch-sparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-u1t4qisr/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/spmm.py -> build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/convert.py -> build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/transpose.py -> build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/eye.py -> build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/__init__.py -> build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/coalesce.py -> build/lib.linux-x86_64-3.6/torch_sparse
    copying torch_sparse/spspmm.py -> build/lib.linux-x86_64-3.6/torch_sparse
    creating build/lib.linux-x86_64-3.6/test
    copying test/test_spmm.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_eye.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_transpose.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_convert.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_spspmm.py -> build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_coalesce.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_spspmm_spmm.py -> build/lib.linux-x86_64-3.6/test
    copying test/utils.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torch_sparse/utils
    copying torch_sparse/utils/unique.py -> build/lib.linux-x86_64-3.6/torch_sparse/utils
    copying torch_sparse/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_sparse/utils
    running build_ext
    building 'torch_sparse.spspmm_cpu' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cpu
    gcc -pthread -B /usr/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/anaconda3/include/python3.6m -c cpu/spspmm.cpp -o build/temp.linux-x86_64-3.6/cpu/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spspmm_cpu -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:10:0,
                     from /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/utils/pybind.h:5,
                     from /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/extension.h:5,
                     from cpu/spspmm.cpp:1:
    cpu/spspmm.cpp: In lambda function:
    cpu/spspmm.cpp:34:48: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘at::ScalarType’
       AT_DISPATCH_FLOATING_TYPES(valueA.scalar_type(), "spspmm_bw", [&] {
                                                    ^
    /usr/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
         const at::Type& the_type = TYPE;                                         \
                                    ^
    **error: command 'gcc' failed with exit status 1
error**
Cleaning up...
  Removing source in /tmp/pip-install-v9mjfxtu/torch-sparse
Removed build tracker '/tmp/pip-req-tracker-sxiwp27z'
Command "/usr/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v9mjfxtu/torch-sparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-u1t4qisr/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-v9mjfxtu/torch-sparse/
Exception information:
Traceback (most recent call last):
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 791, in install
    spinner=spinner,
  File "/usr/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-v9mjfxtu/torch-sparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-u1t4qisr/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-v9mjfxtu/torch-sparse/
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 11615

**Comment by rusty1s** [comment]
```
definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
const at::Type& the_type = TYPE;
^
error: command 'gcc' failed with exit status 1
```
You need to upgrade to PyTorch 1.1 :)

**Comment by qiulesun** [comment]
Now I have to use PyTorch 1.0.0 for my current work. Besides, I also want to use your pytorch_geometric  to deal with works involving graph convolution. Do you have any idea to handle that incompatibility.

**Comment by rusty1s** [comment]
According to the [releases](https://github.com/rusty1s/pytorch_scatter/releases), you can try to install `torch-scatter==1.1.2` and repeat this process for the other packages. We rely on a lot of internal PyTorch APIs for our extension modules, which gets changed quite rapidly by the PyTorch team. Not much I can do about it. Sorry :(

**Comment by qiulesun** [comment]
Following your suggestion, I have successfully install the packages as follows:

torch-cluster                      1.2.4
torch-geometric                    1.2.1          
torch-scatter                      1.1.2          
torch-sparse                       0.2.3          
torch-spline-conv                  1.0.6 

Thanks for your timely help.

root@hh-ubuntu:/home/hh# python
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_scatter
>>> import torch_sparse
>>> import torch_cluster
>>> import torch_geometric

**Comment by shuhongwang-zzu** [comment]
pip install --verbose --no-cache-dir torch-sparse    install error!!!!
ERROR: Command "'e:\anaconda\envs\pytorch\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\13224\\AppData\\Local\\Temp\\pip-install-wzr8089_\\torch-sparse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\13224\AppData\Local\Temp\pip-record-hxu3uth7\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\13224\AppData\Local\Temp\pip-install-wzr8089_\torch-sparse\

**Comment by ddehueck** [comment]
Ran into this issue using pytorch 1.3 - had to clone and `$ pip install .` each package referenced in the installation guide.

**Comment by jiachangliu** [comment]
@ddehueck Thank you. In my case, I have to reinstall CUDA and cuDNN. Then install all dependences from the source. Then it works.

**Comment by harshadindigal** [comment]
Hello, I am trying to download the CoraFull dataset and apply/recreate the SplineCNN classifier. I am running into issues loading the data with the torch_sparse import. (I am in google collab), When I do the pip install verbose, I get an error saying that the Cuda Versions of Pytorch and Toche_Sparse are different (10.1 vs. 10 respectively). How can I rectify this as I don't think colab can go backwards in cuda versions?

**Comment by harshadindigal** [comment]
@rusty1s

**Comment by rusty1s** [comment]
Install the packages with the currect CUDA version:
```
pip install torch-scatter==latest+cu101 torch-sparse==latest+cu101 -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
```

**Comment by albertotono** [comment]
I am getting the same issue now, but I have cuda11

**Comment by rusty1s** [comment]
Do you have a local CUDA11 or are you using the PyTorch CUDA 11 package? You should be able to compile the libraries for CUDA 11 from source, and I'm currently working on providing CUDA 11 wheels.

**Comment by GoingMyWay** [comment]
Installing this library is real slow, showing `Building wheel for torch-sparse (setup.py) ... |`

```
$ pip3.7 install torch_sparse
Collecting torch_sparse
  Downloading torch_sparse-0.6.8.tar.gz (34 kB)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from torch_sparse) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scipy->torch_sparse) (1.19.2)
Building wheels for collected packages: torch-sparse
  Building wheel for torch-sparse (setup.py) ... /
```
Could you please create wheel files to provide fast installation?

**Comment by rusty1s** [comment]
There already exists [wheel files](https://github.com/rusty1s/pytorch_geometric#installation) for a smoother installation.

**Comment by GoingMyWay** [comment]
> There already exists [wheel files](https://github.com/rusty1s/pytorch_geometric#installation) for a smoother installation.

Thank you very much.

**Comment by rusty1s** [comment]
Try
```
pip install torch-sparse=0.6.13 -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```

**Comment by lucy66666** [comment]
> 
Build wheels still take forever with wheel files for torch 1.11?

**Comment by rusty1s** [comment]
If the wheels will install forever, this means that it does not really take up the wheels and tries to compile manually. Try.
```
pip install --no-index --verbose torch-sparse==0.6.13 -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
```
