### ISSUE TITLE
ASAPooling: jit.save function model export failed

### ISSUE THREAD

**Issue by huang229** [pyg-team/pytorch_geometric#5421]
### 🐛 Describe the bug

ASAPooling: jit.save function model export failed. I need your help, thank you very much!

```python
class ASAP(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.asapooling = ASAPooling(128, ratio=0.25, dropout=0.0).jittable()

    def forward(self, x, edge_index):

        edge_weight = None
        batch = torch.zeros((x.shape[0])).cuda().long()
        x, edge_index, edge_weight, batch, _ = self.asapooling(
            x=x, edge_index=edge_index, edge_weight=edge_weight,
            batch=batch)

        return x
model = ASAP()
mm = torch.jit.script(model)
torch.jit.save(mm,"asapooling.pt")
```
#error 
Traceback (most recent call last):
  File "D:\pycharm\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python_program/mesh_gcn/teeth_classfication/net/jit_model.py", line 210, in <module>
    torch.jit.save(mm,"asapooling.pt")
  File "D:\Anaconda3\envs\teeth_deploy\lib\site-packages\torch\jit\_serialization.py", line 81, in save
    m.save(f, _extra_files=_extra_files)
  File "D:\Anaconda3\envs\teeth_deploy\lib\site-packages\torch\jit\_script.py", line 693, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: 
Could not export Python function call '<python_value>'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
  File "E:\python_program\mesh_gcn\teeth_classfication\torch_geometric\utils\scatter.py", line 66
            out: Optional[Tensor] = None, dim_size: Optional[int] = None,
            reduce: str = 'sum') -> Tensor:
    return _scatter_impl(src, index, dim, out, dim_size, reduce)
           ~~~~~~~~~~~~~ <--- HERE


Process finished with exit code -1




### Environment

PyG version:2.04
PyTorch version:1.11.0
OS: windows
Python version:3.7.0
CUDA/cuDNN version: cuda=11.3.1 cudnn not have
How you installed PyTorch and PyG (conda, pip, source): conda
Any other relevant information (e.g., version of torch-scatter):
pytorch-scatter==2.0.9
pytorch-sparse==0.6.13
pytorch-cluster==1.6.0

**Comment by rusty1s** [comment]
Thanks for reporting. This looks to be an issue with how we treat the conditional `torch-scatter` implementation right now. @dszwicht Do you have any idea on how to fix this?
