### ISSUE TITLE
cannot import the aggregation module

### ISSUE THREAD

**Issue by LiuCMU** [pyg-team/pytorch_geometric#5443]
### 🐛 Describe the bug

Hi, I tried to import `SumAggregation`, but it always yielded `ImportError`.  I can import other packages, though. Here is an example:

```{Python}
(py39) liucmu@storm:~/reaction_prediction$ ipython
Python 3.9.12 (main, Jun  1 2022, 11:38:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from torch_geometric.nn import aggr
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from torch_geometric.nn import aggr

ImportError: cannot import name 'aggr' from 'torch_geometric.nn' (/home/liucmu/miniconda3/envs/py39/lib/python3.9/site-packages/torch_geometric/nn/__init__.py)

In [2]: from torch_geometric.nn import Set2Set

In [3]: import torch_geometric.nn.aggr
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 import torch_geometric.nn.aggr

ModuleNotFoundError: No module named 'torch_geometric.nn.aggr'

In [4]: import torch_geometric.data

In [5]: 

```

Could you please take a look? Thank you!

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.11.0
* OS: Ubuntu 18.04.5 LTS
* Python version: 3.9.12
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): N/A

**Comment by EdisonLeeeee** [comment]
Hi @LiuCMU 

The module `aggr` is supported for PyG>=2.1.0. Just need to upgrade your PyG.

**Comment by LiuCMU** [comment]
Hi,

Thank you very much for the quick response.

May I have a follow-up question about using the `SumAggregation`: To use the aggregation on a batch of graphs, should I provide an `index` vector, or `data.batch`, as the additional argument? 

The [documentation](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#aggregation-operators:~:text=We%20can%20then%20easily%20apply%20these%20aggregations%20over%20a%20batch%20of%20sets%20of%20potentially%20varying%20size.%20For%20this%2C%20an%20index%20vector%20defines%20the%20mapping%20from%20input%20elements%20to%20their%20location%20in%20the%20output%3A) said `index`, but I don't know how to prepare a customized index vecotr for the graph batch.
Based on my experience with `Set2Set`, providing `data.batch` is enough.

FYI, here is my model:
```
class Net(torch.nn.Module):
    def __init__(self, num_features, graph_dim, max_degree, num_conv, num_layers, layer_dim):
        super().__init__()
        self.lin0 = torch.nn.Linear(num_features, graph_dim)
        self.conv = MFConv(graph_dim, graph_dim, max_degree, aggr='sum')
        # self.set2set = Set2Set(graph_dim, processing_steps=3)  #The set2set is used to map from nodes to graphs
        # self.lin1 = torch.nn.Linear(2*graph_dim, layer_dim)
        self.aggregation = SumAggregation()
        self.lin1 = torch.nn.Linear(graph_dim, layer_dim)
        self.layers = torch.nn.ModuleList([torch.nn.Linear(layer_dim, layer_dim) for _ in range(num_layers)])
        self.lin2 = torch.nn.Linear(layer_dim, 1)
        self.num_conv = num_conv
        self.num_layers = num_layers

    def forward(self, data):
        out = F.relu(self.lin0(data.x))  #data.x size [batch_num_nodes, num_node_features]
        for _ in range(self.num_conv):
            out = F.relu(self.conv(out, data.edge_index))
        # out = self.set2set(out, data.batch)  #[batch_num_nodes, dim] ==> [batch_num_graphs, dim*2]
        out = self.aggregation(out, data.batch)
        out = F.relu(self.lin1(out))
        for i in range(self.num_layers):
            out = F.relu(self.layers[i](out))
        out = self.lin2(out)
        return out.view(-1)
```
Previously, I was using `Set2Set`. Now I am switching to simple `SumAggregation` to make the model simpler. 
Thanks again!

**Comment by LiuCMU** [comment]
Oh, I might figure it out: `data.batch` is the so-called "index vector" here. Pytorch Geometric dataset object already prepared the index vector for me.

**Comment by EdisonLeeeee** [comment]
Yes, it is. Since all aggregations share the same set of forward arguments, there is no need for you to change the "index vector" when switching from `Set2Set` to `SumAggregation `, `MeanAggregation`, etc.
