### ISSUE TITLE
the role of edge attribute when doing GNN with MetaLayer

### ISSUE THREAD

**Issue by ICDI0906** [pyg-team/pytorch_geometric#545]
## ❓ Questions & Help

I recently think about the questions that what is the role of edge attribute with dimension size one when doing GNN with MetaLayer to learn node embedding.Is it just the connectivity between two nodes? I say that because when I random the edge attribute without changing the structure of the graph, the performance doesn't change a lot!
Have a nice weekend!  :)

**Comment by rusty1s** [comment]
Well, the edge attributes are just edge features that denote how neighboring nodes should be aggregated. Hence, neighboring nodes with different edge features *can* be aggregated differently (in contrast to something like `GCNConv`). It seems strange that your model does not seem to not make use of these features. Maybe they are not especially useful for the given task?

**Comment by ICDI0906** [comment]
Yes, It may be. I just want to learn the node embedding as the input to LSTM. And I want to test how important the edge attribute. So I make the experiments with the truth attribute and the random attribute separately. But the performance differs less than 1%. So I think the edge attribute just like a bridge for message passing and doesn't impose so much information.
