### ISSUE TITLE
CUDA 11.4 version problem results in installing failed

### ISSUE THREAD

**Issue by un0o7** [pyg-team/pytorch_geometric#5464]
### 😵 Describe the installation problem

I am using cuda11.4 which you do not provide install doc on this version cuda. So I'd like to ask why? 

### Environment

* PyG version: latest
* PyTorch version:1.11.0
* OS:linux
* Python version:3.7
* CUDA/cuDNN version: 11.4
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by nestiank** [comment]
I think installing with `cu113` is applicable. It should be compatible.
