### ISSUE TITLE
MessagePassing.propagate() computes the contraction with the transpose

### ISSUE THREAD

**Issue by Stannislav** [pyg-team/pytorch_geometric#549]
**Short:** if `(edge_index, norm)` represent the matrix `M` in the sense that `M = to_scipy_sparse_matrix(edge_index, norm)` then `MessagePassing.propagate(edge_index, x, norm)` computes `M.T @ x`, so `M` is implicitly transposed in the process

**Example**
```python
# Create matrix M and vector x
row = np.array([0, 0])
col = np.array([1, 2])
norm = np.array([1, 1])
num_nodes = 3
x = np.array([[2, 3, 4], [5, 6, 7]]).T

# Compute M@x and M.T@x explicitly
M = scipy.sparse.coo_matrix((norm, (row, col)), shape=(num_nodes, num_nodes))
print("M:\n", M.toarray())
print("x:\n:", x)
print("M @ x:\n", M @ x)
print("M.T @ x:\n", M.T @ x)

# Compute MessagePassing.propagate
conv = torch_geometric.nn.MessagePassing()  # flow='source_to_target'
edge_index = torch.tensor([row, col])
conv_result = conv.propagate(edge_index=edge_index,
                             x=torch.tensor(x),
                             norm=norm)
print("conv:")
print(conv_result)
```
output:
```
M:
 [[0 1 1]
 [0 0 0]
 [0 0 0]]
x:
: [[2 5]
 [3 6]
 [4 7]]
M @ x:
 [[ 7 13]
 [ 0  0]
 [ 0  0]]
M.T @ x:
 [[0 0]
 [2 5]
 [2 5]]
conv:
tensor([[0, 0],
        [2, 5],
        [2, 5]])

```
So we see that `M.T @ x` is computed.

**Comments:**
This is probably the way it is supposed to work, but at least for me it was not very intuitive, that's why I wanted to mention it. If I understand correctly, the reason why it works that way is that in PyG `edge_index=(row, col) = (source, target)`, while for `M @ x` one should have `row=target` and `col=source`.

While the transposition of `M` can be called a convention, and wouldn't matter for  symmetric `M`, this might be a source of confusion for directed graphs.

**Comment by rusty1s** [comment]
That is correct. One can change this by setting `flow=target_to_source`. I think this is very intuitive if you think about the graph connectivity as a set of (source, target) tuples. A lot of papers also define A_ji = 1 if there is an edge from i to j, which is IMO much more confusing. I tried my best to make this clear in the message passing documentation.

**Comment by nastaranmarzban** [comment]
Hi, hope you're doing well.
In the above example I wanna calculate conv = conv.message()
Now I have 3 questions:
The first one is how can I calculate x_j(the features of source nodes, I hope it's correct!!)?I mean I have to calculate it manually?if yes, how can I deal with when I have a huge graph with millions of nodes?
****************************************
The second one is what does conv.message give us?
****************************************
The third one is when I call GATConv or any other convolutional layer, are propagate and message calculated automatically?and how can I access them?
sorry, I'm new in these domains and a bit confused.

**Comment by rusty1s** [comment]
`x_j` will be automatically calculated in `self.propagate` based on the properties you request in `self.message`. For example, if you call it via `self.propagate(edge_index, x=x=)`, then in `message`, you can access both `x_j` and `x_i`. For large-scale graph learning, you will need to make use of some scalability technique provided in PyG, *e.g.*, `NeighborLoader` or `ClusterLoader`.

`message` will return an edge-level matrix that holds the message that is send along each edge to the destination node. All messages pointing to the same destination node will be aggregated according to `self.aggr`.

Yes, `GATConv`, etc will already implement `forward` and `message` functions that can be directly used.

**Comment by nastaranmarzban** [comment]
Hi, thaks for your reply, I got the things that I wanted, you're
explnations were really helpful🙏
In GATConv, source code, all the things that are written in def
reset_parameters are learnable?and what's defference between Linear and
Parameter? Can they use interchangeably?

**Comment by rusty1s** [comment]
1) Yes :)
2) In general, we try to use `Linear` if we simply want to transform node or edge features. We use `Parameter` to implement more complex logic, it is used to compute the trainable dot-product.
3) It temporarily stores the attention weights of the current forward pass. They are returned in case `return_attention_weights=True` is set.

**Comment by nastaranmarzban** [comment]
thanks a lot....your explanations were clear as always

**Comment by nastaranmarzban** [comment]
hi, hope you're doing well
I wanna know that Is there any website or paper in which they implemented GNNs for multivariate datasets?
I wanna classify multivariate datasets with GNNs  and not classify networks datasets as usual.
sorry for my irrelevant question to this topic.
thanks in advance

**Comment by rusty1s** [comment]
Sorry for late reply. Can you say more about this? What would be the difference in GNN design in case you are operating on a multivariate dataset.

**Comment by nastaranmarzban** [comment]
Hello, no problem, I know you are busy...let me explain more.
we have multivariate datasets with the size of p×n, in which p is the number of variables(say number of people) and n is the number of observations (for each person we measure n different things)
I look for datasets like in the attached file....
this example is just for clarification I can work on any datasets
[New Document.pdf](https://github.com/pyg-team/pytorch_geometric/files/7911911/New.Document.pdf)

**Comment by rusty1s** [comment]
Thanks for the clarification, but I'm probably not of good help here since I'm not aware of any such dataset, in particular, because I fail to see the connection to graph-based datasets. How would one model edges in this case?

**Comment by nastaranmarzban** [comment]
Hi, would it be ok if I explain more via your email address ? Is matthias.fey@tu-dortmund.de ok?

**Comment by rusty1s** [comment]
Sure.
