### ISSUE TITLE
Bug in PNAConv implementation

### ISSUE THREAD

**Issue by adrianjav** [pyg-team/pytorch_geometric#5514]
### 🐛 Describe the bug

When aggregating messages in PNAConv, scalers are applied one after the other and then stacked, but the variable used on the for loop is the **same one always**. That is, scalers are applied to the same variable one after the other, instead of applying each scaler independently to the same base variable.

This is the latest code in the repository:
https://github.com/pyg-team/pytorch_geometric/blob/8bcc77c6f36b44f7be0ca7dc11f4dc3faecd31ed/torch_geometric/nn/aggr/scaler.py#L68-L90
and the variable `out` is reused over the entire loop.

## Proposed solution

The solution is as simple as using a different variable name within the for loop and do, e.g., `out_i = out` at the start of the loop in line 77. Since it is such a simple change, I am happy to open a pull request if requested.

I might be wrong here, so please correct me if that's the case, but looking at the original paper and the official implementation, I think this is a bug:
https://github.com/lukecavabarrett/pna/blob/0c630c2e2d88bb1ef784c850dd8f3a069fcd9489/models/pytorch_geometric/pna.py#L158

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
Thanks for reporting. You are right. This is not expected behavior in `PNAConv`. Please feel free to send a PR for this :)
