### ISSUE TITLE
Slack channel link is not active

### ISSUE THREAD

**Issue by ChrisZonghaoLi** [pyg-team/pytorch_geometric#5557]
### 📚 Describe the documentation issue

The Slack link posted here on Github does not work: "To join this workspace, you’ll need to ask the person who originally invited you for a new link."

https://torchgeometricco.slack.com/join/shared_invite/zt-1ggstl6ea-4ItJJQXlZj8VJsM1pPfGIA#/shared-invite/error

### Suggest a potential alternative/fix

Update the Slack link or provide a workaround to this.

**Comment by rusty1s** [comment]
Can you try to access https://data.pyg.org/slack.html and see if it works? I just fixed this.

**Comment by ChrisZonghaoLi** [comment]
Hi Matthias,

Thanks yes I joined the channel!

Chris

From: Matthias Fey ***@***.***>
Date: Thursday, September 29, 2022 at 9:47 AM
To: pyg-team/pytorch_geometric ***@***.***>
Cc: Chris Li ***@***.***>, Author ***@***.***>
Subject: Re: [pyg-team/pytorch_geometric] Slack channel link is not active (Issue #5557)

Can you try to access https://data.pyg.org/slack.html and see if it works? I just fixed this.

**Comment by Pedramto89** [comment]
I attended the Graph Learning workshop held by Stanford University a few days ago but the slack channel is not working to join. Would you help me too?

**Comment by akihironitta** [comment]
Use this link for the time being :) https://join.slack.com/t/torchgeometricco/shared_invite/zt-2ppirgs10-_krkJVMgCeXiP92jDCRbig
