### ISSUE TITLE
A question about Dataloader

### ISSUE THREAD

**Issue by ZhaoYuTJPU** [pyg-team/pytorch_geometric#5590]

**Comment by LukeLIN-web** [comment]
In my experience, REDDIT with Neighbor sampler (dataloader) can be accelerated by increasing num_workers(14 numworkers is optimal). Maybe you could show your codes how you use them.

**Comment by ZhaoYuTJPU** [comment]
Yes, it is indeed my problem and I have solved it. Thank you for your answer
