### ISSUE TITLE
Additional option for `torch_geometric.utils.subgraph`

### ISSUE THREAD

**Issue by EdisonLeeeee** [pyg-team/pytorch_geometric#5595]
### 🚀 The feature, motivation and pitch

I've come across `dropout_node` again and I found an unexpected behavior for this function. For an example provided in the doc-string:
```python
        >>> edge_index = torch.tensor([[0, 1, 1, 2, 2, 3],
        ...                            [1, 0, 2, 1, 3, 2]])
        >>> edge_index, edge_mask, node_mask = dropout_node(edge_index)
        >>> edge_index
        tensor([[0, 1],
                [1, 0]])
        >>> edge_mask
        tensor([ True,  True, False, False, False, False])
        >>> node_mask
        tensor([ True,  True, False, False])
```
Actually, we need to remove **all** edges that contained the dropped nodes `[0, 1]`, but `subgraph` only drops edges that both ends are in the subset `[0,1]`:
https://github.com/pyg-team/pytorch_geometric/blob/081a964638459d1374f2e90de8ccfc9f0ea1f043/torch_geometric/utils/subgraph.py#L98

So in this case it should be `|` rather than `&` in the above code? Should we add an additional option to support this?

### Alternatives

Add an option for `subgraph` to support `|` rather than `&` in some cases.
https://github.com/pyg-team/pytorch_geometric/blob/081a964638459d1374f2e90de8ccfc9f0ea1f043/torch_geometric/utils/subgraph.py#L98

**Comment by rusty1s** [comment]
I am not totally sure I understand. If we use `|`, then we would include edges between two nodes where one has been dropped. In that case, your `edge_index` points to nodes that no longer exists in the your graph. Let me know if I am missing something.

**Comment by EdisonLeeeee** [comment]
> If we use |, then we would include edges between two nodes where one has been dropped. In that case, your edge_index points to nodes that no longer exists in the your graph.

Yeah, I think this should be the expected behavior of `dropout_node`. Otherwise, a dropped node would still have connections with others. That doesn't make sense.

Also seen from this discussion https://github.com/pyg-team/pytorch_geometric/discussions/5593, I think it is necessary to support this feature. WDYT?

**Comment by rusty1s** [comment]
Ok, but in this case we need to add the 1-hop neighborhood to the non-dropped node set, which is different from the original definition of `subgraph`. In that case, you may wanna use `k_hop_subgraph`.

**Comment by EdisonLeeeee** [comment]
>  in this case we need to add the 1-hop neighborhood to the non-dropped node set

Why should we do that? Did I miss something? I think we removed those edges associated with dropped nodes should be fine.

**Comment by rusty1s** [comment]
Sorry for the confusion. Don't we already do this?
```
edge_mask = node_mask[edge_index[0]] & node_mask[edge_index[1]] 
```
only maintains the edges for which both endpoints are in the non-dropped node set.

**Comment by EdisonLeeeee** [comment]
Oh you are right, my bad. Everything looks okay, sorry for the wasted time here.
