### ISSUE TITLE
Visualization of GNN Explanations

### ISSUE THREAD

**Issue by RexYing** [pyg-team/pytorch_geometric#5631]
### 🚀 The feature, motivation and pitch

Improve visualization utility functions of the explanation. It can be in the form of feature importance maps, or visualization of the explanation subgraph. Support parameters such as the size of explanation and show weighted importance for edges to control the visualization output.

Plan:
- [x] Explanation subgraph visualization for thresholded explanation. The output would be a visualization of the explanation subgraph after filtering out edges according to their importance / mask values (by a threshold). 
- [x] Explanation subgraph visualization for non-threshold explanation. Potentially plot the whole graph or the neighborhood graph, where edge width / color depends on the importance value of each edge.
- [x] Visualize feature importance. Draw a bar plot that corresponds to the importance of each feature dimension (and sort them).

**Comment by rjurney** [comment]
This would be great!

**Comment by davodogster** [comment]
Yes this would be great!

**Comment by sebastian-montero** [comment]
Hello all! I will be working on the third point for this PR. 

@RexYing I am looking at the `GNNExplainer` module in this [example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/gnn_explainer.py). If I understand this correctly, the `explain_node` method already provides a `node_feat_mask` for a specific node. What is not clear is if this mask the actual feature importance? If so, I can wrap this in a matplotlib bar plot. 

I am planning to add the options for feature names and top N feature to plot. Is there anything else we should add for this specific point?

Thank you!

**Comment by rusty1s** [comment]
This sounds good. I think we can support this option for both`MaskType.common_attributes` and `MaskType.attributes` (see #5967). For `MaskType.attributes`, we first need to reduce the feature mask from shape `(N,F)` to shape `(F,)`.

**Comment by snknitin** [comment]
Does this include visualization of Heterogenous Graphs? How would one go about using the explainer module right now for HeteroData and for edge based prediction tasks?

**Comment by rusty1s** [comment]
It does not include visualizations of heterogeneous graphs. For heterogeneous graphs, we can later just leverage `data.to_homogeneous()` for visualization purposes.

**Comment by wsad1** [comment]
For hetero graphs it might be useful to include the node and edge types in the visualization. So we  could consider building visualizations directly on heterogenous graphs.

**Comment by rusty1s** [comment]
Yes, these are available through `data.to_homogeneous()`.

**Comment by akash-vartak** [comment]
Closing issue since tasks are complete and relevant PRs (#6235 and #6094) are linked in comments above.
