### ISSUE TITLE
AttributeError: module 'torch_geometric.utils' has no attribute 'dropout_node'

### ISSUE THREAD

**Issue by malisit** [pyg-team/pytorch_geometric#5636]
### 🐛 Describe the bug

I'm trying to go over the example at https://github.com/pyg-team/pytorch_geometric/blob/master/examples/graph_unet.py but can't seem to import dropout_node. Here's a snippet showing what's going on;
```
Python 3.10.5 (main, Jun 11 2022, 16:53:29) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_geometric
>>> torch_geometric.utils.dropout_node
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch_geometric.utils' has no attribute 'dropout_node'. Did you mean: 'dropout_adj'?
>>> from torch_geometric.utils import dropout_node
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'dropout_node' from 'torch_geometric.utils' (/env/lib/python3.10/site-packages/torch_geometric/utils/__init__.py)
>>> import torch; print(torch.__version__)
1.11.0+cu102
>>> import torch_geometric; print(torch_geometric.__version__)
2.1.0
>>> import torch_scatter; print(torch_scatter.__version__)
2.0.9
>>> import torch_sparse; print(torch_sparse.__version__)
0.6.13
>>> import torch_cluster; print(torch_cluster.__version__)
1.6.0
```

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.11.0
* OS: Ubuntu
* Python version: 3.10.5
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):  torch_cluster==1.6.0, torch_sparse==0.6.13, torch_scatter==2.0.9

**Comment by LukeLIN-web** [comment]
https://github.com/pyg-team/pytorch_geometric/blob/d5e2e1eec7ff25435eef3a1904a9c19a3d4cfc82/examples/graph_unet.py#L8 
It is dropout_edge?

**Comment by EdisonLeeeee** [comment]
Both `dropout_edge` and `dropout_node` are new features to be introduced in the next version. You can simply install your PyG from master to use them. Alternatively, you might use `dropout_adj` instead of `dropout_edge` in the example:
```python
from torch_geometric.utils import dropout_adj as dropout_edge
```

**Comment by malisit** [comment]
> https://github.com/pyg-team/pytorch_geometric/blob/d5e2e1eec7ff25435eef3a1904a9c19a3d4cfc82/examples/graph_unet.py#L8
> 
> 
> It is dropout_edge?

My bad, I actually tried both dropout_edge and dropout_node.



> Both `dropout_edge` and `dropout_node` are new features to be introduced in the next version. You can simply install your PyG from master to use them. Alternatively, you might use `dropout_adj` instead of `dropout_edge` in the example:
> 
> ```python
> from torch_geometric.utils import dropout_adj as dropout_edge
> ```

Thank you, I just checked my utils/dropout.py and it doesn't have dropout_edge and dropout_node implemented.
