### ISSUE TITLE
using edge weights (e.g. node distances) in AddLaplacianEigenvectorPE

### ISSUE THREAD

**Issue by daniel-unyi-42** [pyg-team/pytorch_geometric#5646]
### 🚀 The feature, motivation and pitch

Hi!

 I would like to use edge weights in 'AddLaplacianEigenvectorPE' which requires the following simple modification in its 'call' function:
`edge_index, edge_weight = get_laplacian(
            data.edge_index,
            data.edge_attr,
            normalization='sym',
            num_nodes=num_nodes,
   )
`
This is useful when working with geometric graphs, for instance cortical surfaces as in the paper https://www.sciencedirect.com/science/article/abs/pii/S1361841518305243.

**Comment by rusty1s** [comment]
We are happy to make this modification. Are you interested in contributing this feature?

**Comment by daniel-unyi-42** [comment]
For sure.

**Comment by musicjae** [comment]
I'm also
