### ISSUE TITLE
Hope class Entities can get Edge Name for AIFB not just Edge ID

### ISSUE THREAD

**Issue by YijianLiu** [pyg-team/pytorch_geometric#5692]
### 🚀 The feature, motivation and pitch

On RGCN, class Entities to construct graph just get edge id not edge name, and these edges include inverse edges. But sometimes we need process these inverse edges separately. But we don't know which edge type is inverse.
Or have you taken it into consideration, edge index [0,1,2,3] which means [0,1, 0_inverse, 1_inverse ] ?

**Comment by rusty1s** [comment]
In `Entities`, it is currently `[0, 0_inverse, 1, 1_inverse]`, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/datasets/entities.py#L115-L116).
