### ISSUE TITLE
Expand_as RuntimeError in torch_scatter!!!

### ISSUE THREAD

**Issue by tjb-tech** [pyg-team/pytorch_geometric#5720]
### 🐛 Describe the bug

Hi, I am inheritanting Messagepassing in pytorch_geometric to create my own graph conv, but I face the error below. To be exact, it occurs in function `propagate`, and I sent `edge_index`(shape: 2, edge_num) and `x` (shape: num_node, 128) into `propagate`. And I try my code on both linux and win. And they occurred the same problems. Note that I use the famous dataset Cora use the code `dataset = Planetoid(path, 'Cora', transform=T.NormalizeFeatures())`

my code: 

```python
class GATConv(MessagePassing):
   
    def __init__(self, in_channels, out_channels, heads=1, concat=True,
                 negative_slope=0.2, reparam_mode=None, prior_mode=None,
                 struct_dropout_mode=None, sample_size=1,
                 val_use_mean=True,
                 bias=True,
                 **kwargs):
        super(GATConv, self).__init__(aggr='add', **kwargs)

    def forward(self, x, edge_index, size=None):
        """"""
        if size is None and torch.is_tensor(x) and not self.skip_editing_edge_index:
            edge_index, _ = remove_self_loops(edge_index)
            edge_index, _ = add_self_loops(edge_index,
                                           num_nodes=x.size(self.node_dim))

        if torch.is_tensor(x):
            x = torch.matmul(x, self.weight)
        else:
            x = (None if x[0] is None else torch.matmul(x[0], self.weight),
                 None if x[1] is None else torch.matmul(x[1], self.weight))

        out = self.propagate(edge_index, size=size, x=x)
```

imag of bug:

on linux:
![J4U6NM5}) )(0RA2LZBQG8K](https://user-images.githubusercontent.com/56426168/195988616-084d5abd-d4bc-4719-b0d6-9ced31b75728.png)
on win
![L9~ GBZ1WKSA{{0S1W M08Q](https://user-images.githubusercontent.com/56426168/195988620-77e96e4a-29be-4b77-872e-97130d4db50e.png)

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.9.1
* OS: Ubuntu x86_64
* Python version: 3.8.12
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): source
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter: 2.0.9; torch-sparse: 0.6.12

**Comment by rusty1s** [comment]
See https://github.com/pyg-team/pytorch_geometric/discussions/5719

**Comment by tjb-tech** [comment]
> See #5719

Thanks a lot!
