### ISSUE TITLE
BUG: cannot load DBLP_v1

### ISSUE THREAD

**Issue by YannDubs** [pyg-team/pytorch_geometric#581]
## 🐛 Bug

I cannot load ` DBLP_v1`, I get a (memory?) error during preprocessing. I have 32Gb of RAM, so I'm not sure the problem is my computer (although it could).

## To Reproduce

```python
from torch_geometric.datasets import TUDataset
dblp = TUDataset(root='data/DBLP_v1', name='DBLP_v1')
```

Error:

```
/usr/local/lib/python3.6/dist-packages/torch_geometric/read/tu.py in <listcomp>(.0)
     33         node_labels = node_labels - node_labels.min(dim=0)[0]
     34         node_labels = node_labels.unbind(dim=-1)
---> 35         node_labels = [F.one_hot(x, num_classes=-1) for x in node_labels]
     36         node_labels = torch.cat(node_labels, dim=-1).to(torch.float)
     37     x = cat([node_attributes, node_labels])

RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0
```

## Environment

* OS: Ubuntu
* Python version: 3.7
* PyTorch version: 1.1.0
* Any other relevant information: 32Gb RAM

**Comment by rusty1s** [comment]
I see, the `node_labels` gets converted to a one-hot encoding, but the `DBLP_v1` dataset contains 41325 different node labels. This can run out of memory quite quickly. The only way to prevent this is to use sparse one-hot encoded node features, but we need to modify our `DataLoader` to work with those properly.
