### ISSUE TITLE
Adding a virtual node expands mini-batched Data's `batch` attribute incorrectly

### ISSUE THREAD

**Issue by amtseng** [pyg-team/pytorch_geometric#5818]
### Overview of the bug

Using `torch_geometric.loader.DataLoader`, resulting Data objects are mini-batched and include a `batch` attribute which denotes the source graph for each node (i.e. `batch` is a vector of length equal to the number of nodes in the graph).

When adding a virtual node using `torch_geometric.transforms.VirtualNode`, a new node is added which has an edge to every other node in the batch. This means that attributes such as `data.x`, `data.edge_index`, and `data.batch` need to be expanded to accommodate the new node.

Unfortunately, `data.batch` is expanded incorrectly. In particular, `data.batch` is usually not altered at all (when in reality it should be extended by 1 extra entry). Even more sinister, if the number of nodes and the number of edges is the same in the batch, then `data.batch` is extended by twice the number of nodes/edges, which is arguably worse.

### Minimal reproducing example

```python
print("torch " + torch.__version__)
print("torch_geometric " + torch_geometric.__version__)
print()

print("Number of nodes != number of edges:")
x = torch.randn(10, 1)
edge_index = torch.randint(10, size=(2, 9))
batch = torch.zeros(10)
data = torch_geometric.data.Data(x=x, edge_index=edge_index, batch=batch)
print("Before VN: %s" % data)
torch_geometric.transforms.VirtualNode()(data)
print("After VN: %s" % data)
print()

print("Number of nodes == number of edges:")
x = torch.randn(10, 1)
edge_index = torch.randint(10, size=(2, 10))
batch = torch.zeros(10)
data = torch_geometric.data.Data(x=x, edge_index=edge_index, batch=batch)
print("Before VN: %s" % data)
torch_geometric.transforms.VirtualNode()(data)
print("After VN: %s" % data)
```

Output:
```
torch 1.11.0
torch_geometric 2.1.0

Number of nodes != number of edges:
Before VN: Data(x=[10, 1], edge_index=[2, 9], batch=[10])
After VN: Data(x=[11, 1], edge_index=[2, 29], batch=[10], edge_type=[29])

Number of nodes == number of edges:
Before VN: Data(x=[10, 1], edge_index=[2, 10], batch=[10])
After VN: Data(x=[11, 1], edge_index=[2, 30], batch=[30], edge_type=[30])
```

### Explanation for why the bug occurs

[When a virtual node is added](https://github.com/pyg-team/pytorch_geometric/blob/c8e1cdb4665d408dd2d5de3fbe0fb2fdb0bfbd1d/torch_geometric/transforms/virtual_node.py#L38), it loops through each of the Data-object attributes, classifies it as a node attribute or an edge attribute, and extends the attribute's tensor in turn. Node attributes are supposed to be extended by 1. Edge attributes are supposed to be extended by 2n, where n is the number of nodes. Special treatment is given to `data.edge_index`, `data.edge_type`, and `data.edge_weight`.

This loop, however, will directly modify `data` _after each iteration_. At least in my environment, `x` is encountered first in the loop. After this `x` iteration of the loop, the number of nodes has increased by 1. Upon the next iteration when we encounter `batch`, as a result of [how `is_node_attr` and `is_edge_attr` are defined](https://github.com/pyg-team/pytorch_geometric/blob/344b143ce5df74ef6ef277f18f1c2d8f8299c41b/torch_geometric/data/storage.py#L475), `batch` will be incorrectly classified. Usually, this means that `batch` will not be classified as a node or edge attribute (the number of nodes has recently increased so its size no longer batches the number of nodes). In the case that the number of nodes and edges start out being equal, `batch` will be misclassified as an edge attribute (the [check for `num_nodes != num_edges`](https://github.com/pyg-team/pytorch_geometric/blob/344b143ce5df74ef6ef277f18f1c2d8f8299c41b/torch_geometric/data/storage.py#L497) no longer works because the number of nodes has changed).

As a result, `batch` is usually not altered at all, or if the number of nodes and edges were the same to begin with, it is accidentally treated as an edge attribute.

### Proposed fix

The most obvious fix is to perform all compute the updates to the Data-object attributes in the loop, and then update them all once the loop has completed. This would ostensibly fix the issue above.

However, I also suggest that when `data.batch` is extended, it should be extended by an entry that is not also an index for another graph in the batch (including 0). For example, the new entry could be 1 greater than the largest batch index. In order to do this, I believe `batch` should also receive special treatment, along with `edge_weight` and the like.

I will hold off on writing the change and submitting a pull request for now, in view of the suggested design change (i.e. extending `data.batch` by something other than 0).

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.11.0
* OS: Linux
* Python version: 3.8.13
* How you installed PyTorch and PyG (`conda`, `pip`, source): `conda`

**Comment by rusty1s** [comment]
Thanks for this detailed issue. This is well-written. You are absolutely correct that the current implementation is buggy due to running `is_node_attr` and `is_edge_attr` on in-place modified data. I fixed it in https://github.com/pyg-team/pytorch_geometric/pull/5819 (hope that was okay)! Thanks a lot!

**Comment by amtseng** [comment]
Awesome, thank you! :)
