### ISSUE TITLE
DataLoader: Dynamic Batch-size based on num_nodes/num_edges

### ISSUE THREAD

**Issue by yg-li** [pyg-team/pytorch_geometric#583]
## ❓ Questions & Help

I was using the RGCNConv layer with num_relations=4, in_channels=out_channels=512. In the forward step, I pass in a graph with 300 nodes and 22768 edges which caused it to raise an CUDA OOM saying it needs 22.23GB memory while I only have 11.17GB.

The line causing the error is
`w = torch.index_select(w, 0, edge_type)`
in the message function of RGCNConv class, which makes sense as it was trying to create a float tensor of size [22768 x 512 x 512].

But it seems copying the weights num_edges times is inefficient and not necessary. Is there another way to implement RGCN without copying the weights this many times?

**Comment by rusty1s** [comment]
I sadly do not know of another way to implement this layer. For each edge, we need to select the appropriate weight matrix and multiply it with the respective feature vector. This is the reason why the authors of the paper train larger graphs on the CPU. Might this be an option to you? If you know of another way to implement this, feel free to reach out :)

**Comment by yg-li** [comment]
> I sadly do not know of another way to implement this layer. For each edge, we need to select the appropriate weight matrix and multiply it with the respective feature vector. This is the reason why the authors of the paper train larger graphs on the CPU. Might this be an option to you? If you know of another way to implement this, feel free to reach out :)

Thank you for your reply @rusty1s . I do not know the way to solve this problem either.

Btw I also have a problem with batching. Since graphs have different shapes/sizes, each batch of 32 graphs are consuming different GPU memory. Hence, some of the batches are capable to be processed but the others cause OOM problem. 

Is there a general way to solve (or mitigate) this problem? I cannot find anything about in the documentation.

**Comment by rusty1s** [comment]
This is a good request and we currently do nor support this. We could add an argument `max_num_nodes` or `max_num_edges` in addition to `batch_size` to the `DataLoader`. However, this requires us to implement our own data loading routine without relying on PyTorch to do this task for us so it can be a bit tricky to get right, especially in combination with `num_workers`.

**Comment by Zacharias030** [comment]
I was about to open the same issue about dynamic batch size.

Could we as a hack create a `collate_fn` which discards the latter part of the batch under the `max_num_nodes` condition (greedily adding samples from the original batch in order and maybe discarding the tail of the batch)?
You probably thought of that before, therefore I'd welcome a hint as to why this is not possible or a pointer for where to start implementing a feature like that!

If that could solve the problem in practice, I could tolerate the side effects which would include:
It would skew the meaning of what an 'epoch' is since we can't guarantee that a sample has been processed and it would possibly skew the dataset distribution since large graphs are discarded with a higher probability.

Thanks so much for the amazing work on pytorch geometric!
Best, Zacharias

**Comment by Zacharias030** [comment]
It looks like we have to replace the [`BatchSampler`](https://pytorch.org/docs/stable/_modules/torch/utils/data/sampler.html#BatchSampler) which aggregates samples until `batch_size` is reached by something that inspects the samples added a little.

here is the aggregation of the `BatchSampler`:
```
def __iter__(self):
        batch = []
        for idx in self.sampler:
            batch.append(idx)
            if len(batch) == self.batch_size:
                yield batch
                batch = []
        if len(batch) > 0 and not self.drop_last:
            yield batch
```

It would be more tricky to implement the `__len__` of such a sampler though.

**Comment by Zacharias030** [comment]
Here's a first hack of the above with all the caveats included:

```python
import torch.utils.data
from torch.utils.data.dataloader import default_collate

from torch_geometric.data import Data, Batch
from torch._six import container_abcs, string_classes, int_classes


class NodeLimitedDataLoader(torch.utils.data.DataLoader):
    r"""Data loader which merges data objects from a
    :class:`torch_geometric.data.dataset` to a mini-batch.

    Args:
        dataset (Dataset): The dataset from which to load the data.
        batch_size (int, optional): How many samples per batch to load.
            (default: :obj:`1`)
        shuffle (bool, optional): If set to :obj:`True`, the data will be
            reshuffled at every epoch. (default: :obj:`False`)
        follow_batch (list or tuple, optional): Creates assignment batch
            vectors for each key in the list. (default: :obj:`[]`)
    """
    def __init__(self, dataset, batch_size=1, shuffle=False, follow_batch=[],
                 max_num_nodes=None, **kwargs):
        self.max_num_nodes = max_num_nodes

        def collate(batch):
            elem = batch[0]
            if isinstance(elem, Data):
                # greedily add all samples that fit within self.max_num_nodes
                # and silently discard all others
                if max_num_nodes is not None:
                    num_nodes = 0
                    limited_batch = []
                    for elem in batch:
                        if num_nodes + elem.num_nodes <= self.max_num_nodes:
                            limited_batch.append(elem)
                            num_nodes += elem.num_nodes
                    return Batch.from_data_list(limited_batch, follow_batch)
                else:
                    return Batch.from_data_list(batch, follow_batch)
            elif isinstance(elem, float):
                return torch.tensor(batch, dtype=torch.float)
            elif isinstance(elem, int_classes):
                return torch.tensor(batch)
            elif isinstance(elem, string_classes):
                return batch
            elif isinstance(elem, container_abcs.Mapping):
                return {key: collate([d[key] for d in batch]) for key in elem}
            elif isinstance(elem, tuple) and hasattr(elem, '_fields'):
                return type(elem)(*(collate(s) for s in zip(*batch)))
            elif isinstance(elem, container_abcs.Sequence):
                return [collate(s) for s in zip(*batch)]

            raise TypeError('DataLoader found invalid type: {}'.format(
                type(elem)))

        super(NodeLimitedDataLoader,
              self).__init__(dataset, batch_size, shuffle,
                             collate_fn=lambda batch: collate(batch), **kwargs)
```

**Comment by rusty1s** [comment]
This is cool. Happy to take a contribution on this one. The `__len__` is indeed an issue. Another option would be to just pass in a number of steps to the `Sampler`.

**Comment by GericoVi** [comment]
Yes that is an option. There's a few ways to get around the `__len__` issue and also a few ways to fill the batches depending on the specific use case. So because of that and since no PyG classes need to be changed, maybe if this were to be a contribution it would just be as an illustration in `examples/`?

I'd be happy to start a PR on this, but unsure what to include (which dataset for example).

**Comment by GericoVi** [comment]
I've started a PR with what you've proposed. It's mostly the same as the code I proposed above but I've removed the `lookahead` - I don't think this is really that necessary, and simplifies the code.

Let me know what you think.

**Comment by rusty1s** [comment]
Thank you!
