### ISSUE TITLE
TUDataset proteins

### ISSUE THREAD

**Issue by cxw-droid** [pyg-team/pytorch_geometric#5845]
### 🐛 Describe the bug

When I load proteins dataset using TUDataset(), I found the data.x.shape[1] is 0. i.e., the feature dimension is 0. Possibly it should be 3? Did you changed TUDataset() recently? I remember the proteins dataset worked normally before.

I am using torch-geometric 2.1.0

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.10
* OS: Ubuntu 20.04
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
Did you mean the `PROTEINS` dataset? I'm looking into this and the feature dimension is still 3 instead of 0.
```python
from torch_geometric.datasets import TUDataset
dataset = TUDataset(".", 'PROTEINS')
dataset[0].x.size(1)
>>> 1
```

**Comment by rusty1s** [comment]
There is some issue with `TUDataset` on 2.1.0 which is already fixed in master. Can you check if the same issue still exists when updating?

**Comment by cxw-droid** [comment]
I reinstalled `torch-geometric` with `pip` and tried again. You can see x.size[1] is 0

>from torch_geometric.datasets import TUDataset
dataset = TUDataset(".", 'PROTEINS')
Downloading https://www.chrsmrrs.com/graphkerneldatasets/PROTEINS.zip
Extracting ./PROTEINS/PROTEINS.zip
Processing...
Done!
dataset[0].x
tensor([], size=(42, 0))

**Comment by rusty1s** [comment]
Can you install as described [here](https://github.com/pyg-team/pytorch_geometric#nightly-and-master).

**Comment by cxw-droid** [comment]
After installing `pyg-nightly`, the PROTEINS `dataset.x` has feature dimension 3 now. In the previous version (2.1.0) I found only PROTEINS dataset has the zero feature dimension problem and other dataset such as MUTAG works well. I also noticed the raw data of PROTEINS has a file `PROTEINS_node_attributes.txt` while MUTAG etc. has no corresponding node attribute file. FYI.

**Comment by rusty1s** [comment]
Thanks for confirming. I assume this is safe to close since this is already fixed in master. Will create a new version for PyG soon, which will include this fix.
