### ISSUE TITLE
Inconsistency between input Types in method vs in doc

### ISSUE THREAD

**Issue by alzaia** [pyg-team/pytorch_geometric#5853]
### 📚 Describe the documentation issue

In the GNNExplainer model, there are some inconsistencies in the methods code vs docs. For example, in the input method we have (Tensor Type):
https://github.com/pyg-team/pytorch_geometric/blob/62e2e52373c114c58a2fce5c06814fd0cecea433/torch_geometric/nn/models/gnn_explainer.py#L213
while the doc indicates an int Type:
https://github.com/pyg-team/pytorch_geometric/blob/62e2e52373c114c58a2fce5c06814fd0cecea433/torch_geometric/nn/models/gnn_explainer.py#L223

### Suggest a potential alternative/fix

Recheck the doc to make sure that the argument Types are consistent with the documentation.

**Comment by rusty1s** [comment]
You are absolutely correct. I just fixed it. Thanks!
