### ISSUE TITLE
AssertionError in GNNExplainer 

### ISSUE THREAD

**Issue by alzaia** [pyg-team/pytorch_geometric#5855]
### 🐛 Describe the bug

I am trying to run the GNNExplainer on top of my user-defined GAT model. It throws the following error:

```
File ~/.conda/envs/pfp_venv/lib/python3.8/site-packages/torch_geometric/nn/models/gnn_explainer.py:231, in GNNExplainer.explain_node(self, node_idx, x, edge_index, **kwargs)
    229 optimizer.zero_grad()
    230 h = x * self.node_feat_mask.sigmoid()
--> 231 out = self.model(x=h, edge_index=edge_index, **kwargs)
    232 loss = self.get_loss(out, prediction, mapping)
    233 loss.backward()

File ~/.conda/envs/pfp_venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1110, in Module._call_impl(self, *input, **kwargs)
   1106 # If we don't have any hooks, we want to skip the rest of the logic in
   1107 # this function, and just call forward.
   1108 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110     return forward_call(*input, **kwargs)
   1111 # Do not call functions when jit is used
   1112 full_backward_hooks, non_full_backward_hooks = [], []
...
--> 495 assert inputs.size(self.node_dim) == edge_mask.size(0)
    497 size = [1] * inputs.dim()
    498 size[self.node_dim] = -1

AssertionError:
```
The code I run is the following:

```
node_idx = 100
explainer = GNNExplainer(model, epochs=200, return_type='regression')
node_feat_mask, edge_mask = explainer.explain_node(node_idx=node_idx, x=data.x, edge_index=data.edge_index, batch=data)
```
Where `model` is a multi-layer GAT model that has `n` node features and `m` edge features and that performs a node regression task. Let me know if you need more details.

### Environment

* PyG version: 2.1.0.post1
* PyTorch version: 1.11.0
* OS: MacOS
* Python version: 3.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip install -U torch_geometric

**Comment by rusty1s** [comment]
Can you share your `GAT` model with us (or at least a minimal version that can reproduce this)? We tested `GNNExplainer` with a basic `GAT` model on our end and it runs just fine.

**Comment by alzaia** [comment]
Hello, the error came from a mistake from my side (forgetting to pass a required arg. of my `model` into the `explain_node` method, i.e. the `edge_attr` input). Works perfectly now! Thanks a lot @rusty1s ! I'm closing this as it's now resolved.
