### ISSUE TITLE
Typo in the documentation of k_hop_subgraph

### ISSUE THREAD

**Issue by daniel-unyi-42** [pyg-team/pytorch_geometric#5857]
### 📚 Describe the documentation issue

Just a small typo in the documentation: [this line](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/subgraph.py#L244) should be
`        >>> # Center node 6, 2-hops`

**Comment by EdisonLeeeee** [comment]
Thanks for reporting, will fix it in #5858.
