### ISSUE TITLE
Installing with Conda in Docker Causes Torch to Fallback to CPU

### ISSUE THREAD

**Issue by ChadGueli** [pyg-team/pytorch_geometric#5875]
### 😵 Describe the installation problem

Installing PyG in the following Dockerfile causes Mamba to force PyTorch to use the cpu implementation.
```
FROM mambaorg/micromamba:0.27-focal-cuda-11.6.2

COPY --chown=$MAMBA_USER:$MAMBA_USER requirements.yml requirements.yml
RUN micromamba install -f requirements.yml --yes && \
    micromamba clean --all --yes
```

Where requirements.yml is
```
name: base
channels:
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - pytorch_geometric
```

This issue persists if I install PyG later by removing PyG from requirements.yml and changing the Dockerfile to include
```
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN micromamba install pytorch_geometric -c conda-forge --yes && \
    micromamba clean --all --yes
```

However, if I run the container interactively, I am able to install PyG without a problem, but it changes the PyTorch package file. Unfortunately, if I specify this package file for PyTorch or the CUDA package files for the whole PyG stack when building the image it throws an error about __cuda not being installed.

### Environment

* PyG version: 2.0.9
* PyTorch version: 1.12.1
* OS: Ubuntu 20.04
* Python version: 3.10
* CUDA/cuDNN version: Should be 11.6.
* How you installed PyTorch and PyG (`conda`, `pip`, source): micromamba (so conda)

**Comment by rusty1s** [comment]
I think you also need to add the `nvidia` channel for this to work.

**Comment by ChadGueli** [comment]
Thank you for the help rusty1s! Unfortunately, this doesn't seem to fix the issue either. I tried with both Dockerfile setups, and including PyG during the build still causes the issue.

**Comment by rusty1s** [comment]
Can also try to rename `pytorch_geometric` to `pyg`?

**Comment by ChadGueli** [comment]
Changing from `pytorch_geometric` to `pyg` worked perfectly. Thank you!
