### ISSUE TITLE
PyTorch 1.13 wheels

### ISSUE THREAD

**Issue by himil48** [pyg-team/pytorch_geometric#5880]
### 😵 Describe the installation problem

Hi, 

I receive an error "Segmentation fault: 11" when trying running the following code: import torch_geometric

These are the versions of the installed packages
<img width="241" alt="Screenshot 2022-11-02 at 16 11 32" src="https://user-images.githubusercontent.com/102516553/199511615-d1e7138c-ca05-4c0d-80dd-08c7e052cbb9.png">

May you please provide some assistance regarding this issue. 

Thank you

### Environment

* PyG version:
* PyTorch version: 1.13
* OS: MacOS
* Python version: 3.9
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
We currently only support PyTorch 1.12 in conda. PyTorch 1.13 just got released a few days ago, so we need to update accordingly. Should be done by next week :)

**Comment by himil48** [comment]
Thanks for your reply!

I used pip when installing the packages. Will there be a similar update for the pip installation?

**Comment by rusty1s** [comment]
Yes, all done soon. Will ping you here.

**Comment by himil48** [comment]
Thank you, much appreciated!!

**Comment by lorenz0890** [comment]
> We currently only support PyTorch 1.12 in conda. PyTorch 1.13 just got released a few days ago, so we need to update accordingly. Should be done by next week :)

Hi,

will this environment work with the next update?

PyTorch version: 1.13
OS: Ubuntu 20.04
Python version: 3.10.4
CUDA: 11.7

Thanks!
Lorenz

**Comment by rusty1s** [comment]
Yes, will ping you here once it is ready.

**Comment by rusty1s** [comment]
Just landed.
