### ISSUE TITLE
No node attributes 'x' for PROTEINS dataset

### ISSUE THREAD

**Issue by StevanStanovic** [pyg-team/pytorch_geometric#5891]
### 🐛 Describe the bug

Hello,

I downloaded and loaded the PROTEINS dataset with TUDataset class. The problem is that the node attributes 'x' are empty. Normally, each node represent a one hot encoder representing in which category the node is classified.
The problem occurs for PyG 2.1.0 and, for now, just for PROTEINS.
Thank you in advance for you answer.

Stevan

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.11.0
* OS: linux ubuntu 20.04
* Python version: 3.9.7
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda environment and pip install
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-cluster      1.6.0
torch-scatter      2.0.9
torch-sparse       0.6.15
torch-spline-conv  1.2.1

**Comment by EdisonLeeeee** [comment]
Already fixed in master, see https://github.com/pyg-team/pytorch_geometric/issues/5845
