### ISSUE TITLE
ONNX exported model output different values.

### ISSUE THREAD

**Issue by huhk-sysu** [pyg-team/pytorch_geometric#5921]
### 🐛 Describe the bug

I export a model with ONNX, but its output is different from the one from pytorch model.

Here's a simple code, modify from [test/nn/models/test_basic_gnn.py](https://github.com/pyg-team/pytorch_geometric/blob/master/test/nn/models/test_basic_gnn.py#L170-L203)

```python
import torch
import onnx
import onnxruntime as ort
from torch_geometric.nn import SAGEConv
import os

class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = SAGEConv(8, 16)
        self.conv2 = SAGEConv(16, 16)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x

model = MyModel()
x = torch.randn(3, 8)
edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])

torch_output = model(x, edge_index).detach().numpy()

torch.onnx.export(model, (x, edge_index), 'model.onnx',
                    input_names=('x', 'edge_index'))

model = onnx.load('model.onnx')
onnx.checker.check_model(model)

ort_session = ort.InferenceSession('model.onnx')

onnx_output = ort_session.run(None, {
    'x': x.numpy(),
    'edge_index': edge_index.numpy()
})[0]
assert onnx_output.shape == (3, 16)

# it should be closed to 0
print("edge_index=", edge_index)
print("difference=", (onnx_output-torch_output).sum())

os.remove('model.onnx')
```
And here's the output.
```
edge_index= tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])
difference= -1.766824
```
There may be something wrong related with `edge_index`, I have some trials and different `edge_index` come with different result.
For example, with `edge_index = torch.tensor([[0, 1, 1], [1, 0, 2]])` (remove the last edge), the output is closed to 0, which is  expected.
```
edge_index= tensor([[0, 1, 1],
        [1, 0, 2]])
difference= -4.3958426e-07
```
However, with `edge_index = torch.tensor([[0, 1, 2], [1, 0, 0]])`, the difference is much larger.
 ```
edge_index= tensor([[0, 1, 2],
        [1, 0, 0]])
difference= -0.42195135
```

### Environment

* PyG version: 2.1.0.post1
* PyTorch version: 1.12.1
* OS: Windows
* Python version: 3.10.0
* CUDA/cuDNN version: None(cpu)
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-cluster==1.6.0
torch-scatter==2.0.9
torch-sparse==0.6.15
torch-spline-conv ==1.2.1

**Comment by huhk-sysu** [comment]
> Sorry for late reply, this seems to be related to #5742 (please re-open if this is not the case). We track progress in this PyTorch issue: [pytorch/pytorch#87398](https://github.com/pytorch/pytorch/issues/87398)

Hi, I find that I forgot to set the `opset_version`. Setting `opset_version=16` can solve the issue. And when `opset_version` < 16, the values are different again

**Comment by rusty1s** [comment]
This seems to be indeed doing the trick. Added a basic test to confirm, see https://github.com/pyg-team/pytorch_geometric/blob/master/test/nn/models/test_basic_gnn.py#L191. Thank you!

**Comment by huhk-sysu** [comment]
You're welcome. I'm meeting another problem when exporting with dynamic_axes. I opened the issue there(https://github.com/pytorch/pytorch/issues/89190) because the error message told me to do so. Would you please have a look?

**Comment by lyimage** [comment]
same demo code, and same Environment, Setting opset_version=16, still Setting opset_version=16.
