### ISSUE TITLE
Clarify additional dependencies in CONTRIBUTING.md

### ISSUE THREAD

**Issue by avgupta456** [pyg-team/pytorch_geometric#5950]
### 📚 Describe the documentation issue

Following `CONTRIBUTING.md` to set up pytorch_geometric locally, I created an empty virtual environment and ran `pip install -e ".[dev,full]"`. After this, running `pytest` threw errors regarding `torch-scatter` and the other three sub-packages. 

I was able to resolve this issue by specifically installing PyTorch 1.12.0 and following the instructions from each of the sub-package repositories to install the correct version for my OS/CUDA combination. However, this wasn't made clear in the docs, and I'm not sure if this was an expected step.

### Suggest a potential alternative/fix

Include additional steps in `CONTRIBUTING.md` to install the correct versions of `torch`, `torch-scatter`, `torch-sparse`, `torch-cluster`, and `torch-spline-conv`.

**Comment by rusty1s** [comment]
This is a good callout. Added this information to `CONTRIBUTING.md`. Thanks!
