### ISSUE TITLE
aggr in many conv layers fixed

### ISSUE THREAD

**Issue by flgw** [pyg-team/pytorch_geometric#597]
## ❓ Questions & Help
Most of the pre-defined conv layers fix the aggregator function, e.g. GCNConv. Is that intended due to you assuming other values for aggr don't work / make sense?

**Comment by rusty1s** [comment]
Most operators which fix the aggregator function are defined this way, *e.g.*, for `GCNConv` or `GATConv` another aggregator function does not really make sense. If you feel an operator should also support any other aggregator function, feel free to let me know. We can fix this easily.

**Comment by flgw** [comment]
OK. I have no specific operator in mind. It's then more a matter of software design or such. The base class allows you to pass "aggr" while _some_ of it's derived classes cause an error when passing "aggr". But rather that way than ignoring it silently.
I don't have an elegant solution to that from the top of my head, but a more specific error message would be nice to have.

**Comment by rusty1s** [comment]
I see. I think we can add a more meaningful error message in this case.
