### ISSUE TITLE
Is there any plan to support Windows OS？

### ISSUE THREAD

**Issue by 1066118757** [pyg-team/pytorch_geometric#599]

**Comment by 1066118757** [comment]
Thanks to the software author, a lot of algorithms for graph neural networks have been implemented, which is very helpful for our research . I would like to consult, does this tool support the Windows OS, or is there any plan to support the Windows OS in the future?

**Comment by rusty1s** [comment]
Windows should work just fine, but it may need some trial-and-error to install the extension packages.

**Comment by WMF1997** [comment]
hello @1066118757 :
I have installed Windows Version. Now I tell you some of my installation experience. 

### 1 use Microsoft Visual Studio 2019 (perhaps 2017 is the same way...)
I installed Visual Studio 2019(Visual C++ should be installed) and its Python extensions (Python 3.7.3 64bit), and use its pip to install pytorch_geometric.
```pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric``` (perhaps add a --user)

I installed VS 2019 (in this method) on Windows 10 (17763), Windows 7. Works (CPU, for i don't have a computer with both NVIDIA GPU and VS 2017+). 

### 2 use Microsoft Visual Studio 2015
I have another laptop, with a NVIDIA Geforce GTX 1060 6GiB GPU . I want to use the GPU. However, I installed Python 3.6.4 (Anaconda) and VS 2015. I cannot uninstall them. I changed the compiler config in anaconda, and it finally works. (CPU and GPU both works well)

### ?? A Summary of install PyG on Microsoft Windows 

I guess, a compiler with C++11 support is necessary(g++, clang++, msvc, ...). (Sorry, I really do not read the source of torch-scatter, which supports the calculation of PyG)

P.S. 
just type ```pip install torch-scatter``` and try. (all platforms)
if it works, then everything is fine. installing other packages still works. 
if it not work, ... I hope my experience of installing PyG on Windows may help you a bit... 

yours, 
@wmf1997

**Comment by WMF1997** [comment]
hello @1066118757  @rusty1s :
I think my experience of installing PyG on Windows 7 (only tested CPU) and Windows 10 (CPU and CUDA) may help others who want to install PyG on Windows? 

P.S. Perhaps one day, installing PyG on Windows can be as easy as that on *NIX(Linux and macOS). 
(P.P.S. @rusty1s : Macao is really a nice place, with a lot of places of interest to visit~)

yours sincerely, 
@WMF1997

**Comment by rusty1s** [comment]
There were a lot of improvements to ease Windows installation. Closing this issue now.
