### ISSUE TITLE
PyG graph To Smiles Function

### ISSUE THREAD

**Issue by hichiaty** [pyg-team/pytorch_geometric#6009]
### 🚀 The feature, motivation and pitch

This feature request is for a function converts a PyG graph to a SMILES string.

There already exists a function that converts a SMILES string to a PyG graph (`from_smiles`), but not the other way around.

I appreciate that for some graphs, returning to a SMILES string is not possible or will not be consistent due to the loss of information and/or various atom/bond encodings used during the conversion to a graph for each dataset. However, for some graphs, it is possible to return to a SMILES string. This feature request is for a function that can do this by using the same atom/bond encodings used in the `from_smiles` function. I would be happy to work on and submit a PR for this function.

### Alternatives

Not sure if there are any other ways currentl to go from a PyG graph to SMILES.

**Comment by rusty1s** [comment]
I am happy to take in such a PR :)

**Comment by hichiaty** [comment]
This has been merged here: #6038
