### ISSUE TITLE
Questions and help on node to node modeling

### ISSUE THREAD

**Issue by Optimox** [pyg-team/pytorch_geometric#601]
## ❓ Questions & Help on node to node modeling

Hi, first thanks for this awesome package, it's a great piece of work.
I've been working on the Molecular Properties challenge on Kaggle lately (https://www.kaggle.com/c/champs-scalar-coupling) and I am struggling a bit. I would really appreciate some help (both in terms of existing codes, papers or your own vision on the problem).

## Problem setting

In this competition, we have molecule similar to the molecules in QM9 datasets, the goal is to predict the coupling constant between some atom pairs given atom types and positions. There are 8 differents pair types ('1JHC', '2JHH', '1JHN', '2JHN', '2JHC', '3JHH', '3JHC', '3JHN') and it seems that making different models for each type improve performances.

Here are some specificity I see here and didn't managed to overcome yet : 
- the edges are not given, so there are different ways of creating the edges. I'll be more specific when explaining my approaches so far.
- for a same graph you have multiple targets that don't follow a clear pattern (not one output per node, not one output per edge etc...) 

### "Real" bond graphs

My first approach consists in creating both node_features, edges and edges_attr by using openbabel and following existing bonds.
Since there is no "real" bond for 3JHC coupling type for example, this method does not allow  to create predictions from edges so  my approach is that one prediction can be done from one graph and two nodes indices where I just stack nodes_1 and nodes_2 representation to then pass then to a MLP (with other external features).

```
 class RealBondNet(torch.nn.Module):
    def __init__(self, num_node_features, num_edge_features, num_mol_features,
                 dropout=0.0, output_dim=1, num_conv = 5, conv_size=64, num_steps=3):
        super(RealBondNet, self).__init__()
        self.num_conv = num_conv
        self.num_steps = num_steps
        self.num_mol_features = num_mol_features
        self.conv_size = conv_size
        self.output_dim = output_dim
        self.dropout = dropout
        self.graph_conv1 = GraphConv(num_node_features, self.conv_size) 
        self.graph_conv2 = GraphConv(self.conv_size, self.conv_size)
        self.pool_S2S = Set2Set(self.conv_size, processing_steps=self.num_steps)
        
        
        self.edge_lin0 = torch.nn.Linear(num_node_features, conv_size)

        nn = torch.nn.Sequential(Linear(num_edge_features, 128), ReLU(), Linear(128, conv_size * conv_size))
        self.NNconv = NNConv(conv_size, conv_size, nn, aggr='mean', root_weight=False)
        self.gru = torch.nn.GRU(conv_size, conv_size)
        self.edge_set2set = Set2Set(conv_size, processing_steps=self.num_steps)
        
        self.fc1 = Linear(self.conv_size*8, self.conv_size*4)
        self.bn1 = BatchNorm1d(self.conv_size*4)
        self.fc2 = Linear(self.conv_size*4, int(self.conv_size))
        self.bn2 = BatchNorm1d(int(self.conv_size))
        
        # mol features
        self.fcmol1 = Linear(self.num_mol_features, self.num_mol_features)
        self.bnmol1 = BatchNorm1d(self.num_mol_features)
        self.fcmol2 = Linear(self.num_mol_features, self.num_mol_features)
        self.bnmol2 = BatchNorm1d(self.num_mol_features)
        self.fcmol3 = Linear(int(self.num_mol_features), int(self.num_mol_features /2))
        self.bnmol3 = BatchNorm1d(int(self.num_mol_features /2))
        
        self.before_final_fc = Linear(int(self.num_mol_features /2)+self.conv_size, self.conv_size)
        self.bnbf = BatchNorm1d(self.conv_size)
        self.final_fc = Linear(self.conv_size, 1)
        
    def forward(self, data):
        x, edge_index, edge_attr, batch, atom_index_0, atom_index_1 = data.x, data.edge_index, data.edge_attr, data.batch, data.atom_index_0, data.atom_index_1
        
        # edges transformations
        out = F.relu(self.edge_lin0(data.x))
        h = out.unsqueeze(0)

        for i in range(3):
            m = F.relu(self.NNconv(out, edge_index, edge_attr))
            out, h = self.gru(m.unsqueeze(0), h)
            out = out.squeeze(0)

        edge_pool = self.edge_set2set(out, batch)

        # mol information
        mol_out = self.fcmol1(data.mol_attr.view(atom_index_0.shape[0], -1))
        mol_out =  F.relu(self.bnmol1(mol_out))
        mol_out = self.fcmol2(mol_out)
        mol_out =  F.relu(self.bnmol2(mol_out))
        mol_out = self.fcmol3(mol_out)
        mol_out =  F.relu(self.bnmol3(mol_out))
        mol_out = F.dropout(mol_out, p=self.dropout, training=self.training)
        # nodes transformations
        x = F.relu(self.graph_conv1(x, edge_index))
        for i in range(self.num_conv):
            x = F.relu(self.graph_conv2(x, edge_index))
            
        pool = self.pool_S2S(x, batch)        
        
        
        nodes_0 = x[atom_index_0,:]
        nodes_1 = x[atom_index_1,:]
        
        nodes_edge_pool_0 = out[atom_index_0,:]
        nodes_edge_pool_1 = out[atom_index_1,:]
        
        x = torch.cat([edge_pool, pool, nodes_0, nodes_1, nodes_edge_pool_0, nodes_edge_pool_1], dim=1)
        # BEFORE MLP
        x = self.fc1(x)

        x = F.relu(self.bn1(x))
        x = self.fc2(x)
        x = F.relu(self.bn2(x))
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = torch.cat([x, mol_out], dim=1)
        
        x = self.before_final_fc(x)
        x = F.relu(self.bnbf(x))
        x = self.final_fc(x)
        #x = self.fc3(x)
        return x
```

This achieves reasonable but non competitive scores around 0.4 mae while 0.1 is achievable.
I feel like cherry picking nodes representation i and j could break the "flow" since it's external variables which determines what part of the graph representation goes into the MLP.

### Fully connected Graphs

An other approach I tried is to systematically creates all edges (n(n-1)/2 edges where n is the number of atoms) and try to make all predictions for all atom pairs at one time using a mask to perform gradient descent only on given connections.

However I had issue with creating my torch geometric dataset because the default collate function does not seem to allow matrix as targets.

I get this error when trying to set data(y=a_matrix) : 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-01bfcf89c013> in <module>
----> 1 dataset = MolecularCouplingDataset()

<ipython-input-6-080f091cda03> in __init__(self, root, transform, pre_transform)
      1 class MolecularCouplingDataset(InMemoryDataset):
      2     def __init__(self, root="/home/seb/MolecularCouplingPredictions/output", transform=None, pre_transform=None):
----> 3         super(MolecularCouplingDataset, self).__init__(root, transform, pre_transform)
      4         self.data, self.slices = torch.load(self.processed_paths[0])
      5 

/opt/conda/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     54                  pre_filter=None):
     55         super(InMemoryDataset, self).__init__(root, transform, pre_transform,
---> 56                                               pre_filter)
     57         self.data, self.slices = None, None
     58 

/opt/conda/lib/python3.6/site-packages/torch_geometric/data/dataset.py in __init__(self, root, transform, pre_transform, pre_filter)
     81 
     82         self._download()
---> 83         self._process()
     84 
     85     @property

/opt/conda/lib/python3.6/site-packages/torch_geometric/data/dataset.py in _process(self)
    125 
    126         makedirs(self.processed_dir)
--> 127         self.process()
    128 
    129         print('Done!')

<ipython-input-6-080f091cda03> in process(self)
     33             data_list.append(data)
     34 
---> 35         data, slices = self.collate(data_list)
     36         torch.save((data, slices), self.processed_paths[0])
     37 

/opt/conda/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py in collate(self, data_list)
    148             if torch.is_tensor(data_list[0][key]):
    149                 data[key] = torch.cat(
--> 150                     data[key], dim=data.__cat_dim__(key, data_list[0][key]))
    151             else:
    152                 data[key] = torch.tensor(data[key])

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 5 and 4 in dimension 1 at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/TH/generic/THTensor.cpp:711
```

I tried to overcome this by flattening everything but I struggled with reshaping everything back during  the forward step.

Anyway I decided to create create fake nodes to pad every graph to the maximum size and  I tried to apply a MPNN, then from a matrix (n_graphs, n_conv, n_atom) I tried to create a invariant matrix of shape  (n_graphs, n_conv, n_atom, n_atom) to then apply 1x1 conv2D to get predictions for all edges. Here is the network, results where pretty bad but I am not sure I managed to handle the batches properly.

```
class SimpleNet(torch.nn.Module):
    def __init__(self, num_node_features, num_edge_features,
                 dropout=0.0, output_dim=1, num_conv = 6, conv_size=64, num_steps=8):
        super(SimpleNet, self).__init__()
        self.num_conv = num_conv
        self.num_steps = num_steps
        self.conv_size = conv_size
        self.output_dim = output_dim
        self.dropout = dropout
        
        self.edge_lin0 = torch.nn.Linear(num_node_features, conv_size)

        nn = torch.nn.Sequential(Linear(num_edge_features, 128), ReLU(), Linear(128, conv_size * conv_size))
        self.NNconv = NNConv(conv_size, conv_size, nn, aggr='mean', root_weight=False)
        self.gru = torch.nn.GRU(conv_size, conv_size)
        
        
        self.conv2d =torch.nn.Conv2d(self.conv_size, 1, kernel_size=1)
        
    def forward(self, data):
        x, edge_index, edge_attr, batch = data.x, data.edge_index, data.edge_attr, data.batch
        
        out = F.relu(self.edge_lin0(data.x))
        h = out.unsqueeze(0)

        for i in range(self.num_steps):
            m = F.relu(self.NNconv(out, edge_index, edge_attr))
            out, h = self.gru(m.unsqueeze(0), h)
            out = out.squeeze(0)
        
        reshaped_out = out.view(data.num_graphs, 29, self.conv_size).permute(0, 2, 1)
        order_invariant_m = reshaped_out.reshape(data.num_graphs, self.conv_size, 29, 1) @reshaped_out.reshape(data.num_graphs, self.conv_size, 1, 29)
        
        res_conv2D = self.conv2d(order_invariant_m)
        
        return res_conv2D
```

So a few questions:
1- do you know about such problems that have been tackled before? Do you have any links?
2- how would you approach the problem yourself?
3- which method looks more promising to you?
4- any idea how to overcome the collate error and simply put matrices as targets?
5- does it make any sense to pad every graph to the maximum graph size? how to do so properly?
6- any idea how to deal with training one or different model to take into account the different coupling types?

I hope this message finds you well (I get that it's a bit hairy) but I would really be glad to have your thoughts on this.

Thanks!

**Comment by rusty1s** [comment]
Hi and sorry for answering late, but this is an in-depth question and I hasn‘t habe much time recently. To be honest, I haven‘t looked into the Kaggle competition that closely and I am far from expert on this field, so please take my advice with caution. Overall, I find the best place that describes the problem from a GNN perspective is [this thread](https://www.kaggle.com/c/champs-scalar-coupling/discussion/101091#latest-589806). IMO, I would tackle this problem similar. 

1, 2 and 3: While trying to replicate the results of Gilmer et al, I noticed that it is extremely important to perform graph convolution on the fully-connected graphs with distances and bond types as edge features, so I do believe this is the way to go.
4. This is an extremely interesting problem and you may overcome it by saving sparse target matrices in analogy to edge_index and edge_attr, e.g., y_index and y_value. Batching of those values should work fine. Alternatively, dense matrices should work fine too, but they all need to be of equal size. You can save them as [1, N, N] shape to ensure correct batching.
5. This does make sense when you want to model pair-wise interactions. We provide such functionality with to_dense_batch and to_dense_adj in torch_geometric.utils.
6. Do you want to train a single model for all types? I guess you will need to create targets for each coupling type (in sparse scenario) or with an additional dimension (in dense scenario).

**Comment by Optimox** [comment]
Thanks for your answer, it helped me a lot.

I implemented a fully connected version using n(n-1)/2 edges, with corresponding mask and targets for node to node predictions. Putting only half of the edges since my graph is undirected saves space and time. However I am trying to apply a stack of MetaLayers that seem to be working but not as good as I'd expect. I am wondering if this could be due to using only half edges.

In the original paper, the graphs are directed and so information is aggregated following directed eges. My node model looks like this 

```
class NodeModel(torch.nn.Module):
    def __init__(self, num_node_features, num_u_features, node_conv_dim, edge_model_dim):
        super(NodeModel, self).__init__()
        node_mlp1_dim = node_conv_dim
        in_mlp_1 = num_node_features + edge_model_dim
        in_mlp_2 = node_mlp1_dim + num_node_features + num_u_features
        self.node_mlp_1 = Seq(Lin(in_mlp_1, node_mlp1_dim), ReLU(), Lin(node_mlp1_dim, node_mlp1_dim), BatchNorm1d(node_mlp1_dim))
        self.node_mlp_2 = Seq(Lin(in_mlp_2, node_conv_dim), ReLU(), Lin(node_conv_dim, node_conv_dim), BatchNorm1d(node_conv_dim) )

    def forward(self, x, edge_index, edge_attr, u, batch):
        # x: [N, F_x], where N is the number of nodes.
        # edge_index: [2, E] with max entry N - 1.
        # edge_attr: [E, F_e]
        # u: [B, F_u]
        # batch: [N] with max entry B - 1.
        row, col = edge_index
        out = torch.cat([x[col], edge_attr], dim=1)
        out = self.node_mlp_1(out)
        out = scatter_mean(out, row, dim=0, dim_size=x.size(0))
        out = torch.cat([x, out, u[batch]], dim=1)
        return self.node_mlp_2(out)
```

But this part `out = torch.cat([x[col], edge_attr], dim=1)
        out = self.node_mlp_1(out)
        out = scatter_mean(out, row, dim=0, dim_size=x.size(0))` makes me wonder, am I missing half of the messages compared to a fully connected n(n-1) version? It seems that my message fly only from smaller nodes index to larger nodes index (because i have edge_index looking like this [[1, 2, 2, 3, 3, 3], [0, 0, 1, 0, 1, 2]]). Isn't that a big problem in my model?

If so I see two ways to overcome this :
- 1) double the number of edge_index to have all directions 
- 2) try to change my NodeModel to pass messages from both ways. 
Which one would you recommend? How would you implement 2)?

Hope my questions make sense, thanks a lot!

**Comment by rusty1s** [comment]
Yes, you only propagate along half of your edges. I recommend doubling the number of edges. This way you may have more GPU utilization. But honestly, you do not need scatter operations for fully connected graphs. Currently, you implement a sparse version for a very dense graph, which is not that useful. A dense version of your approach should be way faster.

**Comment by Optimox** [comment]
Ok thanks, I doubled the edges and it worked better! Twice longer thoug...

Can I easily switch to a dense implementation with TorchGeometric?

**Comment by rusty1s** [comment]
You can, via the ToDense transform and the DenseDataLoader, but we only provide s limited number of dense GNN operators, although it should be straightforward to extend them or build your own.
