### ISSUE TITLE
RandomNodeLoader missing in module

### ISSUE THREAD

**Issue by MohsenFazaeli** [pyg-team/pytorch_geometric#6020]
### 🐛 Describe the bug

Running example  at
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/ogbn_proteins_deepgcn.py
line 8:
from torch_geometric.loader import RandomNodeLoader

raises following error: 
ImportError: cannot import name 'RandomNodeLoader' from 'torch_geometric.loader'

the code runs after creating class locally. I could not locate the class in module. So, I decided to inform you.

Thank you helpfull repo.

### Environment

* PyG version: 2.1.0.post1
* PyTorch version: 1.12.1
* OS: win 10
* Python version: 3.8
* CUDA/cuDNN version: cpu 
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by LukeLIN-web** [comment]
The previous branch is 
`from torch_geometric.loader import RandomNodeSampler`

**Comment by rusty1s** [comment]
thanks @LukeLIN-web. Indeed, I just renamed the `RandomNodeSampler` in master. You can also take a look at the examples for PyG 2.1.0, see https://github.com/pyg-team/pytorch_geometric/blob/2.1.0/examples/ogbn_proteins_deepgcn.py.

**Comment by MohsenFazaeli** [comment]
Thanks @LukeLIN-web and @rusty1s.
