### ISSUE TITLE
Problems in importing dataset

### ISSUE THREAD

**Issue by vegetablelearning** [pyg-team/pytorch_geometric#6022]
### 🐛 Describe the bug

from torch_geometric.datasets import KarateClub

dataset = KarateClub()
print(f'Dataset: {dataset}:')
print('---------------')
print(f'Number of graphs:{len(dataset)}')

##When I import a dataset, it will report an error to me，the error is ‘TypeError: 'type' object is not subscriptable’，I'm sure the ##version of the scatter sparse and other packages is correct

### Environment

* PyG version:2.1.0.post1
* PyTorch version:1.6.0
* OS:
* Python version:3.7.1
* CUDA/cuDNN version:10.1
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by LukeLIN-web** [comment]
It works well in my docker container.  
https://hub.docker.com/repository/docker/1263810658/pyg 

torch                  1.12.0
torch-geometric        2.1.0.post1
torch-scatter          2.0.9
torch-sparse           0.6.15

**Comment by rusty1s** [comment]
This [Colab](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing#scrollTo=H_VTFHd0uFz6) here works fine for me as well.

**Comment by vegetablelearning** [comment]
Thank you very much. My problem has been solved
