### ISSUE TITLE
Could not find module _convert_cpu.pyd

### ISSUE THREAD

**Issue by dkqkxx** [pyg-team/pytorch_geometric#6024]
### 😵 Describe the installation problem

``` import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\CodeEnv\Python\lib\site-packages\torch_geometric\__init__.py", line 4, in <module>
    import torch_geometric.data
  File "C:\CodeEnv\Python\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data
  File "C:\CodeEnv\Python\lib\site-packages\torch_geometric\data\data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "C:\CodeEnv\Python\lib\site-packages\torch_sparse\__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "C:\CodeEnv\Python\lib\site-packages\torch\_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "C:\CodeEnv\Python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\CodeEnv\Python\Lib\site-packages\torch_sparse\_convert_cpu.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```
Similar to [issues#2850](https://github.com/pyg-team/pytorch_geometric/issues/2850), [issues#5394](https://github.com/pyg-team/pytorch_geometric/issues/5394)

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.12.0
* OS: Win10
* Python version: 3.9.12
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter==2.0.9, torch-sparse==0.6.15

**Comment by dkqkxx** [comment]
The reason is that vs_BuildTools is missing, and the problem has been solved after installation.

**Comment by lemmon-0428** [comment]
> The reason is that vs_BuildTools is missing, and the problem has been solved after installation.
你好，我也遇到这个问题了，可以麻烦您告诉我怎么解决吗？抱歉打扰您了。

**Comment by dkqkxx** [comment]
> > The reason is that vs_BuildTools is missing, and the problem has been solved after installation.
> 你好，我也遇到这个问题了，可以麻烦您告诉我怎么解决吗？抱歉打扰您了。

如果你Windows平台用的是，vs_BuildTools需要安装，选择编译工具，cmake以及必要的Windows头文件，然后按照对应torch版本在https://data.pyg.org/whl/下载安装😀

**Comment by lemmon-0428** [comment]
我是用的jupyter notebook 结果一直用不了torch geometric




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pyg-team/pytorch_geometric"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pyg-team/pytorch_geometric] Could not find module _convert_cpu.pyd (Issue #6024)





   
The reason is that vs_BuildTools is missing, and the problem has been solved after installation.
 你好，我也遇到这个问题了，可以麻烦您告诉我怎么解决吗？抱歉打扰您了。
   
如果你Windows平台用的是，vs_BuildTools需要安装，选择编译工具，cmake以及必要的Windows头文件，然后按照对应torch版本在https://data.pyg.org/whl/下载安装😀

**Comment by lemmon-0428** [comment]
> > > The reason is that vs_BuildTools is missing, and the problem has been solved after installation.
> > > 你好，我也遇到这个问题了，可以麻烦您告诉我怎么解决吗？抱歉打扰您了。
> 
> 如果你Windows平台用的是，vs_BuildTools需要安装，选择编译工具，cmake以及必要的Windows头文件，然后按照对应torch版本在https://data.pyg.org/whl/ 下载安装😀

我们可以微信 交流吗 lizhuoye0428  或者告诉我你的微信号

**Comment by dkqkxx** [comment]
> 我是用的jupyter notebook 结果一直用不了torch geometric
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "pyg-team/pytorch_geometric"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年12月5日(星期一) 晚上7:44
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [pyg-team/pytorch_geometric] Could not find module _convert_cpu.pyd (Issue #6024)
> 
> 
> 
> 
> 
>    
> The reason is that vs_BuildTools is missing, and the problem has been solved after installation.
>  你好，我也遇到这个问题了，可以麻烦您告诉我怎么解决吗？抱歉打扰您了。
>    
> 如果你Windows平台用的是，vs_BuildTools需要安装，选择编译工具，cmake以及必要的Windows头文件，然后按照对应torch版本在https://data.pyg.org/whl/下载安装😀
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

如果在Linux上使用jupyter,直接下载即可，windows设备需要以上操作
