### ISSUE TITLE
Ubuntu18.4 openMVG+openMVS

### ISSUE THREAD

**Issue by code110110** [pyg-team/pytorch_geometric#6030]
### 🐛 Describe the bug

when trying to setup openMVG on my ubuntu18.4
 passed Cmake -DCMAKE_BUILD_TYPE=RELEASE ../src/
but when Cmake --build . --target install
will return the  error:
[ 42%]
#error The SparseCholesky module has nothing to offer in MPL2 only mode。。。
error: ‘AMDOrdering’ does not name a type; did you mean ‘COLAMDOrdering’?
template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::StorageIndex> > class SimplicialLLT;。。
error: expected ‘>’ before ‘<’ token
template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::StorageIndex> > class SimplicialLLT;
error: ‘AMDOrdering’ does not name a type; did you mean ‘COLAMDOrdering’?
template<typename _MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typename _MatrixType::StorageIndex> > class SimplicialLD

some other methods notice my Engin version doesn't match but I checked my Engin version is 3.3.4 should match the need.
so I can't solve the problem , please someone help me.

### Environment

* PyTorch version:
* OS: ubuntu 18.4
* Python version: base environment 2.7
* CUDA/cuDNN version:cuda 11.8/8.3
*

**Comment by rusty1s** [comment]
Not sure to which repository you are referring to, but PyG does not need come with a cmake. Please feel free to re-open this issue if it got mistakenly closed.
