### ISSUE TITLE
CUDA error: initialization error CUDA kernel errors might be asynchronously reported at some other API call

### ISSUE THREAD

**Issue by LukeLIN-web** [pyg-team/pytorch_geometric#6032]
### 🐛 Describe the bug

It has been reported at https://github.com/pyg-team/pytorch_geometric/issues/5340 
When I try [benchmark/training/training_benchmark](https://github.com/pyg-team/pytorch_geometric/blob/master/benchmark/training/training_benchmark.py) 
I also meet this problem : 

Dataset: ogbn-mag
Configuration of ogbn-mag + edge_cnn not supported. Skipping.
Configuration of ogbn-mag + gat not supported. Skipping.
Configuration of ogbn-mag + gcn not supported. Skipping.
Configuration of ogbn-mag + pna not supported. Skipping.
Training bench for rgat:

Batch size=512, Layers amount=2, Num_neighbors=[10, 10], Hidden features size=64, Sparse tensor=False
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### Environment

* PyG version:2.1.0.post1
* PyTorch version:1.10.0
* OS:Ubuntu 18.04.6 LTS
* Python version:3.7.11
* CUDA/cuDNN version:cu113
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for reporting. I fixed it in #6070.
