### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_geometric.explain'

### ISSUE THREAD

**Issue by yhliu2022** [pyg-team/pytorch_geometric#6076]
### 🐛 Describe the bug

I can import other modules, such as 

import torch_geometric.transforms as T
from torch_geometric.datasets import Planetoid
from torch_geometric.nn import GCNConv

But, when I try:

from torch_geometric.explain import Explainer, GNNExplainer

I got this error

### Environment

* PyG version:
* PyTorch version: 1.13
* OS:
* Python version: 3.8
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* conda install pyg -c pyg
* pip install torch-scatter -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
* pip install torch-sparse -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
* pip install torch-geometric
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Yes, this feature is only available on PyG master right now, as indicated [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/explain.html).
