### ISSUE TITLE
Implement Neural Fingerprint from Duvenaud et al.

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#6077]
### 🚀 The feature, motivation and pitch

Neural Fingerprint, continous alternative for molecular fingerprints via convolutional GNNs, is a well known approach to graph classification. PyG already has [the appropriate layer implemented](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.MFConv), and extending this for a full model would be simple, and it would make making benchmarks easier. At the same time it would be very similar to the paper, more so than [DeepChem implementation, which features some changes](https://github.com/deepchem/deepchem/issues/1160). Thus it would be a useful and easy contribution.

**Comment by rusty1s** [comment]
Definitely happy to take this in :)

**Comment by kkothari2001** [comment]
Hi @rusty1s 
I have prior experience in PyG, but am new to contributing to PyTorch Geometric. Could I work on this issue? Some directions would be appreciated!

**Comment by j-adamczyk** [comment]
@kkothari2001 starting with [GCN](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/basic_gnn.html#GCN) would probably be a good start. You could probably even make this almost identically, inheriting from `BasicGNN`. This would not only implement Neural Fingerprint, but also allow users to extend it, e.g. with dropout.

**Comment by Kumbong** [comment]
@kkothari2001 this looks interesting. Not sure if you are still working on this. Can I pick this up ?

**Comment by Kumbong** [comment]
Feel free to. Currently working on a different issue

**Comment by EulerPascal404** [comment]
> @Kumbong @rusty1s can I also start working on this? I have a few holidays coming up so I plan to work on this issue this week. I am new to PyTorch Geometric and open source contributions so working on this will provide me with a valuable experience.

@harshit5674 I am in the same boat as you. Would you be interested in collaborating/splitting up the work. It might make it easier for both of us.

**Comment by harshit5674** [comment]
@EulerPascal404 Yeah sure, i will be happy to collaborate. So how would this work, would we discuss through on this on some platform?

**Comment by EulerPascal404** [comment]
> @EulerPascal404 Yeah sure, i will be happy to collaborate. So how would this work, would we discuss through on this on some platform?

@harshit5674 Great. I think we can just collaborate on this thread(unless you have a better way).

**Comment by EulerPascal404** [comment]
@harshit5674 Are you in the PyG Slack? We can communicate through that, it would be easier.

**Comment by harshit5674** [comment]
@EulerPascal404 i hope you have read the paper. I have added a pull request in which i have tried to implement the model introduced in the paper. It would be really helpful if you help to prepare some tests for it and also try to check some errors/bugs in the pull request.

**Comment by CodeTal** [comment]
@harshit5674 That's awesome! I am an undergraduate green hand in open-source and PyG too and thinking to contribute. Let's make this project better!

**Comment by harshit5674** [comment]
@CodeTal Awesome!

**Comment by DarthRevan07** [comment]
@j-adamczyk did anyone manage to progress further on this issue? Or is it still at home base?

**Comment by j-adamczyk** [comment]
@DarthRevan07 there is [a PR](https://github.com/pyg-team/pytorch_geometric/pull/7105), not mine, not touched since 4 months, and lacking tests. But it's a starting point definitely

**Comment by harshit5674** [comment]
Hey, that PR is mine, apologies for the inactivity on the PR(had a hectic summer), I will try to resolve the issue within this week itself.
