### ISSUE TITLE
Information about models pytorch_geometric supports

### ISSUE THREAD

**Issue by StrangersZero** [pyg-team/pytorch_geometric#6078]
### Suggest a potential alternative/fix

1. i suggest to write an markdown to show models
2. it also can write some formula the model uses and which paper it comes

**Comment by rusty1s** [comment]
We have a [GNN Cheatsheet](https://pytorch-geometric.readthedocs.io/en/latest/notes/cheatsheet.html). Is this similar to what you have in mind?

**Comment by StrangersZero** [comment]
yeah！thank u
