### ISSUE TITLE
How the categories names from Cora Dataset chosen?

### ISSUE THREAD

**Issue by EddyDavies** [pyg-team/pytorch_geometric#609]
## ❓ Questions & Help

In your GCN example [https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gcn.py](url) and many others you use the Cora dataset and in your test loop I don't understand the line 
`for _, mask in data('train_mask', 'val_mask', 'test_mask'):`
Where do the names come from? I have been trying to read about the Cora dataset but not found these names anywhere?

**Comment by rusty1s** [comment]
Those masks denote which nodes are used for training, evaluating and testing the semi-supervised model. The for loop just iterates over those masks. The masks describe the split used in the GCN paper.
