### ISSUE TITLE
index out of range while using to_dense_batch

### ISSUE THREAD

**Issue by konyul** [pyg-team/pytorch_geometric#6103]
### 🐛 Describe the bug

When I use this function, I get index out of range error
```python
pytorch_geometric.to_dense_batch

def to_dense_batch(x, batch,
                   fill_value, max_num_nodes,
                   batch_size):
    r"""Given a sparse batch of node features
    :math:`\mathbf{X} \in \mathbb{R}^{(N_1 + \ldots + N_B) \times F}` (with
    :math:`N_i` indicating the number of nodes in graph :math:`i`), creates a
    dense node feature tensor
    :math:`\mathbf{X} \in \mathbb{R}^{B \times N_{\max} \times F}` (with
    :math:`N_{\max} = \max_i^B N_i`).
    In addition, a mask of shape :math:`\mathbf{M} \in \{ 0, 1 \}^{B \times
    N_{\max}}` is returned, holding information about the existence of
    fake-nodes in the dense representation.

    Args:
        x (Tensor): Node feature matrix
            :math:`\mathbf{X} \in \mathbb{R}^{(N_1 + \ldots + N_B) \times F}`.
        batch (LongTensor, optional): Batch vector
            :math:`\mathbf{b} \in {\{ 0, \ldots, B-1\}}^N`, which assigns each
            node to a specific example. Must be ordered. (default: :obj:`None`)
        fill_value (float, optional): The value for invalid entries in the
            resulting dense output tensor. (default: :obj:`0`)
        max_num_nodes (int, optional): The size of the output node dimension.
            (default: :obj:`None`)
        batch_size (int, optional) The batch size. (default: :obj:`None`)

    :rtype: (:class:`Tensor`, :class:`BoolTensor`)
    """
    if batch is None and max_num_nodes is None:
        mask = torch.ones(1, x.size(0), dtype=torch.bool, device=x.device)
        return x.unsqueeze(0), mask

    if batch is None:
        batch = x.new_zeros(x.size(0), dtype=torch.long)

    if batch_size is None:
        batch_size = int(batch.max()) + 1

    num_nodes = scatter_add(batch.new_ones(x.size(0)), batch, dim=0)#,
                            #dim_size=batch_size) # num_points_in_pillars
    cum_nodes = torch.cat([batch.new_zeros(1), num_nodes.cumsum(dim=0)]) # num_nodes의 축적값

    if max_num_nodes is None:
        max_num_nodes = int(num_nodes.max())
    idx = torch.arange(batch.size(0), dtype=torch.long, device=x.device)
    idx = (idx - cum_nodes[batch]) + (batch * max_num_nodes)

    size = [batch_size * max_num_nodes] + list(x.size())[1:]
    out = x.new_full(size, fill_value)
    if idx.max() >= out.shape[0]:
        import pdb;pdb.set_trace()
    out[idx] = x

    out = out.view([batch_size, max_num_nodes] + list(x.size())[1:])

    mask = torch.zeros(batch_size * max_num_nodes, dtype=torch.bool,
                       device=x.device)
    mask[idx] = 1
    mask = mask.view(batch_size, max_num_nodes)

    return out, mask
```
idx.max() exceeds the shape of out.

this happens intermittently.

![image](https://user-images.githubusercontent.com/70498916/204937007-1671c0b8-0f79-48b7-96e7-66b267e13f47.png)

**Comment by rusty1s** [comment]
Do you have a reproducible example for this?

**Comment by konyul** [comment]
x = torch.randn((274040,5))
batch = torch.randint(0,3,(274040,))
import torch_geometric.utils.to_dense_batch as t_b

output = t_b(x,batch,max_num_nodes=20)

I expect the output should have the shape of (4,20,5)
however the indexerror occurs
![Screenshot from 2022-12-01 18-46-20](https://user-images.githubusercontent.com/70498916/205020434-36bc1b36-9b43-4c43-a8ad-c1891730456f.png)

I guess this is because the maximum nodes falling in a batch exceeds the max_num_nodes. so I want them to clip the rest nodes that exceed the max_num_nodes but they don't.

**Comment by rusty1s** [comment]
Oh, for `to_dense_batch`, the `batch` vector needs to be sorted.

**Comment by konyul** [comment]
oh, I see.. thank you!!

**Comment by konyul** [comment]
![image](https://user-images.githubusercontent.com/70498916/205316929-5c393ca7-e39b-45fb-8fd2-679f36d43419.png)
The result which batch is sorted is not working...

**Comment by konyul** [comment]
![image](https://user-images.githubusercontent.com/70498916/205317319-237cc87b-f4ed-4f17-b445-d601661b6cbb.png)

The result which batch is sorted is still not working...

**Comment by EdisonLeeeee** [comment]
`output = t_b(x, batch)` that should work.

**Comment by rusty1s** [comment]
Yeah, I was wrong. `max_num_nodes` should always be larger than the maximum nodes in the examples. We currently do not support "dropping" of nodes here.

**Comment by konyul** [comment]
changing idx = (idx - cum_nodes[batch]) + (batch * max_num_nodes)
-> idx = torch.clamp((idx - cum_nodes[batch]),max=max_num_nodes-1) + (batch * max_num_nodes) in def to_dense_batch would fix the problem

**Comment by rusty1s** [comment]
Yeah, thanks for the code. I fixed it via https://github.com/pyg-team/pytorch_geometric/pull/6124.
