### ISSUE TITLE
index_select does not select data.y subset

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#6110]
### 🐛 Describe the bug

I am trying to extract subsets of graphs and `y` vector for graph classification. However, it seems like `.index_select()` does not select subset of `y` vector.

Using OGB for data loading:
```
from ogb.graphproppred import PygGraphPropPredDataset


dataset = PygGraphPropPredDataset(name="ogbg-molhiv")
splits_idxs = dataset.get_idx_split()

train = dataset.index_select(splits_idxs["train"])
valid = dataset.index_select(splits_idxs["valid"])
test = dataset.index_select(splits_idxs["test"])

train_num_graphs = len([None for _ in train])
valid_num_graphs = len([None for _ in valid])
test_num_graphs = len([None for _ in test])

print(train_num_graphs, len(train.data.y))
print(valid_num_graphs, len(valid.data.y))
print(test_num_graphs, len(test.data.y))
```

This results in:
```
32901 41127
4113 41127
4113 41127
```

Doing this manually works:
```
train = dataset.index_select(splits_idxs["train"])
y_train = train.data.y[splits_idxs["train"]]

valid = dataset.index_select(splits_idxs["valid"])
y_valid = valid.data.y[splits_idxs["valid"]]

test = dataset.index_select(splits_idxs["test"])
y_test = test.data.y[splits_idxs["test"]]

train_num_graphs = len([None for _ in train])
valid_num_graphs = len([None for _ in valid])
test_num_graphs = len([None for _ in test])

print(train_num_graphs, len(y_train))
print(valid_num_graphs, len(y_valid))
print(test_num_graphs, len(y_test))
```

Output:
```
32901 32901
4113 4113
4113 4113
```

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.0+cpu
* OS: Ubuntu 20.04
* Python version: 3.9.15
* CUDA/cuDNN version: -
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): OGB version 1.3.5

**Comment by EdisonLeeeee** [comment]
Thanks for reporting. I think this is expected since `train/valid/test.data` is a reference of `dataset.data`. In other words, PyG only modifies the indices of the original data being indexed when using `index_select`.

**Comment by j-adamczyk** [comment]
@EdisonLeeeee thank you for fast response. This behavior is undocumented, however, or at least I could not find any mention of this. Additionally, this makes PyG problematic to work with non-GNN methods for graph classification, or in general any tabular feature extraction.

For example, PyG implements Local Degree Profile (LDP) features, which in the paper are then fed to tabular classifier. To accomplish this, one first needs to get train/valid/tests graphs and targets, and then extract features. This requires this weird additional indexing of `y` that I had to do. I understand if this is intended, but this should be documented, since LDP baseline is shown to be quite strong and implementing it is a good practice for graph classification tasks.

**Comment by rusty1s** [comment]
It is actually not recommended to use `dataset.data`, this is just the internal storage of an `InMemoryDataset`. Sadly, I should have made this property private, but now it is too late too change due to backward incompatibility issues :(

**Comment by j-adamczyk** [comment]
@rusty1s PyG is very useful for data loading and some preprocessing for various graph-based methods, e.g. to later mix with Karateclub and Scikit-learn, and easy access to target vector is quite important.

Perhaps this behavior should be changed? I would absolutely assume that method called `index_select`, which selects a subset of dataset by index, will select both features (graphs, in this case) and targets. This would make sense, since `Dataset` class couples both data and targets in the same place, so selection should be simultaneous.

Even if the current behavior is kept, there should be some way to easily index `y`, without using internal `data`, if this is an undesirable thing to do.

**Comment by rusty1s** [comment]
I would be open to provide an alternative API for this. Do you have some suggestion? Would something like `dataset.y` be confusing? What about other attributes?

**Comment by j-adamczyk** [comment]
Yes, `dataset.y` would be perfect, and something I initially expected. And then `y` should be indexable, with `.index_select()` or regular square brackets `[]`.

**Comment by rusty1s** [comment]
Implemented this feature in https://github.com/pyg-team/pytorch_geometric/pull/6319 :) Let me know if this works for you.

**Comment by j-adamczyk** [comment]
@rusty1s yes, this works perfectly. However, I think that the new warning when using `data` will be thrown, since the class itself uses it to access data, e.g. in `self._infer_num_classes(self.data.y)` or in `return copy.copy(self.data)`. This means that this warning will be thrown even if this property is not used from outside this class, am I right?

**Comment by rusty1s** [comment]
Can you point me to the code you are referring to? I changed all occurrences of `self.data` to `self._data`.

**Comment by j-adamczyk** [comment]
@rusty1s you're right, I must have misread something. Looks great!
