### ISSUE TITLE
Error encountered downloading dataset using Planetoid()

### ISSUE THREAD

**Issue by vegetablelearning** [pyg-team/pytorch_geometric#6119]
### 🐛 Describe the bug

from torch_geometric.datasets import Planetoid
dataset = Planetoid(root='/data/dataset',name='Cora')
data = dataset[0]
print(data.edge_index.size())

###When I looked at the shape of this variable, I found that its shape was 2 * 10556, but in my impression, the Cora dataset should be 2 * 5429, and the graph should have 5429 edges. The same problem exists in Citeseer dataset and Pubmed dataset. I don't know if it's my code or something is wrong.

### Environment

* PyG version:2.1.0.post1
* PyTorch version:1.8.1
* OS:
* Python version:3.7.15
* CUDA/cuDNN version:cuda 10.1
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
+ There are some duplicated edges and self-loops in the datasets, PyG just removed them.
+ The datasets in `Planetoid` are made undirected.

**Comment by vegetablelearning** [comment]
> * There are some duplicated edges and self-loops in the datasets, PyG just removed them.
> * The datasets in `Planetoid` are made undirected.

I still don't understand why there are more edges in the dataset downloaded with pyg than in the general dataset. If pyg removes some edges, the number of edges in the Cora data set should be smaller than 5429, but the result is 10556, which is not twice the size of 5429. I want to know how 10556 was calculated. I would be grateful if you could answer my question.

**Comment by EdisonLeeeee** [comment]
1. Remove duplicated edges: 5429 -> 5278
2. Convert to undirected graphs: 5278 * 2 ->  10556

The graph is made undirected so the edges of two directions are counted.

**Comment by vegetablelearning** [comment]
> 1. Remove duplicated edges: 5429 -> 5278
> 2. Convert to undirected graphs: 5278 * 2 ->  10556
> 
> The graph is made undirected so the edges of two directions are counted.

Thank you very much. I understand your answer.
