### ISSUE TITLE
??????

### ISSUE THREAD

**Issue by MrAcademic** [pyg-team/pytorch_geometric#613]
Could you please help me how install your Library?

pip install --no-cache-dir torch-scatter
Collecting torch-scatter
  Downloading https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/setup.py'"'"'; __file__='"'"'/private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-wheel-faeimbyx --python-tag cp37
       cwd: /private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/
  Complete output (59 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/test
  copying test/test_std.py -> build/lib.macosx-10.7-x86_64-3.7/test
  copying test/test_max_min.py -> build/lib.macosx-10.7-x86_64-3.7/test
  copying test/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/test
  copying test/test_multi_gpu.py -> build/lib.macosx-10.7-x86_64-3.7/test
  copying test/test_forward.py -> build/lib.macosx-10.7-x86_64-3.7/test
  copying test/utils.py -> build/lib.macosx-10.7-x86_64-3.7/test
  copying test/test_backward.py -> build/lib.macosx-10.7-x86_64-3.7/test
  creating build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/max.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/add.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/div.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/std.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/min.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/mean.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/mul.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  copying torch_scatter/sub.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
  creating build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
  copying torch_scatter/utils/gen.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
  copying torch_scatter/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
  copying torch_scatter/utils/ext.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
  running build_ext
  /anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:171: UserWarning:

                                 !! WARNING !!

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (g++) is not compatible with the compiler Pytorch was
  built with for this platform, which is clang++ on darwin. Please
  use clang++ to to compile your extension. Alternatively, you may
  compile PyTorch from source using g++, and then you can also use
  g++ to compile your extension.

  See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
  with compiling PyTorch from source.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                !! WARNING !!

    platform=sys.platform))
  building 'torch_scatter.scatter_cpu' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/cpu
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/lib/python3.7/site-packages/torch/include -I/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/anaconda3/include/python3.7m -c cpu/scatter.cpp -o build/temp.macosx-10.7-x86_64-3.7/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from cpu/scatter.cpp:1:
  In file included from /anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4:
  In file included from /anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:3:
  /anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: 'cstddef' file not found
  #include <cstddef>
           ^~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter ... error
    ERROR: Command errored out with exit status 1:
     command: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/setup.py'"'"'; __file__='"'"'/private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-record-fa90qllr/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/
    Complete output (59 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/test
    copying test/test_std.py -> build/lib.macosx-10.7-x86_64-3.7/test
    copying test/test_max_min.py -> build/lib.macosx-10.7-x86_64-3.7/test
    copying test/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/test
    copying test/test_multi_gpu.py -> build/lib.macosx-10.7-x86_64-3.7/test
    copying test/test_forward.py -> build/lib.macosx-10.7-x86_64-3.7/test
    copying test/utils.py -> build/lib.macosx-10.7-x86_64-3.7/test
    copying test/test_backward.py -> build/lib.macosx-10.7-x86_64-3.7/test
    creating build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/max.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/add.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/div.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/std.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/min.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/mean.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/mul.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    copying torch_scatter/sub.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter
    creating build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
    copying torch_scatter/utils/gen.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
    copying torch_scatter/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
    copying torch_scatter/utils/ext.py -> build/lib.macosx-10.7-x86_64-3.7/torch_scatter/utils
    running build_ext
    /anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:171: UserWarning:

                                   !! WARNING !!

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (g++) is not compatible with the compiler Pytorch was
    built with for this platform, which is clang++ on darwin. Please
    use clang++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using g++, and then you can also use
    g++ to compile your extension.

    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                  !! WARNING !!

      platform=sys.platform))
    building 'torch_scatter.scatter_cpu' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/cpu
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/lib/python3.7/site-packages/torch/include -I/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/anaconda3/include/python3.7m -c cpu/scatter.cpp -o build/temp.macosx-10.7-x86_64-3.7/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command lineto use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from cpu/scatter.cpp:1:
    In file included from /anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4:
    In file included from /anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:3:
    /anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: 'cstddef' file not found
    #include <cstddef>
             ^~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/setup.py'"'"'; __file__='"'"'/private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-install-j6pyv_1y/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pj/c1zvx_055996p9q9rtr5qnfr0000gn/T/pip-record-fa90qllr/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rusty1s** [comment]
It says that your compiler is not supported. Eventually, [this](https://twitter.com/xbresson/status/1154686843130011649/photo/1) may help you.

**Comment by MrAcademic** [comment]
Thanks for your comment.
These consideration is important or not before that command?
I just wanna install for CPU.

$ echo $PATH
>>> /usr/local/cuda/bin:...

$ echo $CPATH
>>> /usr/local/cuda/include:...

**Comment by rusty1s** [comment]
Not needed for CPU only.

**Comment by MrAcademic** [comment]
Is It possible PyTorch 1.2 causes these errors?

**Comment by rusty1s** [comment]
No :)
