### ISSUE TITLE
Provide an example of PyG with `torch._dynamo`

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#6131]
### 🚀 The feature, motivation and pitch

With the recent release of PyTorch 2.0 nightly, we should provide an example of how we can leverage the Python JIT compiler `torch._dynamo` to accelerate GNNs.

Integration should be as easy as running:
```python
import torch._dynamo as dynamo
opt_model = dynamo.optimize("inductor")(your_gnn_model)
```

Link: https://pytorch.org/docs/master/dynamo/

**Comment by hakeemo** [comment]
Is help wanted on this issue ?

**Comment by rusty1s** [comment]
Thanks for the offer! I didn't manage yet to try it out, so if you want to go ahead with this one, please do so :) I was imagining we can simply provide a short example for this, and measure timings between optimized and non-optimized versions.

**Comment by akihironitta** [comment]
There are examples of using `torch.compile` with PyG are available at: https://github.com/pyg-team/pytorch_geometric/tree/master/examples/compile
Also, there're quite a number of benchmark scripts under [the `benchmark/` directory](https://github.com/search?q=repo%3Apyg-team%2Fpytorch_geometric+compile+path%3Abenchmark&type=code).
