### ISSUE TITLE
What's the difference between the example directory and benchmark directory inside pytorhc_geometric

### ISSUE THREAD

**Issue by PPGGG** [pyg-team/pytorch_geometric#6153]
What's the difference between the example directory and benchmark directory inside pytorhc_geometric ? 

It's seems that the model inside the `benchmark/kernel` is good enough to start a training process, except for the missing of dataset.

**Comment by rusty1s** [comment]
The `benchmark/citation`, `benchmark/kernel` and `benchmark/points` dataset replicate the experiments in our PyG paper. The `examples/` directory contains examples across all PyG functionality and try to replicate other's papers experiments as well.

**Comment by PPGGG** [comment]
@rusty1s  Thanks a lot.
