### ISSUE TITLE
Support different message passing schemes

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#6206]
### 🚀 The feature, motivation and pitch

Currently PyTorch Geometric supports vanilla message passing scheme, where each node sends messages to all neighbors. Recently, multiple message passing schemes have been proposed to combat oversmoothing, tottering and other unfavorable behaviors in GNNs, e.g.:
- using fully connected graph for message passing (https://arxiv.org/abs/2006.05205)
- Shortest Path Networks, which pass messages only along shortest paths between node pairs (https://arxiv.org/abs/2206.01003)
- Directed MPNN, which passes messages along directed edges (https://arxiv.org/abs/1904.01561)
- Expander Graph propagation, which constructs a Cayley graph for passing messages (https://arxiv.org/abs/2210.02997)

For directed PMNN, [this issue](https://github.com/pyg-team/pytorch_geometric/issues/1497) suggested using line graph, which is a solution, but one that is indirect and specific to only this case. As far as I can tell, it is currently not possible to easily implement other approaches with PyG.

Being able to decouple message passing from graph structure, and being able to provide propagation graph, would probably be the easiest way to add this. Neighbors for message passing can then be inferred from this propagation graph.

**Comment by rusty1s** [comment]
Thanks for this issue. The currently strategy for this is to pre-process `edge_index` and bring it into the right format such that message passing are only passed between the desired neighbors. If you have better ideas on how to integrate this, let me know :)
