### ISSUE TITLE
'batch' attribute of 'HeteroDataBatch'

### ISSUE THREAD

**Issue by Jerome-Cong** [pyg-team/pytorch_geometric#6209]
### 🚀 The feature, motivation and pitch

In the doc [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Batch), the **Batch** object has an attribute **batch** to identify each node to its respective graph. This is true for homogeneous data. But when dealing with **HeteroData**, it doesn't have this. 

### Additional context

Are there any ways to implement a similar feature to that?

**Comment by Jerome-Cong** [comment]
> For heterogeneous graphs, the `batch` information is available in the node types.

Thanks for your reply! With the following code example, I can only get a list of str about node types from `batch.node_types`
```
data=HeteroData()
data['a'].x = torch.empty((4, 6)).float()
data['b'].x = torch.empty((1,6)).float()
data['a','with','a'].edge_index = torch.Tensor([[0,0,1,1,2,2,3,3],[1,2,0,3,0,3,1,2]]).long()
data['a','to','b'].edge_index = torch.Tensor([[0,1,2,3], [0,0,0,0]]).long()
data_list = [data, data, data]
test_loader = DataLoader(data_list,batch_size=3)
batch = next(iter(test_loader))
print(batch.node_types)
```
**Output:**
`['a', 'b']`
Did I misunderstand your point or make mistakes somewhere?

**Comment by rusty1s** [comment]
You can do something like `batch["a"].batch`.
