### ISSUE TITLE
How could I build a GCN for my own data,could you provide a example for me?

### ISSUE THREAD

**Issue by xiaobai12345** [pyg-team/pytorch_geometric#621]
## ❓ Questions & Help
how could i build a graph network for my own data, do you have a sample to handle for that, or do you have a sample to solve your own data, I need  some code for  solving raw data, 
because i do not known how to use the pytorch_geometric API to solve my own data, thanks your reply.

**Comment by rusty1s** [comment]
Hi, did you try to read the [documentation](https://pytorch-geometric.readthedocs.io/en/latest/)? We describe our data format [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#data-handling-of-graphs), an example  on how you create your own network and train it [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#learning-methods-on-graphs). In addition, if you have a bunch of graphs you can build your [own dataset](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html). For training, we provide a bunch of examples in the `examples/` directory, *e.g.*:

* [Training on single graphs in a transductive semi-supervised learning scenario](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gcn.py)
* [Training on many small graphs in an inductive learning scenario](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py)

Feel free to ask if you encounter any questions!

**Comment by xiaobai12345** [comment]
Thank you for your letter. Your reply is very helpful to me. In addition, I would like to ask you if you have written some code to process your own data. I don't know if you can share your code. If you can, I'd like to take a detailed look at the code you wrote with the pytorch_geometric tool. Thank you.



------------------ 原始邮件 ------------------
发件人: "Matthias Fey"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 中午12:25
收件人: "rusty1s/pytorch_geometric"<pytorch_geometric@noreply.github.com>; 
抄送: "齐白one"<2272638562@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [rusty1s/pytorch_geometric] How could I build a GCN for my owndata,could you provide a example for me? (#621)




Hi, did you try to read the documentation? We describe our data format here, an example  on how you create your own network and train it here. In addition, if you have a bunch of graphs you can build your own dataset. For training, we provide a bunch of examples in the examples/ directory, e.g.:
  
Training on single graphs in a transductive semi-supervised learning scenario
 
Training on many small graphs in an inductive learning scenario
  
Feel free to ask if you encounter any questions!

**Comment by rusty1s** [comment]
I can not share such an example with you, but I suggest you to look up the implementations of the publicly available datasets and adjust them to your needs.
