### ISSUE TITLE
Is torch_geometric.data.HeteroData for directed graph by default?

### ISSUE THREAD

**Issue by Jerome-Cong** [pyg-team/pytorch_geometric#6210]
### 📚 Describe the documentation issue

In the notes of [heterogeneous graph learning](https://pytorch-geometric.readthedocs.io/en/latest/notes/heterogeneous.html#creating-heterogeneous-graphs), when creating heterogeneous graphs, the edge index tensors are defined by a triplet (**source_node_type, edge_type, destination_node_type**) and then it says that triplet identifies the edge type exists between the two node types.  

Does that mean the edge type is directed (pointing from source_node_type to destination_node_type) or undirected (connecting the source and the destination node)?

### Suggest a potential alternative/fix

If possible, please explain it explicitly (either directed edge or undirected edge)

**Comment by rusty1s** [comment]
Yes, each edge type is directed. If you want to include both directions (which you should always do for message passing), you can achieve this via `data = transforms.ToUndirected()(data)`.
