### ISSUE TITLE
Questions about propagate function in PYG 

### ISSUE THREAD

**Issue by HelloWorldLTY** [pyg-team/pytorch_geometric#6211]
### 🐛 Describe the bug

Hi, I found such an error message in the function self.propagate (now forward):

ValueError: Expected 'edge_index' to be of type 'torch.long' (got 'torch.float32')

However, my tensor can be used to perform forwarding and the codes are:

        train_pos_edge_index = graph.edge_index.long()
        
        z = gene_encoder(x, train_pos_edge_index, graph.show_index)
        
        preg = loss_fun_preg.soft_cross_entropy(
            F.softmax(
                gene_encoder.propagate(x, train_pos_edge_index, graph.show_index),
                dim=1
            ),
            F.softmax(
                gene_encoder(x, train_pos_edge_index, graph.show_index),
                dim=1
            )
        )

Could you please help me address the problem in propagate? Thanks.

### Environment

* PyG version:  2.1.0
* PyTorch version: 1.11.0
* OS: linux
* Python version: 3.8
* CUDA/cuDNN version: 11.7+8.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
The `edge_index` should be the first argument in `self.propagate`.
