### ISSUE TITLE
Hardware for PyTorch Geometric

### ISSUE THREAD

**Issue by testzorg** [pyg-team/pytorch_geometric#624]
This [paper](https://arxiv.org/abs/1907.10701) got me wondering if there is any specific type of GPU or similar that works particularly well with this software / with GNNs in general. What do you recommend / what has your experience been? How does the conclusion of this [blog post](https://timdettmers.com/2019/04/03/which-gpu-for-deep-learning/) apply to PyTorch Geometric?

**Comment by rusty1s** [comment]
Thank you for the link to the paper. I think that the conclusion of the blog post does also hold for sparse architectures like they are implemented in PyTorch Geometric. At work I have access to a 1080Ti ans 2080Ti and both work great, but comparably equal. There are also a lot of students of mine which run PyG on lower hardware and they never complained. I do not have access to any other setups, so it is quite hard to answer your question, e.g., I never played around with TPUs, but according to [this paper](https://arxiv.org/abs/1906.11786) GNNs can also be heavily accelerated by the use of TPUs and a clever memory layout.
