### ISSUE TITLE
TUDataset Problem

### ISSUE THREAD

**Issue by fork123aniket** [pyg-team/pytorch_geometric#6262]
### 😵 Describe the installation problem

Here is my code:

```
from torch_geometric.datasets import TUDataset

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')
loader = DataLoader(dataset, batch_size=100, shuffle=True)
edge_y = torch.randint(low=0, high=30,
                       size=(dataset[4].edge_index.size(1),))


class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(3, 7, add_self_loops=True, normalize=False)
        self.conv2 = GCNConv(7, 9, add_self_loops=False, normalize=True)
        self.conv3 = GCNConv(9, 6, add_self_loops=True, normalize=False)

    def forward(self, x, edge_index, batch, edge_weight):
        x = F.relu(self.conv1(x, edge_index, edge_weight))
        x = F.dropout(x, training=self.training)
        x = F.relu(self.conv2(x, edge_index, edge_weight))
        x = F.dropout(x, training=self.training)
        x = F.relu(self.conv3(x, edge_index, edge_weight))
        x = global_add_pool(x, batch)
        return F.log_softmax(x, dim=1)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01,
                             weight_decay=5e-4)

for epoch in range(1, 5):
    loss_all = 0
    for data in loader:
        model.train()
        optimizer.zero_grad()
        output = model(data.x, data.edge_index, data.batch,
                       data.edge_weight)
        loss = F.nll_loss(output, data.y)
        loss.backward()
        torch.nn.utils.clip_grad_value_(model.parameters(), 2.0)
        optimizer.step()
        loss_all += loss.item() * data.num_graphs
    print('Epoch {:03d}'.format(epoch),
          'train_loss: {:.4f}'.format(loss_all / len(loader.dataset)))
print("Optimization Finished!")
```

Here is the error I have come across:
```
Traceback (most recent call last):
  File "C:\Documents\Implementations\PyG PRs\GraphMask\Example.py", line 311, in <module>
    dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')
  File "C:\Documents\Implementations\PyG PRs\GraphMask\venv\lib\site-packages\torch_geometric\datasets\tu_dataset.py", line 127, in __init__
    raise RuntimeError(
RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.
```

I don't have any `dataset` folder already, which I can delete/remove `processed/` directory from. Need help on this as I don't see any solution for this problem on the internet.

Thank you...

### Environment

* `PyG` version: 2.2.0
* `PyTorch` version: 1.13.1
* `OS`: Windows 11 64-bit
* `Python` version: 3.9.5
* `CUDA/cuDNN` version: NA
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cpu.html`
* `torch-scatter` version: 2.1.0+pt113cpu
* `torch-cluster` version: 1.6.0+pt113cpu
* `torch-sparse` version: 0.6.15+pt113cpu
* `torch-spline-conv` version: 1.2.1+pt113cpu

**Comment by rusty1s** [comment]
There should be a folder `/tmp/ENZYMES` which you can try to remove. Let me know if this helps.

**Comment by fork123aniket** [comment]
I don't see any `/tmp/ENZYMES` folder anywhere inside the installed `PyG` library folder. I have created `Virtual Environment` via `PyCharm IDE` and installed the latest version of `PyG` inside the same, yet I'm continue to receive aforementioned error while trying to use the `TUDataset`. Even this code statement: `dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')` doesn't download the `TUDataset`, instead throws the aforementioned error. Don't know how to fix it now. Some screenshots of the installed `PyG` library folder have been attached below for further reference. Please help!!!

View of Installed `PyG` folder:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/92912434/208376304-714c690a-d754-47b4-a3ad-16888fd8de7b.png">

View of `data` folder inside already installed `PyG` folder:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/92912434/208376471-774117ce-d8f8-4f07-a177-f5569704326a.png">

View of `datasets` folder inside already installed `PyG` folder:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/92912434/208376563-47789fc3-49b7-4223-8864-9f76b87a1dd2.png">

**Comment by rusty1s** [comment]
Yes, the dataset should be downloaded to `/tmp/ENZYMES`. Since you are on Windows, maybe try something like
```python
dataset = TUDataset(root='ENZYMES', name='ENZYMES')
```
