### ISSUE TITLE
Splitting Edges of a Really Big Graph leads to Error:

### ISSUE THREAD

**Issue by joeybose** [pyg-team/pytorch_geometric#628]
## ❓ Questions & Help

If there is a really big Graph say (100k+ nodes) calling `model.split_edges(...)` as done in VGAE or GAE can throw Runtime Errors. Specifically, this line will throw the following error: https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/models/autoencoder.py#L122
`RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0`. Is there a way to better handle really large graphs? Maybe Sparse Matrices?

**Comment by rusty1s** [comment]
We use a dense matrix to sample negative edges, and hence you run out of memory on large graphs. A better approach would be to sample sparse random node pairs, and doing this as long as a fixed number of negative examples were sampled. Sampled node pairs should be unique, undirected, and have no self-loops.

**Comment by joeybose** [comment]
Awesome, do you think it would be worth while have an optional flag in the split_edges function that can sample sparse random node pairs? As in perhaps there could be a sparse negative sampling function for large graphs.

**Comment by rusty1s** [comment]
I do not know. We need to benchmark it to see if it is worth it to keep the dense version after all. If yes, an optional flag might be a good idea.

**Comment by rusty1s** [comment]
We also support sampling of negatives in a sparse fashion. Closing this issue as a result.
