### ISSUE TITLE
Add support for PyG <-> NetworKit conversion

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#6320]
### 🚀 The feature, motivation and pitch

NetworKit (https://networkit.github.io/) is a high performance graph library. It allows computation of various graph properties (e.g. shortest paths, betweenness, PageRank), with interface similar to NetworkX. However, it is about 10-100x faster than NetworkX, see [this independent benchmark](https://github.com/timlrx/graph-benchmarks), so for larger graphs it is quite useful.

PyG currently supports PyG <-> NetworkX conversion. For NetworKit, it has NetworkX converter function, but this way computing properties becomes PyG -> NetworkX -> NetworKit and then NetworKit -> NetworkX -> PyG. It is still very much worth it for datasets with many large graphs, but this overhead is quite significant. If PyG supported PyG <-> NetworKit conversion, this would be much more efficient.

This should be very easy, as NetworKit has a graph construction API very similar to NetworkX, so we can base on an existing function.

**Comment by rusty1s** [comment]
Great idea. I made a first PR in https://github.com/pyg-team/pytorch_geometric/pull/6321. Let me know what you think :)

**Comment by j-adamczyk** [comment]
@rusty1s this looks great, thank you!
