### ISSUE TITLE
link prediction

### ISSUE THREAD

**Issue by Purpleheather** [pyg-team/pytorch_geometric#634]
## ❓ Questions & Help

Is there an example of RGCN doing link prediction?

**Comment by rusty1s** [comment]
No, we sadly do not have a link prediction example of RGCN, but it should be relatively easy to implement. The main part would be to add the necessary datasets to the repository. Feel free to work on it if you like :)

**Comment by WMF1997** [comment]
hello @Purpleheather

Here is a [repo](https://github.com/XuSShuai/SEAL-for-link-prediction) about link prediction in github. 
NOTE THAT it is implemented on TensorFlow 1.7.0 and networkx 2.0 (the repo's owner shows that networkx 2.0+ does not work, in this [issue](https://github.com/XuSShuai/SEAL-for-link-prediction/issues/1)) 

and its arxiv preprint paper: [*Link Prediction Based on Graph Neural Networks*](https://arxiv.org/pdf/1802.09691.pdf)


I installed it and run it on the environment below:
Ubuntu 16.04 (NO CUDA)
Python 3.7
TensorFlow 1.13.1


I do not know your environment. And I run the repo's [gnn_implementation folder](https://github.com/XuSShuai/SEAL-for-link-prediction/tree/master/GNN_implement), whose main.py uses mutag dataset. (in fact, we have mutag dataset in pyg)

in [./GNN_implement/gnn.py](https://github.com/XuSShuai/SEAL-for-link-prediction/blob/master/GNN_implement/gnn.py): 118-131 (118-131 lines) shows its gnn network. I think it is a GCN. 

hope to help you a little. 

yours sincerely
@wmf1997

**Comment by tchaton** [comment]
@WMF1997, interesting to follow this thread. I might give a try to SEAL.

Best,
T.C

**Comment by tchaton** [comment]
Here is the pytorch version: https://github.com/muhanzhang/SEAL

**Comment by laifi** [comment]
:eyes: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/link_pred.py

**Comment by DavideBuffelli** [comment]
> 👀 👀 ➡️ https://github.com/rusty1s/pytorch_geometric/blob/master/examples/link_pred.py 🎉

Hi, I think there are several errors in this Link Prediction example. I opened an issue about it here https://github.com/rusty1s/pytorch_geometric/issues/1121

**Comment by dongkwan-kim** [comment]
> > 👀 👀 ➡️ [/examples/link_pred.py@`master`](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/link_pred.py) [](/rusty1s/pytorch_geometric/blob/HEAD@{2020-04-13T08:27:13Z}/examples/link_pred.py) 🎉
> 
> Hi, I think there are several errors in this Link Prediction example. I opened an issue about it here #1121

It is fixed now 😊 #1124

**Comment by moritzblum** [comment]
There is now an example: https://github.com/rusty1s/pytorch_geometric/blob/master/examples/rgcn_link_pred.py
