### ISSUE TITLE
Installation failing on mac 

### ISSUE THREAD

**Issue by GianlucaDeStefano** [pyg-team/pytorch_geometric#6362]
### 😵 Describe the installation problem

I have a mac m1 max with a clean python environment  (only the following packages are installed):
```certifi==2022.12.7
charset-normalizer==2.1.1
idna==3.4
numpy==1.24.1
Pillow==9.4.0
requests==2.28.1
torch==1.13.1
torchaudio==0.13.1
torchvision==0.14.1
typing_extensions==4.4.0
urllib3==1.26.13
```

As you can see, I am using the latest torch version (1.13.1),  but if I try to install PyTorch geometric using the command generated by the  [online widget](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html):

```
pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cpu.html
```

I get the error: 
```
ERROR: Could not find a version that satisfies the requirement pyg-lib (from versions: none)
ERROR: No matching distribution found for pyg-lib
```

To generate the command above I used the following options: 
```
PyTorch: 1.13.*,
Your OS: Mac,
Package: Pip,
CUDA: CPU
```

### Environment

* PyG version: latest
* PyTorch version: 1.13.1
* OS: MacOs Ventura 13.1 
* Python version: 3.10
* CUDA/cuDNN version: 
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
`pyg-lib` is not yet available on PyPi. You would need to run
```
pip install git+https://github.com/pyg-team/pyg-lib.git
```
