### ISSUE TITLE
Creating data object features. 

### ISSUE THREAD

**Issue by SaschaStenger** [pyg-team/pytorch_geometric#638]
## ❓ Questions & Help

Hello there. I do have a question regarding the creation of data objects for my own dataset.
Lets say i have a graph and every node has a feature consisting of a data, a short sentence and a provided as a label. 
My problem now is that i load this data out of a csv file and they are not encoded. In every dataset that i have looked through so far, the encoding of features was already done and the only things that needed to be done was laoding in the data. 
I would very much appreciate an example, that shows how to assign different features to each node and/or edge. 

Thank you and i hope that my question is understandable

**Comment by rusty1s** [comment]
It might help if you look up how pre-processing of sentences in done in NLP, e.g., by the use of an index for every word. You can then proceed to pad your input sentences to equal length and store it in a node feature matrix.

PyTorch Geometric does have no restrictions here. You can use embedding layers and LSTMs/GRUs independently for each node, and use the final hidden representation for relational learning.
