### ISSUE TITLE
MessagePassing.propagate Error

### ISSUE THREAD

**Issue by himil48** [pyg-team/pytorch_geometric#6392]
### 🐛 Describe the bug

Hi, 
 
After executing the code 

```
class Model(torch.nn.Module):
    def __init__(self, hidden_channels):
        super().__init__()
        self.encoder = GNNEncoder(hidden_channels, hidden_channels)
        self.encoder = to_hetero(self.encoder, data.metadata(), aggr='sum')
        self.decoder = EdgeDecoder(hidden_channels)
    def forward(self, x_dict, edge_index_dict, edge_label_index):
        z_dict = self.encoder(x_dict, edge_index_dict)
        return self.decoder(z_dict, edge_label_index) 


model = Model(hidden_channels=64).to(device)
model(data.x_dict, data.edge_index_dict,
                 edge_label_index)


```

I receive an error 
`ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index``

```
>>> data.edge_index_dict[('patient','has','condition')].shape
torch.Size([2, 6990])
>>> data.edge_index_dict[('patient','has','condition')].dtype
torch.int64
>>> edge_label_index.shape
torch.Size([2, 123])
>>> edge_label_index.dtype
torch.int64
```

May you please assist me with what the problem might be.
Thank you

### Environment

* PyG version:2.1.0.post1
* PyTorch version: 1.13
* OS: MacOS
* Python version: 3.9
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):
torch-cluster         1.6.0
torch-geometric       2.1.0.post1
torch-scatter         2.0.9
torch-sparse          0.6.15
torch-spline-conv     1.2.1
torchvision           0.14.0

**Comment by rusty1s** [comment]
The snippet you sent looks correct to me. What does `print(self.encoder)` return after the `to_hetero()` call?

**Comment by himil48** [comment]
I ran the entire script again and it seems to work now. 
Thank you

**Comment by rusty1s** [comment]
Super :)
