### ISSUE TITLE
Change default version from 'latest' to latest actual release

### ISSUE THREAD

**Issue by andrinr** [pyg-team/pytorch_geometric#6411]
### 📚 Describe the documentation issue

For me it doesn't make sense that when you load the documentation page, you see a version which is based on a unreleased code ( I think its the nightly build)

For example: [Graph Generators](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html#graph-generators) are already documented but not part of the 2.20 release. 

### Suggest a potential alternative/fix

- Add a disclaimer notifying readers that 'latest' refers to a version of pyg which is not yet released.
- And/Or: Default address should be the latest actual release, not the latest code version

**Comment by rusty1s** [comment]
I like the first idea of adding a disclaimer. Would that work for you?

**Comment by rusty1s** [comment]
Added a note to the documentation, see https://pytorch-geometric.readthedocs.io/en/latest.
