### ISSUE TITLE
Segmentation fault when constructing KNNGraph from empty graph

### ISSUE THREAD

**Issue by Vuenc** [pyg-team/pytorch_geometric#6413]
### 🐛 Describe the bug

When I try to construct a KNNGraph from a graph that has `pos` tensor of shape (0, d), i.e. an empty graph, the `KNNGraph` transform crashes with a segmentation fault:

```python
import torch
import torch_geometric
data = torch_geometric.data.Data(pos=torch.zeros(0,3))
torch_geometric.transforms.KNNGraph(k=5)(data)  #  Segmentation fault
```
Expected behavior: KNNGraph should return a graph with an empty `edge_index` (i.e. of shape (2, 0))

Traceback when I enable `faulthandler`:

```
Current thread 0x00007fd7fc1933c0 (most recent call first):
  File "/home/username/miniconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/nn/pool/__init__.py", line 128 in knn_graph
  File "/home/username/miniconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/transforms/knn_graph.py", line 33 in __call__
  File "<string>", line 5 in <module>
Segmentation fault (core dumped)
```

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.10.2
* OS: Ubuntu
* Python version: 3.9.12
* CUDA/cuDNN version: 11.6
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This is already fixed in `torch-cluster`, we just need to provide a new version. Closing this as a result.
