### ISSUE TITLE
Wrong information of the latest version of the GNN Cheatsheet

### ISSUE THREAD

**Issue by kylemin** [pyg-team/pytorch_geometric#6436]
### 📚 Describe the documentation issue

It says that EdgeConv supports message passing in bipartite graphs with potentially different feature dimensionalities. However, I don't think EdgeConv supports this function. For example, when xi and xj have different dimensions, EdgeConv cannot be applied because of the xj-xi term.

Is this correct? If this is correct, please modify the cheatsheet. If this is not correct, please let me know how I can use EdgeConv with different feature dimensionalities for source and destination nodes.

### Suggest a potential alternative/fix

Please modify the cheatsheet (https://pytorch-geometric.readthedocs.io/en/latest/notes/cheatsheet.html) by removing the checkmark under the bipartite column for the EdgeConv row.

**Comment by rusty1s** [comment]
Yeah, that is correct. While `EdgeConv` can be applied on bipartite graphs, there feature size have to match. That's why we framed it "with potentially different feature dimensionalities". Hope that clarifies your concerns.

**Comment by kylemin** [comment]
Thank you for the clarification! I'll close the issue
