### ISSUE TITLE
What is the default k in GraphConv?Can we define it?

### ISSUE THREAD

**Issue by chengxiao19961022** [pyg-team/pytorch_geometric#644]
## ❓ Questions & Help

What is the default k in [GraphConv](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GraphConv)?Can we define it?

**Comment by rusty1s** [comment]
There is no `k` parameter in the `GraphConv` definition. I am unsure what you mean. Can you elaborate?

**Comment by chengxiao19961022** [comment]
I believe we can define the in k-GNNs in this paper[Weisfeiler and Leman Go Neural: Higher-order Graph Neural Networks](https://arxiv.org/pdf/1810.02244.pdf)?

**Comment by chengxiao19961022** [comment]
Thanks for your attention and sorry for commenting late. I am not so familiar with the theory. But I believe we can define the k in k-GNNs in this paperWeisfeiler and Leman Go Neural: [Higher-order Graph Neural Networks](https://arxiv.org/pdf/1810.02244.pdf)?

**Comment by rusty1s** [comment]
I see, the `GraphConv` is indeed equal to the one in the paper, but the `k` needs to be implemented by the use of a different graph structure (where nodes are replaced by subset of nodes). You can see [here](https://github.com/chrsmrrs/k-gnn) that is implemented by the use of transforms.

**Comment by chengxiao19961022** [comment]
Can I use GraphConv in pytorch_geometric directly without implementing k(the example in enzymes_topk_pool.py uses GraphConv in a simple way)? I am not so familiar with the theory. Guess there may be a default value.

**Comment by rusty1s** [comment]
Yes, but this way it is only as powerful as the 1-WL in distinguishing graph structures.

**Comment by chengxiao19961022** [comment]
I see, k-WL does better on distinguishing graph structures(the author uses a one-hot
encoding of the isomorphism type). But I guess the feature of each node itself is missing cause it uses a one-hot subgraph encoding? Does GraphConv here initialize each node's feature as data.x if I do not do the transforms?

**Comment by rusty1s** [comment]
In addition to the isomorphism type, the k-GNN pools the 1-GNN features to the initial features of 2-GNN or 3-GNN. If you do not use the transforms, simply pass `data.x` to the operator.

**Comment by chengxiao19961022** [comment]
Thanks! I appreciate your help.
