### ISSUE TITLE
Graph Pooling Framework :rocket:

### ISSUE THREAD

**Issue by rusty1s** [pyg-team/pytorch_geometric#6455]
### 🚀 The feature, motivation and pitch

The ["Understanding Pooling in Graph Neural Networks"](https://arxiv.org/abs/2110.05292) paper introduces a simple framework to unify (most) graph pooling approaches:

1. **Select:** Selects input nodes to map to supernodes
2. **Reduce:** Reduces the supernodes to singletons
3. **Connect:** Decides how the new nodes are connected

Currently, the pooling operators included in PyG are implemented isolated from each other, and there exists a lot of repetitive code and different interfaces, which makes their application confusing and challenging. By following the above approach, we can unify existing implementations and can accelerate new research on graph pooling. For example, we can introduce base classes for each of the aforementioned steps:

```python
class Select(torch.nn.Module):
    def forward(self, *args, **kwargs) -> torch.Tensor:
         """Returns a bipartite `edge_index` mapping input nodes to supernodes."""

class Reduce:  # No need -> we can utilize `nn.aggr` for this
    pass

class Connect(torch.nn.Module):
    def forward(self, cluster_index: torch.Tensor, edge_index: torch.Tensor, *args, **kwargs):
        """Returns a coarsened graph."""
```

With this, *e.g.*, `graclus` can be moved to a `Select` operator and `TopK` pooling can be moved to a `Connect` operator.

Relevant twitter thread: https://twitter.com/riceasphait/status/1447867635442585601

Tasks:

- [x] Add `Select` and `Connect` base classes [#6540]
- [x] Add `Pooling` base class [#6540]

Add concrete `Select` and `Connect` classes and update implementations of.
- [x] `TopKPooling` [#7308]
- [x] #7617

**Comment by wsad1** [comment]
Would it be useful to add a `Pooling` class that all pooling operators inherit from.
```
class Pooling(torch.nn.Module):
    def forward(self, x, edge_index, *args, **kwargs):
          mapping = self.select(x, edge_index, *args, **kwargs)
          x = self.reduce(x, mapping)
          edge_index = self.connect(mapping, edge_index, *args, **kwargs)
```
`self.select`, `reduce` and `connect` would be objects defined in the child class like `graclus` or `TopK`.

**Comment by rusty1s** [comment]
Yes, definitely :)

**Comment by danielegrattarola** [comment]
Hey, first author of the paper here!

This is super, if help is still wanted (as I see on the tags) I'd be happy to participate! 

Worth mentioning that there is an implementation of SRC [in Spektral](https://github.com/danielegrattarola/spektral/blob/master/spektral/layers/pooling/src.py#L15) and a few layers implemented with it, it might be possible to translate the implementation from TF to Torch/PyG.

**Comment by wsad1** [comment]
@danielegrattarola firstly great paper. Sorry for the late reply. 
But if you are still interested we could use your help moving `SAGPooling` and `PANPooling`. 
Just refactor topkpooling [here](https://github.com/pyg-team/pytorch_geometric/pull/7308).

**Comment by puririshi98** [comment]
topk microbench PR:
https://github.com/pyg-team/pytorch_geometric/pull/7549

**Comment by puririshi98** [comment]
diff pool microbench PR:
https://github.com/pyg-team/pytorch_geometric/pull/7550

**Comment by puririshi98** [comment]
https://github.com/pyg-team/pytorch_geometric/pull/7361
PR is ready to merge

**Comment by puririshi98** [comment]
https://github.com/pyg-team/pytorch_geometric/pull/7625
