### ISSUE TITLE
'from_netwrokx' doesn't work with my 'group_node_attrs'

### ISSUE THREAD

**Issue by irisferrazzo** [pyg-team/pytorch_geometric#6481]
### 🐛 Describe the bug

Hi,

I' trying to convert a NetwrokX graph into the pyg format to feed it to a GCN.

- from_networkx(G) works without problems

- from_networkx(G, group_node_attrs='x') doesn't work, and I get the following error:

Traceback (most recent call last):
  File "/home/iris/PycharmProjects/GNN/input_preprocessing.py", line 126, in <module>
    pyg_graph1 = from_networkx(G1, group_node_attrs='x_1')
  File "/home/iris/venv/GNN/lib/python3.10/site-packages/torch_geometric/utils/convert.py", line 262, in from_networkx
    x = data[key]
  File "/home/iris/venv/GNN/lib/python3.10/site-packages/torch_geometric/data/data.py", line 444, in __getitem__
    return self._store[key]
  File "/home/iris/venv/GNN/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 85, in __getitem__
    return self._mapping[key]
KeyError: 'x'

My 'x' looks like this:

tensor([[ 0.3818, -1.3873, -0.8542,  ..., -1.0018, -0.1969, -0.3482],
        [-0.1424,  0.3124,  2.0222,  ..., -0.6686, -0.1507, -0.8110],
        [ 2.1959,  0.0281,  0.0663,  ..., -1.7057, -1.4785, -0.8781],
        [ 0.5917,  0.2848,  0.9729,  ..., -1.0171, -1.7088, -1.2153]])

It is a tensor with each row representing a node embedding (bert).

Can you please help me understand how the format of my 'x' should be?

Thank you very much in advance :)

**Comment by rusty1s** [comment]
Do you have a minimal example to reproduce this issue? Note that `group_node_attrs` should be a list, e.g., `['x']`.

**Comment by irisferrazzo** [comment]
Hi, thank you for your reply!

My 'group_node_attrs' is a list of lists. Each of these sublists comprehends the (bert) embedding of my each of my nodes.
My goal is to update these initial node representation with the help of a GCN.

I have converted the elements of the embeddings sublists in str, but the format of the the nested list (my 'group_node_attrs' ) may be the problem, right?

It is a bit complicated to give an example, but if it is required or it may help I can try to do it!

**Comment by rusty1s** [comment]
Ah, so each node actually has a matrix of embeddings? If the embedding sizes do not match across nodes, this will currently fail in `from_networkx`. Otherwise, I don't see an issue with this.

**Comment by irisferrazzo** [comment]
I give an example so that you can reproduce the error that I'm still getting, that is as follow:

Traceback (most recent call last):
  File "/home/iris/PycharmProjects/GNN/input_preprocessing.py", line 161, in <module>
    pyg_graph1 = from_networkx(G1, group_node_attrs=x_1_str)
  File "/home/iris/venv/GNN/lib/python3.10/site-packages/torch_geometric/utils/convert.py", line 262, in from_networkx
    x = data[key]
  File "/home/iris/venv/GNN/lib/python3.10/site-packages/torch_geometric/data/data.py", line 444, in __getitem__
    return self._store[key]
  File "/home/iris/venv/GNN/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 85, in __getitem__
    return self._mapping[key]
TypeError: unhashable type: 'list'


Here the example:

import networkx as nx
from torch_geometric.utils.convert import from_networkx
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

nodes= ['1', '5', '28']
edges= [('1', '5'), ('5', '28')]

G = nx.DiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

# x is actually longer, each list consists of the 768 dim, but here for a representation:
x=[['0.7844669818878174', '-0.40328940749168396', '-0.9366764426231384'],['0.14061762392520905', '-1.1449155807495117', '-0.1811756044626236'],['-1.8840126991271973', '-1.2096494436264038', '1.0780194997787476']]

pyg_graph = from_networkx(G, group_node_attrs=x)

Thank you very much in advance!

**Comment by irisferrazzo** [comment]
I found the problem, the nodes features need to be already in the NetworkX graph.
