### ISSUE TITLE
Loading PyG data

### ISSUE THREAD

**Issue by Frank-LIU-520** [pyg-team/pytorch_geometric#649]
## 🐛 Bug
When I try to load the *pt  files in my MPNN code with pytorch 1.2.0 , there is the error. However evertything works fine when the pytorch 1.1.0.

Traceback (most recent call last):
  File "mpnn.py", line 50, in <module>
    train_dataset = Dataset(root='data-bin', mode='dev', transform=transform)
  File "E:\problem\bertopv\dataset.py", line 38, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "D:\Anaconda\envs\bertopv\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda\envs\bertopv\lib\site-packages\torch\serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
OSError: [Errno 22] Invalid argument

## To Reproduce

1.run your code with pytorch 1.10 and everything works fine
2.uninstall pytorch 1.10 , pyG and then reinstall pytorch 1.2.0  pyG 
3. rerun your code in pytorch 1.2.0 environment

## Environment

* OS:windows10 
* Python version:3.7
* PyTorch version: 1.2.0
* CUDA/cuDNN version:10.0
* GCC version:
* Any other relevant information:

## Additional context

(bertopv) E:\problem\bertopv>python -c "import torch;print(torch.__version__)
1.2.0
(bertopv) E:\problem\bertopv>python -c "import torch_geometric ; print(torch_geometric.__version__)
INFO:rdflib:RDFLib Version: 4.2.2
1.3.0

**Comment by rusty1s** [comment]
I do not think this is a PyTorch Geometric bug but rather a PyTorch bug. Have you tried recreating the `*.pt` files under PyTorch 1.2?

**Comment by Mario-Liu** [comment]
of course I tried at the first time , the same errors remain.
what's more, PyTorch 1.1.0 still can handel the *pt files created under PyTorch 1.2.0.

**Comment by rusty1s** [comment]
This seems strange, and I am not sure how I can help you. Can you generally save and load objects via torch.save and torch.load respectively?

**Comment by Mario-Liu** [comment]
Just as you thought,  Under PyTorch 1.2,there is the problem:
>>> import torch
>>> torch.load('./data_dev.pt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\bertopv\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda\envs\bertopv\lib\site-packages\torch\serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
OSError: [Errno 22] Invalid argument

And under PyTorch 1.1,everything is ok:
>>> import torch
>>> torch.load('./data_dev.pt')
(Data(edge_attr=[47600974, 40], edge_index=[2, 47600974], pos=[2156474, 3], x=[2156474, 46], y=[99776, 12]), {'x': tensor([      0,      20,      40,  ..., 2156426, 2156449, 2156474]), 'edge_index': tensor([       0,      400,      800,  ..., 47599820, 47600349, 47600974]), 'edge_attr': tensor([       0,      400,      800,  ..., 47599820, 47600349, 47600974]), 'y': tensor([    0,     1,     2,  ..., 99774, 99775, 99776]), 'pos': tensor([      0,      20,      40,  ..., 2156426, 2156449, 2156474])})

However, what should I do the next? T.T

**Comment by rusty1s** [comment]
I mean, does something like
```python
torch.save(torch.rand(100, 100), ...)
torch.load(...)
```
work for you in PyTorch 1.2?

**Comment by rusty1s** [comment]
This can also be a memory issue.

**Comment by Mario-Liu** [comment]
Yes,it works for me in PyTorch 1.2.

>>> torch.save(torch.rand(100,100),'./tmp.pt')
>>> torch.load('./tmp.pt')
tensor([[0.4196, 0.1025, 0.8305,  ..., 0.0634, 0.1148, 0.6569],
        [0.4304, 0.4405, 0.0012,  ..., 0.1615, 0.6157, 0.8861],
        [0.3562, 0.9105, 0.2570,  ..., 0.0806, 0.6714, 0.4613],
        ...,
        [0.5417, 0.0852, 0.7797,  ..., 0.5782, 0.5256, 0.1065],
        [0.8263, 0.9983, 0.0648,  ..., 0.9746, 0.4569, 0.4070],
        [0.4338, 0.6539, 0.1003,  ..., 0.2688, 0.5829, 0.1009]])

**Comment by Mario-Liu** [comment]
If that‘'s a memory issue, what should I do?

**Comment by rusty1s** [comment]
Mh, you could reduce the number of entries in your data object to see if you can save this reduced data object. On the otherside, the fact that it works in PyTorch 1.1 speaks against it :(

**Comment by Mario-Liu** [comment]
It seems that waiting for the PyTorch 1.3 update could be the right choice....... T.T

**Comment by antonioroberto1994** [comment]
Looks like force setting f_should_read_directly = False before this block in serialization.py

```python
f_should_read_directly = False # add this line
offset = f.tell() if f_should_read_directly else None
for key in deserialized_storage_keys:
    assert key in deserialized_objects
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
    if offset is not None:
        offset = f.tell()
```

seems to solve the problem
