### ISSUE TITLE
Training the network gives an edge_index error

### ISSUE THREAD

**Issue by Aster77** [pyg-team/pytorch_geometric#6500]
### 🐛 Trying to Train a GCN network on Custom Dataset gives an edge_index error suggesting that it isnt pointing to valid indices

I have been trying to use Pyg on my Custom Dataset and have used a simple pytorch dataloader to load Data objects(which contains a single graph for each data object). When I try to train the network, after a couple of batches I get the error
```



class GCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels, cached=True
                            )
        self.conv2 = GCNConv(hidden_channels, out_channels, cached=True,)

    def forward(self, x, edge_index, edge_weight=None):
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv1(x, edge_index, edge_weight).relu()
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index, edge_weight)
        return x
model = GCN(nfeat, nhid, nclass).to(device)
train_loader = DataLoader(dataset,batch_size=1,shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=4,shuffle=True)
criterion = CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)


def training(model,train_loader,test=True):
    for epoch in range(num_epochs):

        running_loss =0.0
        step=0
        for num, batch in enumerate((train_loader)):
            model.train()
            batch.to(device)
            optimizer.zero_grad()
            model.to(device)
            print(torch.max(batch.edge_index))
            print(torch.min(batch.edge_index))
            print(len(batch.x))
            pred=model(batch.x.float(),batch.edge_index)
            loss=criterion(pred,batch.y)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
```

```
ValueError: Encountered a CUDA error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 7) in your node feature matrix and try again.
```
Each graph contains unique num_nodes and edge_index. Ive made sure that the max index of edge_index is well within the num_nodes. Can anyone explain why this is an issue?

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.12.1
* OS: WSL
* Python version: 3.8

* How you installed PyTorch and PyG (`conda`, `pip`, source): conda

**Comment by rusty1s** [comment]
What happens if you run
```python
for data in dataset:
     data.validate()

**Comment by Aster77** [comment]
I tried running 
```
for data in dataset:
    data.validate(raise_on_error=True)
```
and I get no error and I tried running the program after running and get the same Value error as stated previously. 
I believe the error could be in the Dataloader because when I try to manually load each data object using a for loop, the network seems to work just fine. Can I know how the edge index changes with the node index when you call more than one graph(each data object stores a single graph and I am assuming each batch_size=number of graphs rather than num_nodes?)

**Comment by rusty1s** [comment]
Can you show me how a single `Data` object looks like for you? In general, `edge_index` gets increased by `num_nodes` for every example.

**Comment by Aster77** [comment]
So I have input features each stored on 
```
data = Data(x=all_feats,
                    edge_index=edge_index_new_1,
                    y=all_labels)
torch.save(data,save_path+str(index)+'.pt')
```
```
an example looks like this:Data(x=[61, 192], edge_index=[2, 2315], y=[61])
```
all_feats is of the size (num_nodes, num_features). My num_nodes changes for each graph (It can be anywhere from 2-300). My num_features remains constant (192 dim). My edge_index is of the size (2, num_edges), making sure the indices are not greater than num_nodes-1.

```
class My_Train(Dataset):
    def __init__(self, root, filename,  transform=None, pre_transform=None):
        """
        root = Where the dataset should be stored. This folder is split
        into raw_dir (downloaded dataset) and processed_dir (processed data).
        """

        self.filename = filename
        super(My_Train, self).__init__(root, transform, pre_transform)



    def len(self):
        
        reader_graph = os.listdir(self.root)
        return len(reader_graph)

    def get(self, idx):
        """ - Equivalent to __getitem__ in pytorch
            - Is not needed for PyG's InMemoryDataset
        """

        data = torch.load(os.path.join(self.root,
                                           f'data_{idx}.pt'))
        return data

dataset = My_Train(root='TestingUbuntu/data/ecapa/Train_10',
                        filename='Input Files/My_class_Train.csv')
train_loader = DataLoader(dataset,batch_size=1,shuffle=True)
```

**Comment by rusty1s** [comment]
Note that `data.x.size(0)` and `data.num_nodes` needs to match. You cannot have shared node features across graphs with different number of nodes.

**Comment by Aster77** [comment]
The node features are not shared across graphs but is it a problem if there are different num_nodes for each graph (each data object with no connection to other graphs)?


Also, in Dataset class

```
def len(self):
        
        reader_graph = os.listdir(self.root)
        return len(reader_graph)
```
Should this be the number of graphs or number of nodes in each graph?


I should mention that when I loaded the complete data in a list and used a dataloader as shown below, it seemed to work so I'm left confused. Could you please explain why this could be happening? Is it an an error with my dataset?

```
data_list=[Data(...),Data(...),....,Data(...)]
train_loader=DataLoader(data_list,batch_size=6)
```

**Comment by rusty1s** [comment]
Not sure what you mean with no connection to other graphs. Isn't this normal?

`len` should return the number of examples/graphs in your dataset.

**Comment by Aster77** [comment]
I just wanted to confirm that it was not a sub-graph. However, the original error does exist. I can try looking into what was wrong with the dataset class and update if I find a solution. Thank you so much for your help!

**Comment by aa-oo** [comment]
> I just wanted to confirm that it was not a sub-graph. However, the original error does exist. I can try looking into what was wrong with the dataset class and update if I find a solution. Thank you so much for your help!

Hello, I have met the same problem. Have you found the problem? How to solve it

**Comment by Aster77** [comment]
Actually I was able to solve my error as I had made a silly mistake on my code. I made the Dataloader to be as similar as possible to the pytorch dataloader and I have not been having issues. If you could post your code and the error you are facing, it would be helpful

**Comment by Aster77** [comment]
Also, I am new to Github, I am unsure on how to close my original issue as I have managed to solve it

**Comment by aa-oo** [comment]
ok,thank you!I've found the problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月1日(星期三) 凌晨5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pyg-team/pytorch_geometric] Training the network gives an edge_index error (Issue #6500)





 
Actually I was able to solve my error as I had made a silly mistake on my code. I made the Dataloader to be as similar as possible to the pytorch dataloader and I have not been having issues. If you could post your code and the error you are facing, it would be helpful
