### ISSUE TITLE
InMemoryDataset.collate depends on the order of the data

### ISSUE THREAD

**Issue by GianlucaDeStefano** [pyg-team/pytorch_geometric#6506]
### 🐛 Describe the bug

Hi all, I just noticed a behavior that I believe is a bug. 
I have multiple HeteroData objects, among which some miss a particular edge type. 
By collating them all together with the InMemoryDataset.collate function I obtain a graph that presents or not this edge type depending if this edge was present in the first HeteroData in the list. 

For example, executing:
```
import torch
from torch_geometric.data import HeteroData, InMemoryDataset

def get_heterodata():

    h = HeteroData()

    h['node_1'] = torch.arange(10)
    h['node_2'] = torch.arange(10)

    h['node_1', 'edge_1', 'node_2'].edge_index = torch.stack(
        (torch.randint(0, 9, (5,)), torch.randint(0, 9, (5,))), dim=1)
    h['node_1', 'edge_2', 'node_2'].edge_index = torch.stack(
        (torch.randint(0, 9, (5,)), torch.randint(0, 9, (5,))), dim=1)

    return h

h1 = get_heterodata()
h2 = get_heterodata()

del h2['node_1', 'edge_1', 'node_2']

res1 = InMemoryDataset.collate([h1,h2])
res2 = InMemoryDataset.collate([h2,h1])

print("Res1:")
print(res1)

print("Res2:")
print(res2)
```

Returns: 

```
Res1:
(HeteroData(
  node_1=[20],
  node_2=[20],
  (node_1, edge_1, node_2)={ edge_index=[5, 2] },
  (node_1, edge_2, node_2)={ edge_index=[5, 4] }
), defaultdict(<class 'dict'>, {'node_1': tensor([ 0, 10, 20]), 'node_2': tensor([ 0, 10, 20]), ('node_1', 'edge_1', 'node_2'): {'edge_index': tensor([0, 2])}, ('node_1', 'edge_2', 'node_2'): {'edge_index': tensor([0, 2, 4])}}))
Res2:
(HeteroData(
  node_1=[20],
  node_2=[20],
  (node_1, edge_2, node_2)={ edge_index=[5, 4] }
), defaultdict(<class 'dict'>, {'node_1': tensor([ 0, 10, 20]), 'node_2': tensor([ 0, 10, 20]), ('node_1', 'edge_2', 'node_2'): {'edge_index': tensor([0, 2, 4])}}))
```

As you can see, res1 contains the edge 'edge_1'  while res2 doesn't, even if the data fed into collate is exactly the same.
Should the order of the data objects matter in the final result of the collate function?

### Environment

* PyG version: b78a67ea13a1096ba20071957be5acb9b790f81d (installed from source)
* PyTorch version: 1.13.1
* OS: IOS Ventura 13.1
* Python version: 3.9.6
* CUDA/cuDNN version: \
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): 2.1.0

**Comment by rusty1s** [comment]
Currently, collating is only well-defined if node types and edge types match. If you want to drop certain edge types, you can do it via
```
h2['node_1', 'edge_1', 'node_2'].edge_index = torch.empty(2, 0, dtype=torch.long)

**Comment by GianlucaDeStefano** [comment]
I see thanks! The problem was not dropping edges.  I encountered this problem because some of the graphs I am working with may not contain a particular type of edge, and this caused the collate function to delete them all. 

If this is the correct behavior, it may be worth pointing it out in the documentation.
