### ISSUE TITLE
Bipartite graph support for utils.dense_to_sparse

### ISSUE THREAD

**Issue by apt-get-nat** [pyg-team/pytorch_geometric#6507]
### 🚀 The feature, motivation and pitch

I have a nearly-dense bipartite graph (that is, most features in node set A are connected to most features in node set B), and so it is easiest for me to define the edge adjacency matrix as a dense, non-square matrix. However, the message passing class expects a sparse edge adjacency layout. The dense_to_sparse utility would seem to be ideal for this purpose, but it can only take square matrices (thus, is unhelpful for bipartite graphs).

### Alternatives

A way to implicitly request propagate to pass messages from every node in A to every node in B would be even better (storing fully connected graphs is very memory inefficient), but I know that pyg is meant for sparser graph constructions so this would likely be a feature that wasn't used very much by other people.

**Comment by rusty1s** [comment]
Thanks for this feature request, we should definitely work on this. Do you have interest in helping with this?

**Comment by apt-get-nat** [comment]
I'm not at all familiar with the back-end and code base for pyg yet, just using it and the documentation. I can try to help, though.

**Comment by rusty1s** [comment]
Fixed with https://github.com/pyg-team/pytorch_geometric/pull/6546.
