### ISSUE TITLE
Installing from source for PyTorch 2.0 nightly

### ISSUE THREAD

**Issue by andreimano** [pyg-team/pytorch_geometric#6515]
### 😵 Describe the installation problem

Hi, I've tried installing pyg 2.2.0 alongside PyTorch 2.0 (for `torch.compile` and `torch._dynamo`), but installing via conda or pip doesn't seem to work, therefore I've tried [installing from source](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#installation-from-source), but the following compilation error occurs while installing `torch-scatter` via pip:

`      csrc/version.cpp:41:53: error: no matching function for call to ‘c10::RegisterOperators::op(const char [28], int64_t (*)() noexcept)’
         41 | static auto registry = torch::RegisterOperators().op(
            |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
         42 |     "torch_scatter::cuda_version", &scatter::cuda_version);`

Is there any workaround for using pytorch geometric along with pytorch 2.0?
This is also related to the following issue: https://github.com/pyg-team/pytorch_geometric/issues/6131 .

### Environment

* PyG version: 2.2.0
* PyTorch version: 2.0
* OS: Ubuntu 22.04
* Python version: 3.10.9
* CUDA/cuDNN version: 11.7 / 8.6
* How you installed PyTorch and PyG (`conda`, `pip`, source): source
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter 2.1.0

**Comment by rusty1s** [comment]
Yes, curreutnly you also need to install `torch-scatter` and `torch-sparse` from latest master in this case, e.g., via:
```
pip install git+https://github.com/rusty1s/pytorch_scatter.git

**Comment by HekpoMaH** [comment]
Hi,

How did you manage to complete the installation. I am struggling to complete the installation on the `torch_geometric` package. All other packages (e.g. `torch`, `torch_scatter`) work well.

E.g.
![image](https://user-images.githubusercontent.com/8327849/226105469-6c3359ed-7180-42c4-9011-dfcf386430ca.png)
![image](https://user-images.githubusercontent.com/8327849/226105476-5106a54e-434e-448f-896d-c1ba36de8278.png)

Versions and paths:
![image](https://user-images.githubusercontent.com/8327849/226105541-4ae65542-3df6-496d-9e21-8a18f5c75936.png)
![image](https://user-images.githubusercontent.com/8327849/226105659-d82f7f96-0aea-4cc9-b146-8fc1bfcb5fbd.png)


CPATH
![image](https://user-images.githubusercontent.com/8327849/226105549-14395385-46a7-4e03-bd5a-a25955c652f6.png)

PATH
![image](https://user-images.githubusercontent.com/8327849/226105588-1dd2c4a5-d5f8-4b86-9fbb-4ed81f1e23cb.png)

LD_LIBRARY_PATH
![image](https://user-images.githubusercontent.com/8327849/226105596-5f4ff4ea-ed30-4a5a-a825-04d50daae531.png)

OS: Ubuntu 20.04 LTS,

**Comment by HekpoMaH** [comment]
I don't need them _right now_, but would appreciate trying if it can speed up one model.... conference deadlines are just around the corner.

**Comment by rusty1s** [comment]
I just pushed some major fixes to let PyG work with `torch.compile` (see https://github.com/pyg-team/pytorch_geometric/pull/6984). Here are some steps that should get you going:
* Install PyTorch 2.0
* Install `pip install git+https://github.com/pyg-team/pytorch_geometric.git`
* Run
  ```python
  import torch_geometric
  model = torch_geometric.compile(model)
  ```
