### ISSUE TITLE
The saved feature importance in explainer, has the x-axis labelled wrongly as Feature Label

### ISSUE THREAD

**Issue by amirtha255** [pyg-team/pytorch_geometric#6516]
### 🐛 Describe the bug

![Screenshot 2023-01-25 115534](https://user-images.githubusercontent.com/10433985/214628187-2d221580-b79b-4e96-a206-a791a75f70c5.png)

The y-axis label should have been 'feature label'

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
Thanks for reporting. The bug is related to pandas and an older pandas version (<1.5) works fine (see https://github.com/pandas-dev/pandas/issues/46129). 

Will fix it via https://github.com/pyg-team/pytorch_geometric/pull/6520
