### ISSUE TITLE
pyg-nightly installations fails (starting with 2.3.0.dev20230117)

### ISSUE THREAD

**Issue by jreniecki** [pyg-team/pytorch_geometric#6521]
### 😵 Describe the installation problem

The following command works for me:
`python3 -m pip install pyg-nightly==2.3.0.dev20230116`

But the next one fails
`python3 -m pip install pyg-nightly==2.3.0.dev20230117`

with the following message:
`Requested torch-geometric from https://artifactory.sourcevertex.net:443/api/pypi/pypi-virtual/packages/packages/80/d9/1b7387a4c2c49807d8c0ab8f91e6285f3ead12be5a25867615a11e937054/pyg-nightly-2.3.0.dev20230117.tar.gz#sha256=037c037dafed6aa8ef86b19a48a1ab7a06c5f4a18ae469828485ca993e840d16 has inconsistent name: expected 'pyg-nightly', but metadata has 'torch-geometric'                                                                `

Is this because of [PR6431](https://github.com/pyg-team/pytorch_geometric/pull/6431) ?

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Yeah, this is likely. Thanks for spotting. Will take a look.

**Comment by rusty1s** [comment]
Should be fixed with https://github.com/pyg-team/pytorch_geometric/pull/6531.
