### ISSUE TITLE
ImportError: cannot import name 'VirtualNode'

### ISSUE THREAD

**Issue by mgao97** [pyg-team/pytorch_geometric#6567]
### 🐛 Describe the bug

Hey! I have encountered the following question when I tried to add a virtual node to a pyg graph data:
`from torch_geometric.transforms import VirtualNode 
ImportError: cannot import name 'VirtualNode'`

### Environment

* PyG version: 2.0.3
* PyTorch version: 1.10.0
* OS: Linux
* Python version: 3.8
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
Try upgrading PyG `pip install -U torch_geometric`
