### ISSUE TITLE
GCNConv not working with example data

### ISSUE THREAD

**Issue by rkube** [pyg-team/pytorch_geometric#657]
## 🐛 Bug
GCNConv is not working properly with the example data

1. x = torch.tensor([[-1], [0], [1]], dtype=torch.float)
2. edge_index = torch.tensor([[0, 1, 1, 2],  [1, 0, 2, 1]], dtype=torch.long
3 .gcn = GCNConv(1,1)
4. gcn1.forward(x, edge_index)

4. results in an error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-95cf6e2a993a> in <module>
----> 1 gcn1.forward(x, edge_index)

~/.conda/envs/ml/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in forward(self, x, edge_index, edge_weight)
     98             self.cached_num_edges = edge_index.size(1)
     99             edge_index, norm = self.norm(edge_index, x.size(0), edge_weight,
--> 100                                          self.improved, x.dtype)
    101             self.cached_result = edge_index, norm
    102 

~/.conda/envs/ml/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py in norm(edge_index, num_nodes, edge_weight, improved, dtype)
     76         fill_value = 1 if not improved else 2
     77         edge_index, edge_weight = add_remaining_self_loops(
---> 78             edge_index, edge_weight, fill_value, num_nodes)
     79 
     80         row, col = edge_index

~/.conda/envs/ml/lib/python3.7/site-packages/torch_geometric/utils/loop.py in add_remaining_self_loops(edge_index, edge_weight, fill_value, num_nodes)
    105     if edge_weight is not None:
    106         assert edge_weight.numel() == edge_index.size(1)
--> 107         inv_mask = 1 - mask
    108         remaining_edge_weight = edge_weight[inv_mask]
    109         if remaining_edge_weight.numel() > 0:

~/.conda/envs/ml/lib/python3.7/site-packages/torch/tensor.py in __rsub__(self, other)
    323 
    324     def __rsub__(self, other):
--> 325         return _C._VariableFunctions.rsub(self, other)
    326 
    327     def __rdiv__(self, other):

RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

## Environment

* OS: linux-3.10.0=957.21.3.el7.x86_64
* Python version: Python 3.7.4
* PyTorch version: 1.2.0
* CUDA/cuDNN version: 10
* GCC version: pgcc 19.5-0 LLVM 64-bit target on x86-64 Linux -tp skylake 
PGI Compilers and Tools
Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.

**Comment by rusty1s** [comment]
Please update to PyG 1.3.1
