### ISSUE TITLE
How to split a dynamic pyg data according to edge attr and edge index?

### ISSUE THREAD

**Issue by mgao97** [pyg-team/pytorch_geometric#6574]
### 🚀 The feature, motivation and pitch

Do any functions support for the above request? 

If yes, please give links and some examples :)

**Comment by rusty1s** [comment]
There is a `data.edge_subgraph` method. Does that fulfill your needs?

**Comment by rusty1s** [comment]
If you are working with `TemporalData`, wouldn't it make more sense to utilize `TemporalData.train_val_test_split`? This correctly ensures that there will be no data leakage across splits.

**Comment by mgao97** [comment]
Thank you!

Good idea! But I just want to split edges with timestamps according to the timestamps serving as the edge attrs. 

I would appreciate it if you can share any suggestions that I can use for this problem.

**Comment by rusty1s** [comment]
Maybe I am misunderstanding, but can't you just do
```python
train_mask = data.t <= threshold
val_mask = data.t > threshold <= threshold 2
test_mask = data.t > threshold2

train_data = data[train_mask]
...
```

**Comment by EdisonLeeeee** [comment]
@rusty1s I think we can provide a method `data.time_subgraph`, which has the following functionality:
```python
data = ...
data.t = torch.tensor([0, 1, 2, 3, 4])

# case 1
data.time_subgraph(t=torch.tensor([0,1])) # return edges belonging to timestamp t=0 and t=1

# case 2
data.time_subgraph(min_t=0, max_t=2) # return edges belonging to the time span [0, 2]
```
WDYT?
