### ISSUE TITLE
GNN Explainer in the example file cannot work

### ISSUE THREAD

**Issue by ZihanChen1995** [pyg-team/pytorch_geometric#6579]
### 🐛 Describe the bug

Hi, I am running the `gnn_explainer.py` file in the [examples](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/gnn_explainer.py). However, when I try to load the explainer, the following error appears. (Since I am running the file on Google Colab, my torch version is `1.13.1+cu116`.)
```
explainer = Explainer(
    model=model,
    algorithm=GNNExplainer(epochs=200),
    explanation_type='model',
    node_mask_type='attributes',
    edge_mask_type='object',
    model_config=dict(
        mode='multiclass_classification',
        task_level='node',
        return_type='log_probs',
    ),
)

>>> 
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-7c4636ee1dc4>](https://localhost:8080/#) in <module>
----> 1 explainer = Explainer(
      2     model=model,
      3     algorithm=GNNExplainer(epochs=200),
      4     explanation_type='model',
      5     node_mask_type='attributes',

TypeError: __init__() got an unexpected keyword argument 'explanation_type'
```

I am not sure whether this issue is caused by PyG version, so I try to install PyG both from `wheels` and `source`. However, none of them work. Can you help me with this? Thank you!

```
# from source
!pip install git+https://github.com/pyg-team/pyg-lib.git
!pip install torch-scatter 
!pip install torch-sparse 
!pip install torch-geometric 

# from wheels
pip install pyg-lib torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.13.1+cu116.html
pip install torch-geometric
```

### Environment

* PyG version:
* PyTorch version: 1.13.1
* OS:
* Python version: 
* CUDA/cuDNN version: 116
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): Google Colab

**Comment by rusty1s** [comment]
For all explainer scripts, you currently need PyG from master, or look at the examples from the PyG 2.2 tag: https://github.com/pyg-team/pytorch_geometric/tree/2.2.0/examples
