### ISSUE TITLE
Conda package is missing `tabulate` dependency

### ISSUE THREAD

**Issue by amotta** [pyg-team/pytorch_geometric#6584]
### 🐛 Describe the bug

I've installed PyTorch Geometric with

```bash
NAME=debug
conda create --name $NAME python=3.9 numpy
conda install --name $NAME --channel pytorch pytorch cpuonly
conda install --name $NAME --channel pyg pyg
```

Then, following the "Introduction by Example" in the PyTorch Geometric docs, I created a `Dataset` with:
```python
from torch_geometric.datasets import TUDataset
dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES')
dataset
```

This prints `ENZYMES(600)`, as expected.

However, the call to `dataset.print_summary()` fails with the following backtrace:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amotta/.miniconda/envs/debug/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 309, in print_summary
    return str(self.get_summary())
  File "/home/amotta/.miniconda/envs/debug/lib/python3.9/site-packages/torch_geometric/data/summary.py", line 81, in __repr__
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

I am not very familiar with packaging for PyPI or conda, but I have noticed that
- `tabulate` is listed as a dependency in `setup.py`,
- but that `tabulate` is missing from the dependencies of the [conda packages](https://anaconda.org/pyg/pyg/files)

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.1
* OS: Linux 6.1.9
* Python version: 3.9.16
* CUDA/cuDNN version: cpu only
* How you installed PyTorch and PyG (`conda`, `pip`, source): see bug report
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This is to be expected. PyG comes with a lot of optional dependencies that are not installed by default in order to keep the amount of dependencies low.

**Comment by amotta** [comment]
Oh, I wasn't aware that this is common practice and the intended behavior.

My apologies for the false positive report. And thank you for explaining!
