### ISSUE TITLE
PyG CI failures:`test_cpu_affinity_neighbor_loader[1-loader_cores1]` & `test_profile`

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#6585]
### 🐛 Describe the bug

log attached
[pyg_failures.txt](https://github.com/pyg-team/pytorch_geometric/files/10581661/pyg_failures.txt)

### Environment

* PyG version: master branch build
* PyTorch version: 2.0
* CUDA version: 12

**Comment by LukeLIN-web** [comment]
```
        stats_list = []
        for epoch in range(5):
>           _, stats = train(model, data.x, data.edge_index, data.y)
E           TypeError: cannot unpack non-iterable float object
test/profile/test_profile.py:44: TypeError
```
This is a bug. You can remove the return value. 
Refer https://github.com/pyg-team/pytorch_geometric/pull/6555

**Comment by puririshi98** [comment]
i was using a very recent commit but updating it again this morning fixed it
