### ISSUE TITLE
Typo in docs/source/advanced/remote.rst

### ISSUE THREAD

**Issue by kimfalk** [pyg-team/pytorch_geometric#6649]
### 📚 Describe the documentation issue

There is a typo in the [remote](https://github.com/pyg-team/pytorch_geometric/blob/master/docs/source/advanced/remote.rst) doc. 

in line 66 `Implemented` is spelled `inmplementation`

### Suggest a potential alternative/fix

remove the `n` in `inmplementation`

**Comment by EdisonLeeeee** [comment]
Thanks for the catch. Do you have interest in sending a PR?

**Comment by kimfalk** [comment]
Created a PR: https://github.com/pyg-team/pytorch_geometric/pull/6651
