### ISSUE TITLE
Help on graph classification with edge attr

### ISSUE THREAD

**Issue by chengxiao19961022** [pyg-team/pytorch_geometric#668]
## ❓ Questions & Help

Sorry to bother you. The graph data is formed of node attr and edge attr. I wonder which layer is appropriate for those graph classification tasks(are there any demos?). For example, does GCNConv encode edge attr into network learning?

**Comment by rusty1s** [comment]
The `GCNConv` can only make use of one-dimensional edge weights. If you want to integrate multi-dimensional edge features, you should have a look at the `NNConv`, `GMMConv` or `SplineConv`. We provide examples [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mnist_nn_conv.py) and [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mnist_graclus.py).

**Comment by chengxiao19961022** [comment]
Thanks. When assigning the weight of each edge using `GCNConv`, can I use `data.edge_attr` directly or I need to construct a weight function in `forward` method.

**Comment by rusty1s** [comment]
You can pass it to the forward function:
```python
conv(data.x, data.edge_index, data.edge_attr)
```

**Comment by rusty1s** [comment]
I don't think we have an example for graph classification with one-dimensional edge weights, but we have a few with multi-dimensional edge features, e.g., https://github.com/pyg-team/pytorch_geometric/blob/master/examples/pna.py#L52-L60.

In general, you can simply swap out the operator with `GCNConv`, and replace the multi-dimensional edge features with one-dimensional ones.
