### ISSUE TITLE
Getting attention weights of ONLY one node and its neighbors. k_hop_subgraph producing 'weird' result

### ISSUE THREAD

**Issue by amjass12** [pyg-team/pytorch_geometric#6687]
### 🐛 Describe the bug

Hi!

I am trying to get attention scores for node 'x' and ALL node that node x is connecting to. I am doing this in this way (and any easier way to do this is greatly appreciated) but think i have come across a bug:

```
idx = k_hop_subgraph(0, 1, torch_graph.edge_index, relabel_nodes=True)[0]
x = torch_graph.x[idx]# subset node features
y = k_hop_subgraph(0, 1, torch_graph.edge_index, relabel_nodes=True)[1]# node 0 and ONLY one-hop away(neighbors only)
model.gat_conv1(x, y, return_attention_weights=True)[1][1]

```

The shape of the edges is 100k (directed) so 50000 unique edges. Now this is confusing to me as node 0 connect to 368 other nodes, and it is only these nodes i want attention scores for (I want self attention for node 0 as well) so 369 weights in total. What is happening however, is that i am getting the subgraph for the edges for nodes that node x is connected and their immediate nodes. 

Reproducible example:
```
import torch
from torch.utils import k_hop_subgraph
import networkx as nx

edge_index = torch.tensor([[0, 0, 1, 2,3 ,4, 5], [1, 2, 3, 4, 0, 5, 6]])
edge_index = to_undirected(edge_index)
bla = k_hop_subgraph(0, 1, edge_index)
edge_pd = pd.DataFrame(bla[1].numpy().transpose(), columns=['source', 'target'])
graph = nx.from_pandas_edgelist(edge_pd, source='source', target='target').to_undirected()
print(graph.edges())
>>> EdgeView([(0, 1), (0, 2), (0, 3), (1, 3)])
```

as you can see from the reproducible example, when asking for a subgraph of node 0 only - 1 hop away, it has also provided the edge (3, 1) which is not intended. 

Is this a bug? I apologise if i have misunderstood something, but essentially what i need, is to access the attention score that node x is paying ONLY to its neighbours. thank you!

**Comment by amjass12** [comment]
Hi @rusty1s ,

thank you for the reply. 

Can you advise on how the edge_index should be re-indexed, as your approach works but can then no longer be input in to `model.gat_conv1(sub_node_features, sub_edges)` which throws the reindex error - `ValueError: Found indices in 'edge_index' that are larger than 10 (got 1949 ...etc`

The code used is:

```
mask = torch_graph.edge_index[1] == 1949  # All edges that point to node i
sub_edge_index = torch_graph.edge_index[:, mask]

node_features_idx = np.array(np.unique(sub_edge_index))
sub_node_features = final_node_features[node_features_idx]

```

`model.gat_conv1(sub_node_features, sub_edge_index, return_attention_weights=True)`

thank you!

**Comment by rusty1s** [comment]
Fair point, I think you can do the relabeling via
```python
sub_edge_index = ...
node_subset = sub_edge_index.unique()

node_mapping = torch.zeros(data.num_nodes, dtype=torch.long)
node_mapping[subset] = torch.arange(subset.size(0))
sub_edge_index = node_mapping[sub_edge_index]
```

**Comment by rusty1s** [comment]
By default, `GATConv` will add a self-loop to the graph, so it will basically add `(10, 10)` as edge to your graph (the 11th edge).

**Comment by rusty1s** [comment]
Happy to accept a PR to integrate such a function, e.g., `GATConv.get_attention_for_node()` or something similar.

**Comment by amjass12** [comment]
I think this is the confusion, because, weirdly - it has added 10 'self-loops' all with an attention score of 1.. this 11th node isn't part of the set?

And yes for sure, once this is resolved i am happy to write. a PR!

**Comment by rusty1s** [comment]
Ah, I see. That's because it treats the input as a homogeneous graph. I think you can also fix this by specifying `size=(10, 1)`.

**Comment by amjass12** [comment]
shape = (10, 1) for which variable? sorry for how silly i am being here - but neither the node features or the edge index have such a shape

**Comment by rusty1s** [comment]
There is a `size` argument in `GATConv.forward`.

**Comment by amjass12** [comment]
ok - thank you. and should the node_features matrix contain ONLY features for the 10 connections, or plus the node of interest as well?

currently it is of shape 11 - 10 connections, plus the node of interest.. creating a shape mismatch (but does not throw an error)

**Comment by amjass12** [comment]
Hi @rusty1s 

thank you for clarifying - After all this confusion, i re-read the paper and realised that this is indeed the case as the softmax is calculated over all nodes attending node i including node i itself - all attention scores (per column) in each head sum to one. I am satsified with this, so will generate a function and maybe put a pull request through. thanks for all of your help!!
