### ISSUE TITLE
Sending model to GPU causes a system crash

### ISSUE THREAD

**Issue by tonydavis629** [pyg-team/pytorch_geometric#6688]
### 🐛 Describe the bug

When I create a clean environment and install the latest torch and pytorch-geometric with pip, then attempt to send a model with both pytorch-geometric and torch.nn attributes to the GPU, it crashes my entire system. What's strange is that it only crashes if I call `torch.cuda.is_available()`, and only with a pip installation.

Steps to replicate:
In terminal:
```
conda create -n environment python=3.9
conda activate environment
pip install torch
pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
```

Minimal example that causes this crash for me:
```
import torch
from torch.nn import Sequential, Linear, ReLU, GRU
from torch_geometric.nn import NNConv

class example(torch.nn.Module):
    def __init__(self, dim):
        super(example, self).__init__()

        nn = Sequential(Linear(11, 128), ReLU(), Linear(128, dim * dim)) # 11 edge features
        self.conv = NNConv(dim, dim, nn, aggr='mean', root_weight=False)
        self.gru = GRU(dim, dim)

dim = 64

model = example(dim)
print(torch.cuda.is_available())
device = torch.device('cuda')
model.to(device)
```
If I do not call `torch.cuda.is_available()`, the code runs normally. 

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.1
* OS: Ubuntu 22.04
* Python version: 3.9.16
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): No crash occurs with conda installation. `conda install pyg pytorch pytorch-cuda=11.7 -c pytorch -c nvidia -c pyg`

**Comment by rusty1s** [comment]
This is unexpected. Does this work for normal PyTorch modules? Is there any error message?

**Comment by tonydavis629** [comment]
I have no issues with normal pytorch modules only. There is no error message, my entire system crashes. I am using WSL2, I can't confirm if this happens in standalone Ubuntu. I have crash logs but I didn't see anything particularly out of the ordinary. https://filebin.net/h6zfmi8leaz0w6zr

**Comment by rusty1s** [comment]
Ok. Can you confirm that `torch-scatter` works for you:
```python
import torch
from torch_scatter import scatter_max

src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]]).cuda()
index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]]).cuda()

out, argmax = scatter_max(src, index, dim=-1)
```

**Comment by tonydavis629** [comment]
This code works just fine for me. My crash occurs only after a model with pyg + torch attributes is sent to the GPU. The crash actually occurs when the memory is cleared after the script ends.

**Comment by rusty1s** [comment]
Mh, I am sadly not sure what might cause this, never experienced this before. Is it possible to reverse engineer this, e.g., which children module in `model.to(device)` produces the issue? Does the same happen for other GNN layers?

**Comment by tonydavis629** [comment]
I hadn't tested other layers. This was the most minimal example I found which caused this error. Maybe you can confirm if you can reproduce this? Otherwise, it might be a quirk with my system or WSL.

**Comment by rusty1s** [comment]
I cannot reproduce this, this works just fine on my end.

**Comment by tonydavis629** [comment]
Just to confirm, that is with PyG version: 2.2.0 and PyTorch version: 1.13.1 installed through pip? I'm curious because for me it works fine with a conda installation.

**Comment by rusty1s** [comment]
Yeah, using the exact same setup.

**Comment by tonydavis629** [comment]
Ok must be a problem on my end. I will close the issue.
