### ISSUE TITLE
NeighborLoader returned batch does not have n_id attribute

### ISSUE THREAD

**Issue by qwu01** [pyg-team/pytorch_geometric#6705]
### 🐛 Describe the bug

In the dataloader documentation: it is possible to get original node index by n_id
```
loader = NeighborLoader(data, ...)
sampled_data = next(iter(loader))
print(sampled_data.n_id)  # Global node index of each node in batch.
```
But in the latest version it raise AttributeError: 'GlobalStorage' object has no attribute 'n_id'.

To reproduce:
``` python:
from torch_geometric.datasets import Planetoid
from torch_geometric.loader import NeighborLoader
import torch_geometric
import torch


# print(torch_geometric.__version__)
# print(torch.__version__)

data = Planetoid('data/temp/', name='Cora')[0]



loader = NeighborLoader(
    data,
    num_neighbors=[10] * 2,
    batch_size=5,
    input_nodes=data.train_mask,
)
for sampled_data in loader:
    # print(sampled_data.batch_size)
    print(sampled_data.n_id)
    break

```

```
Traceback (most recent call last):
  File "E:\tmp\.venv\lib\site-packages\torch_geometric\data\storage.py", line 62, in __getattr__
    return self[key]
  File "E:\tmp\.venv\lib\site-packages\torch_geometric\data\storage.py", line 85, in __getitem__
    return self._mapping[key]
KeyError: 'n_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tmp\temp.py", line 22, in <module>
    print(sampled_data.n_id)
  File "E:\tmp\.venv\lib\site-packages\torch_geometric\data\data.py", line 428, in __getattr__
    return getattr(self._store, key)
  File "E:\tmp\.venv\lib\site-packages\torch_geometric\data\storage.py", line 64, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'n_id'
```

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.1+cu117
* OS: windows
* Python version: 3.10.8
* CUDA/cuDNN version: 117
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
It just got recently added to PyG and is not been released yet. You need to install PyG from master or from nightly (see README) to use it.

**Comment by qwu01** [comment]
thanks, found this: https://github.com/pyg-team/pytorch_geometric/discussions/3528

**Comment by LukeLIN-web** [comment]
> It just got recently added to PyG and is not been released yet. You need to install PyG from master or from nightly (see README) to use it.

Do all datasets have n_id? or the datasets before this version still don't have `n_id`.

**Comment by EdisonLeeeee** [comment]
The attribute `n_id` is only available for batches obtained through the `NeighborLoader` and is independent of the specific dataset.
