### ISSUE TITLE
ImportError: cannot import name 'RootedEgoNets'

### ISSUE THREAD

**Issue by mgao97** [pyg-team/pytorch_geometric#6725]
### 🐛 Describe the bug

from torch_geometric.transforms import RootedEgoNets

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
Which PyG version are you using? This should work for PyG>=2.1

**Comment by mgao97** [comment]
Got it. Thank you!
