### ISSUE TITLE
When an empty graph (no nodes/edges) is at the end of the list of being placed into a data-loader, obtaining graph embeddings 'misses' it off

### ISSUE THREAD

**Issue by davidireland3** [pyg-team/pytorch_geometric#6737]
### 🐛 Describe the bug

I used the following code to obtain a batch of graphs:
`states = next(iter(DataLoader([s for s, _, _, _, _ in batch], batch_size=self.batch_size))).to(self.device)`. 

However, if the last graph in `batch` is empty, i.e. with no nodes or edges, then the `states.batch` object is a tensor of int's from `0` to `batch_size - 2` (this is not totally unexpected, if the empty graph is somewhere in the middle of the list then the element it is in the list is also missing from batch). However, when I use `global_add_pool(x, batch)` (where `x` are the returned node embeddings from a GNN layer) it returns only a tensor of size `batch_size - 1`, i.e. the empty graph's graph embedding is missing. I have previously tested the code to see what would happen when using this with an empty graph, and it correctly returns a zero-vector for the empty graph, but this seems to be an edge case that fails when the empty graph is last in the data loader. Is this behaviour intended or not? 

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.12.1
* OS: Mac
* Python version: 3.9
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda

**Comment by rusty1s** [comment]
All `global_*_pooling` methods come with a `size` argument, so you can fix this via
```python
out = global_add_pool(data.x, data.batch, size=data.batch_size)
