### ISSUE TITLE
Character substitution "-" for "_" in pip version of pyg installation instructions

### ISSUE THREAD

**Issue by agrubertx** [pyg-team/pytorch_geometric#6764]
### 🐛 Describe the bug

Hi PyG devs,

I wanted to let you know that I was unable to complete step 3 of the PyG installation using pip and the instructions here:  [https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html#installation-via-pip-wheels](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html#installation-via-pip-wheels).

In particular, running 

`pip install pyg-lib torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-1.13.0+cu117.html`

produced the following error:

`Looking in links: https://data.pyg.org/whl/torch-1.13.0+cu117.html`
`ERROR: Could not find a version that satisfies the requirement pyg-lib (from versions: none)`
`ERROR: No matching distribution found for pyg-lib`

Looking manually into this webpage, I was able to circumvent this error by substituting "pyg_lib" for "pyg-lib" in the pip install command, which completed the installation.  Is it possible that there was a transposition error which occurred during the documentation process?  Will you please double-check that page to make sure that others do not have the same issue?

Thanks,
Anthony

### Environment

* PyG version:  2.2.0
* PyTorch version:  1.13.0+cu117
* OS: RHEL 7.9 (Maipo)
* Python version: 3.9.13
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source):  pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Interesting. In my experience, `pip` can substitute `-` with `_` if necessary (it seems to be doing this already for `torch-scatter` and `torch-sparse`?). I have no problem on my end, but it would be also fine to me to just replace the installation command with `pyg_lib torch_scatter torch_sparse`.
