### ISSUE TITLE
Download data set error

### ISSUE THREAD

**Issue by Waterpine** [pyg-team/pytorch_geometric#678]
## ❓ Questions & Help

I am confronted with a problem that ssl.CertificateError: hostname 'ls11-www.cs.uni-dortmund.de' doesn't match 'ls11-www.cs.tu-dortmund.de'

I use the command: pip install --upgrade torch-geometric

The information is shown below:
Requirement already up-to-date: torch-geometric in /data2/bs/iclr/lib/python3.5/site-packages (1.3.1)
Requirement already satisfied, skipping upgrade: plyfile in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (0.7)
Requirement already satisfied, skipping upgrade: scikit-learn in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (0.21.3)
Requirement already satisfied, skipping upgrade: networkx in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (2.3)
Requirement already satisfied, skipping upgrade: scipy in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (1.3.1)
Requirement already satisfied, skipping upgrade: numpy in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (1.17.2)
Requirement already satisfied, skipping upgrade: googledrivedownloader in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (0.4)
Requirement already satisfied, skipping upgrade: rdflib in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (4.2.2)
Requirement already satisfied, skipping upgrade: h5py in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (2.10.0)
Requirement already satisfied, skipping upgrade: pandas in /data2/bs/iclr/lib/python3.5/site-packages (from torch-geometric) (0.24.2)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /data2/bs/iclr/lib/python3.5/site-packages (from scikit-learn->torch-geometric) (0.13.2)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in /data2/bs/iclr/lib/python3.5/site-packages (from networkx->torch-geometric) (4.4.0)
Requirement already satisfied, skipping upgrade: pyparsing in /data2/bs/iclr/lib/python3.5/site-packages (from rdflib->torch-geometric) (2.4.2)
Requirement already satisfied, skipping upgrade: isodate in /data2/bs/iclr/lib/python3.5/site-packages (from rdflib->torch-geometric) (0.6.0)
Requirement already satisfied, skipping upgrade: six in /data2/bs/iclr/lib/python3.5/site-packages (from h5py->torch-geometric) (1.12.0)
Requirement already satisfied, skipping upgrade: pytz>=2011k in /data2/bs/iclr/lib/python3.5/site-packages (from pandas->torch-geometric) (2019.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in /data2/bs/iclr/lib/python3.5/site-packages (from pandas->torch-geometric) (2.8.0)

I am wondering how to solve this problem? Thanks!

**Comment by rusty1s** [comment]
Can you download the datasets from [here](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets), *e.g.*, [ENZYMES](https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/ENZYMES.zip)?

**Comment by Waterpine** [comment]
Sure, however, I want to download the datasets by code automatically. Because I also want to use 3D cloud points data sets. I do not know where to download 3D cloud points data sets which are contained in the library. Thanks!

**Comment by rusty1s** [comment]
Can you download other datasets or is this a `TUDataset` only bug? As far as I know, `TUDataset` does not provide any 3D point cloud datasets.
