### ISSUE TITLE
Different node representations for GCN node classification on Fully connected graph!!!

### ISSUE THREAD

**Issue by anilesec** [pyg-team/pytorch_geometric#679]
## ❓ Questions & Help

I am doing a node classification using GCN(https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GCNConv), based on the formulation it is expected that all the nodes have the same representation for a fully connected graph. But they are different. I am not able to understand why it is different?

I have tried on a small graph of size 4, final representation looks like below
tensor([[0.4232, 0.0000],
        [0.5726, 0.0000],
        [0.4293, 0.0000],
        [0.2699, 0.0000]],

They are all different. As per my understanding they should be same. Can you please give your opinion.
notebook attached for code reference:
[GCNConv.zip](https://github.com/rusty1s/pytorch_geometric/files/3596335/GCNConv.zip)

Best,
Anil

**Comment by rusty1s** [comment]
Representations are only the same if node features are also equal, which I do not think they are:
```python
loc = torch.FloatTensor(4, 2).uniform_(0, 1)
```
In addition, `edge_index = torch.ones((2, num_edges * 2), dtype=torch.long)` does not encode a fully connected graph!

**Comment by anilesec** [comment]
Thanks for the response!
Yes, node features are different but since the graph is fully connected, every node gets a contribution from every other node, this means that even if the node features are different, it does not matter as parameters are shared across.

Regarding the edge index, should they be a matrix of node ids pairs? In my case its just matrix of ones of size(2, num_edges * 2)

**Comment by rusty1s** [comment]
Yes, it needs to be a matrix with node id pairs of shape `[2, num_edges]`.

**Comment by rusty1s** [comment]
Yes, of course, I was too fast on this one. But `edge_index` is wrongly encoded nonetheless.

**Comment by intello72** [comment]
I wanted to ask that GCNConv does give different node embeddings for a fully connected layer. Is that due to numerical computation error or is there some other reason?

**Comment by rusty1s** [comment]
There might exist some minor numerical instabilities, but overall the embeddings should be close to exact. Is this not what you are seeing?

**Comment by intello72** [comment]
Yes they are close to each other. The DenseGCNConv, gives the same embeddings, so I was wondering if there was some major difference between the 2 layers.

**Comment by rusty1s** [comment]
They should be identical (at least we test against that). The differences in output should be very minor at best (e.g., `atol=1e-6`), otherwise there is still something fishy going on. Feel free to share a reproducible example if possible.
