### ISSUE TITLE
Error of "indices out of edge_index" caused by the way of mini-batch on PairData

### ISSUE THREAD

**Issue by mgao97** [pyg-team/pytorch_geometric#6793]
### 🐛 Describe the bug

Hi! 

When I use the PairData batching according to the docs [advanced mini-batching](https://pytorch-geometric.readthedocs.io/en/latest/advanced/batching.html?highlight=pairdata#pairs-of-graphs) have encountered the following problem when I take the **batch.x_s** and **batch.edge_index_s** into a GNN model.

raise ValueError(
ValueError: Found indices in 'edge_index' that are larger than 22353 (got 42712). Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 22354) in your node feature matrix and try again.

Here, the key valid_dataloader is defined as 
`pair_data = PairData(edge_index_s, x_s, edge_index_t, x_t)
    datalist3 = [pair_data, pair_data]
    val_loader = DataLoader(datalist3, batch_size=128, shuffle=False, follow_batch=['x_s','x_t'])`

I am confused about the result, and the indices of edges should be no larger than the indices of the nodes in theory. Specifically, the **x**, and **edge_index** are from the outputs **subset2, and edge_index2** of the k_hop_subgraph function.

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.0
* OS: Linux
* Python version: 3.8.0
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
How do you pass your data to the GNN model? Note that if you are working on a bipartite graph, you have to input a tuple of feature matrices:
```python
conv((x_s, x_t), edge_index)

**Comment by mgao97** [comment]
Ok, thank you! Specifically, the info. of one pair of graph including two subgraphs subG1 and subG2 from the same graph G.
and I pass them by `model(node_index, batch.x_s[batch.x_s_batch], batch.edge_index_s, batch.x_t[batch.x_t_batch], batch.edge_index_t)` this way,  Should I input the corresponding feature matrices with tuples?

**Comment by mgao97** [comment]
> Ok, thank you! Specifically, the info. of one pair of graph including two subgraphs subG1 and subG2 from the same graph G. and I pass them by `model(node_index, batch.x_s[batch.x_s_batch], batch.edge_index_s, batch.x_t[batch.x_t_batch], batch.edge_index_t)` this way, Should I input the corresponding feature matrices with tuples?

btw, where the size of subG1 is not equal to that of subG2

**Comment by rusty1s** [comment]
Do you have a minimal toy example? I am not sure I fully understand your snippet, especially the `batch.x_s[batch.xs_batch]` calls - this will index the `batch.x_s` tensor wrongly.

**Comment by mgao97** [comment]
Thanks a lot! The following problem had been solved. But I am confused at how to make train/test set splitting on the object of PairData. Any tutorials?

**Comment by rusty1s** [comment]
Depends on what you wanna do. Do you wanna split single `PairData` instances or a dataset of `PairData` objects?

**Comment by mgao97** [comment]
The latter

**Comment by rusty1s** [comment]
In that case, I would recommend to shuffle your list of data objects and then just:
```
test_dataset = dataset[:50]
val_dataset = dataset[50:100]
train_dataset = dataset[100:]
```
(or similar).

**Comment by mgao97** [comment]
Ok, thank you so much, so I need to split it manually.
