### ISSUE TITLE
Add new heterophilous datasets

### ISSUE THREAD

**Issue by OlegPlatonov** [pyg-team/pytorch_geometric#6794]
### 🚀 The feature, motivation and pitch

Hi! A recent [paper](https://arxiv.org/abs/2302.11640) found some issues with popular heterophilous graph datasets such as squirrel and chameleon and proposed several new datasets. It would be great to add them to PyG. The datasets are available [here](https://github.com/yandex-research/heterophilous-graphs).

**Comment by rusty1s** [comment]
This is a good feature request. Do you have interest in helping us to integrate those?

**Comment by rusty1s** [comment]
Added them via https://github.com/pyg-team/pytorch_geometric/pull/6846. Thanks for letting me know.
