### ISSUE TITLE
Dataset category 

### ISSUE THREAD

**Issue by LukeLIN-web** [pyg-team/pytorch_geometric#6801]
### 🚀 The feature, motivation and pitch

https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html 

I want to know what is the biggest node classification dataset in PyG. But it is difficult.
It would be better if I could know **whether a  dataset is hetero**.  
Now it seems random, without an order.

**Comment by rusty1s** [comment]
I agree. We just started to provide better grouping as part of the documentation (see, e.g., `utils/__init__.py`). We can definitely do the same for all the datasets.
