### ISSUE TITLE
Attempted to use an uninitialized parameter

### ISSUE THREAD

**Issue by chrisn-pik** [pyg-team/pytorch_geometric#6827]
### 🐛 Describe the bug

When trying to access the params of a model using GATConv and edge dims I get an error: "Attempted to use an uninitialized parameter", even though I already did a forward pass. In case of SAGEConv and not using edge features the error message does not occur. The full code to reproduce the issue:

```python
from torch_geometric.nn import SAGEConv, GATConv

import torch
from torch_geometric.datasets import FakeDataset
dataset = FakeDataset(1, edge_dim=3)
data = dataset[0]


class GNN_with_edge_dim(torch.nn.Module):
    def __init__(self, hidden_channels=64):
        super().__init__()
        self.conv1 = GATConv((-1, -1), hidden_channels, edge_dim=3)

    def forward(self, x, edge_index, edge_attr):
        x = self.conv1(x, edge_index, edge_attr).relu()
        return x


class GNN_without_edge_dim(torch.nn.Module):
    def __init__(self, hidden_channels=64):
        super().__init__()
        self.conv1 = SAGEConv((-1, -1), hidden_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index).relu()
        return x


model_wo_edge_dim = GNN_without_edge_dim()
model_with_edge_dim = GNN_with_edge_dim()

with torch.no_grad():
    out_wo_edges = model_wo_edge_dim(data.x, data.edge_index)
    out_with_edges = model_with_edge_dim(
        data.x, data.edge_index, data.edge_attr)

total_params = sum([param.nelement()
                   for param in model_wo_edge_dim.parameters()])
total_params = sum([param.nelement()
                   for param in model_with_edge_dim.parameters()])
```

The final line throws the following error message:
```
Attempted to use an uninitialized parameter in <method 'numel' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions
 
ValueError: Attempted to use an uninitialized parameter in <method 'numel' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions
```
The problem occurs for homogeneous and heterogeneous graphs. Perhaps the issue is related to: #3640.

### Environment

* PyG version: 2.2.0 (torch-geometric)
* PyTorch version: 1.13.1
* OS: MacOS
* Python version: Python 3.10.9
* CUDA/cuDNN version: no
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda and pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): reproduced the issue on Linux with Python 3.10.0

**Comment by rusty1s** [comment]
I can reproduce this. The issue is that you are initializing your operator as bipartite `(-1, -1)`, but you pass in a single feature matrix tensor. This resolves in `lin_dst` being undefined. You can fix it via `GATConv(-1)` or by calling the model via `conv((data.x, data.x), edge_index, edge_attr)`.

**Comment by chrisn-pik** [comment]
Thank you very much for your quick and fast help! That's great. However, I am still wondering why the error occurs for GATConv and not SAGEConv. Shouldn't it be consistent?

**Comment by rusty1s** [comment]
Not necessarily. In `SAGEConv`, we use both neighbor transformation and learnable skip-connection, independent of whether we are operating in a bipartite graph or not. The same does not hold true for `GATConv`, since in a non-bipartite graph, we transform neighbors and central root node the same (as it is done by definition).

**Comment by chrisn-pik** [comment]
Thank you very much for the explanation!
