### ISSUE TITLE
GraphGym dataloader `persistent_workers` option

### ISSUE THREAD

**Issue by RemyLau** [pyg-team/pytorch_geometric#6842]
### 🚀 The feature, motivation and pitch

I'm using GraphGym to conduct a lot of my experiments. However, I noticed that currently, there is no way to turn on the `persistent_workers=True` option in the [`get_loader`](https://github.com/pyg-team/pytorch_geometric/blob/0c2e736f26b80f3914e3d4509b3a3b369321c019/torch_geometric/graphgym/loader.py#L248) function, which is used by the [`creater_loader`](https://github.com/pyg-team/pytorch_geometric/blob/0c2e736f26b80f3914e3d4509b3a3b369321c019/torch_geometric/graphgym/loader.py#L304) function to create data loaders for downstream tasks. I'm wondering if it is a good idea to implement some mehcanisms to allow setting `persistent_workers=True`. For example, in the [`LightningDataModule`](https://github.com/pyg-team/pytorch_geometric/blob/0c2e736f26b80f3914e3d4509b3a3b369321c019/torch_geometric/data/lightning/datamodule.py#L27), `persistent_workers` is automatically set to `True` if the specified number of workers is positive:

https://github.com/pyg-team/pytorch_geometric/blob/0c2e736f26b80f3914e3d4509b3a3b369321c019/torch_geometric/data/lightning/datamodule.py#L45-L46

I have noticed that enabling `persistent_worker=True` results in ~20% shortening of total runtime and thus would really love to have the option to enable this from the GraphGym API!

**Comment by rusty1s** [comment]
This is a good idea. We should probably just set `persistent_workers=num_workers>0` here as well. Do you mind making a short PR for this?
