### ISSUE TITLE
The problem of obtaining the attention parameter of GAT

### ISSUE THREAD

**Issue by vegetablelearning** [pyg-team/pytorch_geometric#6861]
### 📚 Describe the documentation issue

After training the GAT model, I want to get the corresponding attention parameter of the model, but I can't find the corresponding method in the document. If you can help me solve this problem, I would like to thank you very much

**Comment by EdisonLeeeee** [comment]
You can just set `return_attention_weights=True` during forward of `GATConv`, see: https://github.com/pyg-team/pytorch_geometric/blob/29b20796d9e3fca1662029d1083d508634b7593e/torch_geometric/nn/conv/gat_conv.py#L179-L181

**Comment by vegetablelearning** [comment]
Thank you very much for your answer. The problem has been solved.

**Comment by gsk1692** [comment]
Hello, just a small query regarding the extraction of attention_weights.
I am able to extract the attention weights when I am designing my own network architecture using `GATConv` or `GATV2Conv`. But, I wanted to simplify the prototype code a bit further by just invoking the GAT model in `torch_geometric.nn.models.GAT`. If we are using this default model, how can we extract the attention weights? Specifying the `return_attention_weights` to true while calling the model does not return the weights.
Could you please assist me in using the default GAT model to extract the attention weights? Thanks!

**Comment by rusty1s** [comment]
I am afraid this is currently not possible :( In this case, I think it makes more sense to build your `GAT` model from scratch with calling `GATConv(return_attention_weights=True)` on the desired layers.

**Comment by gsk1692** [comment]
Oh that's sad!
Thanks for the info anyways!
