### ISSUE TITLE
How to find a alternative of dgl.dataloading.MultiLayerFullNeighborSampler in PyG

### ISSUE THREAD

**Issue by tjb-tech** [pyg-team/pytorch_geometric#6864]
### 🐛 Describe the bug

Dear author, I am translate a program written in dgl to PyG, but a problem occur: 
```python
def track_acc(g, args, device):

    sampler = dgl.dataloading.MultiLayerNeighborSampler(
                [int(fanout) for fanout in args.fan_out.split(',')])

    train_nid = torch.nonzero(g.ndata['train_mask'], as_tuple=True)[0]
    
    train_dataloader = dgl.dataloading.DataLoader(
        g, train_nid, sampler,
        batch_size=args.batch_size,
        shuffle=True, drop_last=False,
        num_workers=args.num_workers) 
```
May I ask whether I could use NeighborSampler to replace the MultiLayerNeighborSampler? If yes, how I could write the code. If no, may I ask what API I should use? 
Looking forward to your reply! 

### Environment

* PyG version: 
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
`torch_geometric.loader.NeighborLoader` with full-neighbor sampling is what you need. For eaxmple:
```python
loader = NeighborLoader(data, [-1, -1, -1], train_nid, 
                        batch_size=1024, shuffle=True, drop_last=False, num_workers=4)
for batch in loader:
    train_on(batch)
```
which is equivalent to
```python
sampler = dgl.dataloading.MultiLayerFullNeighborSampler(3)
dataloader = dgl.dataloading.DataLoader(
    g, train_nid, sampler,
    batch_size=1024, shuffle=True, drop_last=False, num_workers=4)
for input_nodes, output_nodes, blocks in dataloader:
    train_on(blocks)

```

**Comment by tjb-tech** [comment]
> `torch_geometric.loader.NeighborLoader` with full-neighbor sampling is what you need. For eaxmple:
> 
> ```python
> dataloader = NeighborLoader(data, [-1, -1, -1], train_nid, 
>                         batch_size=1024, shuffle=True, drop_last=False, num_workers=4)
> for batch in dataloader :
>     train_on(batch)
> ```
> 
> which is equivalent to
> 
> ```python
> sampler = dgl.dataloading.MultiLayerFullNeighborSampler(3)
> dataloader = dgl.dataloading.DataLoader(
>     g, train_nid, sampler,
>     batch_size=1024, shuffle=True, drop_last=False, num_workers=4)
> for input_nodes, output_nodes, blocks in dataloader:
>     train_on(blocks)
> ```

Thanks for your reply, and may I ask if the following code: 
```python
sampler = dgl.dataloading.MultiLayerNeighborSampler(
                [int(fanout) for fanout in args.fan_out.split(',')])
dataloader = dgl.dataloading.DataLoader(
        g, train_nid, sampler,
        batch_size=args.batch_size,
        shuffle=True, drop_last=False,
        num_workers=args.num_workers)
```
is equivalent to
```python
dataloader = NeighborLoader(data, [int(fanout) for fanout in args.fan_out.split(',')], train_nid, 
                        batch_size=1024, shuffle=True, drop_last=False, num_workers=4)
```

**Comment by EdisonLeeeee** [comment]
Not. According to the [DGL doc](https://docs.dgl.ai/en/latest/generated/dgl.dataloading.MultiLayerFullNeighborSampler.html), `MultiLayerFullNeighborSampler` accepts `n_layers` rather than `fanouts`.

**Comment by EdisonLeeeee** [comment]
1. `NeighborSampler` is deprecated. You can directly use `NeighborLoader` instead.
2. DGL `MultiLayerNeighborSampler` accepts `int`, not `list`. Are you mentioning DGL `NeighborSampler`? If so, the code is equivalent.

**Comment by tjb-tech** [comment]
Yes, you are right. I found a mistake in my previous code. Thank you very much! 
Maybe the last question, may I ask: 
if we use `NeighborSampler`, we can iter the data like:  
```python 
for batch_size, n_id, adjs in train_loader:
        # `adjs` holds a list of `(edge_index, e_id, size)` tuples.
        adjs = [adj.to(device) for adj in adjs]
        optimizer.zero_grad()
        out = model(x[n_id], adjs)
        loss = F.nll_loss(out, y[n_id[:batch_size]])
        loss.backward()
        optimizer.step()
```
but if we use `NeighborLoader`, I can't find an example. Could you please help me?

**Comment by EdisonLeeeee** [comment]
You can simply do:
```python
    for batch in train_loader:
        optimizer.zero_grad()
        y = batch.y[:batch.batch_size]
        y_hat = model(batch.x, batch.edge_index.to(device))[:batch.batch_size]
        loss = F.cross_entropy(y_hat, y)
        loss.backward()
        optimizer.step()

```


FYI: https://github.com/pyg-team/pytorch_geometric/blob/master/examples/reddit.py

**Comment by tjb-tech** [comment]
> 

Amazing! Thank you very much for the patient reply! I just want to reproduce the GraphSAGE based on the PyG!
