### ISSUE TITLE
PyTorch Installation Issues

### ISSUE THREAD

**Issue by ThePopDiva93** [pyg-team/pytorch_geometric#6896]
### 😵 Describe the installation problem

Hello,

I am experiencing an issue with Pythorch and the GPU usage on a program called Fish-SVC after reinstalling it, I have tried to update and downgrade the CUDA drivers along with torch packages but with no success, the computer almost froze when collecting torch. Unfortunately, the issue still persists. I am not an expert at coding so I am relatively new

Could you please help me with this? Any assistance would be greatly appreciated.

Additional information for more context, the codes I used that don't work apparently but did previously:
pip uninstall torch torchaudio torchvisison -y
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
NVIDIA CUDA Development 11.0
My GPU: NVIDIA GeoForce GTX 1650
System: Windows 10
Python Version: 3.10
Pythorch Version:  C:\Users\MSI>conda list -f pytorch
# packages in environment at C:\ProgramData\miniconda3:
#
# Name                    Version                   Build  Channel
pytorch                   1.13.1          py3.10_cuda11.6_cudnn8_0    pytorch
However, when running pip3 show torch it says WARNING: Package(s) not found: torch

![why](https://user-images.githubusercontent.com/123522771/224476244-7e819255-d0cd-410a-85d2-fadd3cd834f1.png)

![I-](https://user-images.githubusercontent.com/123522771/224476278-8387df71-fde6-4312-8445-8a4718bca31e.png)

### Environment

* PyG version:
* PyTorch version: 1.13.1
* OS:
* Python version: 3.10
* CUDA/cuDNN version: 11.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Is this a PyG issue? This seems more related to PyTorch if I understand correctly. Maybe best to ask for help there?

**Comment by ThePopDiva93** [comment]
> 

I think it's definitely a PyTorch issue and Thank you very much :). I was wondering If I could move this thread to the following section. I'm new here so I don't know how Github works properly lol

**Comment by rusty1s** [comment]
I think you can just create the same issue in github.com/pytorch/pytorch rather than here.

**Comment by ThePopDiva93** [comment]
> I think you can just create the same issue in https://github.com/pytorch/pytorch rather than here.

Oh Alright :). I apologize for causing a distress and thank you for the help 👍
