### ISSUE TITLE
FPS / Radius slow

### ISSUE THREAD

**Issue by FraLotito** [pyg-team/pytorch_geometric#690]
## 🐛 Bug

Hi! I'm reproducing a paper using PyTorch Geometric and I'm using the Set Abstraction layer of Pointnet++ from the examples:

```
class SAModule(torch.nn.Module):
    def __init__(self, ratio, r, nn):
        super(SAModule, self).__init__()
        self.ratio = ratio
        self.r = r
        self.conv = PointConv(nn)

    def forward(self, x, pos, batch):
        idx = fps(pos, batch, ratio=self.ratio)
        row, col = radius(pos, pos[idx], self.r, batch, batch[idx],
                          max_num_neighbors=64)
        edge_index = torch.stack([col, row], dim=0)
        x = self.conv(x, (pos, pos[idx]), edge_index)
        pos, batch = pos[idx], batch[idx]
        return x, pos, batch
```

The point cloud in input has dimension 20k x 3. The execution of fps and radius takes 0.3s each. The whole execution of the forward step of my network is ~1.5s, while the execution of the forward step of the official implementation of the paper takes 0.1s. (with the SA implementation in PyTorch). Am I missing something? Why is it so slow?

**Comment by rusty1s** [comment]
Interesting. Do you operate on single point clouds or mini-batches? Both fps and radius can only utilize GPU acceleration in a mini-batch scenario, because we parallelize in the batch dimension across the number of blocks. Do you have a link to the respective repo? I would like to have a closer look on this one.

**Comment by FraLotito** [comment]
I use mini-batches of size 8 during training. Thanks!

**Comment by hudingchang** [comment]
The problem of FPS still exists. Thanks for your efforts @rusty1s .

**Comment by rusty1s** [comment]
A lot of speed-ups to FPS and radius have been integrated into `torch-cluster`. Feel free to re-open if there are still concerns.
