### ISSUE TITLE
Incompatible with torch 2.1.0-dev

### ISSUE THREAD

**Issue by lsnty5190** [pyg-team/pytorch_geometric#6900]
### 😵 Describe the installation problem

Dear Team.

I try to install `PyG` with the latest `torch` but it seems the current `PyG` is incompatible with `torch-2.1.0.dev` on cuda, which would raise the most common error: `undefined symbol: _ZN2at4_ops6narrow4callERKNS_6TensorElll`. Could u help me with this? Thanks!

### Environment

* PyG version: `latest`
* PyTorch version: `2.1.0.dev20230309+cu117`
* OS: `Ubuntu 20.04.5 LTS`
* Python version: `3.10.9`
* CUDA/cuDNN version: `cu117`
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu117` and `pip install torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html`
* Any other relevant information (*e.g.*, version of `torch-scatter`): `latest`

**Comment by rusty1s** [comment]
Note that for PyTorch >= 2.0, you currently need to install the extension packages from source. If you install PyG from latest master, these extensions (`torch-scatter`, `torch-sparse`, etc) are also no longer required, so simply installing PyTorch and running
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
should be sufficient.

**Comment by lsnty5190** [comment]
Thanks. The problem is resolved.
