### ISSUE TITLE
PointConv feature dimension

### ISSUE THREAD

**Issue by Magnetar99** [pyg-team/pytorch_geometric#691]
## 🐛 Bug

While running the Pointnet++ classification example, I observe that without the local.nn argument, PointConv returns features of dimension 6 i.e. the original point location and 3 more features based on local spatial location. I don't understand why is there local spatial location for only one point. Shouldn't it be for all the points in the group? 

For example,
If there are 1024 points initially and we run FPS to get 256 centroids, after PointConv I get a (256,6) feature space. whereas the pointnet++ Paper mentions that this should be 256xKx(3+C), where K can be flexible for each group.

Another issue that I've with the example is the edge_index calculation method in the SAModule, the edge_index is directly computed by radius function, whereas I don't think the radius function directly provides the edge_indexes, shouldn't the edge_index be torch.stack((idx[row], col))?

**Comment by rusty1s** [comment]
So, without the `local attribute`, input features are not transformed, and hence, each execution of it will add the relative spatial coordinates to the input features and apply a `max` pooling on all points in the group. Note that the `max` pooling is already integrated in our formulation, so the ordering is as follows:
1. Add relative spatial coordinates
2. Transform features locally (optional)
3. Apply max pooling over the set of neighbors
4. Transform features globally (optional)

Concerning `radius`, I do not see your point. the `radius` function calculates the edges from a set of points to another set of points, and results in a bipartite graph, which can be processed by `PointConv`.

**Comment by Magnetar99** [comment]
Thanks, @rusty1s . 
I had another question related to pointnet++, while transforming features locally, how does it handle the variable number of K for each group? 
Also, is it possible to modify Pointconv to use GATConv (or any other graph convolution network) instead of MLPs for local feature transformation?

**Comment by rusty1s** [comment]
It handles the variable number of `K` via an assignment matrix encoded in `edge_index`. It is possible to use `GATConv` instead of `PointConv`, just swapping the layers and adjusting the arguments/parameters should be sufficient.
