### ISSUE TITLE
LinkNeighborLoader crashed on Google Colab, even when the batch_size = 1.

### ISSUE THREAD

**Issue by ZihanChen1995** [pyg-team/pytorch_geometric#6925]
### 🐛 Describe the bug

Hi, I am trying to run an experiment with `HeteroData()` on Google Colab. First, I load the data and split it into train/val/test using `RandomLinkSplit`. Since my graph is quite large, then I use the `LinkNeighborLoader` for sampling. 

**However, whenever I run the `train_loader = LinkNeighborLoader()`, the session crashes after 2-3 seconds. The crash occurs even I set the batch size as 1. May I ask what causes this to happen, and what can I do to fix it? Thank you!**

---

Here are the code details:

```
import torch_geometric.transforms as T
import torch_geometric.utils as U

# RandomLinkSplit
transform = T.RandomLinkSplit(
    num_val=0.2,  
    num_test=0.1,  
    disjoint_train_ratio=0.3,  
    neg_sampling_ratio=2.0,  
    add_negative_train_samples=False, 
    edge_types=("A","a_to_b","B"),
    rev_edge_types=("B","b_to_a","A"), 
)

# generate train and validation
train_data, val_data, test_data = transform(data)
```
Training data looks like:
```
HeteroData(
  A={
    node_id=[51761],
    x=[51761, 768]  # text emb from BERT
  },
  B={
    node_id=[4913],
    x=[4913, 768]  # text emb from BERT
  },
  (A, a_to_a, A)={ edge_index=[2, 9653294] },
  (B, b_to_b, B)={ edge_index=[2, 3963422] },
  (A, a_to_b, B)={
    edge_index=[2, 16659],
    edge_label=[7139],
    edge_label_index=[2, 7139]
  },
  (B, rev_a_to_b, A)={ edge_index=[2, 29747] },
)
```
**And the following is where the crash occurs every time:**
```
from torch_geometric.loader import LinkNeighborLoader

# Define seed edges:
edge_label_index = train_data[("A", "a_to_b", "B")].edge_label_index
edge_label = train_data[("A", "a_to_b", "B")].edge_label

train_loader = LinkNeighborLoader(
    data=train_data,  
    num_neighbors=[10, 5],  
    neg_sampling_ratio=2.0,  
    edge_label_index=(("A", "a_to_b", "B"), edge_label_index), 
    edge_label=edge_label,
    batch_size=1,
    shuffle=True,
)
```

Since my System RAM is 83.5 GB, I guess the memory limit is not the cause? If so, may I ask is there a way to fix it?

Here is the `app.log` from Colab:

<img width="500" alt="Screenshot 2023-03-15 at 11 42 08 PM" src="https://user-images.githubusercontent.com/36064256/225508540-599c4466-0089-4dfb-ad92-f1f4a8f407a2.png">

<img width="515" alt="Screenshot 2023-03-16 at 12 00 09 AM" src="https://user-images.githubusercontent.com/36064256/225511001-dadb02cf-5dac-4135-8025-cf77aae8107a.png">

### Environment

* PyG version: 2.3.0
* PyTorch version: 1.13.1
* OS: Google Colab
* Python version: 3.9.16
* CUDA/cuDNN version: cu116
* How you installed PyTorch and PyG (`conda`, `pip`, source): !pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
* Any other relevant information (*e.g.*, version of `torch-scatter`): Google Colab Pro+ (System RAM 51.0 GB)

**Comment by rusty1s** [comment]
Thanks for reporting. Do you know or can debug where the crash is happening? Does it work for smaller-sized graphs?

**Comment by ZihanChen1995** [comment]
Hi Matthias thank for the reply. I spent some time on debugging. And I found two causes: 1. the input data (edge index) is not contiguous, which can be solved by `.contiguous()`. 2. The max index in the edge list is larger than the `x` (feature) row index, which is due to my negligence. Anyway, this issue is perfectly solved now. Thanks!

**Comment by ZihanChen1995** [comment]
BTW, since there are no hints or warnings when Colab crashes, some new users (start with Colab tutorials) might feel confused about it. 

**Do you want me to submit a PR?** I really enjoy using this library, and I'd love to contribute! Feel free to let me know if I can help.

**Comment by rusty1s** [comment]
Cool finding. I think we should ensure that the input is contiguous. Happy to take a PR in for that.

**Comment by ZihanChen1995** [comment]
> Cool finding. I think we should ensure that the input is contiguous. Happy to take a PR in for that.

Hi, I have added a precheck in RandomLinkSplit ([PR #6968](https://github.com/pyg-team/pytorch_geometric/pull/6968)). Feel free to let me know if anything further I can help!
