### ISSUE TITLE
pytorch2.0

### ISSUE THREAD

**Issue by peirisi** [pyg-team/pytorch_geometric#6926]
### 😵 Describe the installation problem

Hi,
The latest stable version of pytorch is 2.0 with cuda11.8
If I refer to this website“https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html”，there is no tip about how to install pyg for the latest version of pytorch.
If I try "conda install pyg -c pyg",then when i import torch_geometric 
![image](https://user-images.githubusercontent.com/47599755/225550128-d4792c29-8e4e-4e04-93a5-ce75520daa93.png)

### Environment

* PyG version:
* PyTorch version:2.0
* OS:ubuntu22.04
* Python version:3.10
* CUDA/cuDNN version:11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source):conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
We are in the process of releasing PyG 2.3 with full PyTorch 2.0 support very soon. For now, you can install it via
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
