### ISSUE TITLE
Bridging the gap between DGL and PyG

### ISSUE THREAD

**Issue by nowyouseemejoe** [pyg-team/pytorch_geometric#6979]
### 🚀 The feature, motivation and pitch

DGL and PyG are two popular deep learning libraries that specialize in working with graph-structured data. Both DGL and PyG have become go-to libraries for researchers and practitioners working on graph deep learning problems, and have a growing community of contributors and users.

I would like to request a new feature for PyG that allows for converting DGL graphs to PyG instances (e.g., `Data`). This would make it easier for users who have existing graph structures in DGL to switch to PyG without having to recreate their graphs from scratch.

In addition, it would be great to have a tutorial added to the documentation, demonstrating how to mitigate from DGL to PyG using this new feature. The tutorial could introduce some equivalent message and aggregation operations for these two libraries, helping users navigate the differences between them. With this new feature and tutorial, users can seamlessly transition between DGL and PyG, unlocking the full potential of graph deep learning for their projects.

**Comment by rusty1s** [comment]
I like the idea of providing conversion from DGL to PyG and vice versa. This should be pretty straightforward to get in. Do you have interest in contributing this?

**Comment by rusty1s** [comment]
I am not sure if @nowyouseemejoe has the intention to work on this. I think we could split the work into two parts:
* [ ] `from_dgl(dgl.Graph) -> data: Union[Data, HeteroData]`
* [ ] `to_dgl(Union[Data, HeteroData]) -> dgl.Graph`

such that both of you could work on this in parallel. WDYT?

**Comment by nowyouseemejoe** [comment]
@rusty1s Sorry. I'm afraid I don't have the time or expertise to contribute effectively to this at the moment. I appreciate your understanding.

Thank you @hbenedek . That would be great!

**Comment by tjb-tech** [comment]
> 
Highly recommend this idea! Maybe having this api, the issue like https://github.com/pyg-team/pytorch_geometric/issues/7017, which I recently meet, will not arise.

**Comment by akihironitta** [comment]
@Priyankagautam08 It's included in 2.4.0 release:
- https://pytorch-geometric.readthedocs.io/en/2.4.0/modules/utils.html#torch_geometric.utils.to_dgl
- https://pytorch-geometric.readthedocs.io/en/2.4.0/modules/utils.html#torch_geometric.utils.from_dgl
