### ISSUE TITLE
some quesion about Graph classify

### ISSUE THREAD

**Issue by LinzzMichael** [pyg-team/pytorch_geometric#698]
## ❓ Questions & Help

I am study the classify of Graph,  not the node classfiy , but I am confusing about the data.y, if I have two classes, can I only set the data.y to be 0 or 1. and is there some exampe how to classify graph not node in the expample code.

**Comment by rusty1s** [comment]
Yes, you can do this. An example can be found [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py).

**Comment by LinzzMichael** [comment]
thank you for your reply, I have read the Mutag_gin code, but I find it is not suitable for me, because its' node feature is a one hot encoding, but my node_feature is just a numerial number; so it perform poor, is there any other example to classify graph?

**Comment by rusty1s** [comment]
Well, you can use any node features you like. It is just that MUTAG does not provide any node features, so we create them by ourselves. The example code stays the same, it just expects a different number of input features.

**Comment by LinzzMichael** [comment]
ok, I got it , maybe my graph is not suitabe for it so it perfom poor,  another question about the MessagePassing class, when I read the document of the class, it says the 'update' function will perform the aggregation, but I saw the code, you perform the 'message' function, then the aggregation, finally the 'update' function, so is there two aggregation operate?
It seem I have so many quesion, thank you for reply me again!

**Comment by rusty1s** [comment]
No, the update function does not implement the aggregation. It takes the aggregated messages and combines them with the old feature information.

**Comment by LinzzMichael** [comment]
when I implement the GinConv or GCN conv to my dataset, my dataset is a 30 node graph with full connect, which means it has 900 edge, and each node has two feature, which is a umerial number, for exampe[0.1, 0.2], I got a confuse result that the train acc and test acc always be 50%,No more, no less, It just 50%, and I check my pred, it's not just both 1 or 0, it's random, but the correct pred always be the half of the total, I have stuck in this problem for many day, could you give me some advice?

**Comment by rusty1s** [comment]
I guess your model cannot learn anything when operating on fully-connected graphs. All node features should be (nearly) identical.
