### ISSUE TITLE
Some question I meet when I use PyG to implement my model created by tensorflow

### ISSUE THREAD

**Issue by YamingZ** [pyg-team/pytorch_geometric#700]
## ❓ Questions & Help
These days I want to achieve my model which created by tensorflow with PyG, but I meet some questions. As follows
- my model need weighted graph, which function can generate graph with edge_weight?
- if I use the node after FPS-operate as the final node of pooling-operate, which pooling function I can use?

**Comment by rusty1s** [comment]
What do you mean with "generate"? Do you want to generate graphs with edge weights, *e.g.*, based on an autoencoder? This is indeed possible with PyTorch, but we do not provide an example for this kind of task.
For obtaining global representations, you can use any global pooling function after FPS, *e.g.*, `global_max_pool` or `global_mean_pool`.
