### ISSUE TITLE
Can we learn edge weight in this way?

### ISSUE THREAD

**Issue by QijinYin** [pyg-team/pytorch_geometric#701]
suppose we had set the 
`edge_weight = nn.Parameter(t.Tensor(edge_num)))`
and we sent the edge_weight to the graph conv layer(such as SAGEConv) by 
`model.forward(x,edge_index,edge_weight)`

Can we learn meaningful edge weight?

In my experiment, trained edge_weight have very similar values to the original one. 

And if we set `edge_weight = nn.Parameter(t.ones(edge_num)))`,the learned edge_weight has very similar value for each edge.

Is there any mistake in this way?

**Comment by rusty1s** [comment]
Learning edge weights shouldn't be a problem. Everything is differentiable expect for `edge_index`. Maybe you are not optimizing them?

**Comment by QijinYin** [comment]
yes, edge weights can be learned,(the values of edge_weight are changed). But it seems in my experiment, the learned edge weights is not so meaningful since for each edge, the learned edge weight is similar. 
I'll try to figure it out.
