### ISSUE TITLE
Temporal version for elliptic bitcoin dataset

### ISSUE THREAD

**Issue by rishiagarwal2000** [pyg-team/pytorch_geometric#7010]
### 🚀 The feature, motivation and pitch

I am using the EllipticBitcoinDataset, and want to compare the performance of static GCNs (that do not change with time) with evolving GCNs. Hence, it would be useful if we have a temporal version for the dataset where a separate graph for each time step can be loaded.

**Comment by akihironitta** [comment]
Closing this issue as #7011 added `EllipticBitcoinTemporalDataset`. It should be available in the next 2.4.0 release.
