### ISSUE TITLE
Duplicate shared nodes

### ISSUE THREAD

**Issue by dhorka** [pyg-team/pytorch_geometric#702]
Hi,

I would like to know pygeometric provides any method to solve the following problem:

I have the following graph:

x = torch.tensor([[200], [100], [300]], dtype=torch.float)
edge_index = torch.tensor([[0, 0, 1, 1, 1, 2, 2],
                           [0, 1, 1, 0, 2, 2, 1]], dtype=torch.long)

As you can see there are 3 different neighrborhoods and each node belongs to more than one neighborhood. I would like to obtain a graph stucture where each node that belongs to more than one neighrborhood is duplicated. Instead of sharing the same node create a different node for each neighborhood. 

Is it possible to do this in pygeometric?

Thanks,

**Comment by dhorka** [comment]
Sorry :( I think that my explanation was a bit confusing. For me each node has its own neighborhood. In the previous case the neighborhood of node 0 it will be composed for: node 0 and 1. The neighborhood of node 1 will be composed for: node 0, node 1 and node 2. Finally the neighborhood of node 2 will be composed node 2 and node 1. As you can see node 1 is repeated in three different neighborhoods. I would like to duplicate the feature of this node as many times as neighborhoods have.

**Comment by rusty1s** [comment]
Ok, you can count the amounts a node occurs in a neighborhood, *e.g.*:
```python
row, col = edge_index
count = torch.bincount(col)
```
which would result in `[2, 3, 2]` in your case. You can than proceed to duplicate your node features via
```python
torch.repeat_interleave(x, count, dim=0)
```
