### ISSUE TITLE
data/collate TypedStorage is deprecated.

### ISSUE THREAD

**Issue by KevinCrp** [pyg-team/pytorch_geometric#7031]
### 🐛 Describe the bug

Hello

I have just upgraded PyTorch and Pyg to 2.0.0 and 2.3.0 version

When I launch a training I have the following warning, how can I fix it ?

```
torch_geometric/data/collate.py:145: UserWarning: TypedStorage is deprecated.
 It will be removed in the future and UntypedStorage will be the only storage class.
 This should only matter to you if you are using storages directly.  
To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = elem.storage()._new_shared(numel)
```

Thanks
Kevin

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0
* OS: Ubuntu
* Python version: 3.8
* CUDA/cuDNN version: 11.7/8
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):
pyg                       2.3.0           py38_torch_2.0.0_cu117    pyg
pytorch                   2.0.0           py3.8_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-lightning         2.0.0              pyhd8ed1ab_1    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.0.0                py38_cu117    pytorch
torchmetrics              0.11.2           py38hb070fc8_0  
torchtriton               2.0.0                      py38    pytorch
torchvision               0.15.0               py38_cu117    pytorch
pyg-lib                   0.2.0+pt20cu117          pypi_0    pypi

**Comment by rusty1s** [comment]
:( Sorry about this. I fixed it in https://github.com/pyg-team/pytorch_geometric/pull/7034. However, since this is just a warning, I am not sure if it warrants a hotfix. I suggest simply filter this warning
```python
warnings.filterwarnings('ignore', '.*TypedStorage is deprecated.*')
