### ISSUE TITLE
How to input a weighted graph to a GCN model?

### ISSUE THREAD

**Issue by albert-666** [pyg-team/pytorch_geometric#707]
How to input a weighted graph to a GCN model? Thanks!

**Comment by WMF1997** [comment]
hello @albertshifengshiyu 

i do not know which kind of "weight" you want. 

👇 is an ugly example of ```edge_weight```, sorry, I do not get how to use ```node_weight```

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch_geometric
import torch_geometric.nn as gnn

torch.manual_seed(0)  # to see better, you can use a manual seed. 

# if it is "edge_weight"
gcn = gnn.GCNConv(in_channels=18, out_channels=36)

x = torch.randn(22, 18)
edge_index = torch.randint(0, 22, [2, 40])
edge_weight = torch.randn(40)
# NOTE(WMF): I really do not understand the line "above", and I just "try" to get that. 
# in /torch_geometric/utils/loop.py
# if edge_weight is not None:
#   assert edge_weight.numel() == edge_index.size(1)
#   inv_mask = ~mask

y = gcn(x=x, edge_index=edge_index, edge_weight=edge_weight)
```

```y.shape``` is still ```torch.Size[22, 36]```
Perhaps something like this? In fact, I do not know "how to use" ```edge_weight``` better.... 

yours sincerely, 
@wmf1997

**Comment by albertshifengshiyu** [comment]
Thank you for your reply! It is very help. What I mean is 'edge_weight'. I will try to implement my code in this way. 
Thanks!
yours sincerely,
@albertshifengshiyu

**Comment by Christian-Git01** [comment]
Hello @WMF1997 

When running your code, I get some NANs in my y. How should one treat them? I reduced the dimension of this problem to make it easier to show the NANs


`
> import torch.nn as nn
>  import torch.nn.functional as F
> import torch_geometric
> import torch_geometric.nn as gnn
> torch.manual_seed(0)
> gcn = gnn.GCNConv(in_channels=1, out_channels=4)

> x = torch.randn(10, 1)
> edge_index = torch.randint(0, 10, [2, 22])
> edge_weight = torch.randn(22)
> y = gcn(x=x, edge_index=edge_index, edge_weight=edge_weight)
`
![image](https://user-images.githubusercontent.com/52127686/68477566-1c040c80-022e-11ea-8ff6-47f4d3fe5a8c.png)
