### ISSUE TITLE
Compose pre-filters

### ISSUE THREAD

**Issue by anton-bushuiev** [pyg-team/pytorch_geometric#7084]
### 🚀 The feature, motivation and pitch

Hi 👋! Is there an already implemented alternative to [torch_geometric.transforms.compose](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/transforms/compose.html#Compose) for prefilters?

**Comment by rusty1s** [comment]
Happy to include this. Please send a PR if you find some time :)
