### ISSUE TITLE
Should `'Data'` instead be `Dict[str, Any]`?

### ISSUE THREAD

**Issue by amorehead** [pyg-team/pytorch_geometric#7091]
### 📚 Describe the documentation issue

Looking at the functionality of PyTorch Geometric Data objects' `update` function, it looks like one needs to pass a dictionary of features into this function instead of a `Data` object. Is that correct? If so, I think updating the documentation on this function would be a good idea to avoid confusing any users.

This is in reference to this line: https://github.com/pyg-team/pytorch_geometric/blob/707fee2f9d7ff56a4792693eaea0134390749eef/torch_geometric/data/data.py#L515

### Suggest a potential alternative/fix

We can update the function argument type for `data` here to be a `Dict[str, Any]`.

**Comment by rusty1s** [comment]
It can actually be both (since `Data` also defines an `items()` method), so something like `Union[Data, Dict[str, Any]]` would be indeed better. Feel free to update if you have some time.

**Comment by amorehead** [comment]
Sounds good. I've made a pull request for this [here](https://github.com/pyg-team/pytorch_geometric/pull/7110).
