### ISSUE TITLE
`from_networkx` calls the constructor of the `nx.Graph` again

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#7112]
### 🐛 Describe the bug

brought to my attention by [mahdieh.ahmadi88@gmail.com](mailto:mahdieh.ahmadi88@gmail.com) via slack
```
Ground Truth NetworkX num_edges= 72
num_edges after convert to PyG= 144
PyG to_string= Data(edge_index=[2, 144], max_pp=[52], remaining_pp=[52], pp_req=[52], max_ram=[52], remaining_ram=[52], ram_req=[52], tier=[52], is_core=[52], edge_tier=[144], max_bw=[144], remaining_bw=[144], delay=[144], bw_req=[144], num_nodes=52)
NetworkX to_string= MetroNetwork with 52 nodes and 72 edges
```
I made the repro below based on his code snippets:
```
import networkx as nx
from torch_geometric.utils import from_networkx
class MetroNetwork(nx.Graph):
    def __init__(self, debug_mode=False, testing=False, **attr):
        super().__init__(**attr)
        self.num_access = None
        self.num_main = None
        self.num_core = None
        self.num_nodes = None
        self.num_edges = None
        self.max_pp = None
        self.max_ram = None
        self.max_bw = None
        self.max_link_delay = None
        self.max_placement_delay = None
        self.create_network4()
    def create_network4(self):
        num_access = 44
        num_main = 6
        num_core = 2
        self.num_access = num_access
        self.num_main = num_main
        self.num_core = num_core
        self.num_nodes = num_access + num_main + num_core

        tier_0_node_attributes = {'max_pp': 4000., 'remaining_pp': 4000., 'pp_req': 0,
                                  'max_ram': 100., 'remaining_ram': 100., 'ram_req': 0,
                                  'tier': 0, 'is_core': 0}
        tier_1_node_attributes = {'max_pp': 6000., 'remaining_pp': 6000., 'pp_req': 0,
                                  'max_ram': 150., 'remaining_ram': 150., 'ram_req': 0,
                                  'tier': 1, 'is_core': 1}
        tier_2_node_attributes = {'max_pp': 12000., 'remaining_pp': 12000., 'pp_req': 0,
                                  'max_ram': 300., 'remaining_ram': 300., 'ram_req': 0,
                                  'tier': 2, 'is_core': 1}

        node_idx = 0
        node_list = [(node_idx + i, tier_0_node_attributes) for i in range(num_core)]
        node_idx += num_core
        node_list.extend([(node_idx + i, tier_1_node_attributes) for i in range(num_main)])
        node_idx += num_main
        node_list.extend([(node_idx + i, tier_2_node_attributes) for i in range(num_access)])
        self.add_nodes_from(node_list)

        tier_0_link_attributes = {'tier': 0, 'max_bw': 2000., 'remaining_bw': 2000., 'delay': 1.8, 'bw_req': 0}
        tier_1_link_attributes = {'tier': 1, 'max_bw': 3000., 'remaining_bw': 3000., 'delay': 4.8, 'bw_req': 0}

        edge_list = [(0, 7, tier_1_link_attributes),
                     (0, 2, tier_1_link_attributes),
                     (0, 3, tier_1_link_attributes),
                     (0, 27, tier_0_link_attributes),
                     (0, 8, tier_0_link_attributes),
                     (0, 44, tier_0_link_attributes),
                     (1, 5, tier_1_link_attributes),
                     (1, 7, tier_1_link_attributes),
                     (1, 30, tier_0_link_attributes),
                     (1, 28, tier_0_link_attributes),
                     (1, 11, tier_0_link_attributes),
                     (1, 50, tier_0_link_attributes),
                     (1, 22, tier_0_link_attributes),
                     (2, 4, tier_1_link_attributes),
                     (2, 37, tier_0_link_attributes),
                     (2, 24, tier_0_link_attributes),
                     (3, 4, tier_1_link_attributes),
                     (3, 7, tier_1_link_attributes),
                     (3, 5, tier_1_link_attributes),
                     (3, 21, tier_0_link_attributes),
                     (3, 20, tier_0_link_attributes),
                     (3, 49, tier_0_link_attributes),
                     (4, 18, tier_0_link_attributes),
                     (4, 10, tier_0_link_attributes),
                     (5, 19, tier_0_link_attributes),
                     (5, 43, tier_0_link_attributes),
                     (5, 11, tier_0_link_attributes),
                     (5, 6, tier_1_link_attributes),
                     (7, 32, tier_0_link_attributes),
                     (7, 33, tier_0_link_attributes),
                     (7, 25, tier_0_link_attributes),
                     (7, 17, tier_0_link_attributes),
                     (8, 44, tier_0_link_attributes),
                     (8, 14, tier_0_link_attributes),
                     (9, 10, tier_0_link_attributes),
                     (10, 40, tier_0_link_attributes),
                     (11, 34, tier_0_link_attributes),
                     (11, 48, tier_0_link_attributes),
                     (12, 39, tier_0_link_attributes),
                     (12, 51, tier_0_link_attributes),
                     (13, 23, tier_0_link_attributes),
                     (13, 27, tier_0_link_attributes),
                     (14, 21, tier_0_link_attributes),
                     (14, 16, tier_0_link_attributes),
                     (14, 42, tier_0_link_attributes),
                     (15, 20, tier_0_link_attributes),
                     (15, 50, tier_0_link_attributes),
                     (15, 51, tier_0_link_attributes),
                     (16, 42, tier_0_link_attributes),
                     (16, 44, tier_0_link_attributes),
                     (17, 42, tier_0_link_attributes),
                     (17, 39, tier_0_link_attributes),
                     (18, 40, tier_0_link_attributes),
                     (22, 41, tier_0_link_attributes),
                     (23, 38, tier_0_link_attributes),
                     (24, 38, tier_0_link_attributes),
                     (24, 49, tier_0_link_attributes),
                     (25, 51, tier_0_link_attributes),
                     (26, 47, tier_0_link_attributes),
                     (28, 30, tier_0_link_attributes),
                     (29, 31, tier_0_link_attributes),
                     (29, 41, tier_0_link_attributes),
                     (31, 34, tier_0_link_attributes),
                     (32, 33, tier_0_link_attributes),
                     (35, 40, tier_0_link_attributes),
                     (36, 37, tier_0_link_attributes),
                     (37, 40, tier_0_link_attributes),
                     (39, 42, tier_0_link_attributes),
                     (43, 47, tier_0_link_attributes),
                     (45, 46, tier_0_link_attributes),
                     (45, 47, tier_0_link_attributes),
                     (46, 48, tier_0_link_attributes),
                     ]

        # Add edges with networkx format
        self.add_edges_from(edge_list)
        self.num_edges = len(edge_list)

        self.max_pp = 12000
        self.max_ram = 300
        self.max_bw = 5000
        self.max_link_delay = 4.8
        self.max_placement_delay = 30
network = MetroNetwork()
print('Ground Truth NetworkX num_edges=', network.num_edges)
from_netx = from_networkx(network)
print('num_edges after convert to PyG=', from_netx.num_edges)
print("PyG to_string=", from_netx)
print("NetworkX to_string=", network)
```

### Environment

* PyG version:latest

**Comment by puririshi98** [comment]
after looking into it:
```
edge_index  =
tensor([[ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  3,
          3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  7,
          7,  7,  7,  7,  7,  7,  8,  8,  8,  9, 10, 10, 10, 11, 11, 11, 11, 12,
         12, 13, 13, 14, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18,
         19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 24, 25, 25, 26, 27, 27, 28,
         28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 36, 37, 37, 37,
         38, 38, 39, 39, 39, 40, 40, 40, 40, 41, 41, 42, 42, 42, 42, 43, 43, 44,
         44, 44, 45, 45, 46, 46, 47, 47, 47, 48, 48, 49, 49, 50, 50, 51, 51, 51],
        [ 7,  2,  3, 27,  8, 44,  5,  7, 30, 28, 11, 50, 22,  0,  4, 37, 24,  0,
          4,  7,  5, 21, 20, 49,  2,  3, 18, 10,  1,  3, 19, 43, 11,  6,  5,  0,
          1,  3, 32, 33, 25, 17,  0, 44, 14, 10,  4,  9, 40,  1,  5, 34, 48, 39,
         51, 23, 27,  8, 21, 16, 42, 20, 50, 51, 14, 42, 44,  7, 42, 39,  4, 40,
          5,  3, 15,  3, 14,  1, 41, 13, 38,  2, 38, 49,  7, 51, 47,  0, 13,  1,
         30, 31, 41,  1, 28, 29, 34,  7, 33,  7, 32, 11, 31, 40, 37,  2, 36, 40,
         23, 24, 12, 17, 42, 10, 18, 35, 37, 22, 29, 14, 16, 17, 39,  5, 47,  0,
          8, 16, 46, 47, 45, 48, 26, 43, 45, 11, 46,  3, 24,  1, 15, 12, 15, 25]])
```

**Comment by m4ahmadi** [comment]
I get this edge_index 
tensor([[ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,
          2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,
          5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  7,
          7,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9, 10, 10, 10, 10, 10, 11, 11,
         11, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 14, 14, 14, 14, 15, 15, 15,
         16, 16, 16, 17, 17, 17, 18, 18, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24,
         24, 24, 25, 25, 26, 27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33,
         33, 34, 34, 35, 36, 37, 37, 37, 38, 38, 39, 39, 39, 40, 40, 40, 40, 41,
         41, 42, 42, 42, 42, 43, 43, 44, 44, 44, 45, 45, 46, 46, 47, 47, 47, 48,
         48, 49, 49, 50, 50, 51, 51, 51],
        [ 5,  7,  2,  3, 27,  8, 44,  4,  5,  7, 30, 28, 11, 50, 22,  3,  0,  4,
         37, 24,  2,  4, 10,  0,  7,  5, 21, 20, 49,  1,  3,  9,  5,  2, 18, 10,
          0,  4,  8,  1,  3, 19, 43, 11,  6,  7,  8,  5,  6, 11,  0,  1,  3, 32,
         33, 25, 17,  5,  6, 11,  0, 44, 14,  4, 10,  3,  9, 12,  4, 40,  8,  7,
         12,  1,  5, 34, 48, 10, 11, 39, 51, 23, 27,  8, 21, 16, 42, 20, 50, 51,
         14, 42, 44,  7, 42, 39,  4, 40,  5,  3, 15,  3, 14,  1, 41, 13, 38,  2,
         38, 49,  7, 51, 47,  0, 13,  1, 30, 31, 41,  1, 28, 29, 34,  7, 33,  7,
         32, 11, 31, 40, 37,  2, 36, 40, 23, 24, 12, 17, 42, 10, 18, 35, 37, 22,
         29, 14, 16, 17, 39,  5, 47,  0,  8, 16, 46, 47, 45, 48, 26, 43, 45, 11,
         46,  3, 24,  1, 15, 12, 15, 25]])

**Comment by m4ahmadi** [comment]
When I run this script, I get the correct answer. 
In my own code, I have some if else in the constructor which determine the network which should be created based on parameters debug_mode and testing. 
I realized that when conversion occurs, the constructor is called again, but this time with default parameters, and so another network will be created. Is there a way to stop calling the constructor again for the conversion or at least pass the appropriate parameter to that?

**Comment by puririshi98** [comment]
https://github.com/pyg-team/pytorch_geometric/pull/7119
fyi u should check again after this PR goes through.

**Comment by m4ahmadi** [comment]
Consider running this code. The number of edges would be 146 instead of 144. 

import networkx as nx
from torch_geometric.utils import from_networkx
class MetroNetwork(nx.Graph):
    def __init__(self, debug_mode=False, testing=False, **attr):
        super().__init__(**attr)
        self.num_access = None
        self.num_main = None
        self.num_core = None
        self.num_nodes = None
        self.num_edges = None
        self.max_pp = None
        self.max_ram = None
        self.max_bw = None
        self.max_link_delay = None
        self.max_placement_delay = None
        if testing:
            self.create_network4()
        else:
            self.add_edges_from([(1, 4, {'tier': 0, 'max_bw': 2000., 'remaining_bw': 2000., 'delay': 1.8, 'bw_req': 0})])


    def create_network4(self):
        num_access = 44
        num_main = 6
        num_core = 2
        self.num_access = num_access
        self.num_main = num_main
        self.num_core = num_core
        self.num_nodes = num_access + num_main + num_core

        tier_0_node_attributes = {'max_pp': 4000., 'remaining_pp': 4000., 'pp_req': 0,
                                  'max_ram': 100., 'remaining_ram': 100., 'ram_req': 0,
                                  'tier': 0, 'is_core': 0}
        tier_1_node_attributes = {'max_pp': 6000., 'remaining_pp': 6000., 'pp_req': 0,
                                  'max_ram': 150., 'remaining_ram': 150., 'ram_req': 0,
                                  'tier': 1, 'is_core': 1}
        tier_2_node_attributes = {'max_pp': 12000., 'remaining_pp': 12000., 'pp_req': 0,
                                  'max_ram': 300., 'remaining_ram': 300., 'ram_req': 0,
                                  'tier': 2, 'is_core': 1}

        node_idx = 0
        node_list = [(node_idx + i, tier_0_node_attributes) for i in range(num_core)]
        node_idx += num_core
        node_list.extend([(node_idx + i, tier_1_node_attributes) for i in range(num_main)])
        node_idx += num_main
        node_list.extend([(node_idx + i, tier_2_node_attributes) for i in range(num_access)])
        self.add_nodes_from(node_list)

        tier_0_link_attributes = {'tier': 0, 'max_bw': 2000., 'remaining_bw': 2000., 'delay': 1.8, 'bw_req': 0}
        tier_1_link_attributes = {'tier': 1, 'max_bw': 3000., 'remaining_bw': 3000., 'delay': 4.8, 'bw_req': 0}

        edge_list = [(0, 7, tier_1_link_attributes),
                     (0, 2, tier_1_link_attributes),
                     (0, 3, tier_1_link_attributes),
                     (0, 27, tier_0_link_attributes),
                     (0, 8, tier_0_link_attributes),
                     (0, 44, tier_0_link_attributes),
                     (1, 5, tier_1_link_attributes),
                     (1, 7, tier_1_link_attributes),
                     (1, 30, tier_0_link_attributes),
                     (1, 28, tier_0_link_attributes),
                     (1, 11, tier_0_link_attributes),
                     (1, 50, tier_0_link_attributes),
                     (1, 22, tier_0_link_attributes),
                     (2, 4, tier_1_link_attributes),
                     (2, 37, tier_0_link_attributes),
                     (2, 24, tier_0_link_attributes),
                     (3, 4, tier_1_link_attributes),
                     (3, 7, tier_1_link_attributes),
                     (3, 5, tier_1_link_attributes),
                     (3, 21, tier_0_link_attributes),
                     (3, 20, tier_0_link_attributes),
                     (3, 49, tier_0_link_attributes),
                     (4, 18, tier_0_link_attributes),
                     (4, 10, tier_0_link_attributes),
                     (5, 19, tier_0_link_attributes),
                     (5, 43, tier_0_link_attributes),
                     (5, 11, tier_0_link_attributes),
                     (5, 6, tier_1_link_attributes),
                     (7, 32, tier_0_link_attributes),
                     (7, 33, tier_0_link_attributes),
                     (7, 25, tier_0_link_attributes),
                     (7, 17, tier_0_link_attributes),
                     (8, 44, tier_0_link_attributes),
                     (8, 14, tier_0_link_attributes),
                     (9, 10, tier_0_link_attributes),
                     (10, 40, tier_0_link_attributes),
                     (11, 34, tier_0_link_attributes),
                     (11, 48, tier_0_link_attributes),
                     (12, 39, tier_0_link_attributes),
                     (12, 51, tier_0_link_attributes),
                     (13, 23, tier_0_link_attributes),
                     (13, 27, tier_0_link_attributes),
                     (14, 21, tier_0_link_attributes),
                     (14, 16, tier_0_link_attributes),
                     (14, 42, tier_0_link_attributes),
                     (15, 20, tier_0_link_attributes),
                     (15, 50, tier_0_link_attributes),
                     (15, 51, tier_0_link_attributes),
                     (16, 42, tier_0_link_attributes),
                     (16, 44, tier_0_link_attributes),
                     (17, 42, tier_0_link_attributes),
                     (17, 39, tier_0_link_attributes),
                     (18, 40, tier_0_link_attributes),
                     (22, 41, tier_0_link_attributes),
                     (23, 38, tier_0_link_attributes),
                     (24, 38, tier_0_link_attributes),
                     (24, 49, tier_0_link_attributes),
                     (25, 51, tier_0_link_attributes),
                     (26, 47, tier_0_link_attributes),
                     (28, 30, tier_0_link_attributes),
                     (29, 31, tier_0_link_attributes),
                     (29, 41, tier_0_link_attributes),
                     (31, 34, tier_0_link_attributes),
                     (32, 33, tier_0_link_attributes),
                     (35, 40, tier_0_link_attributes),
                     (36, 37, tier_0_link_attributes),
                     (37, 40, tier_0_link_attributes),
                     (39, 42, tier_0_link_attributes),
                     (43, 47, tier_0_link_attributes),
                     (45, 46, tier_0_link_attributes),
                     (45, 47, tier_0_link_attributes),
                     (46, 48, tier_0_link_attributes),
                     ]

        # Add edges with networkx format
        self.add_edges_from(edge_list)
        self.num_edges = len(edge_list)

        self.max_pp = 12000
        self.max_ram = 300
        self.max_bw = 5000
        self.max_link_delay = 4.8
        self.max_placement_delay = 30

network = MetroNetwork(testing = True)
print('Ground Truth NetworkX num_edges=', network.num_edges)
from_netx = from_networkx(network)
print('num_edges after convert to PyG=', from_netx.num_edges)
print("PyG to_string=", from_netx)
print("NetworkX to_string=", network)

**Comment by puririshi98** [comment]
```
Ground Truth NetworkX num_edges= 72
num_edges after convert to PyG= 146
PyG to_string= Data(edge_index=[2, 146], max_pp=[52], remaining_pp=[52], pp_req=[52], max_ram=[52], remaining_ram=[52], ram_req=[52], tier=[52], is_core=[52], edge_tier=[146], max_bw=[146], remaining_bw=[146], delay=[146], bw_req=[146], num_nodes=52)
NetworkX to_string= MetroNetwork with 52 nodes and 72 edges
```

**Comment by puririshi98** [comment]
```
class MetroNetwork(nx.Graph):
    def __init__(self, debug_mode=False, testing=False, **attr):
        super().__init__(**attr)
        self.num_access = None
        self.num_main = None
        self.num_core = None
        self.num_nodes = None
        self.num_edges = None
        self.max_pp = None
        self.max_ram = None
        self.max_bw = None
        self.max_link_delay = None
        self.max_placement_delay = None
        if testing:
            self.create_network4()
        else:
            print("inside else testing")
            self.add_edges_from([(1, 4, {'tier': 0, 'max_bw': 2000., 'remaining_bw': 2000., 'delay': 1.8, 'bw_req': 0})])
```

adding this print shows:
```
Ground Truth NetworkX num_edges= 72
inside else testing
num_edges after convert to PyG= 146
PyG to_string= Data(edge_index=[2, 146], max_pp=[52], remaining_pp=[52], pp_req=[52], max_ram=[52], remaining_ram=[52], ram_req=[52], tier=[52], is_core=[52], edge_tier=[146], max_bw=[146], remaining_bw=[146], delay=[146], bw_req=[146], num_nodes=52)
NetworkX to_string= MetroNetwork with 52 nodes and 72 edges
```

this shows that the constructor is somehow being called w/ testing=false and that is causing ur error. will investigate why

**Comment by puririshi98** [comment]
ive isolated the issue to here:
https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/convert.py#L205
i did so with print statements:
```
    from torch_geometric.data import Data
    print("print1")
    G = nx.convert_node_labels_to_integers(G)
    print("print1.1")
    G = G.to_directed() if not nx.is_directed(G) else G
    print("print1.2")
    edge_index = torch.empty(G.number_of_edges(), 2, dtype=torch.long)
    print("print1.3")
    for i, e in enumerate(G.edges):
        edge_index[i, 0], edge_index[i, 1] = e
    print("print1.4")
    edge_index = edge_index.t().contiguous()
    print("print1.5")
    data = defaultdict(list)
    print("print2")
...
```
->
```
Ground Truth NetworkX num_edges= 72
print1
inside else testing
print1.1
print1.2
print1.3
print1.4
print1.5
print2
print3
print4
print5
print6
print7
num_edges after convert to PyG= 146
PyG to_string= Data(edge_index=[2, 146], max_pp=[52], remaining_pp=[52], pp_req=[52], max_ram=[52], remaining_ram=[52], ram_req=[52], tier=[52], is_core=[52], edge_tier=[146], max_bw=[146], remaining_bw=[146], delay=[146], bw_req=[146], num_nodes=52)
NetworkX to_string= MetroNetwork with 52 nodes and 72 edges

```

**Comment by puririshi98** [comment]
@m4ahmadi  u can build pyg w/ [this branch](https://github.com/pyg-team/pytorch_geometric/tree/nx_check) until i provide a longterm solution to PyG master

**Comment by puririshi98** [comment]
closing the issue, any furhter discussion can be had in the PR

**Comment by puririshi98** [comment]
@m4ahmadi u can temporarily solve your issue by building PyG w/ https://github.com/pyg-team/pytorch_geometric/tree/fromnetworkx-fix until we find a longterm solution
