### ISSUE TITLE
Edge weight in the LightGCN implementation in torch_geometric.nn.models.lightgcn does not work

### ISSUE THREAD

**Issue by happykygo** [pyg-team/pytorch_geometric#7149]
### 🐛 Describe the bug

Edge weight in the LightGCN implementation in torch_geometric.nn.models.lightgcn does not seem to work.

While the init() function can take edge_weight as an additional argument of the underlying LGConv layers, it does not appear to be used anywhere in the code, including the forward() function. 

The forward() function in LightGCN only takes edge_index as a parameter and not edge_weight, even though the forward() function in the LGConv layers accepts both edge_index and edge_weight. 

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0
* OS: MacOS and Linux
* Python version: 3.9
* CUDA/cuDNN version: 
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
This is because the interactions between users and items are naturally unweighted. If you want to use edge weights, you can use weighted `torch_spaerse.SparseTensor` as input `edge_index`.

**Comment by rusty1s** [comment]
This is something we can still add in the `LightGCN` model. Happy to take a look.
