### ISSUE TITLE
Metapath2vec IndexError: index is out of bounds

### ISSUE THREAD

**Issue by ZihanChen1995** [pyg-team/pytorch_geometric#7151]
### Description
Hi, I am trying to implement the `MetaPath2Vec()` to embed the nodes of a `HeteroData`. I wrote the code following the `AMiner` data example. **However, when training the model, it keeps showing the IndexError**: 

`IndexError: index 86099 is out of bounds for dimension 0 with size 9290`. 

Can you help me with that? Thank you so much in advance!

(This issue is similar but different from [ISSUE #2273](https://github.com/pyg-team/pytorch_geometric/issues/2273), since the error messages are somehow different, and that issue has already been fixed.)

---

My sample data and code can be found here:

### Sample Data: 
- [Links to data repo](https://github.com/ZihanChen1995/Sample_Edges)

### Code:
```
from torch_geometric.nn import MetaPath2Vec
num_cores = 8

# load edges
root_path = "./Sample_Edges"
a2a = torch.load(Path(root_path, "a2a.pt"))
b2b = torch.load(Path(root_path, "b2b.pt"))
a2b = torch.load(Path(root_path, "a2b.pt"))
b2a = torch.load(Path(root_path, "b2a.pt"))

# construct graph
sample_graph = HeteroData()
sample_graph["a"].num_nodes = 76809
sample_graph["b"].num_nodes = 9290
sample_graph["a","a2a","a"].edge_index = a2a.contiguous()
sample_graph["b","b2b","b"].edge_index = b2b.contiguous()
sample_graph["a","a2b","b"].edge_index = a2b.contiguous()
sample_graph["b","b2a","a"].edge_index = b2a.contiguous()

# define metapath
metapath = [
    ("a","a2a","a"),
    ("a","a2b","b"),
    ("b","b2b","b"),
    ("b","b2a","a"),
]

model = MetaPath2Vec(sample_graph.edge_index_dict, embedding_dim=100,
                     metapath=metapath, walk_length=50, context_size=7,
                     walks_per_node=5, num_negative_samples=3, num_nodes_dict=sample_graph.num_nodes_dict,
                     sparse=True).to(device)

loader = model.loader(batch_size=512, shuffle=True, num_workers=num_cores)
optimizer = torch.optim.SparseAdam(list(model.parameters()), lr=0.01)
```

### Error Message
```
def train(epoch, log_steps=100):
    model.train()

    total_loss = 0

    for i, (pos_rw, neg_rw) in enumerate(loader):    # this is where the error occurs
        optimizer.zero_grad()
        loss = model.loss(pos_rw.to(device), neg_rw.to(device))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        if (i + 1) % log_steps == 0:
            print((f'Epoch: {epoch}, Step: {i + 1:05d}/{len(loader)}, '
                f'Loss: {total_loss / log_steps:.4f}'))
            total_loss = 0

for epoch in range(1, 10):
    train(epoch)


>>>>>>>>>
[/usr/local/lib/python3.9/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    642             # instantiate since we don't know how to
    643             raise RuntimeError(msg) from None
--> 644         raise exception
    645 
    646 

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.9/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 193, in _sample
    return self._pos_sample(batch), self._neg_sample(batch)
  File "/usr/local/lib/python3.9/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 151, in _pos_sample
    batch = sample(
  File "/usr/local/lib/python3.9/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 245, in sample
    rand *= rowcount[subset].to(rand.dtype).view(-1, 1)
IndexError: index 86099 is out of bounds for dimension 0 with size 9290
```

Seems the 86099 equals the sum of 76809 (num of `a`) and 9290 (num of `b`). I also added the `num_nodes_dict=sample_graph.num_nodes_dict` to the arguments. But it did not help.

May I ask how I can fix it? Thank you so much!

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.0.0+cu118
* Python version: 3.9
* CUDA/cuDNN version: 118
* How you installed PyTorch and PyG (`conda`, `pip`, source):
```
os.environ['TORCH'] = torch.__version__
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-cluster -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q pyg-lib -f https://data.pyg.org/whl/nightly/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
```
* Any other relevant information (*e.g.*, version of `torch-scatter`): Running on Google Colab.

**Comment by EdisonLeeeee** [comment]
This is because there are nodes with zero degree, i.e., isolated nodes, in your dataset formated by `edge_index`. Therefore, when sampling, these nodes are assigned as a unified ID: `dummy_idx` (=76809+9290), see
https://github.com/pyg-team/pytorch_geometric/blob/2d8af8fa1508272c0ac48da7c8a4bb906dd29e21/torch_geometric/nn/models/metapath2vec.py#L249

Let me see how to fix it.

**Comment by EdisonLeeeee** [comment]
I'm trying to reproduce your error by generating random edges, and the error occurred when the graph has isolated nodes （`rowcount[subset] == 0`). What would happen if you comment out this line of code? Would this error still occur?
https://github.com/pyg-team/pytorch_geometric/blob/2d8af8fa1508272c0ac48da7c8a4bb906dd29e21/torch_geometric/nn/models/metapath2vec.py#L249

**Comment by ZihanChen1995** [comment]
Hi @EdisonLeeeee Thank you for the reply. I have commented out this line of code, but the error still occurred. Here is the new error message:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-8-97b364646eac>](https://localhost:8080/#) in <cell line: 18>()
     17 
     18 for epoch in range(1, 10):
---> 19     train(epoch)

4 frames
[/usr/local/lib/python3.9/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    642             # instantiate since we don't know how to
    643             raise RuntimeError(msg) from None
--> 644         raise exception
    645 
    646 

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.9/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 193, in _sample
    return self._pos_sample(batch), self._neg_sample(batch)
  File "/usr/local/lib/python3.9/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 151, in _pos_sample
    batch = sample(
  File "/usr/local/lib/python3.9/dist-packages/torch_geometric/nn/models/metapath2vec.py", line 248, in sample
    col = col[rand]
IndexError: index 20230 is out of bounds for dimension 0 with size 20230
```

**Comment by ZihanChen1995** [comment]
Hi @EdisonLeeeee , I just followed the Pull Request [#3353](https://github.com/pyg-team/pytorch_geometric/pull/3353) and successfully solved this bug. Thank you so much for all your help!

**Comment by t9lex** [comment]
i follow the Pull Request .but i got erro like：
 Traceback (most recent call last):
  File "nodvec.py", line 561, in <module>
    loss = train()
  File "nodvec.py", line 552, in train
    for pos_rw, neg_rw in loader:
  File "/home/ahmu/ENTER/envs/pytorchseq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ahmu/ENTER/envs/pytorchseq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/ahmu/ENTER/envs/pytorchseq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/ahmu/ENTER/envs/pytorchseq/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ahmu/ENTER/envs/pytorchseq/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ahmu/ENTER/envs/pytorchseq/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "nodvec.py", line 418, in _sample
    return self._pos_sample(batch), self._neg_sample(batch)
  File "nodvec.py", line 386, in _pos_sample
    batch = sample(adj, batch, num_neighbors=1,
  File "nodvec.py", line 461, in sample
    rowcount[mask] = src.storage.rowcount()[subset[mask]]
IndexError: index 15694 is out of bounds for dimension 0 with size 634

this seem some different erro.
Can you help me with that? Thank you so much in advance

**Comment by ZihanChen1995** [comment]
Are you running the `metapath2vec.py`? Seems you are working with `nodvec.py`, and that pull request is working for metapath (I tested on several version of PyG). If you can offer your code snippet or sample data, we may better help you with that.

**Comment by t9lex** [comment]
i have solved this problem
it is not  pyg metapath2vec problem but my metapath problem
do not use data.edgetype as metapath, it is ok in AMdataset ,but when come to your own dataset ,you must  set by yourself
metapath = [("drug","to","gene"),("gene","to","gene"),("gene","to","disease")]

thinks very much
