### ISSUE TITLE
LabelPropagation reference

### ISSUE THREAD

**Issue by carloalbertobono** [pyg-team/pytorch_geometric#7167]
### 📚 Describe the documentation issue

Hi,

I'm struggling to understand how the [formula](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.models.LabelPropagation.html#torch_geometric.nn.models.LabelPropagation) reported for LabelPropagation is related to the [reference](https://mlg.eng.cam.ac.uk/zoubin/papers/CMU-CALD-02-107.pdf).

The algorithm exposed in the paper does not seem to contain the formulation, but maybe I'm just unable to see it.
I can't even find the "alpha" parameter that the implementation exposes.

Is there something missing from the documentation?
Sorry if it's something obvious.

Thank you

**Comment by rusty1s** [comment]
The algorithm of label propagation is given in Sec 2.2. I am pretty sure this is the first reference of label propagation, but it got refined over the years. The residual connection via "alpha" is, for example, also used in the correct and smooth paper.

**Comment by carloalbertobono** [comment]
Hi, 
thank you very much for your answer.

I understand the use of the alpha, and the fact that can be mapped to the epsilon in the paper.
I also understand that the whole LP concept was "baptized" in the reference work.

However, the main point is that the documentation states: "_The label propagation operator from the Learning from Labeled and Unlabeled Data with Label Propagation paper_", but the reported (and implemented) operator is not from the paper. 

While I understand the presence of the reference, I think that it's misleading since:
1. That's not the operator from the paper
2. The actual reference is missing

Does this make sense?
Thank you

**Comment by rusty1s** [comment]
I updated the doc-string in https://github.com/pyg-team/pytorch_geometric/pull/7210.

**Comment by carloalbertobono** [comment]
Thank you very much! It helped a lot
