### ISSUE TITLE
PPI dataset can not work with GCNConv model

### ISSUE THREAD

**Issue by CFF-Dream** [pyg-team/pytorch_geometric#717]
## ❓ Questions & Help

```python
`class RGNN(nn.Module):
    def __init__(self, ):
        super(RGNN, self).__init__()                
        self.gcn0 = GCNConv(train_dataset.num_features, HIDDEN_SIZE_128*HEADS, cached=True)
        self.lin0 = nn.Linear(train_dataset.num_features, HEADS*HIDDEN_SIZE_128)        
        self.gcn1 = GCNConv(HIDDEN_SIZE_128*HEADS, HIDDEN_SIZE_128*HEADS, cached=True)
        self.lin1 = nn.Linear(HEADS*HIDDEN_SIZE_128, HEADS*HIDDEN_SIZE_128)        
        self.lin = nn.Linear(HIDDEN_SIZE_128*HEADS, NUM_CLASSES)        
    def forward(self, x, edge_index): 
        x0 = F.elu(self.gcn0(x, edge_index) + self.lin0(x))
        x1 = F.elu(self.gcn1(x0, edge_index) + self.lin1(x0))
        out = self.lin(x1)
        return out
 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = RGNN().to(device)
loss_op = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)
            
def train():
    model.train()
    total_loss = 0
    for data in train_loader:
        num_graphs = data.num_graphs
        data.batch = None
        data = data.to(device)
        optimizer.zero_grad()
        loss = loss_op(model(data.x, data.edge_index), data.y)
        total_loss += float(loss.item()) * num_graphs
        loss.backward()
        optimizer.step()
    return total_loss / len(train_loader.dataset)`
```
When I process ppi dataset which import from  torch_geometric.datasets with GCNConv model(imprort from torch_geometric.nn), it always raise the “RuntimeError: CUDA error: device-side assert triggered”，I tried for many times, it seems like ppi data can not work  with GCNConv? Do you know why?
Looking forward you reply, Thank u!

**Comment by rusty1s** [comment]
That is correct. The `GCNConv` does not support the sampling API as its current state. It can be however achieved by pre-computing the GCN edge normalization and passing it to `SAGEConv.forward()`.

**Comment by ldv1** [comment]
This is something I do not understand: we are always considering full graphs in each mini-batch, aren't we? if so, why should it fail? Thanks;

**Comment by rusty1s** [comment]
Yeah, it looks like my previous answer is not correct. The example above fails because of setting `cached=True`, which does not work in inductive settings (it expects operating on the same graph all time). Otherwise, this should just work just fine.
