### ISSUE TITLE
[HGTConv] Weird Behavior

### ISSUE THREAD

**Issue by yamaceay** [pyg-team/pytorch_geometric#7182]
### 🐛 Describe the bug

Hey, I recently noticed a potential bug in HGTConv: Attribute `dst_node_types` causes weird behavior. 

_torch_geometric/nn/conv/hgt_conv.py:74_

```python
self.dst_node_types = list(set(metadata[1][1]))
```
 
In this context, metadata is a list as specified below:
```python
> print(metadata)
[["X", "Y", "Z"], [["X", "r", "Y"], ["X", "s", "X"], ["Z", "t", "Y"]]]
# [[Nodes], [Meta relations]]

> print(metadata[1])
[["X", "r", "Y"], ["X", "s", "X"], ["Z", "t", "Y"]]
# [Meta relations]

> print(metadata[1][1])
["X", "s", "X"]
# Second relation type

> list(set(print(metadata[1][1]))
["X", "s"]
# Unique values of second relation type
# 'X' being a node type and 's' being an edge type
```

And it is used exactly once at:
_torch_geometric/nn/conv/hgt_conv.py:212-215_

```python
for node_type, out in out_dict.items():
  if node_type not in self.dst_node_types:
    out_dict[node_type] = None
    continue
```
 
So, results of each node type except 'X' would be ignored. 

I suggest the following change:

Change _torch_geometric/nn/conv/hgt_conv.py:74_ to:

```python
self.dst_node_types = [edge_type[2] for edge_type in self.edge_types]
```

I hope this helps. Keep up the good work and thank you in advance!

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.0.0+cu118
* OS: Linux (Google Colab)
* Python version: 3.9.16
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for letting us know. Fixed in https://github.com/pyg-team/pytorch_geometric/pull/7183.
