### ISSUE TITLE
Can PyTorch Geometric perform neighbor sampling on specific nodes each time?

### ISSUE THREAD

**Issue by zhijiejia** [pyg-team/pytorch_geometric#7188]
### 🚀 The feature, motivation and pitch

Can PyTorch Geometric perform neighbor sampling on specific nodes each time?  That is, can you manually specify the root node for each neighbor sampling before it is performed ?  For recommendation tasks, neighbor sampling needs to be performed based on the samples present in the batch. This means that the samples selected for neighbor sampling cannot be randomly generated each time during iterations.

**Comment by rusty1s** [comment]
You can initialize your `NeighborLoader` and then perform sampling on specific nodes via `loader.collate_fn(torch.tensor([...]))`. I think we can add a better interface for this.

**Comment by rusty1s** [comment]
Added a better interface here: https://github.com/pyg-team/pytorch_geometric/pull/7197, which should let you do
```python
loader([0, 1, 2, 3, ...])
```

**Comment by zhijiejia** [comment]
Thank you very much for responding and addressing my issue so quickly. May I ask if you could provide a small example? I didn't quite understand how to do what you mentioned.

**Comment by zhijiejia** [comment]
May be means this ?
```python
train_loader = NeighborLoader(data, num_neighbors=[20] * 2, batch_size=64, input_nodes=('paper', data['paper'].train_mask), shuffle=True)

sample_sub_graph = train_loader.collate_fn(torch.tensor([0, 1, 2, 3])) 
```

**Comment by zhijiejia** [comment]
Or, the better way to sample neighbor on specific node is this ?
```python
train_loader = NeighborLoader(data, num_neighbors=[20] * 2, batch_size=64, input_nodes=('paper', data['paper'].train_mask), shuffle=True)

sample_sub_graph = train_loader(torch.arange(64))
```

**Comment by zhijiejia** [comment]
Thank you very much for the author's answer. Let me summarize how to specify the root node for neighbor sampling every time.
```python
# version < 2.4 (version = 2.4, updated 2023.4.18)
sample_sub_graph = train_loader.collate_fn(torch.arange(16))
sample_sub_graph = train_loader.filter_fn(sample_sub_graph)
```
```python
# version >= 2.4 (version = 2.4, updated 2023.4.18)
sample_sub_graph = train_loader(torch.arange(16))
```
