### ISSUE TITLE
How to concatenate different positional encoding node features faster?

### ISSUE THREAD

**Issue by kou18n** [pyg-team/pytorch_geometric#7190]
### 🐛 Describe the bug

I want to concatenate AddRandomWalkPE node feature and AddLaplacianEigenvectorPE feature as x value.
```python
transform = T.Compose([T.RemoveIsolatedNodes() ,T.AddSelfLoops(), T.AddLaplacianEigenvectorPE(5,attr_name='x'),T.AddRandomWalkPE(20,attr_name='x'),T.ToSparseTensor()])  
train_dataset = MalNetTiny(root='/home/xxx/Datasets/MalNetTiny', split='train', transform=transform)
```
Currently, I use for loop, but it's time-consuming.

```python
for i,graph in enumerate(tqdm(train_dataset,total=3500)):
    train_dataset[i].x = torch.cat([graph.x.to(device) ,graph.random_walk_pe.to(device)],dim=1)
```
Is there any faster way? Thank you.

**Comment by rusty1s** [comment]
I wouldn't know of a faster way to do this. The concatenation should be actually quite fast. Are you sure this is the bottleneck?

**Comment by kou18n** [comment]
Thank you for your reply. I found the solution. 
I should set  `T.AddRandomWalkPE(20,attr_name=None)`.
