### ISSUE TITLE
BPRLoss implementation in torch_geometric.nn.models.lightgcn

### ISSUE THREAD

**Issue by happykygo** [pyg-team/pytorch_geometric#7196]
### 🐛 Describe the bug

There are two potential bugs in torch_geometric.nn.models.lightgcn:

1. In BPRLoss(_Loss)::forward, `log_prob` is divided by `n_pairs` twice: the first time in F.logsigmoid(positives - negatives).mean(), and the second time in the return clause.
I suggest changing the return clause to: `return -log_prob + regularization / n_pairs`

2. In LightGCN()::recommendation_loss, it calls BPRLoss::forward and passes in the embeddings of all nodes. It should pass in only the embeddings of the nodes in the mini-batch.

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0
* OS: MacOS and Linux
* Python version: 3.9
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks for the issue, and sorry for my super late reply. I think you are absolutely correct. We will revisit this as part of our community sprint, in which we want to finally provide an example of `LightGCN` as well.

**Comment by happykygo** [comment]
Thank you. Glad to be helpful. I would love to contribute to the community sprint. I can also provide an example of `LightGCN` usage. Please let me know how I can help.

**Comment by rusty1s** [comment]
This sounds wonderful, thanks for considering contributing. We are kicking the community sprint of next week, and post regular updates to our Slack (feel free to join if you haven't). I marked you already to work on this issue and potentially an example of LightGCN. Thank you!
