### ISSUE TITLE
How to install old version PyG

### ISSUE THREAD

**Issue by JialeTao** [pyg-team/pytorch_geometric#720]
## Environment

* OS: linux
* Python version: 3.6
* PyTorch version: 1.0
* CUDA/cuDNN version: 10.0
* GCC version: 5
* How did you try to install PyTorch Geometric and its extensions (pip, source):
* Any other relevant information:

## Checklist

- [ ] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

Hi , how can I install the old version PyG. For some reason I want to use pytorch1.0 based on which it seems latest PyG can't be installed. I can install PyG based on pytorch1.1 in my environment. Is there any solution?

**Comment by rusty1s** [comment]
PyTorch updates their internal APIs regularly and we are hence forced to change our internals too (in addition to the external packages). Therefore, we cannot provide backward capabilities :( However, there definitely exist versions that work under PyTorch 1.0. For example, for `torch-scatter` it would be version [1.1.2](https://github.com/rusty1s/pytorch_scatter/releases). If you have figured out which versions work together for PyTorch 1.0, we can add those information to the documentation.
