### ISSUE TITLE
BFS, DFS implementation in PyG

### ISSUE THREAD

**Issue by bboyleonp666** [pyg-team/pytorch_geometric#7205]
### 🚀 The feature, motivation and pitch

I am working on a project to classify a whole graph, and I try to implement [graph2vec](https://arxiv.org/abs/1707.05005). In this work, it applys WL algorithm, which I thought GCN and its variations are great replacement, which makes me wanna implement the whole model by PyG.

Since I would like my model to be an end-to-end one, instead of separating into WL -> BFS -> Doc2Vec -> Classification. I searched for BFS utils in PyG, but did not find useful information. And I was not sure if I apply other packages' BFS, will that still update the weight correctly?

Even if applying other packages is a wise choice, I still perfer there's a method provide by PyG to implement BFS or other traversals (even the customized ones).

### Alternatives

If there's a graph, or simply, a tree, like below.
```
       1
     /   \
   2      3
 /   \   /  \
4    5  6    7
```
I think reordering the nodes and cut off all the links and re-generate the links as [(1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)] might be a great idea, but I am not quite sure whether there will be any problem consequently.

**Comment by rusty1s** [comment]
Would something like `k_hop_subgraph` be sufficient for you?

**Comment by bboyleonp666** [comment]
I am afraid that `k_hop_subgraph` is not enough for the task. `k_hop_subgraph` keeps the graph structure and only consider part of a graph, but I would like to represent the whole graph using 1 vector which takes all the node attributes into consideration.

**Comment by rusty1s** [comment]
Yes, but can't you just reshape your node features afterwards to obtain a sequence of node features?

**Comment by bboyleonp666** [comment]
Oh! It was my fault that I didn't mention my edges are generated based on time. My graphs are control flow graphs (CFGs) which I think taking execution flow into consideration is a better idea to embed a graph as a whole. Reshaping is a great idea, and it might train a model well, but I don't know if it's a nice way to consider my graphs that way.

**Comment by rusty1s** [comment]
Ok, just want to point out that `k_hop_subgraph` will already order based on BFS (which seems to be the original issue).

**Comment by bboyleonp666** [comment]
I got your point! I didn't even realize that `k_hop_subgraph` must be implemented by BFS at first. I was trapped in `k hop` itself. I guess my problem is solved now.
