### ISSUE TITLE
Handelling default values in from_networkx

### ISSUE THREAD

**Issue by timdnewman** [pyg-team/pytorch_geometric#7278]
### 🐛 Describe the bug

Hi,

Bad news I think I found a bug! Good news I think I found the solution!

The way that from_networkx handles "node_default" and "edge_default" metadata is causing it to fall over. I think the underlying issue is not checking for emptiness in the dictionaries in the nx graph. See discussion here: [different package, same problem](https://stackoverflow.com/questions/73991516/osmnx-graph-to-torch-geometry-error-could-not-infer-dtype-of-point/76157301#76157301)

In my case read_graphml is adding the "node_default" and "edge_default" but all sorts of things can add them.

Example:

```python
import networkx as nx
from random import randint,random
from torch_geometric.utils.convert import from_networkx

#Generate a graph with example data
g = nx.generators.classic.complete_graph(5,nx.Graph)

#nodes
nprop1 = {n:randint(0,50) for n in g.nodes()}
nprop2 = {n:random() for n in g.nodes()}
nx.set_node_attributes(g,nprop1,'nprop1')
nx.set_node_attributes(g,nprop2,'nprop2')

#edges
eprop1 = {e:randint(0,10) for e in g.edges()}
eprop2 = {e:random() for e in g.edges()}
nx.set_edge_attributes(g,eprop1,'eprop1')
nx.set_edge_attributes(g,eprop2,'eprop2')

#THIS WORKS
G1 = from_networkx(g,group_node_attrs=all,group_edge_attrs=all)

#THIS DOES NOT SEE ERROR BELOW
nx.write_graphml(g,'gml_test.graphml')
g2 = nx.read_graphml('gml_test.graphml')
G2 = from_networkx(g2,group_edge_attrs=all,group_node_attrs=all)
```

Full error

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[c:\Git_projects\AnlyticalMethods-CoSInC-WP4\PYG_experiments.ipynb](file:///C:/Git_projects/AnlyticalMethods-CoSInC-WP4/PYG_experiments.ipynb) Cell 6 in ()
      [3](vscode-notebook-cell:/c%3A/Git_projects/AnlyticalMethods-CoSInC-WP4/PYG_experiments.ipynb#W5sZmlsZQ%3D%3D?line=2) nd_graph.add_nodes_from(g.nodes())
      [4](vscode-notebook-cell:/c%3A/Git_projects/AnlyticalMethods-CoSInC-WP4/PYG_experiments.ipynb#W5sZmlsZQ%3D%3D?line=3) nd_graph.add_edges_from(g.edges())
----> [5](vscode-notebook-cell:/c%3A/Git_projects/AnlyticalMethods-CoSInC-WP4/PYG_experiments.ipynb#W5sZmlsZQ%3D%3D?line=4) data = from_networkx(g,group_node_attrs=all,group_edge_attrs=all)

File [c:\Users\Tim.Newman\Anaconda3\envs\GPU_WS_pyg\lib\site-packages\torch_geometric\utils\convert.py:249](file:///C:/Users/Tim.Newman/Anaconda3/envs/GPU_WS_pyg/lib/site-packages/torch_geometric/utils/convert.py:249), in from_networkx(G, group_node_attrs, group_edge_attrs)
    247 else:
    248     try:
--> 249         data[key] = torch.tensor(value)
    250     except (ValueError, TypeError):
    251         pass

RuntimeError: Could not infer dtype of dict
```
This was from me working through from_networkx in a jupyter notebook line by line, it all worked until there so I added `print(key, value)` to the loop to pin it down and it errored at: `node_default {}`

Looking around though I found this works
FIX
```python
# remove node_default and edge_default metadata keys if they exist
g2.graph.pop("node_default", None)
g2.graph.pop("edge_default", None)

#THIS NOW DOES
G2 = from_networkx(g2,group_edge_attrs=all,group_node_attrs=all)
```
Even if the default dict did have a value - I'm 99% sure you wouldn't want it loaded into the data object anyway. So I think you want to check for empty dictionaries in or before:

```python
try:
    data[key] = torch.tensor(value)
````

### Environment

* PyG version: 2.0.4
* PyTorch version: 2.0.0
* OS:Win10
* Python version:3.8
* CUDA/cuDNN version:11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source):Conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): networkx=3.1

**Comment by rusty1s** [comment]
Thanks for reporting. I fixed it in https://github.com/pyg-team/pytorch_geometric/pull/7348.
