### ISSUE TITLE
one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by GodeWithWind** [pyg-team/pytorch_geometric#7283]
### 🐛 Describe the bug

```py
/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch/autograd/__init__.py:175: UserWarning: Error detected in ScatterAddBackward0. Traceback of forward call that caused the error:
  File "main.py", line 39, in <module>
    main(cfg)
  File "main.py", line 16, in main
    solver.train(loaders)
  File "/home/code/MCMU/MCMUGNN/solver/solver.py", line 78, in train
    loss, ratePenalty)
  File "/home/code/MCMU/MCMUGNN/solver/utils.py", line 13, in train_one_epoch
    w_hat = model(batch)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/code/MCMU/MCMUGNN/models/ComHAN.py", line 40, in forward
    x_dict = self.han1(x_dict, edge_index_dict, edge_attr_dict)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/code/MCMU/MCMUGNN/models/layers.py", line 279, in forward
    alpha=(alpha_src, alpha_dst), size=None, alpha_edge=alpha_edge)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 484, in propagate
    out = self.aggregate(out, **aggr_kwargs)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 609, in aggregate
    dim=self.node_dim)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch_geometric/nn/aggr/base.py", line 109, in __call__
    return super().__call__(x, index, ptr, dim_size, dim, **kwargs)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch_geometric/nn/aggr/basic.py", line 21, in forward
    return self.reduce(x, index, ptr, dim_size, dim, reduce='sum')
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch_geometric/nn/aggr/base.py", line 155, in reduce
    return scatter(x, index, dim, dim_size, reduce)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 74, in scatter
    return src.new_zeros(size).scatter_add_(dim, index, src)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484801627/work/torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
```
```py
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main(cfg)
  File "main.py", line 16, in main
    solver.train(loaders)
  File "/home/code/MCMU/MCMUGNN/solver/solver.py", line 78, in train
    loss, ratePenalty)
  File "/home/code/MCMU/MCMUGNN/solver/utils.py", line 28, in train_one_epoch
    total_loss.backward()
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/anaconda3/envs/pyg2.3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [144, 4]] is at version 8; expected version 4 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```
I encountered this problem, the console shows that it is caused by the function self.aggregate(out, **aggr_kwargs), here is my code
```py
    def forward(self, data):
        x_dict, edge_index_dict, edge_attr_dict = data.x_dict, data.edge_index_dict, data.edge_attr_dict
        x_dict = self.han1(x_dict, edge_index_dict, edge_attr_dict)
        x_dict = self.han2(x_dict, edge_index_dict, edge_attr_dict)
```

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by LukeLIN-web** [comment]
It is because your han1 layer uses in-place operation. You can use `x.clone()` before the in-place operation.

**Comment by GodeWithWind** [comment]
Thanks for the reply, although I know this makes the code run, does using the .clone() function affect the gradient return? And the ones that use the in-place operation do so because they inherit from MessagePassing, which means that this problem cannot be avoided?
Here is the modified code, I'm not sure if this will affect the model
```py
    def forward(self, data):
        x_dict, edge_index_dict, edge_attr_dict = data.x_dict, data.edge_index_dict, data.edge_attr_dict
        out = self.han1(x_dict, edge_index_dict, edge_attr_dict)
        out  = out.clone()
        out = self.han2(out, edge_index_dict, edge_attr_dict)
```

**Comment by GodeWithWind** [comment]
> It is because your han1 layer uses in-place operation. You can use tensor `.clone()` before the in-place operation. refer this https://discuss.pytorch.org/t/how-can-i-keep-gradient-when-i-change-one-row/176883
 Thanks for the reply, although I know this makes the code run, does using the .clone() function affect the gradient return? And the ones that use the in-place operation do so because they inherit from MessagePassing, which means that this problem cannot be avoided?
Here is the modified code, I'm not sure if this will affect the model
```py
    def forward(self, data):
        x_dict, edge_index_dict, edge_attr_dict = data.x_dict, data.edge_index_dict, data.edge_attr_dict
        out = self.han1(x_dict, edge_index_dict, edge_attr_dict)
        out  = out.clone()
        out = self.han2(out, edge_index_dict, edge_attr_dict)
```

**Comment by LukeLIN-web** [comment]
> > It is because your han1 layer uses in-place operation. You can use tensor `.clone()` before the in-place operation. refer this https://discuss.pytorch.org/t/how-can-i-keep-gradient-when-i-change-one-row/176883
> > Thanks for the reply, although I know this makes the code run, does using the .clone() function affect the gradient return? And the ones that use the in-place operation do so because they inherit from MessagePassing, which means that this problem cannot be avoided?
> > Here is the modified code, I'm not sure if this will affect the model
> 
> ```python
>     def forward(self, data):
>         x_dict, edge_index_dict, edge_attr_dict = data.x_dict, data.edge_index_dict, data.edge_attr_dict
>         out = self.han1(x_dict, edge_index_dict, edge_attr_dict)
>         out  = out.clone()
>         out = self.han2(out, edge_index_dict, edge_attr_dict)
> ```

It should have the same gradient so that it would not affect the model coverage.

**Comment by GodeWithWind** [comment]
> > > It is because your han1 layer uses in-place operation. You can use tensor `.clone()` before the in-place operation. refer this https://discuss.pytorch.org/t/how-can-i-keep-gradient-when-i-change-one-row/176883
> > > Thanks for the reply, although I know this makes the code run, does using the .clone() function affect the gradient return? And the ones that use the in-place operation do so because they inherit from MessagePassing, which means that this problem cannot be avoided?
> > > Here is the modified code, I'm not sure if this will affect the model
> > 
> > 
> > ```python
> >     def forward(self, data):
> >         x_dict, edge_index_dict, edge_attr_dict = data.x_dict, data.edge_index_dict, data.edge_attr_dict
> >         out = self.han1(x_dict, edge_index_dict, edge_attr_dict)
> >         out  = out.clone()
> >         out = self.han2(out, edge_index_dict, edge_attr_dict)
> > ```
> 
> It should have the same gradient so that it would not affect the model coverage.

Thank you very much, I have solved my problem
