### ISSUE TITLE
RadiusGraph issues

### ISSUE THREAD

**Issue by vkovac2** [pyg-team/pytorch_geometric#7286]
### 🐛 Describe the bug

from torch_geometric.transforms import RadiusGraph   
transform_radius = RadiusGraph(r = 1e6)
dataset = dataset_class(root = args.dataset_path, pre_transform=transform_radius)

I am working with QM9 dataset and I am trying to make a fully connected graph by using the RadiusGraph. When I run it I get the following error:

"return torch_cluster.radius_graph(x, r, batch, loop, max_num_neighbors,
AttributeError: 'NoneType' object has no attribute 'radius_graph'"

Thanks

### Environment

* PyG version: 2.3.0
* PyTorch version: 1.13.0
* OS: MAC
* Python version:3.10.6
* CUDA/cuDNN version: Nan
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Do you have `torch_cluster` installed?

**Comment by vkovac2** [comment]
I had to uninstall torch_cluster and install it again for some reason. Thanks a lot
