### ISSUE TITLE
WITH TORCH CLUSTER typing variable did not make it's way into release 2.3.0 or 2.3.1

### ISSUE THREAD

**Issue by ProfDoof** [pyg-team/pytorch_geometric#7290]
### 🐛 Describe the bug

Using 2.3.0, the following code fails

```python
from torch_geometric.typing import WITH_TORCH_CLUSTER
```

and produces the following error

```
ImportError: cannot import name 'WITH_TORCH_CLUSTER' from 'torch_geometric.typing' (/REDACTED/mambaforge/envs/gnn/lib/python3.9/site-packages/torch_geometric/typing.py)
```

After getting that error, I dumped the contents of the file at that location and found that it did not contain the code referencing `WITH_TORCH_CLUSTER` that can be found here

https://github.com/pyg-team/pytorch_geometric/blob/1b6c40f1bd6ed668a131f0f6e0dcf10f9bf54cb9/torch_geometric/typing.py#L36-L43

I then went and looked at the tagged releases and found that they also do not contain this code. 

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.0
* OS: Pop!_OS 22.04
* Python version: 3.9
* CUDA/cuDNN version: 11.7.0 according to the cudatoolkit I have installed
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): I do not have torch-cluster installed

**Comment by rusty1s** [comment]
That is correct. We update the examples according to the current master state of PyG. If you wanna run the examples on PyG 2.3.0, it is better to do this under the `2.3.0` tag, see https://github.com/pyg-team/pytorch_geometric/tree/2.3.0/examples.

**Comment by ProfDoof** [comment]
I didn't realize I was on the development version of the docs. This may be a mild feature request. It would probably be beneficial to warn that this is an unreleased version of the docs at the top of every page for that version instead of just the home page because the latest is what pops up when I google it instead of stable.

**Comment by evg-mar** [comment]
I get the same error, as described with:

Python 3.9.13
Torch '2.0.1+cu117'
PyG 2.4.0

**Comment by evg-mar** [comment]
Hi, I am getting the same error, while trying to run
**examples/mnist_nn_conv.py**

PyG: 2.4.0
PyTorch: '2.0.1+cu117'
Python: 3.9.13
OS: Ubuntu 22.04.1 LTS

Thanks in advance.

**Comment by akihironitta** [comment]
> PyG: 2.4.0

@evg-mar 2.4.0 hasn't been released yet. Which commit are you on? It should be available on master now:
https://github.com/pyg-team/pytorch_geometric/blob/165b68eebdc4d5bf44e56ca12f081aa55020a883/torch_geometric/typing.py#L44-L52
