### ISSUE TITLE
IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, X] (got interval [0, Y])

### ISSUE THREAD

**Issue by mmpust** [pyg-team/pytorch_geometric#7306]
Hi, 
I want to do supervised binary classification of a list of labelled graphs (train_graphs):
```
train_loader = DataLoader(
        train_graphs,
        batch_size=1,
        shuffle=True)
```
I get an index error, and assume that the error is caused by the node labelling and missing nodes. The maximum integer label of the first failing example is "405" but the number of nodes is 400.  But theoretically, DataLoader should be able to deal with missing nodes or graphs of different sizes, right?

```
def train(loader, model):
    model.train()
    for batch in loader:

        print("Run batch")
        print(batch)
        print(max(batch.edge_index[0]))
        logits = model(x=batch.x,
                       edge_index=batch.edge_index,
                       edge_attr=batch.edge_attr,
                       batch=batch.batch)

```
Output of print statements:
```                  
Run batch
DataBatch(x=[406, 1], edge_index=[2, 20618], edge_attr=[20618, 1], y=[1], num_nodes=406, dataType=[1], batch=[406], ptr=[2])
tensor(405)
Run batch
DataBatch(x=[406, 1], edge_index=[2, 22208], edge_attr=[22208, 1], y=[1], num_nodes=406, dataType=[1], batch=[406], ptr=[2])
tensor(405)
Run batch
DataBatch(x=[400, 1], edge_index=[2, 27101], edge_attr=[27101, 1], y=[1], num_nodes=400, dataType=[1], batch=[400], ptr=[2])
tensor(405)
```

Error message and traceback:
```
Traceback (most recent call last):
  File "miniconda3/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 272, in _lift
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gcnn_run2.py", line 424, in <module>
    main()
  File "gcnn_run2.py", line 326, in main
    train(
  File "gcnn_run2.py", line 185, in train
    logits = model(x=batch.x,
  File "miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "gcnn_run2.py", line 162, in forward
    x = layer(x, edge_index, edge_attr)
  File "miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniconda3/lib/python3.9/site-packages/torch_geometric/nn/models/deepgcn.py", line 94, in forward
    h = self.conv(h, *args, **kwargs)
  File "miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniconda3/lib/python3.9/site-packages/torch_geometric/nn/conv/graph_conv.py", line 86, in forward
    out = self.propagate(edge_index, x=x, edge_weight=edge_weight,
  File "miniconda3/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 461, in propagate
    coll_dict = self._collect(self._user_args, edge_index, size,
  File "miniconda3/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 335, in _collect
    data = self._lift(data, edge_index, dim)
  File "miniconda3/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py", line 275, in _lift
    raise IndexError(
IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 399] (got interval [0, 405])
```

Environment:
```
Python 3.9.12
PyG version: 2.4.0
Torch: 1.13.0
Ubuntu 20.04 LTS
```

Any ideas what I can do about this?
Thanks!

**Comment by rusty1s** [comment]
This looks to be a data issue, where `edge_index.max()` is greater than `data.num_nodes`. Can you confirm?

**Comment by mmpust** [comment]
Hi Matthias, yes that's correct. I need consistent labelling across graphs, even when nodes are missing or absent. So, for graphs with N nodes, node labels are not necessarily ```0, 1, 2, …, N-1```.
A graph with ```num_nodes=100``` may have a node labelled ```L=123```, so that there is an edge between nodes ```123---12```. In this case ```edge_index.max() = 123```.

**Comment by rusty1s** [comment]
`edge_index` needs to always point to the corresponding index in the feature matrix. As you said, if you want to store additional node IDs, you can hold them in a separate attribute, *e.g.*, `data.node_id`, and use that for any mapping related work.

**Comment by figurative666** [comment]
How to solve this problem? Thank you

**Comment by rusty1s** [comment]
You need to fix your data for this. Calling `data.validate()` should give you additional information.

**Comment by figurative666** [comment]
> You need to fix your data for this. Calling `data.validate()` should give you additional information.

Thank you. The problem has been solved according to the method you provided.

**Comment by ykoc58** [comment]
Hi @rusty1s , 

I have the same problem using GINE model/GINEConv in pytorch lightning. 

for batch_size = 1 : 'edge_index' point to valid indices in the interval [0, 0] (got interval [0, 34])
                                DataBatch(x=[29, 1], edge_index=[2, 64], edge_attr=[64], y=[1], batch=[29], ptr=[2])

for batch_size = 2 : 'edge_index' point to valid indices in the interval [0, 1] (got interval [0, 53])
                               DataBatch(x=[55, 1], edge_index=[2, 120], edge_attr=[120], y=[2], batch=[55], ptr=[3])

Where can I apply data.validate() in lightning model? Here is my lightning model:

class LightningGNN(pl.LightningModule):
    def __init__(self, **kwargs):
        super(LightningGNN, self).__init__()
        self.num_features = kwargs["num_features"] if "num_features" in kwargs.keys() else 3
        self.num_classes = kwargs["num_classes"] if "num_classes" in kwargs.keys() else 2
        self.validation_R2_scores = []
        self.validation_step_outputs = []
        self.training_step_outputs = []
        self.hidden = 256
        self.r2_score_metric = R2Score().to(self.device)
        self.model = GINE(self.num_features, self.hidden, self.num_classes)

    def forward(self, x, edge_index, edge_weight, batch_index):
        x_out = self.model(x.float(), edge_index, edge_weight, batch_index)
        #x_out = self.model(x.float(), edge_index, batch_index)
        return x_out

    def training_step(self, batch, batch_index):
        batch.validate()
        x, edge_index, edge_attr = batch.x, batch.edge_index, batch.edge_attr
        batch_index = batch.batch
        edge_weight = edge_attr.float()
        x_out = self.forward(x, edge_index, edge_weight, batch_index)
        loss = F.mse_loss(x_out.squeeze(), batch.y)
        self.training_step_outputs.append(loss)
        self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True, batch_size = batch_size)
        return loss

    def validation_step(self, batch, batch_index):
        batch.validate()
        x, edge_index, edge_attr = batch.x.float(), batch.edge_index, batch.edge_attr
        batch_index = batch.batch
        edge_weight = edge_attr.float()
        x_out = self.forward(x.float(), edge_index, edge_weight, batch_index)
        loss = F.mse_loss(x_out.squeeze(), batch.y)
        R2_score = self.r2_score_metric(x_out.squeeze(), batch.y)
        pred = x_out
        targets = batch.y
        self.validation_step_outputs.append(loss)
        self.validation_R2_scores.append(R2_score)
        self.log('val_loss', loss, on_step=True, on_epoch=True, prog_bar=True, batch_size = batch_size)
        self.log('val_R2score', R2_score, on_step=True, on_epoch=True, prog_bar=True, batch_size = batch_size)
        return loss

    def on_train_epoch_end(self):
        avg_train_loss = torch.stack(self.training_step_outputs).mean()
        self.logger.experiment.add_scalars('loss', {'train_loss': avg_train_loss.item()},self.global_step)
        self.training_step_outputs.clear()  # free memory

    def on_validation_epoch_end(self):
        avg_val_loss = torch.stack(self.validation_step_outputs).mean()
        avg_val_R2score = torch.stack(self.validation_R2_scores).mean()
        self.logger.experiment.add_scalars('loss', {'val_loss': avg_val_loss.item()},self.global_step)
        self.logger.experiment.add_scalars('R2score', {'val_R2score': avg_val_R2score.item()},self.global_step)
        self.validation_step_outputs.clear()  # free memory
        self.validation_R2_scores.clear()  # free memory

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr = 0.01)

------------------------------------------------------------------------

batch_size = 2
train_dataset = ZINC(root='data/ZINC', subset=True, split='train')
test_dataset = ZINC(root='data/ZINC', subset=True, split='test')
val_dataset = ZINC(root='data/ZINC', subset=True, split='val')
train_loader = DataLoader(train_dataset, batch_size=batch_size, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size)
val_loader = DataLoader(val_dataset, batch_size=batch_size, num_workers=2)

-------------------------------------------------------------------------
epoch_no = 100
num_features = train_dataset[0].x.size(1)
num_classes = train_dataset[0].y.size(0)
logger = pl.loggers.TensorBoardLogger("logs", name="GraphModel")
lightning_model = LightningGNN(num_features=num_features, num_classes=num_classes)
#lightning_model = LightningGCN(num_features, in_edge_features, hidden_channels, num_classes, num_heads, dropout)
trainer = pl.Trainer(max_epochs=epoch_no, logger=logger, log_every_n_steps=1)
trainer.fit(lightning_model, train_loader, val_loader)

**Comment by ykoc58** [comment]
I actually used the same dataset in GCNConv and it works. When I passed to GINEConv, this error is appeared. I just change the batch_size from 1 to 2 and the interval changes to [0, 0] to [0, 1] in the error message. It seems max value of edge_index is not cover the max value of batch_index. I could not understand why the model looks edge_indexes in batch_index for GINEConv, they are not same.

**Comment by rusty1s** [comment]
Do you have a small reproducible example?

**Comment by ykoc58** [comment]
[GNN_lightening_2.txt](https://github.com/pyg-team/pytorch_geometric/files/13558045/GNN_lightening_2.txt)

Hi @rusty1s , Here is my colab file. You can see the error by running the file. Please change the extension of the file extension as ".ipynb"

**Comment by rusty1s** [comment]
It looks like your model architecture is wrong, since you are using graph-level pooling readouts as input into your next GNN layer:
```python
        h1 = self.conv1(x, edge_index, edge_attr)
        h1 = global_add_pool(h1, batch)
        h2 = self.conv2(h1, edge_index, edge_attr)
        h2 = global_add_pool(h2, batch)
        h3 = self.conv3(h2, edge_index, edge_attr)
        h3 = global_add_pool(h3, batch)
        h = torch.cat((h1, h2, h3), dim=1)
```
I think it should be
```python
        h = self.conv1(x, edge_index, edge_attr)
        h1 = global_add_pool(h, batch)
        h = self.conv2(h, edge_index, edge_attr)
        h2 = global_add_pool(h, batch)
        h = self.conv3(h, edge_index, edge_attr)
        h3 = global_add_pool(h, batch)
        h = torch.cat((h1, h2, h3), dim=1)

**Comment by tekeburak** [comment]
I'm encountering an index error while attempting to train the GraphSAGE model using batch processing. When inspecting my batch data one by one. `data[0,...,n].edge_index`, I found that the maximum value in edge_index isn't greater than num_nodes. However, upon checking my data as batch using `data.edge_index`, I noticed that its maximum value exceeds num_nodes. I think that this inconsistency seems to be causing issues during batch training.

The error arises at the line where I call `out = model(data.x, data.edge_index)`. It seems that the model receives edge indices as a batch, resulting in an index error. I suspect that the discrepancy in edge indices when accessing as batch.

Since there is no problem with my data, how can I solve this problem?

`Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 171] (got interval [9, 200])`.

My code snipper below.

```python
import torch
from torch_geometric.data import Data, Batch
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GraphSAGE

train_data = Batch.from_data_list(train_dataset)
loader = DataLoader(train_data, batch_size=32, shuffle=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GraphSAGE(
    in_channels=9,
    hidden_channels=64,
    num_layers=2,
    out_channels=40,
).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005)
criterion = torch.nn.NLLLoss()

def train():
    model.train()
    
    total_loss = total_examples = 0
    for data in loader:
        data = data.to(device)
        optimizer.zero_grad()
        out = model(data.x, data.edge_index)
        loss = criterion(out, data.y)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        total_examples += 1
    
    return total_loss / total_examples if total_examples > 0 else 0.0
    
for epoch in range(1, 6):
    train_loss = train()
    print(f'Epoch: {epoch:02d}, Train Loss: {train_loss:.4f}')
```

**Comment by rusty1s** [comment]
Can you show me the output of
```python
print(train_dataset[0])
```
Also note that
```python
train_data = Batch.from_data_list(train_dataset)
loader = DataLoader(train_data, batch_size=32, shuffle=True)
```
is a wrong usage (since it will just contain a single graph you are trying to batch). Instead, do:
```python
loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

**Comment by tekeburak** [comment]
Thank you @rusty1s. If anyone encounters the same problem, check [here](https://github.com/pyg-team/pytorch_geometric/issues/8630) as well.
