### ISSUE TITLE
NeighborLoader() return subgraph with unexpected node number

### ISSUE THREAD

**Issue by xiachenrui** [pyg-team/pytorch_geometric#7341]
### 🐛 Describe the bug

NeighborLoader() return subgraph with unexpected node number. In following codes, `subgraph_loader` may return subgraph with 7 or 8 nodes, but only subgraph with 7 nodes is expected.

```python
from torch_geometric.loader import NeighborLoader
kwargs = {'batch_size': 1, 'num_workers': 1, 'persistent_workers': True}
# my_graph is undirected and withour self loops
subgraph_loader = NeighborLoader(my_graph , num_neighbors=[6], shuffle=False, **kwargs)

```

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.0
* OS: Ubuntu 
* Python version: 3.9.16
* CUDA/cuDNN version: none
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Can you share your `my_graph` data with us to look into this? Trying to reproduce on `Cora` right now.

**Comment by rusty1s** [comment]
This works as expected
```python
from torch_geometric.datasets import Planetoid
from torch_geometric.loader import NeighborLoader

dataset = Planetoid('/tmp/Cora', name='Cora')
loader = NeighborLoader(dataset[0], batch_size=1, num_neighbors=[6])

for batch in loader:
    assert batch.num_nodes <= 7

**Comment by xiachenrui** [comment]
Thanks you very much! You can get the grpah object [here](https://drive.google.com/file/d/1APC1G2gG4ypy9Pa5IjeZO_8Yx7X8XV6Y/view?usp=sharing). It is a `DataBatch()` object. Below is my code

```python
from torch_geometric.loader import NeighborLoader

kwargs = {'batch_size': 1, 'num_workers': 1, 'persistent_workers': True}
raw_edge_index = my_graph.edge_index
my_graph.edge_index, _ = remove_self_loops(my_graph.edge_index)
subgraph_loader = NeighborLoader(my_graph, num_neighbors=[6], shuffle=False, **kwargs)

for subg in subgraph_loader:
    assert subg.num_nodes == 7

```

**Comment by xiachenrui** [comment]
Sorry, I make a stupid mistake. In my graph , some nodes in grpah do not have enough neighbors to be sampled.

Thanks for your reply again !

Best,
Chen-Rui
