### ISSUE TITLE
Index out of bounds in batched_negative_sampling

### ISSUE THREAD

**Issue by manavkulshrestha** [pyg-team/pytorch_geometric#7347]
### 🐛 Describe the bug

I get an index out of bounds when trying to use batched negative sampling for my dataset. As far as I can tell, it's trying to index into the `edge_index` tensor using the a node value but I'm not entirely sure. I've made a small example here which gives me the same bug by selecting a batch size of 2 for my loader. I looked at the example of standard usage in the docs and don't see anything too different about it. If I'm not using the function as intended, please let me know. My data batch for the iteration looks like `DataBatch(x=[31, 511], edge_index=[2, 21], all_e_idx=[481, 2], all_e_y=[481], adj_mat=[2], num_nodes=31, batch=[31], ptr=[3])` so the number of nodes is large enough for the `edge_index` tensor. and I calculated the batch by just doing `batch = data.batch[edge_index[0]]`.

Code to reproduce:
```python
from torch_geometric.utils import batched_negative_sampling
import torch

edge_index = torch.tensor([
    [ 7,  7,  8,  8,  9, 10, 11, 12, 12, 13, 14, 15, 23, 23, 24, 24, 25, 26, 27, 29, 30],
    [ 0,  2,  4,  5,  1,  3,  6,  7,  8,  9, 10, 11, 16, 17, 19, 22, 18, 20, 21, 25, 26]
])
batch = torch.tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

assert batch.size(0) == edge_index.size(1)
batched_negative_sampling(edge_index, batch)
```

Error message:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [6], line 11
      8 batch = torch.tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])
     10 assert batch.size(0) == edge_index.size(1)
---> 11 batched_negative_sampling(edge_index, batch)

File ~/anaconda3/envs/pn/lib/python3.8/site-packages/torch_geometric/utils/negative_sampling.py:176, in batched_negative_sampling(edge_index, batch, num_neg_samples, method, force_undirected)
    173 else:
    174     src_batch, dst_batch = batch[0], batch[1]
--> 176 split = degree(src_batch[edge_index[0]], dtype=torch.long).tolist()
    177 edge_indices = torch.split(edge_index, split, dim=1)
    179 num_src = degree(src_batch, dtype=torch.long)

IndexError: index 23 is out of bounds for dimension 0 with size 21
```

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.12.1
* OS: Ubuntu 20.04
* Python version: 3.8.15
* CUDA/cuDNN version: 11.6
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): -

**Comment by rusty1s** [comment]
The `batch` still needs to be a node-level vector, so the `assert batch.size(0) == edge_index.size(1)` is wrong. No need to map it to an edge-level vector via `batch[edge_index[0]]`.

**Comment by manavkulshrestha** [comment]
Ah, thank you! I didn't catch that in the example
