### ISSUE TITLE
`to_homogeneous` doens't preserve `ptr`

### ISSUE THREAD

**Issue by ekosman** [pyg-team/pytorch_geometric#7362]
### 🐛 Describe the bug

The attribute `ptr` is not preserved when `to_homogeneous` is called on a `HeteroDataBatch`.

``` python

>>> a = Batch.from_data_list([HeteroData({"agent":{"x":torch.randn(3)}})])
>>> a
HeteroDataBatch(  # has ptr
  agent={
    x=[3],
    batch=[3],
    ptr=[2]
  }
)
>>> a.to_homogeneous()
Data(x=[3], batch=[3], node_type=[3])  # doesn't have ptr

```

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.1
* OS: linux
* Python version: 3.8
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Yes, this is a current limitation, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/hetero_data.py#L854). The problem with that is that `to_homogeneous` sorts features by type and not by example, so `ptr` cannot be computed anymore.

**Comment by ekosman** [comment]
> Yes, this is a current limitation, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/hetero_data.py#L854). The problem with that is that `to_homogeneous` sorts features by type and not by example, so `ptr` cannot be computed anymore.

Thanks for clarifying. I close this for now.
