### ISSUE TITLE
NeighborLoader not oblious behaviour

### ISSUE THREAD

**Issue by thinginyourmind** [pyg-team/pytorch_geometric#7372]
### 📚 Describe the documentation issue

NeighborLoader returns  *all* sampled neighbors and after forwarding the model one ends up with more data than initial batch_size. Code examples quietly return the first "batch_size" points, i.e.:

`result = model(batch)[:batch.batch_size]`

Which assumes initial nodes are in the same order in memory and are loaded first. This is not obvious and, as far as I can see, not documented in PyG docs.

### Suggest a potential alternative/fix

Mention the behavior of neighborloader in the corresponding page and add short code example in case user wants to only return the results from initial `batch_size` nodes.

**Comment by rusty1s** [comment]
This is actually mentioned [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/loader.html#torch_geometric.loader.NeighborLoader):
> Sampled nodes are sorted based on the order in which they were sampled. In particular, the first batch_size nodes represent the set of original mini-batch nodes.

I agree that we can probably make this more visible since this is crucial for the usage of `NeighborLoader`. Let me know how you want to see this resolved :)

**Comment by thinginyourmind** [comment]
Oops, my bad. Adding it to examples in the doc may clarify things for new users. In particular, this line: 

`out = model(batch.x_dict, batch.edge_index_dict)['paper'][:batch_size]`

However, I'm not sure how to incorporate it in the doc in a concise manner and if it would be beneficial at all. This solves my problem, so I'll close the issue.
