### ISSUE TITLE
prediction from edges

### ISSUE THREAD

**Issue by danfeiX** [pyg-team/pytorch_geometric#74]
First of all, thanks for the great library! 

I'm currently trying to implement a network that can predict labels for both nodes and edges. This might require adding new nodes to the graph. Does the library happen to offer a function that automatically converts edges to additional nodes or does the `nn` package already support outputing from edge features? Thanks.

**Comment by rusty1s** [comment]
We currently do not offer an operator for your task. Can you point me to a specific paper or method that would fit your needs?

**Comment by nitinkgp23** [comment]
Has this feature been implemented yet? If not, can you give hints on how to go ahead with this problem?

We could somehow convert the edges into some additional nodes and then do a node classification. If the library doesn't support it, is there any close mathematical operation that would possibly be useful here? I could try to implement the operation on my own.

**Comment by rusty1s** [comment]
There is now a line graph transform which could be useful for this.

**Comment by yt2639** [comment]
Hi @rusty1s ! Thanks for providing this amazing tool for us. I am now also working on a task where I need to predict the value of edges (like regression problem). I got n nodes * d node_features, and m edges (among those n nodes) * k edge_features. I quickly went over a paper [Neural Message Passing for Quantum Chemistry](https://arxiv.org/pdf/1704.01212.pdf) and then I used NNConv as conv.op and Set2Set as pooling.op. I am still not very clear how to do the edge prediction. 

And, by 
> There is now a line graph transform which could be useful for this.

Do you mean this **torch_geometric.transforms.line_graph**? I am not very familiar with those functions and can you add one or two examples to this function (like what PyTorch did )? Also, the tutorial in [Doc](https://pytorch-geometric.readthedocs.io/) is kind of too short. I just very superficially understand how to use PyG actually. Can you also make more tutorial and examples on the doc?

Really appreciate your work!!

Many thanks!
