### ISSUE TITLE
Do I need to specify the full incidence matrix for HypergraphConv to work?

### ISSUE THREAD

**Issue by yinyee** [pyg-team/pytorch_geometric#740]
## ❓ Questions & Help

Hello! I'm trying to use HypergraphConv with hypergraphs of varying sizes, therefore I need the weight matrix to be independent of the number of vertices.  How can I achieve this?

**Comment by rusty1s** [comment]
As far as I see, there is nothing that prevents you from using the `HypergraphConv` with hypergraphs of varying sizes. The parameters do not dependent on the number of vertices. You can even encode multiple hypergraphs in `hyperedge_index` by stacking them to the diagonal form `(N_1 + N_2 + ...) x (M_1 + M_2 + ...)`.
