### ISSUE TITLE
Is is available for PyTorch 1.3 now?

### ISSUE THREAD

**Issue by donandthou** [pyg-team/pytorch_geometric#742]
## 📚 Installation
I have trouble when I install:
$ pip install --verbose --no-cache-dir torch-scatter
$ pip install --verbose --no-cache-dir torch-sparse
$ pip install --verbose --no-cache-dir torch-cluster
$ pip install --verbose --no-cache-dir torch-spline-conv (optional)
it shows "failed building wheel for xxx(torch-scatter/torch-sparse/torch-cluster/torch-spline-conv)",but $ pip install torch-geometric is OK.
it adviced me to install a VC ++ 14.0，which I did later and then it didnot show the advice when install.BUT,the "failed building wheel for xxx" is still there.

## Environment
win10 x64
python 3.7
PyToch 1.3
cuda 10.1
cudnn 7.0
I use pip to install.
And when I install these components in my another PC which is:
win10 x64
python 3.6
PyToch 1.2
cuda 10.1
cudnn 7.0.
AND all things are FINE,PyG works well.
## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [x] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by cy69855522** [comment]
I am using torch1.3 and geometric, everything goes well.

**Comment by donandthou** [comment]
Thanks for ur reply,I will check if there is something else wrong.

**Comment by zzs95** [comment]
Hi, is the pytorch 1.2.0 compatible with cuda 10.1 in win10?

**Comment by donandthou** [comment]
yeah, its compatible.

**Comment by zzs95** [comment]
I solved the problem, it seem like i did not install the vs correctly. Then i install vs 2017 with the common c++ build tools and the win10 sdk, and set the path. and it finally work.

**Comment by tanzhenning** [comment]
> I solved the problem, it seem like i did not install the vs correctly. Then i install vs 2017 with the common c++ build tools and the win10 sdk, and set the path. and it finally work.

hi,can you help me online or give detailed steps？my qq is 549356893
