### ISSUE TITLE
Did you also publish the original C++ and CUDA code

### ISSUE THREAD

**Issue by BluePanda-io** [pyg-team/pytorch_geometric#744]
Hello again 

Did you also publish the original C++ and CUDA code for the layers for example for B-Spline

Thank you for your time

**Comment by rusty1s** [comment]
Sure, you can find all low-level code in the related subpackages, *e.g.*, the implementation of the SplineCNN operator in [`torch-spline-conv`](https://github.com/rusty1s/pytorch_spline_conv).
