### ISSUE TITLE
ValueError: 'add_self_loops' attribute set to 'True' on module 'GATConv((-1, -1), 128, heads=1)' for use with edge type(s) '[('author', 'to', 'paper')]'

### ISSUE THREAD

**Issue by PPGGG** [pyg-team/pytorch_geometric#7463]
I tried to leverage GATConv on heterogenous graph node classification. I defined a network like below:

```
self.convs = torch.nn.ModuleList()
    for _ in range(3):
        conv = HeteroConv({
            edge_type: GATConv((-1, -1), hidden_dim)
            for edge_type in metadata[1]
        })
        self.convs.append(conv)

self.lin = Linear(hidden_dim, num_classes)
```

However, i met the error below:

`ValueError: 'add_self_loops' attribute set to 'True' on module 'GATConv((-1, -1), 128, heads=1)' for use with edge type(s) '[('author', 'to', 'paper')]'. This will lead to incorrect message passing results.`

**Comment by akihironitta** [comment]
The error seems correct as it's raised to avoid silently calculating incorrect message passing on a hetero graph. Have you had a chance to pass `add_self_loops=False`? 

```diff
-           edge_type: GATConv((-1, -1), hidden_dim)
+           edge_type: GATConv((-1, -1, hidden_dim, add_self_loops=False)
```

https://pytorch-geometric.readthedocs.io/en/2.3.1/generated/torch_geometric.nn.conv.GATConv.html#torch_geometric.nn.conv.GATConv

**Comment by PPGGG** [comment]
> The error seems correct as it's raised to avoid silently calculating incorrect message passing on a hetero graph. Have you had a chance to pass `add_self_loops=False`?
> 
> ```diff
> -           edge_type: GATConv((-1, -1), hidden_dim)
> +           edge_type: GATConv((-1, -1), hidden_dim, add_self_loops=False)
> ```
> 
> https://pytorch-geometric.readthedocs.io/en/2.3.1/generated/torch_geometric.nn.conv.GATConv.html#torch_geometric.nn.conv.GATConv

Yeah. Then i met the problems below:

`RuntimeError: mat1 and mat2 shapes cannot be multiplied (400x128 and 512x512) `

The previous gat network is defined as below:

```
self.layer_1 = GATConv(input_dim, out_channels=hidden_dim, heads=4)
self.layer_2 = GATConv(4 * hidden_dim, hidden_dim, heads=4)
self.layer_3 = GATConv(4 * hidden_dim, num_classes, heads=6, concat=False)
```

But i don't know how to specific the input and output dimension on GATConv while in the heterogenous situation.

**Comment by rusty1s** [comment]
Do you have a script to reproduce? This works just fine for me:
```python
import torch

from torch_geometric.datasets import DBLP
from torch_geometric.nn import GATConv, HeteroConv

data = DBLP('/tmp/DBLP')[0]
data['conference'].x = torch.eye(data['conference'].num_nodes)

convs = torch.nn.ModuleList()
for _ in range(3):
    conv = HeteroConv({
        edge_type: GATConv((-1, -1), 32, add_self_loops=False)
        for edge_type in data.edge_types
    })
    convs.append(conv)

x_dict = data.x_dict
for conv in convs:
    x_dict = conv(x_dict, data.edge_index_dict)

**Comment by PPGGG** [comment]
> Do you have a script to reproduce? This works just fine for me:
> 
> ```python
> import torch
> 
> from torch_geometric.datasets import DBLP
> from torch_geometric.nn import GATConv, HeteroConv
> 
> data = DBLP('/tmp/DBLP')[0]
> data['conference'].x = torch.eye(data['conference'].num_nodes)
> 
> convs = torch.nn.ModuleList()
> for _ in range(3):
>     conv = HeteroConv({
>         edge_type: GATConv((-1, -1), 32, add_self_loops=False)
>         for edge_type in data.edge_types
>     })
>     convs.append(conv)
> 
> x_dict = data.x_dict
> for conv in convs:
>     x_dict = conv(x_dict, data.edge_index_dict)
> ```

Thanks a lot. This also works fine for me. Thanks a lot.
