### ISSUE TITLE
knn_graph is not working on cuda

### ISSUE THREAD

**Issue by qilinli** [pyg-team/pytorch_geometric#7475]
### 🐛 Describe the bug

The knn_graph works fine with x on the CPU but returns no edge if x is on CUDA.

```
import torch
from torch_geometric.nn import knn_graph

x = torch.rand((10, 2))

edge_index_cpu = knn_graph(x.cpu(), k=2)
edge_index_cuda = knn_graph(x.cuda(), k=2)

print('cpu:', edge_index_cpu.shape)
print('cuda:', edge_index_cuda.shape)

cpu: torch.Size([2, 20])
cuda: torch.Size([2, 0])
```

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* torch-cluster version: 1.6.1
* torch-scatter version: 2.1.1
* OS: Windows 10
* Python version: 3.10.10
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda (PyTorch), pip (PyG)

**Comment by rusty1s** [comment]
Seems related: https://github.com/rusty1s/pytorch_cluster/issues/181
