### ISSUE TITLE
ShapeNet sampling method?

### ISSUE THREAD

**Issue by MaGiiK02** [pyg-team/pytorch_geometric#753]
## ❓ Questions & Help
I have tried to understand the **ShapeNet dataset you are providing as a ready data set**, which is composed of cloud points, so different from the original without the whole mesh.
So I would ask you, **which kind of sampling did you apply** to the ShapeNet dataset to obtain the CloudPoints?

**Comment by rusty1s** [comment]
We use the ShapeNet point cloud dataset from [here](https://shapenet.cs.stanford.edu/iccv17/).
