### ISSUE TITLE
Planetoid dtype mismatch for CiteSeer

### ISSUE THREAD

**Issue by lippirk** [pyg-team/pytorch_geometric#7532]
### 🐛 Describe the bug

I find that I can't load the CiteSeer dataset with double precision

```python
import torch_geometric as tg
tg.datasets.Planetoid(root="/tmp", name="CiteSeer")
```

I get this error

```
File /user/work/pc22286/mambaforge/envs/dkm/lib/python3.11/site-packages/torch_geometric/io/planetoid.py:34, in read_planetoid_data(folder, prefix)
     31 len_test_indices = (test_index.max() - test_index.min()).item() + 1
     33 tx_ext = torch.zeros(len_test_indices, tx.size(1))
---> 34 tx_ext[sorted_test_index - test_index.min(), :] = tx
     35 ty_ext = torch.zeros(len_test_indices, ty.size(1))
     36 ty_ext[sorted_test_index - test_index.min(), :] = ty

RuntimeError: Index put requires the source and destination dtypes match, got Double for the destination and Float for the source.
```

Fortunately, there is a workaround if I set the default precision to single precision

```python
import torch as t
t.set_default_dtype(t.float32)
tg.datasets.Planetoid(root="/tmp", name="CiteSeer") ## success, this time
```

and then I will convert to double precision manually later. Not a bit problem, but I expected to be able to use float64

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* OS: CentOS 7
* Python version: 3.11.3
* CUDA/cuDNN version: 12.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): installed torch by conda (mamba), PyG by pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Thanks! Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/7536.
