### ISSUE TITLE
Comma in get_mesh_laplacian, symmetric normalization implementation

### ISSUE THREAD

**Issue by eloygeenjaar** [pyg-team/pytorch_geometric#7541]
### 🐛 Describe the bug

An additional comma is breaking the assignment of a floating point number to a tensor, making it a tuple for the 'sym' normalization of the get_mesh_laplacian function.

```import torch
from torch_geometric.utils import get_mesh_laplacian

edge_index = torch.tensor([[0, 1, 2], [1, 2, 0], [2, 0, 1]])
coordinates = torch.tensor([[0.0, 0.0, 0.0], [1.0, 1.0, 1.0], [2.0, 2.0, 2.0]])
get_mesh_laplacian(coordinates, edge_index, normalization='sym')
```
This code produces the following error:
```torch_geometric/utils/get_mesh_laplacian.py", line 101, in get_mesh_laplacian
    area_deg_inv_sqrt[area_deg_inv_sqrt == float('inf')] = 0.0,
TypeError: can't assign a tuple to a torch.FloatTensor
```

The issue is the following line in [get_mesh_laplacian](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/get_mesh_laplacian.py) line 101. The code works fine without the comma.
```area_deg_inv_sqrt[area_deg_inv_sqrt == float('inf')] = 0.0,```

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.0
* OS: Ubuntu
* Python version: 3.9.16
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
Oh, I am amazed we didn't test against this, sorry :(

Fixed in https://github.com/pyg-team/pytorch_geometric/pull/7544.
