### ISSUE TITLE
Regarding Heterogeneous Graph Explainability Sample Code

### ISSUE THREAD

**Issue by naoyukiwatanabe** [pyg-team/pytorch_geometric#7553]
### 🚀 The feature, motivation and pitch

We become indebted to

In the sample code below, I think that "HeteroExplanation" has the "visualize_feature_importance" function, but I think it is not implemented in the latest version of pypi (torch-geometric 2.3.1).
When will the implemented version be updated?

examples/explain/captum_explainer_hetero_link.py

Thank you for your confirmation.

Thank you in advance.

**Comment by rusty1s** [comment]
We are planning a new official release around end of June. If you cannot wait to test that out, we provide nightly builds and installation from GitHub directly (see `README` for more information).

**Comment by naoyukiwatanabe** [comment]
@rusty1s 
Thanks for the reply.

**Comment by naoyukiwatanabe** [comment]
t
