### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_geometric.nn.attention'

### ISSUE THREAD

**Issue by lizhixi212** [pyg-team/pytorch_geometric#7580]
### 🐛 Describe the bug

run code:examples/graph_gps.py
```python
import argparse
import os.path as osp
from typing import Any, Dict, Optional

import torch
from torch.nn import (
    BatchNorm1d,
    Embedding,
    Linear,
    ModuleList,
    ReLU,
    Sequential,
)
from torch.optim.lr_scheduler import ReduceLROnPlateau

import torch_geometric.transforms as T
from torch_geometric.datasets import ZINC
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GINEConv, GPSConv, global_add_pool
from torch_geometric.nn.attention import PerformerAttention
```
bug
```
Traceback (most recent call last):
  File "/home/xxx/pytorch_geometric/examples/graph_gps.py", line 21, in <module>
    from torch_geometric.nn.attention.performer import PerformerAttention
ModuleNotFoundError: No module named 'torch_geometric.nn.attention'
```

### Environment

torch                    1.13.1+cu117
torch-cluster            1.6.1+pt113cu117
torch-geometric          2.3.1
torch-scatter            2.1.1+pt113cu117
torch-sparse             0.6.17+pt113cu117
torch-spline-conv        1.2.2+pt113cu117
torchaudio               0.13.1+cu117
torchmetrics             0.11.4
torchvision              0.14.1+cu117

**Comment by lizhixi212** [comment]
.conda/envs/pytorch1.13gpu/lib/python3.10/site-packages/torch_geometric/nn
![image](https://github.com/pyg-team/pytorch_geometric/assets/53890383/53a73289-ba54-4e64-a317-8c1954aaabe3)
this is environment by `pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv`
however the code that was ran is that was cloned by this  repository.
![image](https://github.com/pyg-team/pytorch_geometric/assets/53890383/e355dcc0-492a-4571-a78d-347df40806f1)

**Comment by EdisonLeeeee** [comment]
`PerformerAttention` is not currently available in the stable version of PyTorch Geometric (2.3). To experiment with it, you need to install the nightly version of PyG. You can follow the instructions provided in README to install the nightly version, see: https://github.com/pyg-team/pytorch_geometric#nightly-and-master

**Comment by lizhixi212** [comment]
> `PerformerAttention` is not currently available in the stable version of PyTorch Geometric (2.3). To experiment with it, you need to install the nightly version of PyG. You can follow the instructions provided in README to install the nightly version, see: https://github.com/pyg-team/pytorch_geometric#nightly-and-master

thanks for you response！
