### ISSUE TITLE
About the custom aggregation scheme

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [pyg-team/pytorch_geometric#763]
## ❓ Questions & Help

Hi, thanks for the wonderful codes, I have a strange thought about the aggregation scheme that you mentioned in the [tutorial](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_gnn.html).

You mentioned that ![](http://latex.codecogs.com/gif.latex?\\square) denotes a differentiable, permutation invariant function such as `sum` and `mean`.

Here are my questions:
1. Can I apply a kind of differentiable but permutation variant function such as `GRU` or `LSTM`? Or this function has to be the permutation invariant function in the theory of graph networks?

2. If I can construct the ![](http://latex.codecogs.com/gif.latex?\\square) by applying `GRU`, what should I do (how to build custom aggregation scheme)? 

Hope to get the response from you, thank you so much.

**Comment by rusty1s** [comment]
Sure, you can apply a different aggregator function other than sum, mean, or max, but this is something we do not currently support. So you need to implement this on your own. This can be typically achieved by the "degree bucketing" approach, which groups nodes with the same number of neighbors into a list of tensors of shape `[batch, num_neighbors, num_features]`. You can iterate over this list and apply the `GRU` individually.

**Comment by gmftbyGMFTBY** [comment]
Thanks for your reply, I will try to use your suggestions.

**Comment by rusty1s** [comment]
Integrated via https://github.com/pyg-team/pytorch_geometric/pull/4379.
