### ISSUE TITLE
Fix the paper link in the docstring of `pyg.transforms.NodePropertySplit`

### ISSUE THREAD

**Issue by gvbazhenov** [pyg-team/pytorch_geometric#7634]
### 📚 Describe the documentation issue

Hi! I am not sure whether it requires creating a new PR (and I hope it does not), because the problem can be fixed easily — could you please change the paper link in the [docstring](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.transforms.NodePropertySplit.html) of `pyg.transforms.NodePropertySplit` from https://arxiv.org/abs/2302.13875v1 to https://arxiv.org/abs/2302.13875? We want to cite the **latest version** of our paper, not the first one.

### Suggest a potential alternative/fix

Replace https://arxiv.org/abs/2302.13875v1 with https://arxiv.org/abs/2302.13875 (i.e., remove version specification).

**Comment by rusty1s** [comment]
Sure :) https://github.com/pyg-team/pytorch_geometric/pull/7639
