### ISSUE TITLE
About enzymes_topk_pool.py

### ISSUE THREAD

**Issue by Yfhu1103** [pyg-team/pytorch_geometric#764]
## ❓ Questions & Help

Hello, I have read your code "examples/enzymes_topk_pool.py", I suppose this is the implementation of "Towards Sparse Hierarchical Graph Classifiers". But after running the code, I get some really poor result, I change the dataset to PROTEINS, the result is still bad, best test acc is about 0.53, why is that?

**Comment by rusty1s** [comment]
Yeah, there seems to be a bug somewhere. This once used to work. I will look into it. In the meantime, you can have a look at `benchmark/kernel` for a working `top-k` pooling implementation.

**Comment by Mrslock** [comment]
Thank you very much！if you have updated your code, will I receive a notification?

**Comment by rusty1s** [comment]
Thank you very much. So this could potentially be a dataset bug.

**Comment by Mrslock** [comment]
yeah, I think so.

**Comment by Mrslock** [comment]
> Hey, I'm also trying to reproduce the result. Are you testing using 10 fold validation? Or follow exactly the example code?

**Comment by Mrslock** [comment]
I do not follow the exact example code, and I do not use 10 fold validation either, not exactly. I just run the code for 10 rounds, during each round I shuffle the dataset thus get a new split for experiment. I calculate the avg value of the 10 results.

**Comment by Mrslock** [comment]
I can not get a satisfying result in ENZYMES, what is your result?

**Comment by zechenzhang** [comment]
Me neither, it's around ~50%.
