### ISSUE TITLE
add_random_edge does not check existing edges

### ISSUE THREAD

**Issue by abojchevski** [pyg-team/pytorch_geometric#7653]
### 🐛 Describe the bug

Calling add_random_edge may introduce duplicate edges that already existing in the graph. This may have unintended downstream consequences.

Minimal code to reproduce.

```python
edge_index = torch.IntTensor(([0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 0, 0, 1, 1, 1, 2, 2, 2]))
torch_geometric.utils.add_random_edge(edge_index, 0.4, num_nodes=3)
```

**Comment by rusty1s** [comment]
This is indeed wrong :( Fixed in https://github.com/pyg-team/pytorch_geometric/pull/7654.
