### ISSUE TITLE
GAT accepts num_layers as input argument, but this is not used

### ISSUE THREAD

**Issue by Chris-Pedersen** [pyg-team/pytorch_geometric#7682]
### 📚 Describe the documentation issue

In the [docstring](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.models.GAT.html#torch_geometric.nn.models.GAT.forward), when initialising a GAT, one possible argument is `num_layers` to set the number of message passing steps. However this is never actually used, which is a bit misleading.

### Suggest a potential alternative/fix

Either remove the argument from the constructor and docstring, or if you want to keep it for consistency's sake across other models where this is implemented, maybe flag a warning or error if this is =! 1, such that users are aware that additional message passing steps are not implemented.

**Comment by LukeLIN-web** [comment]
I wonder whether `num_layers` is used on BasicGNN

**Comment by SimonPop** [comment]
Hi @Chris-Pedersen

I think @LukeLIN-web is right, this parameter is in fact used in `GAT`'s parent class: `BasicGNN`.

GAT only defines the `init_conv` method which is in turn used by the `BasicGNN` implementation to create as many layers as wanted (defined by the `num_layers` parameter).

In the current code of [`BasicGNN`](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/basic_gnn.html?highlight=BasicGNN): 

```python
...
for _ in range(num_layers - 2):
            self.convs.append(
                self.init_conv(in_channels, hidden_channels, **kwargs))
...
```

You can check that by looking for example at the number of parameters with different values for `num_layers`.

```python
from torch_geometric.nn.models.basic_gnn import GAT

gat_10 = GAT(8, 8, 10)
print('Number of layers in gat_1: ', len([x for x in gat_10.parameters()]))

gat_1 = GAT(8, 8, 1)
print('Number of layers in gat_1: ', len([x for x in gat_1.parameters()]))
```

```bash
>> Number of layers in gat_1:  40
>> Number of layers in gat_1:  4
```
