### ISSUE TITLE
I customized a "transform" function in the dataset.

### ISSUE THREAD

**Issue by wwma** [pyg-team/pytorch_geometric#7727]
I customized a "transform" function in the dataset.
But when I load this dataset, runing “print (dataset [0])”, it automatically calls the "transform" function I defined, but the number of variables changed in it is more than the number of variables defined to be changed in the function. However, when I use the "transform" function alone, this does not happen.

_Originally posted by @wwma in https://github.com/pyg-team/pytorch_geometric/discussions/7676_

Now I have another problem.
As the code shows,the "transformer function" changes the label of the data, and save the original label as a tensor.
During the training ,the first epoch is okay,however the data in the second epoch I loaded are transformered data.
Its original labels are changed because the first epoch used "transformer function" , so the "transformer function" is used again on the data , and the original labels are wrong .

**Comment by akihironitta** [comment]
Closing this in favor of https://github.com/pyg-team/pytorch_geometric/discussions/7676#discussioncomment-6442150 :)
