### ISSUE TITLE
Half-Precision Training Support

### ISSUE THREAD

**Issue by jlevy44** [pyg-team/pytorch_geometric#773]
Hi!

I've been wrapping a lot of my models using nvidia-apex https://github.com/NVIDIA/apex. Will there be support in the future for training half precision? Seemed PointCNN failed when I wrapped it with amp.

```
    return torch_cluster.knn_cuda.knn(x, y, k, batch_x, batch_y, cosine)
ValueError: value cannot be converted to type at::Half without overflow: 1e+38
```

Thanks!

**Comment by rusty1s** [comment]
I believe this is caused by
```python
auto dist = at::full(y.size(0) * k, 1e38, y.options());
```
in `torch-cluster/cuda/knn_kernel.cu`. Setting this to a more reasonable value for half precision should fix this issue. I welcome any PR on this.

**Comment by jlevy44** [comment]
I’ll give it a shot and see if it works

**Comment by rusty1s** [comment]
All packages now have full-support for half-precision.
