### ISSUE TITLE
The DimeNet implementation always returns 0.

### ISSUE THREAD

**Issue by ATheCoder** [pyg-team/pytorch_geometric#7762]
### 🐛 Describe the bug

The `DimeNet` implementation in `torch_geometric.nn.models.dimenet` always returns `0`.

```
from torch_geometric.nn.models.dimenet import DimeNet

model = DimeNet(128, 128, 5, 8, 6, 6, 3.0)

x = torch.randint(15, (32,))
pos = torch.randn((15, 3))
batch = torch.randint(2, (15,))

model(x, pos, batch) // Returns tensor of 0s.
```

I believe this is because in the `OutputBlock` module when setting the initial weights the weights are set to `0` for the output layer that doesn't have a bias:

https://github.com/pyg-team/pytorch_geometric/blob/c6f3a55dff40992947ba15e34925cb3333a7c351/torch_geometric/nn/models/dimenet.py#L358C1-L358C38

I'm not sure what the right implementation is but I would love to make a pull request to fix this. 

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.0a0+1767026
* OS: Ubuntu 22.04
* Python version: 3.8.10
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by akihironitta** [comment]
Would you be interested in submitting a PR to fix this?

**Comment by ATheCoder** [comment]
@akihironitta @rusty1s  Yes I am. Just tell me what the right implementation looks like.

**Comment by rusty1s** [comment]
```python
glorot_orthogonal(self.lin.weight, scale=2.0)
```

**Comment by ATheCoder** [comment]
@rusty1s PR is ready ^^
