### ISSUE TITLE
"Data" object from older version of PyG

### ISSUE THREAD

**Issue by apadhiUCLS** [pyg-team/pytorch_geometric#7776]
### 🐛 Describe the bug

I'm trying to make a class that inherits from pytorch_geometric Data:

`
class graphSim(Data): 
    def __init__(self, data):

        self.nodes = data[0]
        self.node_prop = data[1]
        self.edges = data[2]
        self.edge_prop = data[3]
        
        Data(x=self.node_prop, edge_attr=self.edge_prop, edge_index=self.edges).__init__()
`

When I try to make an instance of this class, I get an error: `RuntimeError: The 'data' object was created by an older version of PyG. If this error occurred while loading an already existing dataset, remove the 'processed/' directory in the dataset's root folder and try again.`

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* Python version: 3.9
* How you installed PyTorch and PyG (`conda`, `pip`, source): yes

**Comment by rusty1s** [comment]
Do you have a reproducible example for me?

**Comment by apadhiUCLS** [comment]
Oh it looks like the error somehow disappeared for me... Thanks for your help!
