### ISSUE TITLE
knn_graph example not working

### ISSUE THREAD

**Issue by dyutimoy** [pyg-team/pytorch_geometric#7783]
### 🐛 Describe the bug

import torch
from torch_geometric.nn import knn_graph

x = torch.tensor([[-1.0, -1.0], [-1.0, 1.0], [1.0, -1.0], [1.0, 1.0]])
batch = torch.tensor([0, 0, 0, 0])
edge_index = knn_graph(x, k=2, batch=batch, loop=False)

Error message -----
 File "lib/python3.8/site-packages/torch_geometric/nn/pool/__init__.py", line 130, in knn_graph
   return torch_cluster.knn_graph(x, k, batch, loop, flow, cosine,
AttributeError: 'NoneType' object has no attribute 'knn_graph

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1+cu117
* OS: Ubuntu 20.04
* Python version: 3.8
* CUDA/cuDNN version: 12
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment]
You are missing the `torch_cluster` dependency.

**Comment by dyutimoy** [comment]
Thanks
