### ISSUE TITLE
the problem about PPI dataset 

### ISSUE THREAD

**Issue by MrLinNing** [pyg-team/pytorch_geometric#782]
## ❓ Questions & Help

When I use this APIs `train_dataset = PPI(path, split='train')` .
Because of the internet reason, I can not  download the ppi.zip from `https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip`. 
So, If I already have copy ppi.zip from other peoples to my local folds, how to directly use this ppi.zip rather than downloading  it again  from the  `https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip` ?

**Comment by rusty1s** [comment]
Unpack it into the `root` folder and name it `raw`.

**Comment by im-wll** [comment]
I use the sentence “ test_dataset = GeoData.PPI('/home/work/wll/GCN/demo/deep_gcns_torch-master/data/deepgcn/ppi/data-wll', split='test')”，but get an error, I don't know how to solve it?
![$FVZL9EECMGE7R}CN(U`(O8](https://user-images.githubusercontent.com/33930824/68543437-f4f63800-03f1-11ea-9aaa-55dd83ca990d.png)

**Comment by rusty1s** [comment]
Mh, works like a charm for me. Which `networkx` version are you using?

**Comment by im-wll** [comment]
thank you for your reply.  I have installed torch 1.2.0 ,  torch-geometric and a series of package，but my cuda is 8.0, so the torch.cuda.available( ) is False. Now, I only call the GeoData.PPI class without using network, but the error still appear.  I don't kmow Whether the environment is satisfied.

**Comment by rusty1s** [comment]
No, I mean the version of the `networkx` package. It recently changed its API.

**Comment by LiaoLW** [comment]
> ## ❓ Questions & Help
> When I use this APIs `train_dataset = PPI(path, split='train')` .
> Because of the internet reason, I can not download the ppi.zip from `https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip`.
> So, If I already have copy ppi.zip from other peoples to my local folds, how to directly use this ppi.zip rather than downloading it again from the `https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip` ?

Excuse me, can you share this dataset with me? The one I downloaded from http://snap.stanford.edu/graphsage/ppi.zip is not the same as the one used in PyG.

**Comment by rusty1s** [comment]
This is the same dataset, but it is already processed to speed up the dataset creation part. We load the pre-processed version provided by DGL, so I do not have access to the pre-processing part.

**Comment by LiaoLW** [comment]
> This is the same dataset, but it is already processed to speed up the dataset creation part. We load the pre-processed version provided by DGL, so I do not have access to the pre-processing part.

But there is not any 'train_graph.json' in this file, all I have is 
![image](https://user-images.githubusercontent.com/49851668/99770036-34e21600-2b42-11eb-81cb-56244a26bf81.png)

**Comment by rusty1s** [comment]
The training split can be found in `ppi-G.json`:
```
"nodes": [{"test": false, "id": 0, "val": false}, {"test": false, "id": 1, "val": false}, ...
```
