### ISSUE TITLE
Slack Link is Broken

### ISSUE THREAD

**Issue by NathanielB123** [pyg-team/pytorch_geometric#7833]
### 📚 Describe the documentation issue

The readme suggests joining the Slack "Click here to join our Slack community!" (address https://data.pyg.org/slack.html) but clicking this link leads to the following page:
![image](https://github.com/pyg-team/pytorch_geometric/assets/30476356/6e79b984-7123-45e1-a9a7-4000e3fc201b)

**Comment by EdisonLeeeee** [comment]
Link broken confirmed @rusty1s

**Comment by rusty1s** [comment]
Thanks for letting me know. Should be fixed now :)
