### ISSUE TITLE
`ValueError: Attempted to use an uninitialized parameter`

### ISSUE THREAD

**Issue by qwgao** [pyg-team/pytorch_geometric#7845]
### 🚀 The feature, motivation and pitch

Can the torch library and PyTorch Geometric (pyg) be used together to build a network? Can a network be constructed with both conventional convolutions and graph convolutions? Will there be any issues in the DataLoader part?

**Comment by EdisonLeeeee** [comment]
Yes.  PyG is an extension library for PyTorch that provides tools for working with graph-structured data and it is naturally possible to use PyTorch and PyG together to build a network. 

In terms of the DataLoader, PyG provides its own `Data` class and a `DataLoader` wrapper specifically designed for graph-structured data. You might prefer it when dealing with graph-structure data.

**Comment by qwgao** [comment]
When building a network, placing the pyg model as a module in the pytorch model resulted in the following error. Do you know the reason?

ValueError: Attempted to use an uninitialized parameter in <method 'numel' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions

**Comment by EdisonLeeeee** [comment]
Can you show me the full stacktrace?

**Comment by qwgao** [comment]
Connected to pydev debugger (build 191.7479.30)
Training with a single process on 1 GPUs.
/home/anaconda3/envs/graph/lib/python3.8/site-packages/torch_geometric/nn/conv/hetero_conv.py:62: UserWarning: There exist node types ({'S'}) whose representations do not get updated during message passing as they do not occur as destination type in any edge type. This may lead to unexpected behavior.
  warnings.warn(
Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
Traceback (most recent call last):
  File "/home/pycharm/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/pycharm/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/pycharm/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/Cls/graph/train.py", line 890, in <module>
    main()
  File "/home/Cls/graph/train.py", line 437, in main
    f'Model {safe_model_name(args.model)} created, param count:{sum([m.numel() for m in model.parameters()])}')
  File "/home/Cls/graph/train.py", line 437, in <listcomp>
    f'Model {safe_model_name(args.model)} created, param count:{sum([m.numel() for m in model.parameters()])}')
  File "/home/anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/parameter.py", line 145, in __torch_function__
    raise ValueError(
ValueError: Attempted to use an uninitialized parameter in <method 'numel' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions

**Comment by qwgao** [comment]
I have added the following modules to a Pytorch model

`class HeteroGraphSage(torch.nn.Module):
    def __init__(self, edge_types, hidden_channels, out_channels, num_layers):
        super().__init__()

        self.convs = torch.nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv(
                {
                    edge_type: SAGEConv((-1, -1), hidden_channels)
                    for edge_type in edge_types
                }, aggr='sum')
            self.convs.append(conv)
        self.lin = Linear(hidden_channels, out_channels)

    def forward(self, x_dict, edge_index_dict):

        for i, conv in enumerate(self.convs):
            x_dict = conv(x_dict, edge_index_dict)
            x_dict = {key: x.relu() for key, x in x_dict.items()}

        return self.lin(x_dict)
`

**Comment by qwgao** [comment]
I have added the following modules to a Pytorch `model.
`
class HeteroGraphSage(torch.nn.Module):
    def __init__(self, edge_types, hidden_channels, out_channels, num_layers):
        super().__init__()

        self.convs = torch.nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv(
                {
                    edge_type: SAGEConv((-1, -1), hidden_channels)
                    for edge_type in edge_types
                }, aggr='sum')
            self.convs.append(conv)
        self.lin = Linear(hidden_channels, out_channels)

    def forward(self, x_dict, edge_index_dict):

        for i, conv in enumerate(self.convs):
            x_dict = conv(x_dict, edge_index_dict)
            x_dict = {key: x.relu() for key, x in x_dict.items()}

        return self.lin(x_dict)

`

**Comment by qwgao** [comment]
I have added the following modules to a Pytorch model

```python
class HeteroGraphSage(torch.nn.Module):
    def __init__(self, edge_types, hidden_channels, out_channels, num_layers):
        super().__init__()

        self.convs = torch.nn.ModuleList()
        for _ in range(num_layers):
            conv = HeteroConv(
                {
                    edge_type: SAGEConv((-1, -1), hidden_channels)
                    for edge_type in edge_types
                }, aggr='sum')
            self.convs.append(conv)
        self.lin = Linear(hidden_channels, out_channels)

    def forward(self, x_dict, edge_index_dict):

        for i, conv in enumerate(self.convs):
            x_dict = conv(x_dict, edge_index_dict)
            x_dict = {key: x.relu() for key, x in x_dict.items()}

        return self.lin(x_dict)

```

**Comment by qwgao** [comment]
If I use the above program during the training process, the modules built by the pyg library cannot be trained during the pytorch model training process. Is it currently supported to train different modules of Pytorch and Pyg together?

**Comment by EdisonLeeeee** [comment]
Can you clarify? PyG should be seamlessly integrated with PyTorch during training. The way to fix your code is to initialize lazy modules before counting parameters or remove this part of the code `sum([m.numel() for m in model.parameters()])`.

**Comment by SyedBaqarAbbas** [comment]
> `SAGEConv((-1, -1)` uses the lazy initialization of PyTorch, you need to explicitly call forward to initialize the modules before calculating the number of parameters, e.g.,
> 
> https://github.com/pyg-team/pytorch_geometric/blob/9f9a38bf02e392d3bda116b4b258204fde63098e/examples/hetero/hetero_conv_dblp.py#L43-L44

Adding to it, the answer here lies in running a dummy forward pass. This will initialize your model parameters, and then you can run it later without `torch.no_grad()` and begin training the model.

**Comment by akihironitta** [comment]
Hey @qwgao, as @EdisonLeeeee @SyedBaqarAbbas responded here, the error is due to the lazy initialisation of your model parameters as you specify in your script:
```
                    edge_type: SAGEConv((-1, -1), hidden_channels)
```

To avoid the error, you need to either:
- initialise params before the logic by dummy forward as expleined above,
- move the logic using uninitialised params to somewhere after the first forward pass, or
- not use the lazy initialisation at all.

Here is a quick explanation in the docs: https://pytorch-geometric.readthedocs.io/en/latest/tutorial/heterogeneous.html#lazyinit

Closing this issue for now, but feel free to let us know if you have any further questions!
