### ISSUE TITLE
In Lightgcn example Amazonbook dataset cannot import 

### ISSUE THREAD

**Issue by primising** [pyg-team/pytorch_geometric#7882]
### 📚 Describe the documentation issue

This code:from torch_geometric.datasets import AmazonBook
ImportError: cannot import name 'AmazonBook' from 'torch_geometric.datasets'

**Comment by akihironitta** [comment]
It's a new dataset that hasn't been released yet. Until the next release becomes available, you can use it by installing PyG master or nightly: https://github.com/pyg-team/pytorch_geometric#nightly-and-master

**Comment by primising** [comment]
> 

Thank you bro. I try to install PYG nightly,the code out:ImportError: cannot import name 'Final' from 'typing,this Traceback point to this code:from torch_geometric.datasets import AmazonBook,and the last point to from typing import Any, Callable, Dict, Final, List, Optional, Tuple, Union in  basic.gnn.py.  ImportError: cannot import name 'Final' from 'typing'.
Is there any way to download this dataset from somewhere else?  I try to get this dataset in Amazon review data, but I don‘t know which one to download,[ratings only] [raw review data] or [5-core}.

**Comment by primising** [comment]
> It's a new dataset that hasn't been released yet. Until the next release becomes available, you can use it by installing PyG master or nightly: https://github.com/pyg-team/pytorch_geometric#nightly-and-master

Thank you ,bro. I install PYG nightly, and the out :
cannot import name 'Final' from 'typing' 
for this code : from torch_geometric.datasets import AmazonBook

**Comment by akihironitta** [comment]
`typing.Final` was introduced in Python 3.8, so you need to use Python 3.8 or later. https://docs.python.org/3/library/typing.html#typing.Final
