### ISSUE TITLE
bias_initializer with zeros not supported in HeteroLinear

### ISSUE THREAD

**Issue by Nokimann** [pyg-team/pytorch_geometric#7920]
### 🐛 Describe the bug

Unlike the description in [HeteroLinear](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.dense.HeteroLinear)

`HeteroLinear(..., bias_initializer='zeros')` does not work.

```
from torch_geometric.nn import HeteroLinear

lin = HeteroLinear(3,4,5, bias_initializer='zeros')

...
RuntimeError: Weight initializer 'zeros' not supported
```

### Environment

* PyG version: 2.3.0
* PyTorch version: 2.0.1
* OS: Ubuntu 20.04.6 LTS
* Python version: 3.10.11
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): pyg-lib

**Comment by rusty1s** [comment]
Thanks for reporting. Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/7923.
