### ISSUE TITLE
mnist_graculs.py in SVHN dataset

### ISSUE THREAD

**Issue by tonyandsunny** [pyg-team/pytorch_geometric#794]
## ❓ Questions & Help

Hi! I use the code to run the SVHN dataset. But loss does not converge. 
Do you meet the same problem?

**Comment by rusty1s** [comment]
I haven't tested this myself, so I can not give you any tips. This could have multiple sources of errors. I guess you are using SLIC superpixel representation? Can you identify the resulting images by yourself?

**Comment by tonyandsunny** [comment]
Yes！ I use the SLIC superpixel representation.

**Comment by rusty1s** [comment]
Just wanted to let you know that there is now a `ToSLIC` transform in `torch_geometric.transforms`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html?highlight=toslic#torch_geometric.transforms.ToSLIC).

**Comment by tonyandsunny** [comment]
I see! But it just get the features and positions. How about the edge_index?
Use the torch_geometric.utils.grid.py?

**Comment by rusty1s** [comment]
I suggest using the RadiusGraph or KNNGraph transforms to obtain edges.
