### ISSUE TITLE
SparseTensor Message Passing produce incorrect results with directed graphs

### ISSUE THREAD

**Issue by NematGH** [pyg-team/pytorch_geometric#7960]
### 🐛 Describe the bug

When performing message passing with an edge index that is an instance of SparseTensor the result is incorrect.  It produces the same result as when  flow = 'target_to_source' without SparseTensor( Graph is directed)

```
from torch_geometric.utils import add_self_loops
from torch_geometric.nn import MessagePassing
from torch_sparse import SparseTensor
import torch

torch.manual_seed(10)
x = torch.rand((4, 1))
edge_index = torch.as_tensor([
    [0, 0, 1, 2, 3],
    [2, 3, 3, 0, 0]])
edge_index_s = SparseTensor(row=edge_index[0], col=edge_index[1], sparse_sizes=(4, 4))

mp = MessagePassing().propagate(edge_index, x=x)
s_mp = MessagePassing().propagate(edge_index_s, x=x)
mp_t_s = MessagePassing(flow='target_to_source').propagate(edge_index, x=x)
```

the result is:
```
mp:     tensor([[0.9275],[0.0000],[0.4581],[0.9409]]),
s_mp:   tensor([[0.9275],[0.6150],[0.4581],[0.4581]]),
mp_t_s: tensor([[0.9275],[0.6150],[0.4581],[0.4581]])
```

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.
* OS: Windows 11
* Python version: 3.10.8
* CUDA/cuDNN version: 11.7
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter verison 0.6.16

**Comment by rusty1s** [comment]
You need to input the transpose `SparseMatrix`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/advanced/sparse_tensor.html).

> However, when holding a directed graph in SparseTensor, you need to make sure to input the transposed sparse matrix to propagate():

**Comment by NematGH** [comment]
Thanks for your response
