### ISSUE TITLE
In Introduction data.keys should be changed to data.key

### ISSUE THREAD

**Issue by chen-erqi** [pyg-team/pytorch_geometric#7965]
### 📚 Describe the documentation issue

In Introduction by examples
print(data.keys()) should be changed to print(data.keys)

### Suggest a potential alternative/fix

print(data.keys()) should be changed to print(data.keys)

**Comment by rusty1s** [comment]
In PyG master, we changed `data.keys` to `data.keys()` and updated the documentation accordingly. If you visit the PyG 2.3 documentation, it should still say `data.keys`.

**Comment by chen-erqi** [comment]
> In PyG master, we changed `data.keys` to `data.keys()` and updated the documentation accordingly. If you visit the PyG 2.3 documentation, it should still say `data.keys`.

Thanks for ur reply! 
Please forgive that I am a fresher in PyG!
The documentation I visit is latest.

**Comment by chen-erqi** [comment]
> In PyG master, we changed `data.keys` to `data.keys()` and updated the documentation accordingly. If you visit the PyG 2.3 documentation, it should still say `data.keys`.

I find out the 2.3.1 documentation.
Thanks a lot!!!
