### ISSUE TITLE
LSTM  aggregation or pooling aggregation for SAGEConv?

### ISSUE THREAD

**Issue by xuehui1991** [pyg-team/pytorch_geometric#798]
## ❓ Questions & Help

Seems only support mean aggregation now.

**Comment by rusty1s** [comment]
That is true, there is currently no way to handle neighbors in a permutation-sensitive way. I will think about how to implement it since it is not only necessary for SAGEConv but also for models like Janossy Pooling.

**Comment by goolhanrry** [comment]
Hi @rusty1s , I notice that in your implementation of SAGEConv, the node features are multiplied by the weights BEFORE aggregation, which is different from the original paper. Is there a mistake or I just misunderstand the algorithm in the paper? Thanks!

**Comment by rusty1s** [comment]
It does not matter, both ops compute the same output.

**Comment by goolhanrry** [comment]
> It does not matter, both ops compute the same output.

Thank you!

**Comment by rusty1s** [comment]
Integrated via https://github.com/pyg-team/pytorch_geometric/pull/4379.
