### ISSUE TITLE
CGConv

### ISSUE THREAD

**Issue by moqingyan** [pyg-team/pytorch_geometric#799]
## ❓ Questions & Help

I am using pytorch_geometric version 1.3.2, but it doesn't have CGConv in the pytorch_geometric.nn 
```
>>> torch_geometric.nn.CGConv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch_geometric.nn' has no attribute 'CGConv'
>>> torch_geometric.nn.conv.CGConv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch_geometric.nn.conv' has no attribute 'CGConv'
>>> torch_geometric.__version__
'1.3.2'
```

However, CGConv is in the documentation of pytorch_geometric.nn
https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.CGConv

Further, the website shows the latest version is 1.3.0. I think I still see the CGConv in the github code, so I don't think you have remove the feature. Is the pip package not updated?

Thanks for your help!

**Comment by rusty1s** [comment]
It was just added recently and is only available on master, see [here](https://github.com/rusty1s/pytorch_geometric/pull/732).
