### ISSUE TITLE
Strange behaviour with the to_dense_adj function

### ISSUE THREAD

**Issue by chinmay5** [pyg-team/pytorch_geometric#7998]
### 🐛 Describe the bug

While using to_dense_adj with edge attributes, I observed that the `idx` values generated are not unique ((line 94 in to_dense_adj.py). As such, the scatter_add function sums up overlapping values and generating an output greater than the original range of edge_attr values.

![image](https://github.com/pyg-team/pytorch_geometric/assets/16525717/be9029d6-f104-4577-bb5a-62c097c1ed9a)

The required tensors can be downloaded from [here](https://filesender.switch.ch/filesender2/download.php?token=d4b1599a-6eee-4b06-8640-be16fb784ab5&files_ids=490595)

Any help or insights are highly appreciated. 

Thanks,
Chinmay

### Environment

* PyG version:2.3.1
* PyTorch version: 2.0.1+cu117
* OS: Ubuntu 20.04
* Python version:3.8.10
* CUDA/cuDNN version:11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source):pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
It looks like your `edge_index` contains duplicated entries, and so all entries of `edge_attr` that belong to the same edge will be summed up to obtain a single entry in the dense adjacency matrix. I made this behavior more clear in the doc, see https://github.com/pyg-team/pytorch_geometric/pull/8016.
