### ISSUE TITLE
torch.load fails for torch_geometric.nn.Sequential

### ISSUE THREAD

**Issue by janblumenkamp** [pyg-team/pytorch_geometric#8008]
### 🐛 Describe the bug

When attempting to load a saved model that contains `torch_geometric.nn.Sequential`, pickle seems to fail to find the `Sequential` class. The exception is something along the line of `No module named 'Sequential_22ed45`, but the hash after `Sequential_` is always different.

To reproduce:
```python
import torch
from torch.nn import Linear, ReLU
from torch_geometric.nn import Sequential, GCNConv

in_channels = 10
out_channels = 1

model = Sequential('x, edge_index', [
    (GCNConv(in_channels, 64), 'x, edge_index -> x'),
    ReLU(inplace=True),
    (GCNConv(64, 64), 'x, edge_index -> x'),
    ReLU(inplace=True),
    Linear(64, out_channels),
])

torch.save(model, "test_save.ckpt")
model_load = torch.load("test_save.ckpt")
```

Stack trace:
```
Traceback (most recent call last):
  File "[...]/test_load_model.py", line 23, in <module>
    test_loading("test_save.ckpt")
  File "[...]/test_load_model.py", line 15, in test_loading
    model_load = torch.load(path)
  File "[...]/.local/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "[...]/.local/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "[...]/.local/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'Sequential_22ed45'
```

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* OS: Linux 5.15.0-60-generic Ubuntu 22.04
* Python version: 3.10
* CUDA/cuDNN version: NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): `conda`
* Any other relevant information (*e.g.*, version of `torch-scatter`): N/A

**Comment by rusty1s** [comment]
Will take a look.

**Comment by janblumenkamp** [comment]
Thanks! Just a brief update, it seems like a fresh installation on another machine does not have this problem, so it is probably connected to my environment setup. It might still be useful to figure this out, but feel free to close this otherwise.

**Comment by tedtroxell** [comment]
I have the same setup as @janblumenkamp except the torch_geometric version is 2.4.0 and am also running into this same issue. Is there any ideas for a quick workaround? most of the weights of my model were created with the Sequential module, and I'd hate to have to rewrite and retrain the model. Any help is greatly appreciated

**Comment by tedtroxell** [comment]
@rusty1s I'm using torch version `2.0.1+cu118` I also tried installing version `2.1.0+cu118`. I'm going to try with cuda 12.1 and torch version 2.1.0 as well to see if there is any success. What version or torch worked for you?

**Comment by tedtroxell** [comment]
@rusty1s I found the issue I was having, or at least mostly figured it out. I was using MLflow to load models and at some point it is breaking using MLflow's machinery, not PyG's. Thanks for all the help!

**Comment by way-zer** [comment]
Encountered this problem, How to resolve?

python 3.11
torch                   2.2.2
torch_geometric         2.5.3
```python
import torch
import torch_geometric.nn
from torch_geometric.nn import TransformerConv

gnn = torch_geometric.nn.Sequential(
    "x, edge_index",
    [
        (TransformerConv(10, 32, heads=4, concat=False), "x, edge_index -> a1"),
        (TransformerConv(32, 32, heads=4, concat=False), "a1, edge_index -> a2"),
        (TransformerConv(32, 32, heads=4, concat=False), "a2, edge_index -> a3"),
    ],
)

torch.save(gnn, 'tmp/t.pt')
```
Get
```
Traceback (most recent call last):
  File "/root/rl4net/examples/tmp/SequentialTest.py", line 14, in <module>
    torch.load('tmp/t.pt')
  File "/root/micromamba/envs/rl4net/lib/python3.11/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/micromamba/envs/rl4net/lib/python3.11/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/root/micromamba/envs/rl4net/lib/python3.11/site-packages/torch/serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'torch_geometric.nn.sequential_3992c5'
```

**Comment by rusty1s** [comment]
Will take a look.

**Comment by rusty1s** [comment]
will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/9369.
