### ISSUE TITLE
mixhop

### ISSUE THREAD

**Issue by xnuohz** [pyg-team/pytorch_geometric#8022]
### 🚀 The feature, motivation and pitch

I found a [PR](https://github.com/pyg-team/pytorch_geometric/pull/6448) about it already, but it hasn't been maintained for a long time. May I contribute to it from scratch? Let me know if there is any concern, thanks:)

### Alternatives

- A `mixhop_conv` module in `pyg.nn.conv`
- An example for Planetoid datasets

**Comment by rusty1s** [comment]
I think this is a good idea, thank you. Compared to the existing PR, we should add `MixHopConv` directly into `nn.conv`. We can add an example in a follow-up.
