### ISSUE TITLE
HeteroConv fails when only GCNConv are used

### ISSUE THREAD

**Issue by ver228** [pyg-team/pytorch_geometric#8034]
### 🐛 Describe the bug

It seems that if only GCNConv are used on a HeteroConv the forward pass fails. 

Below is a minimum example:
```
import torch
import torch_geometric.transforms as T
from torch_geometric.datasets import OGB_MAG
from torch_geometric.nn import HeteroConv, GCNConv, SAGEConv, GATConv

dataset = OGB_MAG(root='./data', preprocess='metapath2vec', transform=T.ToUndirected())
data = dataset[0]

hidden_channels = 32

conv_het = HeteroConv({
            ('paper', 'cites', 'paper'): GCNConv(-1, hidden_channels, add_self_loops=False),
            ('author', 'writes', 'paper'): SAGEConv((-1, -1), hidden_channels),
            ('paper', 'rev_writes', 'author'): GATConv((-1, -1), hidden_channels, add_self_loops=False),
        }, aggr='sum')

conv_only_gcn = HeteroConv({
            ('paper', 'cites', 'paper'): GCNConv(-1, hidden_channels, add_self_loops=False),
            ('author', 'writes', 'paper'): GCNConv(-1, hidden_channels, add_self_loops=False),
            ('paper', 'rev_writes', 'author'): GCNConv(-1, hidden_channels, add_self_loops=False),
        }, aggr='sum')

# Success!!! 
out1 = conv_het(data.x_dict, data.edge_index_dict)

# Fails :(
out2 = conv_only_gcn(data.x_dict, data.edge_index_dict)
```

The error message I have is:
```
  File "/opt/pyenv/versions/3.11.4/lib/python3.11/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 211, in forward
    edge_index, edge_weight, x.size(self.node_dim),
                             ^^^^^^
AttributeError: 'tuple' object has no attribute 'size'
```

Thanks for your help!

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* OS: Ubuntu 22.04.2 LTS
* Python version: 3.11.4
* CUDA/cuDNN version:  cu117
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): NA

**Comment by EdisonLeeeee** [comment]
That's because `GCNConv` does not support heterogenerous graphs, check [here](https://pytorch-geometric.readthedocs.io/en/latest/cheatsheet/gnn_cheatsheet.html) for all supported operators (marked as `bipartite`).

**Comment by ver228** [comment]
Thanks a lot! Now this make sense :) 

Do you know if there is a way to access to this information programatically? 
I am trying to dynamically change the base GNN for GCNConv, and it will be nice to throw a more informative error if somebody tries to do the same mistake i was doing.

**Comment by EdisonLeeeee** [comment]
Actually, the error message has been added in PyG via #7637, you might need to upgrade your PyG verison :)

**Comment by ver228** [comment]
Thanks! I see the change hasn't come to a release version yet since the last release version is from the 27 Apr while the change was merged on the 23 Jun. I am happy to wait to the next release. Thanks for your help!
