### ISSUE TITLE
Provide access to module function headers after definition in `torch_geometric.nn.sequential`

### ISSUE THREAD

**Issue by rachitk** [pyg-team/pytorch_geometric#8082]
### 🚀 The feature, motivation and pitch

This feature request is based on a Slack conversation; credit to Agamemnon for asking it.

Currently, an instance of `torch_geometric.nn.sequential` can be defined as follows (slightly modified from the docs at https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.sequential.Sequential): 

```
from torch.nn import Linear, ReLU, Dropout
from torch_geometric.nn import Sequential, GCNConv, JumpingKnowledge
from torch_geometric.nn import global_mean_pool

model = Sequential('x, edge_index, batch', [
    (Dropout(p=0.5), 'x -> x'),
    (GCNConv(128, 64), 'x, edge_index -> x1'),
    ReLU(inplace=True),
    (GCNConv(64, 64), 'x1, edge_index -> x2'),
    ReLU(inplace=True),
    (lambda x1, x2: [x1, x2], 'x1, x2 -> xs'),
    (JumpingKnowledge("cat", 64, num_layers=2), 'xs -> x'),
    (global_mean_pool, 'x, batch -> x'),
    Linear(2 * 64, 2),
])
```

From reading the code, `torch_geometric.nn.sequential` works by using a template (https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/sequential.jinja) that is then used to create a custom module definition and representation that inherits from torch.nn.Module. 

However, after definition, there is no apparent straightforward way to identify the individual module headers (`'x, edge_index -> x'`, for example).

A new feature could be simply to add an attribute (perhaps 'module_headers' or something similar) when instantiating and setting the attributes for the custom module. This could be done before returning the new module on line 115 of torch_geometric.nn.sequential (https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/sequential.py#L115). The only important thing would be to make sure the attribute in question isn't a defined attribute in `torch.nn.Module` or any other attributes that may be confusing. It may also be worth overloading the `__repr__` to include the headers, if desired.

### Alternatives

Currently, one can use the `inspect` module and get the source for the newly defined module forward:

```
import inspect
inspect.getsource(model.forward)
```

to get 

```
def forward(self, x, edge_index, batch):
        """"""
        x = self.module_0(x)
        x1 = self.module_1(x, edge_index)
        x1 = self.module_2(x1)
        x2 = self.module_3(x1, edge_index)
        x2 = self.module_4(x2)
        xs = self.module_5(x1, x2)
        x = self.module_6(xs)
        x = self.module_7(x, batch)
        x = self.module_8(x)
        return x
```

which can then be parsed in conjunction with attributes corresponding to the modules to get the original function headers. However, this seems overly complex. 

### Additional context

I would be happy to try to implement this feature request if it is something that is of interest to the maintainers (and the PyG community). I can't think of any issues that could arise from making the function headers available in this way.

**Comment by rusty1s** [comment]
Thank you. I like it and went ahead to implement this in https://github.com/pyg-team/pytorch_geometric/pull/8093. I hope that's okay :)

**Comment by rachitk** [comment]
Sounds great - I'm glad that it was an easy enough addition!
