### ISSUE TITLE
FB15k_237 has missing attributes 

### ISSUE THREAD

**Issue by LuisaWerner** [pyg-team/pytorch_geometric#8084]
### 🐛 Describe the bug

Hi, 

I want to make use of the dataset `torch_geometric.datasets.FB15k_237`. Unfortunately, when I load the dataset as follows, I only have the attribute `edge_type` contained but I think there should also be an `edge_index`, right? 

```python
import os.path as osp
from torch_geometric.datasets import FB15k_237

path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'FB15k')
data = FB15k_237(path)[0]

print(data)
print(data.edge_index)
```

However, the output of my print is 
```
Data(edge_type=[272115])
None
```

There seems to be something wrong with the loaded object or is there a mistake from my side? 
Thanks! 

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* OS: MacOS 
* Python version: 3.11.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter: 2.1.1, torch-sparse: 0.6.17

**Comment by rusty1s** [comment]
I cannot reproduce this :( Does the same happen if you remove the processed folder from disk and run again?

**Comment by LuisaWerner** [comment]
When I do this, I get the following output: 
```
Downloading https://raw.githubusercontent.com/villmow/datasets_knowledge_embedding/master/FB15k-237/train.txt
Downloading https://raw.githubusercontent.com/villmow/datasets_knowledge_embedding/master/FB15k-237/valid.txt
Downloading https://raw.githubusercontent.com/villmow/datasets_knowledge_embedding/master/FB15k-237/test.txt
Processing...
Done!
Data(edge_type=[272115])
None
```

It looks like the dataset is loaded again but the edge_index is still missing unfortunately

**Comment by akihironitta** [comment]
@LuisaWerner I've just tried this with 2.4.0 but couldn't reproduce the issue. It'd be great if you could try again with 2.4.0 and see if it works. Feel free to re-open this issue if the issue still persists.

**Comment by LuisaWerner** [comment]
Hi,  I updated torch_geometric to 2.4.0, loaded the data again, had the same issue. But this time, after removing the processed folder, it works well. So this solved the issue, Thanks a lot! :)

```Downloading https://raw.githubusercontent.com/villmow/datasets_knowledge_embedding/master/FB15k-237/train.txt
Downloading https://raw.githubusercontent.com/villmow/datasets_knowledge_embedding/master/FB15k-237/valid.txt
Downloading https://raw.githubusercontent.com/villmow/datasets_knowledge_embedding/master/FB15k-237/test.txt
Processing...
Done!
Data(edge_index=[2, 272115], edge_type=[272115], num_nodes=14541)
tensor([[    0,     2,     4,  ...,  6954,  3818, 10244],
        [    1,     3,     5,  ...,  8974,  7570,  8396]])
```
