### ISSUE TITLE
Dataset is not undirected

### ISSUE THREAD

**Issue by emalgorithm** [pyg-team/pytorch_geometric#8171]
### 🐛 Describe the bug

Dataset is not undirected, despite passing ``to_undirected=True`` flag.

```python
# !pip install pyg-nightly

from torch_geometric.datasets import CitationFull
from torch_geometric.utils import is_undirected

edge_index = CitationFull(root=".", name="Cora_ML", to_undirected=True).edge_index
is_undirected(edge_index)
```
The above outputs: *False*

### Environment

* PyG version: 2.4.0.dev20231010
* PyTorch version: 2.0.1+cu118
* OS: Colab
* Python version: 3.10.12
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by Tuhinm2002** [comment]
Hey ! I ran it on colab and it ran. `is_undirected(edge_index)` is outputing `True`

**Comment by akihironitta** [comment]
@emalgorithm I don't see any issue running your code on my side as well. Would you mind trying it again and letting us know how to reproduce it?

**Comment by rusty1s** [comment]
You may have the old version stored on disk, so you can try to remove the `processed_dir` and re-process again.

**Comment by rusty1s** [comment]
I fixed this here: https://github.com/pyg-team/pytorch_geometric/pull/8179
