### ISSUE TITLE
unused `group` parameter in `HGTConv` still documented

### ISSUE THREAD

**Issue by stadlmax** [pyg-team/pytorch_geometric#8185]
### 📚 Describe the documentation issue

#7117 replaces `HGTConv` with the implementation done for the faster `FastHGTConv`. In the process of doing so, the `group` parameter has been removed falling back to the default `sum` operation. (@puririshi98: this was intentional, right?). The docs, however, haven't been updated accordingly.

https://github.com/pyg-team/pytorch_geometric/blob/737707c37fc2bd712a2289b683ec14549926ff49/torch_geometric/nn/conv/hgt_conv.py#L40-L43

### Suggest a potential alternative/fix

Remove the unused parameter from the docs.

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign me.

**Comment by Lian259** [comment]
I don't understand, won't removing the 'group' parameter affect the subsequent aggregation effects?
