### ISSUE TITLE
Splitting the dataset using Randomlinksplit

### ISSUE THREAD

**Issue by Tabatabaei1999** [pyg-team/pytorch_geometric#8190]
### 🐛 Describe the bug

I am using RandomLinkSplit to divide my data to train, validation, and test. I set the parameters as follows:
``` python 
transform = T.RandomLinkSplit(
    num_val=0.1,
    num_test=0.1,
    add_negative_train_samples=False,
    is_undirected=True,
)
```
train_data, val_data, test_data = transform(data)
the number of edges in the dataset itself is 841878; after the split, the number of edges in train_data is 673504, and the number of edges in val_data is  673504. I wonder why the number of edges in  val_data is equal to train_data? Is there anything wrong with the way that I'm using the RandomLinkSplit ?

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.1
* OS: ubuntu 
* Python version: 3.11 
* CUDA/cuDNN version: 
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by aaronwtr** [comment]
Did you figure out why this happened? I am having the same problem

**Comment by rusty1s** [comment]
Both `train_data.edge_index` and `val_data.edge_index` will contain 80% of edges for message passing. If you do not want to share `edge_label_index` and `edge_index` during training, take a look at the `RandomLinkSplit.disjoint_train_ratio` argument.
