### ISSUE TITLE
`GLIBC_2.29' not found error from pytorch-sparse=0.6.18

### ISSUE THREAD

**Issue by Barcavin** [pyg-team/pytorch_geometric#8217]
### 😵 Describe the installation problem

I'd like to install PyG 2.4.0 from Conda:
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 pyg=2.4 pytorch-sparse -c pytorch -c nvidia -c pyg
```
when I run
```
python -c "import torch_sparse"
```
it will throw error:
```
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /xxxxxx/.conda/envs/jupyter/envs/pyg240/lib/python3.11/site-packages/torch_sparse/_metis_cuda.so)
```
Here, pytorch-sparse=0.6.18 Pytorch=2.1.0

However, if I install it with pytorch-sparse=0.6.17:
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 pyg=2.4 pytorch-sparse=0.6.17 -c pytorch -c nvidia -c pyg
```
which will force pytorch to be 2.0.1. Then it works fine when loading torch-sparse.

Specifying Pytorch version:
```
conda install pytorch=2.1.0 torchvision torchaudio pytorch-cuda=11.8 pyg=2.4 pytorch-sparse=0.6.17 -c pytorch -c nvidia -c pyg
```
won't help as there is no compatible version for pytorch-sparse=0.6.17 and pytorch=2.1.0.

Does pyg=2.4.0 only work for pytorch=2.1.0, especially for the torch compiling functions?

**Comment by rusty1s** [comment]
We are currently building wheels via Ubuntu 20.04, which seems to enforce `GLIBC_2.29` usage. I am not yet sure how to fix this since any older Ubuntu version support was removed from GitHub CI :(

**Comment by Barcavin** [comment]
will building pytorch-sparse from the source solve the problem?

**Comment by rusty1s** [comment]
Yes.

**Comment by JTaozhang** [comment]
So, what is the solution for this uncompatible problem? install it from source?

**Comment by rusty1s** [comment]
The solution is that I fix this on our end. In the meantime, you need to install from source.

**Comment by rusty1s** [comment]
Should be fixed :)

**Comment by pujacomputes** [comment]
Hi, I actually ran into the same problem recently. I think I'm using the latest packages, so maybe something else is wrong? My environment details are below. I was wondering if you had any suggestions? I'm trying to use the NeighborSampler and that requires pyg-lib/torch-sparse. My system doesn't have glib_2.29 installed, and I don't have priveleges to update that myself I believe. Any help is appreciated! 

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.9 (Ootpa)
Release:        8.9
Codename:       Ootpa
```

```
torch==2.2.0+cu118
torch_cluster==1.6.3+pt22cu118
torch_geometric==2.4.0
torchaudio==2.2.0+cu118
torchmetrics==0.11.4
torchvision==0.17.0+cu118
```

```
rpm -qa | grep glibc
glibc-2.28-236.el8_9.12.x86_64
glibc-common-2.28-236.el8_9.12.x86_64
glibc-utils-2.28-236.el8_9.12.x86_64
glibc-static-2.28-236.el8_9.12.x86_64
glibc-gconv-extra-2.28-236.el8_9.12.x86_64
glibc-2.28-236.el8_9.12.i686
glibc-langpack-en-2.28-236.el8_9.12.x86_64
glibc-devel-2.28-236.el8_9.12.x86_64
glibc-all-langpacks-2.28-236.el8_9.12.x86_64
glibc-headers-2.28-236.el8_9.12.i686
glibc-devel-2.28-236.el8_9.12.i686
glibc-gconv-extra-2.28-236.el8_9.12.i686
glibc-headers-2.28-236.el8_9.12.x86_64
```

**Comment by JTaozhang** [comment]
Hi there,

Yes. Your right. My experience is also the reason of the incompatibility of the new version of PyTorch with your system. More details seems to be that the new PyTorch version need you updating the gnu compiler package. When I adopt lower version of PyTorch, it works.

Best,
Tao

On Mar 17, 2024, at 10:22, pujacomputes ***@***.***> wrote:

﻿

Hi, I actually ran into the same problem recently. I think I'm using the latest packages, so maybe something else is wrong? My environment details are below. I was wondering if you had any suggestions? I'm trying to use the NeighborSampler and that requires pyg-lib/torch-sparse. My system doesn't have glib_2.29 installed, and I don't have priveleges to update that myself I believe. Any help is appreciated!

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.9 (Ootpa)
Release:        8.9
Codename:       Ootpa


torch==2.2.0+cu118
torch_cluster==1.6.3+pt22cu118
torch_geometric==2.4.0
torchaudio==2.2.0+cu118
torchmetrics==0.11.4
torchvision==0.17.0+cu118


rpm -qa | grep glibc
glibc-2.28-236.el8_9.12.x86_64
glibc-common-2.28-236.el8_9.12.x86_64
glibc-utils-2.28-236.el8_9.12.x86_64
glibc-static-2.28-236.el8_9.12.x86_64
glibc-gconv-extra-2.28-236.el8_9.12.x86_64
glibc-2.28-236.el8_9.12.i686
glibc-langpack-en-2.28-236.el8_9.12.x86_64
glibc-devel-2.28-236.el8_9.12.x86_64
glibc-all-langpacks-2.28-236.el8_9.12.x86_64
glibc-headers-2.28-236.el8_9.12.i686
glibc-devel-2.28-236.el8_9.12.i686
glibc-gconv-extra-2.28-236.el8_9.12.i686
glibc-headers-2.28-236.el8_9.12.x86_64
