### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wjlpku** [pyg-team/pytorch_geometric#822]
## To Reproduce
python gcn.py

1.cd example
1.python gcn.py
1.
Epoch: 297, Loss: 0.0153
Epoch: 298, Loss: 0.0104
Epoch: 299, Loss: 0.0111
Epoch: 300, Loss: 0.0134
Accuracy: 0.8150
Segmentation fault (core dumped)

## Expected behavior
no Segmentation fault

## Environment

* OS:                          Ubuntu
* Python version:       3.7.3
* PyTorch version:      1.3.1
* CUDA/cuDNN version: Cuda compilation tools, release 10.0, V10.0.130
* GCC version:    gcc version 7.4.0
* Any other relevant information:

## Additional context
Each time I run the code in the example , I get the Segmentation fault

**Comment by rusty1s** [comment]
Do you know where the Segmentation fault is happening?
