### ISSUE TITLE
Manipulation tools for Batches

### ISSUE THREAD

**Issue by mova** [pyg-team/pytorch_geometric#8226]
### 🚀 The feature, motivation and pitch

Currently,  Batches should not manipulated once created.
Yet, I would be useful to be able 
- create batches from an index (`init_batch`)
- add features for the nodes/edges/graph (`add_?_attr`)
- concatenate and slice batches (`from_batch_list` and TBD)
without turning the batch into a list and batching the list again.
I have implemented these functions here:
https://github.com/DeGeSim/caloutils/blob/main/caloutils/utils/batch.py
Tests 
https://github.com/DeGeSim/caloutils/blob/main/tests/test_batch.py
Do you see any chance of integrating this? 
What would need to happen before that? 
Cheers!

**Comment by rusty1s** [comment]
Thanks for the issue. Can you clarify what `init_batch` and `add_?_attr` would do? More efficient concatenating and slicing batches is a cool, and I am happy to include them if you wanna give it a shot.

**Comment by mova** [comment]
`init_batch` would provide an "empty" batch object, just containing `batch.batch`.
With `add_node_attr` we can then add the `batch.x` later, with `batch._slice_dict` and `batch._inc_dict`  updated accordingly.
Here an example from the tests:
```
    batch_size = 3
    node_range = (1, 10)
    nodes_v = torch.randint(*node_range, (batch_size,)).to(device)
    x_list = [torch.rand(n, 3).to(device) for n in nodes_v]
    graph_attr_list = torch.rand(batch_size).to(device)

    batch_list = [Data(x=x, ga=ga) for x, ga in zip(x_list, graph_attr_list)]
    batch_truth = Batch.from_data_list(batch_list)
    batch_idx = batch_truth.batch
    batch = init_batch(batch_idx)
    add_node_attr(batch, "x", torch.vstack(x_list))
    add_graph_attr(batch, "ga", graph_attr_list)
    compare(batch_truth, batch)
```

**Comment by mova** [comment]
Currently `init_batch` takes the mapping from the points to the graph as an input. 
I'd like to change that to a vector containing the number of points per graph.
Ideally `init_batch` would become the new constructor or a classmethod like `Batch.from_num_points`.
The `add_?_method` I would like to turn into methods of the batch class, replacing the `batch` argument with`self`. 
What I'm currently wondering is how to make that work with `Batch` objects derived from `HeteroData`.

**Comment by rusty1s** [comment]
Mh, I am not sure I see the point in `init_batch` yet. Wouldn't it be sufficient to support something like
```python
batch = Batch()
batch.batch = ...
batch.x = ...
```

**Comment by mova** [comment]
Ah, yes. The only thing I would like to make sure is that the batchidx is available when x is added as a variable.
```python
batch = Batch(batchidx) # constructing batch.batch and batch.ptr
batch.x = ...
```

**Comment by mova** [comment]
I updated the code into a class here:
https://github.com/DeGeSim/caloutils/blob/main/caloutils/utils/superbatch.py
and test / usage examples are here:
https://github.com/DeGeSim/caloutils/blob/main/tests/test_superbatch.py
Maybe there is a smarter way to do all this.

**Comment by mova** [comment]
I've implemented a extension of the Batch class here:
https://github.com/DeGeSim/caloutils/blob/main/caloutils/utils/superbatch.py
With tests/examples here:
https://github.com/DeGeSim/caloutils/blob/main/tests/test_superbatch.py

**Comment by rusty1s** [comment]
Thank you. Do you have interest in submitting a PR for this?

**Comment by mova** [comment]
Yes, I will. It may take a bit, Im not available  next week. 
 Would you want this in the `data.Batch` class or in a new class? 
It looks to me like the existing Batch class can handle heterogeneous graphs, while my current implementation would likely need significant work to handle that. I haven't checked though. 

Am 26. Oktober 2023 20:45:42 MESZ schrieb Matthias Fey ***@***.***>:

**Comment by rusty1s** [comment]
We would need to integrate this into `Batch`. I am okay with restricting this to homogeneous graphs for now. We should also start with `cat` and `slice` since I think these are the most important ones.
