### ISSUE TITLE
torch_geometric 2.4.0 version does not work with stable baselines3 model load function

### ISSUE THREAD

**Issue by Fengtao22** [pyg-team/pytorch_geometric#8229]
### 🐛 Describe the bug

Installed torch_geometric 2.4.0 with stable-baselines 2.1.0, python 3.9. Training process runs well, but when loading the trained model into the stable-baselines, got the issue "While copying the parameter named "xxx.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([yyy])." shown in the fig:

![image](https://github.com/pyg-team/pytorch_geometric/assets/98062703/556653cc-e471-45f6-a949-5a567bffa9ac)

After downgrade torch_geometric to 2.3.1. Issue is solved.

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.1.0
* OS: Linux
* Python version: 3.9.18
* CUDA/cuDNN version: 
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by akihironitta** [comment]
Do you have a script to reproduce this?

Could be related to #8234 cc @puririshi98

**Comment by Fengtao22** [comment]
> Do you have a script to reproduce this?
> I was replicating the repo (https://github.com/zerongxi/graph-sdc/tree/main) and the issue happens when I tried to evaluate the learned policy. This should be the same as #8234.

**Comment by rusty1s** [comment]
Fixed via https://github.com/pyg-team/pytorch_geometric/pull/8242.
