### ISSUE TITLE
How to use GPSConv to the node classification task ?

### ISSUE THREAD

**Issue by OswaldoBornemann** [pyg-team/pytorch_geometric#8261]
### 🐛 Describe the bug

How do we use GPSConv for the node classification task?

**Comment by rusty1s** [comment]
You can just drop the global readout operator [here](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/graph_gps.py#L78). This will give you node-level predictions instead of graph-level predictions.

**Comment by OswaldoBornemann** [comment]
I see. So i only need to add a linear to classify it?

**Comment by OswaldoBornemann** [comment]
I tried to use the `GPS` class to cora dataset by using the following code

`x_node_emb = model.node_emb(test_batch.x)`

 However, I got the following error:

`RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)
`

**Comment by OswaldoBornemann** [comment]
@rusty1s I define the network below, could you please help me check it whether is correct? Because based on the following architecture, I got the worse results than GCN.

```
      self.node_emb = torch.nn.Linear(input_dim, hidden_dim - pe_dim)
      self.pe_lin = torch.nn.Linear(walk_len, pe_dim)
      self.pe_norm = BatchNorm1d(walk_len)

      # self.layer_1 = SAGEConv(hidden_dim, hidden_dim)

      self.convs = torch.nn.ModuleList()
      for _ in range(num_layers):
          sageconv = SAGEConv(hidden_dim, hidden_dim)
          conv = GPSConv(hidden_dim, sageconv, heads=4,
                         attn_type="multihead", attn_kwargs={"dropout": 0.5})
          self.convs.append(conv)

      self.redraw_projection = RedrawProjection(
          self.convs,
          None)

      self.Linear1 = torch.nn.Linear(hidden_dim, num_classes)
```

**Comment by rusty1s** [comment]
Ok, so you resolved the issue? I think it is expected that this architecture doesn't work that well on Cora, since you will just overfit.

**Comment by OswaldoBornemann** [comment]
I see. I will try to solve the problem.
