### ISSUE TITLE
to_homogeneous() Fails When an Edges Storage contains "edge_attrs"

### ISSUE THREAD

**Issue by fierval** [pyg-team/pytorch_geometric#8270]
### 🐛 Describe the bug

When calling `.to_homogeneous`, the following occurs (in `hetero_data.py`):

![image](https://github.com/pyg-team/pytorch_geometric/assets/987574/057b51fd-b9a9-4a85-9d39-51a047bb0e27)

This is due to one of the keys in the store being named `edge_attrs`, which apparently resolves to a method rather than tensor:
```Python
type(data[GraphConsts.RECEIPT_SCANNEDBY_USER.value].edge_attrs)
<class 'method'>
```

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.1.0
* OS: Win11
* Python version: 3.10
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): 
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
I tried to reproduce this in https://github.com/pyg-team/pytorch_geometric/pull/8275, and I am pretty sure this is already fixed in master (it doesn't look like you are on PyG 2.4 though). Feel free to re-open if your issue remains.
