### ISSUE TITLE
Pass weight_attr as map to NeighborLoader for HeteroData object 

### ISSUE THREAD

**Issue by shubhamjmeesho** [pyg-team/pytorch_geometric#8291]
### 🚀 The feature, motivation and pitch

Currently NeighborLoader expects weight_attr argument as string, but it would be better if this could be a map of node type to attribute name. I am also not clear on how to pass the attribute name string as torch_geometric.data.Data object does not store the node features names. Shouldn't this be passed as the feature index number instead?

**Comment by rusty1s** [comment]
Let's discuss in https://github.com/pyg-team/pytorch_geometric/discussions/8290
