### ISSUE TITLE
GPU-OUT of memory

### ISSUE THREAD

**Issue by moghadas76** [pyg-team/pytorch_geometric#8316]
### 🐛 Describe the bug

```
[/usr/local/lib/python3.10/dist-packages/torch_geometric/nn/conv/gat_conv.py](https://localhost:8080/#) in message(self, x_j, alpha)
    308 
    309     def message(self, x_j: Tensor, alpha: Tensor) -> Tensor:
--> 310         return alpha.unsqueeze(-1) * x_j
    311 
    312     def __repr__(self) -> str:
```

### Environment

* PyG version: latest
* PyTorch version: 2.1.0
* OS: ubuntu
* Python version: 3.10
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by akihironitta** [comment]
I'd recoomend https://pytorch.org/docs/stable/notes/faq.html to avoid OOM :)
