### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by trialan** [pyg-team/pytorch_geometric#8324]
### 📚 Describe the documentation issue

Is there still a slack group? All links are broken here and on readthedocs.

**Comment by rachitk** [comment]
While waiting for the maintainers to respond - yes, there is still a Slack group. 

Slack invite links expire after 400 people have joined using them on Slack (or after a predefined amount of time), so it may just be that it needs to be updated.

**Comment by rusty1s** [comment]
Updated, sorry for any trouble :(

**Comment by muety** [comment]
Slack is is broken again :link: Is the Slack community still existing?

**Comment by akihironitta** [comment]
@muety Thanks for reporting! You can use this link for the time being: https://join.slack.com/t/torchgeometricco/shared_invite/zt-2ppirgs10-_krkJVMgCeXiP92jDCRbig
