### ISSUE TITLE
Unable to load amazon photo dataset in PYG 1.7.1

### ISSUE THREAD

**Issue by pintu-dot** [pyg-team/pytorch_geometric#8338]
### 🐛 Describe the bug

I have set up a virtual environment to compare my method with an existing method. Code for existing method does not work on newer version of torch. 

I am trying to load amazon data set using following code

`from torch_geometric.datasets import Amazon
dataset = Amazon(root='data/Amazon', name='Photo')`

amazon dataset is available in PYG documentation, but the above line gives following error

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 5
      2 from torch_geometric.transforms import NormalizeFeatures
      3 from torch_geometric.datasets import Amazon
----> 5 dataset = Amazon(root='data/Amazon', name='Photo')
      6 data_b = dataset[0]  # Get the first graph object.
      7 data=conv_to_bin(data_b,dataset.num_classes)

File ~/anaconda3/envs/ngn/lib/python3.8/site-packages/torch_geometric/datasets/amazon.py:41, in Amazon.__init__(self, root, name, transform, pre_transform)
     39 assert self.name in ['computers', 'photo']
     40 super().__init__(root, transform, pre_transform)
---> 41 self.data, self.slices = torch.load(self.processed_paths[0])

File ~/anaconda3/envs/ngn/lib/python3.8/site-packages/torch/serialization.py:594, in load(f, map_location, pickle_module, **pickle_load_args)
    592             opened_file.seek(orig_position)
    593             return torch.jit.load(opened_file)
--> 594         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    595 return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)

File ~/anaconda3/envs/ngn/lib/python3.8/site-packages/torch/serialization.py:853, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    851 unpickler = pickle_module.Unpickler(data_file, **pickle_load_args)
    852 unpickler.persistent_load = persistent_load
--> 853 result = unpickler.load()
    855 torch._utils._validate_loaded_sparse_tensors()
    857 return result

ModuleNotFoundError: No module named 'torch_geometric.data.storage'`

Any help will be greatly appreciated 

### Environment

* PyG version: 1.7.1
* PyTorch version: 1.7.1+cu110
* OS: Debian
* Python version: 3.8
* CUDA/cuDNN version: 110
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by akihironitta** [comment]
@pintu-dot AFAIK, you need to use a newer version of PyG as I see that `torch_geometric.data.storage` doesn't exist in 1.7.1: https://github.com/pyg-team/pytorch_geometric/commit/2718a804d9c898131de695cc7d30492efa0416ae

**Comment by rusty1s** [comment]
Alternatively, you can remove the `processed` directory and re-process it.

**Comment by pintu-dot** [comment]
> Alternatively, you can remove the `processed` directory and re-process it.

any guidance on how to do so

**Comment by pintu-dot** [comment]
> @pintu-dot AFAIK, you need to use a newer version of PyG as I see that `torch_geometric.data.storage` doesn't exist in 1.7.1: [2718a80](https://github.com/pyg-team/pytorch_geometric/commit/2718a804d9c898131de695cc7d30492efa0416ae)

existing method runs only on version 1.7.1, gives some gradient related error on higher versions of pyg

**Comment by EdisonLeeeee** [comment]
> > Alternatively, you can remove the `processed` directory and re-process it.
> 
> any guidance on how to do so

@pintu-dot Delete `data/Amazon/Photo/processed` and re-run `dataset = Amazon(root='data/Amazon', name='Photo')` again.

**Comment by pintu-dot** [comment]
> > > Alternatively, you can remove the `processed` directory and re-process it.
> > 
> > 
> > any guidance on how to do so
> 
> @pintu-dot Delete `data/Amazon/Photo/processed` and re-run `dataset = Amazon(root='data/Amazon', name='Photo')` again.

Thanks worked
