### ISSUE TITLE
Generating Graph Data Object on the fly cause RAM to Explode After A Few Epochs

### ISSUE THREAD

**Issue by Sirius-zn** [pyg-team/pytorch_geometric#834]
## ❓ Questions & Help
Hello, 

In my application, I am generating graphs on the fly using torch_geometric.data objects. Specifically, I am creating a set of new edge_attr, edge_index, and x variables for each of my new graph data objects. These data objects get appended to a graph_object_list. Then the graph_object_list will be used to create a DataLoader object. After processing all the data inside this DataLoader object, graph_object_list gets emptied (using graph_object_list = []) and the same process described above will repeat itself again and again.

I am experiencing CPU RAM explosion after a few epochs. It seems to be coming from the fact that edge_attr and edge_index objects are not being freed probably. If I only use one pair of global edge_index and edge_attr objects, the program runs fine. If I generate unique edge_index edge_attr on the fly for each new graph, I will have RAM explosion problem. 

Is there a way I can destroy these edge_attr and edge_index objects explicitly? Since the graph data objects build from these old edge_attr and edge_index objects are no longer in the gragh_object_list, shouldn't they all get cleared by garbage collector? 

I tried calling del keyword explicitly on each of the data object in the graph_object_list as well as on the edge_attr and edge index variables after use. I also tried import gc, gc.collect(). Both didn't help with the situation.

**Comment by rusty1s** [comment]
The only way I can think of that RAM gets not freed is when PyTorch is not clearing its computation graph. Normally, tensors should get freed automatically in case they are not longer needed. Sadly, I do not have much more advice for you and I never witnessed it myself. If you show me a minimal reproducible example, I can help further.
