### ISSUE TITLE
Add an option to reload (re-process) datasets

### ISSUE THREAD

**Issue by EdisonLeeeee** [pyg-team/pytorch_geometric#8349]
### 🛠 Proposed Refactor

Add an option to `Dataset` and allow users to re-process the dataset to meet any API or data changes.

```python
from torch_geometric.datasets import Planetoid
dataset = Planetoid(..., reload=True) # re-process the raw data

```

### Suggest a potential alternative/fix

Add an option (e.g., `reload` or `reprocess`) to `torch_geometric.data.Dataset` and its subclasses.

**Comment by rusty1s** [comment]
I like this idea. Instead of changing the interface in trillions of datasets, shall we just do `dataset.force_reload()`?

**Comment by EdisonLeeeee** [comment]
Sounds great. But what is the logic? Haven't any idea in mind to to so :(

**Comment by rusty1s** [comment]
Oh, right. It's tricky to implement this outside of `__init__`. Then let's go with the initial solution.

**Comment by EdisonLeeeee** [comment]
Just made an initial PR for it #8352
