### ISSUE TITLE
possibillity to change nn operator in DynEdgeConv

### ISSUE THREAD

**Issue by pietroastolfi** [pyg-team/pytorch_geometric#835]
## ❓ Questions & Help

Hi,
first of all congrats for the library. Very useful. 
Then, my question regards the paper DGCNN, that in pyg is implemented through DynEdgeConv. As in the original implementation of this model they use conv2d and conv1d, where by changing the filter size you can actually tackle other data wrt to point-clouds. I tried to replicate the use of this conv operators (instead of Linear) in pyg, but I got errors in the MessagePassing forward since these operators (conv1d and conv2d) expect a 3d / 4d input and by feeding the model with a pyg.Batch where pyg.Btach.x is 2d, I get size mismatch.  Can you suggest me a viable solution if there is?

Hope it's all clear, ow ask me 

thanks  

Pietro

**Comment by pietroastolfi** [comment]
referring the DEC  example the change I tried is the following:
```
nn1 = nn.Sequential(nn.Conv1d(2*input_size,64,fov), nn.ReLU(),nn.Conv1d(64,64,3)) 
        self.conv1 = DynamicEdgeConv(nn1, k, aggr)
nn2 = nn.Sequential(nn.Conv1d(2*64,128,fov), nn.ReLU(), nn.Conv1d(128,512,fov))
        self.conv2 = DynamicEdgeConv(nn2, k, aggr)
nn3 = nn.Sequential(nn.Conv1d(2*512,512,fov), nn.ReLU(), nn.Conv1d(512,embedding_size,fov))
```

**Comment by rusty1s** [comment]
Well, the 1x1 `conv1d` operations do exactly what the linear layers are doing, projecting each message individually into a high-dimensional space. I am not sure which problem you are trying to solve here using `conv` operations. How do you want your input to look?

**Comment by pietroastolfi** [comment]
I would like to loose the invariance to the input order (guaranteed by linear / conv1d(1x1)). Since I would like to use conv1d with a filter of nx1, n>1

**Comment by pietroastolfi** [comment]
Do you think is possible to do what I am trying to do?

**Comment by rusty1s** [comment]
Not with the means of the `MessagePassing` interface, but you can use the `knn_graph` method to find the nearest `k` neighbors, reshape the resulting tensor to `[N,K,F]` and employ your convolutions afterwards.
