### ISSUE TITLE
incidence matrix problems with HypergraphConv class?

### ISSUE THREAD

**Issue by mianbaodaxia** [pyg-team/pytorch_geometric#840]
## ❓ Questions & Help
Hi, it's very nice to find the hypergraph convolution implementation here, however, i found something confused in HypergraphConv class codes. 

The hyperedge_index in forward/\_forward\_ seems only to support 2\*num_edge shape, which is in fact a simple graph.
So if i have an incidence matrix of hypergraph with shape of num_node\*num_edge, how can i use HypergraphConv to do hypergraph convolution 
\mathbf{X}^{\prime} = \mathbf{D}^{-1} \mathbf{H} \mathbf{W} \mathbf{B}^{-1} \mathbf{H}^{\top} \mathbf{X} \mathbf{\Theta}

thanks

**Comment by rusty1s** [comment]
`hyper_edge_index` refers to the sparse indices of the incidence matrix `H` of shape [N, M] in the paper. It is still expects a `[2, num_entries]` layout though with `hyper_edge_index[0]` holding values between `0-N-1` and `hyper_edge_index[1]` holding values between `0-M-1`.
