### ISSUE TITLE
Potential Bug w. the Addition of GDC?

### ISSUE THREAD

**Issue by emanuelazcona** [pyg-team/pytorch_geometric#843]
`-----------------------------------------------------------------------
RuntimeError                          Traceback (most recent call last)
<ipython-input-1-09a0f6707436> in <module>
     14 
     15 import torch
---> 16 import torch_geometric
     17 
     18 from torch_geometric.transforms import LaplacianLambdaMax

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/__init__.py in <module>
      3 import torch_geometric.data
      4 import torch_geometric.datasets
----> 5 import torch_geometric.transforms
      6 import torch_geometric.utils
      7 

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/__init__.py in <module>
     34 from .delaunay import Delaunay
     35 from .to_superpixels import ToSLIC
---> 36 from .gdc import GDC
     37 
     38 __all__ = [

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/gdc.py in <module>
      8 
      9 
---> 10 class GDC(object):
     11     r"""Processes the graph via Graph Diffusion Convolution (GDC) from the
     12     `"Diffusion Improves Graph Learning" <https://www.kdd.in.tum.de/gdc>`_

/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/gdc.py in GDC()
    486 
    487     @staticmethod
--> 488     @numba.njit(cache=True)
    489     def __calc_ppr__(indptr, indices, out_degree, alpha, eps):
    490         r"""Calculate the personalized PageRank vector for all nodes

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/decorators.py in wrapper(func)
    192                           **dispatcher_args)
    193         if cache:
--> 194             disp.enable_caching()
    195         if sigs is not None:
    196             # Register the Dispatcher to the type inference mechanism,

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/dispatcher.py in enable_caching(self)
    677 
    678     def enable_caching(self):
--> 679         self._cache = FunctionCache(self.py_func)
    680 
    681     def __get__(self, obj, objtype=None):

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/caching.py in __init__(self, py_func)
    612     def __init__(self, py_func):
    613         self._name = repr(py_func)
--> 614         self._impl = self._impl_class(py_func)
    615         self._cache_path = self._impl.locator.get_cache_path()
    616         # This may be a bit strict but avoids us maintaining a magic number

/usr/local/lib/python3.6/dist-packages/numba-0.46.0-py3.6-linux-x86_64.egg/numba/caching.py in __init__(self, py_func)
    347         else:
    348             raise RuntimeError("cannot cache function %r: no locator available "
--> 349                                "for file %r" % (qualname, source_path))
    350         self._locator = locator
    351         # Use filename base name as module name to avoid conflict between

RuntimeError: cannot cache function 'GDC.__calc_ppr__': no locator available for file '/usr/local/lib/python3.6/dist-packages/torch_geometric-1.3.2-py3.6.egg/torch_geometric/transforms/gdc.py'`

**Comment by rusty1s** [comment]
Yeah, it seems related to [this thread](https://github.com/ska-sa/montblanc/issues/253). Our `readthedocs` builds fail for this same reason. I am working on it, and I expect it to be fixed today. In the meantime, you can just comment out the `GDC` import in `transforms/__init__.py`.

**Comment by rusty1s** [comment]
Should be fixed in master!
