### ISSUE TITLE
regression on qm7 dataset

### ISSUE THREAD

**Issue by ibnopcit** [pyg-team/pytorch_geometric#844]
## ❓ Questions & Help

Great work with this.  

I'm trying to get a basic regression working on the qm7 dataset and am having trouble adapting the other examples.

Some examples (`cora.py`, `qm9_nn_conv.py`) seed the initial convolution in the `forward` method with the features `x`.  The qm7 dataset is unusual in that it has no `x`, just edge indices and edge attributes.  I've tried starting the convolution with a dummy tensor, which works in a limited way, but I'm running into mismatched shape issues which make me think I'm missing something about the data structure, and this is probably not the right approach in the first place.

What would a minimally functional `Net` look like for the qm7 dataset?

I haven't been able to run the complete qm9 example because of the issue mentioned [here](https://github.com/rusty1s/pytorch_geometric/issues/511#issuecomment-511034818).

**Comment by rusty1s** [comment]
Regarding the `QM9` bug, please delete the root folder and try to download it again. I haven't looked into the `QM7` dataset that closely myself, are there any papers using it?

**Comment by ibnopcit** [comment]
Ok `QM9` is working iff you have `rdkit` installed.  The fallback onto the preprocessed version is broken.

I haven't found a paper that does GNN on `QM7`, will keep looking.

**Comment by rusty1s** [comment]
Downloading pre-processed `QM9` works for me so I am not really sure why this is happening:
```
Processing...
Using a pre-processed version of the dataset. Please install `rdkit` to alternatively process the raw data.
Done!
QM9(132480)
Data(edge_attr=[8, 4], edge_index=[2, 8], pos=[5, 3], x=[5, 13], y=[1, 16])
```
