### ISSUE TITLE
CI Failures: CuGraph GATConv & dmon pooling

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#8456]
### 🐛 Describe the bug

log attached
[log.txt](https://github.com/pyg-team/pytorch_geometric/files/13480705/log.txt)

### Environment

latest stack as of today

**Comment by rusty1s** [comment]
Thanks, will be fixed with https://github.com/pyg-team/pytorch_geometric/pull/8464.
