### ISSUE TITLE
EdgeStorage redundantly checks for Tensor type instead of ndarray type

### ISSUE THREAD

**Issue by LucaButera** [pyg-team/pytorch_geometric#8480]
### 🐛 Describe the bug

In [https://github.com/pyg-team/pytorch_geometric/blob/408d23e161cf53698fdc5f0c5b64c3a74c558df9/torch_geometric/data/storage.py#L457C13-L462C44](EdgeStorage.num_edges), the implementation redundantly checks if the current value is a Tensor. I imagine the intended behavior, on the second check, is to look for a ndarray. The current implementation is at best redundant but, in the worst case, can lead to unexpected behavior.

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.1.0
* OS: MacOS (M1)
* Python version: 3.11
* CUDA/cuDNN version: None
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): None

**Comment by rusty1s** [comment]
Thanks for spotting. Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/8487
