### ISSUE TITLE
About Cora Dataset

### ISSUE THREAD

**Issue by chanderler** [pyg-team/pytorch_geometric#852]
Hello, I notice that in your implementation, Cora dataset contains 10556 edges. But many papers in recent years adopted settings of 5429 edges(5429*2=10858). Why is there such a difference?

**Comment by rusty1s** [comment]
Because the Cora dataset is holding duplicated edges, which we remove in a pre-processing step. See https://github.com/rusty1s/pytorch_geometric/issues/343.

**Comment by chanderler** [comment]
Thank you very much!
