### ISSUE TITLE
`PCQnm4v2` dataset is regression and `data.y` gives ugly error message, could use a nicer error message

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#8543]
### 🐛 Describe the bug

```
Traceback (most recent call last):
  File "/opt/pyg/pytorch_geometric/x.py", line 195, in <module>
    main()
  File "/opt/pyg/pytorch_geometric/x.py", line 136, in main
    model = GCN(-1, args.emb_dim, args.num_layers, out_channels=train_dataset.num_classes, dropout=args.drop_ratio ).to(device)
  File "/opt/pyg/pytorch_geometric/torch_geometric/data/dataset.py", line 173, in num_classes
    y = torch.cat([data.y for data in data_list if 'y' in data], dim=0)
TypeError: expected Tensor as element 0 in argument 0, but got float
```

code used to repro:
[ondiskdrugdisc.py.zip](https://github.com/pyg-team/pytorch_geometric/files/13573430/ondiskdrugdisc.py.zip)

### Versions

latest stack

**Comment by rusty1s** [comment]
This is a regression dataset, so `dataset.num_classes` is expected to fail. We can still print out a better error message though.

**Comment by puririshi98** [comment]
oh shoot thanks for lmk, that solves my issue lol, hand't looked too closely into the dataset yet. ill leave this issue about the error message in case this is something you want to edit.
