### ISSUE TITLE
Transforms fail to work when using torch.utils.data.random_split to split graphs

### ISSUE THREAD

**Issue by lurenyi233** [pyg-team/pytorch_geometric#8557]
### 🐛 Describe the bug

Hi, I have a graph-level classification task and plan to split the dataset to train and test sets randomly.  I use `torch.utils.data.random_split` to split graphs. There is no error with dataset splitting, dataloader creating, and input to models for training, but it looks like I can't apply the `torch_geometric.transforms` methods to the split dataset, as the example shown below.

```
from torch_geometric.datasets import GNNBenchmarkDataset
import torch_geometric.transforms as T
from torch.utils.data import random_split

dataset = GNNBenchmarkDataset(root = "./data/CSL", name="CSL") # get a graph level classification dataset

# use random_split to split the dataset
train_dataset, test_dataset = random_split(dataset, [100, 50])
print("Before transform: ", train_dataset[0]) # Data(edge_index=[2, 164], y=[1], num_nodes=41)
train_dataset.transform = T.OneHotDegree(max_degree=5) # do a transform, e.g., add some node features
print("After transform: ", train_dataset[0]) # Data(edge_index=[2, 164], y=[1], num_nodes=41)

# NOTE: the bug is that it fails to add node features
# NOTE: After `random_split`, the train_set is torch.utils.data.dataset.Subset object

```

If I split the dataset manually, the `torch_geometric.transforms` methods can be applied successfully:
```
from torch_geometric.datasets import GNNBenchmarkDataset
import torch_geometric.transforms as T
from torch.utils.data import random_split

dataset = GNNBenchmarkDataset(root = "./data/CSL", name="CSL") # get a graph level classification dataset

# manually split the dataset
train_dataset = dataset[:100]
test_dataset = dataset[100:]
print("Before transform: ", train_dataset[0]) # Data(edge_index=[2, 164], y=[1], num_nodes=41)
train_dataset.transform = T.OneHotDegree(max_degree=5) # do a transform, e.g., add some node features
print("After transform: ", train_dataset[0]) # Data(edge_index=[2, 164], y=[1], num_nodes=41, x=[41, 6])

# NOTE: successfully do the transform and add the node features.
# NOTE: After manually split, the train_set is CSL(100)
```
How do we do the graph-level random split correctly? The current way I use is to generate random indexes. It is better to mention using `random_split` is wrong here.

### Versions

torch: 2.1.0+cu118
torch_geometric: 2.4.0

**Comment by rusty1s** [comment]
it looks like `random_split` converts the dataset into a list of examples, which will indeed break `transform` usage. How about:
```python
train_idx, test_idx = random_split(range(len(dataset)), [100, 50])
train_dataset = dataset[train_idx]
test_dataset = dataset[test_idx]

**Comment by lurenyi233** [comment]
Thank

> it looks like `random_split` converts the dataset into a list of examples, which will indeed break `transform` usage. How about:
> 
> ```python
> train_idx, test_idx = random_split(range(len(dataset)), [100, 50])
> train_dataset = dataset[train_idx]
> test_dataset = dataset[test_idx]
> ```

You're right, it's more elegant than mine. 
Not sure if type checking should be added before transforming. I'll close this post and hope it helps someone else.
