### ISSUE TITLE
Cora Dataset TypeError in Colab Notebook "2. Node Classification with Graph Neural Networks"

### ISSUE THREAD

**Issue by tisabe** [pyg-team/pytorch_geometric#8572]
### 🐛 Describe the bug

It seems like the ```NormalizeFeatures``` transform produces a bug when calling ```num_classes``` on the Cora dataset.
I discovered this while running the Colab Notebook "2. Node Classification with Graph Neural Networks", so Google Colab is also where I am reproducing the error. Below is some code that reproduces the bug (on my colab):

```python
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures

# this DOES NOT produce an error:
dataset = Planetoid(root='data/Planetoid', name='Cora')
print(f'Number of classes: {dataset.num_classes}')

# this produces an error:
dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
print(f'Number of classes: {dataset.num_classes}')
```

This produces the following error:
```
TypeError                                 Traceback (most recent call last)

[<ipython-input-2-24edb7716247>](https://localhost:8080/#) in <cell line: 3>()
      1 # this produces an error:
      2 dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
----> 3 print(f'Number of classes: {dataset.num_classes}')

1 frames

[/usr/local/lib/python3.10/dist-packages/torch_geometric/data/in_memory_dataset.py](https://localhost:8080/#) in num_classes(self)
     88         if self.transform is None:
     89             return self._infer_num_classes(self._data.y)
---> 90         return super().num_classes
     91 
     92     def len(self) -> int:

[/usr/local/lib/python3.10/dist-packages/torch_geometric/data/dataset.py](https://localhost:8080/#) in num_classes(self)
    177         # with `RandomLinkSplit`, so we take care of this case here as well:
    178         data_list = _get_flattened_data_list([data for data in self])
--> 179         y = torch.as_tensor([data.y for data in data_list if 'y' in data])
    180 
    181         # Do not fill cache for `InMemoryDataset`:

TypeError: only integer tensors of a single element can be converted to an index
```

### Versions

PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.7
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.120+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        45 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0+cu118
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.2+pt21cu118
[pip3] torch-sparse==0.6.18+pt21cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchdata==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.16.0
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by rusty1s** [comment]
Thanks! Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/8576.
