### ISSUE TITLE
inverse of torch_geometric.transforms.NormalizeFeatures ?

### ISSUE THREAD

**Issue by paapu88** [pyg-team/pytorch_geometric#8703]
### 🚀 The feature, motivation and pitch

Dear Developers,
I could not find the inverse of `torch_geometric.transforms.NormalizeFeatures`

Is there such a function to get from the scale features back to the original space?
I would need this because trying to predict features over time.
Cheers, Markus

**Comment by akihironitta** [comment]
I don't think there is as `NormalizeFeatures` doesn't save the min and sum values:
https://github.com/pyg-team/pytorch_geometric/blob/09733b493493083ab7cb09faf60716308e270093/torch_geometric/transforms/normalize_features.py#L27-L28

**Comment by paapu88** [comment]
Thanks for pointing the source!

I probably must write the saving myself.

I had problems when doing myself std or minmax scaling (the model output was just nans) with
torch_geometric.nn.HANConv
but with torch_geometric.transforms.NormalizeFeatures
model was converging ok, and no nans were produced...
Cheers, Markus
