### ISSUE TITLE
GATv2Conv is not inference thread-safe

### ISSUE THREAD

**Issue by mathijs02** [pyg-team/pytorch_geometric#8741]
### 🐛 Describe the bug

Unexpectedly, the [`GATv2Conv`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GATv2Conv.html) layer is not thread-safe when it is used for inference. The reason for this is that the instance attribute `self._alpha` is modified when running `.forward()` and `.message()`, in particular [here](https://github.com/pyg-team/pytorch_geometric/blob/32e3872721b9475c760d54a2c22ca8365f957017/torch_geometric/nn/conv/gatv2_conv.py#L306) and [here](https://github.com/pyg-team/pytorch_geometric/blob/32e3872721b9475c760d54a2c22ca8365f957017/torch_geometric/nn/conv/gatv2_conv.py#L345). This problem hit me when I was deploying a model for inference in a multi-threaded environment.

This behaviour is different from other PyTorch Geometric layers, and other typical PyTorch layers. For example, [`GATConv`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GATConv.html), [`SAGEConv`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.SAGEConv.html#torch_geometric.nn.conv.SAGEConv) and [`GCNConv`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GCNConv.html) are inference thread-safe, because in these classes no instance attributes are modified during inference. Thread safety is not a hard requirement, but tends to be the case (see discussion [here](https://discuss.pytorch.org/t/is-inference-thread-safe/88583)).

The reason for opening is this issue is to understand whether this layer property is considered important in the PyTorch Geometric library. If yes, I think that an inference thread-safe implementation of `GATv2Conv` is possible, similar to how `GATConv` is designed.

Below you see a MWE that can reproduce the issue:
```python
import torch
import torch_geometric as tg

from multiprocessing.dummy import Pool


def inference(model):
    def predict(_):
        x = torch.rand(3,1)
        edge_index = torch.randint(0, 2, (2, 2))
        model(x, edge_index)
    return predict


def inference_multithread(model):
    thr = Pool(10)
    thr.map(inference(model), range(50))
```

When running
```python
inference_multithread(tg.nn.GATv2Conv(1, 1))
```
This results in an `AssertionError`, in particular [this line](https://github.com/pyg-team/pytorch_geometric/blob/32e3872721b9475c760d54a2c22ca8365f957017/torch_geometric/nn/conv/gatv2_conv.py#L305).

The following examples run without problems:
```python
inference_multithread(tg.nn.GATConv(1, 1))
inference_multithread(tg.nn.GCNConv(1, 1))
inference_multithread(tg.nn.SAGEConv(1, 1))
```

### Versions

python 3.9.12
torch 2.0.0
torch-geometric 2.4.0

Issue can be reproduced with other Python, PyTorch and PyTorch Geometric versions too.

**Comment by rusty1s** [comment]
Thanks for reporting. Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/8753.
