### ISSUE TITLE
warnings.warn('We do not recommend using the non-optimized CPU '

### ISSUE THREAD

**Issue by jieegao** [pyg-team/pytorch_geometric#876]
## ❓ Questions & Help
when i run the following example:
examples/mnist_voxel_grid.py

it stoped and warning :

python3.7/site-packages/torch_geometric/nn/conv/spline_conv.py:104: UserWarning: We do not recommend using the non-optimized CPU version of SplineConv. If possible, please convert your data to the GPU.
warnings.warn('We do not recommend using the non-optimized CPU '

how can i fix this? 
thanks!

**Comment by rusty1s** [comment]
What do you mean? We just recommend using SplineConv on GPU.

**Comment by Minhsuperfragile** [comment]
> What do you mean? We just recommend using SplineConv on GPU.

It's slow on CPU, but when I run my model on GPU it gives this error:

RuntimeError: kernel_size.device().is_cpu() INTERNAL ASSERT FAILED at "csrc/cpu/basis_cpu.cpp":59, please report a bug to PyTorch. kernel_size must be CPU tensor

How can I fix this.
