### ISSUE TITLE
Pytorch Geometric UPFD dataset retrieves Google Drive virus scan warning instead of data files

### ISSUE THREAD

**Issue by SteliosKliafas** [pyg-team/pytorch_geometric#8787]
### 🐛 Describe the bug

You can see the code below which I got from the tutorial found in the official github page. Instead of downloading the dataset it downloads the google drive virus warning html page. 

I got the hardcoded url with the dataset id and placed it in the browser and it gives the same warning that is downloaded instead of the datafiles but you can click "Download anyway" and the download starts. Is there a way to bypass this warning using the pytorch geometric library? 

(I will also attach the start of the file that is downloaded not the whole thing just so you can understand what is happening).

I saw the same issue happened in huggingface and they had to fix it https://github.com/huggingface/datasets/pull/3787

```import numpy as np
from torch_geometric.datasets import UPFD
from torch_geometric.loader import DataLoader
from torch_geometric.transforms import ToUndirected
import os.path as osp


path = osp.join(osp.dirname(osp.realpath(__file__)), 'UPFD')


if __name__ == "__main__":
    train = UPFD(path, 'gossipcop', 'profile', 'train', ToUndirected(), force_reload=True)
    val = UPFD(path, 'gossipcop', 'profile', 'val', ToUndirected())
    test = UPFD(path, 'gossipcop', 'profile', 'test', ToUndirected())

    train_loader = DataLoader(train, batch_size=128, shuffle=True)
    val_loader = DataLoader(val, batch_size=128, shuffle=False)
    test_loader = DataLoader(test, batch_size=128, shuffle=False)```



<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv=" .... so on

### Versions

I'm using the latest torch_geometric and torch versions and python 3.10

**Comment by rusty1s** [comment]
Thanks for reporting. We already fixed this in https://github.com/pyg-team/pytorch_geometric/pull/8766
