### ISSUE TITLE
in utils.subgraph.py  RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by allierc** [pyg-team/pytorch_geometric#8817]
### 🐛 Describe the bug

in utils.subgraph.py

edge_mask = node_mask[edge_index[0]] & node_mask[edge_index[1]]

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

because edge_index on 'cuda:0' and node_mask on 'cpu'

being solved with: node_mask=node_mask.to(device=device)

### Versions

last version

**Comment by rusty1s** [comment]
Is this a bug? `subset` and `edge_index` needs to be on the same device. If that's not the case, the code is expected to crash.

**Comment by allierc** [comment]
Thank you for your prompt reply.
You must be right, I'm new to Python and the error can be on my side

Subset and edge_index were not on the same device, this causes the error
subset was generated by transform RadiusGraph<https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.transforms.RadiusGraph.html#torch_geometric.transforms.RadiusGraph> or transform.largest_connected_components from a data on cuda:0
and ended up on the cpu whereas edge_index was cuda:0

I propose you to write the small piece of code that reproduce this error ?

Best,

Cedric
________________________________
De : Matthias Fey ***@***.***>
Envoyé : jeudi 25 janvier 2024 03:23
À : pyg-team/pytorch_geometric ***@***.***>
Cc : Allier, Cedric ***@***.***>; Author ***@***.***>
Objet : Re: [pyg-team/pytorch_geometric] in utils.subgraph.py RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu) (Issue #8817)

External Email: Use Caution



Is this a bug? subset and edge_index needs to be on the same device. If that's not the case, the code is expected to crash.

**Comment by rusty1s** [comment]
You are right, fix is here: #8831
