### ISSUE TITLE
Add Support for Pytorch 2.2

### ISSUE THREAD

**Issue by Foisunt** [pyg-team/pytorch_geometric#8853]
### 🚀 The feature, motivation and pitch

Pytorch 2.2 was released:
[Blog](https://pytorch.org/blog/pytorch2-2/)
[Release Notes](https://github.com/pytorch/pytorch/releases/tag/v2.2.0)

**Comment by rusty1s** [comment]
In the process of it. Should land today or tomorrow.

**Comment by rusty1s** [comment]
PyTorch 2.2 just landed on PyG master :)
