### ISSUE TITLE
GPU vs. CPU for Aggregation of Aggregation: Significant difference in terms of reproducibility and stable results

### ISSUE THREAD

**Issue by simonheilig** [pyg-team/pytorch_geometric#8866]
First, I want to say that I am aware of the existing [reproducibility issues with scatter ops](https://github.com/pyg-team/pytorch_geometric/issues/92).
But still, I expect that those numerical issues should not result in significant (i.e. > 1e-6) differences in computation.

In my case, I want to aggregate once, apply non-linearity and aggregate again with the same message passing module.
When doing this over multiple layers, those effects are very significant on gpu in comparison to perfect cpu.

For the sake of reproducing this behavior, I adopted the [introduction:learning-methods-on-graphs ](https://pytorch-geometric.readthedocs.io/en/latest/get_started/introduction.html#learning-methods-on-graphs) task. See the full script below.

The main model difference is in the forward method:
```
def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.emb(x)

        for _ in range(2):
            x = self.conv(x,edge_index)
            x = F.relu(x)
            y = self.conv(x,edge_index)
            x = x+y

        x = self.dec(x)
```
When training with a fixed seed multiple times, I get the following results:

```
cuda  loss  0.6542618870735168
cpu  loss  0.9095242023468018
cuda  loss  0.705021321773529
cpu  loss  0.9095242023468018
cuda  loss  0.8169752359390259
cpu  loss  0.9095242023468018
cuda  loss  0.6809478402137756
cpu  loss  0.9095242023468018
cuda  loss  0.6463167667388916
cpu  loss  0.9095242023468018
```
One can clearly see, that the cpu loss is perfect while using cuda things start to vary at 1e-1 precision!
Which is not expected at this bad precision. 
Please note, that this is only to demonstrate this effect and is not aiming for reasonable performance on the task.

### Full Training Script

```
import torch
import torch.nn.functional as F
import os.path as osp
from torch_geometric.nn import MessagePassing
from torch_geometric.datasets import Planetoid
from typing import Optional
import numpy as np
import random
import math

class VanillaConv(MessagePassing):
    def __init__(self,in_channels: int,out_channels:int):
        super().__init__(aggr = 'add')
        self.weight = torch.nn.Parameter(torch.empty((in_channels, out_channels)), requires_grad=True)
        self.set_transposed = False
        self.reset_parameters()

    def forward(self, x: torch.Tensor, edge_index: torch.Tensor, edge_weight: Optional[torch.Tensor] = None) -> torch.Tensor: 
        message = F.linear(x,self.weight)
        aggregation = self.propagate(edge_index, x=message, edge_weight=edge_weight)
        return aggregation
    
    def message(self, x_j: torch.Tensor, edge_weight: Optional[torch.Tensor] = None) -> torch.Tensor:
        return x_j if edge_weight is None else edge_weight.view(-1, 1) * x_j

    def reset_parameters(self,):
        torch.nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = torch.nn.Linear(dataset.num_node_features, 16)
        self.conv = VanillaConv(16,16)
        self.dec = torch.nn.Linear(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.emb(x)

        for _ in range(2):
            x = self.conv(x,edge_index)
            x = F.relu(x)
            y = self.conv(x,edge_index)
            x = x+y

        x = self.dec(x)

        return F.log_softmax(x, dim=1)
    
def train_model(device):
    seed = 41
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    
    model = GCN().to(device)
    data = dataset[0].to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
    model.train()
    for _ in range(200):
        optimizer.zero_grad()
        out = model(data)
        loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()

    print(device,' loss ',loss.detach().item())
    del model,optimizer
    
if __name__ == "__main__":
    device_cuda= torch.device('cuda')
    device_cpu = torch.device('cpu')

    path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'Planetoid')
    dataset = Planetoid(root=path, name='Cora')
    for i in range(5):
        train_model(device_cuda)
        train_model(device_cpu)

```

### Versions

Collecting environment information...
PyTorch version: 2.1.2
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1032-nvidia-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 525.125.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             224
On-line CPU(s) list:                0-223
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8480CL
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 56
Socket(s):                          2
Stepping:                           7
CPU max MHz:                        3800,0000
CPU min MHz:                        800,0000
BogoMIPS:                           4000.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
L1d cache:                          5,3 MiB (112 instances)
L1i cache:                          3,5 MiB (112 instances)
L2 cache:                           224 MiB (112 instances)
L3 cache:                           210 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-55,112-167
NUMA node1 CPU(s):                  56-111,168-223
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-lightning==2.1.3
[pip3] torch==2.1.2
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.2
[pip3] torch-sparse==0.6.18
[pip3] torchaudio==2.1.2
[pip3] torchcde==0.2.5
[pip3] torchdiffeq==0.2.3
[pip3] torchdyn==1.0.6
[pip3] torchmetrics==1.3.0.post0
[pip3] torchsde==0.2.6
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.8.0               h6a678d5_0    anaconda
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py38h5eee18b_1  
[conda] mkl_fft                   1.3.8            py38h5eee18b_0  
[conda] mkl_random                1.2.4            py38hdb19cb5_0  
[conda] numpy                     1.24.3           py38hf6e8229_1  
[conda] numpy-base                1.24.3           py38h060ed82_1  
[conda] pyg                       2.4.0           py38_torch_2.1.0_cu121    pyg
[conda] pytorch                   2.1.2           py3.8_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-lightning         2.1.3                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.1.2           py38_torch_2.1.0_cu121    pyg
[conda] torch-sparse              0.6.18                   pypi_0    pypi
[conda] torchaudio                2.1.2                py38_cu121    pytorch
[conda] torchcde                  0.2.5                    pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchdyn                  1.0.6                    pypi_0    pypi
[conda] torchmetrics              1.3.0.post0              pypi_0    pypi
[conda] torchsde                  0.2.6                    pypi_0    pypi
[conda] torchtriton               2.1.0                      py38    pytorch
[conda] torchvision               0.16.2               py38_cu121    pytorch

**Comment by rusty1s** [comment]
Yes, scatter ops introduce non-determinism, and this non-determinism is increased exponentially over layers, since differences in earlier layers propagate to later layers.

Two comments:
* You can clearly see that this non-determinism is actually a good thing (since the CUDA loss is lower than the CPU loss).
* I think the way you measure the difference across runs is not totally fair. In the end, you are just measuring the loss of the last epoch, which is expected to be different across runs with non-determinism. You can make this more fair by actually computing, e.g., the average of loss values of the last 50 epochs:
```python
cuda  avg_loss 0.8122314620018005
cpu  avg_loss 1.073906236886978
cuda  avg_loss 0.812663015127182
cpu  avg_loss 1.073906236886978
cuda  avg_loss 0.8182425475120545
cpu  avg_loss 1.073906236886978
cuda  avg_loss 1.1064115726947785
cpu  avg_loss 1.073906236886978
cuda  avg_loss 0.8701974999904633
cpu  avg_loss 1.073906236886978
```
and you can see that the performance is quite stable across runs, even with non-determinism.

**Comment by simonheilig** [comment]
I agree, that the comparison on the last epoch is too sensitive - but when training models the performance is also measured on the last (or early stopped) epoch. Since there are models that can handle layers greater than 10 or even 30, I think this is still a concerning issue, also for the downstream task performance (since the backprop-trajectories are so different over longer periods).

If the vanilla neighborhood aggregation is swapped with a GCNConv, then the loss is smaller and the effect appears, obviously, not in the 1e-1 area. But this is due to the normalization, aka. smaller values to work with everywhere:
```
cuda  loss  0.0005538088153116405
cpu  loss  0.0005537859397009015
cuda  loss  0.000553823250811547
cpu  loss  0.0005537859397009015
cuda  loss  0.0005538267432712018
cpu  loss  0.0005537859397009015
cuda  loss  0.0005538080586120486
cpu  loss  0.0005537859397009015
cuda  loss  0.0005538080586120486
cpu  loss  0.0005537859397009015
```

**Comment by simonheilig** [comment]
I will close this issue, but still want to stress the point that using vanilla neighborhood aggregation, the scatter-ops are introducing significant uncertainty. It would be nice to dig into the technicalities, to see why the normalization of GCN reduces this effect.

**Comment by rusty1s** [comment]
I wouldn‘t call it uncertainty, just a by-product of floating-point precision for permutation-invariant aggregations. Maybe I am still missing the point why determinism is required in a permutation-invariant GNN world :)

Nonetheless, we are making the process of guaranteeing deterministic behavior easier to achieve in an upcoming release. Meanwhile, `SparseTensor` usage already provides deterministic behavior.

**Comment by simonheilig** [comment]
Thanks for hinting to SparseTensor. In my current project, we suffered over long periods of training and layers of no reproducibility in the downstream-performance.

**Comment by siantonelli** [comment]
Hi, I think this issue is the closest to the problem I am facing right now.

Training a simple 2-layer GCN with a seed set for both data and weight initialization does not guarantee similar _**test performance**_ across 10 runs. To avoid opening a new issue, here is a [colab notebook](https://colab.research.google.com/drive/1wHmQ3daAxpuEi0o3Ol2UerV8-yZk2LLw?usp=sharing) that can be used to reproduce the bug.
In the notebook, you can see there is more than 1% std in the final test accuracy, but what is more apparent is the discrepancy between the min and max accuracy, namely `0.801` and `0.849`.

I also show the train losses for the different trials, and you can see that up to some epoch (around 50), the losses remain the same, and then they diverge. 
![train_losses](https://github.com/pyg-team/pytorch_geometric/assets/49906477/45bd4c72-b321-4ea4-8131-c91da1719e4e)
I agree with [Simon](https://github.com/pyg-team/pytorch_geometric/issues/8866#issuecomment-1935636273) and probably it would be nice to dig into the technicalities. For the moment, I have to switch to `SparseTensor` to trust my results.
