### ISSUE TITLE
CI failing for `test_dist_neighbor_sampler_hetero[False]`

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#8941]
### 🐛 Describe the bug

```
test/distributed/test_dist_neighbor_sampler.py::test_dist_neighbor_sampler_hetero[False] Computing METIS partitioning...
double free or corruption (!prev)
```

### Versions

using PyG commit from Simplify RecSys example (#8904) 3a56d4bfd50f16515138be73b748fa586747c3ef

**Comment by DamianSzwichtenberg** [comment]
@kgajdamo @JakubPietrakIntel Could you please take a look at this issue?

**Comment by rusty1s** [comment]
I think this stems from `pyg-lib` METIS computation. The `torch-sparse` implementation doesn't seem to have this issue. Not totally sure why.

**Comment by puririshi98** [comment]
same thing for this test:
```
test/distributed/test_dist_neighbor_sampler.py::test_dist_neighbor_sampler_hetero[True] Computing METIS partitioning...
python: malloc.c:4302: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Session terminated, killing shell... ...killed.
```
i produced this error by skipping the test originally failing at the top of this issue

**Comment by puririshi98** [comment]
test/distributed/test_dist_neighbor_sampler.py::test_dist_neighbor_sampler_temporal_hetero[uniform-None] Computing METIS partitioning...
double free or corruption (!prev)
Session terminated, killing shell...******TIMEOUT EXPIRED******

**Comment by rusty1s** [comment]
Let me try to fix this. For now, we can just disable the tests in case METIS does not work properly.

**Comment by puririshi98** [comment]
```
test/distributed/test_dist_neighbor_sampler.py::test_dist_neighbor_sampler_temporal_hetero[uniform-seed_time1] Computing METIS partitioning...
python: malloc.c:4302: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Session terminated, killing shell... ...killed.
******TIMEOUT EXPIRED******
```

**Comment by puririshi98** [comment]
> Let me try to fix this. For now, we can just disable the tests in case METIS does not work properly.

thanks, yep im skipping them on our end

**Comment by puririshi98** [comment]
for more info, to get passing CI i needed to add -k w/ : `not test_dist_neighbor_loader_hetero[True-0-2] and not test_dist_neighbor_sampler_hetero[True] and not test_dist_neighbor_sampler_temporal_hetero and not test_dist_neighbor_sampler_edge_level_temporal_hetero and not test_from_partition_hetero_data and not test_from_partition_hetero_edge_level_temporal_data`

**Comment by rusty1s** [comment]
Added `@onlyMETIS` decorator in https://github.com/pyg-team/pytorch_geometric/pull/9033.

@puririshi98 Can you please test if the following works for you:
```python
import torch
import pyg_lib
rowptr = torch.tensor([0, 2, 4, 6])
col = torch.tensor([1, 2, 0, 2, 1, 0])
pyg_lib.partition.metis(rowptr, col, num_partitions=2)

**Comment by puririshi98** [comment]
```
root@viking-prod-283:/opt/pyg/pytorch_geometric# python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

>>> import pyg_lib
>>> rowptr = torch.tensor([0, 2, 4, 6])
>>> col = torch.tensor([1, 2, 0, 2, 1, 0])
>>> pyg_lib.partition.metis(rowptr, col, num_partitions=2)
tensor([0, 1, 1])

```

this is the output using 24.03 pyg dlfw container + latest pyg source build

**Comment by puririshi98** [comment]
no longer an issue
