### ISSUE TITLE
Graph Transformer implementation

### ISSUE THREAD

**Issue by ck-amrahd** [pyg-team/pytorch_geometric#8957]
### 🚀 The feature, motivation and pitch

DGL has graph transformer implementation here: https://docs.dgl.ai/en/1.1.x/notebooks/sparse/graph_transformer.html
Is it possible to include this architecture in pytorch geometric?

### Alternatives

We may already have the implementation of this but I can not find it.

**Comment by rusty1s** [comment]
We have a Graph Transformer implementation via `GPSConv` and a corresponding example, see https://github.com/pyg-team/pytorch_geometric/blob/master/examples/graph_gps.py. Does that fit your needs?
