### ISSUE TITLE
Torch Compilation does not work with torch scatter and torch cluster

### ISSUE THREAD

**Issue by liyy2** [pyg-team/pytorch_geometric#8963]
### 🐛 Describe the bug

```
torch_geometric.nn.radius_graph
```
does not support torch compile

### Versions

[pip3] numpy==1.26.4
[pip3] pytorch-lightning==2.1.3
[pip3] torch==2.1.0
[pip3] torch-cluster==1.6.3+pt21cu121
[pip3] torch-ema==0.3
[pip3] torch_geometric==2.5.0
[pip3] torch-runstats==0.2.0
[pip3] torch-scatter==2.1.2+pt21cu121
[pip3] torch-sparse==0.6.18+pt21cu121
[pip3] torch-spline-conv==1.2.2+pt21cu121
[pip3] torchaudio==2.1.0
[pip3] torchmetrics==1.2.1
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] libopenvino-pytorch-frontend 2023.3.0             h59595ed_0    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.26.4          py311h64a7726_0    conda-forge
[conda] pytorch                   2.1.0           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-lightning         2.1.3              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-cluster             1.6.3+pt21cu121          pypi_0    pypi
[conda] torch-ema                 0.3                      pypi_0    pypi
[conda] torch-geometric           2.5.0                    pypi_0    pypi
[conda] torch-runstats            0.2.0                    pypi_0    pypi
[conda] torch-scatter             2.1.2+pt21cu121          pypi_0    pypi
[conda] torch-sparse              0.6.18+pt21cu121          pypi_0    pypi
[conda] torch-spline-conv         1.2.2+pt21cu121          pypi_0    pypi
[conda] torchaudio                2.1.0               py311_cu121    pytorch
[conda] torchmetrics              1.2.1              pyhd8ed1ab_0    conda-forge
[conda] torchtriton               2.1.0                     py311    pytorch
[conda] torchvision               0.16.0              py311_cu121    pytorch

**Comment by rusty1s** [comment]
This is tracked in https://github.com/pyg-team/pytorch_geometric/issues/8890. For now, you have to manually disable compilation of custom ops.
