### ISSUE TITLE
NotImplementedError in demo notebook

### ISSUE THREAD

**Issue by devinbost** [pyg-team/pytorch_geometric#8989]
### 🐛 Describe the bug

When I try to step through the demo here: https://colab.research.google.com/drive/1xpzn1Nvai1ygd_P5Yambc_oe4VBPK_ZT?usp=sharing#scrollTo=I_63--974srt

I hit this `NotImplementedError`:
<img width="694" alt="image" src="https://github.com/pyg-team/pytorch_geometric/assets/7418031/3b512b83-6237-4faf-961e-2390c7f09650">

It looks like the demo notebook is incomplete. Is there a workaround? 

### Versions

https://colab.research.google.com/drive/1xpzn1Nvai1ygd_P5Yambc_oe4VBPK_ZT?usp=sharing#scrollTo=I_63--974srt

**Comment by akihironitta** [comment]
AFAIK, the notebook is intentionally made incomplete so that new PyG users can use it as an excercise to familiarise themselves with PyG.

**Comment by rusty1s** [comment]
Closing this. Happy to answer any questions though if you are stuck with filling the notebook out.
