### ISSUE TITLE
Add edge_attr reduction argument to torch_geometric.nn.pool.pool.pool_edge

### ISSUE THREAD

**Issue by MatthieuMelennec** [pyg-team/pytorch_geometric#9107]
### 🚀 The feature, motivation and pitch

I am working on my own graph pooling scheme based on cluster vectors assigning nodes to the cluster they get pooled into. To pool my edges and edge_attributes, I am using `pool_edge` from `torch_geometric/nn/pool/pool.py`. However, I would want to be able to choose the reduce operation that will be used in `coalesce`. As of now, it is hardcoded to the default value `'sum'`.

### Alternatives

The only solution I see is to rewrite the `pool_edge` function identically and adding an argument `reduce` that will be passed to `coalesce`.

**Comment by rusty1s** [comment]
That's a good request. Do you mind sending a PR for that?
