### ISSUE TITLE
Dataset penn94 dimension of node features seems to large, 4814 instead of 5

### ISSUE THREAD

**Issue by chrisn-pik** [pyg-team/pytorch_geometric#9108]
### 🐛 Describe the bug

```python
from torch_geometric.datasets import  LINKXDataset
import torch
linkxdataset =  LINKXDataset(name = "penn94", root = ".")
linkxdataset[0].x.shape
```
returns: 
```
torch.Size([41554, 4814])
```

According to table 2 from the paper on [Arxiv](http://arxiv.org/abs/2110.14446), there should be 5 features.

Am I missing something? What should I do differently?

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0
CMake version: version 3.27.1
Libc version: N/A

Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torch-cluster==1.6.1
[pip3] torch-geometric==2.3.0
[pip3] torch-scatter==2.1.1
[pip3] torch-sparse==0.6.17
[pip3] torchaudio==2.0.1
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.15.1
[pip3] torchviz==0.0.2
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torch-cluster             1.6.1                    pypi_0    pypi
[conda] torch-geometric           2.3.0                    pypi_0    pypi
[conda] torch-scatter             2.1.1                    pypi_0    pypi
[conda] torch-sparse              0.6.17                   pypi_0    pypi
[conda] torchaudio                2.0.1                    pypi_0    pypi
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

**Comment by rusty1s** [comment]
Note that there exists 5 categorical features in this dataset, which we convert into a one-hot representation each. This explains the increase amount of features we have.

**Comment by chrisn-pik** [comment]
Thank you very much for the fast reply. It makes total sense that one-hot encoding increases the amount of features we have, even though, I am still confused where the exact numbers come from. For example, the sum per row of features is equal to 6 and not 5 what I would have assumed. Nevertheless, the issue can be closed in my point of view.
