### ISSUE TITLE
Batching Graphs only increments edge_index not node_index

### ISSUE THREAD

**Issue by Angelo92Git** [pyg-team/pytorch_geometric#9128]
### 📚 Describe the documentation issue

In this tutorial linked below, it is stated that any attributes containing the substring "index" is incremented by the number of of nodes of the graph, however, this appears only to be true for ```edge_index```. After batching, it seems that ```node_index``` is not incremented.
https://pytorch-geometric.readthedocs.io/en/latest/advanced/batching.html

### Suggest a potential alternative/fix

Update documentation to state that only ```edge_index``` is incremented, without affecting other index attributes. The ```batch``` tensor allows for differentiation between graphs within a batch instead.

**Comment by rusty1s** [comment]
This works fine for me:
```python
import torch

from torch_geometric.data import Batch, Data

data = Data(node_index=torch.arange(3))

batch = Batch.from_data_list([data, data])
print(batch.node_index)
```
```
tensor([0, 1, 2, 3, 4, 5])
```
