### ISSUE TITLE
How to classify graphs of variable lengths ?

### ISSUE THREAD

**Issue by Benjiou** [pyg-team/pytorch_geometric#913]
## ❓ Questions & Help
Hello,

Is there any way to classify graphs with variable lengths ?
Or the only solution is to apply  zero-nodes padding ?

Thank you,

**Comment by rusty1s** [comment]
We do not apply zero-nodes padding in graph classification, but instead stack adjacency matrices diagonally. Have a look at the MUTAG GIN script for an example.

**Comment by Benjiou** [comment]
@rusty1s  thank you for your answer. Would you mind giving me the link to MUTAG GIN script ?

Thank you

**Comment by rusty1s** [comment]
See [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/mutag_gin.py).
