### ISSUE TITLE
enforce single quotes in `ruff` and `pre-commit`

### ISSUE THREAD

**Issue by SauravMaheshkar** [pyg-team/pytorch_geometric#9153]
### 🚀 The feature, motivation and pitch

From `ruff` docs:

> "[In compliance with PEP 8 and PEP 257, Ruff prefers double quotes for triple quoted strings and docstrings even when using quote-style = "single".](https://docs.astral.sh/ruff/settings/#format_quote-style)". 

Thus even with pre-commit passing there are changes which convert `'` to `"`. Should probably look into setting the `quote-style` property to `"single"`, if single quotes are desired. That way it can be enforced via pre-commit as well.

Happy to take this up 😃 

### Additional context

Initially raised in https://github.com/pyg-team/pytorch_geometric/pull/9090#issue-2201278622

**Comment by rusty1s** [comment]
I prefer `'` for single names, and `"` for text. Thanks for your PR, I'll take a look.

**Comment by SauravMaheshkar** [comment]
`"preserve"` might also be an option worth considering.

**Comment by SauravMaheshkar** [comment]
Fixed in https://github.com/pyg-team/pytorch_geometric/pull/9163
