### ISSUE TITLE
torch_geometric InMemoryDataset doesn't load data

### ISSUE THREAD

**Issue by zarkoivkovicc** [pyg-team/pytorch_geometric#9165]
### 🐛 Describe the bug

Here I have the dataset definition:
```
class MolecularShiftsDataset(InMemoryDataset):
    def __init__(
        self,
        dataset: pd.DataFrame,
        encoding: str,
        sdf: SDMolSupplier,
        name: str = "NMR_FF",
        root="data/graph_datasets/",
        edge_attr: bool = True,
        transform=None,
        pre_transform=None,
    ):
        self.encoding = encoding
        self.name = name
        self.dataset = dataset
        self.sdf = sdf
        self.edge_attr = edge_attr
        super().__init__(root, transform, pre_transform)

    @property
    def processed_file_names(self):
        return [f"{self.name}_{self.encoding}.pt"]

    def process(self):
        encoder = encoders.MoltoGraphEncoder()
        # Read data into huge `Data` list.
        data_list = encoder.encode(self.sdf, self.dataset)

        if self.pre_filter is not None:
            data_list = [data for data in data_list if self.pre_filter(data)]

        if self.pre_transform is not None:
            data_list = [self.pre_transform(data) for data in data_list]

        self.save(data_list, self.processed_paths[0])
```
When I initialize this dataset and the files are preprocessed, there is no error, but the dataset is empty. It has length of 1 and the method `GetSummary()` fails because there are no nodes in the graph. However, when I make a new InMemoryDataset as:
```
dataset = InMemoryDataset()
dataset.load(<path_to_processed_file>)
```

Everything works fine.
Any idea why this is happening?

### Versions

[pip3] pytorch-lightning==2.1.3
[pip3] torch==2.2.1
[pip3] torch-ema==0.3
[pip3] torch_geometric==2.5.2
[conda] pyg                       2.5.2           py312_torch_2.2.0_cu118    pyg
[conda] pytorch                   2.2.1           py3.12_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-lightning         2.1.3              pyhd8ed1ab_0    conda-forge

**Comment by rusty1s** [comment]
By default, `__init__` does not load in any pre-processed data. You have to call `self.load()` internally.

**Comment by zarkoivkovicc** [comment]
Thanks. Maybe it should be added in the docs for clarity.
