### ISSUE TITLE
Docker image for CUDA 10.1, and also such that it allows inference on CPU

### ISSUE THREAD

**Issue by Laksh1997** [pyg-team/pytorch_geometric#917]
## 🚀 Feature

I have been banging my head for the past 12 hours trying to get a Dockerfile with CUDA 10.1 to build the CUDA bindings for torch-scatter etc successfully, yet I have not succeeded. I always get the error that there are no NVIDIA drivers on my system. But if I manually enter a Docker container with nvidia-docker, everything works fine...

**Comment by rusty1s** [comment]
I am not a docker user, so I am not give you much advice here. We provide a Dockerfile for CUDA 9 which might be a good starting point. In addition, the [torch-scatter README](https://github.com/rusty1s/pytorch_scatter) contains an advice about building inside Docker.

**Comment by mlaprise** [comment]
Same here, I installed previous versions of PyG successfully in Docker image in the past, but I had the same issue with the latest version. Like mentioned in the README, adding this env. var in my Dockerfile (before the pip install) fixed the issue:

ENV TORCH_CUDA_ARCH_LIST  "6.0 6.1 7.2+PTX 7.5+PTX"

thx for tip @rusty1s

**Comment by rusty1s** [comment]
We are tracking progress on this issue on #5543
