### ISSUE TITLE
Returning map_index while relabelling the nodes

### ISSUE THREAD

**Issue by Roy-Shubhajit** [pyg-team/pytorch_geometric#9174]
### 🚀 The feature, motivation and pitch

While creating a subgraph, we generally pass on the list of nodes and the original edge index based on which the subgraph is created. However, when the relabel node attribute is set to true, the nodes are mapped to new nodes. However, the node features are not taken into consideration. For better transparency, I would like to request that the map_idex be returned, which will help to get the node features down the line when required using the mapping.

**Comment by rusty1s** [comment]
We generally don't return them because they are already part of the input, e.g.:
```python
edge_index, _ = subgraph(n_id, edge_index, relabel_nodes=True)
x = x[n_id]
```
This is also already performed automatically if you do `data.subgraph(n_id)`.

**Comment by Roy-Shubhajit** [comment]
Thanks for the info. However, I wanted to know which node is being relabeled to which node. For example, if I gave `n_id = [45, 78, 129, 467]` as a set of nodes,  then the resultant subgraph will have nodes `[0,1,2,3]`. As `data.subgraph(n_id)` or `subgraph(n_id, edge_index, relabel_nodes=True)` doesn't return any mapping, I'm assuming that it is mapped in the following way
```
mapping = {int(v): i for i, v in enumerate(n_id)}
```
where `i` is the new node and `v` is the node name in the original graph. Please let me know whether this mapping is correct or not.

**Comment by rusty1s** [comment]
Yes, this is correct.
