### ISSUE TITLE
ToSparseTensor() leads to GPU memory leakage when dealing with data generated from RandomLinkSplit()

### ISSUE THREAD

**Issue by shishixuezi** [pyg-team/pytorch_geometric#9196]
### 🐛 Describe the bug

`ToSparseTensor()` leads to GPU memory leakage when dealing with data generated from `RandomLinkSplit()`

```   
    data = ...  

    train_data, val_data, test_data = T.RandomLinkSplit(...)(data)

    data = T.ToSparseTensor()(data) # works fine
    train_data = T.ToSparseTensor()(train_data) # crash
```

I guess `ToSparseTensor()` treats `edge_label_index` as an `edge_attr` so that when executing

```
    if isinstance(edge_attr, (list, tuple)):
        return edge_index, [e[perm] for e in edge_attr]
```
The memory leakage happens since `edge_label_index` is a tensor in `[2, num]`.

Could you please help me with that? Thank you!

### Versions

numpy: 1.21.4
torch: 2.2.2+cu118
torch-geometric: 2.6.0
torch_scatter: 2.1.2+pt22cu118
torch_sparse: 0.6.18+pt22cu118
torchaudio: 2.2.2+cu118
torchvision: 0.17.2+cu118

**Comment by rusty1s** [comment]
Thanks. Will be fixed in https://github.com/pyg-team/pytorch_geometric/pull/9199.
