### ISSUE TITLE
pyproject.toml doesn't list as dependencies modules imported at runtime: dgl, torch_sparse

### ISSUE THREAD

**Issue by yurivict** [pyg-team/pytorch_geometric#9222]
### 🐛 Describe the bug

dgl, torch_sparse are imported, but not mentioned in pyproject.toml

### Versions

HEAD

**Comment by rusty1s** [comment]
`dgl` is never imported, only if you explicitly call `to_dgl`. `torch_sparse` is imported in case if it is found, it's an optional dependency. Since none of these dependencies are required to run PyG, I don't see a good reason to list them in `pyproject.toml`.

**Comment by yurivict** [comment]
Ok, thanks.
