### ISSUE TITLE
HeteroDataBatch dict assignment fails

### ISSUE THREAD

**Issue by Kidara** [pyg-team/pytorch_geometric#9247]
### 🐛 Describe the bug

You cannot override the value of a HeteroDataBatch dict, such as 'x_dict', with an assignment. The assignment instruction does not work.

```python
import torch
from torch_geometric.data import Data, HeteroData
from torch_geometric.loader import DataLoader

# Create homogeneous dataset on the fly
dataset = []
for _ in range(100):
    data = Data()
    
    data.x = torch.randn(1, 1)
    data.edge_index = torch.as_tensor([[0],
                                       [0]])
    
    dataset.append(data)

loader = DataLoader(dataset, batch_size=2)

# Create heterogeneous dataset on the fly
hetero_dataset = []
for _ in range(100):
    data = HeteroData()
    
    data['paper'].x = torch.randn(1, 1)
    data['author'].x = torch.randn(4, 6)
    data['author', 'writes', 'paper'].edge_index = torch.as_tensor([[0, 0],
                                                                    [0, 1]])
    
    hetero_dataset.append(data)

hetero_loader = DataLoader(hetero_dataset, batch_size=2)

print('This works')
for db in loader:
    print(db.x)
    db.x = db.x + 1
    print(db.x)
    break

print()

print('This fails')
for hdb in hetero_loader:
    print(hdb.x_dict['paper'])
    hdb.x_dict['paper'] = hdb.x_dict['paper'] + 1
    print(hdb.x_dict['paper'])
    break

print()

print('This works')
for hdb in hetero_loader:
    print(hdb.x_dict['paper'])
    hdb.x_dict['paper'] += 1
    print(hdb.x_dict['paper'])
    break

print()

print('This works')
for hdb in hetero_loader:
    paper_x = hdb.x_dict['paper']
    print(paper_x)
    paper_x = paper_x + 1
    print(paper_x)
    break
```

Example output:
```
This works
tensor([[-0.8772],
        [-0.1099]])
tensor([[0.1228],
        [0.8901]])

This fails
tensor([[0.9899],
        [0.3381]])
tensor([[0.9899],
        [0.3381]])

This works
tensor([[0.9899],
        [0.3381]])
tensor([[1.9899],
        [1.3381]])

This works
tensor([[0.9899],
        [0.3381]])
tensor([[1.9899],
        [1.3381]])
```

### Versions

PyTorch version: 2.2.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 551.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2300
DeviceID=CPU0
Family=198
L2CacheSize=11776
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2300
Name=12th Gen Intel(R) Core(TM) i7-12700H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] pytorch-lightning==2.2.3
[pip3] torch==2.2.2+cu121
[pip3] torch_cluster==1.6.3+pt22cu121
[pip3] torch_geometric==2.5.2
[pip3] torch_scatter==2.1.2+pt22cu121
[pip3] torch_sparse==0.6.18+pt22cu121
[pip3] torch_spline_conv==1.2.2+pt22cu121
[pip3] torchaudio==2.2.2+cu121
[pip3] torchmetrics==1.3.2
[pip3] torchvision==0.17.2+cu121
[conda] Could not collect

**Comment by EdisonLeeeee** [comment]
Hi @Kidara 

This is an intended behavior because:

+ `Data` functions similarly to a dictionary, so assigning to its attribute `Data.x` would override it.
+ `HeteroData.x_dict` returns a new dictionary each time, so assigning to it wouldn't work as expected.

**Comment by Kidara** [comment]
> Hi @Kidara
> 
> This is an intended behavior because:
> 
> * `Data` functions similarly to a dictionary, so assigning to its attribute `Data.x` would override it.
> * `HeteroData.x_dict` returns a new dictionary each time, so assigning to it wouldn't work as expected.

I see. But I don't get why the third example works then.

**Comment by EdisonLeeeee** [comment]
That's because `+=` is an in-place operation performed on the tensor `hdb.x_dict['paper']` directly.

This example would provide a better explanation:

```python
import torch

class HeteroData:
    paper = torch.ones(3)

    @property
    def x_dict(self):
        return {'paper': self.paper}

print('This fails')
hdb = HeteroData()
print(hdb.x_dict['paper'])
hdb.x_dict['paper'] = hdb.x_dict['paper'] + 1
print(hdb.x_dict['paper'])

print()

print('This works')
print(hdb.x_dict['paper'])
hdb.x_dict['paper'] += 1
print(hdb.x_dict['paper'])

```
Example output:


```
This fails
tensor([1., 1., 1.])
tensor([1., 1., 1.])

This works
tensor([1., 1., 1.])
tensor([2., 2., 2.])

```

**Comment by Kidara** [comment]
Thanks
