### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file error while downloading papers-100M data

### ISSUE THREAD

**Issue by meenamohit** [pyg-team/pytorch_geometric#9258]
### 😵 Describe the installation problem

<img width="573" alt="error" src="https://github.com/pyg-team/pytorch_geometric/assets/160098429/a228f1b1-72e2-4c40-835e-db6d5c31c7a5">

I'm trying to download the papers-100M data using the following code lines

from ogb.nodeproppred import PygNodePropPredDataset
ogb_dataset = PygNodePropPredDataset('ogbn-papers100M')
ogb_data=ogb_dataset[0]

I looked at the similar issue and there problem is related to storage space but that is not the case for me as I have around 100 GB free space available. I've also tried downloading the data using wget and then gave the path of it but that throws some decompression error. I'm stuck, can anyone please help regarding this? Thanks in anticipation!

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
This seems to be an issue with OGB. Do you mind creating an issue there?
