### ISSUE TITLE
Correction of error in the Tutorial's Point Cloud Classification Colab Notebook

### ISSUE THREAD

**Issue by hdsfade** [pyg-team/pytorch_geometric#9340]
### 📚 Describe the documentation issue

Colab Notebook link: https://colab.research.google.com/drive/1D45E5bUK3gQ40YpZo65ozs7hg5l-eo_U?usp=sharing

The problem is shown in the figure: 
<img width="820" alt="image" src="https://github.com/pyg-team/pytorch_geometric/assets/59165160/f4f2b73f-6cb7-43d9-8675-afdaf6264854">

Fix: data.face.t() should be face.t()

Thank you very much for your attention to this issue and for considering the necessary correction. 

### Suggest a potential alternative/fix

Fix: data.face.t() should be face.t()

**Comment by rusty1s** [comment]
Thanks for spotting. Fixed it.
