### ISSUE TITLE
I have installed all PyG dependencies , but import error!

### ISSUE THREAD

**Issue by Zening-Li** [pyg-team/pytorch_geometric#935]
## Environment

* OS: ubuntu 16.04
* Python version: 3.7.3
* PyTorch version: 1.4.0
* CUDA/cuDNN version: cuda 9.2, cudnn 7.6.4
* GCC version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
* How did you try to install PyTorch Geometric and its extensions (pip, source):  conda
* Any other relevant information:
I have installed torch-scarrter, torch-sparse, torch-cluster, torch-spline-conv and torch-geometric.

## Additional context

pyg dependencies:(conda install torch-cluster...)
torch-cluster             1.4.5            py37hf484d3e_0     ostrokach-forge
torch-geometric        1.3.2                    py37_0            ostrokach-forge
torch-scatter             1.4.0            py37hf484d3e_0     ostrokach-forge
torch-sparse              0.4.3            py37hf484d3e_0    ostrokach-forge
torch-spline-conv      1.1.1            py37hf484d3e_0    ostrokach-forge
```bash
from torch_geometric.data import Data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/lzn/anaconda3/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /home/lzn/anaconda3/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
```

**Comment by rusty1s** [comment]
This basically indicates that you have multiple PyTorch versions or that the extension packages are built with another version that you currently use. If you have upgraded PyTorch to 1.4, you also need to upgrade *all* extension packages.

**Comment by mia-minyoung** [comment]
Hi, I have been facing the same problem rn. I'm using

> python 3.5
> CUDA 10.1
> torch                 1.4.0
> torch-cluster         1.4.5
> torch-geometric       1.4.1
> torch-scatter         1.4.0
> torch-sparse          0.4.4

and others are the same as Zening-Li.
I upgrade all packages except torch-scatter(newest 2.0.2) since there was a syntax error. 

My error is a bit different but generally similar. Thank you for any help.

> ImportError: /opt/conda/envs/py35/lib/python3.5/site-packages/torch_cluster/graclus_cpu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by rusty1s** [comment]
What is the syntax error in `torch-scatter=2.0.2`? You can use `torch-scatter=1.4.0`, but you still need to reinstall it when upgrading PyTorch.

**Comment by mia-minyoung** [comment]
This one. I also tried to install 2.0.2v by source (running setup.py) but encountered the same error.

> (py35) root@9ccd12852d78:/data_my/pytorch_coma# pip install --upgrade torch-scatter
> Collecting torch-scatter
>   Using cached torch_scatter-2.0.2.tar.gz (22 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /opt/conda/envs/py35/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gkeourgj/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gkeourgj/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-gkeourgj/torch-scatter/pip-egg-info
>          cwd: /tmp/pip-install-gkeourgj/torch-scatter/
>     Complete output (6 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-gkeourgj/torch-scatter/setup.py", line 47
>         sources = [main, osp.join(extensions_dir, 'cpu', f'{name}_cpu.cpp')]
>                                                                          ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

That's interesting. I already reinstall `torch_scatter=1.4.0` tho... I'll try deleting it and reinstall one more time.

**Comment by rusty1s** [comment]
That's a weird error. It would be very helpful if you could dig a bit deeper why this line causes an syntax error for you. I do not have such an error on my side.

**Comment by mia-minyoung** [comment]
Hi, 
It turns out the cause of that error is the python version. I'm using python 3.5.5 but the f string which is giving syntax error is recently added in python 3.6. If it's really due to the version, I think it should be edited because this error occurs at `import torch_geometric.nn ` from message_passing.py as well. 

>   File "/opt/conda/envs/py35/lib/python3.5/site-packages/torch_geometric/nn/conv/__init__.py", line 1, in <module>
>     from .message_passing import MessagePassing
> 
>   File "/opt/conda/envs/py35/lib/python3.5/site-packages/torch_geometric/nn/conv/message_passing.py", line 88
>     (f'Encountered node tensor with size '
>                                          ^
> SyntaxError: invalid syntax

**Comment by rusty1s** [comment]
Oh, you are right. Will fix it! Thank you!

**Comment by mia-minyoung** [comment]
Welcome! Hope to solve this error soon and always appreciate your great work!
