### ISSUE TITLE
from_smiles should allow setting y (label)

### ISSUE THREAD

**Issue by j-adamczyk** [pyg-team/pytorch_geometric#9354]
### 🚀 The feature, motivation and pitch

Currently `from_smiles` (https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.from_smiles) does not allow setting `y` (label). It should take such an argument, and pass it to `Data` it creates.

**Comment by rusty1s** [comment]
The current design idea is to add labels afterwards. Does that work in your case?

**Comment by j-adamczyk** [comment]
I was getting a warning about `y` not being settable from PyCharm, but it went away after updating PyG. Probably due to `@property` for `y` being present, but not `@y.setter`. Anyway, it works, so I'm closing the issue
