### ISSUE TITLE
Add docs for environment setup on XPU device

### ISSUE THREAD

**Issue by zhouyu5** [pyg-team/pytorch_geometric#9384]
### 📚 Describe the documentation issue

Currently the environment setting for XPU device is very concise, I only found two of them:

- One in benchmark folder, see [here](https://github.com/pyg-team/pytorch_geometric/tree/master/benchmark/multi_gpu/training#environment-setup), see screenshot below.
![image](https://github.com/pyg-team/pytorch_geometric/assets/12825276/52434ca6-29ed-4211-bf7d-9c4b23ebe532)

- One in example folder, in the comment of the code, see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/distributed_sampling_xpu.py#L5), see screenshot below.
![image](https://github.com/pyg-team/pytorch_geometric/assets/12825276/ce132d55-c90d-4d4f-9c19-5350c49c496f)

However, it assume the users has good knowledge of setting up the environment in Intel GPU, which is not the case for some beginners. Just follow the above simple guide, users are not likely to launch the scripts in Intel GPU. 

### Suggest a potential alternative/fix

Give a more detailed guide for users to setting up the environment on Intel GPU. I would likely to help with the following docs:

- A doc give the detailed guide on setting up the environment on bare mental server or docker runtime, and contains related links 
- A Dockerfile with everything setup in advance, users could utilize this to build the images on top of their server

**Comment by rusty1s** [comment]
I don't have much knowledge on Intel GPU so any help is appreciated :)

**Comment by zhouyu5** [comment]
> I don't have much knowledge on Intel GPU so any help is appreciated :)

@rusty1s  I add some docs in PR #9407 , hope it can help.

**Comment by rusty1s** [comment]
Nice, thank you.
