### ISSUE TITLE
unable to install with conda

### ISSUE THREAD

**Issue by davidireland3** [pyg-team/pytorch_geometric#9388]
### 😵 Describe the installation problem

```
(base) conda install pyg -c pyg
Channels:
 - pyg
 - defaults
 - pytorch
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyg

Current channels:

  - https://conda.anaconda.org/pyg
  - defaults
  - https://conda.anaconda.org/pytorch/osx-arm64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

using the conda install command given on the installation page, I get the above error. I was able to install with pip. 

### Environment

* PyG version: latest
* PyTorch version: 2.3
* OS: Mac
* Python version: 3.10
* CUDA/cuDNN version: n/a
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`): n/a

**Comment by rusty1s** [comment]
Currently, we don't have conda builds for ARM-based mac. I suggest to install via pip for now.
