### ISSUE TITLE
Support GraphSAGE concatenation step

### ISSUE THREAD

**Issue by kkonevets** [pyg-team/pytorch_geometric#945]
## ❓ Questions & Help

Looking at the code I could not find an evidence that SAGEConv layer concatenates aggregated neighbor features with current node features, namely step 5 in the original paper, it only averages them by adding self loops. How easy is to add concatenation?

Concatenation is crucial as it preserves target node signal and does not vanish it by averaging. For example, social network needs to account current person information along with his/her neighbors. It is useful for person classification.

![Screenshot from 2020-02-06 13-05-52](https://user-images.githubusercontent.com/16817116/73927782-137da980-48e3-11ea-81f2-d187773e7268.png)

**Comment by rusty1s** [comment]
We currently only have an implementation of the `mean` aggregator of GraphSAGE, which replaces lines 4 and 5 of the pseudocode with Eq. (2).

**Comment by kkonevets** [comment]
Can I try to make a pull request to implement the feature?

**Comment by rusty1s** [comment]
Sure, contributions are very welcome! Feel free to ask any questions :)

**Comment by yinanzhangepfl** [comment]
Hi,

I have just started working on PyG and I am confused about the concatenation step of SAGEConv.

1) If we set concat=False, then only aggr_out is used for updating node features. Let's say we have node i, and its neighbors are node k and node j. In this case,  aggr_out =mean{f_k, f_j} or aggr_out = mean {f_i, f_k, f_j}? Which one is correct? 

2) If we set concat=True, then is aggr_out = mean(f_k, f_j)?

I am not sure if we need add self-loops to graphs in the first case and  
remove self-loops in the second case. 
Actually, I have checked your example Reddit.py, where you used a NeighborSampler and add self loops without concatenation. 

Many thanks:)

**Comment by kkonevets** [comment]
It is confusing, I agree.
If we want to use concatenation then self loops addition must be done before `SageConv` initialization, e.g. in `NeighborSampler` that will produce `res_n_id` for us. Otherwise it is optional. If someone will try to use concatenation without self loops `res_n_id` will be `None`.
If we have self loops then `aggr_out = mean {f_i, f_k, f_j}` otherwise `mean(f_k, f_j)`. So concatenation is independent of aggregation.

**Comment by yinanzhangepfl** [comment]
2. It is always mean(f_i, f_k, f_j). Seems like it is not the same as neighborhood function in original paper, because it should be mean(f_k, f_j). It is done this way only to get res_n_id. And as I said, adding self loops improves results.

Just to clarify this:
If we set concat=True, must self-loops be added? If yes, then aggr_out = mean(f_i, f_k, f_j) and f_i and aggr_out are concatenated to generate a new feature vector for node i? And this is different from the original paper, where we concatenate f_i and mean(f_k, f_j).
We add self-loops here only to get res_n_id (if using NeighborSampler) and to improve results.

Thank you very much for your detailed reply. Hope you could tell me if my understanding is correct when available:)

**Comment by kkonevets** [comment]
"If we set concat=True, must self-loops be added? " - Yes
"If yes, then aggr_out = mean(f_i, f_k, f_j) and f_i and aggr_out are concatenated to generate a new feature vector for node i? " - Yes
"And this is different from the original paper, where we concatenate f_i and mean(f_k, f_j)" - yes, but not almost, original paper has different aggregators, e.g. `max pooling`. Here we use `mean` aggregator
"We add self-loops here only to get res_n_id (if using NeighborSampler) and to improve results" - True

Glad could help

**Comment by yinanzhangepfl** [comment]
Yes, your answer is very helpful, thanks~
