### ISSUE TITLE
Wrong link in `GDC` page

### ISSUE THREAD

**Issue by songsong0425** [pyg-team/pytorch_geometric#9609]
### 📚 Describe the documentation issue

Hi, there is a wrong link to the Diffusion Improves Graph Learning paper on `GDC` page.
https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.transforms.GDC.html

### Suggest a potential alternative/fix

Can anyone update the link to [this one](https://arxiv.org/abs/1911.05485)?
Thank you for reading this issue.

**Comment by DonBoscoBlaiseA** [comment]
I would like to fix this.

**Comment by DonBoscoBlaiseA** [comment]
Fixed this and made a PR!
