### ISSUE TITLE
Check the duplicated edges in the graph

### ISSUE THREAD

**Issue by guanshaoheng** [pyg-team/pytorch_geometric#9654]
### 🚀 The feature, motivation and pitch

Before removing duplicate edges, we can use this function to extract and inspect all the duplicates. This is particularly useful for designing the graph network and for debugging, as edges can easily become duplicated when selected by nodes. In calculations, these duplicate edges can impact the network’s predictions…

**Comment by guanshaoheng** [comment]
maybe making some modifications to the function `torch_geometric.utils.coalesce` can work

**Comment by rachitk** [comment]
There is a transform `RemoveDuplicatedEdges` that should in theory do this - is there additional functionality that you'd need?

 https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.transforms.RemoveDuplicatedEdges.html
