### ISSUE TITLE
Functionality to convert a [N, M] adjacency matrix to a [2, num_messages] edge_index

### ISSUE THREAD

**Issue by kleingeo** [pyg-team/pytorch_geometric#9655]
### 🚀 The feature, motivation and pitch

Simple functionality, or even documentation, to convert a (dense) [N, M] adjacency matrix to a (dense) `edge_index`.

**Comment by rachitk** [comment]
Does the `dense_to_sparse` function meet the criteria of what you need?

https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/sparse.html#dense_to_sparse
