### ISSUE TITLE
Typo in NeighborLoader

### ISSUE THREAD

**Issue by marcosousapoza** [pyg-team/pytorch_geometric#9755]
### 📚 Describe the documentation issue

There is a small typo in the docs (https://github.com/pyg-team/pytorch_geometric/blob/f5c829344517c823c24abb08ce2fc7cf00ff29f7/torch_geometric/loader/neighbor_loader.py#L17)

### Suggest a potential alternative/fix

It should say: `    More specifically, :obj:`num_neighbors` denotes how many neighbors are`

**Comment by goelzva** [comment]
would like to take this over

**Comment by goelzva** [comment]
this issue can be closed, the PR was merged
