### ISSUE TITLE
ImportError: cannot import name '_validate_lengths

### ISSUE THREAD

**Issue by xuexiaoxiaohu** [pyg-team/pytorch_geometric#978]
## Environment

* OS:Ubuntu6.04
* Python version:3.6.4
* PyTorch version:1.4.0
* CUDA/cuDNN version:9.2
* GCC version:5.4.0
* How did you try to install PyTorch Geometric and its extensions (pip, source):pip
* Any other relevant information:
first i install torch-scatter using pip install torch-sparse==latest+cu92 -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
then display：
Looking in links: https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa69d5c6208>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa69d5c62b0>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa69d5c6390>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa69d5c64a8>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa69d5c6588>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
ERROR: Could not find a version that satisfies the requirement torch-sparse==latest+cu92 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.1)
ERROR: No matching distribution found for torch-sparse==latest+cu92
and i try 

## Checklist

- [yes ] I followed the installation guide.
- [ yes] I cannot find my error message in the FAQ.
- [ yes] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ no] I have cloned the repository and tried a manual installation from source.
- [no ] I do have multiple CUDA versions on my machine.
- [ yes] I checked if the official extension example runs on my machine.
- [no ] The offical extension example runs on my machine.

## Additional context

(lir) shapelight@shapelight-PC:~$  pip install torch-scatter==latest+cu92 torch-sparse==latest+cu92 -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html

Looking in links: https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f799ed6a0>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f799ed748>, 'Connection to s3.eu-central-1.amazonaws.com timed out. (connect timeout=15)')': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f799ed828>: Failed to establish a new connection: [Errno 111] 拒绝连接',)': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f799ed940>: Failed to establish a new connection: [Errno 111] 拒绝连接',)': /pytorch-geometric.com/whl/torch-1.4.0.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f799eda20>: Failed to establish a new connection: [Errno 111] 拒绝连接',)': /pytorch-geometric.com/whl/torch-1.4.0.html
ERROR: Could not find a version that satisfies the requirement torch-scatter==latest+cu92 (from versions: 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3)
ERROR: No matching distribution found for torch-scatter==latest+cu92

and i try (lirui) shapelight@shapelight-PC:~$ pip install torch-sparse==0.5.1
Collecting torch-sparse==0.5.1
  Downloading torch_sparse-0.5.1.tar.gz (28 kB)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.6/site-packages (from torch-sparse==0.5.1) (1.0.0)
Building wheels for collected packages: torch-sparse
  Building wheel for torch-sparse (setup.py) ... done
  Created wheel for torch-sparse: filename=torch_sparse-0.5.1-cp36-cp36m-linux_x86_64.whl size=9583219 sha256=7d3c25addf7f63610ae4a0d83ec350f4632a26f5a934dbc84766f8d8798e7418
  Stored in directory: /home/shapelight/.cache/pip/wheels/5d/22/04/1fb2a724f907ddc961040f153f00149df4a3e1edca232c65f5
Successfully built torch-sparse
Installing collected packages: torch-sparse
  Attempting uninstall: torch-sparse
    Found existing installation: torch-sparse 0.4.4
    Uninstalling torch-sparse-0.4.4:
      Successfully uninstalled torch-sparse-0.4.4
Successfully installed torch-sparse-0.5.1

and i try (lirui) shapelight@shapelight-PC:~$ pip install torch-scatter==2.0.3

Collecting torch-scatter==2.0.3
  Downloading torch_scatter-2.0.3.tar.gz (20 kB)
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... done
  Created wheel for torch-scatter: filename=torch_scatter-2.0.3-cp36-cp36m-linux_x86_64.whl size=10728260 sha256=4fafe7052cfff7e7da1b833e8bf9595d81f016335c1452ed2a03ff5d8f0cef6f
  Stored in directory: /home/shapelight/.cache/pip/wheels/b8/a3/6a/b2ded19afea11f3bb62093d3fc84703f2b1aa635a5c9e66751
Successfully built torch-scatter
Installing collected packages: torch-scatter
  Attempting uninstall: torch-scatter
    Found existing installation: torch-scatter 1.4.0
    Uninstalling torch-scatter-1.4.0:
      Successfully uninstalled torch-scatter-1.4.0
Successfully installed torch-scatter-2.0.3
 
but when  i  try that, it not works
(lirui) shapelight@shapelight-PC:~$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch_geometric.data import Data
INFO:rdflib:RDFLib Version: 4.2.2
/home/shapelight/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shapelight/anaconda3/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.transforms
  File "/home/shapelight/anaconda3/lib/python3.6/site-packages/torch_geometric/transforms/__init__.py", line 35, in <module>
    from .to_superpixels import ToSLIC
  File "/home/shapelight/anaconda3/lib/python3.6/site-packages/torch_geometric/transforms/to_superpixels.py", line 2, in <module>
    from skimage.segmentation import slic
  File "/home/shapelight/anaconda3/lib/python3.6/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/home/shapelight/anaconda3/lib/python3.6/site-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/home/shapelight/anaconda3/lib/python3.6/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

I am very  sorry to trouble you ,and look forward to your reply .Thank you

**Comment by rusty1s** [comment]
Seems like a version conflict between `skimage` and `numpy`. Can you try to update both packages?

**Comment by dabao0903** [comment]
> Seems like a version conflict between `skimage` and `numpy`. Can you try to update both packages?

The problem was solved after pip numpy and scikit-image
