### ISSUE TITLE
Lacking backend for data loaded by PyG

### ISSUE THREAD

**Issue by junjy007** [pyg-team/pytorch_geometric#991]
## ❓ Questions & Help

I have installed PyG on MacOS as follows
```
pip install torch-scatter==latest+cpu torch-sparse==latest+cpu -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
pip install torch-geometric
```
on top of an Anaconda environment and pytorch 1.4

When I tried to load ModelNet with the following test code
```
import torch
import torch_sparse
import torch_scatter
a = torch.Tensor([1, 2, 3])
print(len(a))

from torch_geometric.datasets import ModelNet
mn10 = ModelNet("~/data/")
print(len(mn10))
```
After the dataset has been successfully downloaded and processed,  I encountered the following errors:

```
3
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-1f88dfc65aaa> in <module>
      7 from torch_geometric.datasets import ModelNet
      8 mn10 = ModelNet("~/data/")
----> 9 print(len(mn10))

~/toolbox/anaconda3/envs/ml/lib/python3.7/site-packages/torch_geometric/data/dataset.py in __len__(self)
    177         if self.__indices__ is not None:
    178             return len(self.__indices__)
--> 179         return self.len()
    180 
    181     def __getitem__(self, idx):

~/toolbox/anaconda3/envs/ml/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py in len(self)
     61 
     62     def len(self):
---> 63         for item in self.slices.values():
     64             return len(item) - 1
     65         return 0

RuntimeError: Could not run 'aten::values' with arguments from the 'CPUTensorId' backend. 'aten::values' is only available for these backends: [SparseCPUTensorId, VariableTensorId].
```

As seen above, the prerequisites seem to be working. As I am not familiar with custom Op's in PyTorch and new to PyG, I cannot say this is a bug or I haven't put the appropriate libraries together properly. 

Plz advice.

**Comment by rusty1s** [comment]
Well, this does work for me. Can you verify that `self.slices` is a dictionary? And which Python version are you using?

**Comment by junjy007** [comment]
Thanks for the quick reply.

By `self`, you meant for `mn10` in the example, I assume. `mn10.slices` is a `torch.Tensor`, not a `dictionary`:

Running
```
print(type(mn10.slices))
print(mn10.slices)
```
I got the outputs
```
<class 'torch.Tensor'>
tensor([5, 0, 4,  ..., 5, 6, 8])
```

My Python version is 3.7 (note the path `~/toolbox/anaconda3/envs/ml/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py`).

**Comment by rusty1s** [comment]
There is definitely something wrong with your pre-processing, but I am not sure what may be causing this.

**Comment by junjy007** [comment]
The downloading and pre-processing were performed by a `ModelNet` object. I guess the workhorse of formatting the data in a uniform format is `InMemoryDataset.collate()`? I will clean my local cache of the dataset and step in the function.

**Comment by WhatAShot** [comment]
Hi, I get a similar error. I install pytorch1.5 with cuda 101. When I get MNISTSuperpixel, an error:

`RuntimeError: Could not run 'aten::values' with arguments from the 'CPUTensorId' backend. 'aten::values' is only available for these backends: [SparseCPUTensorId, SparseCUDATensorId, VariableTensorId].`

Plz advice. @rusty1s

**Comment by rusty1s** [comment]
Do you know where the error occurs?
